### ISSUE TITLE
Movie not downloaded : English is wanted, but found French 

### ISSUE THREAD

**Issue by Capslock2204** [Radarr/Radarr#1615] opened 2017-06-03 16:35 UTC
Hello,

I've created a new profile, and I had to specify a language, I specified "English" because the majority of the release I see are in english in orginal version (I take only original version with french subtitles).

Today, it was released this : "Moonlight (2016) MULTI VFF Bluray 1080p REMUX AVC DTS-HD MA 5 1" in one of the trackers I follow.
And it was not automatically downloaded because "English is wanted, but found French"

You'll say that I can set "French" in the prefered language, but if I do that, all FGT releases won't be downloaded for the same reason ( "French is wanted, but found English") ...

Is there a way to solve this problem ? Maybe selecting more languages ? Or maybe I'm not using Radarr correctly.

Thanks for your help !

**Radarr Version:**
0.2.0.696

**Comment by galli-leo** [comment] 2017-06-03 22:27
There really isn't a solution to this other than tell your indexers / release groups to correctly include the language tags :/

**Comment by JocPelletier** [comment] 2017-07-19 14:30
A solution would be an option to "Consider MULTI as: Language" like you said in [this comment](https://github.com/Radarr/Radarr/pull/899#issuecomment-293814458)

**Comment by silentmiles** [comment] 2017-12-09 11:38
I'm posting this comment in a few different issues, since there seems to be a lot of overlap. Perhaps these should all be consolidated into a single issue about supporting multiple languages?

Anyway, the core problem here seems to be that the profiles are rigid in requiring the selection of just one language. A lot of people, I think, prefer to always get a movie in it's original language, and use subtitles, so in this case, ANY language is preferred. Others would like to be able to select multiple languages, and even set a priority among them. 

Of course, this logic only works if the movie is tagged with appropriate language tags, but in my experience this is not very common. Non-English movies often do not specify their language. It's been suggested that this is a tracker issue, and that it should be raised with the tracker -- yes, I guess that is right, but with the way trackers are constantly coming and going these days, this is really an impossible solution.

I know that there is a long-term solution being worked on, but couldn't we get an interim solution? I think just NOT requiring a specific language would be at least a partial solution for most people. Surely, just disabling the language matching logic (via a config toggle) would be easy to implement?

**Comment by galli-leo** [comment] 2018-02-06 23:49
Duplicate of #2433

**Closed by galli-leo** 2018-02-06 23:49 UTC
