### ISSUE TITLE
Cant snatch movie with greek language also if title has greek and english title the release get reject

### ISSUE THREAD

**Issue by vlevas** [Radarr/Radarr#5631] opened 2020-12-26 11:04 UTC
**Describe the bug**
radarr v3.0.1.4259

Logs:

i tried to snatch a movie but on my trackers the releases is like this:
The reject is like this: https://prnt.sc/wa8jaj how i can fix that? 
i want to download that release automatic is possible to regexp some way the greek characters or something?
and make the system ignore the non english letter?

Why here doesnt show the greek title? https://prnt.sc/wa8kig

As we can see here the title is on themoviedb https://prnt.sc/wa8l21

can someone tell me how i can make it work ?

**Platform Information (please complete the following information):**
 - OS: [Ubuntu 20.10]
 - Docker: [Yes]
 - Radarr Version 3.0.1.4259
 -

**Comment by bakerboy448** [comment] 2020-12-26 14:38
Duplicate of #5585 
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

look at the screenshot; the movie has two names, the parser is strict, so you need to add both names to TMDB as an alt title

**Closed by bakerboy448** 2020-12-26 14:38 UTC
Labels: bug
