### ISSUE TITLE
Add multiple files to a movie

### ISSUE THREAD

**Issue by tingisinfo** [Radarr/Radarr#7069] opened 2022-02-23 16:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hello,
If possible, I would like you to add a new feature,
it is possible to add multiple files to a movie? so you can easily know if there are duplicates and also choose the quality you want to leave and delete the others.
Thank you for your work you are doing a great job

### Describe the solution you'd like

Hello,
If possible, I would like you to add a new feature,
it is possible to add multiple files to a movie? so you can easily know if there are duplicates and also choose the quality you want to leave and delete the others.
Thank you for your work you are doing a great job

### Describe alternatives you've considered

Hello,
If possible, I would like you to add a new feature,
it is possible to add multiple files to a movie? so you can easily know if there are duplicates and also choose the quality you want to leave and delete the others.
Thank you for your work you are doing a great job

### Anything else?

Hello,
If possible, I would like you to add a new feature,
it is possible to add multiple files to a movie? so you can easily know if there are duplicates and also choose the quality you want to leave and delete the others.
Thank you for your work you are doing a great job

[AB#2655](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2655)

**Comment by bakerboy448** [comment] 2022-02-23 16:35
Duplicate of https://github.com/Radarr/Radarr/issues/1910

**Closed by bakerboy448** 2022-02-23 16:35 UTC
Labels: Type: Feature Request, Type: Duplicate
