### ISSUE TITLE
Feature: Add tags from all lists to all movies, independently if it was added by other list

### ISSUE THREAD

**Issue by joshlopes** [Radarr/Radarr#9402] opened 2023-11-14 13:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've a list Trakt Antecipated that adds movies, shouldn't need more clarification. It adds a tag "trakt-antecipated" so I know where my movies are coming from.

I have recently created a custom list that adds movies that are in cinema near me, it should add a tag "in-cinema-near-me" but sadly it doesn't as it seems that tags are only added when a movie is added to the database.

### Describe the solution you'd like

I think lists should add a tag to all movies in that list, despite that movie already existing or not in the database. So I can create "custom filters" based on that list tag. 

This allow people to create custom filters or more lists to add more tags to existing movies and be super flexible in later on filter by those tags. 

E.g.:
 - Have an `Anime movies I want to watch list` adding a `anime-i-love`, then being able to filter by that tag
 - Have an `Kids visiting for xmas movies list` adding a `just-4-xmas` which I know I can remove after xmas season
 - My example, having `in cinema near me` so I can watch the movies that are currently in cinema and when I go to cinema pick ones that are NOT in my media center
 

### Describe alternatives you've considered

I would love to have this feature added to the Radarr by generic, I could even add another option to `remove tag` for when a movie gets OUT of the list but potentially this would be more "annoying" to deal or maybe not is just a disjoint of the current movies with that tag vs the movies in the list.

If Radarr doesn't solve the issue, then I will probably create a script/service that uses RADARR API and adds the tag for me, instead of exporting/creating the custom list, I will just add the API to add the movie if doesn't exist AND add the tag I want in the movie.

### Anything else?

I've create a custom list using an api, just did this yesterday https://github.com/joshlopes/radarr-in-cinemas

**Comment by bakerboy448** [comment] 2023-11-14 13:39
Duplicate of https://github.com/Radarr/Radarr/issues/9004#issuecomment-1678844809

**Closed by bakerboy448** 2023-11-14 13:39 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by joshlopes** [comment] 2023-11-14 15:31
@bakerboy448 they are not the same thing. One wants to automate more than just tagging.

**Comment by bakerboy448** [comment] 2023-11-14 15:44
> Lists are not for updating existing items within Radarr but about adding movies.

> We have discussed that in the past and have no plans on changing that

**Comment by joshlopes** [comment] 2023-11-14 16:22
Where was that discussion so I can read more about it ?

**Comment by bakerboy448** [comment] 2023-11-14 16:23
Internally on discord in the internal team channels.

the consensus has been and is that lists are not to update existing movies

**Comment by joshlopes** [comment] 2023-11-14 16:27
I should add then, you should ask the people that use the software for this sort of feedback -- unless there is a technical issue that prevents to do this -- and if so, it should be mentioned somewhere to be clear -- should be the community deciding whether or not something makes sense to the masses. The fact that two people spent time to open an issue, not so far away in the time, from one another, should point that something could be done there and potentially can be done there.

Anyway appreciate the time. Thank you.
