### ISSUE TITLE
Fix all Indexers for Movies

### ISSUE THREAD

**Issue by galli-leo** [Radarr/Radarr#4] opened 2016-12-29 10:04 UTC
# Indexers to fix:
- [x] Rarbg.to
- [x] HDBits
- [ ] IPTorrents
- [x] Newznab
- [x] Omgwtfnzbs
- [x] PFMonkey
- [ ] TorrentRss (Should work without a problem, not yet tested.)
- [x] Torznab (Works, but when your indexer does not support movie search, falls back to movie title. This is not so much of a problem as the Parser should ensure only the right movie gets downloaded.)
- [x] Wombles
- [x] Fanzub (closed)

**Comment by galli-leo** [comment] 2016-12-29 21:58
@fedoranimus The rarbg.to indexer was only searching in the TV shows category. I thought it was the same for the other indexers. Nevertheless, all indexers should be tested to work with movies.

**Comment by fedoranimus** [comment] 2016-12-29 22:00
I agree they all need to be tested. I think most of them have a comma-separated "Category" input box which is user-customizable.

**Comment by brianmbutler** [comment] 2017-01-04 01:42
Wombles is shut down so you can check that off.

http://www.newshost.co.za

**Comment by brianmbutler** [comment] 2017-01-04 16:54
I couldn't get NZBGeek (which is newznab) to work, possibly user error.   I did notice you need to go into Advanced Settings and change the categories because it defaults to TV.   Movies are:

2020 - Movies/Other
2030 - Movies/SD
2040 - Movies/HD
2050 - Movies/BluRay
2060 - Movies/3D

**Comment by fedoranimus** [comment] 2017-01-04 17:04
@brianmbutler The usenet indexers are not working at the moment - I'm looking into them.

Thanks for the categories - I've changed most of them on my local machine for the custom newznab.

**Comment by brianmbutler** [comment] 2017-01-04 17:05
No problem.  Trying to help test where I can because I don’t know any C#/.net

**Comment by fedoranimus** [comment] 2017-01-04 17:23
Yup, very much appreciated!

**Comment by AeonLucid** [comment] 2017-01-04 17:31
@fedoranimus  All available categories can be found here http://newznab.readthedocs.io/en/latest/dev/lib/category/.

**Comment by fedoranimus** [comment] 2017-01-04 20:56
#23 fixes Newznab

**Comment by brianmbutler** [comment] 2017-01-04 21:48
Thanks, will test next release.

**Comment by wkupike2000** [comment] 2017-01-05 21:15
Can DOGnzb, NZB.su, NZBCat, and SimplyNZB be added? those are popular ones supported in Sonarr and that I use to find movies often manually. Thanks!

**Comment by fedoranimus** [comment] 2017-01-05 21:16
If they're supported in Sonarr, we will be supporting them in Radarr as well.

Most of the nzb indexers fall under Newznab.

**Comment by edru** [comment] 2017-01-05 21:19
The categories are universal usenet - if you just use 2000 it should search all of "movies" as a whole.

**Comment by wkupike2000** [comment] 2017-01-05 21:29
And here I thought I was pretty Savvy with this stuff but definitely not
haha. I've been running a Plex server with Usenet and torrents for about a
year pretty efficiently. But I'd be lying if I told you I knew anything
about newznab or what you mean about searching using 2000.  Most of my
downloads come from the indexers but that's from in putting them one by one
into the programs.

**Comment by AeonLucid** [comment] 2017-01-05 21:33
@wkupike2000 I've tested DOGnzb and NZBCat. Both work.

**Comment by wkupike2000** [comment] 2017-01-07 19:27
Thanks, DOGnzb, NZBgeek and NZB.su work but NZBCat gives me an error when
trying to add it.

**Comment by AeonLucid** [comment] 2017-01-07 19:44
@wkupike2000 I had the same issue, submitting a fix now which makes it work for me.

**Comment by donldmn** [comment] 2017-01-10 03:47
PFMonkey does not seem to work for me.

**Comment by onedr0p** [comment] 2017-01-10 09:38
HDBits need testing, I fixed it but cannot test due to lack of an account.

**Comment by Fossil01** [comment] 2017-01-10 15:08
I don't think this should list TV Categories:

https://github.com/galli-leo/Radarr/blob/develop/src/NzbDrone.Core/Indexers/Newznab/Newznab.cs#L46

Should it list seperate categories or does removing them cause it to look into the normal Newznab cats? Category 2000-2999

**Comment by onedr0p** [comment] 2017-01-10 21:26
Wombles still appears to be up:

http://newshost.co.za/rss/?sec=Movies&fr=false

**Comment by derik0709** [comment] 2017-01-10 21:50
PFMonkey is not working for me either.

**Comment by subzero79** [comment] 2017-01-10 22:17
Using torznab in [cardigann](https://github.com/cardigann/cardigann) is not working either

This is the trace error

```
17-1-10 21:28:17.3|Trace|HttpClient|Req: [GET] http://10.10.10.12:5060/torznab/alpharatio/api?t=caps&apikey=(removed)
17-1-10 21:28:17.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-10 21:28:17.3|Trace|HttpClient|Res: [GET] http://10.10.10.12:5060/torznab/alpharatio/api?t=caps&apikey=(removed) 200.OK (2 ms)
17-1-10 21:28:17.3|Trace|HttpClient|Req: [GET] http://10.10.10.12:5060/torznab/alpharatio/api?t=caps&apikey=(removed)
17-1-10 21:28:17.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-10 21:28:17.3|Trace|HttpClient|Res: [GET] http://10.10.10.12:5060/torznab/alpharatio/api?t=caps&apikey=(removed) 200.OK (1 ms)
17-1-10 21:28:17.3|Warn|Torznab|Unable to connect to indexer

[v0.2.0.45] System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0006c] in <63992662b765477a898ef49cdcc99ee2>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0001a] in <e39287ceff6c4c74b2e9f62acd6fe53d>:0 

17-1-10 21:28:17.3|Trace|HttpClient|Req: [GET] http://10.10.10.12:5060/torznab/alpharatio/api?t=caps&apikey=(removed)
17-1-10 21:28:17.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-10 21:28:17.3|Trace|HttpClient|Res: [GET] http://10.10.10.12:5060/torznab/alpharatio/api?t=caps&apikey=(removed) 200.OK (0 ms)
17-1-10 21:28:17.3|Trace|NzbDroneErrorPipeline|Handling Exception
17-1-10 21:28:17.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-1-10 21:28:17.3|Trace|Http|Res: 38 [POST] /api/indexer/test: 400.BadRequest (38 ms)
17-1-10 21:28:17.3|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (38 ms)
```

**Comment by Anijake** [comment] 2017-01-10 22:25
[logs.zip](https://github.com/Radarr/Radarr/files/697541/logs.zip)


Trying to get this working with nzbs.in, a newznab indexer

**Comment by fryfrog** [comment] 2017-01-11 20:19
I was able to successfully add Dognzb.cr, NZBgeek, omgwtfnzbs (newznab), OZnzb and anizb.

Not working are: Miatrix, PFmonkey, SickBeard and Usenet-Crawler.

Would it be helpful to post some logs?

**Comment by onedr0p** [comment] 2017-01-11 20:30
My post from the other issue.

I did some more investigations it appears that usenet-crawler and newztown (possibly others) don't support searching for movies, they do support searching for TV series hence it works with Sonarr.
`<movie-search available="no" supportedParams="q" />`

A couple things, Maybe contact the staff of those sites and see if they will turn it on or set up NZBHydra to get those working with Radarr.

**Comment by smidley** [comment] 2017-01-12 17:31
PFM is still not working for me either.

**Comment by onedr0p** [comment] 2017-01-12 17:39
Again, this is not a issue we can solve. Please get in touch with you indexers staff and ask them if they can add the following flag to their `/api?t=caps` RSS feed.

`<movie-search available="yes" supportedParams="q,imdbid"/>`

Thanks.

**Comment by breadcan** [comment] 2017-01-12 19:05
dognzb has a uhd movie category 2045

**Comment by edru** [comment] 2017-01-12 20:46
Everyone should be aware that the categories have NOTHING to do with the
indexers. They are categories within usenet the indexers are.. well....
indexing. There is an image that breaks it down a bit, though its dated:
https://i.imgur.com/uxkRpfc.jpg

In essence you can search all of category "2000" which is just simply all
of "movies", which includes EVERYTHING within the 2000's - 2010, 2020,
2040, and so on. So its not that "dognzb" has it's own specific category
that no one else does, they just bother to actually list it apart from "HD"
which houses "UHD" allowing it to be a bit more granular.

Within Sonarr, I literally just search category "5000, 8000" for all of TV
and all of "Other" as some documentaries get posted there, and sometimes TV
on accident.

Id recommend searching just "2000, 8000" for the same reason. The indexers
should default automatically to search ALL MOVIES, be it SD/UHD/HD/3D as
well as "Other" in case it made its way there. Going any granular only
limits what you are searching, and is honestly only good to AVOID specific
qualities.

**Comment by onedr0p** [comment] 2017-01-12 20:56
@smidley PFM will work now.

@edru I think we can just  drop 2000 in their by default, 8000 can be optional.

**Comment by Enver-Adams** [comment] 2017-01-12 21:32
Hello,

Just recently signed up to https://www.nzb-tortuga.com with a VIP account to get API access. The API feature works great in Sonarr, however for some reason the same API information fails on Radarr!? It fails to connect.

System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0006c] in <63992662b765477a898ef49cdcc99ee2>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0001a] in <f7444edbf1a84c5d9823504fa7d67cc4>:0 


Can anyone provide any advice? I have tried changing the Category to 2000, but I  get the same error.

**Comment by onedr0p** [comment] 2017-01-12 22:06
@Enver-Adams https://github.com/Radarr/Radarr/issues/4#issuecomment-272230066

We will provide a better error for that exception.

**Comment by magicdude4eva** [comment] 2017-01-13 12:16
Is NZBHydra supported?

**Comment by schumi2004** [comment] 2017-01-13 12:29
@magicdude4eva Hydra works perfect

**Comment by onedr0p** [comment] 2017-01-13 13:28
Hydra works here :)

**Comment by wkupike2000** [comment] 2017-01-13 19:36
@edru Few days late as I've been away from my setup. When I enter just 5000, 8000 into my indexers for Sonarr, some work and some the Test function fails. Dog and NzbCat both failed. And for Radarr, you're recommending inputting 2000, 8000 I think. I'm all about opening up searches to find more of my missing so appreciate the help/guidance.

**Comment by onedr0p** [comment] 2017-01-14 16:57
Closing this issue, we can handle independent indexer requests in separate issues.

**Closed by onedr0p** 2017-01-14 16:57 UTC
Labels: bug, indexer, priority:medium

**Comment by edru** [comment] 2017-02-06 16:23
Nzbgeek working fine for me

**Comment by xybydy** [comment] 2017-02-09 07:40
Yify Torrent is pretty good for movies. Has better seeder performance than rarbg.
Hope you add it to indexers.

[https://yts.ag/](https://yts.ag/)

**Comment by dedepene** [comment] 2017-02-11 09:24
I can confirm that hdbits works. Not sure if this is the place for a request, but it will be awesome if we can pick hdbits internal releases as a (cutoff) quality.

**Comment by Enver-Adams** [comment] 2017-02-26 09:50
Hi onedr0p,

I posted your comments suggesting the error in adding an index to RADARR was an issue on the indexer end.
Unfortunately their testing seems to indicate its a bug in RADARR. I would have to agree with their analysis please see below.
I have taken on onboard their suggestion and it works, it does seem like its a bug in RADARR.

Admin Response Extract:
he API structure that indexing sites uses is quite generic and is compatible with major the applications like,

Nzb 360
Sonarr
XBMC
NZBGet
Couch Potato
SickBeard 
Sabnzbd

I will take a look at this Radarr later and do some testing and get back to you if i find anything - but i am not convinced that its an issue with the API structure more like an issue with the application, as you said above it works fine with Sonarr and i can see many other clients connecting each day.
I downloaded this radarr and did some testing, i managed to get it to work by defining the full api path it was looking for...

i.e. url

https://nzb-tortuga.com/api?t=movie&cat=2030,2040

or

http://api.nzb-tortuga.com/api?t=movie&cat=2030,2040

for info movie cat ids are...

2010	Foreign	Movies	
2020	Other	Movies	
2030	SD	Movies	
2040	HD	Movies	
2045	UHD	Movies	
2050	BluRay	Movies	
2060	3D	Movies

TV

5020	Foreign	TV	
5030	SD	TV	
5040	HD	TV	
5045	UHD	TV	
5050	Other	TV	
5060	Sport	TV	
5070	Anime	TV	
5080	Documentary	TV	

Note i is only for Radarr and its an application issue they need to fix...

Happy to help

Regards
Nzb Tortuga

**Comment by DariusIII** [comment] 2017-03-24 13:03
For sites based on nZEDb/NNTmux category strucrure is listed here: https://github.com/nZEDb/nZEDb/blob/0.x/docs/newznab_api_specification.txt

 

>  Categories                           Category Name
> 
>    0000                                 Other                           All of Other
>    0010                                 Other/Misc                      Anything that could not get categorized
>    0020                                 Other/Hashed                    Anything with a hashed name
>    1000                                 Console                         All of console
>    1010                                 Console/NDS                     Nintendo DS
>    1020                                 Console/PSP                     Sony Playstation Portable
>    1030                                 Console/Wii                     Nintendo Wii
>    1040                                 Console/Xbox                    Microsoft XBox
>    1050                                 Console/Xbox 360                Microsoft XBox 360
>    1060                                 Console/Wiiware/VC              Wii homebrew
>    1070                                 Console/XBOX 360 DLC            Microsoft XBox 360 Downloadable Content
>    1080                                 Console/PS3                     Playstation 3
>    1999                                 Console/Other                   Misc Console
>    1110                                 Console/3DS                     Nintendo 3DS
>    1120                                 Console/PS Vita                 Playstation Vita
>    1130                                 Console/WiiU                    Nintento Wii U
>    1140                                 Console/Xbox One                Xbox One
>    1180                                 Console/PS4                     Playstation 4
>    2000                                 Movies                          All of movies
>    2010                                 Movies/Foreign                  Non english movies
>    2020                                 Movies/Other                    Misc movies
>    2030                                 Movies/SD                       Standard definition movies
>    2040                                 Movies/HD                       High definition movies (720p+)
>    2050                                 Movies/3D                       3D movies
>    2060                                 Movies/BluRay                   Full BR movies
>    2070                                 Movies/DVD                      Full DVD movies
>    2080                                 Movies/WEBDL                    WEB-DL movies
>    3000                                 Audio                           All of audio
>    3010                                 Audio/MP3                       Mp3 music
>    3020                                 Audio/Video                     Music videos
>    3030                                 Audio/Audiobook                 Books in audio format
>    3040                                 Audio/Lossless                  Lossless music
>    3999                                 Audio/Other                     Misc music
>    3060                                 Audio/Foreign                   Non english music.
>    4000                                 PC                              All of PC
>    4010                                 PC/0day                         Apps and games not released in ISO.
>    4020                                 PC/ISO                          CD-ROM images/DVD Images
>    4030                                 PC/Mac                          OS X apps and games
>    4040                                 PC/Phone-Other                  Misc mobile phone software
>    4050                                 PC/Games                        PC Games
>    4060                                 PC/Phone-IOS                    IOS apps
>    4070                                 PC/Phone-Android                Android apps
>    5000                                 TV                              All of TV
>    5010                                 TV/WEB-DL                       WEB-DL TV
>    5020                                 TV/FOREIGN                      FOREIGN TV
>    5030                                 TV/SD                           SD TV
>    5040                                 TV/HD                           HD TV
>    5999                                 TV/OTHER                        Other TV Content
>    5060                                 TV/Sport                        Sports
>    5070                                 TV/Anime                        Anime
>    5080                                 TV/Documentary                  Documentaries
>    6000                                 XXX                             All of XXX
>    6010                                 XXX/DVD                         Full DVD's
>    6020                                 XXX/WMV                         WMV rips
>    6030                                 XXX/XviD                        dvdrips
>    6040                                 XXX/x264                        HD Porn
>    6999                                 XXX/Other                       Misc Porn
>    6060                                 XXX/Imageset                    Sets of porn images
>    6070                                 XXX/Packs                       Packs of multiple porn videos
>    7000                                 Books                           All of Books
>    7010                                 Books/Magazines                 Magazines
>    7020                                 Books/Ebook                     Ebooks
>    7030                                 Books/Comics                    Comics Ebooks
>    7040                                 Books/Technical                 Technical books
>    7060                                 Books/Foreign                   Non english books
>    7999                                 Books/Unknown                   Misc books
>    100000+                              Custom                          Specific to a site

**Comment by ksya** [comment] 2017-05-03 18:36
@galli-leo, I use PassThePopcorn a lot. Is it possible to add this indexer again?

**Comment by galli-leo** [comment] 2017-05-03 18:56
@ksya It's already added?

**Comment by dr0pd34d** [comment] 2017-06-04 08:24
Hello there, thank you for developing such a great movie tool, i love it!
Would it be possible to add
binsearch.info
or
nzbindex.nl
as Indexers?

Thank you :)

**Comment by endquote** [comment] 2017-09-30 16:07
@fryfrog how did you add oznzb?

**Comment by brianmiller** [comment] 2017-10-10 19:33
Just installed Radarr Ver. 0.2.0.870 today.  nzbplanet doesn't seem to work.

**Comment by theimmortal68** [comment] 2017-11-20 21:12
Is there any progress on getting IPTorrents to work?  Is there anything I can do to help move this along (ie. invite).
