### ISSUE TITLE
Borrow sonarr "release group" sorting

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#8715] opened 2023-06-19 10:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sort all movies by release group.

### Describe the solution you'd like

Above.

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by Silent-Remux** [comment] 2023-06-19 10:34
> You need to be more specific, where and what, because you're mixing sorting with filtering.

On the main table view. Custom filters, add custom filter, can't pick relative path contains X for example.

**Comment by bakerboy448** [comment] 2023-06-19 17:28
Duplicate of https://github.com/Radarr/Radarr/issues/7919

no near term plans for any ability to filter or sort by movie file properties on the movie index

**Closed by bakerboy448** 2023-06-19 17:28 UTC
Labels: Type: Feature Request, Status: Needs Triage
