### ISSUE TITLE
New update is redownloading everything!!

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#1151] opened 2017-03-13 08:20 UTC
**Description:**

Updated to latest and now everything is re-downloading, even if i already have it. See screenshots below. 

**Radarr Ver. 0.2.0.535**

![image](https://cloud.githubusercontent.com/assets/18261123/23846316/2487c758-078a-11e7-98a8-031accbb20ad.png)

Lets take an example of "The Dark Knight Rises"

![image](https://cloud.githubusercontent.com/assets/18261123/23846348/475ce8ee-078a-11e7-9e4c-7bca26fca501.png)

i just updated the app and as you can see it's just grabbing and adding to my SAB client

![image](https://cloud.githubusercontent.com/assets/18261123/23846416/97945770-078a-11e7-8847-275c03bc7624.png)

I had to go and pause SAB and manually go and unmonitor everything it has sent to SAB, and then delete it from my SAB queue.  This is not good at all. 

This may affect anyone who bulk added their whole library to Radarr.

**Comment by galli-leo** [comment] 2017-03-13 09:05
Do you see anything in the logs?

**Comment by uffcd** [comment] 2017-03-13 09:26
Maybe a change in lists processing?

NetImportSearchService     Found 83 movies on your auto enabled lists not in your library

But its adding movies already on hdd with status downloaded

**Comment by mgladwin** [comment] 2017-03-13 09:35
not related to this problem directly but i just updated to latests develop branch release and now im stuck on the radarr loading page with the white circles going back and forth after clicking reload radarr.

**Comment by madvtak** [comment] 2017-03-13 09:43
Here's the latest log, even more have been added after that first bulk download. Same result, movies I already have marked as download re-downloading. 


![image](https://cloud.githubusercontent.com/assets/18261123/23848967/b04fc1da-0796-11e7-8ea3-f101035b0ea0.png)

**Comment by madvtak** [comment] 2017-03-13 09:45
I'm just going to unmonitor every single movies thats marked as downloaded. Not the fix i want, but just now there was 200GB+ files in SAB downloading.

**Comment by madvtak** [comment] 2017-03-13 09:56
i don't even have "how to train your dragon" on any of my lists and its just sending to SAB. 

![image](https://cloud.githubusercontent.com/assets/18261123/23849367/96f6bae8-0798-11e7-93ce-72310f765d73.png)

**Comment by madvtak** [comment] 2017-03-13 10:00
I turned off every single list, just in case its adding from there.

**Comment by madvtak** [comment] 2017-03-13 10:07
All the upcoming movies are now showing this.

![image](https://cloud.githubusercontent.com/assets/18261123/23849770/067d160e-079a-11e7-96e7-cd07da94abdd.png)

Lets pick Patriots day on March 27th

It Begins to load......
![image](https://cloud.githubusercontent.com/assets/18261123/23849791/1d32cc5e-079a-11e7-84dd-196b1a50cee6.png)

![image](https://cloud.githubusercontent.com/assets/18261123/23849806/2da4e7f2-079a-11e7-8c79-4d74b0bff95d.png)

**Comment by madvtak** [comment] 2017-03-13 10:19
When I try to re-add patriots day, its says its already added. But i no longer can search for it in the top search bar. Even though it says "This movie has already been added" 

![image](https://cloud.githubusercontent.com/assets/18261123/23850202/a275ff0c-079b-11e7-9069-6cdfa5717d0e.png)

Here's the log for that

![image](https://cloud.githubusercontent.com/assets/18261123/23850251/e05b0c4a-079b-11e7-91b4-7660c505043f.png)

**Comment by madvtak** [comment] 2017-03-13 10:21
It is now only showing me movies that I already have already downloaded. 

![image](https://cloud.githubusercontent.com/assets/18261123/23850308/173d8116-079c-11e7-80e0-00424255fd8b.png)

**Comment by astlaurent** [comment] 2017-03-13 12:24
Same thing happened to me. I had the following lists enabled: stevenlu, trakt anticipated, trakt trending. It seems that the trending one imported a boat load of movies which all started downloaded for me, some of which i already had but not imported into radarr yet so i guess it really didn't know. i had to cancel everything out, delete all the movies if i did not want them. I removed that import list. The other ones are small and mostly movies that are not released yet or in the theaters so i do not think they caused much harm if they freaked out as well. Maybe something with trakt scores because a lot of these movies that were downloaded i would think would be very low on the trending

**Comment by onedr0p** [comment] 2017-03-13 13:53
I believe this is a duplicate of https://github.com/Radarr/Radarr/issues/1108

**Comment by onedr0p** [comment] 2017-03-13 14:00
@galli-leo this might be the cause?

https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/NetImport/NetImportSearchService.cs#L117

This searches movies as they are imported from lists, but it should exclude those already in their Radarr library.

**Comment by galli-leo** [comment] 2017-03-13 14:32
I don't see anything inherently wrong with that code on my phone. But you probably want an option to set that per list. Also shouldn't the AddMovieOptions be enough for a search?

**Comment by onedr0p** [comment] 2017-03-13 15:40
I plan on that being a settings in the list options in the future. And the addmovieoptions aren't good enough by themselves to start a search. I tried, you need both..

**Comment by onedr0p** [comment] 2017-03-13 22:04
@madvtak any clue where those movie downloads originated from, like, what task?

**Comment by madvtak** [comment] 2017-03-14 05:04
@onedr0p it looks like it was from one of my lists "trak.tv popular movies" It hasn't done this before, but it started to add and download all of them.  It could be be possible that something in the new update forced a search and grab and send to my usenet client.

**Comment by onedr0p** [comment] 2017-03-14 12:15
A recent update will disable searching for movies on list sync for now until we figure it out

**Comment by wolffstarr** [comment] 2017-03-15 02:29
Wanted to provide some potentially useful information about this. When I first moved over to Radarr a few days ago, I did the bulk import and set about cleaning up the mis-identified movies. One of the ones that I brought in was Legend, the Tom Cruise and Tim Curry movie from 1985. Radarr identified it as a 2015 movie I'd never heard of, also called Legend. As this was the wrong movie, I deleted the entry, manually added it back in, and went about the rest of it.

Yesterday, when I realized that it was adding movies at random, I paused SABnzbd and cleared it, but I noticed that the 2015 version of Legend was one of the movies it had sent to download. I went into Radarr to see if it had been re-added, or if I'd not deleted it properly, but it was not there.

As another note, when these movies show up in the queue on my downloader, there is NO entry for them on the Activity page - usually there's no entries on the page at all - and no icon indicating a download. They are, however, showing up in the History tab of a given movie. Had it happen with Pacific Rim earlier today, and it still had it in there. I switched to the Nightly builds after I stopped that.

**Comment by 1activegeek** [comment] 2017-03-15 18:23
Is it possible to check the status in the list on Trakt as well? I just ran into this issue, but unfortunately I hadn't gotten around to using the new bulk import to start importing hundreds of movies. As I was getting into doing so, I noticed it suddenly started scanning and importing all these movies I had. It was causing some to show the disabled indicating a duplicate. Took a bunch of stopping restarting correcting and cleaning to fix. But I think I'm stable now. 

For me, this could have been solved if it checked/validated the status in Trakt. CP had sync setup to notify Trakt when it downloaded to "add to collection". It would be great to see this sync (I know side topic) but it could be useful in most cases to validate this as well. It would have easily eliminated the import list down to a mere 25 or so unreleased movies vs the whole list I'd ever added to Trakt (including movies I've since deleted or removed from my collection).

Alternatively, could there be a check put in to see the date added to the list? I'm guessing here as I'm not sure if that info is available, but if possible - maybe if the date of the add was prior to todays date, then don't add. Or something shorthanded like within 30 days or something. Just to leave a sanity check and ensure someone doesn't get bombarded with their whole watchlist history from forever? 

Just my two cents. And keep up the awesome work, Radarr has worked (minus instances like this) pretty flawlessly.

**Comment by galli-leo** [comment] 2017-04-15 10:20
Can you guys confirm that this issue is still happening on the latest release?

**Comment by astlaurent** [comment] 2017-04-15 22:46
I have not seen the problem since the original incident.

**Comment by 1activegeek** [comment] 2017-04-15 23:56
I haven't seen the issue, but honestly I don't want to be the guinea pig to TRY and test it out. 😛

**Closed** 2017-04-17 10:02 UTC
Labels: bug, cannot reproduce, priority:high
