### ISSUE TITLE
[Fearture request] Automation  like couchpotato

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#220] opened 2017-01-13 06:18 UTC
Please add the Automation like Couchpotato does.

**Comment by woble** [comment] 2017-01-13 07:44
Might be related to #139

**Comment by galli-leo** [comment] 2017-01-13 07:58
Can you be a bit more specific?

**Comment by SJ50** [comment] 2017-01-13 08:17
It adds movie to wanted list if requirement is fulfilled.

![IMDB](http://i.imgur.com/A5RaBPV.png)
![requirements](http://i.imgur.com/2wm8iDr.png)

**Comment by SJ50** [comment] 2017-01-13 08:18
Please also add language option in requirements as well, so it adds movie from certain language only added to wanted list.

**Comment by galli-leo** [comment] 2017-01-13 08:24
Duplicate of #114 please comment on there if you have more suggestions.

**Closed by galli-leo** 2017-01-13 08:24 UTC
