### ISSUE TITLE
Unable to communicate with deluge. Cannot combine OsPaths of different platforms

### ISSUE THREAD

**Issue by paulombsd** [Radarr/Radarr#2386] opened 2018-01-01 17:47 UTC
Hello guys, 

I'm having a strange issue: Unable to communicate with deluge. Cannot combine OsPaths of different platforms ('/srv/Download/temp_files' + 'The Orphanage (2007) \"El Orfanato\" 1080p BluRay HEVC x265-n0m1')
since then, I've got 243 files moved to my movies path while other 4k files are just sitting there, at the deluged completed folder.
By the way, I'm running ubuntu server 16.04 and I'm using the mono ppa developed by the mono dudes.

The error log has been attached to this message. Thanks for your time and awesome software and Happy new year! LOL

[radarr_error_log.txt](https://github.com/Radarr/Radarr/files/1596270/radarr_error_log.txt)

**Comment by seanvree** [comment] 2018-01-03 20:16
Yeah, I'm getting this issue too. 

OS:  Windows 10E x64 1709
Deluge: 1.3.15
Radarr Ver. 0.2.0.912

**Comment by galli-leo** [comment] 2018-02-07 15:38
The problem are the backslashes in the filename.

Duplicate of #1761

**Closed by galli-leo** 2018-02-07 15:38 UTC
