### ISSUE TITLE
Support for collection/subfolder

### ISSUE THREAD

**Issue by Kedryn** [Radarr/Radarr#4174] opened 2020-02-20 10:57 UTC
**Is your feature request related to a problem? Please describe.**
Radarr seems to not be able to detect movies nested on one level deeper than the root, as all other softwarese for library management or media servers do.
For example, i can have a "007 collection" folder with all the 007 movies in their subfolders. Radarr does not scan them. MCM does. Plex does. Kodi does. 

**Describe the solution you'd like**
Import movies on level deeper from the root when the folder does not contain any movie but has subfolders.

**Comment by ta264** [comment] 2020-02-20 16:35
Duplicate of #153 #1170

**Closed by ta264** 2020-02-20 16:35 UTC
Labels: feature request
