### ISSUE TITLE
Import, Recursively search sub-folders for movies

### ISSUE THREAD

**Issue by MartinR577** [Radarr/Radarr#7946] opened 2022-12-31 12:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be nice if you allowed the option to scan folders and include subfolders.  
I had organized my movies in folders for the main genre , then a subfolder for movies within a movie collection. each movie is in it's own folder under the movie collection.
Examples

Action
- Indiana Jones
--- 1 Raiders of the Lost Ark (1981)
--- 2 Indiana Jones and the Temple of Doom (1984)
--- 3 Indiana Jones and the Last Crusade (1989
--- 4 Indiana Jones and the Kingdom of the Crystal Skull (2008) 
- James Bond Series
- Sniper Series
- the Bourne series
- The expendable Series
- Transporter series

Or 
SciFi
-Planet of the apes
-Star trek
-Star Wars

the current behavior is Radaar will try to match the folder Indiana Jones with a single movie when there are 4 folders under it with each of the movies
So far it seems i need to include each sub-folder as a root folder which is very time consuming

### Describe the solution you'd like

a check box for Scan sub-folders would be nice. the you could pick the root folder and it would check the subfolders for more movie folders.   

### Describe alternatives you've considered

none

### Anything else?

none

[AB#4592](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4592)

**Comment by bakerboy448** [comment] 2022-12-31 14:06
Duplicate of https://github.com/Radarr/Radarr/issues/1170

**Closed by bakerboy448** 2022-12-31 14:06 UTC
Labels: Type: Feature Request, Type: Duplicate
