### ISSUE TITLE
Export/import Movies by CSV

### ISSUE THREAD

**Issue by DezzyMelb** [Radarr/Radarr#8889] opened 2023-07-28 04:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Yes. I'd like to deploy a new Radarr download client and i need to import my movie lists.

### Describe the solution you'd like

Allow us to export our movie lists and block lists to CSV to allow us to import into a new instance.

### Describe alternatives you've considered

I've used the backup/restore feature and it brings the bugs accross with it. If it was in CSV you can see the data being exported/imported into the system.

### Anything else?

Nope

**Comment by bakerboy448** [comment] 2023-07-28 12:34
Duplicate of numerous issues

this can sheath be done utilizing the api and dove scripting by the user

**Closed by bakerboy448** 2023-07-28 12:34 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by nydave69** [comment] 2023-08-02 15:37
I have been trying to get Radarr to work for well over a year,  again I have had problems, this time it won't reinstall.  But that's another story..  I have used the import but it takes so long just to do a few movies and that screen has to stay open the whole time or it's a no go..   The best I've done is about a 1000 movies and most wind up mis-matched..  All the other apps load all my movies in about 20 mins...  I figure it out that Radarr would tale a little over 9 months 26 days and That is ignoring the mismatches, I know it's not the system, or my network..   Because everything else runs just fine.. So an optional way to load all the movies sounds great, then it just requires cleaning up..

**Comment by bakerboy448** [comment] 2023-08-02 16:09
Please use one of the support channels: [Discord](https://radarr.video/discord) for support/questions.
