### ISSUE TITLE
"Preview rename for movie" not working

### ISSUE THREAD

**Issue by jcchristian** [Radarr/Radarr#274] opened 2017-01-15 00:46 UTC
No matter the movie, if I go to "Preview rename for movie" in order to rename my files it keeps loading eternally. Log:

> [v0.2.0.85] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
>   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40993000 + 0x0013b> in <filename unknown>:0 
> 
> 17-1-15 00:33:40.4|Warn|NzbDroneErrorPipeline|API Error
> 
> [v0.2.0.85] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
>   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40993000 + 0x0013b> in <filename unknown>:0 
> 
> 17-1-15 00:34:12.8|Info|RssSyncService|Starting RSS Sync
> 17-1-15 00:34:24.2|Info|DownloadDecisionMaker|Processing 100 releases
> 17-1-15 00:34:25.7|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
> 17-1-15 00:34:51.7|Warn|NzbDroneErrorPipeline|API Error
> 
> [v0.2.0.85] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
>   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40993000 + 0x0013b> in <filename unknown>:0 
> 
> 17-1-15 00:40:03.1|Info|NzbSearchService|Searching 1 indexers for [The Martian]
> 17-1-15 00:40:12.0|Info|DownloadDecisionMaker|Processing 120 releases
> 17-1-15 00:40:24.9|Warn|NzbDroneErrorPipeline|API Error
> 
> [v0.2.0.85] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
>   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40993000 + 0x0013b> in <filename unknown>:0 
> 
> 17-1-15 00:41:32.8|Info|NzbSearchService|Searching 1 indexers for [The Martian]
> 17-1-15 00:41:41.5|Info|DownloadDecisionMaker|Processing 120 releases
> 17-1-15 00:44:21.1|Warn|NzbDroneErrorPipeline|API Error
> 
> [v0.2.0.85] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
>   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40993000 + 0x0013b> in <filename unknown>:0 
> 
> 17-1-15 00:44:36.8|Warn|NzbDroneErrorPipeline|API Error
> 
> [v0.2.0.85] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
>   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40993000 + 0x0013b> in <filename unknown>:0 
> 
> 17-1-15 00:44:47.9|Warn|NzbDroneErrorPipeline|API Error
> 
> [v0.2.0.85] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
>   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x40993000 + 0x0013b> in <filename unknown>:0

In my case I tried with two movies: The Martian and Paprika.

**Comment by hotio** [comment] 2017-01-15 01:13
I can confirm this is still the case on v0.2.0.139

````
17-1-15 02:11:44.3|Warn|NzbDroneErrorPipeline|API Error

[v0.2.0.139] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
  at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00364] in C:\projects\radarr-usby1\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:34 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x41cf3850 + 0x0014f> in <filename unknown>:0 

17-1-15 02:11:44.3|Debug|Api|[GET] /api/rename??movieId=112: 400.BadRequest (4 ms)
````

**Comment by jcchristian** [comment] 2017-01-15 02:13
Oh yes, didn't even see I was using and outdated version. I updated to 0.2.0.134 - Jan 14 2017 but the issues continues as @hotio said.

**Comment by Peap0d** [comment] 2017-01-15 02:19
This is a duplicate of #84

**Closed** 2017-01-15 02:25 UTC
