### ISSUE TITLE
Travis CI is not enabled

### ISSUE THREAD

**Issue by mitchellcash** [Radarr/Radarr#269] opened 2017-01-14 23:06 UTC
I note we have `.travis.yml` file and even badges in the README, but it seems like https://travis-ci.org/Radarr/Radarr does not exist.

Can one of the maintainers please enable Travis?

**Comment by galli-leo** [comment] 2017-01-14 23:14
Duplicate of #181

**Closed by galli-leo** 2017-01-14 23:14 UTC

**Comment by mitchellcash** [comment] 2017-01-14 23:16
@galli-leo ahh yes, sorry!
