### ISSUE TITLE
Add Macedonian and Slovenian language

### ISSUE THREAD

**Issue by jure3000** [Radarr/Radarr#10370] opened 2024-08-27 08:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Can you please add Macedonian and Slovenian language? It is already available in Sonarr, but not yet in Radarr.

### Describe the solution you'd like

Please add languages, in Sonarr, it is defined:

public static Language Macedonian => new Language(45, "Macedonian");
        public static Language Slovenian => new Language(46, "Slovenian");

### Describe alternatives you've considered

/

### Anything else?

/

**Comment by bakerboy448** [comment] 2024-08-27 10:46
Duplicate of https://github.com/Radarr/Radarr/issues/8302

**Closed by bakerboy448** 2024-08-27 10:46 UTC
Labels: Type: Feature Request, Status: Needs Triage
