### ISSUE TITLE
Sort Order Incorrect?

### ISSUE THREAD

**Issue by clambert11** [Radarr/Radarr#340] opened 2017-01-19 02:26 UTC
Currently running Version 0.2.0.182.

The sort order when performing a manual search is different than Sonarr.  Sonarr sorts all by age, newest to oldest. Radarr seems to search by Source and then Age, newest to oldest.  I then have to resort by clicking on the Age column.  Not a huge deal but I prefer the way Sonarr sorts by default.  If Radarr sorts the way it does by design then don't worry about it.  It's more just personal preference than anything.

**Comment by vertigo235** [comment] 2017-01-19 02:53
There was an issue but it should be resolved in the 182 version you have. 

It should sort by quality first then age/peers for usenet/torrent. Or at least mostly.

**Comment by galli-leo** [comment] 2017-01-19 08:12
This is by design. It should first sort the way the auto download system prioritizes downloads. This way you can see what Radarr thinks is the best release.

**Closed by galli-leo** 2017-01-19 08:12 UTC

**Comment by clambert11** [comment] 2017-01-19 11:55
Either I didn't communicate my problem well enough or we have a difference of opinion.  For me it was sorting source first and then by date.  So a 30 day torrent release was listed before a 2 day nzb release.  Right now my I'm apparently having issues connecting to my nzb indexer so I can't confirm how it's operating for me today.

If this is sorting is by design, don't worry about it.  You are the developer and you need to create it the way you want it. At least I have the flexibility to sort the release by age, so I'll deal.

**Comment by clambert11** [comment] 2017-01-19 23:56
Just an update.  The sort order looks more like what I would expect.  I'm not sure why I didn't see it when I did (I was on 182) but the fix that Vertigo235 mentioned must have fixed my problem.  Thanks.
