### ISSUE TITLE
size limitations

### ISSUE THREAD

**Issue by jscottdouglas** [Radarr/Radarr#1125] opened 2017-03-11 17:26 UTC
**Description:**
Can more size limitation be put in right now it goes from 15gb to unlimited, I want to limit the filesizes to 50G can these be added?

**Radarr Version:** 

Latest nightly

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment] 2017-03-11 18:28
If you need right now, you can edit the quality definitions via the api. You are allowed to set them to anything there.

**Comment by galli-leo** [comment] 2017-03-11 18:33
Also duplicate of #978

**Closed** 2017-03-11 22:07 UTC
Labels: feature request
