### ISSUE TITLE
Do not clean non-alphanumeric symbols in search

### ISSUE THREAD

**Issue by megatron1092** [Radarr/Radarr#5973] opened 2021-02-26 11:17 UTC
**Is your feature request related to a problem? Please describe.**
I'm unable to download some releases from some unique trackers. I inspected debug logs - search query doesn't have ":" symbol, so indexer search is failed. This occurs on the unique Russian 4k tracker. So I'm unable to cutoff to the maximum possible quality. If I manually add ":" to the search query, the search is successful

**Describe the solution you'd like**
Enable tick to disable/enable cleaning of non-alphanumeric characters.

**Describe alternatives you've considered**
Or you can point where's that logic located - I'd implement it in forked version

**Comment by bakerboy448** [comment] 2021-02-26 13:30
Duplicate of #5628

**Closed by bakerboy448** 2021-02-26 13:30 UTC
Labels: feature request

**Comment by megatron1092** [comment] 2021-02-26 14:46
Ok. I've found it myself :)
