### ISSUE TITLE
Download Station Error with DSM 7.0 Beta

### ISSUE THREAD

**Issue by behold81** [Radarr/Radarr#5567] opened 2020-12-17 11:51 UTC
Since upgrading to DSM 7.0 beta intergration with Downloadstation fails. 

This is reported on Sonarr but not getting any movement and to be honest I use it more on Radarr. 

Alert is: Unable to communicate with SynoDS. Failed to login. Reason: The requested method does not exist

>

>  2020-12-17 11:49:10.5|Debug|TorrentDownloadStation|Download Station api version information: Min 1 - Max 3
> 2020-12-17 11:49:10.5|Debug|DownloadStationInfoProxy|Trying to login
> 2020-12-17 11:49:10.5|Error|DownloadStationInfoProxy|Failed to login. Reason: The requested method does not exist
> 2020-12-17 11:49:10.5|Error|TorrentDownloadStation|Error testing Torrent Download Station
> 
> [v3.0.1.4259] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 140
>    at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, DiskStationApiInfo apiInfo, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 163
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationInfoProxy.GetConfig(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationInfoProxy.cs:line 22
>    at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.GetDefaultDir() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:line 439
>    at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.TestOutputPath() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:line 311
> 
> 
> 2020-12-17 11:49:10.5|Debug|DownloadStationTaskProxy|Trying to login
> 2020-12-17 11:49:10.5|Error|DownloadStationTaskProxy|Failed to login. Reason: The requested method does not exist
> 2020-12-17 11:49:10.5|Error|DownloadStationTaskProxy|NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 140
>    at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, DiskStationApiInfo apiInfo, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 163
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxy.GetTasks(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationTaskProxy.cs:line 56
> 
> [v3.0.1.4259] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 140
>    at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, DiskStationApiInfo apiInfo, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 163
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DownloadStationTaskProxy.GetTasks(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DownloadStationTaskProxy.cs:line 56
> 
> 
> 2020-12-17 11:49:10.6|Debug|DSMInfoProxy|Trying to login
> 2020-12-17 11:49:10.6|Error|DSMInfoProxy|Failed to login. Reason: The requested method does not exist
> 2020-12-17 11:49:10.6|Warn|SerialNumberProvider|Could not get the serial number from Download Station xxx.xxx.xxx:xxxx
> 
> [v3.0.1.4259] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to login. Reason: The requested method does not exist
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 93
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.AuthenticateClient(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 140
>    at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.BuildRequest(DownloadStationSettings settings, DiskStationApiInfo apiInfo, String methodName, Int32 apiVersion, HttpMethod httpVerb) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 163
>    at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DSMInfoProxy.GetSerialNumber(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DSMInfoProxy.cs:line 22
>    at NzbDrone.Core.Download.Clients.DownloadStation.SerialNumberProvider.GetHashedSerialNumber(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\SerialNumberProvider.cs:line 45
>    at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 114
>    at NzbDrone.Core.Download.Clients.DownloadStation.SerialNumberProvider.GetSerialNumber(DownloadStationSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\DownloadStation\SerialNumberProvider.cs:line 39
> 
> 
> 2020-12-17 11:49:10.6|Debug|Api|[POST] /api/v3/downloadclient/testall: 400.BadRequest (121 ms)
> 2020-12-17 11:49:13.2|Debug|Api|[GET] /api/v3/log/file: 200.OK (20 ms)

**Comment by ta264** [comment] 2020-12-17 11:54
Once it gets fixed in sonarr we'll pull it to Radarr.  As a workaround you can switch to a dedicated download client (which would be a good idea even if download station was working)

**Comment by behold81** [comment] 2020-12-17 11:55
Aware of that but the DS version just works and the mobile app makes it easy to monitor. Was not sure if anyone on here might be able to assist with the issue and resolving it.

**Comment by bakerboy448** [comment] 2020-12-17 18:44
xref Sonarr GHI https://github.com/Sonarr/Sonarr/issues/3943

**Comment by Casuallynoted** [comment] 2020-12-17 23:53
Tricky thing with a dedicated client on a DSM 7 machine is that Transmission, NZBGet, and Deluge all won’t install either due to SynoCommunity’s packages not being updated (they have issues with requesting root access, which is no longer allowed in DSM 7). Atm the best way to go about Sonarr downloads on a Synology NAS is by staying on DSM 6 or having a download client on another machine until the issue is resolved.

**Comment by bakerboy448** [comment] 2020-12-17 23:54
What about docker instead of native?

**Comment by Casuallynoted** [comment] 2020-12-17 23:55
You know... that is actually a great idea! I feel like an idiot now. Hahaha

**Comment by behold81** [comment] 2020-12-18 01:30
I docker all my apps. Just DS works flawlessly

**Closed** 2021-02-07 13:58 UTC

**Comment by carlogarro** [comment] 2021-02-09 16:16
It has already been [fixed](https://github.com/Sonarr/Sonarr/issues/3943) on Sonarr. 
Could you please fix it? Thank you!

**Comment by bakerboy448** [comment] 2021-02-09 21:42
@carlogarro this was already fixed in Radarr (nightly)

That can be identified by this
![image](https://user-images.githubusercontent.com/55419169/107432341-71902e80-6aed-11eb-86fc-5a18c0878c3c.png)

combined with the fact that this GHI is closed.
