### ISSUE TITLE
Allow Genre in filename or directory

### ISSUE THREAD

**Issue by ChrisDurham** [Radarr/Radarr#1684] opened 2017-06-15 14:32 UTC
Allow the primary Genre or all Genres to be included as part of the movie folder or movie filename. This would allow easy segregation of movies.

**Comment by galli-leo** [comment] 2017-06-15 16:06
Probably not happening in the near future. See #153 for discussion. (Also this is a duplicate of that)

**Closed by galli-leo** 2017-06-15 16:06 UTC
Labels: duplicate
