### ISSUE TITLE
Support for importing subfolders

### ISSUE THREAD

**Issue by Lucane** [Radarr/Radarr#5771] opened 2021-01-17 12:53 UTC
I know there are no plans to implement this functionality at the moment, but it would be a huge help.
Just like you can import extra files, it would be nice to be able to import subfolders by name as well.
There are a lot of releases that have "Featurettes" or "Extras" folders. Also, sometimes subtitles are placed in subfolders like "Subs" or "Subtitles", which Radarr ignores completely. Telling Radarr to automatically import these would be a nice improvement.

**Comment by bakerboy448** [comment] 2021-01-17 15:42
Duplicate of #1170
Duplicate of #153

**Closed by bakerboy448** 2021-01-17 15:42 UTC
Labels: feature request

**Comment by henningBunk** [comment] 2021-01-23 23:34
@bakerboy448 I don't think the linked issues are related. This issue has to do with extra content for a single movie which are often stored in subfolders of a movie folder.
The linked issues want to allow to put movies into subfolders.

**Comment by austinwbest** [comment] 2021-01-24 00:40
Yea, one is importing from nested folders and one is saving up nested folders.

This issue is importing the data that is in line with the movie but in a subfolder which although is not related to those issues, there is already an issue related to it.

Has to do with metadata & subs being in a sub folder and in the main folder which causes an overwrite or something.

Regardless importing extra stuff from a subfolder is mixed in other issues.
