### ISSUE TITLE
Build: 0.2.0.262 - Search all missing doesn't work. 

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#525] opened 2017-01-29 23:55 UTC
Hi,

On build 0.2.0.262 the search all missing doesn't work. The search selected work if I select everything.

After I click on it nothing is happening ;)

Thanks

**Comment by scuppasteve** [comment] 2017-01-30 19:27
I can verify this situation. Same happens to me.

**Comment by Firemad03** [comment] 2017-01-30 23:29
I confirmed that on build 0.2.0.267 the problem is there too.

**Comment by Brianwuz** [comment] 2017-01-31 02:22
I confirmed that on build 0.2.0.269 the problem is there too.

**Comment by fedoranimus** [comment] 2017-02-11 14:12
Fixed by #710

**Closed by fedoranimus** 2017-02-11 14:12 UTC
Labels: bug, priority:medium
