### ISSUE TITLE
Add option to delete all inxdexers

### ISSUE THREAD

**Issue by xenoncolt** [Radarr/Radarr#8156] opened 2023-02-24 05:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be better to delete them together.. It takes a lot of time to delete them one by one..
![image](https://user-images.githubusercontent.com/81591350/221099712-0f9f10a5-20b0-43c6-915b-f2befab4de21.png)

### Describe the solution you'd like

Add a selection option so that anyone can delete all indexers at once.

### Describe alternatives you've considered

Or some option that can delete all indexers at once

### Anything else?

Same thing for indexers...
![image](https://user-images.githubusercontent.com/81591350/221100261-8878126c-fabf-4432-a338-d9cf0f07366c.png)

**Comment by bakerboy448** [comment] 2023-02-24 12:50
Duplicate of https://github.com/Radarr/Radarr/issues/6672

**Closed by bakerboy448** 2023-02-24 12:50 UTC
Labels: Type: Feature Request, Status: Needs Triage
