### ISSUE TITLE
[FEAT]: Add Actor etc Tickbox for future items only

### ISSUE THREAD

**Issue by Pantar2205** [Radarr/Radarr#6736] opened 2021-11-18 07:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In lists. Add TMBD Person. For eg Br4d P1tt. Radarr will add everything ever done by that actor. That is fine if you wanted that but there is no way to prevent that.

### Describe the solution you'd like

A tickbox of some sort along the lines of

X Future Content Only (This will only get TMDB Person's content that has been created after the date you tick this box)

### Describe alternatives you've considered

I don't think there is another way to solve this with radarr's current way of doing things.

### Anything else?

Thank you for this fantastic project

[AB#1923](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1923)

**Comment by bakerboy448** [comment] 2021-11-18 07:56
Duplicate of https://github.com/Radarr/Radarr/issues/5250

**Closed by bakerboy448** 2021-11-18 07:56 UTC
Labels: Type: Feature Request, Status: Needs Triage
