### ISSUE TITLE
PassThePopcorn Jackett Torznab only processes 1 movie

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#1491] opened 2017-05-06 04:53 UTC
Hi, I have a Github issue open with Jackett on this, but I thought I could give it a shot here as well.

for reference,
https://github.com/Jackett/Jackett/issues/380

Radarr only processes the first output from the PTP Jackett query. Jackett itself has no problems displaying all the items when you do a manual search in its own interface.

I should also note that this is the only Jackett Indexer I have problems with in Radarr.

I'm not sure if this is fixable on your side, but I thought I might as well give it a shot.

Here is the output from searching for a movie with this indexer (Torznab Jackett PassThePopcorn)

Trace Log: https://pastebin.com/e8JHN4AQ

Thanks for taking a look!

**Comment by galli-leo** [comment] 2017-05-06 10:27
Looked at that issue a few days ago. It will be difficult to debug that without an account, since I can see nothing wrong in the logs.
@onedr0p Can you take a look at this?

**Comment by galli-leo** [comment] 2017-05-06 10:27
Btw. any reason you are not using the built in indexer for PTP? I think it makes much more sense, since it allows for the indexer flags (such as Golden or Approved) to be in Radarr.

**Comment by Quiksmage** [comment] 2017-05-06 15:27
I am using it and having no issues. It's more so that I want it fixed in
case it's no longer supported or breaks. Think of it more as a backup. As
long as the built in works, I'll be using it.

**Comment by vendeka** [comment] 2017-05-07 13:27
@galli-leo Here is search screenshot using Torznab PTP:
![image](https://cloud.githubusercontent.com/assets/3618229/25781207/65002ede-333f-11e7-81af-10370950fba2.png)

I believe there is a parsing error as number of leechers is displayed as -19 which is 0. As @Quiksmage mentioned, only 1st item in XML output is parsed and shown in results.

Here is Jackett output log for URL:

http://localhost:9117/torznab/passthepopcorn/api?t=movie&cat=2000,2010,2020,2030,2040,2050,2060,2070,2080,5000,100001,100002,100003,100004,100005&extended=1&apikey=(APIKEY)&offset=0&limit=100&imdbid=0119116

https://pastebin.com/u1afwEk6

I use internal PTP indexer feature, I decided try PTP through Jackett when I see this issue. I hope it helps.

**Comment by galli-leo** [comment] 2017-05-07 13:39
@vendeka I will have to check once I have more time to see what's the issue. Though the -19 leechers is a clear misunderstanding of whoever maintains the Jackett tracker. We get back seeders & peers from Jackett. From that we deduce leechers (peers-seeders). However, according to your xml, the PTP Jackett indexer gives us the leechers (0) instead of peers, although it says peers. So we calculate a negative leecher number.

**Comment by vendeka** [comment] 2017-05-07 14:37
@galli-leo 

> Though the -19 leechers is a clear misunderstanding of whoever maintains the Jackett tracker. We get back seeders & peers from Jackett. From that we deduce leechers (peers-seeders). However, according to your xml, the PTP Jackett indexer gives us the leechers (0) instead of peers, although it says peers. So we calculate a negative leecher number.

I see. I will report it to them.

**Comment by Quiksmage** [comment] 2017-05-09 20:57
Jackett has updated to fix the leecher issue

I re-ran the same URL vendeka did above.

https://pastebin.com/hpZkxSeC

**Comment by onedr0p** [comment] 2017-05-23 14:05
Good to hear, closing this issue.

**Comment by galli-leo** [comment] 2017-05-23 15:23
@onedr0p @Quiksmage Isn't this still an issue?

**Comment by Quiksmage** [comment] 2017-05-23 16:23
This is still an issue. The leecher output being wrong from the Jackett output has been fixed, but Radarr still only processes the first movie from Jackett's results.

**Comment by onedr0p** [comment] 2017-06-07 12:50
Please try using torznab over potato.

**Comment by Quiksmage** [comment] 2017-06-07 12:57
I am only using torznab

**Comment by trunet** [comment] 2017-06-22 20:32
adding a +1 hgere... only one movie returns from latest jackett and PTP

**Comment by standardcake** [comment] 2017-07-13 14:09
I'm having this same issue.  PTP is only returning 1 result.  Can't seem to add the normal PTP tracker with my QNAP, so Jackett is my only option.

**Comment by slydog3333** [comment] 2017-08-02 18:52
I can confirm all of the above. PTP via Jackett only returns the first result. No issues with IPT via Jackett. PTP works fine via radarr's built in.

For me I was looking forward to having nzbhydra manage all my indexers and PTP was to be my last resort as ratio is tougher there.  I'll just have to hope the torrent delay keeps out PTP till this is fixed.

**Comment by standardcake** [comment] 2017-10-12 01:34
Any update for this?  Same issue...

**Comment by standardcake** [comment] 2017-11-08 18:13
Can someone please look into this?  PTP is a very popular tracker.  No reason it should be broken in Jackett...

**Comment by galli-leo** [comment] 2017-11-10 15:49
After investigating this is an error on Jackett's side. All releases from the Torznab indexer have the same GUID, which is wrong. I will close this issue and open one on the Jackett Github. I would advise using the integrated PTP tracker anyways, since it will handle Golden Popcorn & Internal releases better via indexer flags.

**Closed by galli-leo** 2017-11-10 15:49 UTC
Labels: bug

**Comment by Quiksmage** [comment] 2017-11-10 18:36
Thanks for looking into this galli-leo

**Comment by standardcake** [comment] 2017-11-10 18:40
Unfortunately can't use PTP's built in indexer on my QNAP...for whatever
reason.  Still seeing the same issue after the Jackett github fix...

**Comment by onedr0p** [comment] 2017-11-12 16:48
I don't think it was fixed on Jackett yet...
