### ISSUE TITLE
Wanted / Missing with "released" filter includes "unmonitored"

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#1205] opened 2017-03-17 16:03 UTC
I have "Ignore Deleted Movies" activated.
The Movies gets unmonitored.
Then when I go to wanted -> missing -> Filter "released" to do a manual search it should not include the unmonitored movies and redownload them. 
Of course I could Filter for monitored, but then I search for a lot more movies without proper releases.

And there is now mass delete old unmonitored movies (with marking them to exclude them from readding through lists)

**Comment by geogolem** [comment] 2017-03-17 21:57
This is how the filters work right now...
Missing -- will show you Missing movies, whether monitored or unmonitored. Released will show you released movies, whether monitored, unmonitored, downloaded or missing..

There are some feature requests regarding changing the filtering mechanism and they might be looked at in the future..

but as of right now, this is not a bug... A movie can be Missing and Monitored,. or Missing and Unmonitored.. 

If you are on the Missing page and click "Released" you will get all MIssing movies that are released, monitored and unmonitored...

I agree it would be nice to be able to filter with more flexibility; however this is how it is right now.

**Comment by galli-leo** [comment] 2017-06-15 09:04
So closing this for now. We already have an issue for new filtering options. Once those get implemented, they should work across the board.

**Closed by galli-leo** 2017-06-15 09:04 UTC
