### ISSUE TITLE
"Plex Media Server" Not Notified of change in "Root Folder" by Radarr

### ISSUE THREAD

**Issue by dramirvf** [Radarr/Radarr#5448] opened 2020-12-01 03:25 UTC
Radarr Version: 3.0.0.4216

When the **Root Folders** of movies are changed from within Radarr and Radarr has taken the responsibility of moving the files to the new location, **"Plex Media Center"** (which has been added in **"Connect"** section in Radarr) is not notified of this change.

Therefore, **"Plex Media Center"** thinks there is no changes in the library. To have the updated folders in Plex, we need to manually trigger a library scan in affected folders to resolve the issue, which is very inconvenient.

Expected Behavior:
A library scan is triggered for connected **"Plex Media Server"**  when **Root Folders** are changed by Radarr.

**Comment by SugarDroid** [comment] 2020-12-02 18:38
Not working after renaming movie's own folder neither. 

- Version 3.0.0.4221
- Package Version 3.0.0.4221-ls3 by linuxserver.io
- .NET Core Yes (3.1.10)
- Docker Yes

https://pastebin.com/LFEfrMg6

**Comment by bakerboy448** [comment] 2020-12-02 18:39
@SugarDroid do you have rename enabled for the plex connection?

**Comment by SugarDroid** [comment] 2020-12-02 18:46
@bakerboy448 import, upgrade and rename enabled.

**Comment by endiz** [comment] 2020-12-04 05:54
Running a test connection in Plex connect setting generates the following log entries:


RadarrErrorPipeline | Invalid request Validation failed: -- Host: Unable to connect to Plex Server | 12:52am |  
-- | -- | -- | --
  | PlexServerService | Unable to connect to Plex Server: Unable to connect to Plex Media Server | 12:52am |  
  | X509CertificateValidationService | Certificate validation for https://192.168.2.22:32400/library/sections?X-Plex-Client-Identifier=(removed)&X-Plex-Product=Radarr&X-Plex-Platform=Windows&X-Plex-Platform-Version=7&X-Plex-Device-Name=Radarr&X-Plex-Version=3.0.0.4204&X-Plex-Token=(removed) failed. RemoteCertificateNameMismatch | 12:52am

**Comment by bakerboy448** [comment] 2020-12-04 09:53
See the FAQ, HTTPS is what you're looking for...don't use it on a local network you're implying the network is not trusted and not secure.

Also not CA signed certs are also not secure

**Comment by endiz** [comment] 2020-12-04 16:41
> See the FAQ, HTTPS is what you're looking for...don't use it on a local network you're implying the network is not trusted and not secure.
> 
> Also not CA signed certs are also not secure

We don't assign certs, plex does. Also, But disabling "Use SSL" setting on plex connect config works.

FWIW, this worked before the major upgrade to radarr, and it still works with sonarr.

![image](https://user-images.githubusercontent.com/11183525/101189411-045fa900-3625-11eb-8a05-7121bc3814d7.png)

![image](https://user-images.githubusercontent.com/11183525/101189688-60c2c880-3625-11eb-8d72-cd001cdf48a2.png)

![image](https://user-images.githubusercontent.com/11183525/101189864-9a93cf00-3625-11eb-95c2-8e111e6eb03a.png)

**Comment by bakerboy448** [comment] 2020-12-04 16:43
Again, don't use HTTPS on a local network that is just plain dumb security theater and also implies you do not trust tour network.


Correct, v0.2 in 2010 didn't bother to check if certs were valid; v3 in 2020 does

**Comment by endiz** [comment] 2020-12-04 16:46
I wouldn't agree (and most of the internet wouldn't either) that using HTTPS locally is dumb security theater, but thanks for the help. I appreciate it.

**Comment by bakerboy448** [comment] 2020-12-04 16:52
Using HTTPS on a (non-commercial, home) LAN is absolutely security theater as you inherently can't used a root signed certificate on any LAN and folks almost always use self signed certs which are not secure nor valid/trusted.

**Comment by dramirvf** [comment] 2020-12-04 17:28
> Again, don't use HTTPS on a local network that is just plain dumb security theater and also implies you do not trust tour network.
> 
> Correct, v0.2 in 2010 didn't bother to check if certs were valid; v3 in 2020 does

@bakerboy448 
Why is the ticket closed??? This is a bug! not support!

**Comment by bakerboy448** [comment] 2020-12-04 17:30
Please enlighten me, how exactly is this a bug?

A invalid cert is being used and radarr is correctly throwing an error.  

You shouldn't be using HTTPS on a consumer LAN anyway. 

As the FAQ says, if you still wish to do your security theater there is a setting to adjust certificate validate for local networks.

**Comment by dramirvf** [comment] 2020-12-04 17:32
> Please enlighten me, how exactly is this a bug?
> 
> A invalid cert is being used and radarr is correctly throwing an error.
> 
> You shouldn't be using HTTPS on a consumer LAN anyway.
> 
> As the FAQ says, if you still wish to do your security theater there is a setting to adjust certificate validate for local networks.

What are you talking about?
The subject is something totally different. You are now talking about something else!!! which is not relevant to this thread.

**Comment by bakerboy448** [comment] 2020-12-04 17:35
The provided logs (second OP comment) indicate radarr cannot connect to plex...hence plex not being notified.

The error provided is the SSL error, which my comments addressed. Thus a user configuration error / support issue and not a bug.

So my prior comments still stand.

What is the bug here? (Rhetorical question as there is not one, based on the information provided.)

**Comment by dramirvf** [comment] 2020-12-04 17:38
> The provided logs (second OP comment) indicate radarr cannot connect to plex...hence plex not being notified.
> 
> The error provided is the SSL error, which my comments addressed. Thus a user configuration error / support issue and not a bug.
> 
> So my prior comments still stand.
> 
> What is the bug here? (Rhetorical question as there is not one, based on the information provided.)

Which logs you are talking about? There is no logs!!! Who cares about SSL? Are you ok?
Plex connects and works without any issues.

**Comment by dramirvf** [comment] 2020-12-04 17:39
> The provided logs (second OP comment) indicate radarr cannot connect to plex...hence plex not being notified.
> 
> The error provided is the SSL error, which my comments addressed. Thus a user configuration error / support issue and not a bug.
> 
> So my prior comments still stand.
> 
> What is the bug here? (Rhetorical question as there is not one, based on the information provided.)

That guy is not the author of this thread. This thread is about something else!!!

**Comment by bakerboy448** [comment] 2020-12-04 17:41
@dramirvf i think you're a bit lost and on the wrong issue then.

I'm not sure how I can make it any more clear...

Issue: plex not being notified on renames
Cause: HTTPS being used on the local radarr -> plex connection 
Solution: don't use HTTPS with an invalid, not root signed, cert on a LAN & similarly don't use HTTPS on IP addresses

If you're still confused, hop on discord so members who are following the repo or this issue stop getting their emailed spammed.

This is also how threads end up locked....

**Comment by dramirvf** [comment] 2020-12-04 17:44
> HTTPS be

I think you are a bit lost!

Issue: plex not being notified on **Change** in "Root Folder" by Radarr
Cause: Unknown. Who says HTTPS is being used on the local radarr ???????? HTTPS has not been ever used.
Solution: There should be a trigger sent to the plex by Radarr to re-scan the library upon **Change** in "Root Folder" by Radarr

If you're still confused, read the thread from the beginning.

**Comment by bakerboy448** [comment] 2020-12-04 17:47
Got muddied with the other user comments, my apologies.

Regardless still the same.

You blew away the template and have not provided any information at all to indicate what the issue is.  99.9999% of “bugs” are support/user error; hence the support flag.

Like the other user mentioned and like we see frequently the typical cause is using HTTPS when it should not be used.

As the bot said, and in case you haven’t picked up on it yet.

### Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by dramirvf** [comment] 2020-12-04 17:57
> Got muddied with the other user comments, my apologies.
> 
> Regardless still the same.
> 
> You blew away the template and have not provided any information at all to indicate what the issue is. 99.9999% of “bugs” are support/user error; hence the support flag.
> 
> Like the other user mentioned and like we see frequently the typical cause is using HTTPS when it should not be used.
> 
> As the bot said, and in case you haven’t picked up on it yet.
> 
> ### Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

No. Not having anything to do with HTTPS. This is 100% BUG and 100% reproducible. I did not provided more info, because it is not needed here. The behavior is exactly as I have written. And 100% reproducible. And the reason beyond that is very clear which could be resolved accordingly.

Each topic is about a specific matter. When a bug is clearly stated in the **"TOPIC"** and has been **"Well-explained"** in the body, then other discussions should not be brought here which cause confusion?

How could I add "BUG" tag and remove ""SUPPORT tag from this thread?

**Comment by bakerboy448** [comment] 2020-12-04 18:05
>No. Not having anything to do with HTTPS. This is 100% BUG and 100% reproducible. I did not provided more info, because it is not needed here. The behavior is exactly as I have written. And 100% reproducible. And the reason beyond that is very clear which could be resolved accordingly.

Not a bug, options for the Plex Connection are
- On Import
- On Rename
- On Upgrade

I don't see "On Move" there, do you?
Didn't think so.
Thus it most certainly is not a bug for no notification when folders are moved. If there is not a trigger to be triggered, how can a bug exist?

It can be argued that would make a great feature request.  Don't forget to **NOT** blow away half the template and properly fill it out if you go that route :)

>Each topic is about a specific matter. When a bug is clearly stated in the "TOPIC" and has been "Well-explained" in the body, then other discussions should not be brought here which cause confusion.

I don't disagree with this as a concept.

>How could I add "BUG" tag and remove ""SUPPORT tag from this thread?

You cannot.
And if you open any other "Bug" GHI for this issue, they'll be closed and marked as dupes of this thread.

**Comment by SugarDroid** [comment] 2020-12-04 18:12
> @dramirvf i think you're a bit lost and on the wrong issue then.
> 
> Edit: there are ALWAYS logs as long as radarr even attempts to start up. Any other statement to the contrary is false. and there are logs posted (via Pastebin and less ideally via a screenshot) on this issue/Edit
> 
> I'm not sure how I can make it any more clear...
> 
> Issue: plex not being notified on renames
> Cause: HTTPS being used on the local radarr -> plex connection
> Solution: don't use HTTPS with an invalid, not root signed, cert on a LAN & similarly don't use HTTPS on IP addresses
> 
> If you're still confused, hop on discord so members who are following the repo or this issue stop getting their emailed spammed.
> 
> This is also how threads end up locked....

@bakerboy448 sorry but you're just spreading assumptions here, i've no https enabled. Right, i'm not the author of this issue but gave you log, even gave answer for your question too. If it's related to https connection then it should not work on import neither, but it does!
IMO you just got upset due a dumb guy who derailed valid bug report with his support request, and instead splitting them -i just guess it's available- you just closed a valid report with really bad excuses.

**Comment by bakerboy448** [comment] 2020-12-04 18:14
> Not a bug, options for the Plex Connection are
> 
> On Import
> On Rename
> On Upgrade
> I don't see "On Move" there, do you?
> Didn't think so.
> Thus it most certainly is not a bug for no notification when folders are moved. If there is not a trigger to be triggered, how can a bug exist?
> 
> It can be argued that would make a great feature request. Don't forget to NOT blow away half the template and properly fill it out if you go that route :)

@SugarDroid

**Comment by dramirvf** [comment] 2020-12-04 18:17
Another user has given a comment that this behavior has also been seen on **"rename"**. I have double-checked the issue with renaming, and I believe that user is correct. Changing the root folder could also be considered as something similar to **"rename"**, as the address to the file has been renamed by Radarr.

If Radarr changes anything associated with file address (either renaming the file, or changing the address), it should notify the connected services, since changes has been implemented from within Radarr.

**Comment by SugarDroid** [comment] 2020-12-04 18:19
@bakerboy448 same bad excuses. Radarr does not work correctly, period. Does not matter what you come up with here as excuses..

**Closed** 2020-12-04 18:18 UTC

**Comment by dramirvf** [comment] 2020-12-04 18:22
This is not definitely a **"FEATURE REQUEST"**. This is something which is missed by Radarr. If I want to choose a label between **"BUG"** and **"Feature Request"**, and there is no more options available, again I would choose **"BUG"**, as the concept of **"FEATURE REQUEST"** is something totally different.

**Comment by bakerboy448** [comment] 2020-12-04 18:24
Gents,

This is very very sample:
### RENAME != MOVE
I'm not sure why or how that is a difficult concept to understand?
They are two independent processes.  There is currently no trigger for moves.

Using the move feature to move movies or using the hidden feature of it to rename movie folders is still a move. 

My initial reply to you @SugarDroid was off based, I misread your issue; my apologies, as you can imagine we've been inundated with a deluge of GHI and requests via our other channels.

This is not a bug, but arguably a gap in the features. Perhaps a nice example would help explain this:

This is like your car not having a rear wiper and saying it is a bug that your rear wiper does not clean your rear window.
There is no rear wiper that exists so it inherently is not a bug. A feature request to add a rear wiper may make sense though!

**Comment by dramirvf** [comment] 2020-12-04 18:29
> Gents,
> 
> This is very very simple:
> 
> ### RENAME != MOVE
> I'm not sure why or how that is a difficult concept to understand?
> They are two independent processes. There is currently no trigger for moves.
> 
> Using the move feature to move movies or using the hidden feature of it to rename movie folders is still a move.
> 
> My initial reply to you @SugarDroid was off base, I misread your issue; my apologies, as you can imagine we've been inundated with a deluge of GHI and requests via our other channels.
> 
> This is not a bug, but arguably a gap in the features. Perhaps a nice example would help explain this:
> 
> This is like your car not having a rear wiper and saying it is a bug that your rear wiper does not clean your rear window when you turn on the front wipers.
> There is no rear wiper that exists so it inherently is not a bug. A feature request to add a rear wiper may make sense though!

Your examples are again off the topic!
Please read the topics well, then give comments. There's not rush to give comments if you even don't know what the topic is about. Already, we have seen 2 consecutive examples of your comments without reading the messages properly.
If you had read the topic and messages correctly, there was no need for these irrelevant examples.

**Comment by austinwbest** [comment] 2020-12-04 20:40
Ok, this has become a cluster.. 

@dramirvf please copy and paste your OP into a new issue so i can lock this one and not have to try and keep up with the history. A fresh issue for proper conversation about it would be helpful.

@SugarDroid for your SSL stuff please use discord to get some help and we can determine if there is a bug to be fixed. If you have thoughts on the OP about move/rename then you are welcome to comment on the new issue when it is added.

**Comment by Qstick** [comment] 2020-12-04 20:49
> Ok, this has become a cluster..
> 
> @dramirvf please copy and paste your OP into a new issue so i can lock this one and not have to try and keep up with the history. A fresh issue for proper conversation about it would be helpful.

Good call, this seems like a legit issue so let's start fresh.
