### ISSUE TITLE
Radarr determines wrong source on PAL DVD

### ISSUE THREAD

**Issue by tardezyx** [Radarr/Radarr#8587] opened 2023-05-24 21:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I let Radarr rename movie files according to this tags:
`{Movie Title:DE} ({Release Year}){ (Edition Tags)} [{Quality Full}{.MediaInfo 3D}{.MediaInfo VideoDynamicRange}{.Mediainfo VideoBitDepth}bit{.Mediainfo VideoCodec}{.Mediainfo AudioCodec}{ Mediainfo AudioChannels}]{.MediaInfo AudioLanguages}{-Release Group}`

1. When renaming a file with a video resolution stream of 720x576 (European PAL DVD):
`Captain.Kronos.Vampirjaeger.1974.Uncut.German.DL.Untouched.PAL.DVD9-K4miK4z3`

The result is as follows:
`Captain Kronos - Vampirjäger (1974) (Uncut) [Unknown.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv`

=> Source "Unknown" is wrong

2. When changing the original file name e.g. to:
'Captain.Kronos.Vampirjaeger.1974.Uncut.PAL.DVD.German.DL.Untouched-K4miK4z3.mkv'

The result is as follows:
`Captain Kronos - Vampirjäger (1974) (Uncut) [Bluray-576p.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv`

=> Source "Bluray-576p" is wrong

### Expected Behavior

Expected is one of these results:
`Captain Kronos - Vampirjäger (1974) (Uncut) [DVD.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv`
`Captain Kronos - Vampirjäger (1974) (Uncut) [DVD9.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv`
`Captain Kronos - Vampirjäger (1974) (Uncut) [DVD-R.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv`
`Captain Kronos - Vampirjäger (1974) (Uncut) [PAL-DVD.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv`
etc.

### Steps To Reproduce

Test any video source file with 720x576 (= European PAL DVD) and set the file name to
`Captain.Kronos.Vampirjaeger.1974.Uncut.German.DL.Untouched.PAL.DVD9-K4miK4z3`

Then let Radarr rename the file accordingly while using {Quality Full} in the file renaming settings.

By the way, the Kjeller BOT on your discord server determines the correct data (it determines DVD-R as source) but Radarr seems to use the resolution which then determines the source which is wrong.

The more important questions are:
Why does the resolution determine the source, in the first place?
Especially when the source is already inside the file name (here: "PAL.DVD9")?

### Environment

```markdown
- OS: Unraid v6.9.2
- Radarr: v4.4.4.7068
- Docker Install: Yes, Package: release-901483d by hotio (https://github.com/hotio)
- Using Reverse Proxy: -
- Browser: -
- Database: -
```

### What branch are you running?

Master

### Trace Logs?
```
2023-05-24 03:45:46.8|Info|RefreshMovieService|Updating info for Captain Kronos: Vampire Hunter
2023-05-24 03:45:47.3|Info|DiskScanService|Scanning disk for Captain Kronos: Vampire Hunter
2023-05-24 03:45:47.3|Warn|QualityFinder|Unable to find exact quality for DVD,  576, and REMUX. Using Unknown as fallback
2023-05-24 03:45:47.3|Info|MovieService|Assigning file [Captain.Kronos.Vampirjaeger.1974.Uncut.PAL.DVD9.German.DL.Untouched-K4miK4z3.mkv] to movie [[Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979]]
2023-05-24 03:45:47.3|Info|DiskScanService|Completed scanning disk for Captain Kronos: Vampire Hunter
2023-05-24 03:45:47.3|Info|ExistingMetadataImporter|Found 0 existing metadata files
2023-05-24 03:45:47.3|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2023-05-24 03:45:47.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2023-05-24 03:45:47.3|Info|ExistingExtraFileService|Found 0 possible extra files, imported 0 files.
2023-05-24 03:45:47.3|Info|MediaCoverService|Downloading Poster for [Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979] https://image.tmdb.org/t/p/original/soF2Ue7lrp4LeG4bkmx0AjPeWbt.jpg
2023-05-24 03:45:47.5|Info|MediaCoverService|Downloading Fanart for [Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979] https://image.tmdb.org/t/p/original/8Kif5lgtbI2Incg0hmkkXSmx3xB.jpg
2023-05-24 03:46:25.7|Info|RssSyncService|Starting RSS Sync
2023-05-24 03:46:25.7|Warn|FetchAndParseRssService|No available indexers. check your configuration.
2023-05-24 03:46:25.7|Info|DownloadDecisionMaker|No results found
2023-05-24 03:46:25.7|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
2023-05-24 03:46:57.6|Info|RefreshMovieService|Updating info for Captain Kronos: Vampire Hunter
2023-05-24 03:46:58.0|Info|DiskScanService|Scanning disk for Captain Kronos: Vampire Hunter
2023-05-24 03:46:58.1|Warn|QualityFinder|Unable to find exact quality for DVD,  576, and NONE. Using Bluray-576p as fallback
2023-05-24 03:46:58.1|Info|MediaCoverService|Downloading Poster for [Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979] https://image.tmdb.org/t/p/original/soF2Ue7lrp4LeG4bkmx0AjPeWbt.jpg
2023-05-24 03:46:58.1|Info|MovieService|Assigning file [Captain.Kronos.Vampirjaeger.1974.Uncut.PAL.DVD.German.DL.Untouched-K4miK4z3.mkv] to movie [[Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979]]
2023-05-24 03:46:58.1|Info|DiskScanService|Completed scanning disk for Captain Kronos: Vampire Hunter
2023-05-24 03:46:58.1|Info|ExistingMetadataImporter|Found 0 existing metadata files
2023-05-24 03:46:58.1|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2023-05-24 03:46:58.1|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2023-05-24 03:46:58.1|Info|ExistingExtraFileService|Found 0 possible extra files, imported 0 files.
2023-05-24 03:46:58.2|Info|MediaCoverService|Downloading Fanart for [Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979] https://image.tmdb.org/t/p/original/8Kif5lgtbI2Incg0hmkkXSmx3xB.jpg
2023-05-24 03:48:08.2|Info|RefreshMovieService|Updating info for Captain Kronos: Vampire Hunter
2023-05-24 03:48:08.7|Info|DiskScanService|Scanning disk for Captain Kronos: Vampire Hunter
2023-05-24 03:48:08.8|Info|MediaCoverService|Downloading Poster for [Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979] https://image.tmdb.org/t/p/original/soF2Ue7lrp4LeG4bkmx0AjPeWbt.jpg
2023-05-24 03:48:08.8|Warn|QualityFinder|Unable to find exact quality for DVD,  576, and NONE. Using Bluray-576p as fallback
2023-05-24 03:48:08.8|Info|MovieService|Assigning file [Captain.Kronos.Vampirjaeger.1974.Uncut.PAL.DVD-9.German.DL.Untouched-K4miK4z3.mkv] to movie [[Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979]]
2023-05-24 03:48:08.8|Info|DiskScanService|Completed scanning disk for Captain Kronos: Vampire Hunter
2023-05-24 03:48:08.8|Info|ExistingMetadataImporter|Found 0 existing metadata files
2023-05-24 03:48:08.8|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2023-05-24 03:48:08.8|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2023-05-24 03:48:08.8|Info|ExistingExtraFileService|Found 0 possible extra files, imported 0 files.
2023-05-24 03:48:08.9|Info|MediaCoverService|Downloading Fanart for [Captain Kronos: Vampire Hunter (1974)][tt0071276, 18979] https://image.tmdb.org/t/p/original/8Kif5lgtbI2Incg0hmkkXSmx3xB.jpg
2023-05-24 03:55:59.6|Info|RenameMovieFileService|Renaming 1 files for Captain Kronos: Vampire Hunter
2023-05-24 03:55:59.6|Info|RenameMovieFileService|Selected movie files renamed for Captain Kronos: Vampire Hunter
```
### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by tardezyx** [comment] 2023-05-24 21:10
Using FFProbe:
`d:\Apps\tartube\mingw64\bin>ffprobe -v quiet -print_format json -show_format -sexagesimal -show_streams  -i "g:\data\media\movies (emm)\Captain Kronos - Vampirjäger (1974) [tt0071276]\Captain Kronos - Vampirjäger (1974) (Uncut) [Bluray-576p.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv"`

Output:
```
{
    "streams": [
        {
            "index": 0,
            "codec_name": "mpeg2video",
            "codec_long_name": "MPEG-2 video",
            "profile": "Main",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 720,
            "height": 576,
            "coded_width": 0,
            "coded_height": 0,
            "closed_captions": 0,
            "has_b_frames": 1,
            "sample_aspect_ratio": "64:45",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 8,
            "color_range": "tv",
            "chroma_location": "left",
            "field_order": "tt",
            "refs": 1,
            "r_frame_rate": "25/1",
            "avg_frame_rate": "25/1",
            "time_base": "1/1000",
            "start_pts": 80,
            "start_time": "0:00:00.080000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "BPS-eng": "6418564",
                "DURATION-eng": "01:27:16.040000000",
                "NUMBER_OF_FRAMES-eng": "130901",
                "NUMBER_OF_BYTES-eng": "4200982428",
                "SOURCE_ID-eng": "0100E0",
                "_STATISTICS_WRITING_APP-eng": "MakeMKV v1.17.3 win(x64-release)",
                "_STATISTICS_WRITING_DATE_UTC-eng": "2023-05-23 13:21:00",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID"
            },
            "side_data_list": [
                {
                    "side_data_type": "CPB properties"
                }
            ]
        },
        {
            "index": 1,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 600,
            "start_time": "0:00:00.600000",
            "bit_rate": "192000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "ger",
                "title": "Stereo",
                "BPS-eng": "192000",
                "DURATION-eng": "01:27:15.424000000",
                "NUMBER_OF_FRAMES-eng": "163607",
                "NUMBER_OF_BYTES-eng": "125650176",
                "SOURCE_ID-eng": "0180BD",
                "_STATISTICS_WRITING_APP-eng": "MakeMKV v1.17.3 win(x64-release)",
                "_STATISTICS_WRITING_DATE_UTC-eng": "2023-05-23 13:21:00",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID"
            }
        },
        {
            "index": 2,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0:00:00.000000",
            "bit_rate": "192000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "title": "Stereo",
                "BPS-eng": "192000",
                "DURATION-eng": "01:27:16.032000000",
                "NUMBER_OF_FRAMES-eng": "163626",
                "NUMBER_OF_BYTES-eng": "125664768",
                "SOURCE_ID-eng": "0181BD",
                "_STATISTICS_WRITING_APP-eng": "MakeMKV v1.17.3 win(x64-release)",
                "_STATISTICS_WRITING_DATE_UTC-eng": "2023-05-23 13:21:00",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID"
            }
        },
        {
            "index": 3,
            "codec_name": "dvd_subtitle",
            "codec_long_name": "DVD subtitles",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 720,
            "height": 576,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0:00:00.000000",
            "duration_ts": 5236040,
            "duration": "1:27:16.040000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "ger",
                "BPS-eng": "2630",
                "DURATION-eng": "01:25:58.596977777",
                "NUMBER_OF_FRAMES-eng": "546",
                "NUMBER_OF_BYTES-eng": "1696120",
                "SOURCE_ID-eng": "0120BD",
                "_STATISTICS_WRITING_APP-eng": "MakeMKV v1.17.3 win(x64-release)",
                "_STATISTICS_WRITING_DATE_UTC-eng": "2023-05-23 13:21:00",
                "_STATISTICS_TAGS-eng": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID"
            }
        }
    ],
    "format": {
        "filename": "g:\\data\\media\\movies (emm)\\Captain Kronos - Vampirj├ñger (1974) [tt0071276]\\Captain Kronos - Vampirj├ñger (1974) (Uncut) [Bluray-576p.8bit.MPEG2.AC3 2.0].[DE+EN]-K4miK4z3.mkv",
        "nb_streams": 4,
        "nb_programs": 0,
        "format_name": "matroska,webm",
        "format_long_name": "Matroska / WebM",
        "start_time": "0:00:00.000000",
        "duration": "1:27:16.040000",
        "size": "4457815242",
        "bit_rate": "6810972",
        "probe_score": 100,
        "tags": {
            "encoder": "libmakemkv v1.17.3 (1.3.10/1.5.2) win(x64-release)",
            "creation_time": "2023-05-23T13:21:00.000000Z"
        }
    }
}
```

**Comment by bakerboy448** [comment] 2023-05-24 21:12
The **required** trace logs will show exactly what is driving radarr's decision and make troubleshooting much easier.

info logs are not valid for bug reports and not helpful for any debugging

**Comment by tardezyx** [comment] 2023-05-24 21:20
[Trace Log](https://gist.github.com/tardezyx/dc95ebf7ab2658935ab26a3c06e4c42e)

**Comment by tardezyx** [comment] 2023-05-24 21:23
[Trace Log #2](https://gist.github.com/tardezyx/422d596507e6c1639deb43a9cea44ccb) (renamed to "...Bluray-576p...")

**Comment by bakerboy448** [comment] 2023-05-24 21:27
```
2023-05-24 23:19:48.8|Debug|QualityParser|Trying to parse quality for Captain.Kronos.Vampirjaeger.1974.Uncut.German.DL.Untouched.PAL.DVD9-K4miK4z3.mkv
2023-05-24 23:19:48.8|Debug|Parser|Quality parsed: DVD-R v1
2023-05-24 23:19:48.8|Trace|AggregateQuality|Considering Source DVD (Tag) Resolution 480 (Fallback) Revision v1 from FileName
2023-05-24 23:19:48.8|Trace|AugmentQualityFromMediaInfo|Resolution 720x576 considered 576p
2023-05-24 23:19:48.8|Trace|AggregateQuality|Considering Source UNKNOWN (Default) Resolution 576 (MediaInfo) Revision  from MediaInfo
2023-05-24 23:19:48.8|Trace|AggregateQuality|Selected Source DVD (Tag) Resolution 576 (MediaInfo) Revision v1
2023-05-24 23:19:48.8|Warn|QualityFinder|Unable to find exact quality for DVD,  576, and REMUX. Using Unknown as fallback
2023-05-24 23:19:48.8|Debug|AggregateQuality|Using quality: Unknown v1
```

actually should already be fixed https://github.com/Radarr/Radarr/commit/b8ce140abcef73037b638f3cff200b707aab5e07

**Comment by bakerboy448** [comment] 2023-05-24 21:27
Duplicate of https://github.com/Radarr/Radarr/issues/7297

**Closed by bakerboy448** 2023-05-24 21:27 UTC
Labels: Type: Bug, Status: Needs Triage, Status: Logs Needed
