### ISSUE TITLE
[Feature Request] Download Metadata and import extras

### ISSUE THREAD

**Issue by Mssol94** [Radarr/Radarr#2214] opened 2017-10-25 01:27 UTC
Radar should have the option download metadata for the movies, like posters, subtitles and nfo. It should also be possible to import the extra files that have been downloaded with the movies like you can with Sonarr.

**Comment by ChrisRomp** [comment] 2018-01-05 19:10
https://github.com/Radarr/Radarr/issues/121

**Comment by galli-leo** [comment] 2018-01-07 09:47
Duplicate of #121

**Closed by galli-leo** 2018-01-07 09:47 UTC
