### ISSUE TITLE
Display which list automatically added a movie

### ISSUE THREAD

**Issue by keteague** [Radarr/Radarr#6939] opened 2022-01-17 00:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have new movies in Radarr added as Unmonitored and I don't know which list they're being added from.

### Describe the solution you'd like

It would be helpful to see which list added the movie to Radarr... maybe even a filter for that as well so that I can remove them in bulk.

### Describe alternatives you've considered

No alternatives

### Anything else?

No.  Thanks for your consideration.

[AB#2376](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2376)

**Comment by bakerboy448** [comment] 2022-01-17 00:50
Duplicate of https://github.com/Radarr/Radarr/issues/6734

**Closed by bakerboy448** 2022-01-17 00:50 UTC
Labels: Type: Feature Request, Status: Needs Triage
