### ISSUE TITLE
[FEAT]: Filter movies by Audio Languages

### ISSUE THREAD

**Issue by ejalal** [Radarr/Radarr#6657] opened 2021-10-14 12:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hey guys,

I have plenty of movies which I download in English, and then upgrade to Multilanguage French + English once they are available, the thing is I might still have some movies with only in English XOR French that I would like to uprgade into Multilanguage.

It would be nice to have a new filter by Audio Language.

### Describe the solution you'd like

Add a new filter on the Custom Filter popup for Audio Language

### Describe alternatives you've considered

None that I think of right now

### Anything else?

Nope

[AB#1760](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1760)

**Comment by bakerboy448** [comment] 2021-10-14 12:42
Duplicate of https://github.com/Radarr/Radarr/issues/5703

Duplicate  of #5517 and various others

please do a better search next time

**Closed as completed by bakerboy448** 2021-10-14 12:42 UTC
Labels: Type: Feature Request, Type: Duplicate
