### ISSUE TITLE
"Custom Filter" like "Path" but for files.

### ISSUE THREAD

**Issue by SugarDroid** [Radarr/Radarr#5691] opened 2021-01-05 00:25 UTC
**Is your feature request related to a problem? Please describe.**
Since there are retard releasers/groups -maybe they're the same with different names, idk- who gives garbage names to their releases thus I can't use Radarr completely as it's supposed to be. (Other than this, there's no quality problem with them.)

Many times a movie is out with -non-English- stereo audio at first, which they don't give a duck to put any sign into names, most times a CUSTOM tag neither -thus CF is not a solution here-, so Radarr grabs them. This would be no problem at all, but the same retards put READ.NFO tag into names when the same movie is available with 5.1 audio, instead PROPER/REPACK, so Radarr unable to upgrade from stereo to 5.1 version. 

But to make it even more frustrating, sometimes the READ.NFO tag appears in names with stereo audio, thus make it unable to use CF for this neither. (No, i can't ban these retards, unfortunately.)

Unfortunately due this, from time to time I've to manually search, that that 5.1 version exist already or not yet.

**Describe the solution you'd like**
Since Radarr knows also the name of existing files -not their path only-, would be great and would make easy to find them, if a "Custom Filter" like the one for "Path" would exist for files too. 

**Additional context**
![image](https://user-images.githubusercontent.com/56313144/103592266-e373c780-4ef2-11eb-98d5-581ed5362434.png)

**Comment by ta264** [comment] 2021-02-09 08:24
Duplicate of #5397

**Closed by ta264** 2021-02-09 08:24 UTC
Labels: feature request
