### ISSUE TITLE
Movie posters missing. Refresh results in "UNIQUE constraint failed: Credits.CreditTmdbId"

### ISSUE THREAD

**Issue by cannondale0815** [Radarr/Radarr#8013] opened 2023-01-21 02:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After importing several hundred existing videos to Radarr, I noticed that all movie posters were missing. When I refresh the metadata of an individual movie, I see the following error in the logs:

`
[v4.3.2.6857] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: Credits.CreditTmdbId
`

(see attached full stack trace)

It is worth noting that I had previously added my entire video library into Radarr already, but then I changed the naming of all movie folders, which necessitated the removal of all movies from my Radarr library and reimporting them. Perhaps the database didn't get cleaned properly inbetween, resulting in remnants that now interfere (pure speculation).

### Expected Behavior

I expected the refresh to succeed and movie posters to appear.

### Steps To Reproduce

In my current environment, every time I refresh metadata I see the error message in the logs.

### Environment

```markdown
- OS: Windows 10 32 bit
- Radarr: 4.3.2.6857
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome & Edge Chromium
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

[v4.3.2.6857] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
UNIQUE constraint failed: Credits.CreditTmdbId
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1077
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1060
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 210
   at NzbDrone.Core.Movies.Credits.CreditService.UpdateCredits(List`1 credits, MovieMetadata movieMetadata) in D:\a\1\s\src\NzbDrone.Core\Movies\Credits\CreditService.cs:line 81
   at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo(Int32 movieId) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 154
   at NzbDrone.Core.Movies.RefreshMovieService.Execute(RefreshMovieCommand message) in D:\a\1\s\src\NzbDrone.Core\Movies\RefreshMovieService.cs:line 212
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 81
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

[AB#4771](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4771)

**Comment by bakerboy448** [comment] 2023-01-21 02:33
Duplicate of https://github.com/Radarr/Radarr/issues/4540

**Comment by cannondale0815** [comment] 2023-01-21 02:33
This sounds related to this much older issue: https://github.com/Radarr/Radarr/issues/3965

**Closed by bakerboy448** 2023-01-21 02:33 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by cannondale0815** [comment] 2023-01-21 02:36
> Duplicate of #4540

Perhaps -- but that issue is two years old and there isn't much useful information in there as to how to tactically proceed.
