### ISSUE TITLE
Forms Authentication Login to SSL Radarr is not working (v3)

### ISSUE THREAD

**Issue by EstrianTech** [Radarr/Radarr#5502] opened 2020-12-06 05:53 UTC
The password is accepted when attempting to log on, and fails to redirect to the Radarr main page.

This does not happen on non-SSL logins, and also does not happen on SSL when the login authentication is disabled.

```
2020-12-6 16:27:13.0|Info|Auth|Auth-Success ip ::ffff:192.168.0.1 username 'maskedname'
2020-12-6 16:27:13.0|Info|Auth|Auth-Unauthorized ip ::ffff:192.168.0.1 url 'https://host.name:8787'
```
and 
`2020-12-6 16:31:03.3|Trace|Http|Res: 238 [GET] /: 303.SeeOther (10 ms)`

As far as I know, this is a redirection error.

**Describe the bug**
The password is accepted when attempting to log on, and fails to redirect to the Radarr main page.
This does not happen on non-SSL logins, and also does not happen on SSL when the login authentication is disabled.

**To Reproduce**
1. Set up SSL and login Authentication (Form)
2. Try to login

**Expected behavior**
Logging in sucessfully and redirecting to main page.

**Screenshots**
N/A, just refreshes back to main login page.

**Platform Information (please complete the following information):**
 - OS: Windows 10 Pro 20H2 Build 19042.630
 - Docker: No
 - Mono or.NET Core Version: 3.1.10
 - Browser and Version: Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)
 - Radarr Version 3.0.0.4204
 - Radarr Branch develop

**Trace Logs**
[Trace Logs](https://pastebin.com/raw/qtKr6Ha5
)

**Comment by bakerboy448** [comment] 2020-12-06 16:24
Please fill out the template you blew away

**Comment by austinwbest** [comment] 2020-12-06 16:55
I'm on my phone but it's a duplicate @bakerboy448

**Comment by EstrianTech** [comment] 2020-12-06 22:17
Thanks, would you mind pointing me in the direction of the template? I cannot find references to it anywhere.

**Comment by EstrianTech** [comment] 2020-12-06 22:27
Edited main post.

**Comment by bakerboy448** [comment] 2020-12-06 22:57
Duplicate of #5444

**Closed by bakerboy448** 2020-12-06 22:57 UTC
Labels: information needed

**Comment by bakerboy448** [comment] 2020-12-06 22:59
How'd you create the issue with a blank form?

The only links that should be accessible should be one of the templates....so the typical thought is that if there is no template it was blown away by the user. Unless we have a hole to plug somewhere

**Comment by Ryonez** [comment] 2020-12-22 19:41
I can create issues with fasthub on my phone. That doesn't seem to even see templates. See #5605.
