### ISSUE TITLE
Custom format for size does not save decimal values

### ISSUE THREAD

**Issue by maltyjava** [Radarr/Radarr#7861] opened 2022-12-08 23:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently Radarr doesn't allow you to save a custom format size as anything but a whole (GB) number.

I use a lot of custom size formats and find this quite limiting. 

Radarr can see the size of releases down to 1 decimal place, so I'm assuming it's possible to have it work this way?

### Describe the solution you'd like

Ability to save custom format sizes in 100mb increments (eg 4.5GB or 8.2GB etc)
 

### Describe alternatives you've considered

 None that spring to mind

### Anything else?

This has been mentioned about a year ago in [#6147](https://github.com/Radarr/Radarr/issues/6147) and #7476 

The 0GB minimum size issue was fixed however I haven't seen anything regarding the decimal places issue.

[AB#4371](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4371)

**Comment by bakerboy448** [comment] 2022-12-08 23:05
Duplicate of #6147

**Closed by bakerboy448** 2022-12-08 23:05 UTC
Labels: Type: Feature Request, Status: Needs Triage
