### ISSUE TITLE
Rename Movie fails with SQL error Nightly Build 0.2.0.814

### ISSUE THREAD

**Issue by ChrisDurham** [Radarr/Radarr#1908] opened 2017-08-11 06:40 UTC
AFTER UPDATING TO THE LATEST NIGHTLY VERSION. 
This is a repeat of my post from yesterday as it's still failing to rename files : debug log follows 

17-8-11 07:34:13.2|Error|CommandExecutor|Error occurred while executing task RenameMovie

[v0.2.0.814] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
ambiguous column name: Id
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marr.Data.DataMapper.QueryToGraph[T](String sql, EntityGraph graph, List`1 childrenToLoad) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 624
   at Marr.Data.QGen.QueryBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:line 275
   at Marr.Data.QGen.SortBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 85
   at NzbDrone.Core.Tv.MovieService.GetMovies(IEnumerable`1 movieIds) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 147
   at NzbDrone.Core.MediaFiles.RenameMovieFileService.Execute(RenameMovieCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:line 187
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by chuckkay** [comment] 2017-08-11 18:08
confirmed

Error occurred while executing task RenameMovieFolder: SQL logic error or missing database
ambiguous column name: Id


Exception
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
ambiguous column name: Id
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marr.Data.DataMapper.QueryToGraph[T](String sql, EntityGraph graph, List`1 childrenToLoad) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 624
   at Marr.Data.QGen.QueryBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:line 275
   at Marr.Data.QGen.SortBuilder`1.ToList() in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(IEnumerable`1 ids) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 85
   at NzbDrone.Core.Tv.MovieService.GetMovies(IEnumerable`1 movieIds) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 147
   at NzbDrone.Core.MediaFiles.RenameMovieFileService.Execute(RenameMovieFolderCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:line 202
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by ghallford** [comment] 2017-08-11 18:13
Same error here

**Comment by galli-leo** [comment] 2017-08-11 22:32
Ah sorry I mistakenly marked your issue as fixed. Can confirm this happening, will try to fix tomorrow.

**Comment by weirdcrap** [comment] 2017-08-15 16:37
I can confirm this as well. I was absolutely freaking out because I thought I had broken my Radarr setup!!! Glad to see this is a known bug that will be fixed.

System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
ambiguous column name: Id
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x000f6] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.GetStatement (System.Int32 index) [0x00008] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteCommand:GetStatement (int)
  at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0011e] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
  at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.Common.DbCommand.ExecuteReader () [0x00000] in <cdc42ce9980a4941a4ca468faca7f261>:0 
  at (wrapper remoting-invoke-with-check) System.Data.Common.DbCommand:ExecuteReader ()
  at Marr.Data.DataMapper.QueryToGraph[T] (System.String sql, Marr.Data.EntityGraph graph, System.Collections.Generic.List`1[T] childrenToLoad) [0x00031] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:625 
  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00028] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:275 
  at Marr.Data.QGen.SortBuilder`1[T].ToList () [0x00000] in C:\projects\radarr-usby1\src\Marr.Data\QGen\SortBuilder.cs:176 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Collections.Generic.IEnumerable`1[T] ids) [0x0001d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:86 
  at NzbDrone.Core.Tv.MovieService.GetMovies (System.Collections.Generic.IEnumerable`1[T] movieIds) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:147 
  at NzbDrone.Core.MediaFiles.RenameMovieFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameMovieFolderCommand message) [0x00010] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs:202 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000ec] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:91 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41

**Comment by chuckkay** [comment] 2017-08-16 18:50
still happening on 0.2.0.831

**Closed** 2017-08-20 20:12 UTC
Labels: bug, priority:high, under investigation
