### ISSUE TITLE
Update fails when trying to install latest update with error: The authentication or decryption has failed.

### ISSUE THREAD

**Issue by JaredDiCioccio** [Radarr/Radarr#4264] opened 2020-03-31 14:59 UTC
**Describe the bug**
When clicking the "Install Latest" button in the web UI, the update fails. If I go to the release link the updater is trying to download (https://github.com/Radarr/Radarr/releases/download/v0.2.0.1480/Radarr.develop.0.2.0.1480.linux.tar.gz) , I can manually download it just fine. Other "can't update" issues seemed to involve different error messages than this.

**To Reproduce**
1. Go to 'System->Updates'
2. Click on 'Install Latest'
3. Toast error pops up saying [applicationupdate] Failed

**Expected behavior**
Radarr should download and install latest update

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.03 lts
 - Mono Version: 4.6.2 
 - Browser and Version: Firefox 74.0
 - Version. Radarr 0.2.0.1450

**Debug Logs**

```
20-3-31 10:54:26.3|Info|InstallUpdateService|Deleting old update files
20-3-31 10:54:26.3|Info|InstallUpdateService|Downloading update 0.2.0.1480
20-3-31 10:54:26.3|Warn|HttpClient|Failed to get response from: https://github.com/Radarr/Radarr/releases/download/v0.2.0.1480/Radarr.develop.0.2.0.1480.linux.tar.gz Error: SecureChannelFailure (The authentication or decryption has failed.)
20-3-31 10:54:26.3|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v0.2.0.1450] System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x00057] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x00011] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x00044] in <bd46d4d4f7964dfa9beea098499ab597>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x000c9] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x00019] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadFile (string,string)
  at NzbDrone.Common.Http.HttpClient.DownloadFile (System.String url, System.String fileName) [0x0005d] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:248
```

**Comment by Qstick** [comment] 2020-03-31 15:17
You may have to manually upgrade for this go around. There was a big that was fixed in 1480 that may be the cause of this.

**Comment by ta264** [comment] 2020-03-31 15:23
Mono is too old for HTTPS to work, upgrade it

**Closed by ta264** 2020-03-31 15:24 UTC
Labels: bug

**Comment by Qstick** [comment] 2020-03-31 15:26
Ooo I didn't even see that mono version 😁
