### ISSUE TITLE
[FEAT]: Optionally ignore/deprioritize packed content (torrents)

### ISSUE THREAD

**Issue by jkaberg** [Radarr/Radarr#6698] opened 2021-11-01 19:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently Radarr blindly swallows whatever seems like an legit download, this could and should be smarter. Like for instance when grabbing an .torrent, before sending the torrent to the download client Radarr could inspect the .torrent file to find out if the movie is in fact compressed (rar, zip etc.)

### Describe the solution you'd like

Expose an option to ignore/deprioritize packed content: Inspect the .torrent file, if rar set's or similar are detected score the release lower or ignore it completely (should be optional).

### Describe alternatives you've considered

The alternative is to use trackers that doesn't provide packed content. However many private trackers do allow mixed content (eg some packed, and some not), so that's an hit'n'miss.

### Anything else?

The whole idea here is to avoid packed content so that hardlinking will have an bigger effect. Compressed content tend to take up twice the space (unpacked + original compressed files for seeding) - while simply hardlinking the (not compressed) files doesn't use additional disk space.

[AB#1841](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1841)

**Comment by bakerboy448** [comment] 2021-11-01 20:47
Duplicate of https://github.com/Radarr/Radarr/issues/6476

duplicate of https://github.com/Radarr/Radarr/issues/1256

**Closed by bakerboy448** 2021-11-01 20:47 UTC
Labels: Type: Feature Request, Type: Duplicate

**Comment by austinwbest** [comment] 2021-11-01 23:56
Just to add, PRs are always welcome. If the option is implemented right and a PR added for it, it could be considered.
