### ISSUE TITLE
Radarr downloading the same movie NZB multiple times

### ISSUE THREAD

**Issue by 3phreal** [Radarr/Radarr#2216] opened 2017-10-25 18:38 UTC
This is a request to reopen issue #1108 and #1151

I've seen this problem in 0.2.0.846.

![image](https://user-images.githubusercontent.com/33040834/31912260-9343b890-b843-11e7-8c69-826f85cd3261.png)

![image](https://user-images.githubusercontent.com/33040834/31912277-a1f67f62-b843-11e7-9c6c-4a4c3c53b3aa.png)

![image](https://user-images.githubusercontent.com/33040834/31912293-adde8068-b843-11e7-917f-d6e0544b98ce.png)

Regards

**Comment by Hubszo** [comment] 2017-12-08 19:39
I have same problems after last update (Version 0.2.0.870). Exactly the same movie/release is downloaded several times with new movie folder created each time.
![capture](https://user-images.githubusercontent.com/26574723/33782024-3a7e8446-dc57-11e7-821b-a7d24bae844f.PNG)

**Comment by nixoncd** [comment] 2018-01-05 21:23
I just wanted to chime in and say I'm having the same issue. I just caught sabnzbd attempting it's 8th download in a row of the same movie.

**Comment by jat80** [comment] 2018-02-02 22:59
@galli-leo - Is this the same as https://github.com/Radarr/Radarr/issues/1428#issuecomment-362691585

I'm using NZB's as well.

**Comment by galli-leo** [comment] 2018-02-02 23:03
Duplicate of #1321

**Closed by galli-leo** 2018-02-02 23:03 UTC
