### ISSUE TITLE
Upgrading movies ERROR destination exist

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#958] opened 2017-03-01 07:29 UTC
**Description:**
Not sure why this error happens since if it try manually I can delete file or overwrite it normally. 

**Radarr Version:**
Radarr Ver. 0.2.0.418 nightly
**Logs:**

> [v0.2.0.418] System.IO.IOException: Destination already exists [/mnt/unionfs/movies/E.T. the Extra-Terrestrial (1982)/E.T. the Extra-Terrestrial (1982).mkv]
>   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath (System.String targetPath, Boolean overwrite) <0x418b5090 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) <0x418b4080 + 0x00613> in <filename unknown>:0 
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) <0x418b4000 + 0x0005b> in <filename unknown>:0 
>   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Tv.Movie movie, System.String destinationFilePath, TransferMode mode) <0x418b3990 + 0x00421> in <filename unknown>:0 
>   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie) <0x418b2cf0 + 0x000f7> in <filename unknown>:0 
>   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile (NzbDrone.Core.MediaFiles.MovieFile episodeFile, NzbDrone.Core.Parser.Model.LocalMovie localEpisode, Boolean copyOnly) <0x418b2930 + 0x002e6> in <filename unknown>:0 
>   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1 decisions, Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, ImportMode importMode) <0x418adab0 + 0x01372> in <filename unknown>:0

**Comment by onedr0p** [comment] 2017-03-01 08:30
I think this is a duplicate https://github.com/Radarr/Radarr/issues/895

**Comment by hotio** [comment] 2017-03-01 13:26
Can you see in the Movie History if the old file is trying to be deleted.

I'm assuming you are upgrading some movies, but they have a generic name, so old and new name are the same. Perhaps Radarr doesn't delete the old file because it sees that they have the same name? Then wants to move new file, but fails, because old file is still in place.

**Comment by ajkis** [comment] 2017-03-01 13:46
> Perhaps Radarr doesn't delete the old file because it sees that they have the same name? Then wants to move new file, but fails, because old file is still in place.

Of course the movie have same name ?
If radarr cant overwrite the movie then Cutoff Unmet can be scraped as feature as no movie can be ever replaced. ( this works on sonarr )
Assuming you they are all in same container eg .mkv .mp4 etc...

**Comment by hotio** [comment] 2017-03-01 14:04
Lot's of things working in Sonarr, this is Radarr however, pre-release sofware, forked about a month ?? ago.

Radarr was not able to delete a file some time ago, perhaps it's still funky.

**Comment by ajkis** [comment] 2017-03-01 18:52
Maybe implement delete prior move as it would so if container was not the same eg
If I upgrade Movie Title (2016).mp4 with .mkv version it will delete .mp4 before copying new one.
Exactly same functionality could be added for all upgrades and not just if its different container.

**Comment by onedr0p** [comment] 2017-03-01 19:54
It should be handled like sonarr does it. In fact it works for me on my local machine and server when upgrading. So there is a special case for you why it's happening.

**Comment by ajkis** [comment] 2017-03-01 20:59
Based on discord iam not alone and sonarr does not have problems with upgrades thats why i wonder whats changed.

Atm I just made my self a post process script to fix it: https://github.com/ajkis/scripts/blob/master/radarr/radarr-upgradefix.sh

Basically on download I check if the file already exist and delete it .. actually i just delete the folder since I dont want to keep subtitles of previous version as they more then likely wont be synced.

**Comment by onedr0p** [comment] 2017-03-01 23:01
Closing because this is a duplicate of #895

**Closed by onedr0p** 2017-03-01 23:01 UTC
