### ISSUE TITLE
Problem searching Spanish

### ISSUE THREAD

**Issue by Diablobait** [Radarr/Radarr#2732] opened 2018-04-23 02:07 UTC
Hello, on spanish some names go with ´, and dont find the movies because they normally upload the torrent without, for example radarr try to search "Máquina de guerra" but the torrent is "Maquina de guerra", is possible to fix this? thank you so much

**Comment by galli-leo** [comment] 2018-04-24 07:02
Can you please provide some debug logs?

**Comment by Diablobait** [comment] 2018-04-29 23:35
```
18-4-30 01:29:21.5|Info|NzbSearchService|Searching 3 indexers for [Doble traiciÃ³n]
18-4-30 01:29:21.5|Debug|Torznab|Downloading Feed https://xxxxxxxx/jackett/api/v2.0/indexers/xbytesv2/results/torznab/api?t=search&cat=100016,2040&extended=1&apikey=(removed)&offset=0&limit=100&q=backstabbing%20for%20beginners
18-4-30 01:29:21.5|Debug|Torznab|Downloading Feed https://xxxxxxxx/jackett/api/v2.0/indexers/puntorrent/results/torznab/api?t=search&cat=100057,100109,2040,100110,100058,100056&extended=1&apikey=(removed)&offset=0&limit=100&q=backstabbing%20for%20beginners
18-4-30 01:29:21.5|Debug|Torznab|Downloading Feed https://xxxxxxxxxx/jackett/api/v2.0/indexers/hdspain/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=backstabbing%20for%20beginners%202018
18-4-30 01:29:21.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://xxxxxxxxxxxx/jackett/api/v2.0/indexers/puntorrent/results/torznab/api?t=search&cat=100057,100109,2040,100110,100058,100056&extended=1&apikey=(removed)&offset=0&limit=100&q=backstabbing for beginners failed. RemoteCertificateChainErrors
18-4-30 01:29:22.5|Debug|Torznab|Downloading Feed https://xxxxxxxxxxxx/jackett/api/v2.0/indexers/puntorrent/results/torznab/api?t=search&cat=100057,100109,2040,100110,100058,100056&extended=1&apikey=(removed)&offset=0&limit=100&q=doble%20traici%c3%b3n
18-4-30 01:29:23.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://xxxxxxxx/jackett/api/v2.0/indexers/hdspain/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=backstabbing for beginners 2018 failed. RemoteCertificateChainErrors
18-4-30 01:29:24.3|Debug|Torznab|Downloading Feed https://xxxxxxx4/jackett/api/v2.0/indexers/hdspain/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=doble%20traici%c3%b3n%202018
18-4-30 01:29:25.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://xxxxxxx/jackett/api/v2.0/indexers/xbytesv2/results/torznab/api?t=search&cat=100016,2040&extended=1&apikey=(removed)&offset=0&limit=100&q=backstabbing for beginners failed. RemoteCertificateChainErrors
18-4-30 01:29:26.0|Debug|Torznab|Downloading Feed https://xxxxxxxxx/jackett/api/v2.0/indexers/xbytesv2/results/torznab/api?t=search&cat=100016,2040&extended=1&apikey=(removed)&offset=0&limit=100&q=doble%20traici%c3%b3n
18-4-30 01:29:27.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://xxxxxxxxx/jackett/api/v2.0/indexers/puntorrent/results/torznab/api?t=search&cat=100057,100109,2040,100110,100058,100056&extended=1&apikey=(removed)&offset=0&limit=100&q=doble traiciÃ³n failed. RemoteCertificateChainErrors
18-4-30 01:29:29.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://xxxxxxxx/jackett/api/v2.0/indexers/hdspain/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=doble traiciÃ³n 2018 failed. RemoteCertificateChainErrors
18-4-30 01:29:30.7|Debug|RTorrentProxy|Executing remote method: d.multicall2
18-4-30 01:29:30.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://localhost//rutorrent/plugins/httprpc/action.php failed. RemoteCertificateChainErrors
18-4-30 01:29:30.7|Info|PreDBService|Starting PreDB Sync
18-4-30 01:29:30.7|Info|NetImportSearchService|No lists are enabled for auto-import.
18-4-30 01:29:30.9|Debug|X509CertificateValidationPolicy|Certificate validation for https://localhost//rutorrent/plugins/httprpc/action.php failed. RemoteCertificateChainErrors
18-4-30 01:29:31.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://xxxxxxxx/jackett/api/v2.0/indexers/xbytesv2/results/torznab/api?t=search&cat=100016,2040&extended=1&apikey=(removed)&offset=0&limit=100&q=doble traiciÃ³n failed. RemoteCertificateChainErrors
18-4-30 01:29:31.7|Debug|RTorrent|Retrieved metadata of 50 torrents in client
18-4-30 01:29:32.2|Debug|NzbSearchService|Total of 0 reports were found for [Doble traiciÃ³n] from 3 indexers
18-4-30 01:29:32.2|Info|DownloadDecisionMaker|No results found

```


Problem is here: 18-4-30 01:29:21.5|Info|NzbSearchService|Searching 3 indexers for [Doble traiciÃ³n] is trying to search for Doble traiciÃ³n and the name is Doble traición, and in the torrent tracker Doble Traicion

**Comment by Diablobait** [comment] 2018-05-03 08:29
Yeah, thats the problem we normally upload all without dpecial characters and when ttying to search dont find the movie, the solution maybe can be an option to introduce the nsme we want to search?

**Comment by galli-leo** [comment] 2018-05-08 18:34
Hmm yeah, I will have to come up with some solution. Other indexers have similar issues (also removal of e.g. 'of' from titles causes issues with some)

Duplicate of #2565

**Closed by galli-leo** 2018-05-08 18:34 UTC
Labels: information needed
