### ISSUE TITLE
Add ability to custom filter via Language

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#7134] opened 2022-03-15 09:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Filtering for English, Spanish, French etc would be useful.

### Describe the solution you'd like

Filtering for English, Spanish, French etc would be useful.

### Describe alternatives you've considered

Custom Format labelling but still can't filter with them.

### Anything else?

N/A

[AB#2794](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2794)

**Comment by bakerboy448** [comment] 2022-03-15 12:23
Duplicate of https://github.com/Radarr/Radarr/issues/6657

**Closed by bakerboy448** 2022-03-15 12:23 UTC
Labels: Type: Feature Request, Status: Needs Triage
