### ISSUE TITLE
Log shows sourcePath rather than destinationPath as final location when moving movies to a new root folder

### ISSUE THREAD

**Issue by ChrisBaker97** [Radarr/Radarr#5410] opened 2020-11-26 20:33 UTC
**Describe the bug**
When one or more movies are reorganized into a new root folder, the post-move log entry shows the original location as the final destination, rather than the new location. (The move itself happens as expected—it's just an error in the logs.) For example:

```
2020-11-26 14:39:01.4|Info|MoveMovieService|Moving Fast & Furious Presents: Hobbs & Shaw from '/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019)' to '/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019) {imdb-tt6806448}' (1/1)
2020-11-26 14:39:01.4|Info|MoveMovieService|Fast & Furious Presents: Hobbs & Shaw moved successfully to /volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019)
```

**To Reproduce**
1. Go to the Movies tab
2. Click on Movie Editor
3. Select one or more movies
4. Choose a different Root Folder at the bottom (or choose the same one after changing to a different folder naming scheme)
5. View the log file or go to System | Events

**Expected behavior**
I'd expect the log to read as follows:
```
2020-11-26 14:39:01.4|Info|MoveMovieService|Moving Fast & Furious Presents: Hobbs & Shaw from '/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019)' to '/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019) {imdb-tt6806448}' (1/1)
2020-11-26 14:39:01.4|Info|MoveMovieService|Fast & Furious Presents: Hobbs & Shaw moved successfully to /volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019) {imdb-tt6806448}
```

**Screenshots**
N/A

**Platform Information (please complete the following information):**
 - OS: Linux 3.10.105 (Synology DSM)
 - Docker: Yes
 - .NET Core Version: 3.1.10
 - Radarr Version: 3.0.0.4142
 - Radarr Branch: nightly (via linuxserver.io)

<details>
<summary>**Trace Logs**</summary>

```
2020-11-26 15:13:06.5|Trace|Http|Req: 25799 [PUT] /api/v3/movie/editor (from 10.97.1.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15)
2020-11-26 15:13:06.5|Trace|CommandQueueManager|Publishing BulkMoveMovie
2020-11-26 15:13:06.5|Trace|CommandQueueManager|Checking if command is queued or started: BulkMoveMovie
2020-11-26 15:13:06.5|Trace|CommandQueueManager|Inserting new command: BulkMoveMovie
2020-11-26 15:13:06.7|Debug|MovieService|Updating 1 movie
2020-11-26 15:13:06.7|Trace|MovieService|Updating: Fast & Furious Presents: Hobbs & Shaw
2020-11-26 15:13:06.7|Trace|CommandExecutor|BulkMoveMovieCommand -> MoveMovieService
2020-11-26 15:13:06.7|Trace|CommandQueueManager|Marking command as started: BulkMoveMovie
2020-11-26 15:13:06.7|Trace|MovieService|Changing path for Fast & Furious Presents: Hobbs & Shaw to /volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019) {imdb-tt6806448}
2020-11-26 15:13:06.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:06.9|Info|MoveMovieService|Moving 1 movies to '/volume1/Media/Video/Movies'
2020-11-26 15:13:06.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:06.9|Info|MoveMovieService|Moving Fast & Furious Presents: Hobbs & Shaw from '/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019)' to '/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019) {imdb-tt6806448}' (1/1)
2020-11-26 15:13:06.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:06.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:06.9|Debug|DiskTransferService|Move Directory [/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019)] > [/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019) {imdb-tt6806448}]
2020-11-26 15:13:07.0|Debug|DiskTransferService|Rename Directory [/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019)] > [/volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019) {imdb-tt6806448}]
2020-11-26 15:13:07.0|Info|MoveMovieService|Fast & Furious Presents: Hobbs & Shaw moved successfully to /volume1/Media/Video/Movies/Fast & Furious Presents Hobbs & Shaw (2019)
2020-11-26 15:13:07.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:07.0|Trace|EventAggregator|Publishing MovieMovedEvent
2020-11-26 15:13:07.0|Info|MoveMovieService|Finished moving 1 movies to '/volume1/Media/Video/Movies'
2020-11-26 15:13:07.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:07.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:07.0|Trace|CommandQueueManager|Updating command status
2020-11-26 15:13:07.2|Debug|MovieService|1 movie updated
2020-11-26 15:13:07.2|Trace|Http|Res: 25799 [PUT] /api/v3/movie/editor: 202.Accepted (699 ms)
2020-11-26 15:13:07.2|Debug|Api|[PUT] /api/v3/movie/editor: 202.Accepted (699 ms)
2020-11-26 15:13:07.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-11-26 15:13:07.4|Trace|EventAggregator|Publishing CommandExecutedEvent
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2020-11-26 15:13:07.4|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2020-11-26 15:13:07.4|Trace|CommandExecutor|BulkMoveMovieCommand <- MoveMovieService [00:00:00.2617019]
2020-11-26 15:13:07.4|Trace|Http|Req: 25800 [GET] /api/v3/command (from 10.97.1.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15)
2020-11-26 15:13:07.4|Trace|CommandQueueManager|Getting all commands
2020-11-26 15:13:07.4|Trace|Http|Res: 25800 [GET] /api/v3/command: 200.OK (6 ms)
2020-11-26 15:13:07.4|Debug|Api|[GET] /api/v3/command: 200.OK (6 ms)
2020-11-26 15:13:07.8|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2020-11-26 15:13:07.8|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthModule
2020-11-26 15:13:07.8|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthModule
2020-11-26 15:13:07.8|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthModule
2020-11-26 15:13:07.8|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthModule
2020-11-26 15:13:07.8|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2020-11-26 15:13:07.8|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2020-11-26 15:13:07.8|Trace|Http|Req: 25801 [GET] /api/v3/health (from 10.97.1.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15)
2020-11-26 15:13:07.8|Trace|Http|Res: 25801 [GET] /api/v3/health: 200.OK (2 ms)
2020-11-26 15:13:07.8|Debug|Api|[GET] /api/v3/health: 200.OK (2 ms)
```
</details>

**Proposed Solution**
I don't have a development environment set up to test this, but I think the following patch should do the trick:
```diff
diff --git a/src/NzbDrone.Core/Movies/MoveMovieService.cs b/src/NzbDrone.Core/Movies/MoveMovieService.cs
index 9e1fbb03e..2338a6e18 100644
--- a/src/NzbDrone.Core/Movies/MoveMovieService.cs
+++ b/src/NzbDrone.Core/Movies/MoveMovieService.cs
@@ -56,7 +56,7 @@ private void MoveSingleMovie(Movie movie, string sourcePath, string destinationP
                 _diskProvider.CreateFolder(new DirectoryInfo(destinationPath).Parent.FullName);
                 _diskTransferService.TransferFolder(sourcePath, destinationPath, TransferMode.Move);

-                _logger.ProgressInfo("{0} moved successfully to {1}", movie.Title, movie.Path);
+                _logger.ProgressInfo("{0} moved successfully to {1}", movie.Title, destinationPath);

                 _eventAggregator.PublishEvent(new MovieMovedEvent(movie, sourcePath, destinationPath));
             }
```

[AB#752](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/752)

**Comment by bakerboy448** [comment] 2020-11-27 03:14
that looks like it should do it; i'll test this tomorrow

**Comment by Qstick** [comment] 2020-11-27 04:38
This seems to log fine for me 90% of the time, but I can occasionally reproduce this.

Working
```
[Info] MoveMovieService: Moving The Ballerina from 'D:\Movies\The Ballerina (2017)' to 'D:\Movies\The Ballerina (2017) {imdb-tt3517984}' (1/1)
[Debug] DiskTransferService: Move Directory [D:\Movies\The Ballerina (2017)] > [D:\Movies\The Ballerina (2017) {imdb-tt3517984}]
[Debug] DiskTransferService: Rename Directory [D:\Movies\The Ballerina (2017)] > [D:\Movies\The Ballerina (2017) {imdb-tt3517984}]
[Info] MoveMovieService: The Ballerina moved successfully to D:\Movies\The Ballerina (2017) {imdb-tt3517984}
```

Not Working
```
[Debug] MovieService: Updating 1 movie
[Trace] CommandExecutor: BulkMoveMovieCommand -> MoveMovieService
[Trace] MovieService: Updating: The Ballerina
[Trace] CommandQueueManager: Marking command as started: BulkMoveMovie
[Trace] MovieService: Changing path for The Ballerina to D:\Movies\The Ballerina (2017) {imdb-tt3517984}
[Info] MoveMovieService: Moving 1 movies to 'D:\Movies'
[Info] MoveMovieService: Moving The Ballerina from 'D:\Movies\The Ballerina (2017)' to 'D:\Movies\The Ballerina (2017) {imdb-tt3517984}' (1/1)
[Debug] DiskTransferService: Move Directory [D:\Movies\The Ballerina (2017)] > [D:\Movies\The Ballerina (2017) {imdb-tt3517984}]
[Debug] DiskTransferService: Rename Directory [D:\Movies\The Ballerina (2017)] > [D:\Movies\The Ballerina (2017) {imdb-tt3517984}]
[Info] MoveMovieService: The Ballerina moved successfully to D:\Movies\The Ballerina (2017)
[Trace] EventAggregator: Publishing MovieMovedEvent
[Info] MoveMovieService: Finished moving 1 movies to 'D:\Movies'
```

I can see this possibly being a timing issue as right after the API module pushes the command for the move it calls to update the movie in the db with the new path... so depending on how quick the command executes the movie may not be updated in the db. 

If this is timing this can also create an issue if the move fails. Currently we call and revert the path to the movie service if that happens, but if we try move and revert before the original update then the new path ends up being written to DB (Likely a slim chance due to the time it takes for the move to fail, but possible?)

@markus101 this is all Sonarr code, thoughts? Should we update the movies(series) prior to sending off the commands to move from MovieEditorModule(SeriesEditorModule)?

**Comment by ChrisBaker97** [comment] 2020-11-27 05:17
I moved 1,000 movie folders yesterday. I just skimmed through the logs, and I didn't see a single example of it reporting correctly, so at least on my configuration, it's close to, if not 100% reproducible.

**Comment by Qstick** [comment] 2020-11-27 06:00
15 of the 20 runs I did logged correctly on my side. Granted most were single movie runs... But I had to work hard to get a couple to miss. Likely a few factors at play given they are separate processes fired off back to back.


```
[Info] MoveMovieService: Moving The Glimmer Man from 'D:\Movies 2\The Glimmer Man (1996)' to 'D:\Movies 2\The Glimmer Man (1996) {imdb-tt0116421}' (1/1)
[Trace] EventAggregator: Publishing CommandUpdatedEvent
[Trace] EventAggregator: CommandUpdatedEvent -> CommandModule
[Trace] EventAggregator: CommandUpdatedEvent <- CommandModule
[Trace] EventAggregator: CommandUpdatedEvent -> CommandModule
[Trace] EventAggregator: CommandUpdatedEvent <- CommandModule
[Debug] DiskTransferService: Move Directory [D:\Movies 2\The Glimmer Man (1996)] > [D:\Movies 2\The Glimmer Man (1996) {imdb-tt0116421}]
[Debug] DiskTransferService: Rename Directory [D:\Movies 2\The Glimmer Man (1996)] > [D:\Movies 2\The Glimmer Man (1996) {imdb-tt0116421}]
[Info] MoveMovieService: The Glimmer Man moved successfully to D:\Movies 2\The Glimmer Man (1996) {imdb-tt0116421}
```

**Comment by bakerboy448** [comment] 2022-07-27 18:13
Probably fixed with https://github.com/Radarr/Radarr/commit/70b22e483a15495e35474fd0e7daadd18221fd49

is the race condition still an issue?

**Closed** 2022-07-28 04:11 UTC
Labels: Type: Bug, Status: Info Needed, Status: Confirmed
