### ISSUE TITLE
[minor bug] custom format regex fail in specific case.

### ISSUE THREAD

**Issue by KBlixt** [Radarr/Radarr#7266] opened 2022-05-02 19:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a custom format called "3D edition" to detect if the release is a 3D version. the regex is simply "3D".
This works. But I recently discovered a release where it failed to mark a release as "3D edition" even though there obviously were a 3D in the name of the release.

from indexer nzbdgeek.info:
The Avengers 3D (2012) 1080p BluRay - P3n6u1n

### Expected Behavior

the release to be marked with the custom format "3D edition"

### Steps To Reproduce

1. create custom format containing "3D" regex for the release name
2. search for the movie "the avengers (2012)" with nzbgeek.info indexer
3. find "The Avengers 3D (2012) 1080p BluRay - P3n6u1n" not marked as the newly created custom format.

### Environment

```markdown
Radarr: latest docker from linuxserver/radarr
```

### What branch are you running?

Master

### Trace Logs?

I don't know where this is logged?

[AB#3105](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3105)

**Comment by bakerboy448** [comment] 2022-05-02 19:24
Duplicate of https://github.com/Radarr/Radarr/issues/7004

**Closed by bakerboy448** 2022-05-02 19:24 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by KBlixt** [comment] 2022-05-02 19:31
oh shoot, your right. I hard ban groups that don't follow naming conventions. but missed the order of year/edition. thank you :)
