### ISSUE TITLE
 [Feature Request] Identifying use of subfolders in Movie Folder Names on library imports.

### ISSUE THREAD

**Issue by PeterKse** [Radarr/Radarr#6496] opened 2021-08-01 10:40 UTC
**Is your feature request related to a problem? Please describe.**

When downloading movies, they can only be placed in a folder under the root folder perhaps as "MovieName (2021)". 

When having a large library, it is nice to divide your movies into subfolders. I personally have them as Year\MovieName(year). Makes life easier the few times we manually work on our drive folders (for whatever reason). 

The only problem is, when importing files Radarr doesn't understand this. So i couldn't add "a bunch" of movies copied manually into my library 

**Describe the solution you'd like**

Under Settings -> Media Management, we indicate with Movie Folder Name "{Release Year}\{Movie Title} ({Release Year})" and Radarr should be able to understand this naming format includes subfolder and treat it as such when it's processing through folders with the Library Import tool. This is nothing more than  text string and identifying a "\" sign to understand it, it seems to me.

**Describe alternatives you've considered**

I know no other automated way of doing this operation (library imports). This would help to automate any re-structuring of the library, moving files, copying in large amount of movies and quickly indentifying which you have or not already have, etc.

[AB#1310](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1310)

**Comment by bakerboy448** [comment] 2021-08-01 12:18
Duplicate of #153

**Closed by bakerboy448** 2021-08-01 12:18 UTC
Labels: Type: Feature Request
