### ISSUE TITLE
Quality not matching media info

### ISSUE THREAD

**Issue by burgback** [Radarr/Radarr#407] opened 2017-01-24 01:06 UTC
DVDs are showing 720x480 resolution, which is correct..  The quality is showing up as HDTV-720p.  I do have a few items that are showing up as DVD at a 720x400 or 704x304 resolution.  Movies showing up as DVD also are AVC whereas the 720x480 files are MPEG-2 Video.

![capture](https://cloud.githubusercontent.com/assets/25312074/22229702/5aa1b01e-e1a7-11e6-83fd-630364c8cbbe.PNG)

**Comment by galli-leo** [comment] 2017-01-24 08:41
That's because Radarr tries to guess the quality according to the media info, if it cannot be found in the filename. I will add a feature to change the quality of a found file. (Duplicate of #368)

**Closed by galli-leo** 2017-01-24 08:41 UTC

**Comment by methanoid** [comment] 2017-03-14 15:03
Every file I try to change the quality on seems to be stuck on spinning wheel.. ie Radarr wont do it...
We need to be able to set quality especially when it mis-identifies something

**Comment by galli-leo** [comment] 2017-03-14 15:23
@methanoid Yeah that's an issue because of some js fixes. I should have a fix for that ready in the next couple of hours

**Comment by methanoid** [comment] 2017-04-06 19:07
Hi, has the fix made it out? I noticed same problem. I'm using Radarr in Linuxserver.io's docker container which auto updates on every restart.... so I should be on latest official code?
