### ISSUE TITLE
Ability to manually Map/Fix IDs to movies that are changed on TMDb.

### ISSUE THREAD

**Issue by resonanttoe** [Radarr/Radarr#4414] opened 2020-05-13 09:07 UTC
**Is your feature request related to a problem? Please describe.**
When a TMDb ID is changed Radarr alerts and offers a wiki article link suggesting manual user [intervention](https://github.com/Radarr/Radarr/wiki/Health-checks#movie-was-removed-from-tmdb), in order to remap the movie in Radarr, you have to remove and readd to the library

<img width="1033" alt="Screenshot 2020-05-13 at 10 59 34" src="https://user-images.githubusercontent.com/4146864/81792833-e1df3480-9508-11ea-97c8-b871e1e8f2eb.png">

**Describe the solution you'd like**
The ability to manually fix mapping to new IDs - Similar to Plex's "Fix Metadata/Fix Match" feature, where you can manually override the TMDb to Movie Mapping. (En masse would be nice too)

**Describe alternatives you've considered**
On refresh and update, when seeing an invalid ID, Radarr could look the movie up by name and automatically readd the correct mapping - I like the manual intervention a bit more as it probably handles weird edge cases and situations where the user wants a bit more control.

**Additional context**
Some example movie IDs are

Movie Name | Old ID (Reported in Radarr) | New ID (Found by searching)
------------ | -------------| -------------
63 Up | 567273 | 698102
Surviving R Kelly | 600100 | 85389
The Legend of Zelda: Retrospective* | 18286 | 146748

*This one may not be entirely accurate because the title changed in the TMDB too

**Error messages from Events** 
<img width="803" alt="Screenshot 2020-05-13 at 10 59 44" src="https://user-images.githubusercontent.com/4146864/81792841-e3a8f800-9508-11ea-9eb3-5537401b77e6.png">

**Version and platform**
Version    3.0.0.2915
.NET Core    Yes
DB Migration    172
AppData directory    /home/sonarr/.config/Radarr
Startup directory    /opt/Radarr
Mode:    Console
Platform: Ubuntu 20.04 (Container) - Linux Sonarr 5.3.18-2-pve #1 SMP PVE 5.3.18-2 (Sat, 15 Feb 2020 15:11:52 +0100) x86_64 x86_64 x86_64 GNU/Linux

**Comment by Qstick** [comment] 2020-05-16 19:54
Essentially a dupe of #355

**Closed by Qstick** 2020-05-16 19:54 UTC
Labels: feature request
