### ISSUE TITLE
Movie Collection Sorting

### ISSUE THREAD

**Issue by apollotuba87** [Radarr/Radarr#8857] opened 2023-07-21 21:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

While films can be associated with a collection, the group of movies in a collection cannot currently be sorted as a cohesive group.

### Describe the solution you'd like

For Movie Collections such as the Marvel Cinematic Universe, Star Wars, James Bond Films, etc. to be treated by Radarr much like Sonarr treats a single series - all films sent to a single folder for the collection, and renamed with the number of the film (ie for MCU 01 - Iron Man, 02 - The Incredible Hulk, etc).  Perhaps allowing the order of the films in the franchise to be preset in order of release but user-definable for franchises that are released out of chronological order such as Star Wars (or where the user may want to define a nonstandard sequence like the Machete Order for the Star Wars films).  Perhaps have it able - though not required - to split the franchise similarly to Sonarr splitting seasons, only instead of subfolders like Season 01, Season 02, etc it could split by either franchise characteristic or user defined characteristic (ie for MCU, Phase 1, Phase 2, etc; Star Wars Original Trilogy, Prequel Trilogy, Sequel Trilogy, and Supplemental Films; or for the Bond films Connery Era, Moore Era, Brosnan Era, etc.).

It would also be great if Collections themselves were searchable to add an entire collection to your library at once.

### Describe alternatives you've considered

I saw that some of the issues with sorting films presently are due to this project's development from Sonarr, but in this case that might be advantageous as I'm seeking to bring Sonarr functionality into Radarr here as opposed to trying to get non-Collection movies sorted.

### Anything else?

Thanks for your consideration :)

**Comment by bakerboy448** [comment] 2023-07-22 02:35
Duplicate of https://github.com/Radarr/Radarr/issues/153

**Closed by bakerboy448** 2023-07-22 02:35 UTC
Labels: Type: Feature Request, Status: Needs Triage
