### ISSUE TITLE
[Calendar] Color scheme is rather confusing. Redo the whole thing.

### ISSUE THREAD

**Issue by bassrock** [Radarr/Radarr#601] opened 2017-02-04 19:57 UTC
Currently when looking at the calendar view it is showing In Cinema Dates and Physical Release Dates, both as light blue which correspond to the In Cinema Key:

<img width="432" alt="screen shot 2017-02-04 at 11 55 22 am" src="https://cloud.githubusercontent.com/assets/1010384/22621128/eb2b3d80-ead0-11e6-9430-39da165d7ff0.png">

There should be a new color key added for Physical Release Dates, so that you can tell the difference between the dates in the calendar view.

**Comment by geogolem** [comment] 2017-02-10 05:13
maybe this is related to: https://github.com/Radarr/Radarr/issues/470

**Comment by geogolem** [comment] 2017-02-10 21:39
im not sure if this is what you are referring to but take a look at this screenshot: 
![image](https://cloud.githubusercontent.com/assets/23205277/22814878/2a1a2a9e-ef25-11e6-85e3-8561b8234907.png)

Moanna is currently In Cinemas, but will be getting a physical release on Feb 20th... -- so the movie being turqoise and marked In Cinemas on Feb 20th is confusing.

likewise, John WIck 2 will be in theaters on Feb 9th... but we are hsowing it as "Announced" on Feb 9th...

i guess the issue is that the dates on the calendar are the dates the state shoud change, but the colour is showing the current colour.. not the colour it will change to on that day....

not sure if this is related.. but just an observation i noticed.

@galli-leo : I now realize this isn't a bug but rather just the way it was implemented. Im just pasting the discussion here for reference..

**Comment by bassrock** [comment] 2017-02-10 21:54
@geogolem Yes that is the issue that is occuring. Announced should really be in cinemas and in cinemas should really be physical release.

**Closed** 2020-07-11 05:53 UTC
Labels: aphrodite, confirmed, enhancement, priority:low, ui
