### ISSUE TITLE
Quality maximum size limit insufficient

### ISSUE THREAD

**Issue by DominicMe** [Radarr/Radarr#2302] opened 2017-11-29 19:49 UTC
The maximum size limit in the Quality tab seems to be just over 27GB. This is not sufficient anymore especially for 2160p content. /there are many releases over 50GB which makes 27GB limit insuficient.
It seems to be that the maximum limit should approximately match or better still exceed the maximum possible movie size. In practical terms this causes Radarr to snatch unwanted remux releases for non-remux profile when set to Unlimited or if set to ~27GB limit it ignores these larger non-remux releases. Could this limit be increased? Doubling the limit would be sufficient for now.

**Comment by galli-leo** [comment] 2017-12-12 21:26
The limit is only present on the ui. You can set it directly in the db. There is an issue already open to increase it in the UI, so gonna close this.

**Closed by galli-leo** 2017-12-12 21:26 UTC

**Comment by DominicMe** [comment] 2017-12-12 22:49
Please link the other open issue here please. Also a link to some info on editing radarr db would be great too, it's a difficult area to find stuff on google at least it seems like that.

**Comment by galli-leo** [comment] 2017-12-12 22:55
See the wiki for where to locate the radarr.db file (AppData Directory). Then use any sqlite editor (http://sqlitebrowser.org is good). Then edit the QualityDefinitions Table (The values are used for MB/min of runtime, default is 100)

**Comment by galli-leo** [comment] 2017-12-12 22:57
Duplicate of #1797

**Comment by DominicMe** [comment] 2017-12-12 23:48
@galli-leo Thanks! I was hoping it was as simple as that :) In linux the file is still using the old name for db: /var/lib/radarr/nzbdrone.db

For anyone else with the same issue:
To get the actual desired value multiply ?GB by 7.31528895391368. For example 36GB*7.3=~263. Values above the max of the UI do not show up even after editing it in the db so should not be touched in the UI.
