### ISSUE TITLE
Allow custom filters to be created using custom formats

### ISSUE THREAD

**Issue by E-Vix** [Radarr/Radarr#7237] opened 2022-04-22 08:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Filtering movies for specific custom formats for better library maintenance and performing bulk searches for movies that do not match these custom formats.

### Describe the solution you'd like

Adding the ability to use custom formats in custom filters and to be able to display custom format titles in table view of the movie library

### Describe alternatives you've considered

Manually going through each movie to see the custom formats and performing searches one by one

### Anything else?

Custom formats are great :D

[AB#3019](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3019)

**Comment by ta264** [comment] 2022-04-22 08:30
This is a duplicate of many requests

**Closed by ta264** 2022-04-22 08:30 UTC
Labels: Type: Feature Request, Status: Needs Triage
