### ISSUE TITLE
Ability to filter via Custom Formats on home page

### ISSUE THREAD

**Issue by itschasa** [Radarr/Radarr#10031] opened 2024-05-18 21:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I find it irritating how I can't see all the films that have a certain custom format attached to them. I want to research all films that have this specific format again, but there's no way to do this without finding them within the huge collection I have.

### Describe the solution you'd like

An option in the Custom Filters menu called 'Custom Format', which could have 'is' or 'is not', then a list of all custom formats that are registered.

Only needs to handle one custom format per line.

### Describe alternatives you've considered

Can't think of any, I suppose.

### Anything else?

Mockup:

![image](https://github.com/Radarr/Radarr/assets/79016507/3259efcd-bb97-4ef1-9d8b-79e3712c8a62)

**Comment by bakerboy448** [comment] 2024-05-18 21:56
Duplicate of https://github.com/Radarr/Radarr/issues/5909

**Closed by bakerboy448** 2024-05-18 21:56 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by itschasa** [comment] 2024-05-18 21:58
> > [I have _not_ searched the existing open and closed issues](https://github.com/Radarr/Radarr/issues?q=is%3Aissue+filter+custom+formats+is%3Aclosed)
> 
> :(

I couldn't actually find that issue, sorry 😔
