### ISSUE TITLE
Support Torznab tags as flags

### ISSUE THREAD

**Issue by jalaziz** [Radarr/Radarr#7951] opened 2023-01-02 07:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I recently started using Prowlarr for indexer integration and noticed that indexer flags were no longer working correctly. In particular, the `PTP_Approved` flag was no longer working.

### Describe the solution you'd like

It appears that Prowlarr provides indexer flags using tags. For example:
```
      <torznab:attr name="tag" value="approved" />
      <torznab:attr name="tag" value="scene" />
```

or

```
      <torznab:attr name="tag" value="golden" />
      <torznab:attr name="tag" value="approved" />
```

It would be great if Torznab tags could be used as indexer flags.

### Describe alternatives you've considered

I've removed indexer flags for the time being as I can't seem to find an alternative way to get them to work.

### Anything else?

Seems like this has been brought up on [Reddit](https://www.reddit.com/r/prowlarr/comments/t0gesr/does_prowlarr_supports_indexer_flags/) before.

[AB#4608](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4608)

**Comment by bakerboy448** [comment] 2023-01-02 13:49
Duplicate of https://github.com/Radarr/Radarr/issues/6268

**Closed by bakerboy448** 2023-01-02 13:49 UTC
Labels: Type: Feature Request, Status: Needs Triage
