### ISSUE TITLE
Searching for movies with atpostrophes wont match titles without one

### ISSUE THREAD

**Issue by ardevd** [Radarr/Radarr#3254] opened 2018-12-20 12:09 UTC
**Describe the bug**
Example: Searching for a movie called "Now it's time" will yield no results even though the tracker contains an entry called "Now its time". 

**Expected behavior**
Searching for "Now it's time" should also match on "Now its time".

**Comment by galli-leo** [comment] 2018-12-20 13:08
Duplicate of #2565

**Closed by galli-leo** 2018-12-20 13:08 UTC
