### ISSUE TITLE
Bulk Import uses GB's of memory and does not release

### ISSUE THREAD

**Issue by winno** [Radarr/Radarr#1503] opened 2017-05-10 07:25 UTC
When bulk importing 100 movies the memory usage jumps up to 3GB.
Attached image shows the memory increasing as the import runs. It is only released when I restart Radarr.

I am running this under Docker on Synology NAS

Radarr Version 0.2.0.691 - clean install
![2017-05-10](https://cloud.githubusercontent.com/assets/10085583/25927409/6c913bde-3628-11e7-8cab-fa4a49a77a1f.png)

There is only one error in the log file and this does not look related:

SignalR exception thrown by Task: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
  at System.Net.Sockets.Socket.ThrowIfDisposedAndClosed () [0x00021] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) [0x00000] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x000b4] in <bd46d4d4f7964dfa9beea098499ab597>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x00107] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.ResponseStream.InternalWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00029] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.ResponseStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x000a1] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00006] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
  at System.Net.Sockets.Socket.ThrowIfDisposedAndClosed () [0x00021] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) [0x00000] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x000b4] in <bd46d4d4f7964dfa9beea098499ab597>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x00107] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.ResponseStream.InternalWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00029] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at System.Net.ResponseStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x000a1] in <bd46d4d4f7964dfa9beea098499ab597>:0 
  at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00006] in <208c8ef8a4ba4b878f0e4420d5960bea>:0 <---

**Comment by galli-leo** [comment] 2017-05-10 08:27
I have added a cache to the bulk import, so that could lead to increased memory usage, but certainly not that high. Was this screenshot taken immediately after bulk import?

**Comment by maran** [comment] 2017-09-27 17:48
I'm encountering this as well. I'm running in a multi-tenant environment and want to add Radarr as one of the supported apps. I do however need strict memory limitations. Most features work fine with 256MB ram. However importing movies, even with just 15 at a time spikes the memory above this limit easily passing even a 512MB limit. Is there anything that can be done to decrease the memory requirement for importing movies?

**Comment by galli-leo** [comment] 2018-02-06 22:54
Duplicate of #1580 

@maran Currently not, however using swap should work fine.

**Closed by galli-leo** 2018-02-06 22:54 UTC
