### ISSUE TITLE
Import bulk for movies multiple CDs

### ISSUE THREAD

**Issue by steve1977** [Radarr/Radarr#2328] opened 2017-12-09 04:55 UTC
I have a few movies that are comprised of multiple files (i.e., <moviename> CD1.ext, <moviename> CD2.ext). When I bulk-import these files, it renames one of the files removing the CD1.

**Comment by galli-leo** [comment] 2017-12-09 13:48
Duplicate of #145

**Closed by galli-leo** 2017-12-09 13:48 UTC
