### ISSUE TITLE
(RSS) Release rejected: Cannot parse release name.

### ISSUE THREAD

**Issue by Vaaaldez** [Radarr/Radarr#1185] opened 2017-03-15 16:23 UTC
**Description:** The movie _Resident Evil: The Final Chapter_ is found in the RSS feed, but it returns the error:
17-3-15 08:46:33.0|Debug|ParsingService|No matching movie Resident EvilThe Final Chapter
17-3-15 08:46:33.0|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown movie. Cannot parse release name.

I think it is the colon in the title that is not being parsed correctly, Also, in Radarr the movie is listed as 2016, but listed as 2017 in the rss feeds.

**Radarr Version:** 0.2.0.535

**Logs:**
17-3-15 08:46:32.9|Debug|Parser|Parsing string 'Resident Evil: The Final Chapter (2017) 720p WEB-DL 850MB - NBY'
17-3-15 08:46:32.9|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-3-15 08:46:32.9|Debug|Parser|Movie Parsed. Resident EvilThe Final Chapter - 2017 
17-3-15 08:46:32.9|Debug|Parser|Language parsed: English
17-3-15 08:46:32.9|Debug|QualityParser|Trying to parse quality for Resident Evil: The Final Chapter (2017) 720p WEB-DL 850MB - NBY
17-3-15 08:46:32.9|Debug|Parser|Quality parsed: WEBDL-720p v1
17-3-15 08:46:32.9|Debug|Parser|Release Group parsed: 
17-3-15 08:46:33.0|Debug|ParsingService|No matching movie Resident EvilThe Final Chapter
17-3-15 08:46:33.0|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown movie. Cannot parse release name.

17-3-15 08:46:40.0|Debug|Parser|Parsing string 'Resident Evil: The Final Chapter (2017) 720p HD-TC 750MB - NBY'
17-3-15 08:46:40.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-3-15 08:46:40.0|Debug|Parser|Movie Parsed. Resident EvilThe Final Chapter - 2017 
17-3-15 08:46:40.0|Debug|Parser|Language parsed: English
17-3-15 08:46:40.0|Debug|QualityParser|Trying to parse quality for Resident Evil: The Final Chapter (2017) 720p HD-TC 750MB - NBY
17-3-15 08:46:40.0|Debug|Parser|Quality parsed: TELECINE v1
17-3-15 08:46:40.0|Debug|Parser|Release Group parsed: TC
17-3-15 08:46:40.1|Debug|ParsingService|No matching movie Resident EvilThe Final Chapter
17-3-15 08:46:40.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown movie. Cannot parse release name.

17-3-15 08:46:42.1|Debug|Parser|Parsing string 'Resident Evil: The Final Chapter (2016) 1080p WEB-DL - 6CH - 2GB - ShAaNiG'
17-3-15 08:46:42.1|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-3-15 08:46:42.1|Debug|Parser|Movie Parsed. Resident EvilThe Final Chapter - 2016 
17-3-15 08:46:42.1|Debug|Parser|Language parsed: English
17-3-15 08:46:42.1|Debug|QualityParser|Trying to parse quality for Resident Evil: The Final Chapter (2016) 1080p WEB-DL - 6CH - 2GB - ShAaNiG
17-3-15 08:46:42.1|Debug|Parser|Quality parsed: WEBDL-1080p v1
17-3-15 08:46:42.1|Debug|Parser|Release Group parsed: 
17-3-15 08:46:42.2|Debug|ParsingService|No matching movie Resident EvilThe Final Chapter
17-3-15 08:46:42.2|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown movie. Cannot parse release name.

17-3-15 08:46:52.1|Debug|Parser|Parsing string 'Resident Evil: The Final Chapter (2016) 1080p WEB-DL AC3 6CH 2.1GB - MkvCage'
17-3-15 08:46:52.1|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-3-15 08:46:52.2|Debug|Parser|Movie Parsed. Resident EvilThe Final Chapter - 2016 
17-3-15 08:46:52.2|Debug|Parser|Language parsed: English
17-3-15 08:46:52.2|Debug|QualityParser|Trying to parse quality for Resident Evil: The Final Chapter (2016) 1080p WEB-DL AC3 6CH 2.1GB - MkvCage
17-3-15 08:46:52.2|Debug|Parser|Quality parsed: WEBDL-1080p v1
17-3-15 08:46:52.2|Debug|Parser|Release Group parsed: 
17-3-15 08:46:52.2|Debug|ParsingService|No matching movie Resident EvilThe Final Chapter
17-3-15 08:46:52.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown movie. Cannot parse release name.

Thanks.

**Comment by galli-leo** [comment] 2017-03-15 18:56
The problem is probably because the year is not correct. The movie was grabbed for me though, so no Idea why it's not working here.

**Comment by cryptoz** [comment] 2017-03-23 02:57
Im getting same error with 
Rogue One: A Star Wars Story 2016 1080p BluRay REMUX AVC DTS-HD MA 7.1-EPSiLON
and all releases... can it be semicolon?
not able to manually download either.

**Comment by mzaur** [comment] 2017-03-26 18:30
Having same issue with Radarr 0.2.0.535 on linux with Deadpool.2015.720p.BluRay.DD5.1.x264-IDE from PTP

**Comment by galli-leo** [comment] 2017-03-26 19:19
@mzaur Deadpool came out in 2016. The release contains the wrong year.

**Comment by mzaur** [comment] 2017-03-26 19:45
@galli-leo I see that, but this one works fine in CP

**Comment by galli-leo** [comment] 2017-03-26 20:54
@mzaur Yeah, but you want only movies grabbed where the year matches. e.g. Beauty and the Beast has a movie in 2014 and 2017. There you want only one of the two, but not the other. I am sure there are more than enough Deadpool releases with the correct year. I would also suggest to report that torrent with your indexer and tell the group to fix the year.

**Comment by cryptoz** [comment] 2017-03-26 22:08
@galli-leo would be nice if we could override with a manual download button.  no sense in wasting a good download due to a typo... maybe a paused warning instead of an error?  just some feedback.  thanks for radarr :)

**Comment by mzaur** [comment] 2017-03-26 22:11
@galli-leo I understand, FYI  this is on PTP, year old torrent, and it's the "golden" pick for 720p for Deadpool.

**Comment by Megagator** [comment] 2017-04-02 18:28
Once again chokes on a colon:
![screen shot 2017-04-02 at 14 26 40](https://cloud.githubusercontent.com/assets/6308213/24589889/7379d0fa-17b0-11e7-88a0-080a58973d60.png)

**Comment by ultimate255** [comment] 2017-04-10 22:39
![image](https://cloud.githubusercontent.com/assets/8908295/24885520/85a1e14a-1e14-11e7-92aa-13f001aa5d57.png)

Version
0.2.0.596
Mono Version
4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 16:18:35 UTC 2017)

The issue still persists, I have to manually download releases with Colon : in the title.

**Comment by mzaur** [comment] 2017-04-13 01:01
I am still having same issue. 

0.2.0.596 with mono 4.8.0

<img width="1390" alt="screenshot 2017-04-12 20 58 24" src="https://cloud.githubusercontent.com/assets/8196780/24985572/1cda4598-1fc3-11e7-8543-37497b05465f.png">

**Comment by galli-leo** [comment] 2017-04-13 07:53
@mzaur Your problem is that The Movie Database thinks the movie released in 2009, while your torrents say 2008. Only fix I can offer is to change the release date on themoviedb.org of that movie yourself.

**Closed** 2017-04-13 08:27 UTC
Labels: bug, Parser

**Comment by kalman79** [comment] 2017-07-27 16:29
Having this issue, little different the previous posts.  
Radarr is looking for 2016. 
Release is marked as 2017.
TRAKT and The Movie DB have as 2017.
IMDB has as 2016 but with USA Release as 2017.

Radarr
![image](https://user-images.githubusercontent.com/4164974/28680850-2f893a58-72bd-11e7-95ae-1ebae9ca6387.png)

TRAKT
![image](https://user-images.githubusercontent.com/4164974/28680892-522f75c2-72bd-11e7-8bb8-611461776283.png)

The Movie DB
![image](https://user-images.githubusercontent.com/4164974/28680931-671fc176-72bd-11e7-8f19-dfa3691f5eba.png)

IMDB
![image](https://user-images.githubusercontent.com/4164974/28680977-8244bd8a-72bd-11e7-88f5-928807feed3d.png)


Relative lines from log:
17-7-26 10:03:52.2|Info|MovieService|Adding Movie [tt1718924][A Family Man (2016)] Path: [A Family Man - 2016]
17-7-26 10:03:57.6|Info|MediaCoverService|Downloading Poster for [tt1718924][A Family Man (2016)] http://image.tmdb.org/t/p/original/612avgKpukTYLmrXLZmip2Hjwmv.jpg
17-7-26 10:03:57.6|Info|MediaCoverService|Downloading Poster for [tt1718924][A Family Man (2016)] http://image.tmdb.org/t/p/original/612avgKpukTYLmrXLZmip2Hjwmv.jpg
17-7-26 10:04:01.9|Info|MediaCoverService|Downloading Banner for [tt1718924][A Family Man (2016)] http://image.tmdb.org/t/p/original/mvU74vnYTkPrgwGnlpLryVP0S4A.jpg
17-7-26 10:04:09.3|Info|RefreshMovieService|Updating Info for A Family Man
17-7-26 10:04:09.5|Info|DiskScanService|Scanning disk for A Family Man
17-7-26 10:04:09.6|Info|MovieScannedHandler|[A Family Man] was recently added, performing post-add actions
17-7-26 10:05:59.2|Info|NzbSearchService|Searching 2 indexers for [A Family Man]
17-7-26 10:06:00.2|Info|DownloadDecisionMaker|No results found
17-7-26 10:06:00.2|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-7-26 11:31:36.2|Info|RefreshMovieService|Skipping refresh of movie: A Family Man
17-7-26 11:31:36.2|Info|DiskScanService|Scanning disk for A Family Man
17-7-26 11:31:36.4|Info|RenameMovieFileService|Renaming movie folder for A Family Man
17-7-27 09:14:34.7|Info|DiskScanService|Scanning disk for A Family Man
17-7-27 10:25:53.5|Info|RefreshMovieService|Updating Info for A Family Man
17-7-27 10:30:29.1|Info|RefreshMovieService|Updating Info for A Family Man
17-7-27 11:06:34.4|Info|NzbSearchService|Searching 2 indexers for [A Family Man]
17-7-27 11:06:44.5|Info|DownloadDecisionMaker|Processing 4 releases
17-7-27 11:07:00.9|Info|PreDBService|Starting PreDB Sync

**Comment by galli-leo** [comment] 2017-07-27 18:04
@kalman79 Nothing I can do. Scene rules dictate that we use the imdb year (which is 2016 here). Though I am working on a feature that will allow you to dl the release anyway

**Comment by kalman79** [comment] 2017-07-28 21:02
Thanks, that is what i assumed, thought I would bring it up just in case.  Good to know manual download override coming.
