### ISSUE TITLE
When movies are sorted, the 'next' button does not react to it

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#5989] opened 2021-03-05 18:12 UTC
**Is your feature request related to a problem? Please describe.**
When I go to movies, and sort ie on size, I choose the movie with the biggest size (or lowest rating, or whatever). When I click on te arrow to the right it goes to the next movie when it was sorted on alphabet, but I sorted on size so I expected to go to the second biggest moviE.

**Describe the solution you'd like**
Use the sort on the Movies-screen when clicking to a movie and clicking on next/previous-arrows.

Btw: I am using Radarr 3.0.2.4552

**Comment by bakerboy448** [comment] 2021-03-05 18:13
Duplicate of https://github.com/Radarr/Radarr/issues/4977

**Closed by bakerboy448** 2021-03-05 18:13 UTC
Labels: feature request
