### ISSUE TITLE
Radarr still removing extra files

### ISSUE THREAD

**Issue by joncy92** [Radarr/Radarr#7815] opened 2022-12-01 01:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

There are currently closed issues due to inactivity on this issue which was first reported a couple of years ago
Radarr is deleting additional files such as NFOs and images when upgrading a movie. When can we expect this issue to be resolved?

### Expected Behavior

Radarr doesn't delete additional files 

### Steps To Reproduce

1. Use radarr to download a different release of an existing movie 

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 4.2.4.6635
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.36
```

### What branch are you running?

Master

### Trace Logs?

None

[AB#4246](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4246)

**Comment by bakerboy448** [comment] 2022-12-01 01:30
Duplicate of several issues including existing open ones.

**Closed by bakerboy448** 2022-12-01 01:30 UTC
Labels: Type: Bug, Status: Needs Triage
