### ISSUE TITLE
Error occurred while executing task ManualImport

### ISSUE THREAD

**Issue by blackwhattack** [Radarr/Radarr#2032] opened 2017-09-01 21:22 UTC
**Here's the logs:**
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w NzbDrone.Core.Qualities.QualityModelComparer.Compare(QualityModel left, QualityModel right) w C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:wiersz 29
   w System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   w System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   w System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   w System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   w System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) w C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:wiersz 52
   w NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute(ManualImportCommand message) w C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:wiersz 310
   w NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) w C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:wiersz 91
   w CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   w System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   w CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   w NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() w C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:wiersz 41

> Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu 

translates to: 
Object reference not set to an instance of an object.

[Here's the exact movies](https://i.imgur.com/KfN7vRi.png)

**Radarr Version:**
0.2.0.846

**Comment by galli-leo** [comment] 2017-09-06 17:00
Whats the filename of the movie you are trying to import?

**Comment by blackwhattack** [comment] 2017-09-06 17:28
They're in the link at the end of the post: https://i.imgur.com/KfN7vRi.png.

Should've just copied, but now the logs are gonna be buried; as it was almost a week ago.

**Comment by galli-leo** [comment] 2017-09-10 10:43
Hmm. The ones there seem to have imported fine according to the log. Do you remember which filename you tried a manual import on?

**Comment by blackwhattack** [comment] 2017-09-11 15:47
I can't, unfortunately. But if the error occurred while/after importing these files, there's no other way than it being these fault, right?

**Comment by galli-leo** [comment] 2018-02-02 13:48
Duplicate of #2227

**Closed by galli-leo** 2018-02-02 13:48 UTC
