### ISSUE TITLE
Custom Filter options - Wanted/Missing excluding queued/unreleased

### ISSUE THREAD

**Issue by IzaacJ** [Radarr/Radarr#8075] opened 2023-02-07 20:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Only seeing missing movies, ie movies that I still don't have, in any quality, and that hasn't been queued yet, preferably also filtering out unreleased movies as well.
And only seeing wanted movies, ie only movies where cutoff isn't met, and that doesn't have a queued movie meeting cutoff, filtering out missing and unreleased movies.

### Describe the solution you'd like

More options in custom filters.

Example/Suggestions on new filters:
* Queued [is|is not] [true|false]
* Cut-off met [is|is not] [true|false]
* Exists on disk [is|is not] [true|false]  (Size on disk seems to do nothing, so could this maybe be a better option?)

### Describe alternatives you've considered

.

### Anything else?

.

[AB#4874](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4874)

**Comment by bakerboy448** [comment] 2023-02-07 20:27
Duplicate of https://github.com/Radarr/Radarr/issues/5004

**Closed by bakerboy448** 2023-02-07 20:27 UTC
Labels: Type: Feature Request, Type: Duplicate
