### ISSUE TITLE
Radarr doesn't properly communicate with Deluge

### ISSUE THREAD

**Issue by AdamPan** [Radarr/Radarr#761] opened 2017-02-16 04:31 UTC
**Description:**

Deluge seems to work with Radarr in the settings (testing returns success) but when Radarr grabs a torrent, it is successfullly added to Deluge but Radarr doesn't seem to be able to detect it. Checking logs returns the following error every time something is added to Deluge:

```
[Warn] ProcessDownloadDecisions: Couldn't add report to download queue. [redacted] \ufffd\ufffd\ufffd 

[v0.2.0.288] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x41a3c500 + 0x00193> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () <0x41a3b000 + 0x0005a> in <filename unknown>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) <0x41a1bd00 + 0x00468> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult] (NzbDrone.Common.Http.JsonRpcRequestBuilder requestBuilder, System.String method, System.Object[] arguments) <0x41a50ab0 + 0x0027f> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult] (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings, System.String method, System.Object[] arguments) <0x419f9da0 + 0x0005b> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.SetLabel (System.String hash, System.String label, NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings) <0x41ca1cc0 + 0x00093> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.AddFromTorrentFile (NzbDrone.Core.Parser.Model.RemoteMovie remoteEpisode, System.String hash, System.String filename, System.Byte[] fileContent) <0x41ca1660 + 0x00187> in <filename unknown>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteEpisode, System.String torrentUrl) <0x41c98060 + 0x00697> in <filename unknown>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) <0x41c979e0 + 0x0059b> in <filename unknown>:0 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) <0x41c970b0 + 0x0026b> in <filename unknown>:0 
  at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions (System.Collections.Generic.List`1 decisions) <0x41c93470 + 0x009d4> in <filename unknown>:0 

[Info] RssSyncService: RSS Sync Completed. Reports found: 1194, Reports grabbed: 0 
[Warn] DownloadMonitoringService: Unable to retrieve queue and history items from BYSH - Deluge 

[v0.2.0.288] System.OverflowException: TimeSpan overflowed because the duration is too long.
  at System.TimeSpan.Interval (Double value, Int32 scale) <0x7f6c7acb80a0 + 0x000f1> in <filename unknown>:0 
  at System.TimeSpan.FromSeconds (Double value) <0x7f6c7acb8320 + 0x00019> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems () <0x419f6b10 + 0x0064b> in <filename unknown>:0 
  at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads (IDownloadClient downloadClient) <0x41ba34e0 + 0x00141> in <filename unknown>:0 

[Warn] DownloadMonitoringService: Unable to retrieve queue and history items from BYSH - Deluge 

[v0.2.0.288] System.OverflowException: TimeSpan overflowed because the duration is too long.
  at System.TimeSpan.Interval (Double value, Int32 scale) <0x7f6c7acb80a0 + 0x000f1> in <filename unknown>:0 
  at System.TimeSpan.FromSeconds (Double value) <0x7f6c7acb8320 + 0x00019> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems () <0x419f6b10 + 0x0064b> in <filename unknown>:0 
  at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads (IDownloadClient downloadClient) <0x41ba34e0 + 0x00141> in <filename unknown>:0
``` 

**Radarr Version:**
Version
0.2.0.288
Mono Version
4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

**Comment by onedr0p** [comment] 2017-02-24 14:14
Are you trying to add thru magnet link or a torrent file? Do you have the same problem using the same indexer on Sonarr?

**Comment by AdamPan** [comment] 2017-02-24 15:19
I'm using the PtP indexer (which I believe adds torrent files). Radarr adds the torrent to Deluge, which downloads the file. However it seems like Radarr doesn't realize that it has added the file, and thinks the download failed. 

I'm using exactly the same settings for Sonarr on the same machine. Sonarr is working fine

**Comment by onedr0p** [comment] 2017-02-24 16:20
I use deluge on my local machine to test with PTP and it works for me... 

Do you have the label plug-in installed and enabled? 

Also it seems like it can't connect to Deluge for some reason.. `NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The request timed out`

Double check your settings, and also update Deluge if it's not on the latest version. You can also try restarting Deluge and Radarr.. I cannot reproduce this. Sorry, the error appears to be on your end.

**Comment by AdamPan** [comment] 2017-02-24 16:51
That's the weird part. The test button works, Deluge is clearly getting the torrent files, bur Radarr isn't seeing it. I'll look into updating Deluge

**Comment by onedr0p** [comment] 2017-03-08 01:00
Do you still have this error?

**Comment by AdamPan** [comment] 2017-03-08 03:17
Unfortunately I never solved this. I had to switch back to Couchpotato

**Comment by onedr0p** [comment] 2017-03-08 03:26
Have you tried the lastest release?

**Comment by AdamPan** [comment] 2017-03-08 03:43
I will try it and report back

**Comment by rbroh** [comment] 2017-03-11 22:44
I'm having this issue also, but only seems to happen with PTP torrents (as with the linked issue).

```
NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 208
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 234
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 180
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.SetLabel(String hash, String label, DelugeSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 158
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 54
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteEpisode, String torrentUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 269
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 125
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
   at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 73
   at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 47
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
Close
```

**Comment by tymanthius** [comment] 2017-03-13 13:33
I posted #1109 and it's much the same as @rbroh mentioned.  Although manually searching NEVER seems to work.  I did have some automatic stuff that ended up in deluge, but I didn't notice it for a long while b/c it wasn't marked as 'radarr'.

**Comment by shauder** [comment] 2017-04-13 02:11
I am having this issue also.

https://www.reddit.com/r/radarr/comments/650crl/radarr_and_deluge/

Basically from looking at the Deluge logs it appears it sends the torrent name with the checkmark and the golden torrent emoji things and Deluge barfs.

**Comment by shauder** [comment] 2017-04-13 05:25
1) Error : NzbDrone.Core.Test.HistoryTests.HistoryRepositoryFixture.should_get_download_history
NzbDrone.Core.Datastore.CorruptDatabaseException : Database file: C:\projects\radarr-usby1\_tests\_temp_636276566422535293\VirtualNzbDrone\nzbdrone.db is corrupt, restore from backup if available. See: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-am-getting-an-error-database-disk-image-is-malformed
  ----> System.Data.SQLite.SQLiteException : unable to open database file
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\DbFactory.cs:line 116
   at NzbDrone.Core.Test.Framework.DbTest.WithTestDb(MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core.Test\Framework\DbTest.cs:line 67
   at NzbDrone.Core.Test.Framework.DbTest.SetupDb() in C:\projects\radarr-usby1\src\NzbDrone.Core.Test\Framework\DbTest.cs:line 113
--SQLiteException
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.EnsureConnectionIsOpen() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\GenericProcessorBase.cs:line 53
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Exists(String template, Object[] args) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:line 78
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.TableExists(String schemaName, String tableName) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\Processors\SQLite\SQLiteProcessor.cs:line 47
   at FluentMigrator.Runner.VersionLoader.get_AlreadyCreatedVersionTable() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\VersionLoader.cs:line 124
   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo() in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\VersionLoader.cs:line 157
   at FluentMigrator.Runner.VersionLoader..ctor(IMigrationRunner runner, IAssemblyCollection assemblies, IMigrationConventions conventions) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\VersionLoader.cs:line 50
   at FluentMigrator.Runner.MigrationRunner..ctor(IAssemblyCollection assemblies, IRunnerContext runnerContext, IMigrationProcessor processor) in C:\Users\Mark\Source\Repos\fluentmigrator\src\FluentMigrator.Runner\MigrationRunner.cs:line 102
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 58
   at NzbDrone.Core.Datastore.DbFactory.Create(Migratio


What is this? Does it even matter? It is in test.

**Comment by rbroh** [comment] 2017-04-19 19:01
This looks to have resolved the problem for me - PTP downloads are passed to Deluge successfully now.  Thanks!

**Closed** 2017-04-20 15:01 UTC
Labels: bug

**Comment by onedr0p** [comment] 2017-04-20 15:02
@tymanthius do you want to see if it works now?

**Comment by tymanthius** [comment] 2017-04-20 15:30
I tested it yesterday. Works!  Love the flags column.  I just hadn't gotten around to posting here (stupid crazy at work) until you proded me.  :)

**Comment by tymanthius** [comment] 2017-04-22 02:20
Hey, I have a singular file that won't grab from PTP. I'm suspecting something malformed in the feed or some such rather than a true error w/ PTP.

Here's the log:

NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:61 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult] (NzbDrone.Common.Http.JsonRpcRequestBuilder requestBuilder, System.String method, System.Object[] arguments) [0x0006f] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:234 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult] (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings, System.String method, System.Object[] arguments) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:180 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.SetLabel (System.String hash, System.String label, NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:158 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.AddFromTorrentFile (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String hash, System.String filename, System.Byte[] fileContent) [0x00027] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:54 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteEpisode, System.String torrentUrl) [0x001aa] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:269 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x00148] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:125 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x000a3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:119 
  at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease (NzbDrone.Api.Indexers.ReleaseResource release) [0x00041] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:73 
  at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:47 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

**Comment by tymanthius** [comment] 2017-04-22 02:30
Oh, I think it might be that I already have this file in deluge.  So it may simply be that a bit of error checking needs to be done.

Didn't realize I'd already grabbed this.
