### ISSUE TITLE
[Feature Request] Make english releases avaiable for foreign quality profiles, but don't mark them as "finished"

### ISSUE THREAD

**Issue by shaddowlink** [Radarr/Radarr#2188] opened 2017-10-16 07:16 UTC
Heyho I am from Germany and finally got radarr (and sonarr) configured to work with German AND English releases. 

Now my problem is: Releases are out way earlier in english until they get localized into a foreign language, but I still don’t want to miss out on them. Is there a way to make radarr force like a "fake low quality" into English only releases and it will update them, once the German release is out? Like it’s possible with qualities. E.g. when there is a web-rip of something it is downloaded, but not marked as "finished" until the Blu-ray version is downloaded. Is it possible to do something similar to foreign releases ?

**I actually got a solution for my problem:**
My current solution is a second instance of radarr, just for English releases. Configured the renamer so it writes "-480p" at the end of the filename, no matter how good the quality really is. The first instance of radar (that only does German releases) picks that up once it scans the disk (since they share the same folder), but at a lower quality than it really is. The foreign version/first instance of radarr replaces this "low quality" version then with a proper German release once it’s out. But I feel that solution is so dirty.
Fixing errors and problems gets way more complicated etc... Also I have to add everything I want in both instances of radarr and can’t use external stuff (like ombi) really, because its only meant to speak with the API of one instance
My current solution works as I described above, but its a bitch to maintain. Takes alot away from the whole, awesome automation feeling.

**I think it could be a simple solution(not too hard to implement):**
Adding a check that the cutoff requirement is only met if release containes "German" AND is the wanted quality, instead of just the quality. That could be a tickbox, that’s visible once any other language than english is selected. Only if the movie is found and downloaded in the wanted language it's marked as finished, but it does not ignore english releases. 

**Other idea I got(think that would not be possible to implement without a lot of work):**
Qualities for foreign releases instead of only having the option in qualities for e.g. "Blueray-1080p" you could also add the quality "German.Blueray-1080p" and dragging it above the other quality. 

Also in both solutions the renamer could just add the word “-german” to the filenames, if you ever have to setup your programs another time, to not get confused. That would just be a nice extra thinking about long-term reliability. 

Thanks for your response already,
Stefan

**Comment by silentmiles** [comment] 2017-12-09 11:39
I'm posting this comment in a few different issues, since there seems to be a lot of overlap. Perhaps these should all be consolidated into a single issue about supporting multiple languages?

Anyway, the core problem here seems to be that the profiles are rigid in requiring the selection of just one language. A lot of people, I think, prefer to always get a movie in it's original language, and use subtitles, so in this case, ANY language is preferred. Others would like to be able to select multiple languages, and even set a priority among them. 

Of course, this logic only works if the movie is tagged with appropriate language tags, but in my experience this is not very common. Non-English movies often do not specify their language. It's been suggested that this is a tracker issue, and that it should be raised with the tracker -- yes, I guess that is right, but with the way trackers are constantly coming and going these days, this is really an impossible solution.

I know that there is a long-term solution being worked on, but couldn't we get an interim solution? I think just NOT requiring a specific language would be at least a partial solution for most people. Surely, just disabling the language matching logic (via a config toggle) would be easy to implement?

**Comment by galli-leo** [comment] 2018-02-07 13:41
Duplicate of #2433

**Closed by galli-leo** 2018-02-07 13:41 UTC
