### ISSUE TITLE
subtitles moving,proccess

### ISSUE THREAD

**Issue by valantislevas** [Radarr/Radarr#2043] opened 2017-09-06 10:58 UTC
**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:** latest dev

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

Hello is possible when movie proccecing to be copied to selected directory and also proccess the .srt files? like the last version sonarrs do?

**Comment by galli-leo** [comment] 2017-09-06 15:20
Duplicate of #121

**Closed by galli-leo** 2017-09-06 15:20 UTC
