### ISSUE TITLE
Sort by Downloaded (Quality) Shows All Movies Missing

### ISSUE THREAD

**Issue by ktrinkner** [Radarr/Radarr#2195] opened 2017-10-17 18:28 UTC
**Description:**
On the movies (main) tab, if I sort by the "Downloaded" column, all movies show as "missing." If I sort by any other column it works fine and if I re-sort after the "missing" error, all movies show up correctly again. This is happening on the table view in Chrome, Firefox, and IE.

![sort on downloaded](https://user-images.githubusercontent.com/20049617/31682158-85916588-b336-11e7-8a98-12493665b9a0.PNG)
![sort on title](https://user-images.githubusercontent.com/20049617/31682159-85a2a258-b336-11e7-80d5-19cd7021a097.PNG)

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.870

**Logs:**
[radarr.txt](https://github.com/Radarr/Radarr/files/1392132/radarr.txt)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by hotio** [comment] 2017-10-18 08:09
I can confirm this.

**Comment by ktrinkner** [comment] 2017-10-18 14:21
I'm trying to think of any reasons this would happen for me/us and not others. Do you have your movies store on the same box as Radarr? I currently have them imported from a local network share, not sure if that makes any difference.

**Comment by hotio** [comment] 2017-10-18 15:05
This happens only to us at the moment, because we are the only ones clicking it to sort and I only did because you filed a bug report.

**Comment by ktrinkner** [comment] 2017-10-18 15:16
:)

So you think this bug affects everyone, just no one else sorts by quality? How else would you go about looking for your SDTV movies to replace?

**Comment by aschnabl** [comment] 2017-10-19 08:38
I can confirm i have the same issue too. Was looking to see if there was already an issue before raising it

**Comment by DZMM** [comment] 2017-10-19 08:38
I have this problem (unraid docker user) - if I sort by downloaded, it shows just the records for the titles in my library but with the red 'missing' button.  I think I've had this problem for a while, it's just now I've bothered to investigate it.

The sub-menu buttons (all, monitored only etc) are still clickable but only released, announced and in cinemas should be really as the others don't make sense in this context.

Version
0.2.0.870
Mono Version
5.2.0.224 (tarball Tue Oct 3 19:49:47 UTC 2017)
AppData directory
/config
Startup directory
/opt/radarr

**Comment by deadlyknapsack** [comment] 2017-10-19 10:59
I can confirm I have the same issue. Latest version runnning on Synology.

**Comment by Popsikill** [comment] 2017-10-20 02:19
I can also confirm same issue, sorting by "Downloaded" produces the same result.
Synology/Mono/Radarr (0.2.0.870)

**Comment by KalChoedan** [comment] 2017-10-29 10:25
Confirmed.

**Comment by galli-leo** [comment] 2017-10-29 10:30
Not sure if this will get fixed in this version of the UI. I might just disable sorting by downloaded entirely since it's really nasty to do the sql query for.

**Comment by ktrinkner** [comment] 2017-10-29 15:00
That's fine if making the sort is not worth the effort. I was trying to use it as a way to see which movies I only had low quality versions of. Is there a different/better way I could do that?

**Comment by ktrinkner** [comment] 2017-11-14 22:09
There is similar behavior in the Wanted > Cutoff Unmet screen. When you attempt to sort by Downloaded, all of the qualities go blank. I believe, while the values are blank, that it does seem to be sorting by the alphabetical order of the download quality, eg: BluRay-720, DVD, WebDL-1080 (A-Z) when quality should sort DVD, BluRay-720, WebDL-1080 (low to high) or reverse.

**Comment by galli-leo** [comment] 2017-11-15 07:46
@ktrinker that unfortunately will not be possible in this version of the ui. Not sure if it ever will, because quality ordering is dependent on your profile.

**Comment by ktrinkner** [comment] 2017-11-15 14:30
Wow, I guess I showed my Radarr newb status there. I knew you could pick and choose from the qualities in your profiles, but I had no idea you could re-order them. That certainly makes sorting by quality essentially impossible, right? Couldn't you have multiple profiles with different orders all in one list that you would be attempting to apply one sort to?

**Comment by royduin** [comment] 2017-12-16 13:24
Same issue here

**Comment by galli-leo** [comment] 2017-12-16 15:10
@ktrinkner Yep so we probably will just disable sorting by quality until we make a new ui.

**Comment by CrMo4130** [comment] 2018-01-22 17:13
Same issue here.

**Comment by KBlixt** [comment] 2018-02-16 15:49
I have this issue as well, it also affect movies under wanted cut unmet.

**Comment by enchained** [comment] 2018-03-05 00:57
To everyone who needs to sort by downloaded quality - you can do that in the Movie Editor. Didn't see it being mentioned here, have been using this instead for a while.

**Closed** 2018-03-07 20:38 UTC
Labels: bug, priority:medium
