### ISSUE TITLE
Radarr pulling same torrents after being marked as failed. 

### ISSUE THREAD

**Issue by GregoryGHarding** [Radarr/Radarr#8311] opened 2023-04-10 19:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

torrents marked fail continue on to download the same torrent again

### Expected Behavior

torrents marked failed should search for a different torrent

### Steps To Reproduce

my radarr install is selective of which movies it searches the same torrent for, i cannot provide steps without admitting to a specific IP copyright,

### Environment

```markdown
- OS: UnRaid Docker
- Radarr: 4.3.2.6857
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome Up-To-Date
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

![torrent](https://user-images.githubusercontent.com/12652473/230985012-f92aa4ee-6c5e-437f-8ef6-22a681cbd56c.png)

**Comment by bakerboy448** [comment] 2023-04-10 19:51
Duplicate of #8086

**Closed** 2023-04-10 19:51 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by bakerboy448** [comment] 2023-04-29 18:26
https://github.com/Radarr/Radarr/commit/c6bb5024bc16c4983f5943f460ad36db958d49d4
