### ISSUE TITLE
Media Cover matching UI / Profile language 

### ISSUE THREAD

**Issue by OrpheeGT** [Radarr/Radarr#8914] opened 2023-08-01 16:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hello,

My radarr instance is all set in french :
![image](https://github.com/Radarr/Radarr/assets/8038551/a059a896-ff4e-478f-97a9-0b0f50556537)

Media naming is set to FR too :
![image](https://github.com/Radarr/Radarr/assets/8038551/061ca774-0615-49e4-9062-bc7cb5ce0f70)

but no matter what, Covers are retreived in english from TMDB. Even when a french cover is available.

An exemple with : 
https://www.themoviedb.org/movie/888082-les-chemins-de-pierre?language=en
https://www.themoviedb.org/movie/888082-les-chemins-de-pierre?language=fr

![image](https://github.com/Radarr/Radarr/assets/8038551/50a05a46-57ff-4b52-a808-aa0f5087bcee)

As you can see above, the Cover is in english... unlike the description wich is correctly set to french.

### Describe the solution you'd like

I would like the cover to be shown in the localized language, as long as it is available on TMDB. and only fallback to english when localized is not available.

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by bakerboy448** [comment] 2023-08-01 18:37
Duplicate of https://github.com/Radarr/Radarr/issues/5277

**Closed by bakerboy448** 2023-08-01 18:37 UTC
Labels: Type: Feature Request, Status: Needs Triage
