### ISSUE TITLE
option to either not move completed movies to a folder or ability to not put each movie into a separate folder in the final location

### ISSUE THREAD

**Issue by godofjesters** [Radarr/Radarr#5729] opened 2021-01-12 23:35 UTC
**Is your feature request related to a problem? Please describe.**
i'm frustrated that radarr always wants to put the movie as soon as it's done into the directory of where all my movies are, but it wants to put them into their own directory.

**Describe the solution you'd like**
i keep all my movie files in one base directory and don't want to move the files out of the folder that radarr creates and put them in the folder i need them to go to. if that can't be done then can i specify where the files will be moved to after they are done downloading. 

**Describe alternatives you've considered**
other alternatives i've considered is going back to couchpotato or use anything else, but nothing else is working with ombi currently.

**Comment by bakerboy448** [comment] 2021-01-12 23:37
Duplicate of #153  and likely others as well

But likely no plans to have all movies in a single folder even with custom folders.

Use couchpotato if that is a absolute requirement

**Closed by bakerboy448** 2021-01-12 23:37 UTC
Labels: feature request

**Comment by godofjesters** [comment] 2021-01-12 23:43
couchpotato is no longer working with ombi. radarr is the only torrent based software that does currently. if others are asking, wouldn't it be a good idea to at least consider it? or at least the ability to stop putting the movie into their own individual directory in the library/root folder?

**Comment by bakerboy448** [comment] 2021-01-13 00:34
for posterity:
https://wiki.servarr.com/Radarr_FAQ#Can_I_put_all_my_movies_in_my_library_into_one_folder

one could also turn off completed download handling and manually manage their library (or maybe via their download client) as well
