### ISSUE TITLE
Movie renamed by studio, causes 404 issues in radarr

### ISSUE THREAD

**Issue by Moulde** [Radarr/Radarr#2275] opened 2017-11-19 15:51 UTC
I added the movie Moana, and was confused because i kept getting 404 errors, when trying to see the details page of the movie, as I wanted to trigger a search of the movie.

It seems that the movie was renamed by disney, from "moana" to "vaiana" due to name clashing with an italian porn actress... :)

When I add the movie, its added, but it will not return any results when searching.
Searching for new movies, with both titles will return the movie, but it seems that it exists with both names. When i click the "already exists" button, for the Moana result. I get a 404.
But when I click the same button on the "vaiana" movie result, i can see the movie details page.

So it seems that the renaming of the movie is 
1. Causing 404 errors in radarr
2. Causes radarr to not pick up the torrents, maybe it searches for the new title, where it should be using the old name. (The movie is in my indexer, but with the old name "moana")

I hope you can use this information, I know this is kind of vague.
You should be able to reproduce the issue.

**Radarr Version:**
0.2.0.870

**Logs:**
I dont see any logs related to the 404.

**Comment by galli-leo** [comment] 2017-11-19 16:21
What language does your profile have?

**Comment by Moulde** [comment] 2017-11-19 16:39
I tried both English and Norwegian / Nordic, but I get no results from either, using automatic and manual search.

**Comment by hotio** [comment] 2017-11-19 17:51
Vaiana is just another translated alternative title for Moana...as far as I can tell the English official name is still Moana.

Your issue has probably nothing to do with this, try an incognito window to be sure.

**Comment by hotio** [comment] 2017-11-19 17:56
You are indeed partially correct, in Italy the movie is called Oceania, because of the porn star Moana Pozzi.

**Comment by dawtmaytrikx** [comment] 2017-12-09 08:38
I'm having the same issue with All Quiet on the Western Front (1930). Searched for the english title, added the movie in German. Radarr renamed the folder to Im Westen nichts neues (1930) - now no movies show up when I search for the English title. When I attempt to add the movie again (either by it's German or English name), it shows me the movie is already in my DB - but when I click the *Already Exists* button, it redirects me to server:port/movies/all-quiet-on-the-western-front-143 which 404s. Searching for the German title in my DB or server:port/movies/im-westen-nichts-neues-143 on the other hand works.

**Comment by galli-leo** [comment] 2017-12-09 11:37
I tried  reproducing with the original movie (Moana) and couldn't get it to 404. Can you verify what profile language you used as well as clearing cache?

**Comment by dawtmaytrikx** [comment] 2017-12-10 13:07
Profile language was set to German, clearing cache had no effect.

**Comment by Danguard** [comment] 2018-01-07 06:34
Can confirm the issue
Language Italian
Steps:
- New Movie
- Searched for "il capitale umano"
- I already have the movie, so radarr gave me "already exist" pointing to: "http://x.x.x.x:7878/movies/human-capital-244088", pressing the link gave the error 404
- The movie is present in radarr as "Il capitale umano" with correct link: "http://x.x.x.x:7878/movies/il-capitale-umano-244088" (the italian translation of the movie name)
This can be reproduced with all the movies with the title translated.
Nothing i did (clearing cache etc) helped solving the issue.

**Comment by gabo77** [comment] 2018-01-21 03:14
I can confirm this issue is easily reproducible when adding an English movie with a foreign language profile (in my case, with a French profile).

Radarr will often add it with it's foreign (translated) title, and will subsequently create a 404 when clicking the "Already exists" link.

**Comment by krin-san** [comment] 2018-02-10 09:25
Can confirm this isse as well. Have the [Jungle (2017)](https://www.themoviedb.org/movie/390062-jungle) in my DB for few months. Tried to open the details page (/movies/jungle-390062) from add movies page (/addmovies) and go HTTP 404.

Nothing interesting in Debug logs - HTTP 200 is everywhere.

Version: 0.2.0.933 (nightly)
<details>
<summary>Debug logs...</summary>

```log
18-2-10 12:18:37.1|Debug|Api|[PUT] /api/config/host: 202.Accepted (644 ms)
18-2-10 12:18:37.5|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-2-10 12:18:39.3|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-2-10 12:18:39.3|Debug|Api|[GET] /api/diskspace: 200.OK (7 ms)
18-2-10 12:18:39.3|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-2-10 12:18:39.3|Debug|Api|[GET] /api/diskspace: 200.OK (6 ms)
18-2-10 12:18:40.5|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn&filterType=equal: 200.OK (68 ms)
18-2-10 12:18:40.5|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Warn&filterType=equal: 200.OK (13 ms)
18-2-10 12:18:43.3|Debug|Api|[GET] /api/config/ui: 200.OK (1 ms)
18-2-10 12:18:43.4|Debug|Api|[GET] /api/system/status: 200.OK (6 ms)
18-2-10 12:18:43.5|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (7 ms)
18-2-10 12:18:43.5|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-2-10 12:18:43.5|Debug|Api|[GET] /api/profile: 200.OK (13 ms)
18-2-10 12:18:43.7|Debug|Api|[GET] /api/movie?page=1&pageSize=250&sortKey=inCinemas&sortDir=asc&filterKey=downloaded&filterValue=false: 200.OK (228 ms)
18-2-10 12:18:43.9|Debug|Api|[GET] /api/command: 200.OK (3 ms)
18-2-10 12:18:43.9|Debug|Api|[GET] /api/series: 200.OK (18 ms)
18-2-10 12:18:44.0|Debug|Api|[GET] /api/language: 200.OK (1 ms)
18-2-10 12:18:44.0|Debug|Api|[GET] /api/tag: 200.OK (6 ms)
18-2-10 12:18:44.1|Debug|Api|[GET] /api/health: 200.OK (2 ms)
18-2-10 12:18:44.1|Debug|Api|[GET] /api/movies/discover/lists: 200.OK (74 ms)
18-2-10 12:18:44.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (7 ms)
18-2-10 12:18:44.4|Debug|Api|[GET] /api/movie?page=1&pageSize=-1&sortKey=inCinemas&sortDir=desc&filterKey=filterKey&filterValue=filterValue&filterType=filterType: 200.OK (546 ms)
18-2-10 12:18:44.7|Debug|Api|[GET] /api/movie/titleslug/jungle-390062: 200.OK (602 ms)
18-2-10 12:18:46.4|Debug|Api|[GET] /api/log/file: 200.OK (2 ms)
18-2-10 12:18:46.5|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (2 ms)
18-2-10 12:18:49.0|Debug|Api|[GET] /api/config/ui: 200.OK (1 ms)
18-2-10 12:18:49.0|Debug|Api|[GET] /api/system/status: 200.OK (6 ms)
18-2-10 12:18:49.1|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-2-10 12:18:49.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (11 ms)
18-2-10 12:18:49.1|Debug|Api|[GET] /api/profile: 200.OK (16 ms)
18-2-10 12:18:49.3|Debug|Api|[GET] /api/movie?page=1&pageSize=250&sortKey=inCinemas&sortDir=asc&filterKey=downloaded&filterValue=false: 200.OK (202 ms)
18-2-10 12:18:49.5|Debug|Api|[GET] /api/command: 200.OK (2 ms)
18-2-10 12:18:49.9|Debug|Api|[GET] /api/series: 200.OK (447 ms)
18-2-10 12:18:50.0|Debug|Api|[GET] /api/language: 200.OK (1 ms)
18-2-10 12:18:50.0|Debug|Api|[GET] /api/tag: 200.OK (8 ms)
18-2-10 12:18:50.1|Debug|Api|[GET] /api/config/mediamanagement: 200.OK (4 ms)
18-2-10 12:18:50.2|Debug|Api|[GET] /api/config/naming: 200.OK (20 ms)
18-2-10 12:18:50.2|Debug|Api|[GET] /api/movies/discover/lists: 200.OK (64 ms)
18-2-10 12:18:50.2|Debug|Api|[GET] /api/config/indexer: 200.OK (2 ms)
18-2-10 12:18:50.2|Debug|Api|[GET] /api/config/downloadclient: 200.OK (2 ms)
18-2-10 12:18:50.2|Debug|Api|[GET] /api/notification: 200.OK (20 ms)
18-2-10 12:18:50.3|Debug|Api|[GET] /api/config/ui: 200.OK (1 ms)
18-2-10 12:18:50.3|Debug|Api|[GET] /api/config/host: 200.OK (20 ms)
18-2-10 12:18:50.3|Debug|Api|[GET] /api/config/netimport: 200.OK (2 ms)
18-2-10 12:18:50.3|Debug|Api|[GET] /api/health: 200.OK (1 ms)
18-2-10 12:18:50.3|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (6 ms)
18-2-10 12:18:50.4|Debug|Api|[GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+-+%7BQuality+Title%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (18 ms)
18-2-10 12:18:50.4|Debug|Api|[GET] /api/profile: 200.OK (27 ms)
18-2-10 12:18:50.4|Debug|Api|[GET] /api/delayprofile: 200.OK (24 ms)
18-2-10 12:18:50.4|Debug|Api|[GET] /api/qualitydefinition: 200.OK (1 ms)
18-2-10 12:18:50.5|Debug|Api|[GET] /api/movie?page=1&pageSize=-1&sortKey=inCinemas&sortDir=desc&filterKey=filterKey&filterValue=filterValue&filterType=filterType: 200.OK (959 ms)
18-2-10 12:18:50.5|Debug|Api|[GET] /api/Restriction: 200.OK (12 ms)
18-2-10 12:18:50.5|Debug|Api|[GET] /api/downloadclient: 200.OK (20 ms)
18-2-10 12:18:50.5|Debug|Api|[GET] /api/indexer: 200.OK (61 ms)
18-2-10 12:18:50.5|Debug|Api|[GET] /api/remotePathMapping: 200.OK (9 ms)
18-2-10 12:18:50.6|Debug|DiskProvider|Unable to get free space for '/media/movies/', unable to find suitable drive
18-2-10 12:18:50.6|Debug|RootFolderService|Generating list of unmapped folders
18-2-10 12:18:50.6|Debug|Api|[GET] /api/exclusions: 200.OK (9 ms)
18-2-10 12:18:50.6|Debug|Api|[GET] /api/netimport: 200.OK (61 ms)
18-2-10 12:18:50.7|Debug|Api|[GET] /api/metadata: 200.OK (49 ms)
18-2-10 12:18:51.1|Debug|RootFolderService|22 unmapped folders detected.
18-2-10 12:18:51.1|Debug|Api|[GET] /api/rootfolder: 200.OK (558 ms)
```
</details>

**Comment by krin-san** [comment] 2018-02-10 09:28
@Danguard, try removing this movie from the movies list _(website root)_ and add it again. Worked for me.
In case you had any files inside the old (before renaming) folder I assume you have to move them manually.

**Comment by Danguard** [comment] 2018-02-11 18:48
The issue is how the radarr search for the movie.
Let me explain:

When you search for a movie, it will search for it in english and then translate it in your language
Once you did it, you'll be able to find him in your language in radarr search as normal

BUT

When you try to find the movie in "add movie" again (for example, you don't remember the localized name), you'll get the "already exist" pointing to the english title.

Link on the "already exist" is: http://ip:port/movies/human-capital-244088
When you search for it in radarr, you'll find it in: http://ip:port/movies/il-capitale-umano-244088

That's the issue, radarr is able to tell the movie is already in your database but "forget" to give you the right position memorized in the database, pointing always to the english title and not to the name existing in the database for that movie.

**Comment by WoLpH** [comment] 2018-03-06 11:30
Would it be an option to search primarily (or as fallback) using the TmdbId?
A simple fallback here should do the trick: https://github.com/Radarr/Radarr/blob/61ee8edb5a623938f6a1a29fbfb084a086fac1af/src/NzbDrone.Api/Movies/MovieModule.cs#L153-L174

Although it seems that there is no FindByTmdbId method in the movies service right now, that should be as simple as:
```c#
public Movie FindByTmdbId(int tmdbId)
{
    return _movieRepository.FindByTmdbId(tmdbId);
}
```

**Comment by WoLpH** [comment] 2018-05-05 12:09
It's definitely still an issue so I hope we can make stalebot leave this issue alone ;)

**Comment by Danguard** [comment] 2018-05-05 18:53
Confirming the issue is still there.

**Comment by Qstick** [comment] 2020-02-09 00:23
Fixed in v3

**Closed by Qstick** 2020-02-09 00:23 UTC
Labels: bug, cannot reproduce, confirmed
