### ISSUE TITLE
Discover movie import crashes with unhandled exception when duplicate path failure

### ISSUE THREAD

**Issue by psylenced** [Radarr/Radarr#7433] opened 2022-07-22 12:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am attempting to import a list of movies from discover which were imported via lists.

If one of those movies is a duplicate of existing movie, the import crashes half way through.

### Expected Behavior

The import should skip and log the duplicate movie, and import the rest of the list without crashing.

### Environment

```markdown
- OS: Alpine Linux
- Radarr: v4.1.0.6175
- Docker Install: No
```

### What branch are you running?

Master

### Trace Logs?

```2022-07-22 22:08:33.1|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.2|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.3|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.4|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.5|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.6|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.7|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.7|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.8|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:33.9|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:34.0|Info|AddMovieService|Adding Movie [xxxxx] Path: []
2022-07-22 22:08:34.1|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.1.0.6175] FluentValidation.ValidationException: Validation failed: 
 -- Path: Path is already configured for an existing movie: /mnt/media-movies/Duplicate Movie Name (2020)
   at NzbDrone.Core.Movies.AddMovieService.SetPropertiesAndValidate(Movie newMovie) in D:\a\1\s\src\NzbDrone.Core\Movies\AddMovieService.cs:line 124
   at NzbDrone.Core.Movies.AddMovieService.AddMovies(List`1 newMovies, Boolean ignoreErrors) in D:\a\1\s\src\NzbDrone.Core\Movies\AddMovieService.cs:line 67
   at lambda_method371(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-07-22 22:08:34.1|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is already configured for an existing movie: /mnt/media-movies/Duplicate Movie Name (2020)
```

**Comment by bakerboy448** [comment] 2022-07-22 12:35
Duplicate of #7409

**Comment by psylenced** [comment] 2022-07-22 12:36
Possible fix:

https://github.com/Radarr/Radarr/blob/5fb6b449507af0b238afe6b699d8f55cc5deb790/src/Radarr.Api.V3/Movies/MovieImportController.cs#L30

Should pass a 2nd paramter of ```true``` to ignore errors.

Similar to here:

https://github.com/Radarr/Radarr/blob/16ed68d5de5add1ee017bc3181f08e7c835d4b9f/src/Radarr.Api.V3/ImportLists/ImportListMoviesController.cs#L104

**Comment by bakerboy448** [comment] 2022-07-22 12:36
Please search next time before opening an issue

also info logs are invalid for bug reports, trace logs are required

**Closed by bakerboy448** 2022-07-22 12:36 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by psylenced** [comment] 2022-07-22 12:37
I did search, however my terms did not match the linked but.

Info log not required as I posted fix in comments.
