### ISSUE TITLE
manual parse don't rename the file according the tag {Original Title}

### ISSUE THREAD

**Issue by revers59** [Radarr/Radarr#9360] opened 2023-11-01 11:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have Standard Movie Format set to `{Original Title} {imdb-{ImdbId}} {edition-{Edition Tags}}` 
Some files don't pass the automatic parse and we can find it in the download queue.
When I manualy parse the film radarr rename like that for example : {imdb-tt8129806}.mkv
No information about Original title.
Sorry no trace information in my trace log

for information all work nice in automatic parse.

### Expected Behavior

Like automatic parse radarr must take the {Original Title} in consideration

### Steps To Reproduce

Go to Activity -> queue
manual import one file that don't pass the automatic parse
Set Release Group
Set Quality
Set language
Click import
go to the film
Click on the file section
See the filename. 

### Environment

```markdown
- OS: Debian 12
- Radarr: Radarr: 5.1.2.8207
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: 
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

I don't see any information in my trace log about this rename action

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2023-11-01 11:53
Duplicate of several existing issues

https://github.com/Radarr/Radarr/issues/6547

**Closed by bakerboy448** 2023-11-01 11:53 UTC
Labels: Type: Bug, Status: Needs Triage
