### ISSUE TITLE
Remote Login Prompt on Local Install

### ISSUE THREAD

**Issue by gregryman** [Radarr/Radarr#2479] opened 2018-02-04 18:48 UTC
I've had this install running for some time. My current uptime is 34 days with no changes. Today when using the application I started to get prompted for a login. I do not use authentication for Radarr. Looking at the login, it's asking me to login to radarr.video:80, which is the main Radarr website. When I browse to that site, I get the same login prompt. Has something changed that's causing an API or other issue?

Radarr Ver. 0.2.0.910
develop

18-2-4 10:39:39.5|Info|Bootstrap|Starting Radarr - /opt/Radarr/Radarr.exe - Version 0.2.0.910
18-2-4 10:39:42.5|Info|Router|Application mode: Interactive
18-2-4 10:39:42.7|Info|MigrationLogger|*** Migrating data source=/root/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-2-4 10:39:42.9|Info|MigrationLogger|*** Migrating data source=/root/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-2-4 10:39:42.9|Info|OwinHostController|Listening on the following URLs:
18-2-4 10:39:42.9|Info|OwinHostController|  http://*:7878/
18-2-4 10:39:43.0|Info|NancyBootstrapper|Starting NzbDrone API

This image is what I see when using my local install.

<img width="447" alt="screen shot 2018-02-04 at 10 23 03 am" src="https://user-images.githubusercontent.com/9287462/35781002-dff255ec-0998-11e8-8891-65b41b6535a7.png">

**Comment by Nightbr** [comment] 2018-02-04 19:05
Same here... Weird bug

**Comment by SlothCroissant** [comment] 2018-02-04 19:53
+1. Looks like it's trying to load some js: https://imgur.com/DYW89pK

**Comment by kohnman** [comment] 2018-02-04 20:23
+1 i'm having the same problem.

**Comment by escservices** [comment] 2018-02-04 20:36
+1 same issue, looks like the radarr.video website is requiring a browser login and part of the local radarr install pulls from https://radarr.video

**Comment by Madseason41** [comment] 2018-02-05 00:09
+1

**Comment by ParFlesh** [comment] 2018-02-05 01:21
Looks like this is caused by Analytics being enabled.

Settings->General
Disable Analytics

Then restart

**Comment by gregryman** [comment] 2018-02-05 01:26
Can confirm, disabling Analytics fixes the issue.

**Comment by SlothCroissant** [comment] 2018-02-05 01:43
Confirmed as well. Annoyed that Radarr's site throwing a 401 caused weird issues with the client, but happy to just turn it off and move on.

**Comment by kianrafiee** [comment] 2018-02-05 06:25
Yep, same problem here.

**Comment by cvandend** [comment] 2018-02-05 10:47
Issue is indeed fixed with that workaround. But it doesn't explain why the website of the project suddenly requires a password. Did they get a take down notice from the MPAA?

**Comment by kohnman** [comment] 2018-02-05 10:58
yes fix worked for me. THX

**Comment by Nightbr** [comment] 2018-02-05 11:03
the website seems to be on maintenance https://radarr.video/
 Disabling Analytics is a good workaround the time they redeploy the piwik for analytics.

**Comment by galli-leo** [comment] 2018-02-05 11:31
Sorry about this my webhos erroneously thought the Radarr site was causing heavy server load and shut it down. You should be able to just cancel the prompt. They should have activated the site again not sure why there’s still a login prompt. Will talk to them.

**Comment by galli-leo** [comment] 2018-02-05 12:30
Fixed now

**Closed by galli-leo** 2018-02-05 12:30 UTC

**Comment by SlothCroissant** [comment] 2018-03-06 00:11
This is happening again as of 3/5/2018.

**Comment by TheMonDon** [comment] 2018-03-06 01:00
Can also confirm this is happening again.

**Comment by galli-leo** [comment] 2018-03-06 07:36
Yeah for the same reason as outlined above

**Comment by hirezl** [comment] 2018-03-06 14:36
Also confirmed.

**Comment by Starseed6** [comment] 2018-03-06 20:10
Same is happening for me.  I'm also seeing that my Lists are not working, which may be related to the web site refusing access.  Anyone else having problems with their IMDB lists?  (Yes I am using the Radarr lists, not the RSS feeds)

**Comment by galli-leo** [comment] 2018-03-06 20:11
Yes they are also not working due to the server being down.

**Comment by clarkd** [comment] 2018-03-06 21:54
Happening again here.

**Comment by hirezl** [comment] 2018-03-06 22:16
I'm getting no recommendations at all.

Thank you,
Lt Cmdr Rezty Felty
Chief Engineer
Warp Core Research
USS Dark Phoenix NCC 74920
816-559-1196
Rezty@KC-Felty.Net

**Comment by galli-leo** [comment] 2018-03-06 22:22
Yes, it's being worked on, the server should be back up in a few hours.

**Comment by escservices** [comment] 2018-03-07 02:23
Disabling analytics seems to resolve the issue like before.  Make sure you restart Radarr after disabling it.
