### ISSUE TITLE
Automate UFC/Wrestling PPV downloading by not requiring "(yyyy)" tag

### ISSUE THREAD

**Issue by Firestorm2359** [Radarr/Radarr#9215] opened 2023-09-26 05:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

- Sports PPVs are in fact classified as movies in TMDB and can theoretically be seamlessly integrated into Radarr as well.
- The catch? The filenames of PPV torrent releases lack "(yyyy)" tags, making them invisible to Radarr.
- But fear not, in the advanced settings of each indexer, there's a game changing option: "remove year from search string." Click that, and voila! Radarr can now spot those elusive PPVs. But wait, there's a twist!
- There's a pesky error that crops up, claiming it's "unable to parse." This hurdle still prevents smooth imports as per below.

![image](https://github.com/Radarr/Radarr/assets/140573813/3d500697-e042-42e3-b625-3b2593531afe)

### Describe the solution you'd like

Enable Radarr to parse and accept torrent releases without the "(yyyy)" tag. This would open up a world of possibilities for the community. This enhancement is not just for one, but for the many users out there who crave seamless automation of PPV events.

### Describe alternatives you've considered

The current process is a painstaking ordeal. I find myself adding each PPV to Radarr as a movie. Then I manually fetch the release in my download client and again manually match it to the corresponding Radarr entry just to make it import correctly.

### Anything else?

Here are some examples of people wanting the same functionality I'm asking for:

https://www.reddit.com/r/radarr/comments/k6bsix/radarr_cant_find_ufc_fights_despite_them_being/

https://www.reddit.com/r/radarr/comments/xvg509/trouble_finding_ufc_fights/

https://www.reddit.com/r/radarr/comments/bzjasw/ufc_indexer_search_results/

https://www.reddit.com/r/radarr/comments/my1xxy/automated_ufc_downloading/

**Comment by thorrrr** [comment] 2023-09-26 10:15
Totally agree would be great option not sure if its a Radarr or a Sonarr but would be a great option to solve

**Comment by bakerboy448** [comment] 2023-09-26 13:48
Duplicate of https://github.com/Radarr/Radarr/issues/2877

**Closed by bakerboy448** 2023-09-26 13:48 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by Firestorm2359** [comment] 2023-09-26 22:22
> Duplicate of #2877
> 
> no pans for UFC/Sports support

I appreciate your perspective, and I understand that this topic has been discussed previously.

Could we revisit the idea of adding this feature though? It could have a significant positive impact, not only for sports releases but also for movies that lack the "(yyyy)" tag.

I vaguely remember there might be an indexer setting related to "parsing leniency"; can you kindly guide me to it? Your input would be much appreciated!

**Comment by bakerboy448** [comment] 2023-09-26 22:23
That setting was in v0.2 and was removed with v3; it's not coming back

sports will always not support automation

**Comment by Firestorm2359** [comment] 2023-09-26 23:42
> That setting was in v0.2 and was removed with v3; it's not coming back
> 
> sports will always not support automation

It seems like we might have different views on "sports." I agree with your point that automating sports with frequent games like NBA or MLB is not possible.

However, I respectfully believe that automation can work for less frequent events like MMA and wrestling. These events are listed in TMDB and can be added to Radarr, as shown in my screenshot. They are treated as one-off events, similar to movies, making them suitable for Radarr imports. Personally, I've been using RSS feeds to download them in my client and then manually matching them to the TMDB entry in Radarr, that's how I know it's feasible. Just sharing my experience! 😄
