### ISSUE TITLE
[BUG?] sorting wanted cut off by quality removes the quality listings.

### ISSUE THREAD

**Issue by KBlixt** [Radarr/Radarr#2194] opened 2017-10-17 15:28 UTC
**Description:**
When sorting cut off unmet wanted movies by quality, the text indicating what quality the movie is downloaded in disappears.
 
**Radarr Version:**

Version
linux 16.04

radarr
0.2.0.870

Mono Version
5.2.0.224 (tarball Tue Oct 3 19:51:58 UTC 2017)

browser:
linux firefox and windows chrome.

**Logs:**
nothing in the logs regarding this issue.

**Comment by hotio** [comment] 2017-10-18 08:15
I can confirm this.

**Comment by erreib** [comment] 2018-01-09 17:57
I am currently experiencing this issue when sorting by Downloaded/Not Downloaded.

**Comment by galli-leo** [comment] 2018-02-07 13:42
Duplicate of #2195

**Closed by galli-leo** 2018-02-07 13:42 UTC
