### ISSUE TITLE
Older Priority is copying Recent Priority settings for NZBGet download client

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1949] opened 2017-08-17 05:54 UTC
**Description:**

Older Priority Set to Normal, While Recent Priority set to High, results in the Older stuff also being download with high priority in NZB Get. 

**Screens:**

![image](https://user-images.githubusercontent.com/5501908/29397729-f291a0d4-82e5-11e7-8660-d76e8025ec59.png)

![image](https://user-images.githubusercontent.com/5501908/29397748-04d663b0-82e6-11e7-93f1-bf5d773230b8.png)

**Radarr Version:**
Radarr Ver. 0.2.0.831
nightly

**Logs:**
Cant find anything in the log that mentions NZBget priority.

**Comment by galli-leo** [comment] 2017-08-17 17:30
Actually that setting isn't implemented yet ( Duplicate of #229 )

**Closed by galli-leo** 2017-08-17 17:30 UTC

**Comment by desimaniac** [comment] 2017-08-17 18:17
Thanks.
