### ISSUE TITLE
Can't set "Minimum Seeders"

### ISSUE THREAD

**Issue by wgstarks** [Radarr/Radarr#1906] opened 2017-08-10 19:20 UTC
When I enter a value for minimum seeders in my indexer configuration the value is lost when selecting "Save". Checking the db file shows that the value was not saved and the field is empty if I reopen it in the UI. Doesn't seem to matter if creating a new indexer or editing existing. Tried this with Safari and Chrome. No difference.

**Comment by jamesmacwhite** [comment] 2017-08-10 20:13
https://github.com/Radarr/Radarr/issues/1736

Will be fixed in the next release.

**Comment by wgstarks** [comment] 2017-08-10 20:24
Thanks. Is there any way to manually edit the nzbdrone.db file to enter the desired value? I tried with a text editor but couldn't save the changes.

**Comment by jamesmacwhite** [comment] 2017-08-10 20:26
You'd need to edit the DB via an application that can read the sqlite database.

Example: http://sqlitebrowser.org/

**Comment by galli-leo** [comment] 2017-08-10 21:45
Duplicate of #1736

**Closed by galli-leo** 2017-08-10 21:45 UTC

**Comment by wgstarks** [comment] 2017-08-11 02:13
sqlitebrowser worked great thanks
