### ISSUE TITLE
Preferred Tags for each qualities

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#1798] opened 2017-07-15 04:00 UTC
Hi,

I like the global preferred tags but I will like to have a preferred tags too for each qualities.

![image](https://user-images.githubusercontent.com/24792889/28236286-52f44004-68f0-11e7-85f5-a1752ad77b0a.png)

I want to add HDR tags only for the 2160p for example and maybe for dvd quality I want a special codec etc.

The global one should have a less priority vs the specific one because Atmos doesn't exist at the dvd level for example.

I don't know if I explained it well ;)

**Comment by hotio** [comment] 2017-07-18 20:06
I think this might become available in the future with this project https://github.com/Radarr/Radarr/projects/1

**Comment by galli-leo** [comment] 2017-07-20 10:24
Nah I don't think I will add tags for each quality. It's something separate.

**Comment by joydashy** [comment] 2017-11-20 13:33
I think this would be an amazing addition to Radarr. I for one really would like more control like this.

**Comment by galli-leo** [comment] 2018-02-07 10:19
Duplicate of #2433

**Closed by galli-leo** 2018-02-07 10:19 UTC
