### ISSUE TITLE
Error occurred while executing task ApplicationUpdate: Error: SecureChannelFailure (The authentication or decryption has failed.)

### ISSUE THREAD

**Issue by djoole** [Radarr/Radarr#2576] opened 2018-02-25 15:56 UTC
**Description:**

When I want to update to latest version i get this error in the logs : 
_Error occurred while executing task ApplicationUpdate: Error: SecureChannelFailure (The authentication or decryption has failed.)_

I've tried adding the env variable MONO_TLS_PROVIDER=legacy, but it doesn't solve it.
I've checked that libcurl is installed, it is.

**Radarr Version:**
0.2.0.935

**Mono Version:**
5.2.0.215

**Debug Logs:**
on demand.

**Comment by galli-leo** [comment] 2018-02-25 16:42
Duplicate of #2573

**Closed by galli-leo** 2018-02-25 16:42 UTC
