### ISSUE TITLE
[Feature Request] abort download if it doesn't contain a file that would be imported

### ISSUE THREAD

**Issue by fovert** [Radarr/Radarr#2973] opened 2018-08-21 01:57 UTC
**Is your feature request related to a problem? Please describe.**
I've started to see a common error where the indexer has an NZB linked to the wrong movie. Granted, this is ultimately a problem with the indexer, but Radarr could handle this as well.

**Describe the solution you'd like**
Radarr already declines to import the result of a download if the files don't match.
Either by examining the NZB before adding it and/or examining the files that are being downloaded (including looking inside RAR files), Radarr could perform this match before the download is complete. This would save download resources and time. It may be necessary to provide a support script to handle this check at the downloader.

**Describe alternatives you've considered**
It'd be better to resolve the issue with the indexer(s), but handling this in Radarr would be more robust.

**Comment by fryfrog** [comment] 2018-08-21 02:46
I think the problem is that it doesn't track downloads in a way that this would be easy. It sends the nzb / torrent to the downloader. Then it asks the downloader for all the downloads that match the path/category/label you gave it. It parses them for things it recognizes. If it doesn't recognize it, there isn't a reasonable way for it to know why. Did you add it manually and you just haven't added the movie to Radarr? Did the download end up being totally wrong? Who knows. I think for this to work, the submission of the download would have to return a unique id. Then Radarr could see that the unique id for the movie it thought should be A but is really B. But no downloaders do anything like that.

I think this request is harder than you think and unlikely to be implemented.

You *can* do some work in the downloader to prevent very wrong downloads like `.exe` and such, but that doesn't cover your exact case and isn't quite as useful.

**Comment by c0rnflake** [comment] 2018-08-21 21:06
There are scripts/plugins available for some downloaders, nzbget etc, which can delete nzbs that contain files that ain't required.  I personally use FakeDetector, PasswordDetector and Flatten with nzbget.

**Comment by fryfrog** [comment] 2018-08-21 21:13
^ Exactly.

But this *specific* feature request is more like `Movie 123` is wanted, a download that *should* be `Movie 123` is sent, but ends up being `Movie 321` for some reason. Wrongly identified by indexer, malicious upload, whatever. Pretty hard to detect unless you're strictly enforcing queues.

**Comment by galli-leo** [comment] 2018-08-25 22:01
Won't be implemented as is explained already on a few closed issues.

**Closed by galli-leo** 2018-08-25 22:01 UTC
