### ISSUE TITLE
Movies with two parts are not imported correctly

### ISSUE THREAD

**Issue by shocker2** [Radarr/Radarr#302] opened 2017-01-17 12:49 UTC
Hello,
For example if you have the movie:
Movie.Name.Year.DVDRip.XviD-RLS - pt1.avi
Movie.Name.Year.DVDRip.XviD-RLS - pt2.avi
only the pt2 is imported

I'm using the v0.2.0.152

**Comment by ShanDestromp** [comment] 2017-01-17 13:17
Sounds like it's a duplicate of #145;

**Closed** 2017-01-17 13:22 UTC
