### ISSUE TITLE
Default amounts for quality sliders - community effort

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#519] opened 2017-01-29 21:34 UTC
As discussed in chat, we could really use a good solid set of values for the quality sliders.  It's tricky as the sliders take into account movie runtime, but if we can nail some defaults that'll really help with grabbing solid releases (something CP always struggled with).

This will need to be a community effort as it's a bit of a pain, so suggest away and we can tweak as we go :)

**Comment by Firemad03** [comment] 2017-01-29 22:35
I have experience with only the Blueray-1080p. If you want a maximum size I recommend 16gb for normal release. Some different language take more space because of the multi version of a blueray and some release are using more then 13 gigs.

If you want the remux of a bluray I suggest 30gb or unlimited.

**Comment by Firemad03** [comment] 2017-01-29 22:38
Webdl-1080p should be at 8 gigs maximum. It's always a bdrip I think.

The problem is always the remux type of the blueray. We will need more categories and sliders.

Others quality have others problem too. What happen if I want only the cam of the movies ? the MD version of it or the LD version of it ?

**Comment by Firemad03** [comment] 2017-01-29 22:40
An idea: maybe the quality profile need a must contain word. Like in couchpotato. Something like required, prefered and ignored for each quality type.

**Comment by simonk83** [comment] 2017-01-29 23:43
I guess we need to be aware that the sliders are based on the length of the
movie. So a 16GB max for 1080p may be fine for a 90min movie, if but a 3
hour epic comes along then that 16GB won't be enough. That's why this is a
bit tricky.

It'd almost be easier if it weren't based on runtime and was just a flat
limit, but we'll work it out.

**Comment by simonk83** [comment] 2017-01-29 23:43
Firemad, that's in the there already :)

**Comment by scuppasteve** [comment] 2017-01-30 19:33
Is there anyway to have it setup based on a time frame of like so many MB/min of film high and low setpoint. Because i don't want a Pixar short to be ignored because its 500MB for 1080p. I also would like to add some kind of way to have Audio streams as a quality. 
Like 
1080p BluRay - DTS-HD or TrueHD
1080p BluRay - DTS or DD5.1
1080p WEB-DL - DTS-HD or TrueHD
1080p WEB-DL - DTS or DD5.1
1080p BluRay
1080p WEB-DL
720p BluRay - DTS-HD or TrueHD
720p BluRay - DTS or DD5.1
720p BluRay
1080p hdtv

**Comment by galli-leo** [comment] 2017-01-30 22:20
@simonk83 @scuppasteve That's exactly how it currently works. The max allowed file size is calculated per minute of movie runtime.

**Comment by onedr0p** [comment] 2017-02-23 02:51
Closing this, anyone feel free to update the wiki and discuss in discord.

**Closed by onedr0p** 2017-02-23 02:51 UTC
