### ISSUE TITLE
Library Import: import video file IF prior entry = Missing

### ISSUE THREAD

**Issue by bob454522** [Radarr/Radarr#6448] opened 2021-07-05 18:08 UTC
**Is your feature request related to a problem? Please describe.**
Version: 3.2.2.5080
.NET: Yes (5.0.5)
DB Migration: 195

Im not sure if this is a bug, or just a weird edge-case ive come across.

Ive had several lists running in radarr for over 1 year, so i have several movies in radarr,  which are marked as Missing (and monitored , ie radarr is doing its job of looking/waiting for them). 
**Today i found a local folder of about 30x movies which had never been imported nor indexed by radarr.**

So i did Movies->Library Import-> pointed it to the master folder.

Radarr properly matched all 30x movies, however each showed as "Existing" , so i couldn't import them.

However when looked up the various movie name matches, the radarr entries show as Missing, Monitored.  (so these movies must have been added by one of my lists as some point).

**Describe the solution you'd like**
Cleary, Movies->Library Import,  should import these movie files as the movie entries are MISSING.   (Ofcourse that xyz matched movie is already in radar as monitored AND missing.

(this was NOT a quality profile issue,  as i even tried with all formats allowed).  I also tested this with several movies i was trying to import (which were also already in radarr, but as Monitored, Missing).

(i realize i could do Manual Import , one by one -  but Library Import should still import this file iteself)

Picts of examples:
1- Folder im Library Importing ("Packs_COMBINED" , along with the movie file, in a proper movie sub folder)
![image](https://user-images.githubusercontent.com/60830628/124506371-15c28c80-dd91-11eb-9a60-4a967eb171cb.png)

2- radar Library Import- correctly matching the movie , but showing it as existing (which is also true, however its status = MISSING)
![image](https://user-images.githubusercontent.com/60830628/124506611-a4370e00-dd91-11eb-8907-574faa207032.png)

3- radar "existing" entry (correctly showing as missing, as it was added some time ago via a radarr List ) 
![image](https://user-images.githubusercontent.com/60830628/124506473-54584700-dd91-11eb-91da-38b19ea6a6e9.png)

[AB#1217](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1217)

**Comment by bakerboy448** [comment] 2021-07-05 18:13
The paths are completely different, so it is expected that movie would be missing

it would appear your library was not organized when you imported it originally

library import is to import an existing, organized library.

it sounds like one of the following may be true
- you're downloading into your library folder
- you imported a disorganized library initially and are now suffering the consequences
- Your existing movies did not include the year in the file name and thus the file will never be matched by radarr without manual interaction


I'd suggest taking your movies that are not imported and moving them to a temp folder or moving your existing library ||| and then pointing a manual import at your folder containing all the missing movies

For further discussion please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

Please search prior to making a new issue
Duplicate of https://github.com/Radarr/Radarr/issues/6414

**Closed by bakerboy448** 2021-07-05 18:13 UTC
Labels: Type: Feature Request
