### ISSUE TITLE
Status of movies switches back to "missing"

### ISSUE THREAD

**Issue by raysv** [Radarr/Radarr#2399] opened 2018-01-07 22:40 UTC
Hi, 
Have alittle trouble with my newly installed radarr.

I have added my Library, and it imports everything, when doing a Library scan, it updates all the files correctly, and they show up as "Downloaded"... but once i go in and out of the Movie pane again, they switch back to Status "Missing"...      (if i then do a Complete Library scan again, they go back to status downloaded, but again switches back to missing as soon as i go in and out of the Movie pane)

If i click on the Movie, it says downloaded on the page that apear there.

Anyone with some tips on why this is happening, i can't find any errors on the log page.

Running Version 0.2.0.910

**Comment by raysv** [comment] 2018-01-07 22:48
Looks like a "sort" bug, looks like default it sortet on status, when i sort them after any other coluum they shows as downloaded and not missing.

**Comment by galli-leo** [comment] 2018-02-02 11:17
Duplicate of #2195

**Closed by galli-leo** 2018-02-02 11:17 UTC
