### ISSUE TITLE
[BUG] Remote path doesn't seem to be taken into consideration #212

### ISSUE THREAD

**Issue by Guesch** [Radarr/Radarr#8737] opened 2023-06-26 13:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have a permission error (13) in Transmission when the download is completed.

### Expected Behavior

Here is my setup:
Directory is: /mnt/user/download/completed
Transmission has this mapping: /data/completed = /mnt/user/download/completed
Radarr (& Sonarr) have this mapping: /downloads = /mnt/user/download/completed

In both Radarr & Sonarr, I have this configuration for the remote pathing:
remote path = /data/completed/
local path = /downloads

When comparing in Transmission what is the file location when a torrent start, I have:
From Sonarr: /data/completed (Correct)
From Radarr: /downloads (Incorrect)

Sonarr is working as expected (able to move files after the download is completed), I would expect Radarr to do the same.

### Steps To Reproduce

see above
![image](https://github.com/Radarr/Radarr/assets/61683661/f7e188e5-2d67-467e-acd4-7321c57cd415)

### Environment

```markdown
- OS: Unraid
- Radarr: 4.5.2.7388
- Docker Install: Yes
- Using Reverse Proxy: No
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

[trace.txt](https://github.com/Radarr/Radarr/files/11869218/trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Guesch** [comment] 2023-06-26 13:10
> Sonarr v4?

Nope my (working) Sonarr is V3.0.10.1567.

**Comment by bakerboy448** [comment] 2023-06-26 13:19
- takes a restart to apply
- There's 0 need for a remote path map, simply correct your mounts to be consistent.......  https://trash-guides.info/hardlinks

**Comment by Guesch** [comment] 2023-06-26 13:59
> 

I'm using the exact same configuration on both Sonarr & radarr though ;( 
But I agree, better logging for the mapping will be highly appreciated!

**Comment by Guesch** [comment] 2023-06-26 14:16
Oh I tried to do a couple of modification to use the same path on Radarr than I'm using on Transmission; and I have this new error in the system tab:
_**Remote download client Transmission places downloads in /downloads but this directory does not appear to exist. Likely missing or incorrect remote path mapping.**_

Which is weird because my transmission doesn't have /downloads configured at all.. (my download directory doesn't have a s at the end). It feels as if Radarr is assuming that this is how transmission is configured.. and I cannot seem to find a way so it changes his mind about it ;(

Really I don't know if this is a bug in Radarr, or a more likely event of me messing up somewhere, but I appreciate any assistance you could provide!

**Comment by Guesch** [comment] 2023-06-26 15:35
> @Guesch Can you please confirm this happens with new downloads even after restarting Radarr like @bakerboy448 said?

I'm afraid I still have the same issue after restarting the dockers (both transmission & radarr).

1. I have confirmed that I have no active download with /downloads as "location" in transmission, and yet Radarr still reports (and nowhere in my system I should have a folder "downloads" with a S at the end):
_Remote download client Transmission places downloads in /downloads but this directory does not appear to exist. Likely missing or incorrect remote path mapping._

2. I changed the mapping in Radarr docker to be the same than on transmission:

**Transmission**:
![image](https://github.com/Radarr/Radarr/assets/61683661/c4c7fbc1-b683-44d5-970e-35bfcc80acb0)
![image](https://github.com/Radarr/Radarr/assets/61683661/b52b925e-5768-42bc-803e-1cd948cf7fff)

**Radarr**:
docker run
  -d
  --name='radarr'
  --net='bridge'
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Guesch"
  -e HOST_CONTAINERNAME="radarr"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:7878]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-logo.png'
  -p '7878:7878/tcp'
  -v '/mnt/user/Movies/':'/movies':'rw'
  **-v '/mnt/user/download/completed/':'/data/completed/':'rw'**
  -v '/mnt/user/appdata/radarr':'/config':'rw' 'lscr.io/linuxserver/radarr'
c44bb947955da90dc2a32c0135831025e6e979fd14965dbf55ac6f8f572b17d7

3. For good mesure I added this path in Radarr:
![image](https://github.com/Radarr/Radarr/assets/61683661/e1f0b550-aabc-475f-a920-9d28c5cce0f2)

=> When Radarr adds a new item in transmission, the location is set to "downloads" (which doesn't exist and will result in the error 13)

I'm really sorry if this is a user error, but I appreciate you trying to help regardless.

**Comment by Guesch** [comment] 2023-06-26 21:07
I'm! Transmission 4.0.3.

And to be fair, if I were to redo my system, I would perhaps do it differently but now there are way too many files and dependencies attached to it for me to take the risk of breaking it ;(

I guess my main point was: The remote path (which is exactly to cover my type of situation) works perfectly with Sonarr, but doesn't with Radarr; and I was kinda hoping this was a bug that could be fixed ;)

**Comment by bakerboy448** [comment] 2023-06-26 21:17
It's 99.9999% not a bug and is working just fine for the hundreds of thousands of other users.  so it's something specific to your config.

**Comment by Qstick** [comment] 2023-07-18 02:34
Closing this, feel free to do some logging improvements baker

**Closed by Qstick** 2023-07-18 02:34 UTC
Labels: Area: Download Clients, Type: Enhancement

**Comment by bakerboy448** [comment] 2023-07-18 02:51
https://github.com/Sonarr/Sonarr/pull/5816
