### ISSUE TITLE
Bulk Import Movies - Add Selected with nothing checked off

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2540] opened 2018-02-18 23:54 UTC
nightly //  Radarr Ver. 0.2.0.965

Bulk Import Movies > pick folder > - Add Selected.
There are only 15 items on the page (total was 19) and nothing was checked off. It says its adding 79 movies...
![radarr](http://zoggy.net/firefox_2018-02-18_17-53-17.png)

**Comment by galli-leo** [comment] 2018-02-19 07:26
Are you sure this happens when you don't sort by monitored, profile, etc.? What I am thinking happened: You selected a few items, then sorted by monitored, which caused the items to be visually unselected (but they actually were still selected)

**Comment by thezoggy** [comment] 2018-02-19 18:57
There would be at max of 19 movies for it to import.. only 15 if it only did what was shown.. nothing was selected.

So your saying that the `importing ##` amount got incorrectly calculated by stuff being checked/unchecked?

**Comment by thezoggy** [comment] 2018-02-19 19:07
was able to reproduce this bug.

bulk import movies > selected folder
on the first item, set monitor to no, then profile to something. then clicked 'add selected' with nothing checked off: "no movies selected". did what I would expect.

now to see the bug, 
check box to select everything, now click to sort by monitor. nothing really sorts because there no unique data.. and everything is unchecked. click on add selected, now it shows its adding 11 movies..
![bug2](http://zoggy.net/firefox_2018-02-19_13-04-20.png)

**Comment by thezoggy** [comment] 2018-02-19 19:59
a quick fix to stop the bad behavior would be to disable sorting on monitor/profile/etc until the ui can properly handle sorting?

**Comment by galli-leo** [comment] 2018-02-19 21:12
Yeah, gonna mark this as a duplicate of #2539

**Closed by galli-leo** 2018-02-19 21:12 UTC
Labels: bug, information needed, ui
