### ISSUE TITLE
Better title parsing. 

### ISSUE THREAD

**Issue by shohart** [Radarr/Radarr#5946] opened 2021-02-17 10:34 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when i get "Failed to map movie..." error. Ex. I am trying to add a movie wich has a ' / ' in a title, dividing movie title in dirrerent languages. And radarr can not map this movie with the following error:

`Failed to map movie, found title Форрест Гамп / Forrest Gump [, expected one of: Forrest Gump, Forrest Qamp, Forrest Gump: O Contador de Histórias, フォレスト・ガンプ　一期一会, Форест Гъмп, फॉरेस्ट गंप, 阿甘正傳, Tom Hanks est Forrest Gump
`
So it is cleas that torrent name is a bit tricky for radarr to parse, because of the special characters-dividers.

**Describe the solution you'd like**

I would want radarr to map titles whatewer special character is in the torrent name.

**Describe alternatives you've considered**

Strangely, such problem was never a case in v2 radarr...

**Additional context**

Actually, mapping non-english names seem to be a problem with radarr v3.

**Comment by bakerboy448** [comment] 2021-02-17 12:00
Duplicate of #4507

per #4507; 
Duplicate of #3748 
Duplicate of #3747

**Closed by bakerboy448** 2021-02-17 12:00 UTC
Labels: feature request
