### ISSUE TITLE
Custom formats not same on import and search. Causing import/grab loop for the same release

### ISSUE THREAD

**Issue by tenfire** [Radarr/Radarr#8135] opened 2023-02-19 17:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The title of a release of a search is sometimes different than the filename. I think I have also seen cases where the title is updated with more details but, the filename stays the same.

The problem is that the custom formats is not calculated the same on search and on import. This seems to be causing the same release being grabbed over and over in a loop when the score is higher on search than on import.

### Expected Behavior

Not sure, but a suggestion could be that indexers have an option to "trust" the search result rather than analyzing the imported file when calculating custom formats.

### Steps To Reproduce

1. Have a custom format that appear in the search title of a release but not in the actual file.
2. Movie was monitored and set to upgrade past the quality/score post import.

### Environment

```markdown
- OS: Ubuntu
- Radarr: Radarr 4.3.2.6857
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Brave
- Database: Sqlite
```

### What branch are you running?

Master

### Trace Logs?

No logs

**Comment by bakerboy448** [comment] 2023-02-19 17:16
- For Movie Title? - Duplicate of https://github.com/Radarr/Radarr/issues/4859
- Logs are not optional
- Examples and the custom format jsons are needed as well

**Comment by tenfire** [comment] 2023-02-19 17:35
> 

I think this differs from the other issue.

Sorry not posting any logs, I did not know what to post. If there is any moment you would like me to post log from, I can try to find it.
After looking at the issue you just mentioned I realize that I could post a screenshot instead, hope that is sufficient as a start.

Example movie history:
![brave_sTlYk5XEka](https://user-images.githubusercontent.com/3463357/219964251-35b0034f-4889-4351-a770-347c7a2f9567.png)

HDR:
```json
{
  "name": "HDR",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "HDR",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\bHDR.*\\b"
      }
    }
  ]
}
```

HDR10Plus:
```json
{
  "name": "HDR10Plus",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "HDR10Plus",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\bHDR10Plus|(HDR10\\+)"
      }
    }
  ]
}
```

**Comment by bakerboy448** [comment] 2023-02-19 18:49
See [TRaSH's Guides](https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/) and [his discord](https://trash-guides.info/discord) for related custom format support questions

This behavior is expected and your filenames are using the custom format names that the imported file matched for naming which then no longer match the CF when imported. You need to fix your naming scheme to support how you want your custom formats to work....TRaSH's guides detail this all out

**Closed by bakerboy448** 2023-02-19 18:49 UTC
Labels: Type: Support.
