### ISSUE TITLE
Exiting application on Linux results in 100% CPU lock

### ISSUE THREAD

**Issue by maran** [Radarr/Radarr#2218] opened 2017-10-26 07:01 UTC
Using CTRL+C on a running instance, or having an instance exit because of a port conflict or similar will cause Radarr (and Sonarr) to start using all available CPU power.

The relevant [Sonarr issue can be found here.](https://github.com/Sonarr/Sonarr/issues/2190)

This has been fixed in Sonarr using the [following commit.](https://github.com/Sonarr/Sonarr/commit/f53cad822ad54614c0062926262e6474cae25d57). 

Would it be possible to apply something similar to Radarr?

**Comment by maran** [comment] 2017-12-15 07:07
This fix should be in v0.2.0.910 right? I am still having the issue with the latest release.

**Comment by galli-leo** [comment] 2017-12-15 08:01
Correct.

**Comment by maran** [comment] 2018-01-05 07:55
I am afraid this is not fixed in 0.2.0.910. 

1. Boot Radarr using `mono Radarr.exe`
2. Wait for it to start and confirm web-interface is reachable
3. Press ctrl+c once 
4. Wait around 5-15 seconds, after which load will jump to 100% on all available cores.
5. kill -15 PID will still close the program successfully at this stage.

**Comment by ChrisColotti** [comment] 2018-02-17 19:02
It would be nice if this can get fixed.  Just spoke to https://bytesized-hosting.com/ and they are waiting for this bug to get fixed so they can offer in their app servers alongside Sonarr.

**Comment by galli-leo** [comment] 2018-02-18 15:57
No idea why this is still happening, our code looks exactly like what Sonarr did to fix it.

**Comment by galli-leo** [comment] 2018-02-18 16:28
@Taloth Sorry for tagging you here again 😬, but this goes over my head again. You seem to have quite some experience with mono and the way the main Sonarr run loop works. 

I started debugging this issue and it seems three threads are still running after a ctrl-c: Two times command queue and one on `_container.Resolve<IWaitForExit>().Spin();` (in Host.Bootstrap SpinToExit). I am guessing one of these causes the cpu lock? As to why it doesn't tear down these runloops / threads, I am completely lost.

What I also see is one thread stuck on Environment.Exit, which comes from DoConsoleCancelEvent. Did you do something to e.g. catch that and tear down stuff, we didn't yet pull over?

Full Stack Traces as seen in debugger, maybe it is useful:
<img width="772" alt="screen shot 2018-02-18 at 17 26 52" src="https://user-images.githubusercontent.com/5339762/36354210-025da88c-14d1-11e8-9dd4-7bd05a7835b8.png">
<img width="770" alt="screen shot 2018-02-18 at 17 27 47" src="https://user-images.githubusercontent.com/5339762/36354214-19c2820e-14d1-11e8-9ed1-cef06678211e.png">

**Comment by Taloth** [comment] 2018-02-18 20:49
Update NLog first. I know there was some stuff in NLog that caused issues. That's what led me to update it from 4.4.3 to 4.4.12 on Oct 18, 2017, along with the fix you already cherrypicked.
I'm not sure if that's the cause of the continued issues, but it seems likely... a good starting point anyway.

You seem to be on 4.3.11, we upgraded from that back in Dec 29, 2016 4.3.11 [-> 4.4.1](https://github.com/Sonarr/Sonarr/commit/a2ce4352398d4d8d1a825f5d70c4261906ce0ee2#diff-162ae80e85e010a49aadc3768b719270) [-> 4.4.3](https://github.com/Sonarr/Sonarr/commit/781df8b20a3a7405c5e8a95dd21755feea5ddb52#diff-162ae80e85e010a49aadc3768b719270) [-> 4.4.12](https://github.com/Sonarr/Sonarr/commit/ea5769fdd6547e6ed6827bcc620e2427df505a55#diff-162ae80e85e010a49aadc3768b719270) + [Fix](https://github.com/Sonarr/Sonarr/commit/e01e8223940ee3f7254750bcbd8340a431772f62#diff-162ae80e85e010a49aadc3768b719270)

**Comment by galli-leo** [comment] 2018-02-18 23:13
Well that was too soon, still seeing 100% CPU on my Mac.
@Taloth Thanks for the tip, I will start digging around, but honestly I probably won't find out what causes this.

**Comment by danjames92** [comment] 2018-02-18 23:30
Did you include the fix?

**Comment by galli-leo** [comment] 2018-02-19 00:24
In the aboce commit? Yeah but it does nothing.

**Comment by Taloth** [comment] 2018-02-19 08:32
With maran I ended up ssh to his system and used mono-dbg + gdb but I'm really foggy on the details. https://github.com/Sonarr/Sonarr/issues/2190#issuecomment-338310315

**Comment by galli-leo** [comment] 2018-02-19 08:47
Well I am able to replicate it on my mac, so debugging isn't an issue.

@maran Could you try out the latest nightly? Maybe the issue is different on osx, as I am only seeing one core used at 100% not all 8.

**Comment by Taloth** [comment] 2018-02-19 08:52
The screenshot you have with DoConsoleCancelEvent, that's different... Sonarr/Radarr isn't doing that. Are you sure your mac/mono doesn't have different behavior?

The issue was that Environment.Exit was called prior to nlog shutting down, which caused some finalizer issues. Which is why in the fix we shut it down first. in ConsoleApps error handling. But that's unrelated to Ctrl+C.

I'm thinking that with updating nlog you fixed maran's issue, but your repro scenario is different.

What you could try is replace [this](https://github.com/Radarr/Radarr/blob/e4a3e63c446ac726f607a9c867c873360319a42d/src/NzbDrone.Host/ApplicationServer.cs#L56) with `Console.CancelKeyPress += (sender, eventArgs) => LogManager.Shutdown();`... but test it first.
Theory is that CancelKeyPress is raised, followed by Environment.Exit (as in your screenshot). So adding the logger shutdown in the event should prevent that particular issue.
(iirc, Configuration = null does the same, except it's async while Shutdown waits for the teardown to complete)

**Comment by maran** [comment] 2018-02-19 08:56
@galli-leo Something is different now. Only one thread appears to be crashing and it will die with a simple `kill` instead of a `kill -9`. I think there is one more thread just hanging but I couldn't tell you which one.

**Comment by Taloth** [comment] 2018-02-19 08:59
maran, is that with the port conflict or sigint?

**Comment by maran** [comment] 2018-02-19 09:00
This is with `ctrl+c` on the running instance.

**Comment by galli-leo** [comment] 2018-02-19 09:04
@Taloth 
> The screenshot you have with DoConsoleCancelEvent, that's different... Sonarr/Radarr isn't doing that. 

Yeah that's what I guessed. As for whether mac/mono is different to linux/mono, no idea. Probably not that different. Question is, why doesn't that lead to the command queue being "aborted"?

> What you could try is replace this with Console.CancelKeyPress += (sender, eventArgs) => LogManager.Shutdown();... but test it first.
Interesting, that results in the cpu going to 100% immediately.

**Comment by galli-leo** [comment] 2018-02-19 09:05
@maran At least some progress I guess. Did you try the port conflict?

**Comment by maran** [comment] 2018-02-19 09:11
@galli-leo Just tried the port conflict case and that one actually works fine now!

The only issue is pressing ctrl+c while the daemon is running in an active terminal session although for my use-cases this is not really a concern. I will try one more test with `start-stop-daemon` to ensure things work there but it's looking good now on the latest nightly.

**Comment by Taloth** [comment] 2018-02-19 09:30
@galli-leo Ok, so what you need to do it trap the CancelKeyPress entirely.

Step 1:

```
Console.CancelKeyPress += (sender, eventArgs) => { eventArgs.Cancel = true; }
```
That should prevent the shutdown entirely and the 100%. Confirm that first.

Step 2:

Replace the whole thing with:

class CancelHandler
{
  private object _syncRoot;
  private volatile bool _cancelInitiated;
  
  public CancelHandler()
  {
    Console.CancelKeyPress += HandlerCancelKeyPress;
  }
  
  private void HandlerCancelKeyPress(object sender, ConsoleCancelEventArgs e)
  {
    // Tell system to ignore the Ctrl+C and not terminate. We'll do that.
    e.Cancel = true;
	
    var shouldTerminate;
    lock (_syncRoot)
    {
      shouldTerminate = _cancelInitiated;
      _cancelInitiated = true;
    }
    
    // TODO: Probably should schedule these on the threadpool.
    if (shouldTerminate)
    {
      UngracefulShutdown();
    }
    else
    {
      GracefulShutdown();
    }	
  }
  
  private void GracefulShutdown()
  {
    Console.WriteLine("Shutdown requested, press Ctrl+C again to terminate directly.");
    // TODO: Sent ApplicationShutdownRequested event or something like it.
  }
  
  private void UngracefulShutdown()
  {
    Console.WriteLine("Termination requested.");
    // TODO: Kill it. Shutdown NLog and invoke Environment.Exit.
  }
}
``` 

WIth that code you should only see the console writelines, it shouldn't actually terminate. Then proceed to implement the two methods.
CancelHandler will need to be created and it'll need ILifecycleService or IEventAggregator to be able to do the graceful shutdown. But you get the idea.

**Comment by maran** [comment] 2018-02-19 10:10
@galli-leo Are you willing to create a new release soon or would you consider this nightly stable enough to roll out across all my servers?

**Comment by galli-leo** [comment] 2018-02-19 10:29
@Taloth Thanks a ton for the code, will try shortly!

@maran Yeah I want to release soon, but haven't heard back how the metadata stuff is working on the latest nightly.

**Comment by galli-leo** [comment] 2018-02-19 10:42
@Taloth CancelHandler seems to be working (had to initialize the _syncRoot). Should I make it an interface for ILifecycleService or Just create a TinyIoC object and resolve?

**Comment by Taloth** [comment] 2018-02-19 10:59
I'd do it the same as the other stuff in Bootstrap.cs, `_container.Resolve<ICancelHandler>().Attach()` (so yes, give it an interface and move the ctor code to an 'Attach' method).
Bootstrap is one of the few places where _container is accessed directly.

**Comment by galli-leo** [comment] 2018-02-19 11:10
@Taloth Interesting, with lifecycle service the second part isn't even needed (Ungraceful shutdown). If you feel this isn't too hacky, I will commit it shortly.

**Comment by Taloth** [comment] 2018-02-19 11:19
The reason why I added that is because Ctrl+C is supposed to be reliable. the lifecycle service raises an event and allows a lot of potentially blocking stuff run, it doesn't actually kill the app, it lets it shut down on it's leisure. By having the UngracefulShutdown on the second Ctrl+C, it allows a user to terminate it with a bit more prejudice before having to resort to kill -9.
That would allow the ApplicationShutdownRequestedEvent to wait for RssSync and such to finish in the future (iirc it doesn't atm)

**Comment by galli-leo** [comment] 2018-02-19 11:49
@Taloth Cool, thanks a lot for the assistance.

@maran Ctrl-c should be fine now, can you test that?

**Comment by maran** [comment] 2018-02-19 12:25
@galli-leo 

```
Shutdown requested, press Ctrl+C again to terminate directly.
[Info] LifecycleService: Shutdown requested.
maran@atalanta:~/apps/972/Radarr$
```

Works like a charm! 👍

**Comment by Taloth** [comment] 2018-02-19 12:32
It's still odd, Sonarr had the same code (except newer nlog). Makes me wonder if newer mono versions changed how Ctrl+C got handled internally. But that would mean Ctrl+C fails on Sonarr given the same environment.
Makes me wonder if Radarr still has something else that gets stuck.

**Comment by galli-leo** [comment] 2018-02-19 12:45
@Taloth Psst it works now :P. Yeah no idea why it wouldn’t work before. Maybe I can replicate the same thing for Sonarr, will let you know, if I do.

**Comment by galli-leo** [comment] 2018-02-19 15:07
@Taloth Well some bad news: 100% CPU lock occurs for me on OSX with Sonarr master version, will checkout latest dev branch to verify.

**Comment by Taloth** [comment] 2018-02-19 15:54
@galli-leo No need to check develop. I'll simply cherrypick from Radarr for a change :smile:
At least both apps behave the same, that's a relieve.

**Comment by benj3** [comment] 2018-02-20 09:00
Cheers for the work 👍

**Comment by benj3** [comment] 2018-02-22 08:58
Hi @galli-leo 

After some testing using the current nightly build of Radarr still receiving the 100% CPU but not straightaway. Seems to happen once the Instance has been running for some time not sure how long  I have been testing every 24hours the last two days and have had the same result:

**To Recreate:**
- mono Radarr.exe
- Wait 24 Hours
- Ctrl + C on Instance

**Result:**
```
[Info] RssSyncService: RSS Sync Completed. Reports found: 48, Reports grabbed: 0
Shutdown requested, press Ctrl+C again to terminate directly.
[Info] LifecycleService: Shutdown requested.
```

Strangely this isn't happening if I start the Radarr instance then stop it straight away and it closes fine.

**Comment by maran** [comment] 2018-03-07 08:54
I found a way to consistently trigger the Ctrl + C issue again.

* Start with a clean Radarr instance
* mono Radarr.exe
* Visit /system/tasks and trigger the "Rss Sync" / "PreDB Sync" (it seems to also work with "Application Update" but since that probably tries to restart Radarr I left that case out for now)
* CTRL + C the running instance.

**Comment by galli-leo** [comment] 2018-03-07 09:40
@Taloth @maran Seems like it hangs on the command executor? Maybe we can get a reference to that in the new class for handling ctrl c and kill any running commands?

**Comment by bakerboy448** [comment] 2020-11-14 06:40
Closing
v0.2 is no longer being actively developed.

If this is still an issue on **recent** v3 builds, please open a new issue.

**Closed by bakerboy448** 2020-11-14 06:40 UTC
Labels: bug, confirmed, priority:medium, v0.2 legacy
