### ISSUE TITLE
Prioritizing indexer flags over protocol

### ISSUE THREAD

**Issue by Firelfy** [Radarr/Radarr#2821] opened 2018-05-30 16:46 UTC
At the moment it looks as though Radarr prioritizes indexer flags over protocol (torrent/usenet).

With `Prefer Special Indexer Flags` and `Prefer Usenet` both enabled, the torrent will be snatched if it has a indexer flag such as Freeleech.

There was another issue on this here: #1814 however it was auto closed by the stale bot.

It would be ideal if the `Prefer Special Indexer Flags` only applied within the protocol, rather than ignoring protocol, giving indexer tags a higher weight to protocol.

**Radarr Version: 0.2.0.1067**

**Mono Version: 5.12.0.226 (tarball Thu May 3 09:48:32 UTC 2018)**

**Comment by Qstick** [comment] 2018-05-30 23:59
@galli-leo would you agree on this logic? I would tend to agree that protocol should be prioritized first, but I can see where could be different user to user

**Comment by hotio** [comment] 2018-05-31 06:36
Protocol should have heavier weight, just my 2 cents.

**Comment by galli-leo** [comment] 2018-05-31 11:46
Duplicate of #1814

**Comment by galli-leo** [comment] 2018-05-31 11:47
I think protocol should trump indexer flags, if someone wants to change that, they can always use custom formats

**Closed** 2018-05-31 11:46 UTC
