### ISSUE TITLE
Authentication required locally even when set to "disabled for local addresses" using IPv6

### ISSUE THREAD

**Issue by skykingjwc** [Radarr/Radarr#9348] opened 2023-10-29 18:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Authentication is set to disabled for local addresses.   Username and password still required when accessing UI from local network with private 10.x.x.x. address scheme.  Looking at the source, it doesn't appear the IPV6 addresses a considered local.

### Expected Behavior

Authentication should not be mandatory. The option to disable auth altogether should be available to the administrator.  Those of us running Cloudflare don't' need (or want) it anyway, as auth is provided by the tunnel.  If a user has the knowledge to set up Radarr, and a NZB indexer, and SAB Downloader, and Medusa, and Plex which are all typically associated with a Radarr install, then surely they have the knowledge to setup or disable auth as needed and fully understand the implications of doing so.   Particularly true if the "feature" does not work correctly in all cases and has no configuration options such as setting local IP address ranges and completely ignoring the existence of IPv6. 

### Steps To Reproduce

1. Set authentication to not required locally
2. Access UI via mdns .local address using IPV6
3. Will be prompted for password regardless of auth setting

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 5.0.3.8127
- Docker Install: NO
- Using Reverse Proxy: NO
- Browser: Chrome
- Database: Sqlite 3.37.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

2023-10-29 18:30:12.8|Trace|CommandQueueManager|Updating command status
2023-10-29 18:30:12.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-10-29 18:30:12.8|Trace|EventAggregator|Publishing CommandExecutedEvent
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandExecutedEvent -> QualityDefinitionController
2023-10-29 18:30:12.8|Trace|EventAggregator|CommandExecutedEvent <- QualityDefinitionController
2023-10-29 18:30:12.8|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0041401]
2023-10-29 18:30:12.9|Trace|Http|Req: 1062 [GET] /api/v3/command (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:12.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:12.9|Trace|CommandQueueManager|Getting all commands
2023-10-29 18:30:12.9|Trace|Http|Res: 1062 [GET] /api/v3/command: 200.OK (3 ms)
2023-10-29 18:30:12.9|Debug|Api|[GET] /api/v3/command: 200.OK (3 ms)
2023-10-29 18:30:12.9|Trace|Http|Req: 1063 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:12.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:12.9|Trace|Http|Res: 1063 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:12.9|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:12.9|Trace|Http|Req: 1064 [GET] /api/v3/command (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:12.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:12.9|Trace|CommandQueueManager|Getting all commands
2023-10-29 18:30:12.9|Trace|Http|Res: 1064 [GET] /api/v3/command: 200.OK (2 ms)
2023-10-29 18:30:12.9|Debug|Api|[GET] /api/v3/command: 200.OK (2 ms)
2023-10-29 18:30:13.4|Trace|Http|Req: 1065 [GET] / (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:13.4|Trace|Http|Res: 1065 [GET] /: 302.Redirect (1 ms)
2023-10-29 18:30:13.4|Trace|Http|Req: 1066 [GET] /login?ReturnUrl=%2F (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:13.4|Trace|Http|Res: 1066 [GET] /login?ReturnUrl=%2F: 200.OK (1 ms)
2023-10-29 18:30:13.6|Trace|Http|Req: 1067 [GET] /favicon.ico?h=VezoKLEyl0HB1VOmV11x8Q (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:13.6|Trace|Http|Res: 1067 [GET] /favicon.ico?h=VezoKLEyl0HB1VOmV11x8Q: 302.Redirect (1 ms)
2023-10-29 18:30:13.6|Trace|Http|Req: 1068 [GET] /login?ReturnUrl=%2Ffavicon.ico%3Fh%3DVezoKLEyl0HB1VOmV11x8Q (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:13.6|Trace|Http|Res: 1068 [GET] /login?ReturnUrl=%2Ffavicon.ico%3Fh%3DVezoKLEyl0HB1VOmV11x8Q: 200.OK (1 ms)
2023-10-29 18:30:16.0|Trace|Http|Req: 1069 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:16.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:16.0|Trace|Http|Res: 1069 [GET] /api/v3/log/file: 200.OK (1 ms)
2023-10-29 18:30:16.0|Debug|Api|[GET] /api/v3/log/file: 200.OK (1 ms)
2023-10-29 18:30:16.8|Trace|Http|Req: 1070 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:16.8|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:16.8|Trace|Http|Res: 1070 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:16.8|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:17.9|Trace|Http|Req: 1071 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:17.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:17.9|Trace|Http|Res: 1071 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:17.9|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:20.3|Trace|Http|Req: 1072 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:20.3|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:20.3|Trace|Http|Res: 1072 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:20.3|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:21.0|Trace|Http|Req: 1073 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:21.0|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:21.0|Trace|Http|Res: 1073 [GET] /api/v3/log/file: 200.OK (1 ms)
2023-10-29 18:30:21.0|Debug|Api|[GET] /api/v3/log/file: 200.OK (1 ms)
2023-10-29 18:30:24.2|Trace|Http|Req: 1074 [GET] / (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:24.2|Trace|Http|Res: 1074 [GET] /: 302.Redirect (1 ms)
2023-10-29 18:30:24.2|Trace|Http|Req: 1075 [GET] /login?ReturnUrl=%2F (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:24.2|Trace|Http|Res: 1075 [GET] /login?ReturnUrl=%2F: 200.OK (1 ms)
2023-10-29 18:30:24.2|Trace|Http|Req: 1076 [GET] /favicon.ico?h=VezoKLEyl0HB1VOmV11x8Q (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:24.2|Trace|Http|Res: 1076 [GET] /favicon.ico?h=VezoKLEyl0HB1VOmV11x8Q: 302.Redirect (1 ms)
2023-10-29 18:30:24.3|Trace|Http|Req: 1077 [GET] /login?ReturnUrl=%2Ffavicon.ico%3Fh%3DVezoKLEyl0HB1VOmV11x8Q (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:24.3|Trace|Http|Res: 1077 [GET] /login?ReturnUrl=%2Ffavicon.ico%3Fh%3DVezoKLEyl0HB1VOmV11x8Q: 200.OK (1 ms)
2023-10-29 18:30:24.8|Trace|Http|Req: 1078 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:24.8|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:24.8|Trace|Http|Res: 1078 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:24.8|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:27.6|Trace|Http|Req: 1079 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:27.6|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:27.6|Trace|Http|Res: 1079 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:27.6|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:28.4|Trace|Http|Req: 1080 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:28.4|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:28.4|Trace|Http|Res: 1080 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:28.4|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:29.5|Trace|Http|Req: 1081 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:29.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:29.5|Trace|Http|Res: 1081 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:29.5|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:30.6|Trace|Http|Req: 1082 [GET] /login?ReturnUrl=%2F (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:30.6|Trace|Http|Res: 1082 [GET] /login?ReturnUrl=%2F: 200.OK (2 ms)
2023-10-29 18:30:30.6|Trace|Http|Req: 1083 [GET] /Content/styles.css?h=VAwjWra8YBWH8JiyE7JFDA (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:30.6|Trace|Http|Req: 1084 [GET] /Content/Fonts/fonts.css?h=mBv1x1/yHnvphLclzeQIBA (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:30.6|Trace|Http|Req: 1085 [GET] /Content/Images/logo.svg?h=UK+1ymD8NGZtp+MiKdEQRg (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:30.7|Trace|Http|Res: 1084 [GET] /Content/Fonts/fonts.css?h=mBv1x1/yHnvphLclzeQIBA: 200.OK (3 ms)
2023-10-29 18:30:30.7|Trace|Http|Res: 1083 [GET] /Content/styles.css?h=VAwjWra8YBWH8JiyE7JFDA: 200.OK (4 ms)
2023-10-29 18:30:30.7|Trace|Http|Res: 1085 [GET] /Content/Images/logo.svg?h=UK+1ymD8NGZtp+MiKdEQRg: 200.OK (3 ms)
2023-10-29 18:30:30.7|Trace|Http|Req: 1086 [GET] /Content/Fonts/Roboto-Regular.woff2?v=1.3.0 (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:30.7|Trace|Http|Res: 1086 [GET] /Content/Fonts/Roboto-Regular.woff2?v=1.3.0: 200.OK (2 ms)
2023-10-29 18:30:30.7|Trace|Http|Req: 1087 [GET] /favicon.ico?h=VezoKLEyl0HB1VOmV11x8Q (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:30.7|Trace|Http|Res: 1087 [GET] /favicon.ico?h=VezoKLEyl0HB1VOmV11x8Q: 302.Redirect (0 ms)
2023-10-29 18:30:30.7|Trace|Http|Req: 1088 [GET] /login?ReturnUrl=%2Ffavicon.ico%3Fh%3DVezoKLEyl0HB1VOmV11x8Q (from 2601:346:e80:2dd0:5135:f6a7:e01:7688 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:30.7|Trace|Http|Res: 1088 [GET] /login?ReturnUrl=%2Ffavicon.ico%3Fh%3DVezoKLEyl0HB1VOmV11x8Q: 200.OK (1 ms)
2023-10-29 18:30:33.5|Trace|Http|Req: 1089 [GET] /api/v3/log/file (from 68.*.*.2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
2023-10-29 18:30:33.5|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-10-29 18:30:33.5|Trace|Http|Res: 1089 [GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:33.5|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2023-10-29 18:30:33.8|Trace|Scheduler|Pending Tasks: 0

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2023-10-29 18:48
> Authentication should not be mandatory.

it is not, refer to the more info link from the auth setup / see the FAQ

> The option to disable auth altogether should be available to the administrator. 

this exists, see the faq

Disabling auth is a duplicate of numerous github issues


`2601:346:e80:2dd0:5135:f6a7:e01:7688` does not appear to be a local ipv6 address

https://github.com/Radarr/Radarr/blob/8fb21e073b7f7d1b4b090f20fca0cd19acab2aad/src/NzbDrone.Common/Extensions/IpAddressExtensions.cs#L31-L33

Please use [Discord](https://radarr.video/discord) for support/questions.

**Closed by bakerboy448** 2023-10-29 18:48 UTC
Labels: Type: Bug, Status: Needs Triage
