### ISSUE TITLE
as of 10/30, nightly on Windows 10, MediaInfo 0x8007000B

### ISSUE THREAD

**Issue by masterfork** [Radarr/Radarr#3138] opened 2018-10-31 01:02 UTC
Windows 10, nightly, problems with mediainfo:

MediaInfo could not be loaded An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
--

**Radarr Version: 
0.2.0.1212

**Debug Logs:
18-10-30 20:39:33.0|Error|VideoFileInfoReader|Unable to parse media info from file: N:\Movies\Drop Dead Fred (1991)\Drop.Dead.Fred.1991.1080p.BluRay.x264-HD4U\Drop.Dead.Fred.1991.1080p.BluRay.x264-HD4U.mkv

[v0.2.0.1212] System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.MediaInfo_New()
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 41

FYI: somebody mentioned it on Reddit as well (I commented)
https://www.reddit.com/r/radarr/comments/9ssnnw/nightly_anyone_getting_mediainfo_load_errors/

**Comment by galli-leo** [comment] 2018-10-31 01:36
@rfgamaral Have you seen this?

**Comment by geogolem** [comment] 2018-10-31 02:30
I'm also experiencing this with several video files that seemed to be fine before....

**Comment by rfgamaral** [comment] 2018-10-31 02:54
Can we get more info on this? You skipped important data from the bug report template, like steps to reproduce and OS information :)

**Comment by rfgamaral** [comment] 2018-10-31 03:55
I'm no 100% sure of this (around 99.9% - though @geogolem wasn't yet able to fix it on his side) but it might be related to the fact that I used the 64-bit version of `MediaInfo.dll` instead of the 32-bit one (stupid mistake).

Using `MediaInfo.dll` from [this .zip file](https://mediaarea.net/download/binary/libmediainfo0/18.08.1/MediaInfo_DLL_18.08.1_Windows_i386_WithoutInstaller.zip) should fix this issue but I have no means to test this myself...

**Comment by geogolem** [comment] 2018-10-31 04:00
I tested and believe this does solve it..

**Comment by lostandlost** [comment] 2018-10-31 04:07
The 32-bit dll fixed the issue for me as well.

**Comment by geogolem** [comment] 2018-10-31 04:11
so, i think you were correct, in that these are movies that were recently added.. I think the movies that were exposing this issue, were ones that were added after my build was updated...  using the 32 Bit dll solved the problem, switching back to the 64 bit dll after using the 32 bit dll, did not re-introduce the problem, since the movie had already run through with the 32 bit dll... 

this led to some confusion, as I didnt realize that all the movies that were having this problem were recently downloaded -- sorry about that..

In any case, the 32 bit dll definitely solves it! :)

**Comment by geogolem** [comment] 2018-10-31 04:45
I pushed the 32bit dll @rfgamaral provided to the develop branch and am closing this issue.

Thanks @rfgamaral  for fixing - i hope you dont mind that I pushed the change.

**Closed by geogolem** 2018-10-31 04:45 UTC

**Comment by rfgamaral** [comment] 2018-10-31 09:16
@geogolem Not a problem, as long as it's fixed :)

**Comment by galli-leo** [comment] 2018-11-19 09:02
@Zamana Make sure the container has MediaInfo installed and is accessible by Radarr as well.

**Comment by rfgamaral** [comment] 2018-11-19 15:23
This fix related to this issue was to simply replace a `.dll` file packaged with Radarr. The other issue you mentioned simply changed code related to how MediaInfo was being used. Neither changed anything related to how MediaInfo is installed or used.

I'm not 100% aware of how Radarr under Linux handles MediaInfo but AFAIK it doesn't use the `.dll` (that's for Windows only). @galli-leo Please correct me if I'm wrong.

@Zamana I suggest you open up a different issue and please detail your issue as much as possible.

**Comment by Zamana** [comment] 2018-11-19 16:35
> This fix related to this issue was to simply replace a `.dll` file packaged with Radarr. The other issue you mentioned simply changed code related to how MediaInfo was being used. Neither changed anything related to how MediaInfo is installed or used.
> 

Ok, but I thought that this "fix" could had generated a "collateral effect" on the Linux side, by some way, because, as I said, in the previous version everything is running fine.

> I'm not 100% aware of how Radarr under Linux handles MediaInfo but AFAIK it doesn't use the `.dll` (that's for Windows only). @galli-leo Please correct me if I'm wrong.

In Linux the equivalent to DLLs are SOs (shared objects).

> 
> @Zamana I suggest you open up a different issue and please detail your issue as much as possible.

Ok, I will!

Thanks.
Regards.

**Comment by rfgamaral** [comment] 2018-11-19 16:50
> Ok, but I thought that this "fix" could had generated a "collateral effect" on the Linux side, by some way, because, as I said, in the previous version everything is running fine.

I highly doubt it, but, I could be wrong 😛 

> In Linux the equivalent to DLLs are SOs (shared objects).

I'm aware, but AFAIK, those are not included with Radarr, they are provide by the system (ie: you have to have MediaInfo installed on the system).

**Comment by Zamana** [comment] 2018-11-19 17:05
> (...) 
> I'm aware, but AFAIK, those are not included with Radarr, they are provide by the system (ie: you have to have MediaInfo installed on the system).

That's the point! 

Maybe (maybe!) Radarr could be looking for the "embedded" MediaInfo.dll when, in fact, on Linux, it is provided by another package, outside the Radarr installation. Now the error message makes sense:

`18-11-17 15:33:58.1|Error|VideoFileInfoReader|mediainfo is required but was not found
[v0.2.0.1217] System.DllNotFoundException: MediaInfo.dll
  at (wrapper managed-to-native) NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo:MediaInfo_New ()
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo..ctor () [0x00006] in <eb6d7ee69d274d0eb2c19e6d87dabfdc>:0
  at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo (System.String filename) [0x00021] in <eb6d7ee69d274d0eb2c19e6d87dabfdc>:0
`

Because MediaInfo is installed and is accessible:

`root@radarr:/home/plex/radarr/logs# mediainfo --version
MediaInfo Command line,
MediaInfoLib - v18.08.1
`

Thanks.
Regards.

**Comment by rfgamaral** [comment] 2018-11-20 00:01
But the changes in either issues changed anything related to how Radarr uses the MediaInfo library. I don't know what could possibly have changed to cause this. Either way, please open a different issue.

**Comment by galli-leo** [comment] 2018-11-20 09:19
@Zamana Make sure you have downloaded the linux version of Radarr and not the windows version.
