### ISSUE TITLE
Fix removing of non latin characters in parser.

### ISSUE THREAD

**Issue by valantislevas** [Radarr/Radarr#2355] opened 2017-12-18 12:34 UTC
**Radarr Ver. 0.2.0.910**

**Logs:**

i tried to manually search for a movie with restriction tag on my greek language like: ΜΕΤΑΓΛΩΤΙΣΜΕΝΟ 
Radarr finds it but on title greek characters doesnt show up and also on rejection details says that ΜΕΤΑΓΛΩΤΙΣΜΕΝΟ doesnt meet.. its like cant see the greek chars on search title..

can somehow fix it ?

Explain screenshot:

https://image.prntscr.com/image/P9mDpLAUQjKwHYRUYRSY7w.png

**Comment by valantislevas** [comment] 2017-12-18 12:43
ΜΕΤΑΓΛΩΤΙΣΜΕΝΟ in torrent title in english means that the audio is on GREEK language

**Comment by valantislevas** [comment] 2017-12-18 23:08
no one knows something? only with greek is that issue? or also other foreign language have..?

**Comment by Atka122** [comment] 2017-12-24 21:40
Hi,
The same issue with the Hungarian... unfortunately if I set the language to Hungarian, the title of the movie will be the Hungarian title and the indexers will use it for search. However, as I think there is a small mistake with the characters with accent. Perhaps, the code should only be extended with a url encoding or something. I didn't debug the root cause of this.
Could you check what can be the issue? With this version there is no way to download movies with sync of those languages which use another letters than simple English letters.
Thank you for your help!

**Comment by valantislevas** [comment] 2017-12-29 09:33
i see so we must wait for the developer to fix that for all foreign languages

**Comment by valantislevas** [comment] 2018-03-21 11:55
we have any news about it? thanks!!!!! for the great work!

**Comment by ALERTua** [comment] 2018-05-05 12:30
@galli-leo, almost all non-English languages contain such characters. please, raise the priority of this bug. thank you <3

**Comment by valantislevas** [comment] 2018-06-26 23:03
any updates for this? thanks for the great work :D

**Comment by Jeronyson** [comment] 2018-09-17 13:13
Any update? Can't use Radarr, because all non-latin symbols strip.

**Comment by Jeronyson** [comment] 2018-09-19 10:18
@galli-leo 

In example, I use only russian torrent trackers (like kinozal.tv - one of the most popular movie torrent tracker in Russia), where all torrents contain russian tags in title (for audio type, like dubbed (ДБ), multi voice (ПМ) and etc.)
And I want to download only dubbed movies (which contains ДБ in title) and that's not possible.

Very sad, that such small bug is not important to you and you moved it from "In Progress" to "Backlog"...

**Comment by galli-leo** [comment] 2018-09-19 17:00
No there aren‘t any updates unfortunately. Last time I looked at this, it seemed like it would require quite a bit of work to fix as well as test every case.

I would like to fix this more generally in combination with other issues, such as special chars being removed causing wrong results, etc.

This would require some more work, but imo would pay off in the end.

Also I currently don‘t have that much free time to work on Radarr since I just started university. (That‘s one of the reasons the issue was put into backlog)

**Comment by Dm3Ch** [comment] 2019-06-11 20:51
Is there any updates?

I'm not sure, but it seems that Sonarr works without troubles with russian torrent trackers, while in Radarr i'm always getting "Russian is wanted, but found English" for some trackers.

If it is so maybe it is possible to backport this fix from Sonarr?

**Comment by Pixelsru** [comment] 2019-07-22 01:55
> Is there any updates?
> 
> I'm not sure, but it seems that Sonarr works without troubles with russian torrent trackers, while in Radarr i'm always getting "Russian is wanted, but found English" for some trackers.
> 
> If it is so maybe it is possible to backport this fix from Sonarr?

the same

**Comment by vlevas** [comment] 2020-01-01 23:24
hello.. happy new year!!
do we have any news of this?

**Comment by vlevas** [comment] 2020-08-16 16:24
hello do we have any news about this?

thanks a lot..

**Comment by bakerboy448** [comment] 2020-11-14 08:14
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

**Closed by bakerboy448** 2020-11-14 08:14 UTC
Labels: bug, confirmed, parser, priority:low
