### ISSUE TITLE
Title search are done without apostrophe making the film unfoundable

### ISSUE THREAD

**Issue by Th0mC** [Radarr/Radarr#4502] opened 2020-06-08 15:04 UTC
**Describe the bug**
In French, titles can contain apostrophe as "l'adieu" for example.
Looking at the log, I discovered that the movie is searched without apostrophe in the title "ladieu" and so, not found :(

**To Reproduce**
Try to search for a movie with an apostrophe in the title

**Expected behavior**
A search with apostrophe in the title or at least apostrophe replaced by a space

**Platform Information (please complete the following information):**
 - OS: Macosx 10.14.6
 - Mono Version: 6.10.0.104
 - Radarr Version 0.2.0.1480

**Debug Logs**
Radarr log : 
2020-6-8 17:01:01.8|Info|NzbSearchService|Searching 6 indexers for [L?Adieu ? la nuit]
2020-6-8 17:01:06.3|Info|DownloadDecisionMaker|No results found
2020-6-8 17:01:06.3|Info|MovieSearchService|Movie search completed. 0 reports downloaded.

Jackett logs:

2020-06-08 17:01:06 | Info | Found 0 releases from Torrent9 for: ladieu à la nuit
2020-06-08 17:01:05 | Info | Found 0 releases from RARBG for: ladieu à la nuit
2020-06-08 17:01:04 | Info | Found 0 releases from KickAssTorrent for: ladieu à la nuit
2020-06-08 17:01:03 | Info | Found 0 releases from OxTorrent for: ladieu à la nuit
2020-06-08 17:01:02 | Info | Found 0 releases from cpasbien clone for: ladieu à la nuit
2020-06-08 17:01:02 | Info | Found 0 releases from MagnetDL for: ladieu à la nuit

[AB#849](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/849)

**Comment by almottier** [comment] 2020-07-18 19:54
I have the same issue.

**Comment by Jorman** [comment] 2020-09-22 21:31
Same here with Radarr 3.0.0.3746
apostrophe is needed for some movies in foreign languages but some trackers don't support apostrophe during search, for this reason, in theory, inside jackett any tracker have different rules about special char substitution, so for example, for the Italian title `L'avvocato del diavolo`
is ok if `L'avvocato del diavolo` -> `L avvocato del diavolo`
is not ok if `L'avvocato del diavolo` -> `Lavvocato del diavolo`

So please, if you have to do it, substitute apostrophe with space.

J

**Comment by sarakha63** [comment] 2020-10-16 18:37
same here this is quite annoying. deleting apostrophe is quite rude. Lets replace it with something else. And why not an option where we choose what to replace for

**Comment by bakerboy448** [comment] 2020-11-14 08:25
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

**Comment by almottier** [comment] 2020-11-14 10:06
Yes I still have this problem on latest v3

**Comment by gchapeyrout** [comment] 2020-12-14 14:43
I have the same very annoying issue with latest V3 version today.

**Comment by kiralex** [comment] 2021-01-03 12:42
I confirm I have the same issue.

**Comment by JamesDAdams** [comment] 2021-01-03 20:17
same issue in version 3

**Comment by JamesDAdams** [comment] 2021-01-03 20:24
**Expected behavior**
A search with apostrophe in the title or at least apostrophe replaced by a space

is a good solution and it's work !

**Comment by JamesDAdams** [comment] 2021-01-03 20:50
Best solution for everyone ?

![image](https://user-images.githubusercontent.com/20860324/103488537-b7324b00-4e0d-11eb-9b96-24f9452d41b8.png)

**Comment by kiralex** [comment] 2021-01-03 21:29
It would be awesome 😉

**Comment by JamesDAdams** [comment] 2021-01-04 13:26
![Untitled](https://user-images.githubusercontent.com/20860324/103539763-e510a180-4e98-11eb-915e-269a3b15576c.png)

**Comment by Jorman** [comment] 2021-01-04 14:23
I tried in the past to convince markus (sonarr side) to implement a "simple" way to easly hande all these situations, because all of these are by foreign languages.
Sonarr/Radarr, in generall all of them are English based.
See my old request here on sonarr side
https://github.com/Sonarr/Sonarr/issues/2779
Here on Jackett side
https://github.com/Jackett/Jackett/issues/2743
My idea is pretty simple, during a search request via Jackett, radarr/sonarr and so .. specify the selected language, so on Jackett side there must be a substitution table to handle all situations, special characters, apostrophe, for any languages.
In this way, even the indexer code will be more simple, all equal without strange substitutions, because the're 2 issue, languages and the people that make release :D) most of the time they don't respect standard and Radarr/Sonarr can't find the release, but a table of substitution can do the difference, in my opinion.

What do you think?

J

**Comment by JamesDAdams** [comment] 2021-01-04 15:41
> I tried in the past to convince markus (sonarr side) to implement a "simple" way to easly hande all these situations, because all of these are by foreign languages.
> Sonarr/Radarr, in generall all of them are English based.
> See my old request here on sonarr side
> [Sonarr/Sonarr#2779](https://github.com/Sonarr/Sonarr/issues/2779)
> Here on Jackett side
> [Jackett/Jackett#2743](https://github.com/Jackett/Jackett/issues/2743)
> My idea is pretty simple, during a search request via Jackett, radarr/sonarr and so .. specify the selected language, so on Jackett side there must be a substitution table to handle all situations, special characters, apostrophe, for any languages.
> In this way, even the indexer code will be more simple, all equal without strange substitutions, because the're 2 issue, languages and the people that make release :D) most of the time they don't respect standard and Radarr/Sonarr can't find the release, but a table of substitution can do the difference, in my opinion.
> 
> What do you think?
> 
> J

I don't understand sorry :(
and personally for language i use any.

**Comment by awkimball** [comment] 2021-01-05 20:54
Since Radarr (in my case) already appears to be issuing additional search requests to Jackett for movies with non-original language titles, wouldn't an easy solution be to issue search requests both with and without an apostrophe? 

Seems like searching both _with_ and _without_ the apostrophe would cover all possible cases, at the cost of an additional search request to the indexer.

In my case, I am trying to download `Kiki's Delivery Service` but since Radarr asks Jackett for `Kikis Delivery Service` instead, I get significantly fewer results from a number of indexers

**Comment by JamesDAdams** [comment] 2021-01-06 08:30
> Since Radarr (in my case) already appears to be issuing additional search requests to Jackett for movies with non-original language titles, wouldn't an easy solution be to issue search requests both _with_ and _without_ an apostrophe?
> 
> Seems like searching both with and without the apostrophe would cover all possible cases, at the cost of an additional search request to the indexer.
> 
> For my use case this would be preferable, as some indexers return different results with and without the apostrophe and since I don't want to change a setting on a case-by-case basis, I would like Radarr to to receive all potential results with and without apostrophes.
> 
> For some context: I am trying to download "Kiki's Delivery Service" but since Radarr issues search requests to Jackett for
> and
> (the utf-8 representation of the japanese kanji name)
> instead, I get significantly fewer results from a number of indexers.`Kikis Delivery Service 1989``é­�å¥³ã�®å®�æ�¥ä¾¿ 1989`

Yes Radarr does it for me too he sends requests with the names of the films in French and English and yes it would be a good idea if he also sends requests with apostrophe, with space and empty

**Comment by Jorman** [comment] 2021-01-06 14:33
@JamesDAdams 
the apostrophe is only the tip of iceberg, personally I don't think that the apostrophe deserves such a big modification, I mean, is just a substitution inside code, just replace it with space instead replace it with nothing.
I remember this problem in past, sonarr or radarr side.
Maybe the develop teams think that this problem is a lower one, so don't work on it in the short time.

A little OT for you
I know that is a side problem but for what I think, the main problem are indexers and releasers. A better way to handle different languages is needed.
I don't know if you have ever been taking a look at some indexer in jackett side, every one has different substitutions, for example in one forum S01 became Temporada 1 or Stagione 1, just because releasers don't respect the "standard", so for me is wrong try to add all possible combination inside sonarr or radarr, is much simpler to leave the final user to choose. Sonarr for example will always search for S01 so, better handle this on jackett side. The same can be applied to apostrophe on radarr side, for example radarr start a search with apostrophe and on jackett side the user can set a replacing table and decide to replace or not.

**Comment by JamesDAdams** [comment] 2021-01-06 15:56
yes as you said for radar developers it is not an important subject while I consider it to be super important and it should be in their priority

**Comment by awkimball** [comment] 2021-01-06 16:05
I haven’t contributed to Radarr before but took a quick look and it I don’t
think it should take too long to add a universal Indexer option dropdown
that changes how we handle certain special characters in search title
queries.

[here](
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs)
is the relevant base class for Search Criteria which includes all titles
that will be searched for and the code that sanitizes them of special
characters (including apostrophes)

I’ll see what I can do after work today if I have some time

*sent from mobile*

On Jan 6, 2021, at 09:56, JamesAdams <notifications@github.com> wrote:

﻿

yes as you said for radar developers it is not an important subject while I
consider it to be super important and it should be in their priority

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Radarr/Radarr/issues/4502#issuecomment-755383826>, or
unsubscribe

**Comment by JamesDAdams** [comment] 2021-01-06 16:08
> I haven’t contributed to Radarr before but took a quick look and it I don’t think it should take too long to add a universal Indexer option dropdown that changes how we handle certain special characters in search title queries. [here](https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs) is the relevant base class for Search Criteria which includes all titles that will be searched for and the code that sanitizes them of special characters (including apostrophes) I’ll see what I can do after work today if I have some time

you are a love ! I would have liked to do it but I dev in Angular, Java but not in C :(

**Comment by Jorman** [comment] 2021-01-06 18:57
@awkimball 
Correct me if I'm wrong, but this's the "problem"
https://github.com/Radarr/Radarr/blob/99b75a3089d0f235a8bcc88caa933e0e5021eb45/src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs#L31
Just replace it with space so became
cleanTitle = SpecialCharacter.Replace(cleanTitle, " ");

Am I right?

**Comment by awkimball** [comment] 2021-01-06 18:59
@Jorman Indeed, although that would result a blanket change to Radarr behavior. 

In order to maintain current behavior I was planning on adding an option to control the special character handling from the frontend as well

**Comment by JamesDAdams** [comment] 2021-01-06 19:05
> @Jorman Indeed, although that would result a blanket change to Radarr behavior.
> 
> In order to maintain current behavior I was planning on adding an option to control the special character handling from the frontend as well. Maybe a dropdown, with the options 'Remove all special characters', 'Replace with spaces', 'Send search query with and without special characters', etc
> 
> I still maintain that at least for me, the preferable behavior would be to send multiple search queries, both with and without the apostrophe. This in my limited testing returns the greatest overall number of valid results. That being said, I am using Jackett (which is correctly handling special characters itself) via torznab so I don't want to generalize and say that this behavior is best for everyone.

Yes like the mockup that I did rather it would be perfect to be able to do it for each tracker

look here https://github.com/Radarr/Radarr/issues/5685

**Comment by Jorman** [comment] 2021-01-06 19:11
In that way you've to handle a lot of possibilities.
The good is that in every indexer you can "select" the bad is that in every indexer you've to make tests before select. Every single indexer have different approach with special chars, some website can't find any with special, any others do.
Without taking into account Jackett indexer code because also on Jackett side most indexers are "custom-made"
I'm sure this's a good starting point, but I think that a simple space replacement remain, for now, the best solution, this can potentially generate too many mistakes on the indexer side, but maybe I'm wrong

**Comment by awkimball** [comment] 2021-01-06 19:14
Ultimately, the question that needs to be answered is: Should Radarr be broadly, and by default, removing "special" characters to account for some indexers that do not handle them, when other indexers provide better results when using the full, literal title, including apostrophes. I'd be curious to see how many indexers really fail to handle apostrophes in particular  since they are so ubiquitous in many languages.

Either way, I agree with you, simple space replacement would be better than the current behavior of removing the character altogether.

**Comment by ta264** [comment] 2021-01-06 20:22
This is tailored towards usenet, where in general special characters should be removed.

A PR to replace special with space would not get merged.  We're also reluctant to add an option (you shouldn't need to rely on users to select the right option for it to work).  We're still trying to figure out the best approach.

**Comment by JamesDAdams** [comment] 2021-01-06 20:31
> This is tailored towards usenet, where in general special characters should be removed.
> 
> A PR to replace special with space would not get merged. We're also reluctant to add an option (you shouldn't need to rely on users to select the right option for it to work). We're still trying to figure out the best approach.

yes ba the best approach you have not found it and I do not see where the problem is to add an option to choose for each tracker to replace the apostrophe by a blank or a space

**Comment by awkimball** [comment] 2021-01-06 20:39
@ta264 Gotcha. Just for argument’s sake, why is adding this option more of a risk to users than any of the many other options that control search behavior? 

Either way, it seems like we/me/whoever could derive the SearchCriteria class specifically for Torznab and have this derived class not modify the title at all. Is there a problem with just searching for the actual, literal title (including apostrophes) when using Torznab?

**Comment by Jorman** [comment] 2021-01-06 21:20
@ta264 
What if radarr redirects everything to jackett or external indexer aggregators? (only when external indexer is used)
Maybe rather than searching for a movie like "A Dogs Way Home (2019)" Radarr could search for "A Dog's Way Home (2019)" | "language profile", when the search goes through an external aggregator like Jackett and then oriented towards the torrent network.
In this way, it will be Jackett (suitably modified) to make all the replacements of the case, through preset tables and possibly customizable, with all the special characters, not only the apostrophe but also umlauts, French letters and more ...

Is so bad this approach?

J

**Comment by almottier** [comment] 2021-01-08 09:29
I really hope you will find a solution for this soon....... 🙏

**Comment by JamesDAdams** [comment] 2021-01-12 22:29
News ?

**Comment by austinwbest** [comment] 2021-01-12 23:36
> News ?

Same as it was previously.

**Comment by bakerboy448** [comment] 2021-01-12 23:40
When there is an update to be posted then either an update will be posted here; or a Pull Request will be linked to this GitHub Issue.

Until one of those occurs, or unless you have something beneficial productive to comment...kindly don't comment and thus don't spam everyone's inboxes....that's how threads get locked.

**Comment by JamesDAdams** [comment] 2021-01-13 09:02
> I haven’t contributed to Radarr before but took a quick look and it I don’t think it should take too long to add a universal Indexer option dropdown that changes how we handle certain special characters in search title queries. here: https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs is the relevant base class for Search Criteria which includes all titles that will be searched for and the code that sanitizes them of special characters (including apostrophes) I’ll see what I can do after work today if I have some time

Hi, have you tried changing the code ?

**Comment by awkimball** [comment] 2021-01-13 15:12
@JamesDAdams No, as @ta264 said above, the Radarr team is apparently apprehensive about adding an option so I won’t be spending any time on it.

**Comment by JamesDAdams** [comment] 2021-01-13 16:13
> @JamesDAdams No, as @ta264 said above, the Radarr team is not interested in the specific option I was referring to so I won’t be spending any time on it.
> 
> That being said, I still don’t understand why this usenet specific title sanitization is happening globally. Shouldn’t Radarr do title sanitization _only_ for usenet, if usenet is the underlying reason for it in the first place?
> 
> I am happy to provide examples but across a number of languages I get better torznab results when searching _with_ apostrophes.

Let's go create a fork and if they don't want to add it...

**Comment by awkimball** [comment] 2021-01-13 16:22
@JamesDAdams feel free to go do that, but I am trying to converse with the Radarr contributors in this thread and get some clarification on the intended and preferred behavior of Radarr. 

Please don’t continue spamming this thread or it will get locked and we won’t be able to continue any actual discussion on the topic of title search sanitization.

**Comment by bakerboy448** [comment] 2021-01-20 20:17
https://github.com/Jackett/Jackett/pull/9719

Sounds like it would mitigate this problem

**Comment by Zazou89** [comment] 2021-01-22 01:22
I have this issue with `Les Aventures extraordinaires d'Adèle Blanc-Sec` (French movie)

Returns 8 results on Jacketton YGGtorrent  but only one in Radarr. After logging viewed by @bakerboy448 and @Qstick on discord, apostrophe is removed between d and A.  

`&q=Les%20Aventures%20extraordinaires%20dAdele%20Blanc%20Sec 2010`

**Comment by JamesDAdams** [comment] 2021-01-31 16:35
The problème get from radarr not Jackett

https://github.com/Jackett/Jackett/issues/6413#issuecomment-770374106

**Comment by bakerboy448** [comment] 2021-01-31 16:58
@JamesDAdams 
1) That comment is for Sonarr not Radarr
2) the PR I mentioned earlier that would mitigate it on Jackett's side is still open (https://github.com/Jackett/Jackett/pull/9719)
3)  this is a known issue, you constantly spamming github is not going to result in anyone working on it faster...it typically has the opposite effect actually

**Comment by JamesDAdams** [comment] 2021-03-08 23:35
...

**Comment by asurare** [comment] 2021-07-21 09:02
@badwulfy 
Is there already a PR open to treat this issue? If not, am I welcome to do so?

**Comment by ta264** [comment] 2021-07-21 09:04
Contributions to fix this are welcome. But it's more complicated than not removing the apostrophe - that would bread Usenet indexers in general. It needs a more nuanced approach. If it was an easy fix we would have done it already...

**Comment by asurare** [comment] 2021-07-21 09:12
Yup, I did read the above comments ^^
But it had been open for many months now, and I will have some free time to look into this. I was just wondering if anyone tried anything yet (in relation to this related Jackett PR has also changed :https://github.com/Jackett/Jackett/pull/11889)

**Comment by ta264** [comment] 2021-07-21 09:30
You might have more joy working with prowlarr instead of jackett, since prowlarr is one of our projects

**Comment by almottier** [comment] 2021-09-01 22:12
@ta264 I just tried with Prowlarr, it is not working. 

Here is the request log for the movie `L'An 01`, it has been renamed to `LAn 01`

```
2021-09-01 23:51:24.3|Info|NzbSearchService|Searching indexers: [YGGtorrent] for {Term: LAn 01 1973, Offset: 0, Limit: 100, Categories: [2000]}
2021-09-01 23:51:24.3|Info|Cardigann|Adding request: https://www3.yggtorrent.nz/engine/search?category=2145&name=%22LAn%22%20%2201%22%20%221973%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
```

**Comment by Mrpink200** [comment] 2021-09-09 12:19
i was wondering if the issue exists on sonarr and lidarr. gonna check

**Comment by Mrpink200** [comment] 2021-09-09 12:33
[Lidarr.trace.txt](https://github.com/Radarr/Radarr/files/7136462/Lidarr.trace.txt) if it can help

**Comment by Seluj78** [comment] 2021-11-10 20:31
Same problem with those movies (same error with `#` also.)

```
Je.suis.La.2019.FRENCH.1080p.WEB.H264-EXTREME.mkv - https://www.themoviedb.org/movie/605734-jesuisla

Rock_n_Roll.x265.mkv - https://www.themoviedb.org/movie/382589-rock-n-roll

Soeurs.D.Armes.2019.MULTi.1080p.BluRay.DTS.x264-UTT/Soeurs.D.Armes.2019.MULTi.1080p.BluRay.DTS.x264-UTT.mkv - https://www.themoviedb.org/movie/618326-soeurs-d-armes
```

**Comment by bakerboy448** [comment] 2021-11-28 20:08
This is solved by the definition for the indexer indicating it supports raw search - which will then allow the proper search to be used.

This has been added to Prowlarr for YGGTorrents

**Closed** 2021-11-28 20:10 UTC
Labels: Type: Bug, Area: Indexers, Type: External Bug

**Comment by Seluj78** [comment] 2021-11-28 20:11
Amazing thank you so much ! 😀

**Comment by asurare** [comment] 2021-11-28 21:03
Ty for this amazing work ! :D

**Comment by bakerboy448** [comment] 2022-07-29 02:40
jackett will have RawSearch support shortly
https://github.com/Jackett/Jackett/pull/13409
