### ISSUE TITLE
[FEATURE REQUEST] - Update film paths when sequels become known

### ISSUE THREAD

**Issue by XcOM987** [Radarr/Radarr#10132] opened 2024-07-01 13:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I add a film series, and a film get's announced, it gets added to radarr, all good so far, but I am having issues where it will download the film, but the folder will be "Untitled FILMSERIES sequel (year)"

For example the new gladiator film was showing as "Untitled gladiator sequel (2024)"

### Describe the solution you'd like

Could there be a feature add where radarr will correct the name of the folders once the film title is officially announced/released?

### Describe alternatives you've considered

Not adding films until they are released but that negates a feature of Radarr I use

### Anything else?

Latest Radarr used:
Version
5.7.0.8882
.NET
Yes (6.0.29)
Database
Sqlite 3.37.2
Database Migration
237
AppData Directory
/var/lib/radarr
Startup Directory
/opt/Radarr

**Comment by bakerboy448** [comment] 2024-07-01 15:49
Duplicate of https://github.com/Radarr/Radarr/issues/8854

**Closed by bakerboy448** 2024-07-01 15:49 UTC
Labels: Type: Feature Request, Status: Needs Triage
