### ISSUE TITLE
Update and test download clients for movies

### ISSUE THREAD

**Issue by galli-leo** [Radarr/Radarr#14] opened 2017-01-02 17:55 UTC
While nothing should be needed to change, testing is never a bad idea.

## Usenet
- [x] NZBGet
- [x] SABnzbd
- [ ] NZBVortex, fixed, needs testing.
- [ ] Pneumatic, fixed, needs testing.
- [ ] Blackhole, fixed, needs testing.

## Torrent
- [x] Deluge
- [x] qBittorrent
- [x] rTorrent
- [x] Transmission
- [ ] Hadouken
- [ ] Blackhole
- [x] uTorrent
- [ ] Vuze

**Comment by fedoranimus** [comment] 2017-01-04 20:56
#23 Fixed Nzbget

**Comment by AeonLucid** [comment] 2017-01-05 00:08
https://github.com/galli-leo/Radarr/pull/25 Confirmed to have fixed SABnzbd.

Others may be working too, haven't tested.

**Comment by onedr0p** [comment] 2017-01-06 20:41
reporting in that rtorrent isn't working.

**Comment by galli-leo** [comment] 2017-01-07 09:48
@onedr0p rTorrent should be working now.

**Comment by onedr0p** [comment] 2017-01-07 11:18
Sweet, I'll try it when the new release comes out and report back.

**Comment by jamma007** [comment] 2017-01-10 05:18
Transmission is not working.  Just tried it tonight

**Comment by onedr0p** [comment] 2017-01-10 22:58
added and tested Transmission

**Comment by killingit57** [comment] 2017-01-11 06:06
No success with Transmission. 

Message:
`The download client you are using is currently not configured to download movies. Please choose another one.: The method or operation is not implemented.`

Exception:
`System.NotImplementedException: The method or operation is not implemented.
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].AddFromMagnetLink (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String hash, System.String magnetLink) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:45 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteEpisode, System.String magnetUrl) [0x00048] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:299 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x000f1] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:110 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x000a3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:119 `

**Comment by onedr0p** [comment] 2017-01-11 06:11
I added and tested transmission, it will be in the next release.

**Comment by r1nzl3r9991** [comment] 2017-01-11 17:01
Any chance this release comes today?

**Comment by onedr0p** [comment] 2017-01-11 18:53
I believe so!

**Comment by killingit57** [comment] 2017-01-12 03:20
@onedr0p Confirming that Transmission is working on radarr.develop.0.2.0.88
Thank you!

**Comment by hotio** [comment] 2017-01-13 12:45
Torrent Blackhole is not working...
```
17-1-13 13:28:21.5|Trace|Http|Req: 752 [POST] /api/release
17-1-13 13:28:21.5|Debug|ReleaseModule|Couldn't find requested release in cache, cache timeout probably expired.
17-1-13 13:28:21.6|Trace|HttpClient|Req: [GET] http://jackett:9117/xxx.torrent
17-1-13 13:28:21.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-13 13:28:21.7|Trace|HttpClient|Res: [GET] http://jackett:9117/xxx.torrent: 200.OK (148 ms)
17-1-13 13:28:21.7|Debug|TorrentBlackhole|Downloading torrent for episode 'XXX' finished (14773 bytes from http://jackett:9117/xxx.torrent)
17-1-13 13:28:21.7|Debug|TorrentBlackhole|Torrent download failed, trying magnet. (The method or operation is not implemented.)
17-1-13 13:28:21.7|Info|DownloadService|Report sent to Blackhole. XXX
17-1-13 13:28:21.7|Trace|EventAggregator|Publishing MovieGrabbedEvent
17-1-13 13:28:21.7|Trace|EventAggregator|MovieGrabbedEvent -> HistoryService
17-1-13 13:28:21.8|Trace|EventAggregator|MovieGrabbedEvent <- HistoryService
17-1-13 13:28:21.8|Trace|EventAggregator|MovieGrabbedEvent -> PendingReleaseService
17-1-13 13:28:21.8|Trace|EventAggregator|MovieGrabbedEvent <- PendingReleaseService
17-1-13 13:28:21.8|Trace|Http|Res: 752 [POST] /api/release: 200.OK (232 ms)
17-1-13 13:28:21.8|Debug|Api|[POST] /api/release: 200.OK (232 ms)
```
The torrent file given by Jackett is received by Radarr, because it knows exactly how many bytes the file is (checked/compared the link/file manually), however the file is never dropped in the blackhole folder.

**Comment by onedr0p** [comment] 2017-01-13 13:30
Question: what is the purpose of torrent black hole anyways? Why not use a supported download client?

**Comment by hotio** [comment] 2017-01-13 13:43
Download client is not on the same machine as Radarr, download client option doesn't delete ONLY imported files, but also want's to remove from the download client.

Blackhole gives me the desired functionality, the part that Radarr has to execute is minimal, but my own scripts handle all the rest better to my taste than Radarr or CouchPotato do.

**Comment by onedr0p** [comment] 2017-01-13 14:07
Not sure if I'm understanding your first sentence correctly. For testing I set up radarr and my download client on separate machines. I added the movie to radarr, clicked download, radarr handled everything from there. It copied and renamed the movie afterwards to the correct path and kept it seeding in transmission. Are you saying you want to remove torrents after they finish? Sorry for not understanding.

**Comment by hotio** [comment] 2017-01-13 14:13
When deluge has finished downloading on PC1-deluge in puts the torrent in a folder OUT.
Every half hour my script on PC2-radarr checks for new torrents in folder OUT on PC1-deluge and downloads them.
It processes them and puts them in a folder FINISHED so that Radarr can do it's thing. Radarr puts them in the folder MOVIES, but leaves the copy in the folder FINISHED.

I want the files in FINISHED gone, Radarr doesn't have to worry about torrents in Deluge on PC1-deluge.

Makes sense?

**Comment by onedr0p** [comment] 2017-01-13 14:21
Ahh, I understand now. Maybe in the future you could use the custom notification 'custom script' to delete the ones in the FINISHED folder? Sadly that doesn't work with radarr yet though.

**Comment by hotio** [comment] 2017-01-13 14:22
And what is wrong with fixing the Blackhole client?

**Comment by onedr0p** [comment] 2017-01-13 14:23
Nothing is wrong, just curious because I saw Sonarr will remove blackhole in v3.

**Comment by hotio** [comment] 2017-01-13 14:25
Ah, I did not know that...Any link where I can readup on this?

**Comment by onedr0p** [comment] 2017-01-13 14:36
Damn, knew you were gonna ask me that. I saw @markus101 mention it somewhere.

**Comment by markus101** [comment] 2017-01-13 17:20
Blackhole is going to remain, we're just dropping Drone Factory from the UI, the functionality will still be available through the API and Blackhole will still be fully functional.

**Comment by onedr0p** [comment] 2017-01-13 17:20
My mistake, got the two confused. Thanks for clearing that up.

**Comment by suineg** [comment] 2017-01-24 11:16
The major benefit of blackhole is that Radarr is hands of and no mater what obscure client the user has they can take it from there. It's up to them to get it back into the proper area for it to be marked downloaded. I would assume this means less work on your end on entertaining support of systems that aren't very prevalent. 

I for one use it exclusively on Sonarr and it has done well for me for years.

**Comment by SJ50** [comment] 2017-02-03 06:35
any update on torrent blackhole support?
I am using rtorrent and it does not support queue, so I am using script to queue torrents and for this purpose blackhole method is required.

**Comment by danpowell88** [comment] 2017-02-04 09:28
Hadouken is not working 

> The download client you are using is currently not configured to download movies. Please choose another one.: The method or operation is not implemented.

> System.NotImplementedException: The method or operation is not implemented.
>    at NzbDrone.Core.Download.TorrentClientBase`1.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 49
>    at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteEpisode, String torrentUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 269
>    at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 125
>    at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119

**Comment by weirdcrap** [comment] 2017-02-04 17:15
I am also having the black hole issue. I was going to do some testing with it to see if I could change some things up more to my liking by using torrent black hole but I receive the same error as those above me.

**Comment by ashmandias** [comment] 2017-02-05 14:55
I'm just jumping in to say I was trying to use Blackhole, as well, and it is not working.

In my case, using the deluge downloader frequently craps out -- I have around 1k torrents in deluge at any one time, and the connection times out when trying to talk with the deluge webui. I thought that the blackhole would be a little more robust.

I also want to keep a copy of the .torrent files for some custom post-processing, and using a blackhole seems the easiest way to get that to work reliably.

**Comment by onedr0p** [comment] 2017-02-06 23:50
Let's handle new and fixing old ones in a new GH issue. Feel free to open a request for new additional clients or fixing existing ones.

**Closed by onedr0p** 2017-02-06 23:50 UTC
Labels: enhancement, priority:low

**Comment by ashmandias** [comment] 2017-02-07 00:01
Opened as https://github.com/Radarr/Radarr/issues/634

**Comment by onedr0p** [comment] 2017-02-07 00:38
@danpowell88 Hodoken should be working in the next update
