### ISSUE TITLE
The given key '1' was not present in the dictionary.

### ISSUE THREAD

**Issue by JohnShortland** [Radarr/Radarr#4396] opened 2020-05-06 09:53 UTC
**Describe the bug**
Error when loading Movies page or calendar saying "The given key '1' was not present in the dictionary." 2 sets of logs below, 1 from when the error shows and another from when deleting the profiles.

I have restored from backup and as a workaround, I'm creating a new profile called all and assigning that to all movies to avoid the "Qualities can only be used once" error when trying to edit existing profiles, I am assuming that 1 in the DB is the any profile and removing and recreating the others will be ok.

**To Reproduce**
1. Assign temp profile to all movies and lists
2. Remove default profiles to fix bad migration issue as per github issue
3. Recreate profiles
4. Wait

**Expected behavior**
All shows assigned the new profile would update to higher quality

**Screenshots**
http://imgbox.com/HuP3QJE7

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 / Docker 19.03.8, build afacb8b7f0
 - Mono Version: linuxserver/radarr:preview
 - Browser and Version: Google Chrome 81.0.4044.129
 - Version: Aphrodite

**Extra Info**
- Version: 3.0.0.2909
- Package Version: 3.0.0.2909-ls6 by linuxserver.io
- DB Migration: 172

**Debug Logs**
```
2020-5-6 02:04:59.6|Error|RadarrErrorPipeline|[POST /api/v3/qualityprofile]
2020-5-6 02:05:05.5|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/qualityprofile
2020-5-6 02:08:05.7|Error|RadarrErrorPipeline|[POST /api/v3/qualityprofile]
2020-5-6 02:08:05.7|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/qualityprofile
2020-5-6 02:09:36.2|Error|RadarrErrorPipeline|[DELETE /api/v3/qualityprofile/6]
2020-5-6 02:09:36.2|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/qualityprofile/6
2020-5-6 02:11:33.7|Error|RadarrErrorPipeline|[DELETE /api/v3/qualityprofile/5]
2020-5-6 02:11:34.9|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/qualityprofile/5
2020-5-6 02:14:56.1|Error|RadarrErrorPipeline|[POST /api/v3/qualityprofile]
2020-5-6 02:14:57.7|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/qualityprofile
```
```
2020-5-6 10:51:29.2|Error|RootFolderService|Unable to get free space and unmapped folders for root folder /concerts/

[v3.0.0.2908] System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass5_0.<All>b__1(Movie movie, AlternativeTitle altTitle, MovieFile file) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 97
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1442
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1402
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1278
   at NzbDrone.Core.Movies.MovieRepository.All() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 95
   at NzbDrone.Core.RootFolders.RootFolderService.GetUnmappedFolders(String path) in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 136
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 195
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2020-5-6 10:51:30.2|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/movie

[v3.0.0.2908] System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass5_0.<All>b__1(Movie movie, AlternativeTitle altTitle, MovieFile file) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 97
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1442
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1402
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1278
   at NzbDrone.Core.Movies.MovieRepository.All() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 95
   at NzbDrone.Core.Movies.MovieService.GetAllMovies() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieService.cs:line 289
   at Radarr.Api.V3.Movies.MovieModule.AllMovie() in d:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 99
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__33_0(Object options) in d:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 136
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

2020-5-6 10:51:30.3|Error|RootFolderService|Unable to get free space and unmapped folders for root folder /stand_up/

[v3.0.0.2908] System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass5_0.<All>b__1(Movie movie, AlternativeTitle altTitle, MovieFile file) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 97
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1442
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1402
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1278
   at NzbDrone.Core.Movies.MovieRepository.All() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 95
   at NzbDrone.Core.RootFolders.RootFolderService.GetUnmappedFolders(String path) in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 136
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 195
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2020-5-6 10:51:30.4|Error|RootFolderService|Unable to get free space and unmapped folders for root folder /kids_movies/

[v3.0.0.2908] System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass5_0.<All>b__1(Movie movie, AlternativeTitle altTitle, MovieFile file) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 97
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1442
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1402
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1278
   at NzbDrone.Core.Movies.MovieRepository.All() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 95
   at NzbDrone.Core.RootFolders.RootFolderService.GetUnmappedFolders(String path) in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 136
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 195
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2020-5-6 10:51:30.4|Error|RootFolderService|Unable to get free space and unmapped folders for root folder /movies/

[v3.0.0.2908] System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass5_0.<All>b__1(Movie movie, AlternativeTitle altTitle, MovieFile file) in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 97
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1442
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1402
   at Dapper.SqlMapper.Query[TFirst,TSecond,TThird,TReturn](IDbConnection cnn, String sql, Func`4 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1278
   at NzbDrone.Core.Movies.MovieRepository.All() in d:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 95
   at NzbDrone.Core.RootFolders.RootFolderService.GetUnmappedFolders(String path) in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 136
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in d:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 195
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by houdini3009** [comment] 2020-07-05 19:44
I just tried upgrading from Radarr v2 (develop branch) to v3 (aprodite branch) and when I load my Radarr library, this error message is all I see. The "Update All" button is greyed out and unavailable.

> Remove default profiles to fix bad migration issue as per github issue

@JohnShortland Can you point me to this issue? ^^ I'm worried how corrupted my database may have become and how to recover it.

**Comment by Qstick** [comment] 2020-07-06 03:24
I can't reproduce this, the db's that I have seen with this problem had the same issue in their v0.2 db which was carried over. One item in the db was pointing to an old profile.

**Comment by Sebclem** [comment] 2020-07-13 15:08
I have the same issue, fixed by using the `Movie Editor` to change the profile of all my movies

**Closed** 2020-08-24 01:51 UTC
Labels: aphrodite, bug
