### ISSUE TITLE
[BUG] Latest nightly: Error|DownloadDecisionMaker|Couldn't process release | Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#1274] opened 2017-03-27 13:23 UTC
Latest nightly.

Searching for releases does not work eg every search is no results found. ( for any movie )
![No Result Found](https://puu.sh/v04Zv/f6e9cadbb1.png)

> 17-3-27 15:19:07.6|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:07.7|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:07.8|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:07.9|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:07.9|Info|DiskScanService|Scanning disk for Freezer
> 17-3-27 15:19:08.0|Info|DiskScanService|Completed scanning disk for Freezer
> 17-3-27 15:19:08.0|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.2|Info|RefreshMovieService|Updating Info for Frequency
> 17-3-27 15:19:08.2|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.2|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.3|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.4|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.4|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.4|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.4|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.4|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.4|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.5|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.5|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.5|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:08.7|Info|DiskScanService|Scanning disk for Frequency
> 17-3-27 15:19:08.9|Info|DiskScanService|Completed scanning disk for Frequency
> 17-3-27 15:19:09.0|Info|RefreshMovieService|Updating Info for Frida
> 17-3-27 15:19:09.0|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:09.4|Info|DiskScanService|Scanning disk for Frida
> 17-3-27 15:19:09.5|Info|DiskScanService|Completed scanning disk for Frida
> 17-3-27 15:19:09.6|Info|RefreshMovieService|Updating Info for Friday the 13th
> 17-3-27 15:19:09.7|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:09.7|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:09.7|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:09.7|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:09.7|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:09.8|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:10.1|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0 
> 
> 17-3-27 15:19:10.1|Error|DownloadDecisionMaker|Couldn't process release.
> 
> [v0.2.0.564] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Parser.ParsingService.GetMovie (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171ffd0 + 0x0056b> in <filename unknown>:0 
>   at NzbDrone.Core.Parser.ParsingService.Map (NzbDrone.Core.Parser.Model.ParsedMovieInfo parsedMovieInfo, System.String imdbId, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) <0x4171fec0 + 0x00093> in <filename unknown>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetMovieDecisions>d__6.MoveNext () <0x417b9920 + 0x0050c> in <filename unknown>:0

**Comment by galli-leo** [comment] 2017-03-27 13:38
What movie is this?

**Comment by Rhainland** [comment] 2017-03-27 13:51
Seems to be a duplicate of;

https://github.com/Radarr/Radarr/issues/1267
and
https://github.com/Radarr/Radarr/issues/1271

Example move @galli-leo 
John Wick: Chapter 2

But it happens with quite a lot of movies actually

**Comment by galli-leo** [comment] 2017-03-27 15:07
Fixed in latest nightly (should be up in a few minutes).

**Closed by galli-leo** 2017-03-27 15:07 UTC
