### ISSUE TITLE
Slow loading main page with large library

### ISSUE THREAD

**Issue by mikelagase** [Radarr/Radarr#805] opened 2017-02-19 16:15 UTC
I imported my movie library which is close to 3,000 movies and had to do it manually as Bulk import did not work for me. After loading all of the movies when I bring up the main page it hangs for almost a minute before I can do anything. I've tried various browsers all with the same issue and was wondering if there will be some performance improvements coming for larger libraries when attempting to pull up the list of movies in the library. It is not the best experience as couch potato did not have this issue pulling up my library as it looks like it paged the movies in rather then trying to load them all at the same time and Radarr tries to pull up the entire list all at one time. 

I don't believe it is anything I am doing and are looking for information if this experience will be improved in the future. 

**Radarr Version:**
0.2.0.368

**Comment by galli-leo** [comment] 2017-02-19 18:49
This is kinda a duplicate of #617. You can always filter only missing movies, this will help a lot when loading the page.

**Closed by galli-leo** 2017-02-19 18:49 UTC

**Comment by mikelagase** [comment] 2017-02-20 14:24
Well, trying to pull up the page on a mobile phone just locks it up, I cannot switch to on the wanted list so it makes it completely unusable on an Android phone. I've tried a couple of times and cannot get the page to load to switch the filters. It shows the entire list but I cannot select anything on the page which is a bummer.

**Comment by onedr0p** [comment] 2017-02-20 15:24
The same thing happens with Sonarr, for me that takes a good 10 seconds to get working on mobile. There's not much we can do besides creating a new UI which we are thinking about.
