### ISSUE TITLE
Unable to determine if file is a sample  /opt/Radarr/ffprobe

### ISSUE THREAD

**Issue by docfactory37** [Radarr/Radarr#7182] opened 2022-04-04 07:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i have updated to the latest stage version and now i want auto import new movies.

see logs below.

```
2022-04-04 07:11:46.2|Error|VideoFileInfoReader|Unable to parse media info from file: /downloads/completed/radarr-movie/The Hobbit The Desolation Of Smaug (2013) [2160p] [4K] [BluRay] [5.1] [YTS.MX]/The.Hobbit.The.Desolation.Of.Smaug.2013.2160p.4K.BluRay.x265.10bit.AAC5.1-[YTS.MX].mkv

[v4.0.5.5981] System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/opt/Radarr/ffprobe' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Instances.Instance.Start()
   at Instances.Instance.BlockUntilFinished()
   at FFMpegCore.Helpers.FFProbeHelper.VerifyFFProbeExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFProbe.PrepareInstance(String arguments, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.PrepareStreamAnalysisInstance(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 62


2022-04-04 07:11:46.2|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2022-04-04 07:11:46.2|Error|VideoFileInfoReader|Unable to parse media info from file: /downloads/completed/radarr-movie/The Hobbit The Desolation Of Smaug (2013) [2160p] [4K] [BluRay] [5.1] [YTS.MX]/The.Hobbit.The.Desolation.Of.Smaug.2013.2160p.4K.BluRay.x265.10bit.AAC5.1-[YTS.MX].mkv

[v4.0.5.5981] System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/opt/Radarr/ffprobe' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Instances.Instance.Start()
   at Instances.Instance.BlockUntilFinished()
   at FFMpegCore.Helpers.FFProbeHelper.VerifyFFProbeExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFProbe.PrepareInstance(String arguments, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.PrepareStreamAnalysisInstance(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 62
```

if i manually import the movies its fine not sure if this is a bug or something on my side, just thought i would advise

### Expected Behavior

complete auto import

### Steps To Reproduce

download a moves and wait till download has completed, then check logs and you will see it in the logs

### Environment

```markdown
- OS: Docker
- Radarr: latest stage
- Docker Install: yes 
- Using Reverse Proxy: yes
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

```
2022-04-04 07:11:46.2|Error|VideoFileInfoReader|Unable to parse media info from file: /downloads/completed/radarr-movie/The Hobbit The Desolation Of Smaug (2013) [2160p] [4K] [BluRay] [5.1] [YTS.MX]/The.Hobbit.The.Desolation.Of.Smaug.2013.2160p.4K.BluRay.x265.10bit.AAC5.1-[YTS.MX].mkv

[v4.0.5.5981] System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/opt/Radarr/ffprobe' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Instances.Instance.Start()
   at Instances.Instance.BlockUntilFinished()
   at FFMpegCore.Helpers.FFProbeHelper.VerifyFFProbeExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFProbe.PrepareInstance(String arguments, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.PrepareStreamAnalysisInstance(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 62


2022-04-04 07:11:46.2|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2022-04-04 07:11:46.2|Error|VideoFileInfoReader|Unable to parse media info from file: /downloads/completed/radarr-movie/The Hobbit The Desolation Of Smaug (2013) [2160p] [4K] [BluRay] [5.1] [YTS.MX]/The.Hobbit.The.Desolation.Of.Smaug.2013.2160p.4K.BluRay.x265.10bit.AAC5.1-[YTS.MX].mkv

[v4.0.5.5981] System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/opt/Radarr/ffprobe' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Instances.Instance.Start()
   at Instances.Instance.BlockUntilFinished()
   at FFMpegCore.Helpers.FFProbeHelper.VerifyFFProbeExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFProbe.PrepareInstance(String arguments, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.PrepareStreamAnalysisInstance(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 62
```

[AB#2905](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2905)

**Comment by bakerboy448** [comment] 2022-04-04 07:22
`stage` is not a version nor a branch. Who's container?

Seems like perhaps your container maintainer has a broken container or something is screwy with your docker?

No other reports of this.

**Comment by docfactory37** [comment] 2022-04-04 07:26
I'm just trying to work out the issue and have not seen any reports of this issue as to why I reported it if it not an application issue that's fine will continue to look into the issue

**Comment by ta264** [comment] 2022-04-04 08:07
Looks like ffprobe isn't set as executable inside the container.

Hotio and Linuxserver are our recommend images.

**Comment by ta264** [comment] 2022-04-04 08:09
I'm going to close this as a support issue, I'm pretty certain it's not a bug with radarr.

If you need more help in getting it sorted please use the discord channel.

**Closed** 2022-04-04 08:10 UTC
Labels: Type: Support
