### ISSUE TITLE
Test all indexers with one click (Test All)

### ISSUE THREAD

**Issue by mwodzynski** [Radarr/Radarr#3549] opened 2019-06-03 19:15 UTC
From time to time the indexers are unavailable due to failures. It is caused because of my internet connection, so once I fix it I have to retest every indexer separately in order for Radarr to start using them again.

It would be very helpful to have the ability to test all indexers with one click. This feature is available in Sonarr.  

![Screenshot (9)_LI](https://user-images.githubusercontent.com/34895306/58827975-f5500300-8609-11e9-9eb8-0e1233b76890.jpg)

**Comment by Qstick** [comment] 2019-06-06 22:35
Dupe of #3275

**Closed by Qstick** 2019-06-06 22:35 UTC
Labels: feature_request
