### ISSUE TITLE
Cannot change root folder in movie editor

### ISSUE THREAD

**Issue by DaveAlton** [Radarr/Radarr#3348] opened 2019-02-03 00:34 UTC
**Description:**

1) Go to movies
2) Open movie editor
3) Check off any movie
4) Select a different root folder at the bottom of the screen
5) Press save

Expected: Changes root folder of each selected movie
Reality: Does not change any root folder.

**Radarr Version:**

0.2.0.1293

MacOS 10.11.6

**Comment by DaveAlton** [comment] 2019-02-03 00:40
I actually can't change any folder. When going to an individual movie's settings, I can't even manually change the folder. I press save, but it just spins for a while and then stops spinning, not even dismissing the editor box.

**Comment by DaveAlton** [comment] 2019-02-03 00:45
I've downgraded Radarr to v0.2.0.1217, and it works in that version

**Comment by fryfrog** [comment] 2019-02-18 01:50
Can you try in an incognito window on the newest version? I don't change root folders very often, but I've never had any issues w/ it.

**Comment by Qstick** [comment] 2019-02-24 20:23
I can't reproduce this either, seems to work fine for me. Closing unless you can provide some logs showing errors.

**Closed by Qstick** 2019-02-24 20:23 UTC
