### ISSUE TITLE
Some movies imported from Trakt lists added with blank title

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#3957] opened 2019-12-17 09:08 UTC
**Describe the bug**
Some movies imported from Trakt lists have blank titles. 

**To Reproduce**
1. delete all movies
2. automated RSS Sync starts
3. titles are blank for some movies

**Expected behavior**
Proper titles

**Screenshots**
![image](https://user-images.githubusercontent.com/31339007/70980514-cb1de880-20f6-11ea-9172-9d7bdaf09549.png)
Better but still missing some after downgrading to 0.2.0.1358 then upgrading to the latest version
![image](https://user-images.githubusercontent.com/31339007/70986775-e80be900-2101-11ea-81eb-ec0542197f12.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 0.2.0.1450

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/3972360/radarr.txt)

**Comment by Hex-99** [comment] 2019-12-17 09:33
Looks like this is an issue with Refresh Movies Tasks. Assuming this is an API problem and *not* Radarr.

Sample from log showing the result from adding a new movie (note the blanks returned from the API call)

19-12-17 08:21:24.8|Info|MovieService|Adding Movie [Black Widow (2020)][, 497698] Path: [F:\Potato\Black Widow (2020)]
19-12-17 08:21:24.8|Debug|Api|[POST] /api/movie: 201.Created (51 ms)
19-12-17 08:21:24.8|Info|RefreshMovieService|Updating Info for Black Widow
19-12-17 08:21:26.2|Debug|RefreshMovieService|Finished movie refresh for 
19-12-17 08:21:26.2|Info|DiskScanService|Scanning disk for

**Comment by pven** [comment] 2019-12-17 09:40
Sounds a bit like my issue: #3958

**Comment by Qstick** [comment] 2019-12-17 14:12
Dupe of #3958, same root cause

**Closed by Qstick** 2019-12-17 14:12 UTC
Labels: bug
