### ISSUE TITLE
Multiple variants of the same movie

### ISSUE THREAD

**Issue by BacchusFLT** [Radarr/Radarr#5791] opened 2021-01-20 13:50 UTC
(I have searched for language in the other issues but felt they were not really addressing  the same thing)

Having another mother tongue than English, several of the movies I have collected are present in multiple versions. One with Swedish audio and one in English. One can of course argue that ripping should have been done with both audio options in the output container, but this has not been the case and it can't be mitigated now, several years after ditching the original DVDs.

The same issue is also valid for 2D/3D where there are legit reasons for maintaining several versions of the same file, without claiming either is a dupe. They are permutations of the same, but with unique characteristics that have a certain unique value.

I haven't used the program long enough to have any concrete suggestion on how a fix would manifest, but something like upon import - when detecting the movie already existing being given the option to select how it differs from the other and why it should be added. (There are naturally knock-on effects of this if you want to seach for a better version of a file, then the criteria might not be searchable but I leave to the experts to dwell over that).

**Comment by bakerboy448** [comment] 2021-01-20 13:53
Duplicate of #1910

**Closed by bakerboy448** 2021-01-20 13:53 UTC
Labels: feature request

**Comment by BacchusFLT** [comment] 2021-01-20 15:34
It's indeed correct that the intent is multiple movie files with different attributes for the same movie entry, whereas the #1910 is targeting resolutions (which is a dimension readable from the media file), spoken language CAN also be that but not all of them have it properly implemented.

2D/3D is also something I am quite unsure if one can read from the media itself.

**Comment by austinwbest** [comment] 2021-01-20 16:20
The use case isn't relevant with what he linked. The purpose of linking that one was because to achieve what you want, that has to be done. There will be different factors for language VS quality, sure, but it isn't possible without the change from 1:1 to 1:many movie files. Basically this is just another use case of that goal.

**Comment by BacchusFLT** [comment] 2021-01-20 16:30
Den ons 20 jan. 2021 kl 17:20 skrev nitsua <notifications@github.com>:

> The use case isn't relevant with what he linked. The purpose of linking
> that one was because to achieve what you want, that has to be done. There
> will be different factors for language VS quality, sure, but it isn't
> possible without the change from 1:1 to 1:many movie files. Basically this
> is just another use case of that goal
>
Fair enough and thanks for the clarification. I'm fully aware this is free
software and that I can wish - not request, but thanks for listening to my
input and I will still use the program with the restrictions it has for me.

/Pontus
