### ISSUE TITLE
Movies showing as Missing - but files are there

### ISSUE THREAD

**Issue by Ltek** [Radarr/Radarr#2311] opened 2017-12-04 05:33 UTC
Just imported 173 movies and Radarr says 26 are missing when the file is in the folder. Some are MP4, some are MKV. I cant find any pattern to why these specific ones show missing. 

All folders are structured the same where the movie file is in the root of the movie's folder, with folder and the movie are named the same

thx for the help!

**Comment by galli-leo** [comment] 2017-12-04 08:08
What are the folders and files named like?

**Comment by matmuilwijk** [comment] 2017-12-04 09:19
Had the same issue a few times in Chrome. Removing cookies and clearing Cache worked for me... Same fix works for the filter-issue btw...

**Comment by Ltek** [comment] 2017-12-04 16:17
@galli-leo 
I have 2 issues, maybe related... it imported the movies under 
/volume1/kids movies/  -- except for the 26 movies I note.

All folders & files have the same structure and naming conventions...
example:
folder = Avatar (2009)
file = Avatar (2009) or Avatar  *extension are always mkv or mp4

maybe related...
with /volume1/movies/   -- Radarr doesn't "see" any movies and throws his message...
"No movies found in folder /volume1/movies/. Have you already added all of them? "


As for the browser, I have used both Firefox and Edge - same result. And since I have never used or installed Radarr before last night, I cant see any possibility this is a cache issue.

**Comment by galli-leo** [comment] 2017-12-04 17:21
Not having a year in the movie file name might be a problem (for the missing movies). Also useful might be a trace log.

**Comment by Ltek** [comment] 2017-12-05 05:58
@galli-leo
trace log attached. Adding the year didnt help. There are other movies that scanned in fine which dont have the year on them. And, CouchPotato scans them all perfectly. In the Radarr UI is shows the Movie titles correctly, but says they are 'missing' ... makes no sense as the Folder Name and movie File name are the exact same.

thx for the help

[trace.txt](https://github.com/Radarr/Radarr/files/1529840/trace.txt)

**Comment by galli-leo** [comment] 2017-12-05 18:46
@Ltek Can you do an update library and then post a trace log?

**Comment by Ltek** [comment] 2017-12-07 02:08
@galli-leo   trace you requested is attached
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/1537552/radarr.trace.txt)

**Comment by darrenclimienewman** [comment] 2017-12-13 17:29
Hi,

I have recently started using Radarr running on my QNAP NAS, and decided to add my existing movies with the view to getting better copies of some over time.

I found the bulk import and added my movies directory. Initially it was missing loads of movies that i had, but after some research i realised the folders and files needed to have the same name and also the year, to try and ensure they get picked up correctly. So i used TinyMediaManager last night and got all of my 300 odd Movies and folders renamed with the year included, like this:

Folder:
share/Movies/Avatar (2009)
File:
share/Movies/Avatar (2009)/Avatar (2009).mkv

It picked up most of the movies, but it's missing about 46, and I've confirmed that the files are there and the folder and file match in naming convention and also with the year included. I'd like help to try and get this fixed?

On a separate note, and i dont know if this has contributed to it. I was trying some of the setting out, and i turned on the 'Create Folder for missing movies', and it added a folder for all the movies i haven't got yet. I then decided that i didnt want to have empty folders, so i started to delete them and turned OFF the setting. However, every time i deleted the empty movie folder, it reappeared!

Because initially on the first bulk import it didnt pick up most of my movies, it created a folder for almost all of them, leaving me with duplicated folders for most of my collection! After meeting around moving the files between the duplicate folders, i was able to delete the original folder, and leave me with one for each movie.

I them went through the renaming process as described above, and re-imported my collection. This is where i am now left with about 46 missing movies which i actually have.

What steps should i take now to try and fix this?

Thanks

**Comment by distributorofpain** [comment] 2017-12-27 20:29
Have the same issue but might have a possible solution.  I added one of my disks to test radarr and it seems even movie files in folders on local disk with "moviename (YYYY)" and "moviename (YYYY).mp4" show up as missing.  

IE: "F:\pv\Stiletto (2008)\Stiletto (2008).avi" shows as missing in the movie list, but when you bring up the movie edit window, it shows it there.

This occurred after adding 500+ movies.  I waited till morning and refreshed, no change.  I then cleared my chrome's cache, but no change.  I Then hit the update library function and waited an hour or so.  It didnt clear at that point, but when i hit the next button at the bottom, they all showed as downloaded instead of missing.  Navigating back and forth changed them all to downloaded.

Hitting update library didnt immediately fix the issue, i refreshed an hour or so later and thats when they switched to downloaded.

Might be fixed by ensuring that when imported and it sees the file, it immediately marks them as downloaded in the DB?

**Comment by raysv** [comment] 2018-01-07 22:47
Looks like a "sort" bug,  looks like default it sortet on status, when i sort them after any other coluum they shows as downloaded and not missing.

**Comment by galli-leo** [comment] 2018-02-07 14:54
Seems like the movie files are not imported. This could be due to a few reasons, for example reporting a runtime of 0. You might try a manual import to see whats wrong.

**Closed by galli-leo** 2018-02-07 14:54 UTC

**Comment by externl** [comment] 2018-02-15 17:04
I'm also seeing this. Incognito window if fine, my default window shows missing.

**Comment by externl** [comment] 2018-02-15 17:05
Progress. When I sort by downloaded is when I see missing.

**Comment by galli-leo** [comment] 2018-02-15 17:08
@externl Known issue, probably won't be fixed until the new ui. Just don't sort by downloaded for now.

**Comment by externl** [comment] 2018-02-15 17:09
👍

**Comment by LongDono** [comment] 2018-03-18 15:53
Thanks, I was wondering why everything was listed as missing even though the summary at the bottom included they were all present.  I switched to Title sorting and it's fine now.

**Comment by marshalleq** [comment] 2020-01-06 00:03
The problem with this is it keeps searching for the missing ones, even though it knew they were there before.  At least that is what I'm seeing.  I'm new to this (came from CP) but am wondering if it just doesn't like Movies without folders, (I have a mix).
