### ISSUE TITLE
Download client selection parameters

### ISSUE THREAD

**Issue by dantebarba** [Radarr/Radarr#6365] opened 2021-05-29 17:55 UTC
**Is your feature request related to a problem? Please describe.**

I have multiple download clients, but each of them have their own limitations (they are in different VPS, with different bandwidth limits and disk space constraints). With radarr I'm unable to discriminate to what download client I want to send each nzb or torrent. It's important to have this feature specially for nzbs, because for example in one of the VPSs I have 100GB to spare, but in the other one I only have 40. In this case I would like to have a parameter to decide to which download client the nzb should be sent. The parameter could be something like "max size". Additional parameters could be added to.

**Describe the solution you'd like**

Each download client could have additional parameters (just like the current priority parameter) that if they evaluate to true, the download cliente is considered, and if they evaluate to false, the download client is rejected.

**Describe alternatives you've considered**

I'm currently working on my own script that takes torrents and nzbs from a blackhole, process them, and moves them to specific download clients blackholes. So basically radarr sends the nzb and torrents to the same blackhole, my script process these torrents and nzbs, and then they are distributed to their corresponding download client.

**Comment by bakerboy448** [comment] 2021-05-29 18:01
~ Duplicate of #2266

**Closed by bakerboy448** 2021-05-29 18:01 UTC
