### ISSUE TITLE
Option to prevent m2ts files from being imported/renamed

### ISSUE THREAD

**Issue by 23833716** [Radarr/Radarr#3845] opened 2019-10-27 15:52 UTC
The largest m2ts of a full UHD disc backup is being imported/moved by Radarr, it's also being renamed.  I would like to be able to prevent this behavior somehow as I need the entire backup unmodified.  When the m2ts file is moved and renamed it takes some legwork to figure out exactly what I need to rename it back to.

My only option appears to be stopping Radarr from handling completed downloads, which would not ideal as I would still like Radarr to handle completed downloads of containers (ie mkv).  Basically, I would like the best of both worlds. ;)

Just hoping there could be an option added in the future.  Maybe under 'Completed Download Handling' a toggle to select yes or no to 'Apply to m2ts files?'.

**Comment by pinn73** [comment] 2020-07-08 05:51
This is still an issue. I don't have rename option on but radarr only moves the large m2ts file correctly and the other files are left in the original folder meaning there are 2 entries for the movie in Kodi.

**Comment by bakerboy448** [comment] 2020-11-14 05:25
multi file support to fix this will be covered in a future version...

Duplicate of #145

**Closed by bakerboy448** 2020-11-14 05:25 UTC
Labels: feature request
