### ISSUE TITLE
Filter issue unmonitored does not show up in the missing or wanted filters.

### ISSUE THREAD

**Issue by hawk223** [Radarr/Radarr#6837] opened 2021-12-18 14:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Filter issue unmonitored does not show up in the missing or wanted filters.

### Expected Behavior

unmonitored should show up as missing or wanted

### Steps To Reproduce

Set all as unmonitored then filter for missing or wanted.

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 3.2.2.5080
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
```

### What branch are you running?

Develop

### Trace Logs?

trace too big

[AB#2198](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2198)

**Comment by bakerboy448** [comment] 2021-12-18 14:55
- "too big"  - this is NEVER the case.  See the wiki linked in the bug template for how to provide logs in the future

this is not a bug

unmonitored means "I do not want this. I don't care about this. Do nothing with this."

**Comment by bakerboy448** [comment] 2021-12-18 14:55
Duplicate of https://github.com/Radarr/Radarr/issues/4626

**Closed by bakerboy448** 2021-12-18 14:55 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by hawk223** [comment] 2021-12-18 15:27
I did a search and nothing turned up for me, sorry. It's still missing regardless of it's monitored status. Unmonitored means don't monitor for downloads and don't make changes. It is still missing and should still show up as missing. Without this I have no way to mark everything but the missing as unmonitored. Sonarr handles this differently than Radarr and I would say correctly.

**Comment by austinwbest** [comment] 2021-12-18 15:32
Those two filters have had a lot of discussion.. In the end it was decided no changes would be made and they work as intended by Q.

Any difference between sonarr and radarr wouldn't really factor in on this one.

**Comment by hawk223** [comment] 2021-12-18 16:13
Is the discussion available? It makes no sense either it's missing or not and I can't see why any other status would matter. It's not logical.

**Comment by bakerboy448** [comment] 2021-12-18 16:18
The linked duplicate feature request is still open - so it's not fully rejected.

just very unlucky

**Comment by ta264** [comment] 2021-12-19 14:56
> I have no way to mark everything but the missing as unmonitored.

I don't think there is ever any need to do this if you have set up your quality profiles correctly. If you want to discuss, join the discord channel.
