### ISSUE TITLE
Authentication Method

### ISSUE THREAD

**Issue by ahmaddxb** [Radarr/Radarr#9354] opened 2023-10-30 07:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Since you do not allow changing Authentication Method to external from the GUI, make it an docker enviromental variable.

### Describe the solution you'd like

```
environment:
  authmethod: external
```

### Describe alternatives you've considered

NA

### Anything else?

NA

**Comment by bakerboy448** [comment] 2023-10-30 07:20
Duplicate of https://github.com/Radarr/Radarr/issues/9284

**Closed by bakerboy448** 2023-10-30 07:20 UTC
Labels: Type: Feature Request, Status: Needs Triage
