### ISSUE TITLE
[Aphrodite] Issue when recanning a movie (and its filename changed)

### ISSUE THREAD

**Issue by sarakha63** [Radarr/Radarr#3930] opened 2019-12-09 10:33 UTC
**Describe the bug**
When we rename a movie, on the first rescan the movie is seen unaivalable than with an another rescan the new file is seen. That is ok. But the issue is that on first step radarr removes some extradata in the folder such as nfo, extrafanart folder and so on

**To Reproduce**
1. Go to a movie you have in radarr library (with nfos and complete extradata)
2. Rename the file in your file folder
3. Go to radarr on that movie page and click rescan. The movie will be seen unavailbale. And some extradatas will be removed by radarr
4. Rescan again the new file name will be detected but you lost some extradatas

**Expected behavior**
having to sometime rescan twice is not a real issue. But loosing extradatas that you have got with other programs or even taking time to get them by hand for some movie is an issue

Debug log is attached with the two rescans (test case i renamed the movie Zootopia and changed Blu-Ray to Bluray (we can see radarr wants to had those extras to recylcing bin, but it should leave them alone)
[debug.txt](https://github.com/Radarr/Radarr/files/3939168/debug.txt)

**Comment by fryfrog** [comment] 2019-12-09 18:37
This is what happens when you rename a file *outside* of Radarr. It has *no idea* what you've done. Did you rename it? Did you replace it w/ a new file? Did you re-encode it? To Radarr, it is a totally new file and will thus look like that.

The having to refresh twice is weird though, you sure you didn't just need to wait for the UI to update? Or maybe refresh the page?

**Comment by sarakha63** [comment] 2019-12-09 19:10
I'm sure. Its not always the case sometime one refresh and the new file IS Seen. Sometimes it needs a second refresh

But whatever i do i SHOULD NOT have my extrafanarts my logos my discarts my nfo mu trailers and so on be deleted  by radarr.

Radarr teams itself said on some posts to use extra programs for extras such as logo and so on. Radarr doesnt handle 3d (ands its only an example of my usage) so when i replace a standard movie with its 3D MVC version i do or manually. And its not an issue for me to have to do this manually but it IS an issue to see radarr delete some extra content (some of them IS manual hardwork)

And other reason for some manual operation is for other issues i reported about radarr messing with folder name (when locale IS foreign) resulting in having folder and filename in two different language. 

So doing manual operation is not the issue but the Real issue IS radarr removing extras as it shouldnt whatever the case unless i click on delete file and folder there IS no reason for radarr to delete files that are already in the final folder (totaly different of the option to move extras when importing and postprocessing)

Admit this IS quite a strange Behavior that a "refresh files" button décides to delete lots of files

**Comment by fryfrog** [comment] 2019-12-09 19:18
It's because the sidecar files are associated w/ the actual file. It has no idea of files that should be kept and files that should be removed, so it removes *all* the files. It'd be nice if you could set *two* lists of file names or file types, one that is imported and discarded w/ the movie file (like subs and release nfo) and ones that aren't... but that doesn't exist and it isn't an aphrodite issue. I'd dig up what ever existing issue already exists and tag on to that.

In the mean time, what ever you're using to add non-Radarr sidecar files could just set their ownership or permissions such that Radarr can't even see them or remove them.

**Comment by sarakha63** [comment] 2019-12-09 19:24
And why not simple two options of refresh

One that does what it does now and one lets call it "only refresh" which will do the same as now but with no deletion.

**Comment by fryfrog** [comment] 2019-12-09 19:26
Because no one has worked on it? If this is something you care about, there is a good chance you can learn .NET and write it before it gets done because this "issue" w/ Sonarr and Radarr has existed since... longer than I've been using it.

**Comment by sarakha63** [comment] 2019-12-09 19:31
I'm a developper ;) im more used of PHP and python. But why not. But i know WE are in te transition between old radarr and aphrodite. And there IS a heavy roadmap. Its maybe not the right Time to do some PR's

**Comment by fryfrog** [comment] 2019-12-09 19:41
It is the perfect time to do it for aphrodite, but don't bother on the old v0.2. :)

Hop on Discord and talk to @Qstick and/or @ta264.

**Comment by Qstick** [comment] 2019-12-10 01:30
Dupe of #3209

**Closed by Qstick** 2019-12-10 01:30 UTC
Labels: aphrodite, bug
