### ISSUE TITLE
Couldn't evaluate decision on [Film], with spec: DelaySpecification: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by harroguk** [Radarr/Radarr#472] opened 2017-01-27 03:45 UTC
Message...
`Couldn't evaluate decision on Sing 2016 NEW HD-TS x264-CPG, with spec: DelaySpecification: Object reference not set to an instance of an object`

Exception...
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.RssSync.DelaySpecification.IsSatisfiedBy(RemoteMovie subject, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\Specifications\RssSync\DelaySpecification.cs:line 62
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteMovie remoteEpisode, SearchCriteriaBase searchCriteriaBase) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 251
```

I get many of these types of errors for many different movies that have not yet downloaded
I am currently running...
Radarr Ver. 0.2.0.226 - develop
On...
Windows Server 2008 R2

**Comment by webbson** [comment] 2017-01-27 14:22
Duplicate of #410

**Closed** 2017-01-27 14:57 UTC
