### ISSUE TITLE
REQ: Delete from DL Client link in Activity History

### ISSUE THREAD

**Issue by quadcom** [Radarr/Radarr#8074] opened 2023-02-07 15:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not a problem, more a hassle.

### Describe the solution you'd like

While my workflow is slightly different from Radarr's intentions, it's not entirely unique. Many people use an off-site seedbox to manage torrent DL's.

That being said, automatic rtorrent seed management does not work as intended because of the remote nature of the workflow, so I have to manage that part manually. Not a biggie, but I thought of something small that would make a massive difference to me.

It would be great to see an action button to delete the rtorrent seed from the DL client from the Activity > History list. That would negate me having to go to rtorrent every time to clean out finished DL's that are not seeding.

![image](https://user-images.githubusercontent.com/7085931/217291568-b5e7d73a-219c-45b6-b6b8-0f7f417b538f.png)

### Describe alternatives you've considered

Not aware of any alternatives other than continuing manually.

### Anything else?

Nope, that's it.

[AB#4873](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4873)

**Comment by quadcom** [comment] 2023-02-07 15:47
On second thought, having a "delete" button for the import 'source' would also be handy. 

Using a remote approach means the DIR that rtorrent DL's to is not physically the same as the folder where Radarr finds the content. As expected, when Radarr imports the content into the library, the folder where that import was found remains after the import. Even after deleting the seed manually from rtorrent, that source content remains. 

There could be two delete buttons, one for the DL client and the other for the import folder. Or one button that deletes from the DL client and the imported directory simultaneously?

**Comment by bakerboy448** [comment] 2023-11-01 11:54
Duplicate of https://github.com/Radarr/Radarr/issues/3918

**Closed by bakerboy448** 2023-11-01 11:54 UTC
Labels: Type: Feature Request, Type: Duplicate
