### ISSUE TITLE
New file name tokens

### ISSUE THREAD

**Issue by Nexius2** [Radarr/Radarr#6828] opened 2021-12-17 08:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

We all have different ways to sort movies, it would be nice to have more tokens to help renaming.
I would like a {Release Decade} or the possibility to add or remove charaters before or after a token

### Describe the solution you'd like

something like:
{Release Year[-1]}x/{Movie Title} {Release Year} 
would give 
202x/Movie Title (2021)
or 
{Movie Title} {[-2]Release Year}
would give
Movie Title (21)

### Describe alternatives you've considered

having radarr pointing to a temp dir and moving files manually :-/

### Anything else?

in filebot we can do 
{((int)(y/10))+"x"} to have 2021 become 202x

[AB#2172](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2172)

**Comment by bakerboy448** [comment] 2021-12-17 13:09
What's the use case and what's the benefits for organizing everything by decade?

this can already be accomplished by the user using different root folders - no temp folders needed

This seems like a lot of effort for a ~0.1% feature.

I'd also argue this could be considered a duplicate of #153

**Comment by Nexius2** [comment] 2021-12-17 13:38
well, I sort my movies by decades as I have too many to have it in one folder.
if I use different root folder, Deluge won't know where to put the file.
I have seen the request, and that's why I said we all have different useage.
I understand if it's not taken care off, I'll continue doiing it manually ;-)

**Comment by bakerboy448** [comment] 2021-12-17 13:43
> well, I sort my movies by decades as I have too many to have it in one folder.

do you only browse movies via a file system explorer?  Either way - perfect use case for multiple root folders then.

> if I use different root folder, Deluge won't know where to put the file.

This doesn't make any sense as deluge has nothing to do with your root folders. If you have anything other than radarr moving anything into your root folder that's an issue. Nothing other than radarr should move anything into your library folder.

If deluge is downloading into your root folder than you're likely ignoring a healthcheck for that.  Downloading into your root folder is not supported and always eventually causes issues.

your download folder and your library folder MUST be separate.

for further  discussion on that  
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

**Comment by Nexius2** [comment] 2021-12-17 13:48
Yes, I often browse in the filesystem and don't want to have more then 10000 folders being displayed (even if I'm close to it sometimes) ;-)
I ment Radarr sorry, got confused, I'm new to all these methods :-)
downloads and library are seperated ;-)

**Comment by bakerboy448** [comment] 2021-12-17 13:51
Radarr handles multiple root folders without issue.  The user assigns which root folder the movie will be moved to

see the docs.

closing for now given there's existing workarounds - high effort / low reward (parser would need to be reworked to support this) and tagging for consideration in the future one day. 

Also related to 153 as previously mentioned

**Closed by bakerboy448** 2021-12-17 13:51 UTC
Labels: Type: Feature Request, Area: Parser, Status: Maybe One Day, Area: Organizer
