### ISSUE TITLE
Import movies from the 1940s fails with "Year, Month, and Day parameters describe an un-representable DateTime" 

### ISSUE THREAD

**Issue by twiceth** [Radarr/Radarr#3163] opened 2018-11-10 11:33 UTC
Trying to import movies fails with an error by SkyHookProxy.
The entries that result in errors are:
https://www.themoviedb.org/movie/307-roma-citt-aperta?language=it-IT
https://www.themoviedb.org/movie/29682-so-dear-to-my-heart?language=it-IT
https://www.themoviedb.org/movie/13757-melody-time?language=it-IT
https://www.themoviedb.org/movie/46929-fun-fancy-free?language=it-IT

They are all movie s from the 1940s maybe this has somenthing to do with the error.
Also, if I add the movie to Radarr and then move the file in the relative folder and click on "update info and scan disk" it results in the same error.

The log messages are these:

> Couldn't map movie Rome, Open City to a movie on The Movie DB. It will not be added :(: Year, Month, and Day parameters describe an un-representable DateTime.
> 
> System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
>   at System.DateTime.DateToTicks (System.Int32 year, System.Int32 month, System.Int32 day) <0x7fba3e5343e0 + 0x0017d> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.TimeZoneInfo.TransitionPoint (System.TimeZoneInfo+TransitionTime transition, System.Int32 year) <0x7fba3e570f70 + 0x0005c> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.TimeZoneInfo.IsInDSTForYear (System.TimeZoneInfo+AdjustmentRule rule, System.DateTime dateTime, System.Int32 year) <0x7fba3e56f3e0 + 0x00071> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.TimeZoneInfo.IsInDST (System.TimeZoneInfo+AdjustmentRule rule, System.DateTime dateTime) <0x7fba3e56f350 + 0x00075> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.TimeZoneInfo.GetUtcOffsetHelper (System.DateTime dateTime, System.TimeZoneInfo tz, System.Boolean& isDST) <0x7fba3e56ed60 + 0x0010c> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.TimeZoneInfo.GetUtcOffset (System.DateTime dateTime, System.Boolean& isDST) <0x7fba3e56ec50 + 0x000d5> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.TimeZoneInfo.ConvertTimeFromUtc (System.DateTime dateTime) <0x7fba3e56d520 + 0x000af> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.TimeZoneInfo.IsAmbiguousTime (System.DateTime dateTime) <0x7fba3e56f170 + 0x00085> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.DateTimeParse.AdjustTimeZoneToLocal (System.DateTimeResult& result, System.Boolean bTimeOnly) <0x7fba3e54eb10 + 0x000b0> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.DateTimeParse.DetermineTimeZoneAdjustments (System.DateTimeResult& result, System.Globalization.DateTimeStyles styles, System.Boolean bTimeOnly) <0x7fba3e54e760 + 0x00178> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.DateTimeParse.ParseISO8601 (System.DateTimeRawInfo& raw, System.__DTString& str, System.Globalization.DateTimeStyles styles, System.DateTimeResult& result) <0x7fba3e54ed10 + 0x00437> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.DateTimeParse.TryParse (System.String s, System.Globalization.DateTimeFormatInfo dtfi, System.Globalization.DateTimeStyles styles, System.DateTimeResult& result) <0x7fba3e54e000 + 0x004ca> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at System.DateTime.Parse (System.String s) <0x7fba3e535450 + 0x00088> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo (System.Int32 TmdbId, NzbDrone.Core.Profiles.Profile profile, System.Boolean hasPreDBEntry) [0x00323] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:154 
>   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie (NzbDrone.Core.Movies.Movie movie) [0x0000b] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:647

**Comment by Qstick** [comment] 2018-12-01 05:17
I can't seem to reproduce this.

**Comment by twiceth** [comment] 2018-12-01 08:56
@Qstick 
the only details that maybe could help you more reproducing this are:
-the files are named named with the Italian titles
-this is happening on an Ubuntu 16.04 headless system

You could try renaming one of the files "Tanto caro al mio cuore (1948)/Tanto caro al mio cuore (1948).x264.AC3.mkv"

Thanks for taking insterest in this issue.

**Comment by Qstick** [comment] 2018-12-01 15:56
Ok, I’ll try that and test

**Comment by Qstick** [comment] 2020-04-08 01:52
Still cant reproduce this, your error would indicate its failing using the System.DateTime.Parse here `movie.InCinemas = DateTime.Parse(resource.release_date);` If you are still seeing this what version of Mono are you using? I'm closing for now, we can always change this to a TryParse if it pops up again.

**Closed by Qstick** 2020-04-08 01:52 UTC
Labels: bug, confirmed, enhancement, priority:low
