### ISSUE TITLE
Alternative Titles not loading the "main" Alternative Title

### ISSUE THREAD

**Issue by kmr2319** [Radarr/Radarr#4467] opened 2020-05-27 01:42 UTC
**Describe the bug**
Example movie: https://www.themoviedb.org/movie/568160
Title: "Weathering with You"
Original Title: "天気の子"

This is similar to #1447, however, I believe that this is a bug that was introduced likely with 3.0 (I don't recall the last time that I needed Alternative Titles and if it was in fact after I jumped on 3.0, so I'm not sure if it was introduced more recently then my 2.0 -> 3.0 upgrade). However, I believe that the problem occurred AFTER I added the movie in (Jan 25 2020) because the PATH to the movie uses the en-US title rather than the Original Title. If I were to attempt to add a new non-English titled movie right now, the original title is used in the path (see screenshot section).

It's also entirely possible that TMDB changed something (I vaguely recall reading something about a new API version... So there's that...). With that said, from what I can tell this is (currently) a bug in Radarr.

I tested the TMDB APIs and pulled the following data for this example movie...

https://developers.themoviedb.org/3/movies/get-movie-details
(most of the data was edited out by me to keep this shorter)
```
https://api.themoviedb.org/3/movie/568160?api_key=[api]&language=en-US

{
  "id": 568160,
  "imdb_id": "tt9426210",
  "original_language": "ja",
  "original_title": "天気の子",
  "title": "Weathering with You"
}
```
Notice title and original_title fields.

https://developers.themoviedb.org/3/movies/get-movie-alternative-titles
```
https://api.themoviedb.org/3/movie/568160/alternative_titles?api_key=[key]&country=US

{
  "id": 568160,
  "titles": [
    {
      "iso_3166_1": "US",
      "title": "Child of Weather",
      "type": "Informal Literal English Title"
    },
    {
      "iso_3166_1": "US",
      "title": "Tenki no Ko",
      "type": "Romaji"
    },
    {
      "iso_3166_1": "US",
      "title": "Weather Child",
      "type": "Informal Literal English Title"
    }
  ]
}
```

Notice how the en-US default title from the get-movie-details API is not listed in the alternative_titles API response.

I would think that the "title" field should be used in all instances rather than the original title. Especially in this case since the search matched based on the title field (without coping and pasting, I wouldn't be able to search for the original title :laughing:). 

**To Reproduce**
1. Search/add a movie based on the en-US Title
2. The "Original Title" is used instead

**Expected behavior**
The en-US title (which was used to search and/or find the movie and is what is displayed on TMDB when using the links) should be used rather than "original title"

**Screenshots**
Original and Alternate Titles (notice that "Weathering with You" is not listed):
![image](https://user-images.githubusercontent.com/17013046/82964021-52b72f80-9f92-11ea-902d-97ae07ba2075.png)

Path from when I added it in with the en-US title:
![image](https://user-images.githubusercontent.com/17013046/82964072-724e5800-9f92-11ea-843f-e07538d0588a.png)

Different movie - [A Silent Voice](https://www.themoviedb.org/movie/378064) - with original title in the path:
![image](https://user-images.githubusercontent.com/17013046/82964646-066cef00-9f94-11ea-9679-be1dfe7a1d8d.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Mono Version: dotnet

```
$ dotnet --list-runtimes
Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
 - Browser and Version: Firefox 76.0.1
 - Radarr Version: 3.0.0.2998

**Debug Logs**
I can generate debug logs if needed, but it's pretty much just load the movie and get the data from TMDB that "reproduces it". Let me know if the info that I've provided isn't enough and if debug is truly required. I will need to review the logs before uploading to look for any possible personal info which is why I didn't blindly attach.

**Comment by Qstick** [comment] 2020-05-27 02:00
These come from tmdb translations and not alt titles which is why they are not added with alt titles. This is fixed in #4058 already... If you want to test that build, we could use a tester, just back up your DB first.

**Comment by Qstick** [comment] 2020-05-27 02:01
Also this is sort of a dupe of #4045

**Comment by kmr2319** [comment] 2020-05-27 02:21
Now I'm annoyed that I didn't find that one!

Details on how to test this build?

Back out procedure should it cause issues?

Thanks!

**Comment by Qstick** [comment] 2020-05-27 03:19
Are you running via docker or no? Jump on discord and I’ll shoot you a link either way, it’ll be easier to discuss that way.

**Comment by Le-Bit** [comment] 2020-05-27 08:55
Are you still looking for tester ? I watch your PR since few weeks and I'm very interested by the feature you've added ! I just joined the discord, I could use some help to get started on testing your build (and yes I use docker)

**Comment by 19wolf** [comment] 2020-05-27 13:15
I'm also willing to help test. I've been trying to figure out this issue for several days now.

**Comment by Qstick** [comment] 2020-05-27 16:44
Jump on discord Aphrodite channel

**Comment by Qstick** [comment] 2020-05-31 18:51
Closing this issue

**Closed by Qstick** 2020-05-31 18:51 UTC
Labels: bug

**Comment by 19wolf** [comment] 2020-06-04 14:33
> Closing this issue

What is the solution?
