### ISSUE TITLE
Unable to acces Radarr UI

### ISSUE THREAD

**Issue by mwmd** [Radarr/Radarr#2721] opened 2018-04-17 20:08 UTC
**Description:**

Installed Radarr a couple days ago and it worked flawless until today. The Web UI only displays the background and no content, and I see an API call from JS to the backend failing.
Since the radarr version reported in the log was apparently released today, I assume an auto-update to this version has messed something up.

Failed ajax call:
http://192.168.1.40:7878/api/movie?page=1&pageSize=250&sortKey=downloadedQuality&sortDir=asc&filterKey=null&filterValue=null 500 (Internal Server Error)

radarr.log reports the following:

18-4-17 16:05:13.1|Fatal|NzbDroneErrorPipeline|Request Failed

**Radarr Version:**
v0.2.0.1066

**Mono Version:**
Using Windows

**Debug Logs:**
[v0.2.0.1066] System.ArgumentException: Instance property 'downloadedQuality' is not defined for type 'NzbDrone.Core.Movies.Movie'
   at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
   at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel](String propertyName) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:line 36
   at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.OrderByClause[TModel](PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Extensions\PagingSpecExtensions.cs:line 11
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedQuery(QueryBuilder`1 query, PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 261
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPaged(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 252
   at NzbDrone.Core.Movies.MovieService.Paged(PagingSpec`1 pagingSpec) in C:\projects\radarr-usby1\src\NzbDrone.Core\Movies\MovieService.cs:line 149
   at NzbDrone.Api.NzbDroneRestModule`1.ApplyToPage[TModel](Func`2 function, PagingSpec`1 pagingSpec, Converter`2 mapper) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModule.cs:line 27
   at NzbDrone.Api.Movies.MovieModule.GetMoviePaged(PagingResource`1 pagingResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieModule.cs:line 117
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourcePaged>b__35_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 126
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by galli-leo** [comment] 2018-04-17 21:52
Duplicate of #2718

**Closed by galli-leo** 2018-04-17 21:52 UTC
