### ISSUE TITLE
Archived/Offline feature - to prolong HDD life and/or save space

### ISSUE THREAD

**Issue by fgordon-maker** [Radarr/Radarr#10721] opened 2024-11-30 21:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Radarr scans movie folders regularly, depending on its scheduled tasks and possibly other criteria. Combined with Sonarr and other applications, this means that the disks that hold the movie libraries have very little down time. This leads to reduced hard-disk life time (already lost two high-end hard-disks over a span of 4 years).
Would be nice to have the possibility to split the movies library(ies) between an SSD and a spinning drive, with the spinning drive holding the Archive/Offline library and the SSD holding the "Online" library.

### Describe the solution you'd like

It would be nice to have an "Archived" or "Offline" feature. 
The feature would consist of two elements:
- In addition to the regular libraries, the user will have the option to define an "Archive" library, where movie files could be stored, but would NOT be scanned or have periodic tasks running on it.

In the Movie Details Page, there would be a button which would allow the user to choose to Archive a movie. This would further allow choosing between a number of options:
- Move the movie's files to a dedicated "Archive" or "Offline" library which could possibly exist on another disk, and also mark the movie as unmonitored. Radarr would still keep track of the movie and its files location in the Archive folder, but it would not access that location during any of the scheduled tasks, so that the disk could spin down.
- (Optional) Have the option to delete the movie files completely and set the movie to "Unmonitored".
- (Optional) Over time, other features that have been requested in the past may be added here, like searching and/or keeping only a lower size movie file, etc.

When the "Archived"/"Offine" option would be unselected, the movie would be moved back to the "Online" library. If the movie was deleted instead of being moved, the user can be offered to turn on "Monitored" status for the movie or start a search for it, either automatically or manually.

### Describe alternatives you've considered

- I thought of using hard links but those only work on the same volume.
- Symlinks are very hard to keep in sync and I'm not sure that it would even help at all.

### Anything else?

I attached a mockup and a diagram explaining the feature request.

Thanks!

![Radarr-archive](https://github.com/user-attachments/assets/48880305-0e7f-46c5-8988-951b3a51e3cf)
![Radarr-archive Diagram](https://github.com/user-attachments/assets/a1df6fd6-4a0d-43f2-99bb-e1b4be6a4553)

**Comment by bakerboy448** [comment] 2024-11-30 22:28
No plans

- see https://wiki.servarr.com/radarr/faq#can-i-disable-the-refresh-movies-task

Duplicate of:
- https://github.com/Radarr/Radarr/issues/2984
- https://github.com/Radarr/Radarr/issues/1526
- https://github.com/Radarr/Radarr/issues/5543

**Closed by bakerboy448** 2024-11-30 22:28 UTC
Labels: Type: Feature Request, Status: Needs Triage
