### ISSUE TITLE
[Suggestion] Add Star Rating on main screen

### ISSUE THREAD

**Issue by Viper911** [Radarr/Radarr#2563] opened 2018-02-21 13:33 UTC
I have the RSS feeds bringing in suggested movies as Missing, but not Monitored.  Then I go through them and pick which to monitor and which to delete and add to the block list.  It would be nice on the main screen with the title to have the star rating from somewhere like IMDB or something given I may not be familiar with the movie..

**Comment by galli-leo** [comment] 2018-02-21 15:50
Duplicate of #2115

**Closed by galli-leo** 2018-02-21 15:50 UTC
