### ISSUE TITLE
'...And Justice For All' is broken by the three dots in the title.

### ISSUE THREAD

**Issue by Rajeh16** [Radarr/Radarr#7287] opened 2022-05-14 00:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Radarr doesn't recognise releases as they don't contain the three dots in the title, and it puts a dot in front of the file name once you force the download, causing Plex to not recognise it.

### Expected Behavior

Radarr should be able to recognise releases with the three dots, and name them without them as well.

### Steps To Reproduce

Add and search for '...And Justice For All'

### Environment

```markdown
- OS: Truenas 12.0-U8.1
- Radarr: 4.1.0.6175
- Docker Install: No
- Using Reverse Proxy: Yes
```

### What branch are you running?

Master

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/8691886/radarr.txt)

[AB#3143](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3143)

**Comment by bakerboy448** [comment] 2022-05-14 01:00
Duplicate of #5526

**Closed by bakerboy448** 2022-05-14 01:00 UTC
Labels: Type: Bug, Type: Duplicate
