### ISSUE TITLE
Bulk Import Folder Depth

### ISSUE THREAD

**Issue by marshgm** [Radarr/Radarr#2471] opened 2018-02-03 02:39 UTC
**Description:**

When doing bulk import, it will only see 5 levels deep.
My folder structure is like this which works for CP, 
/volume1/Media/Movies/A/A Haunted House/ A Haunted House.p4.

When importing it only see the first video in each letter drive, so only one movie from each letter is discovered. even though their are 100 more moves in the "A" folder.

0.2.0.910

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment] 2018-02-03 14:09
Duplicate of #153

**Closed by galli-leo** 2018-02-03 14:09 UTC
