### ISSUE TITLE
Downloads revision although proper & repack is disabled

### ISSUE THREAD

**Issue by steve1977** [Radarr/Radarr#5331] opened 2020-11-13 23:30 UTC
I am on 3.0.0.4005.

Radarr download revisions for moviesL

2020-11-13 21:32:46.7|Debug|Parser|Quality parsed: Bluray-1080p v2
2020-11-13 21:32:46.7|Debug|UpgradeAllowedSpecification|Comparing file quality with report. Existing file is Bluray-1080p v1 []

I have set file management to file management - Propers and Repacks - Do not Upgrade Automatically

Thanks for your help!

[AB#1035](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1035)

**Comment by bakerboy448** [comment] 2020-11-13 23:37
Logs: https://pastebin.com/Z3MLJwC3
Version: 3.0.0.4005

Discord Context:
>Look at the logic in UpgradableSpecification then to see if something looks off
https://github.com/Radarr/Radarr/blob/d9ff8e0d4a25fb4ed0ad53d7d064cb4df66fdebb/src/NzbDrone.Core/DecisionEngine/Specifications/UpgradableSpecification.cs#L48 rev is only compared on upgradable check if that setting is not don't prefer

Line 99  is just used by another decision spec

**Comment by Qstick** [comment] 2020-11-15 02:41
Log is expired

**Comment by Qstick** [comment] 2020-11-15 03:01
Seems to work as expected here
```
[Trace] [13] DownloadDecisionMaker: Processing release 798/939 
[Trace] [13] EventAggregator: Publishing CommandUpdatedEvent 
[Trace] [13] EventAggregator: CommandUpdatedEvent -> CommandModule 
[Trace] [13] EventAggregator: CommandUpdatedEvent <- CommandModule 
[Trace] [13] EventAggregator: CommandUpdatedEvent -> CommandModule 
[Trace] [13] EventAggregator: CommandUpdatedEvent <- CommandModule 
[Debug] [13] Parser: Parsing string 'The.Ballerina.2017.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG' 
[Trace] [13] Parser: ^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\) 
[Debug] [13] Parser: Movie Parsed. The Ballerina - 2017  
[Debug] [13] Parser: Release Group parsed: NTG 
[Debug] [13] Parser: Languages parsed: Unknown 
[Debug] [13] QualityParser: Trying to parse quality for The.Ballerina.2017.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG 
[Debug] [13] Parser: Quality parsed: WEBDL-1080p v2 
[Debug] [13] Parser: Edition parsed:  
[Debug] [13] ParsingService: Language couldn't be parsed from release, fallback to movie original language: English 
[Debug] [13] AcceptableSizeSpecification: Beginning size check for: The.Ballerina.2017.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG 
[Debug] [13] AcceptableSizeSpecification: Item: The.Ballerina.2017.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG, meets size constraints 
[Trace] [13] ConfigService: Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True' 
[Debug] [13] AlreadyImportedSpecification: Performing already imported check on report 
[Debug] [13] LanguageSpecification: Checking if report meets language requirements. English 
[Trace] [13] ConfigService: Using default config value for 'maximumsize' defaultValue:'0' 
[Debug] [13] MaximumSizeSpecification: Maximum size is not set. 
[Trace] [13] ConfigService: Using default config value for 'minimumage' defaultValue:'0' 
[Debug] [13] MinimumAgeSpecification: Minimum age is not set. 
[Debug] [13] QualityAllowedByProfileSpecification: Checking if report meets quality requirements. WEBDL-1080p v2 
[Debug] [13] ReleaseRestrictionsSpecification: Checking if release meets restrictions: The.Ballerina.2017.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG 
[Debug] [13] ReleaseRestrictionsSpecification: [The.Ballerina.2017.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG] No restrictions apply, allowing 
[Debug] [13] UpgradableSpecification: New quality is a better revision for existing quality 
[Trace] [13] ConfigService: Using default config value for 'retention' defaultValue:'0' 
[Debug] [13] RetentionSpecification: Checking if report meets retention requirements. 1 
[Debug] [13] UpgradeAllowedSpecification: Comparing file quality with report. Existing file is WEBDL-1080p v1 [] 
[Debug] [13] UpgradableSpecification: Quality profile allows upgrading 
[Debug] [13] UpgradeDiskSpecification: Comparing file quality with report. Existing file is WEBDL-1080p v1 [] 
[Trace] [13] ConfigService: Using default config value for 'availabilitydelay' defaultValue:'0' 
[Debug] [13] DelaySpecification: Profile does not require a waiting period before download for Usenet. 
[Trace] [13] ConfigService: Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True' 
[Debug] [13] HistorySpecification: Performing history status check on report 
[Debug] [13] HistorySpecification: Checking current status of movie [1269] in history 
'Radarr.Console.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[Debug] [13] UpgradableSpecification: New quality is a better revision for existing quality 
[Debug] [13] ProperSpecification: Auto downloading of propers is disabled 
[Debug] [13] DownloadDecisionMaker: Release rejected for the following reasons: [Permanent] Proper downloading is disabled 
```

Notice how proper spec kicks it out as I have it set to not automatically upgrade

```
[Debug] [13] ProperSpecification: Auto downloading of propers is disabled 
```

**Comment by steve1977** [comment] 2020-11-15 11:34
Follow-up from the exchange on Discord.

It doesn't upgrade to V2 if using RSS.

However, it does upgrade from V1 to V2 either when using "search all" or also when "search movie" when having the movie selected. It is easy to reproduce. Just pick any movie you have where you have a V1 version and a proper/V2 is available. If helpful I can provide the logs again.

This turns into an issue for me. Reason being is that I have manually imported my library. So, while many of my releases are "proper", they do show up as "V1".

So, I cannot use the "search all" feature without having dozens of movies being downloaded again (both from 480p-V1 to 480p-V2 or from 1080p-V1 to 1080p-V1). Even when I filter for "cutoff unmet", this is an issue as it upgrades from 480p-V1 to 480p-V2 for movies where 1080p is unavailable).

I am planning in the future to upgrade my full library to quality profile 2160p. This will make all my movies show as "cutoff unmet" and most likely lead to a flood of upgrades from 1080p-V1 to 1080p-V2 (2160p not available, manually imported proper movie displayed as V1).

Thanks for looking into this and a potential fix!

**Comment by Qstick** [comment] 2020-11-15 14:42
Yea I'm leaning to having the proper settings also applied to automatic searches...

**Comment by austinwbest** [comment] 2020-11-15 16:15
I kinda think it should as that could be a ratio killer lol.. And just a red warning on the manual search

**Comment by steve1977** [comment] 2020-11-16 02:36
Cool, would be great to have this change implemented.

So far, it is not a major issue for me. I can "search filtered" (cutoff unmet). Still some inconvenience with the V2 for dvd / webrip, but ultimately that's minor.

It will become a larger issue when I upgrade to 4k. Then, filtering for cutoff-unmet is basically the whole library. And many of them may not have 4k file, which will led to a flood of redownloads of V2 for 1080p files.

Thanks for looking into this!

**Comment by bakerboy448** [comment] 2021-08-20 21:50
@RobinDadswell  did https://github.com/Radarr/Radarr/commit/ce6f52552af15f1184c5eaa816d92dc92d1f232c handle this?

**Comment by bakerboy448** [comment] 2022-05-22 02:46
Duplicate of #6595

**Closed by bakerboy448** 2022-05-22 02:46 UTC
Labels: Type: Bug
