### ISSUE TITLE
[FEAT]: Optional MySQL DB Support

### ISSUE THREAD

**Issue by fbc** [Radarr/Radarr#6649] opened 2021-10-10 17:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

SQLITE corrpution/table locking for extremely large DBs

### Describe the solution you'd like

External DB connection to a MYSQL DB would be awesome

### Describe alternatives you've considered

I haven't

### Anything else?

Just have the app use a MYSQL DB for it's current SQLITE DB needs.

[AB#1751](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1751)

**Comment by bakerboy448** [comment] 2021-10-10 17:15
Duplicate of https://github.com/Radarr/Radarr/issues/677

> > Is there an existing issue for this?
>  I have searched the existing issues

There is no way you searched for MySQL
https://github.com/Radarr/Radarr/issues?q=is%3Aissue+MySQL

**Closed by bakerboy448** 2021-10-10 17:15 UTC
Labels: Type: Feature Request, Status: Needs Triage
