### ISSUE TITLE
New Notification Option

### ISSUE THREAD

**Issue by Apollo5555** [Radarr/Radarr#7660] opened 2022-10-05 18:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr waiting for my input

### Describe the solution you'd like

I would like to add a checkbox option to be notified when user input is required.

As an example, I would like to have Discord setup with that option set, so when a recent download fails to be imported, for whatever reason I can get a notification that I have to login and make a decision.

Sometimes things will sit there waiting to be imported simple because I didn’t know it was there.

Would love this to be added.

### Describe alternatives you've considered

na

### Anything else?

nope

[AB#3875](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3875)

**Comment by bakerboy448** [comment] 2022-10-05 20:54
Duplicate of https://github.com/Radarr/Radarr/issues/5164
Duplicate of https://github.com/Radarr/Radarr/issues/5344

**Comment by austinwbest** [comment] 2022-10-05 20:55
You're after a stuck trigger which is not as simple as adding a checkbox. It would also require rules on "what" is considered stuck, how long to wait before sending it because some things just need a little time to clear, how often to send it, etc

**Closed by bakerboy448** 2022-10-05 20:54 UTC
Labels: Type: Feature Request, Type: Duplicate
