### ISSUE TITLE
Ability to quickly select different DL clients when doing interactive searches

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#5936] opened 2021-02-14 04:02 UTC
**Is your feature request related to a problem? Please describe.**
As at the moment, there is no way to select the desired download client when doing interactive searches if you have multiple clients configured. You are forced to go all the way back to the settings page, disable the one you don't wanna use, then enable the one you want to use.

**Describe the solution you'd like**
A way to select the client directly from the interactive search page. Kinda like the way NZBHydra has done it. You see the icons of all the download clients configured and just hit the one you like to DL to.

**Describe alternatives you've considered**
Probably a quick toggle on the main page for switching the active client if you have more than one configured.

**Additional context**
For folks who have more than one DL client set up that DLs to different machines regularly.

**Comment by bakerboy448** [comment] 2021-05-29 17:59
Duplicate of #4843

**Closed by bakerboy448** 2021-05-29 17:59 UTC
Labels: Type: Feature Request
