### ISSUE TITLE
can't refresh existing movie which are missing artwork

### ISSUE THREAD

**Issue by realbuz** [Radarr/Radarr#4466] opened 2020-05-26 22:20 UTC
**Describe the bug**
some movies will not show artwork after importing (existing media, clean radarr install)

**To Reproduce**
1. select a movie without artwork visible
2. hit refresh 

**Expected behavior**
should fetch the artwork

Version
3.0.0.2998
Package Version
aphrodite-77dd8ca-921 by hotio

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4685268/radarr.debug.txt)

**Comment by Qstick** [comment] 2020-05-26 22:38
Dupe of #3965 (the root cause)

**Closed by Qstick** 2020-05-26 22:38 UTC
Labels: bug
