### ISSUE TITLE
[Feature] Movies 'snatched' get marked snatched, not remaining 'missing'

### ISSUE THREAD

**Issue by jaxjexjox** [Radarr/Radarr#2921] opened 2018-07-29 10:19 UTC
Subject says it all.

Grabbed a movie - the primary movie list just says missing, I'd love to see a "snatched" or "downloadING" flag, etc

**Comment by galli-leo** [comment] 2018-08-12 18:04
Duplicate of #252

**Closed by galli-leo** 2018-08-12 18:04 UTC
