### ISSUE TITLE
Titles in search tab are cropped on small screen (phones or tablet) 

### ISSUE THREAD

**Issue by ToXinE** [Radarr/Radarr#5436] opened 2020-11-30 09:45 UTC
The titles displayed in manual search are cropped on phone which make this screen unusable.

1. Go to radarr and select a movie
2. Click on 'search'
3. in Firefox, press Ctrl+Shift+M (adaptative mode) and select any phone

**Expected behavior**
You must be able to see the whole title even on phone like in sonarr or in radarr V2. See attached gif:
![sonarr_title_OK](https://user-images.githubusercontent.com/6205053/100593232-715b0200-32f8-11eb-9b50-5a930aa870e0.gif)

** screenshots **
![radar_3_title_problem](https://user-images.githubusercontent.com/6205053/100593074-3d7fdc80-32f8-11eb-8b15-d857f3487b79.gif)

**Platform Information:**
 - OS: [Ubuntu 20.10]
 - Docker: [Yes]
 - Mono or.NET Core Version: [Mono 6.12.0.90]
 - Browser and Version [chrome 86.0.4240.198, Firefox 83.0]
 - Radarr Version [3.0.0.4204]
 - Radarr Branch [develop]

**Comment by bakerboy448** [comment] 2020-11-30 15:48
Duplicate of #3926

**Closed by bakerboy448** 2020-11-30 15:48 UTC
Labels: bug
