### ISSUE TITLE
Adding movies over the search feature creates paths without the IMDb Id 

### ISSUE THREAD

**Issue by hashworks** [Radarr/Radarr#3117] opened 2018-10-22 19:00 UTC
**Describe the bug**
Adding a new movie using the search with `{IMDb Id}` in `Standard Movie Format` or `Movie Folder Format` results in a path without the id in it.

This is because of TMDb not retuning the IMDb Id in a search result:
```
{
    "vote_count": 443,
    "id": 10226,
    "video": false,
    "vote_average": 6.6,
    "title": "High Tension",
    "popularity": 5.628,
    "poster_path": "\/oyyhw5Ph9p5M4par
gwN2aE9OLCO.jpg",
    "original_language": "fr",
    "original_title": "Haute tension",
    "genre_ids": [
        27,
        53,
        9648
    ],
    "backdrop_path": "\/kmjHWTujBgdUXsS1hFB0lPwfccU.jpg",
    "adult": false,
    "overview": "...",
    "release_date": "2003-06-18"
}
```

Maybe we should call `newMovie = GetMovieInfo(newMovie.TmdbId, newMovie.Profile, newMovie.HasPreDBEntry);` at the start of [AddMovie](https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Movies/MovieService.cs#L156)?

**To Reproduce**
1. Add `{IMDb Id}` in `Movie Folder Format` under Media Management/Movie Naming (Advanced Settings)
2. Search for a new movie and add it
3. Folder path does not contain `{IMDb Id}`

**Expected behavior**
The IMDb Id should be fetched before the path is generated and the new folder path should contain the IMDb Id if set in the settings.

**Comment by hashworks** [comment] 2018-10-22 19:12
According to @galli-leo this is a known issue:
```
@hashworks Yeah that is a known issue, also with other metadata stuff
Proteus is the project intended to fix that
```
So this should be linked to the original issue and closed.

**Comment by galli-leo** [comment] 2018-10-30 10:22
Duplicate of #153

**Closed by galli-leo** 2018-10-30 10:22 UTC
