### ISSUE TITLE
Changing paths not working properly in latest nightly

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#2207] opened 2017-10-21 20:46 UTC
**Description:**

Changing the path via Movie Editor just adds the path to the front of the current one instead of replacing it. 

**Example:**

Movie Folder: `10,000 BC (2008)`
Old Path: `movies/American/`
New path desired: `/movies/Movies/`
New path result: `/movies/Movies//movies/American/10,000 BC (2008)`

**Radarr Version:**

Radarr Ver. 0.2.0.882
nightly

**Screenshot:**

![image](https://user-images.githubusercontent.com/5501908/31855749-e6156484-b676-11e7-9447-e5efddb29d12.png)

**Comment by tusharbhutt** [comment] 2017-10-21 23:38
Same as #2170

https://github.com/Radarr/Radarr/issues/2170

**Comment by desimaniac** [comment] 2017-10-22 00:10
Yup, same issue.

**Comment by galli-leo** [comment] 2017-11-19 13:58
Duplicate of #2170

**Closed by galli-leo** 2017-11-19 13:58 UTC
