### ISSUE TITLE
The option to ignore already downloaded releases

### ISSUE THREAD

**Issue by UnknownUser6** [Radarr/Radarr#6127] opened 2021-03-29 17:24 UTC
I am organizing my library in a way Radarr doesn't allow me to, that's why I have a download folder from where I manually add files to my library, which is fine. But as soon as I remove the file from the download folder Radarr want's to redownload it of course. That's why I would like to manually or automatically mark a certain release as already downloaded.

**Comment by bakerboy448** [comment] 2021-03-29 17:26
Closing Feature Exists: "Ignore Deleted Movies"

I.e. unmonitor the movie when it detects the file is missing
https://wiki.servarr.com/Radarr_Settings#File_Management

it sounds like radarr is not the tool for you if you're doing extensive manual management, not using it's automation, and just using it to get downloads.

**Closed by bakerboy448** 2021-03-29 17:26 UTC
Labels: feature request

**Comment by UnknownUser6** [comment] 2021-03-29 17:39
I am not sure this is what I mean. I don't want the movie to be unmonitored. It should just ignore the specific release and download another release as soon as available. I have a big library and Radarr still takes work from my shoulders by monitoring it all. That's why I don't think it is the wrong tool for me. Unless there is a better one for my usecase.

**Comment by UnknownUser6** [comment] 2021-03-29 17:40
> Closing Feature Exists: "Ignore Deleted Movies"
> 
> I.e. unmonitor the movie when it detects the file is missing
> https://wiki.servarr.com/Radarr_Settings#File_Management
> 
> it sounds like radarr is not the tool for you if you're doing extensive manual management, not using it's automation, and just using it to get downloads.

I am not sure this is what I mean. I don't want the movie to be unmonitored. It should just ignore the specific release and download another release as soon as available. I have a big library and Radarr still takes work from my shoulders by monitoring it all. That's why I don't think it is the wrong tool for me. Unless there is a better one for my usecase.

**Comment by ta264** [comment] 2021-03-29 17:43
I don't think we have any appetite to do this, it would be a lot of work for very little gain for anyone else.

**Comment by bakerboy448** [comment] 2021-03-29 17:46
Sounds like you have radarr pointed at your download folder rather than your library.

Or you're moving files outside of radarr under Radarr's nose and thus on the rescan it sees them are missing.

One of those, or similar actions, are the root cause of your issue.

regardless no appetite to make the high effort, low reward, tiny use case change you request.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for further support/questions.
