### ISSUE TITLE
Feature Request: mark download as complete/unmonitored after x days

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3229] opened 2018-12-03 04:02 UTC
**Is your feature request related to a problem? Please describe.**
Pretty simple, some people want better qualities some don't, a lot of people think "it's done , good". Some don't and it should stay an open option.
Why do I ask, I know what i'm grabbing, it's a lot of work to manually change things, it's ok but a lot of work while a single value change could solve the issue.

**Describe the solution you'd like**
A value box, 0-100 days, disabled by default but when enabled 0 days means instantly marked as Unmonitored, 1 day is it stil checks for a day etc, etc.
 
**Describe alternatives you've considered**
You could add a check box at each file that says done is done/unmonitored (more work for both parties) or add a box "mark as done after initial grab" but that removes flexiblity.

**Additional context**
None, no extra notes and I assume the request is clear, thank you and cheers lads!

**Comment by galli-leo** [comment] 2018-12-20 07:48
duplicate of #3224

**Closed by galli-leo** 2018-12-20 07:48 UTC
