### ISSUE TITLE
Unmatched downloads do not show in Activity

### ISSUE THREAD

**Issue by primeinc** [Radarr/Radarr#3085] opened 2018-10-09 15:56 UTC
**Describe the bug**
When searching for a file to download, Radarr finds a release and sends it to SABnzbd. It then fails to show up in the activity tab. The movie is successfully downloaded by SABnzbd, but because Radarr is not tracking its progress the movie never gets imported. To make problems worse, the release is never blacklisted, so if you don't pay attention and keep searching for the movie it will just keep downloading the same copy multiple times. This only happens with certain titles releases, and its not movie specific. If I blacklist the release that doesn't show up in the activity tab, it finds a different release and works as its supposed to.

While I've only shown one movie here, I've got other movies/releases that are having what I think is the same issue, I can test further if required. For example, this is some of whats in my pending sort folder, and I've got nothing in the queue but there is a large movie file in each of these folders. At the very least the ones that show up multiple times probably have this issue.
![image](https://user-images.githubusercontent.com/4395149/46681628-a4daef80-cbb9-11e8-8b6b-3a71086dac75.png)

On a side note, is it possible to manually import a movie that doesn't show up in the queue?

**Expected behavior**
The download should show up on the activity tab and be imported on completion.

**Screenshots**
![image](https://user-images.githubusercontent.com/4395149/46680699-9a1f5b00-cbb7-11e8-99f0-e2f72122bfe0.png)
![image](https://user-images.githubusercontent.com/4395149/46680751-b8855680-cbb7-11e8-9081-a7e2d1c922e8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Nightly 0.2.0.1198

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2461134/radarr.debug.txt)

**Comment by primeinc** [comment] 2018-10-09 18:02
Here is another example:
```
18-10-9 10:58:44.2|Debug|Parser|Parsing string 'Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER'
18-10-9 10:58:44.2|Debug|Parser|Movie Parsed. Enemy of the State EC - 1998 
18-10-9 10:58:44.2|Debug|ParsingService|Language(s) parsed: 
18-10-9 10:58:44.2|Debug|QualityParser|Trying to parse quality for Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER
18-10-9 10:58:44.2|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
18-10-9 10:58:44.3|Debug|Parser|Parsing string 'Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER'
18-10-9 10:58:44.3|Debug|Parser|Movie Parsed. Enemy of the State EC - 1998 
18-10-9 10:58:44.3|Debug|ParsingService|Language(s) parsed: 
18-10-9 10:58:44.3|Debug|QualityParser|Trying to parse quality for Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER
18-10-9 10:58:44.3|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
18-10-9 10:58:44.4|Debug|Parser|Parsing string 'Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER'
18-10-9 10:58:44.4|Debug|Parser|Movie Parsed. Enemy of the State EC - 1998 
18-10-9 10:58:44.5|Debug|Parser|Parsing string 'Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER'
18-10-9 10:58:44.5|Debug|Parser|Movie Parsed. Enemy of the State EC - 1998 
18-10-9 10:58:44.5|Debug|DownloadedMovieImportService|Unknown Movie Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER
```
It looks like the parser for selecting the release to download and the parser that interprets the queue activity from SAB are slightly different.

**Comment by fryfrog** [comment] 2018-10-09 21:06
Check your category / label settings in both. Check for a single download choking up the scan of sabnzbd queued items. Check your history too, if you have tons of items it might cause problems.

**Comment by primeinc** [comment] 2018-10-09 21:17
I'm pretty positive it's not a problem with my setup. Radarr is the one sending the release to SABnzbd and works with other differently named releases. Also my history was cleared before I generated the logs and nothing else was in SABnzbd's queue.

During troubleshooting I figured out you can change the name of a release in the SABnzbd queue. So working with the release called "Enemy.of.the.State.EC.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER" which again was downloaded with Radarr, I changed the name inside of SABnzbd to "Enemy.of.the.State.1998.BluRay.1080p.LPCM_+_ac3_+_DTS.Remuxed.dxva-KNiCKER" (I removed EC from between the title and the date) and it appeared in the Activity Queue in Radarr almost instantly and was processed correctly.

If you look at the original log and the additional comment Radarr is reporting "DownloadedMovieImportService|Unknown Movie Enemy.of.the.State.EC.1998.BluRay.1080p...." and I'm assuming because this release had an erroneous EC in the name. Also with the Taken release that was having the same issue it erroneously had "96.Hours" in front of the Title of the movie.

I'm not sure, other then changing the name of the release when its sent to SABnszbd (if that's even possible) if this can be fixed easily.

However, maybe instead of not showing the downloaded release in the Queue because it can't match it to a movie. Make it show up and ask you to select the movie manually.

**Comment by primeinc** [comment] 2018-10-09 21:48
Thanks, a couple ideas off the cuff since they currently fail silently and prevent any progress on that movie.
1) Try and parse the release name from the potential search results before sending it over to the download client and not downloading it if it won't match.
2) Rename the file to something parsable when sending it to the download client (not sure if thats possible)
3) Show unmatched downloads in the Activity Queue

Anyway I'm all set just wanted to make sure you guys were aware.

**Comment by galli-leo** [comment] 2018-10-11 09:07
@primeinc Force download already works for movie names. The issue here is differing names reported by your indexer and download client.

The only real option here is to show unmatched movies in your activity queue, so you can manually import them. (It‘s under Wanted).

**Comment by geogolem** [comment] 2018-11-02 05:58
ya, this happens to me on occasion... the good thing in those case, is that radarr doesn't remove the movies from the downloader's history.. so when i see a successful download in my downloader that radarr never seems to pick up it usually corresponds to this issue --> i then go back to the Wanted page and manually import the movie into radarr... and manually remove the movie from my download client..

**Comment by galli-leo** [comment] 2018-11-02 08:08
@geogolem That was something I had planned some time ago, but I think the better option here would be, to just show that a movie failed to match. I am currently working on making the parsing for importing more closely match that when downloading. That should enable showing of unmatched movies.

**Comment by krulos** [comment] 2019-01-12 20:34
I just installed, configured and switched to NZBGET instead of SABNZBD to see if its the downloaders fault. Unfortunately the problem remains. Some releases just won't get added to activity queue. It's so frustrating that I can't trust radarr.

**Comment by fryfrog** [comment] 2019-01-13 04:05
I reproduced with Anchorman 2 which Radarr had *already downloaded* in the past. It just isn't seeing some movies for some reason. :/

**Comment by krulos** [comment] 2019-01-16 14:03
Come on guys! This anomaly is driving me nuts!

**Comment by krulos** [comment] 2019-01-31 10:17
I just uninstalled and reinstalled again, it didn't help. Same problem. I'm so sad :(

**Comment by krulos** [comment] 2019-02-22 12:16
Please help!

**Comment by galli-leo** [comment] 2019-02-22 12:35
No need to uninstall, this is due to the download not being recognized by Radarr. This happens usually if the title is not one in TMDB, but the indexer tags it with an imdbid. When downloading, Radarr will see the title with imdbid and then download the file. However, currently Radarr „forgets“ about that and then is unable to parse the movie when in your download client.

**Comment by krulos** [comment] 2019-02-22 12:38
Thank you @galli-leo for answer. Do you know of any workaround or solution? This anomaly makes radarr kind of unreliable and not very automatic since I have to keep an watchful eye for un-parsed movies. Sonarr don't seem to have the same issue.

**Comment by fryfrog** [comment] 2019-02-22 21:45
Sonarr does have the same issue, if an episode gets queued up that is so poorly named that it can't match it w/ a show, the same thing will happen. But I think it is much more rare. Movies often have a variety  of different names while TV shows don't.

**Comment by krulos** [comment] 2019-02-24 16:41
Thank you, do you know of any workaround or solution?

**Comment by Wyattsb** [comment] 2019-03-09 21:29
I have been losing my mind over this issue, I am in the process of migrating from Couchpotato and have well over 500 movies and about 75 of them will not import and have downloaded about 20 times in Sabnzbd without issue, sitting in the completed folder. I would love for it to prompt for manual import if the name is "close enough" to match.

**Comment by danialmoghaddam** [comment] 2019-05-17 04:57
Maaan, I've been (for about a week or two) switching back and forth between Sab and Nzbget and changing all kinds of settings thinking I messed up something. I went almost mental!

**Comment by ace518** [comment] 2019-07-10 06:26
This is the ONLY thing in my setup that does not work correctly.  Since my download folder is on its own hard drive, this then clogs that drive up because the unmatched movies build up and eventually my entire setup crashes.  I have been blacklisting releases until it finds one that matches.  I did not know about the manual import option above.  That seems to be helping me now, but I'd love to see this resolved.  And to fryfrogs comment back in Feb... yeah, this happens to me in Sonarr occasionally as well.

**Comment by kevincianfarini** [comment] 2019-12-15 05:20
Is an issue opened with Sonarr upstream?

**Comment by fryfrog** [comment] 2019-12-15 05:22
This is fixed in Sonarr's v3 and by extension, Radarr's port of it. Yay!

**Comment by kevincianfarini** [comment] 2019-12-15 05:30
Do we know when th3 v3 release is planned?

**Comment by fryfrog** [comment] 2019-12-15 05:33
When it's ready.

I'd highly recommend Sonarr's v3, been running it for awhile. I'm using Radarr's v3 too, but I wouldn't quite recommend it. Close though!

**Comment by Qstick** [comment] 2020-01-16 01:46
Closing for v3 fix, no backport planned

**Closed** 2020-01-16 01:45 UTC
Labels: confirmed, done aphrodite, enhancement, sonarr upstream
