### ISSUE TITLE
Add missing as option on custom filters

### ISSUE THREAD

**Issue by Norin-Radd** [Radarr/Radarr#5570] opened 2020-12-17 22:26 UTC
hello,

there's no option for missing movies on custom filters.

is it possible to implement this feature?

![image](https://user-images.githubusercontent.com/14083654/102551116-e1b6a100-40b6-11eb-80fe-bc46ee6dbeca.png)

**Comment by bakerboy448** [comment] 2020-12-17 22:34
Duplicate of #5004

Please use the search feature

for now you can use size on disk = 0 which is the same thing

**Closed by bakerboy448** 2020-12-17 22:34 UTC
Labels: feature request
