### ISSUE TITLE
Radarr downloading 0kb poster

### ISSUE THREAD

**Issue by Buster14** [Radarr/Radarr#5798] opened 2021-01-21 23:27 UTC
**Describe the bug**

Most of the time when adding new movies, radarr downloads 0 b poster instead of correct poster
**To Reproduce**
1. Add movies
2. Check folder of added movies
3. poster is 0kb

**Expected behavior**
Full sized poster

**Screenshots**

https://imgur.com/a/9dIfumU

**Platform Information (please complete the following information):**
 - OS: Server 2019
 - Docker: No
 - Radarr Version: 3.0.1.4259
 - Radarr Branch: master

**Trace Logs**
2021-1-1 07:17:45.3|Info|NzbSearchService|Searching 3 indexers for [Skylines] 2021-1-1 07:17:47.0|Info|DownloadDecisionMaker|Processing 22 releases 2021-1-1 07:19:40.1|Info|AddMovieService|Adding Movie [Yearly Departed (2020)][tt13321268, 781188] Path: [N:\FILM_BARAT\Y\Yearly Departed (2020)] 2021-1-1 07:19:40.1|Info|RefreshMovieService|Updating info for Yearly Departed 2021-1-1 07:19:40.2|Info|MediaCoverService|Downloading Poster for [Yearly Departed (2020)][tt13321268, 781188] https://image.tmdb.org/t/p/original/i1g0c8FjNCMkmkqvYthjDqM0dDo.jpg 2021-1-1 07:19:40.2|Info|DiskScanService|Scanning disk for Yearly Departed 2021-1-1 07:19:40.2|Info|DiskScanService|Completed scanning disk for Yearly Departed 2021-1-1 07:19:40.2|Info|MovieScannedHandler|[Yearly Departed] was recently added, performing post-add actions 2021-1-1 07:19:40.2|Info|NzbSearchService|Searching 3 indexers for [Yearly Departed] 2021-1-1 07:19:40.3|Info|ExistingMetadataImporter|Found 0 existing metadata files 2021-1-1 07:19:40.3|Info|ExistingSubtitleImporter|Found 0 existing subtitle files 2021-1-1 07:19:40.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files 2021-1-1 07:19:40.3|Info|ExistingExtraFileService|Found 0 extra files 2021-1-1 07:19:56.3|Info|DownloadDecisionMaker|Processing 10 releases 2021-1-1 07:19:56.5|Info|DownloadService|Report sent to Qbittorrent. Yearly.Departed.2020.1080p.WEBRip.x264-RARBG 2021-1-1 07:19:56.5|Info|MovieSearchService|Movie search completed. 1 reports downloaded.

After this i deleted the 0kb poster and press refresh and scan, and the log generates this, and the correct poster size is downloaded :

2021-1-1 07:21:39.7|Info|RefreshMovieService|Updating info for Yearly Departed 2021-1-1 07:21:39.8|Info|DiskScanService|Scanning disk for Yearly Departed 2021-1-1 07:21:39.8|Info|DiskScanService|Completed scanning disk for Yearly Departed 2021-1-1 07:21:39.8|Info|ExistingMetadataImporter|Found 0 existing metadata files 2021-1-1 07:21:39.8|Info|ExistingSubtitleImporter|Found 0 existing subtitle files 2021-1-1 07:21:39.8|Info|ExistingOtherExtraImporter|Found 0 existing other extra files 2021-1-1 07:21:39.8|Info|ExistingExtraFileService|Found 0 extra files

**Comment by bakerboy448** [comment] 2021-01-21 23:30
Duplicate of #5419

**Closed by bakerboy448** 2021-01-21 23:30 UTC
Labels: Type: Bug
