### ISSUE TITLE
Monitor streaming services and exclude available movies

### ISSUE THREAD

**Issue by zeus1n** [Radarr/Radarr#8698] opened 2023-06-15 10:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Like many users, I have Radarr automatically importing movies from several lists. I mostly follow lists of new releases so I can download all the new movies as they are released. 

I subscribe to many streaming services (Netflix, Disney, Hulu, Max, several more) and to save space on my server I do not want to download movies that I can stream.

### Describe the solution you'd like

It would be amazing if Radarr can monitor the streaming services, maybe use a website like JustWatch to see what movies are available where. I want to tell Radarr what streaming services I subscribe to. Then when a new movie pops up on the monitored new release list, I want Radarr to cross reference and see if the movie is available on any of the streaming services I subscribe to. Only download if not available elsewhere.

### Describe alternatives you've considered

My server is almost completely out of space so I have to be a lot more selective of what I download. My current workaround is I stopped monitoring all lists and no longer add any movies automatically. I just check new releases myself, check if they are available to stream on justwatch.com, and if not I manually add them to Radarr. 

I really miss auto importing movies from lists. That was an amazing feature. But to me the it's a fatal flaw when 2/3 of the movies I download I already have access to through streaming.

### Anything else?

That's it.

**Comment by bakerboy448** [comment] 2023-06-15 13:27
Duplicate of several issues....please search next time and don't simply check the box claiming you searched https://github.com/Radarr/Radarr/issues?q=is%3Aissue+is%3Aopen+streaming

**Closed by bakerboy448** 2023-06-15 13:27 UTC
Labels: Type: Feature Request, Status: Needs Triage
