### ISSUE TITLE
Monitored toggle in table view

### ISSUE THREAD

**Issue by gaurav3297** [Radarr/Radarr#6095] opened 2021-03-25 17:54 UTC
The feature request was raised already as #610 but closed with reference to previously implemented Monitor flag in "Movie edit" view. Re-raisign as a request to add in the main movie window as I feel it would be better/more convenient because of following reasons:
- There are additional columns to sort by in the main movie view compared to movie edit view. e.g. I sometimes would like to sort by "Date added" and then toggle monitored status
- In the movie edit window a change in toggle flag causes the list to switch to "unfiltered/all" and re-renders the list. So I I am looking to toggle multiple movies, they go out of view after the first one is toggled.

I believe all other settings that are handled via the Movie edit view are fine as is. They are rather detailed/one off settings. But toggling monitoring on/off should be somewhat easier/readily doable without going through multiple screens and clicks.

**Comment by bakerboy448** [comment] 2021-03-25 17:56
I believe we can close this?

>There are additional columns to sort by in the main movie view compared to movie edit view. e.g. I sometimes would like to sort by "Date added" and then toggle monitored status

These are the same, unified view and filters.

>In the movie edit window a change in toggle flag causes the list to switch to "unfiltered/all" and re-renders the list. So I I am looking to toggle multiple movies, they go out of view after the first one is toggled.

Could not reproduce

It sounds like maybe you're still on v0.2 which is EOL and not supported?

**Comment by gaurav3297** [comment] 2021-03-26 15:50
Hi bakerboy448, thanks for the quick response. I will check about the version as soon as I can. I'm in middle of building and moving to new NAS and therefore shut down the VMs for now. Hopefully I can get to it during the weekend.

**Comment by bakerboy448** [comment] 2021-04-16 17:04
Closing;  we can reopen if/when we get more info on this.

**Closed by bakerboy448** 2021-04-16 17:04 UTC
Labels: Status: Waiting for OP
