### ISSUE TITLE
Exclude movies with specific genre

### ISSUE THREAD

**Issue by pinkworld123** [Radarr/Radarr#7923] opened 2022-12-24 01:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Its very important to have exclude genre for example Horror. So no Horror movies are downloaded by default.
Also IMDB rating less then 5, do not download. 
This kind of filter are very helpful.
Thanks 

### Describe the solution you'd like

Genre Exclude filter list, so all the Genre selected in the list will not be downloaded.

### Describe alternatives you've considered

https://github.com/artagel/radarr-genre-filter
https://github.com/haijeploeg/excludarr

but they are not perfect. better to have this functionality in Radarr.

### Anything else?

Thanks

[AB#4533](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4533)

**Comment by bakerboy448** [comment] 2022-12-24 01:15
Effective Duplicate of https://github.com/Radarr/Radarr/issues/3578

**Closed by bakerboy448** 2022-12-24 01:15 UTC
Labels: Type: Feature Request, Status: Needs Triage
