### ISSUE TITLE
Multiple Filter switch

### ISSUE THREAD

**Issue by FlyingDutchGeek** [Radarr/Radarr#2883] opened 2018-07-12 15:30 UTC
As a user I like to select multiple filter options ("AND" switches) in movie library instead of the current single option filter. The selected filter should be defaulted/stored for next visit to movie library

Monitored: YES / NO / BOTH
Status: DOWNLOADED / MISSING / BOTH
Stage: ANNOUNCED / CINEMA / RELEASED / ALL

Result could be: show all monitored titles that are missing and are released, or show all unmonitored titles that are downloaded and released

**Comment by Qstick** [comment] 2018-07-14 02:49
dupe of #2011

**Closed by Qstick** 2018-07-14 02:49 UTC
