### ISSUE TITLE
[UI] Inline dropdowns on Movies page

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#2459] opened 2018-01-31 06:19 UTC
**What**

Ability, similar to nzbget, to change certain properties of a movie directly in the list without opening the movies page or its details popup. Nzbget allows changing things like category, status, priority directly inline through a dropdown.

Perhaps even extending it as far as merging the movie editor with the movies pages (list at least) and allow managing of movies in a similar fashion as nzbget, i.e. selecting multiple rows, changing properties through dropdowns that affect selected items, changing monitor status (#610).

![image](https://user-images.githubusercontent.com/494873/35607682-152fad68-06a1-11e8-87ad-2998c7315ce4.png)

**Why**

Less clicks and a lot quicker.
Managing large libraries becomes a lot easier.

Obviously this is low priority.

Also, what's the status on the new UI I see being mentioned in various issues. What's the approach of its development in regards to people's feedback. Are you waiting for Sonarr to update its UI first, whenever that is?

**Comment by galli-leo** [comment] 2018-01-31 10:10
Yeah this would definitely be in the new UI (movie editor merged with main list). Regardless the approach, we will definitely get feedback from you guys once we have something. We are probably not gonna „copy“ Sonarrs new UI, but making it look similar.

**Comment by galli-leo** [comment] 2018-02-07 11:37
Duplicate of #610

**Closed by galli-leo** 2018-02-07 11:37 UTC
