### ISSUE TITLE
Movie Quality not shown in Wanted/Cutoff Unmet Screen

### ISSUE THREAD

**Issue by RandallSG** [Radarr/Radarr#2416] opened 2018-01-13 00:08 UTC
**Description:**

Movie Quality Downloaded is not shown on the Wanted / Cutoff Unmet Screen, but only when sorting by Downloaded Quality.  It is shown when sorting by any other attribute.

**Radarr Version:**

Version
0.2.0.913
Mono Version
5.4.1.6 (2017-06/1f4613aa1ac Wed Oct 18 09:31:57 EDT 2017)

**Logs:**
![4df10599-6954-4030-85db-a6e5fe9e05b3](https://user-images.githubusercontent.com/32939039/34900209-97952bd0-f7c3-11e7-838b-4b483698860e.png)

![b796a2fa-c2f0-485b-ae95-4fe626787151](https://user-images.githubusercontent.com/32939039/34900239-df24cc58-f7c3-11e7-891e-708abcb98255.png)

Log is not applicable

**Comment by galli-leo** [comment] 2018-01-13 05:54
Duplicate of #2195

**Closed by galli-leo** 2018-01-13 05:54 UTC
