### ISSUE TITLE
Implement a hard-link system for alternative presentation of root folders

### ISSUE THREAD

**Issue by kernkraft235** [Radarr/Radarr#8754] opened 2023-07-02 13:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Depending on what I'm doing, organizing the file tree heirarchy and filename schema's in multiple ways would be useful for convenience and technical reasons

A system that works like Linux's "Persistent Block Device Naming" would be cool.

For example take a basic root -> title folder -> file structure
`/video/movies/{Movie_Title}/{Movie_CleanTitle}-{Release Year}-{Quality_Title}`
If you have a lot of movies that is a very large root with tons of single file folders.
You could manually hardlink that into:
`/video/movies-by/letter/{Movie_TitleFirstCharacter}/[the_movie_file]`

You could use this to selectively partiton plex libraries, like a plex user that uses a crap streaming stick causing you to transcode H265 could be given permissions to a library made of only x264 videos. Yea, you could just disable transcoding, but In my case I have people I'm willing to transcode for, but many users I am not. This would be easy from a UX perspective because radarr already has an naming format system in place

### Describe the solution you'd like

- Add an options page for alternative roots. The setup could be very similar to the existing setup under "Media Management" settings

### Describe alternatives you've considered

- Manually doing it and figuring out how to safely script it to run as a cron job. It gets harder when you want an alt root that has parameters that aren't in the origianl path/filename.

- Using ZFS deduplication and changing folder/file format settings, then mass editing library with new fake root, then move a copy of old root back, then mass edit again but dont move files this time
### Anything else?

Symlink could work too if you dont plan on modifying your primary root's path/filename

**Comment by bakerboy448** [comment] 2023-07-03 03:52
Duplicate of https://github.com/Radarr/Radarr/issues/153

**Closed by bakerboy448** 2023-07-03 03:52 UTC
Labels: Type: Feature Request, Status: Needs Triage
