### ISSUE TITLE
Show annonced instead of missing

### ISSUE THREAD

**Issue by almapavi** [Radarr/Radarr#5634] opened 2020-12-26 19:55 UTC
**Is your feature request related to a problem? Please describe.**
Not related to a problem, I think it is more the way the app is built.
**Describe the solution you'd like**
New movies not yet release but are "announced" are showing as missing. This should be described as something else such as announced. Missing should be for items that are available but not downloaded.

**Describe alternatives you've considered**
None available that I have tested. 

**Additional context**
Here is the screen shot of the new "Suicide Squad" movie that will be released in 2021. The item is flagged as announce but showing as missing:
https://imgur.com/a/A5NNeqs
https://imgur.com/a/IIS61nj

**Comment by bakerboy448** [comment] 2020-12-26 19:58
This is accurate based on your availability settings.

If you don't want a movie marked as missing, don't set your availability to announced.

There's some discussion regarding missing/wanted filters here:https://github.com/Radarr/Radarr/issues/4626

~Duplicate of #4626

**Closed by bakerboy448** 2020-12-26 19:58 UTC
Labels: feature request

**Comment by almapavi** [comment] 2020-12-26 20:00
Because the movie is not released! Why would put released for a movie that is not released?  The movie is scheduled for may 2021?

**Comment by austinwbest** [comment] 2020-12-26 20:06
> Because the movie is not released! Why would put released for a movie that is not released?  The movie is scheduled for may 2021?

Because you are not understanding the purpose of the option is all bud

That option tells radarr when to start looking for the title. You set it to announced as when the movie should show as available so therefor it shows as missing because it has been announced.

**Comment by bakerboy448** [comment] 2020-12-26 20:06
> When Radarr shall consider a movie is available..
> 
> Announced: Radarr shall consider movies available as soon as they are added to Radarr. This setting is recommended if you have good private trackers (or really good public ones, e.g. rarbg.to) that do not have fakes.
> InCinemas: Radarr shall consider movies available as soon as movies they hit cinemas. This option is not recommended.
> Physical / Web: Radarr shall consider movies available as soon as the Blu-ray is released. This option is recommended if your indexers contain fakes often.

Radarr is doing exactly what you tell it to do. In this case available = start monitoring

https://wiki.servarr.com/Radarr_Quick_Start_Guide#How_to_add_a_movie

**Comment by almapavi** [comment] 2020-12-26 20:21
I understand how the function works. It just for me, it doesn't make sense for two situations Physical/Web and Announced showing missing when really the only one I am interested in knowing is really missing is the Physical/Web version.   If I know it is released and it is missing I would like to investigate each.  

But anyway ...thanks.

**Comment by bakerboy448** [comment] 2020-12-26 20:39
If you don’t consider it missing until it is physically out then set your availability to release.

for further discussion, hop on discord
