### ISSUE TITLE
Kometa Metadata Files Agent

### ISSUE THREAD

**Issue by tylerreed19** [Radarr/Radarr#10419] opened 2024-09-12 05:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I like probably many other Plex users utilize Kometa. It would be great to do as Sonarr has done and include a Kometa Metadata option that adheres to the Kometa naming structure. The agent that produces the closest naming scheme currently is the Kodi option. It outputs `poster.jpg` and `fanart.jpg`. Kometa does have the ability to auto-rename any jpg with a ratio that would be considered the background fanart, and it will rename it to `background.jpg` but unfortunately that means that when Radarr refreshes that movies folder, it thinks it is now missing a fanart.jpg image so it downloads it alongside the renamed version.

### Describe the solution you'd like

A Kometa metadata setting for images. Their naming scheme and structure is as follows:

├── Movies
    ├── The Lord of the Rings The Fellowship of the Ring (2001)
    │   ├── poster.jpg
    │   └── background.jpg
    ├── The Lord of the Rings The Two Towers (2002)
    │   ├── poster.jpg
    │   └── background.jpg
    ├── The Lord of the Rings The Return of the King (2003)
    │   ├── poster.jpg
    │   └── background.jpg
    
    Here is their wiki naming scheme page: https://metamanager.wiki/en/latest/kometa/guides/assets/#asset-naming

### Describe alternatives you've considered

Just an option within the Kodi Metadata agent settings to name the fanart either **fanart.jpg** or **background.jpg**

Give Radarr a way to recognize if it has previously downloaded a fanart.jpg image so it does not re-download it due to it being now named background.jpg. 

### Anything else?

https://github.com/Sonarr/Sonarr/issues/6851

Also, I am not sure if it will make a big difference but every time I see Kometa reference either the poster art or the background art, the names are always lowercase. I have had Kometa download artwork before and it even saves them as `poster.jpg` and `background.jpg`. So far after the Kometa metadata image option in Sonarr, Kometa doesn't seem to have any issues with a capital P in Poster.jpg, but I am unsure how a capital B in Background.jpg will fare. So if possible, also for my OCD, have them all lowercase?

![Screenshot 2024-09-12 005931](https://github.com/user-attachments/assets/14357617-e925-4771-9ea8-4b6ad4758d1d)

**Comment by bakerboy448** [comment] 2024-09-12 10:46
Duplicate of https://github.com/Radarr/Radarr/issues/10059

**Closed by bakerboy448** 2024-09-12 10:46 UTC
Labels: Type: Feature Request, Status: Needs Triage
