### ISSUE TITLE
When I add a new movie from say upcoming, it scrolls back to top!

### ISSUE THREAD

**Issue by seitzbg** [Radarr/Radarr#3031] opened 2018-09-16 02:39 UTC
**Is your feature request related to a problem? Please describe.**
When I add a new movie from say upcoming, it scrolls back to top so I have to scroll back down to where I was in the list!

**Describe the solution you'd like**
Do not scroll back to the top after adding the movie.

**Describe alternatives you've considered**
None, ideas welcome.

**Additional context**
N/A.

**Comment by galli-leo** [comment] 2018-09-16 19:56
Duplicate of #2781

**Closed by galli-leo** 2018-09-16 19:56 UTC
