### ISSUE TITLE
Another "Import failing" - Radarr not using the correct path to downloads

### ISSUE THREAD

**Issue by mesiasgithub** [Radarr/Radarr#2349] opened 2017-12-15 17:45 UTC
I posted this in Reddit as well but no comments so I giving Github a try...

Something is off and I can't find where the issue lies... Radarr is not looking for the downloads in the correct path. Here is the log record:

Import failed, path does not exist or is not accessible by Radarr: /config/Downloads/complete/movies/...

For some reason Raddar is looking under the config folder instead of the path defined for the downloads folder. Here are the details of my setup:

- Both Sabnzbd and Radarr are installed dockers in an UNRAID box
- Sabnzbd path to downloads folder as defined in the docker: /downloads -> /mnt/user/appdata/sabnzbd/Downloads/complete/
- Raddar path to downloads folder as defined in the docker: /downloads -> /mnt/user/appdata/sabnzbd/Downloads/complete/
- Host for Sabnzbd in Raddar is the local IP address, "localhost" didn't work
- Permissions for completed downloads under Sabnzbd: 775
- File chmod mask in Raddar: 0775
- Any file browser within Raddar is able to see the correct downloads folder

I just noticed the same is happening with Sonarr. Both are fresh installs... using them for the first time.

Any idea where to look?

**Radarr Version:**

Version: 0.2.0.870
Mono Version: 5.4.1.6 (tarball Wed Nov 8 20:37:08 UTC 2017)
AppData directory: /config
Startup directory: /opt/radarr

**Logs:**

Import failed, path does not exist or is not accessible by Radarr: /config/Downloads/complete/movies/...

**Comment by galli-leo** [comment] 2017-12-17 14:59
What path is defined for the movie?

**Comment by weirdcrap** [comment] 2017-12-18 12:12
You will probably find the most help with getting your docker's configured correctly by asking over on the UnRAID forums, we don't bite: https://forums.lime-technology.com/

It sounds to me like the paths from your dockers are not matching up. /config is normally the appdata directory on your cache drive.

What SAB category do you have defined in Radarr to pass to SAB and what is it's path?

**Comment by krin-san** [comment] 2018-02-03 17:18
Noticed the same issue with Radarr 0.2.0.933 (nightly).
Manual import with movie title defined without the quality. For some reason Radarr moved that file with renaming using russian localized title. When moving was finished it produced the following error (and continues to produce it twice a minute) coz' it tries to find movie file using original name.
```
Import failed, path does not exist or is not accessible by Radarr: /media/downloads/_MOVIES/hqf-riddick.1080.mkv
```
Movie: https://www.themoviedb.org/movie/2789-the-chronicles-of-riddick
Also known as: **/ The Chronicles of Riddick ( / David Twohy) [, Pitch Black 2, The Chronicles of Riddick and The Chronicles of Riddick: The Director's Cut.**
Profile: **HD - 720p/7080p**
Downloaded file path: `/media/downloads/_MOVIES/hqf-riddick.1080.mkv`
Destination file path: `/media/movies/The Chronicles of Riddick (2004)/Хроники Риддика (2004) .mkv`

**Comment by galli-leo** [comment] 2018-02-03 17:26
@krin-san Does it correclty show the `/media/movies/The Chronicles of Riddick (2004)/Хроники Риддика (2004) .mkv` file under the files tab (after a browser refresh)? If so it's probably throwing the above error, because the dl client is still telling Radarr it has a file called `/media/downloads/_MOVIES/hqf-riddick.1080.mkv` downloaded and I would suggest clearing out that item from your dl client.

**Comment by galli-leo** [comment] 2018-02-03 17:27
Also the original issue needs more information so closing this until we get that info.

**Closed by galli-leo** 2018-02-03 17:27 UTC
Labels: information needed, support

**Comment by krin-san** [comment] 2018-02-03 19:02
@galli-leo, didn't noticed that unfortunetely.
Other movie with title **and** quality defined was successfully imported. Will try to gather more info when reproduce that again.
