### ISSUE TITLE
[Feature request] Allow hiding of deleted movies.

### ISSUE THREAD

**Issue by darzur** [Radarr/Radarr#1298] opened 2017-03-31 16:51 UTC
Please allow hiding movies that were downloaded and then deleted. Now such movies have "Not monitored" status but there is no way of removing them from main movies screen.

**Comment by galli-leo** [comment] 2017-04-01 10:54
Just filter by monitored?

**Comment by darzur** [comment] 2017-04-01 11:02
Then see all monitored regardless if downloaded or not. My goal is to see missing (never downloaded) only.

**Comment by galli-leo** [comment] 2017-04-01 11:43
IIRC there's a filter for that too.

**Comment by darzur** [comment] 2017-04-01 12:51
No, there isn't. Or at least have no idea how to enable it.

**Comment by galli-leo** [comment] 2017-04-01 13:24
<img width="258" alt="Missing Only" src="https://cloud.githubusercontent.com/assets/5339762/24579118/3cb11798-16ef-11e7-9b62-bcbfcef4160e.png">
Did you try this one?

**Comment by darzur** [comment] 2017-04-01 13:28
That is the setting I was referring to. It shows all missing movies including those deleted and therefore not monitored. I'd like to see here only those not yet downloaded.

**Comment by geogolem** [comment] 2017-04-01 16:46
a feature like this was requested in the past: http://feathub.com/Radarr/Radarr/+56

The issue is, you want "Monitored & Missing"....  I believe you can filter by this currently by going to "Wanted --> Missing" and Filtering by Monitored....

but I get what you mean.

**Comment by 4getit** [comment] 2017-04-01 17:17
> Please allow hiding movies that were downloaded and then deleted. 
This works with the second button from the left 'Monitored Only'. Not the 3rd.
When a movie is downloaded and then deleted (and you have the 'Ignore Deleted Movies' option turned on), they're not there anymore after the next disk scan.
After the disk scan, Radarr sees that the movie is no longer there and flips it from the download status to 'Not Monitored'.

**Comment by darzur** [comment] 2017-04-01 18:13
Still not what I want. "Monitored only" shows all monitored movies whether they were downloaded or not. I want to see only missing movies and by that I mean movies that were never downloaded. 

@geogolem what do you mean by "going to "Wanted --> Missing" and Filtering by Monitored...."?

**Comment by 4getit** [comment] 2017-04-01 18:16
No they don't.
If you have the 'Ignore Deleted Movies' option turned on in Settings -> Media Management, all downloaded movies will change to Not Monitored once removed from disk.
I think that is what you asked in your initial question.

**Comment by geogolem** [comment] 2017-04-01 18:17
![image](https://cloud.githubusercontent.com/assets/23205277/24581247/e25b42f4-16e5-11e7-81da-c8dab162d82e.png)

**Comment by geogolem** [comment] 2017-04-01 18:19
@4getit: The monitored status does change... but if you filter by "Monitored only" You will see all monitored movies regardless of if they have been downloaded or not, downloaded and deleted or not..

@darzur wants to be able to see only movies that are monitored and missing, that werent previously downloaded and subsequently deleted... I believe the only way to accomplish this currently is via the screenshot i posted in the previous comment.... In order to accomplish this on the main movie index page we would need to have another filter specific to this situation or implement a more robust filtering setup... such as: http://feathub.com/Radarr/Radarr/+56

**Comment by 4getit** [comment] 2017-04-01 18:25
I guess I'm confused.
His original question says that his deleted movies show as 'Not Monitored'. So it seems he has 'Ignore Deleted Movies' turned on.
He wants to hide those. The second button does that.

**Comment by darzur** [comment] 2017-04-01 18:26
Now I feel completely stupid. I meant "Movie" tab and didn't even noticed "Wanted" tab. It looks like it is what I was looking for so this request can be closed.

@4getit you're right - I have  'Ignore Deleted Movies' turned on. In my ignorance just didn't noticed "Wanted" tab. Sorry for that.

**Comment by geogolem** [comment] 2017-04-01 18:28
@4getit : yes -- According to his original post --> its not as clear. By the 7th post in this thread it is more clear --> he wants to be able to filter "Missing Only" but excluding any movies that were previously downloaded.

Using the "Ignore Deleted Movies"option marks those deleted movies as "Not Monitored" .... but, even after enabling that he would still need to use a filter "Missing and Monitored" to get what he wants.

**Comment by geogolem** [comment] 2017-04-01 18:29
Great -- I'll close this issue --> If more discussion is required about making the filters more flexible we can refer to: http://feathub.com/Radarr/Radarr/+56

**Closed by geogolem** 2017-04-01 18:29 UTC
