### ISSUE TITLE
Drone Factory not running on completion of download

### ISSUE THREAD

**Issue by scope999** [Radarr/Radarr#566] opened 2017-02-01 19:27 UTC
Hi the Drone Factory does not seem to be running as set. Completed downloads do not get renamed / moved. Set to run every one minute. Windows 10. Does work when Drone Factory is run manually from Wanted but download stays in Activity and the following error occurs (note there is no directory C:\projects):

Message
MovieMissingModule failed while processing [MovieDownloadedEvent]: Object reference not set to an instance of an object.

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2.BroadcastResourceChange(ModelAction action, Int32 id) in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:line 38
   at NzbDrone.Api.Wanted.MovieMissingModule.Handle(MovieDownloadedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:line 74
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56
Close
Radarr Ver. 0.2.0.267
develop

**Comment by WallaWallaWA** [comment] 2017-02-02 04:46
See Closed Issue #228 Drone factory interval input not saving. I'm still experiencing the same situation you are, that is I need to go to Wanted and click the Rescan Drone Factory Folder button to have Radarr actually rename/move the completed movie. Running version 0.2.0.267 - Jan 30 2017 on Windows 10.

**Comment by zductiv** [comment] 2017-02-03 06:44
The drone factory isn't supposed to run when a download completes is it?

The drone factory folder is just an optional folder than can be set to look for movie files and it should run on the drone factory interval set. You should be able to have renaming working without even having a drone factory folder set. Not to say there isn't an issue with the MovieDownloadedEvent though.

**Comment by scope999** [comment] 2017-02-03 07:22
I have tried to have the downloader(SABnzbd) trigger the rename by setting the interval to 0 but this did not work. In Sonarr I have to use the dronefactory as well but it works. The downloader is set to move the completed file to the dronefactory folder which triggers the rename.

**Comment by crafty35a** [comment] 2017-02-03 13:10
@zductiv The point is, the drone factory is never scanned regardless of what you set the interval to (at least, it wasn't for me last time I checked). Normal download handling works fine.

**Comment by jeremyscalpello** [comment] 2017-02-03 16:25
Having the same issue. The Drone Factory folder is not scanned automatically every 1 minute (despite the interval being set to 1 minute) unless the re-scan button in the "Wanted" section is clicked.

**Comment by scope999** [comment] 2017-02-03 21:49
Hi guys I got Radarr to work by using the api instead of drone factory. I did it by not forcing sabnzbd to move the completed file to the drone factory folder by deleting the folder from the category in sabnzbd and setting the interval to 0. Now the api handles the import on completion properly without needing the drone factory.

**Comment by zductiv** [comment] 2017-02-04 02:27
Download client history items that are moved to the drone factory folder being ignored is expected behaviour if anyone else has it set up like that.

**Comment by crafty35a** [comment] 2017-02-05 14:43
@zductiv - is this the case even if you added the items to your download client outside of Radarr?

**Comment by d2dyno** [comment] 2017-02-08 08:23
Having the same issue with drone folder. Only imports when I manually trigger a scan.

**Comment by kingwoftam** [comment] 2017-02-20 01:37
I've got the same issue with Radarr installed on my QNAP. Doesn't do it automatically, only when I manually trigger a scan.

**Comment by chicaneau** [comment] 2017-03-02 01:18
+1 from me on windows, drone factory not scanning automatically, have to force manual scan. Also noticed that a specific movie Snatch would only import when i changed the filename to 'snatch.2000......mkv' instead of 'snatch......mkv '

**Comment by d4rk22** [comment] 2017-03-06 06:12
Ubuntu 16.04 - Drone factory not running at set interval. Works as expected when selecting "Rescan Drone Factory Folder".

**Comment by eriksneff** [comment] 2017-03-08 21:01
MacOS 10.12 Sierra - Drone factory not running at set interval. Works *mostly* as expected when going to Wanted and clicking "Rescan Drone Factory Folder". I say mostly because I would expect/like to see something in the logs put there by drone factory execution. I get that it would be really noisy to have it log every time it runs every minute, so maybe just log things that were successfully or unsuccessfully processed? That would help the debugging effort as well. As it stands now, I have to rely on the Activity>History tab to see successes, and the System>Logs area for possible issues with it not running, since I can't see directly when and if it actually ran. Seems like somewhere in there is an elegant solution.

**Comment by fedoranimus** [comment] 2017-03-08 21:09
Closed by 5c22d0b61d651b2c910d5ff3001cd7848e58588d

**Closed by fedoranimus** 2017-03-08 21:09 UTC
Labels: bug, priority:medium
