### ISSUE TITLE
Increase Quality Profile Slider Sizes

### ISSUE THREAD

**Issue by InSearchOfTh1ngs** [Radarr/Radarr#1969] opened 2017-08-20 14:52 UTC
With 4K Remux files finding their way into the wild radarr is having difficulty determining the difference betweek 1080P BluRay remux vs 2160p BluRay remux base don file size as the sliders range max out at 30GBs and then just defaults to unlimited.

Can the range of the sliders be increased so that quality profiles work properly for the next generation of media quality?

**Comment by mrzoops** [comment] 2018-04-04 16:41
Is there a way to manually set the quality size outside of the gui? 20gb is the max I can set to, but I would like something like 50gb.

**Comment by galli-leo** [comment] 2018-04-06 08:28
Duplicate of #978

**Closed by galli-leo** 2018-04-06 08:28 UTC
Labels: enhancement, ui
