### ISSUE TITLE
Click through Collection Link from Movie page.

### ISSUE THREAD

**Issue by NaPurHab** [Radarr/Radarr#10446] opened 2024-09-17 06:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently when there is a collection on a Movie Page, there is a tag that can be turned on/off.  After that is 'Collection_Name Collection'.  If I want to view the collection, I need to goto Movie, Collections,  then scroll down to the Collection.

### Describe the solution you'd like

Simply make the 'Collection_Name Collection' after the Tag into a Link to the collection. There by removing tedious steps to get to the collection.

### Describe alternatives you've considered

N/A, as a Link is as simple as it gets.

**Comment by bakerboy448** [comment] 2024-09-17 10:37
Duplicate of https://github.com/Radarr/Radarr/issues/9235

**Closed by bakerboy448** 2024-09-17 10:37 UTC
Labels: Type: Feature Request, Status: Needs Triage
