### ISSUE TITLE
Multiple Size Limits for Quality Definitions

### ISSUE THREAD

**Issue by exchronos** [Radarr/Radarr#1510] opened 2017-05-11 02:55 UTC
Hello! Thank you for your work on such a great tool. I'd like to submit a feature request / enhancement for you to consider.

As it is now, quality definitions can be assigned a single cutoff for min/max size limits for that defintion. Ideally, there could be multiple size limits per quality definition.

So...

BluRay-1080p: (0-10gb)
...could be...
BluRay-1080p: low (0-3gb) high (3-10gb)

...this would give someone the ability to filter low quality versions of a 1080p BluRay from a high quality version of a 1080p BluRay. The tagging system, while useful, would not be as efficient to the end-user for such distinctions of file quality.

As it is right now, differentiating between varying qualities of releases within a quality definition is not easily done. I hope my proposal would be easy to implement, and would make this great tool all the more awesome.

**Comment by galli-leo** [comment] 2017-05-11 10:21
I have this planned for the "profilinator", where you could specify different quality size definitions for different profiles and mark certain size ranges as needed / some as preferred.

**Comment by exchronos** [comment] 2017-05-11 11:47
Oh cool!

Sorry if this request was redundant then.. I looked around but not enough I guess.

I have a bit of coding experience, I'd like to help on this one if I could. I can't make any promises though, I'm buried in a renovation for another month or two.

**Comment by galli-leo** [comment] 2017-05-11 12:11
@exchronos Well I don't plan on implementing that anytime soon, since I have to completely rework how profiles work :)

**Comment by kyse** [comment] 2017-11-12 07:47
Just adding in another thought on a thread they dont plan on working on anytime soon.  :)

Would be awesome to be able to specify specific quality levels I don't want to keep, along with the thought of letting me grab both 1080p, and 4k, etc.

Also 1080p vs 1080p 3d?  Not sure I saw a parsing flag for 3d in the settings last I looked.

**Comment by galli-leo** [comment] 2018-02-06 22:56
Duplicate of #2433 

While technically not a duplicate of that issue. Most should be solved by that issue, using custom tags and restricting releases to certain release groups, etc.

I might even add the option to have the same quality twice with different size limits.

**Closed by galli-leo** 2018-02-06 22:56 UTC
