### ISSUE TITLE
v3 Feature Request - Sort Root Folders

### ISSUE THREAD

**Issue by wharris623** [Radarr/Radarr#5253] opened 2020-10-23 19:42 UTC
Hey guys, not a huge thing, and hell if I knew what table it was I could probably stumble my way there and get it sorted, but would love to be able to have Root Folders sorted when choosing where to store data.  Not sure how hard that would be or if it would be a huge issue but if it's a popular idea, that would be awesome!  

Thanks in advance and keep up the good work!

**Comment by austinwbest** [comment] 2020-10-23 21:53
Could you fill out the template you nuked? Version, screenshots, etc would be helpful so no guessing is needed :)

**Comment by wharris623** [comment] 2020-10-24 00:56
![image](https://user-images.githubusercontent.com/56494452/97064151-cddc3c00-1558-11eb-8f59-9a434751168d.png)

Like I said not a huge thing, it's not even an issue, just a feature request.  any v3 build, would love to be able to sort the table that contains the data as shown in the screen snip, so when going to add a new movie it would present the Root Folders list in an organized format vs just having them as how they were added.

If you really want me to fill the template I can close this request and go create a new one but that seems like a waste of everyones time.

**Comment by austinwbest** [comment] 2020-10-24 01:49
No, it's fine.. I gotcha :)

**Comment by bakerboy448** [comment] 2020-11-13 04:23
Duplicate of #3371

**Closed by bakerboy448** 2020-11-13 04:23 UTC
Labels: feature request
