### ISSUE TITLE
Fail hardlinks instead of falling back to copying

### ISSUE THREAD

**Issue by daniel-sousa-me** [Radarr/Radarr#9357] opened 2023-10-31 12:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If I have downloaded the file to a different drive, radarr will start copying it (because hardlinking is not possible).

### Describe the solution you'd like

I think by default it should just fail instead of trying to copy, but there could be a setting for the fallback.

It should also be easy to implement a version that uses symlinks instead when they're available.

### Describe alternatives you've considered

I don't really care for complicated alternatives, since this happened because of a mistake of mine. I just don't want it to fallback by occupying extra space.

### Anything else?

I don't know C♯ or .Net/mono, but I could try this if no one else is interested.

**Comment by bakerboy448** [comment] 2023-10-31 12:32
- duplicate of several issues
- no plans for symlinks support
- This can already be accomplished by end users using the import via script functionality

**Closed by bakerboy448** 2023-10-31 12:32 UTC
Labels: Type: Feature Request, Status: Needs Triage
