### ISSUE TITLE
Movie Naming settings not saving

### ISSUE THREAD

**Issue by macbean101** [Radarr/Radarr#376] opened 2017-01-22 06:32 UTC
I looked but didn't see any report here although issue #228 seems to be similar.  

Under Settings, Media Management, none of the Movie Naming settings save when changed.  

you can add quality, replace spaces, any of these and hit save.  it says it saves but when you go back after browsing through Radarr a bit, they are back at default.

**Comment by simonk83** [comment] 2017-01-22 08:47
It does take a second or three to populate the "example" below the renamer.  Maybe try waiting for that to update before you hit save?

**Comment by fedoranimus** [comment] 2017-01-22 14:47
I cannot reproduce this; closing.

**Comment by macbean101** [comment] 2017-01-22 15:07
any suggestions on what to look for to fix it on my system then?  I'm running windows 10, 0.2.0.196, and no matter what i've done, none of the media management settings stick when I change them.

**Comment by macbean101** [comment] 2017-01-22 15:17
I enabled trace and see these lines that look relevant.


17-1-22 17:14:15.0|Trace|Http|Res: 6284 [GET] /api/config/naming/samples??renameEpisodes=true&replaceIllegalCharacters=true&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1&standardEpisodeFormat=%7BSeries+Title%7D+S%7Bseason%3A00%7DE%7Bepisode%3A00%7D+%7BEpisode+Title%7D+%7BQuality+Title%7D&dailyEpisodeFormat=%7BSeries+Title%7D+%7BAir-Date%7D+%7BEpisode+Title%7D+%7BQuality+Title%7D&animeEpisodeFormat=%7BSeries+Title%7D+S%7Bseason%3A00%7DE%7Bepisode%3A00%7D+%7BEpisode+Title%7D+%7BQuality+Title%7D: 200.OK (130 ms)
17-1-22 17:14:15.0|Trace|Owin|SQLite error (5): database is locked

I DO get the message indicating the settings were saved.  

And as far as I can tell, all other settings get saved properly.

**Comment by zbuttram** [comment] 2017-02-22 02:23
FWIW I had this issue too, but only with advanced settings set to hidden.

**Comment by macbean101** [comment] 2017-02-22 05:17
I've been meaning to update this with that bit of info.  My standard movie naming settings still do nothing but when showing the hidden settings, everything works fine.

**Comment by poppinsmac** [comment] 2017-02-24 03:59
I am having this issue as well. The changes save but upon changing to any other item and back (clicking system and back to setting) replace spaces is back to off.

**Comment by emerik78** [comment] 2017-03-11 00:21
I am also have this issue.  Every time I move to a different item, the Rename Movies setting is moved back to "No".  There is also no notifications that my settings have been saved.

**Comment by vexersa** [comment] 2017-03-31 05:37
Same issue here.

**Comment by galli-leo** [comment] 2017-04-01 11:43
@vexersa Can you try and set a page size under Settings -> UI?

**Comment by vexersa** [comment] 2017-04-01 12:39
Soted it out. Some sort of issue with Chrome. I was able to save
successfully in Edge....

**Comment by galli-leo** [comment] 2017-04-01 13:24
@vexersa Gotcha. Works fine for me though on Chrome. Strange.

**Comment by animosity22** [comment] 2017-04-06 00:25
So, it depends.

If you try to toggle remove spaces and your title has spaces in it or something else has spaces, it won't save.

You have to make sure it's valid I guess. Once I figured those bits out, it saved for me without issue.

**Comment by adamgoldberg** [comment] 2017-05-20 15:52
I have the same problem.  

Interestingly, "remove spaces" is NOT in the Advanced Settings.  I wonder if that might have something to do with it (the remove spaces option is not part of the advanced options, and only the advanced options are saved [under some conditions??])

**Comment by adamgoldberg** [comment] 2017-05-20 16:01
Ok, I don't know WTF I'm doing, but::
/src/NzbDrone.Api/Config/MediaManagementConfigResource.cs

makes mention of the "advanced options", but does NOT make mention of anything to do with "remove spaces."  Is something missing in this file?

**Comment by galli-leo** [comment] 2017-05-20 16:16
@adamgoldberg These settings are client side and I finally found out why they aren't saving. We actually never implemented the non advanced options 😬

**Comment by adamgoldberg** [comment] 2017-05-20 16:44
Ha.  Well, I hope I helped.

**Closed** 2017-05-21 16:10 UTC
Labels: bug, priority:low, under investigation
