### ISSUE TITLE
API: /movie returns all movies although tmdbId is provided

### ISSUE THREAD

**Issue by woiza** [Radarr/Radarr#6086] opened 2021-03-21 16:02 UTC
The followin Go code prints 10, which is the amount of movies I have in my Radarr database.  Shouldn't it be 1 because tmdbid is provided?

````go
movies, _, _ := client.MovieApi.GetMovie(ctx, &radarr.MovieApiGetMovieOpts{
	TmdbId: optional.NewInt32(command.movie.TmdbId),
})
log.Printf("movies (%d)", len(movies))
````

The client code is autogenerated with swagger codegen (Radarr swag file). Other API calls with this client work as expected and `command.movie.TmdbId` has the correct value/tmdbid.

How can I get only the single movie I am looking for (based on tmdbid)?

**Comment by ta264** [comment] 2021-03-21 16:28
Can you replicate with a curl command? It's not obvious to me what call that is doing... It's also quite possible the swagger docs are not quite right

**Comment by woiza** [comment] 2021-03-21 17:33
I used curl and it looks like either the swagger docs are wrong or the autogenerated code.

````bash
$ curl -X GET "http://n2:7878/api/v3/movie" -H "accept: application/json" -H "X-Api-Key: APIKEY"
````
returns a list wiht all of my movies

````bash
$ curl -X GET "http://n2:7878/api/v3/movie?tmdbId=185567" -H "accept: application/json" -H "X-Api-Key: APIKEY"
````
returns only one movie/json which is the expected and correct behavior.

**Comment by ta264** [comment] 2021-03-21 17:46
The swagger docs look ok to me. If you turn radarr logs up to trace it'll show you the request coming in from your app.

Closing this as not a bug. If you need more help with the API, please join the discord channel.

**Closed by ta264** 2021-03-21 17:46 UTC
Labels: Type: Bug
