### ISSUE TITLE
[Feature Request] A potentially different way of handling preferred terms

### ISSUE THREAD

**Issue by Zer0t3ch** [Radarr/Radarr#1649] opened 2017-06-10 13:03 UTC
[This](https://github.com/Sonarr/Sonarr/issues/385#issuecomment-299051872) is what a Sonarr dev is planning to implement, and it looks like it could be a great change from how Radarr currently handles preferred terms.

**Comment by galli-leo** [comment] 2017-06-10 13:12
Yeah, this is the future plan for preferred words for Radarr as well, but for now the simple method works as well. (Btw. you can add words twice, to get the "2 score". e.g. Adding DTS four times, should score a release with only DTS higher, then a release with e.g. h265 - twice in your preferred words.)

**Comment by galli-leo** [comment] 2018-02-20 22:54
Duplicate of #2433

**Closed by galli-leo** 2018-02-20 22:54 UTC
Labels: feature request
