### ISSUE TITLE
Bulk edit defaults to "Monitored: NO"

### ISSUE THREAD

**Issue by Zer0t3ch** [Radarr/Radarr#1633] opened 2017-06-06 12:50 UTC
**Radarr Version:** 0.2.0.696

It's possible this is intended, but it would seem to be a flaw from my view. Anyone (me) who goes to do a quick bulk edit on one field (root folder) of their library without looking at the other fields will accidentally un-monitor everything, which seems unintended, at least for the end user.

**Comment by galli-leo** [comment] 2017-06-06 13:13
Defaults to "No change" for me. Can you try clearing your cache and cookies?

**Comment by Zer0t3ch** [comment] 2017-06-10 12:59
Cleared cache as well as cookies and it persists. (Definitely were cleared, my preferred view method [table] was reset to default)

**Comment by galli-leo** [comment] 2017-06-10 13:02
Are you sure it says No and not No change (Text is probably cut off)?

**Comment by hotio** [comment] 2017-06-14 15:24
9/10 he's looking at this:
![naamloos](https://user-images.githubusercontent.com/26902309/27140571-2ace7928-5126-11e7-87b0-640c2e874a6a.png)

Probably safe to close this issue, since he can't be bothered either to reply...

**Comment by onedr0p** [comment] 2017-06-14 16:50
I can confirm it defaults to 'No change'

**Closed by onedr0p** 2017-06-14 16:50 UTC
Labels: bug, cannot reproduce

**Comment by Zer0t3ch** [comment] 2017-06-30 11:20
Whoops. I don't have GitHub notifications on and didn't see this convo going. I actually figured this a couple weeks ago and meant to come on and close the issue, but forgot. My bad.
