### ISSUE TITLE
Ability to search Filename. The "Path" filter only searches BasePath not the full path. 

### ISSUE THREAD

**Issue by ChristianMalazarte** [Radarr/Radarr#9606] opened 2024-01-14 12:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I was trying to search for release group in Radarr since there is no Release Group filter like in Sonarr.

### Describe the solution you'd like

If this Filter was changed to full path search or if a "Full Path" or "Filename" filter was added, we could search for various other things like custom format tags or qualities like "1080p" "x264" "HDR" that are not currently available to be searched in Radarr. 

This behavior is the same in Sonarr, but at least Sonarr has a Release Group filter. It would be nice if you could search filenames in Sonarr as well because it would open up possibilities, like searching episode titles and custom format tags.

### Describe alternatives you've considered

Outlined above.

### Anything else?

No

**Comment by bakerboy448** [comment] 2024-01-14 13:38
Duplicate of numerous issues
No plans for filtering on movie file properties until after eventually multiple file support is introduced

**Closed by bakerboy448** 2024-01-14 13:38 UTC
Labels: Type: Feature Request, Status: Needs Triage
