### ISSUE TITLE
Loading mutiple movies in tabs is super slow

### ISSUE THREAD

**Issue by seitzbg** [Radarr/Radarr#9227] opened 2023-09-30 23:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If I open multiple tabs with movies (so I can go tab by tab and edit or search for a movie manually), the cpu usage of Radarr shoots up and tab loads can take 20-45 seconds to complete.

The tab urls would be something like: `/movie/2357`

The offending API calls seem to be `/api/v3/movie` and `/api/v3/collection`

```
2023-09-30 01:16:29.1|Trace|Http|Res: 17463 [GET] /api/v3/movie: 200.OK (21667 ms)
2023-09-30 01:16:29.1|Debug|Api|[GET] /api/v3/movie: 200.OK (21667 ms)
2023-09-30 01:16:29.1|Trace|Http|Res: 17486 [GET] /api/v3/movie: 200.OK (21308 ms)
2023-09-30 01:16:29.1|Debug|Api|[GET] /api/v3/movie: 200.OK (21308 ms)
2023-09-30 01:16:29.2|Trace|Http|Res: 17476 [GET] /api/v3/movie: 200.OK (21629 ms)
2023-09-30 01:16:29.2|Debug|Api|[GET] /api/v3/movie: 200.OK (21629 ms)
2023-09-30 01:16:29.2|Trace|Http|Res: 17516 [GET] /api/v3/movie: 200.OK (20093 ms)
2023-09-30 01:16:29.2|Debug|Api|[GET] /api/v3/movie: 200.OK (20093 ms)
2023-09-30 01:16:29.2|Trace|Http|Res: 17500 [GET] /api/v3/movie: 200.OK (20811 ms)
2023-09-30 01:16:29.2|Debug|Api|[GET] /api/v3/movie: 200.OK (20811 ms)
2023-09-30 01:16:29.4|Trace|Http|Res: 17531 [GET] /api/v3/movie: 200.OK (19798 ms)
2023-09-30 01:16:29.4|Debug|Api|[GET] /api/v3/movie: 200.OK (19798 ms)
2023-09-30 01:16:29.6|Trace|Http|Res: 17546 [GET] /api/v3/movie: 200.OK (18506 ms)
2023-09-30 01:16:29.6|Debug|Api|[GET] /api/v3/movie: 200.OK (18506 ms)
```

This is even slow on a single movie or radarr index page load. (2-4 seconds here)

![slow](https://github.com/Radarr/Radarr/assets/171158/468e36af-80e3-4582-82ee-139535e39cf0)

### Expected Behavior

Smooth sub second page loads.

### Steps To Reproduce

Open Radarr index page.  
Middle click 5-10 (or more for delay and load failures) movies into new tabs.

### Environment

```markdown
- OS: Ubuntu-23.04
- Radarr: 5.0.2.8103
- Docker Install: No
- Using Reverse Proxy: Caddy V2 
- Browser: Firefox
- Database: Sqlite3 and Postgres (both perform roughly the same with this bug)
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

Attached logs

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/12775737/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/12775738/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2023-10-01 01:31
Not a bug; every web Ui instance loads the movies and collection apis and seems your system can't handle simultaneous database calls with significant speed 
 
 @Qstick defer to you on closing, but don't see anything to really optimize here; not exactly what radarr's usecase is, no?

**Comment by seitzbg** [comment] 2023-10-01 02:32
It's possible the new tab while working on entries isn't the use case, that's fair.  But what would be needed for a 4000 entry collection to load fast?  

This is my hardware:

```Model Number:                       Micron_7300_MTFDHBE7T6TDF
Total NVM Capacity:                 7,681,501,126,656 [7.68 TB]

processor       : 79
model name      : Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz

$ free -h
               total        used        free      shared  buff/cache   available
Mem:           282Gi       147Gi       121Gi       504Mi        17Gi       135Gi
Swap:             0B          0B          0B```

**Comment by seitzbg** [comment] 2023-10-01 02:42
Turned on slow query logging in Postgres as well:  (To note, this happened with sqlite too)

```2023-10-01 02:41:32.412 UTC [9731] radarr@radarr_main LOG:  duration: 6144.774 ms  execute <unnamed>: SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
         FROM "Movies"
        LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
        LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")

2023-10-01 02:41:33.499 UTC [9734] radarr@radarr_main LOG:  duration: 7267.550 ms  execute <unnamed>: SELECT "MovieMetadata".*, "MovieTranslations".*
         FROM "MovieMetadata"
        LEFT JOIN "MovieTranslations" ON ("MovieMetadata"."Id" = "MovieTranslations"."MovieMetadataId")
         WHERE ("MovieMetadata"."CollectionTmdbId" > $1)

2023-10-01 02:41:33.499 UTC [9734] radarr@radarr_main DETAIL:  parameters: $1 = '0'
2023-10-01 02:41:34.139 UTC [9745] radarr@radarr_main LOG:  duration: 7011.082 ms  execute <unnamed>: SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
         FROM "Movies"
        LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
        LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")

2023-10-01 02:41:36.458 UTC [9733] radarr@radarr_main LOG:  duration: 9616.147 ms  execute <unnamed>: SELECT "MovieMetadata".*, "MovieTranslations".*
         FROM "MovieMetadata"
        LEFT JOIN "MovieTranslations" ON ("MovieMetadata"."Id" = "MovieTranslations"."MovieMetadataId")
         WHERE ("MovieMetadata"."CollectionTmdbId" > $1)

2023-10-01 02:41:36.458 UTC [9733] radarr@radarr_main DETAIL:  parameters: $1 = '0'
2023-10-01 02:41:36.737 UTC [9746] radarr@radarr_main LOG:  duration: 8261.641 ms  execute <unnamed>: SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
         FROM "Movies"
        LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
        LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")

2023-10-01 02:41:37.149 UTC [9744] radarr@radarr_main LOG:  duration: 8717.598 ms  execute <unnamed>: SELECT "MovieMetadata".*, "MovieTranslations".*
         FROM "MovieMetadata"
        LEFT JOIN "MovieTranslations" ON ("MovieMetadata"."Id" = "MovieTranslations"."MovieMetadataId")
         WHERE ("MovieMetadata"."CollectionTmdbId" > $1)

2023-10-01 02:41:37.149 UTC [9744] radarr@radarr_main DETAIL:  parameters: $1 = '0'
2023-10-01 02:41:37.917 UTC [9732] radarr@radarr_main LOG:  duration: 9171.054 ms  execute <unnamed>: SELECT "MovieMetadata".*, "MovieTranslations".*
         FROM "MovieMetadata"
        LEFT JOIN "MovieTranslations" ON ("MovieMetadata"."Id" = "MovieTranslations"."MovieMetadataId")
         WHERE ("MovieMetadata"."CollectionTmdbId" > $1)

2023-10-01 02:41:37.917 UTC [9732] radarr@radarr_main DETAIL:  parameters: $1 = '0'
2023-10-01 02:41:37.944 UTC [9748] radarr@radarr_main LOG:  duration: 7129.794 ms  execute <unnamed>: SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
         FROM "Movies"
        LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
        LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")

2023-10-01 02:41:38.018 UTC [9749] radarr@radarr_main LOG:  duration: 7149.786 ms  execute <unnamed>: SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
         FROM "Movies"
        LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
        LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")```

**Comment by seitzbg** [comment] 2023-10-01 02:58
Is it possible there are missing indexes in the DB?

```radarr_main=# explain analyze SELECT "MovieMetadata".*, "MovieTranslations".*
         FROM "MovieMetadata"
        LEFT JOIN "MovieTranslations" ON ("MovieMetadata"."Id" = "MovieTranslations"."MovieMetadataId")
         WHERE ("MovieMetadata"."CollectionTmdbId" > 0);
                                                                          QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Right Join  (cost=710.98..10023.30 rows=35263 width=1711) (actual time=3.189..56.660 rows=32158 loops=1)
   Hash Cond: ("MovieTranslations"."MovieMetadataId" = "MovieMetadata"."Id")
   ->  Seq Scan on "MovieTranslations"  (cost=0.00..9040.90 rows=103290 width=574) (actual time=0.009..38.498 rows=103290 loops=1)
   ->  Hash  (cost=693.16..693.16 rows=1426 width=1137) (actual time=3.158..3.160 rows=1428 loops=1)
         Buckets: 2048  Batches: 1  Memory Usage: 1650kB
         ->  Bitmap Heap Scan on "MovieMetadata"  (cost=27.33..693.16 rows=1426 width=1137) (actual time=0.146..2.015 rows=1428 loops=1)
               Recheck Cond: ("CollectionTmdbId" > 0)
               Heap Blocks: exact=422
               ->  Bitmap Index Scan on "IX_MovieMetadata_CollectionTmdbId"  (cost=0.00..26.98 rows=1426 width=0) (actual time=0.088..0.089 rows=1430 loops=1)
                     Index Cond: ("CollectionTmdbId" > 0)
 Planning Time: 0.569 ms
 Execution Time: 57.448 ms
(12 rows)```

**Comment by seitzbg** [comment] 2023-10-01 03:37
Not sure what else could cause it tbh, the DB looks to have proper indexes.

**Comment by Qstick** [comment] 2023-10-08 15:03
Test on latest nightly please

**Comment by seitzbg** [comment] 2023-10-09 04:54
Oct 7 code does seem faster!

**Comment by dkrahmer** [comment] 2023-10-26 17:49
Radarr is slow because the entire movie library is transferred from the server to the browser on every page load. It could be much faster if movie searches and filters was done server-side on demand rather than all in the browser (client-side). Even the movie list page would load faster, assuming default filters are in place.
Most web applications rely on server-side for searches, filters, etc. When loading Amazon, it doesn't download all products to the browser then rely on browser client-side code to filter and query. It's all done server-side. If Radarr followed this practice all pages would load nearly instantly every time.
When any Radarr page loads it loads the full movie library twice from two different API methods (/api/v3/movie and /api/v3/collection). If both of these API methods were changed to accepted a filter querystring and the frontend was adjusted to use them then all slowness issues would go away.

**Comment by bakerboy448** [comment] 2023-10-26 18:15
> was adjusted to use them then all slowness issues would go away.

PRs welcome.

**Comment by Qstick** [comment] 2024-02-11 04:42
No plans to do anything different right now, other than the Oct 7th change

**Closed by Qstick** 2024-02-11 04:42 UTC
Labels: Type: Bug, Area: Database, Type: Enhancement, Status: Needs Triage
