### ISSUE TITLE
Filter queued torrents not out of Wanted screen with a check box

### ISSUE THREAD

**Issue by tr00p3r** [Radarr/Radarr#2890] opened 2018-07-14 13:16 UTC
**Is your feature request related to a problem? Please describe.**
I wish to redownload my media in bulk but I have a 5 download queue in transmission, I'd like a way to remove the items from the wanted list that have already been searched and queued

**Describe the solution you'd like**
Ad a check box or option button to let me search for all missing and not queued movies.

**Describe alternatives you've considered**
Turning on all my downloads so they appear in the activity...

**Comment by fryfrog** [comment] 2018-08-20 22:42
The actually screen is Wanted -> Missing and Wanted -> Cutoff unmet. Logically, I disagree that anything should be not shown here until it has literally been downloaded or imported.

A better solution might be a `queued` or `downloading` flag that could be shown basically everywhere it is appropriate. There are tons of views that would benefit from that.

**Comment by galli-leo** [comment] 2018-09-12 15:08
Duplicate of #252

**Closed by galli-leo** 2018-09-12 15:08 UTC
Labels: feature request
