### ISSUE TITLE
Deleted movies not changing status

### ISSUE THREAD

**Issue by syco** [Radarr/Radarr#4576] opened 2020-07-07 09:03 UTC
**Describe the bug**
I have enabled "Unmonitor Deleted Movies", but when I remove all files and folder for said movie, it doesn't change from Downloaded to Unmonitored. Instead it stays stuck in Downloaded.
At the moment my movie folder is completely empty, and it has been empty for several days.

**Expected behavior**
Movie is changed to Unmonitored.

**Screenshots**
![image](https://user-images.githubusercontent.com/54575/86753945-65fcf680-c038-11ea-8567-8874c98d2b3c.png)
![image](https://user-images.githubusercontent.com/54575/86754039-77de9980-c038-11ea-9789-2be5637ad44e.png)

**Platform Information (please complete the following information):**
 - OS: CentOS + Docker [(linuxserver/radarr)](https://hub.docker.com/r/linuxserver/radarr/)
 - Mono Version: 5.20.1.34
 - Radarr Version: 0.2.0.1480

**Comment by Qstick** [comment] 2020-07-07 13:44
Did you refresh that movie? Has it been refreshed since the delete (given the age of the movie I would guess not automatically)? Radarr is only going to pickup that it's deleted after it has refreshed and scanned the directory. If it still doesn't work I'm afraid you are out of luck on v0.2. We likely won't be fixing it.

**Closed by Qstick** 2020-07-07 13:44 UTC
Labels: bug

**Comment by syco** [comment] 2020-07-07 13:54
I did "Update movie and scan disk" several times,
I've also executed all tasks in "/system/tasks", and restarted the server a few times in the last few days.

Just to clarify on the version number, 0.2 is the current stable. So what version should I test with?
Thanks

**Comment by Qstick** [comment] 2020-07-08 04:02
V3 is nearing a beta state, if you feel up to it you can test with that... Just backup your DB first

**Comment by syco** [comment] 2020-07-20 11:27
Hi,
I've updated radarr to version 3, running in docker, but the problem is still occurring
```txt
Version    3.0.0.3164
Package Version    3.0.0.3164-ls14 by linuxserver.io 
.NET Core    Yes
Docker    Yes
DB Migration    177
AppData directory    /config
Startup directory    /app/radarr/bin
Mode    Console
```

For example:
![image](https://user-images.githubusercontent.com/54575/87932357-50012400-ca83-11ea-8cc4-1c8eea0508df.png)

![image](https://user-images.githubusercontent.com/54575/87932202-06b0d480-ca83-11ea-8dd5-402837db9c7a.png)

![image](https://user-images.githubusercontent.com/54575/87932240-16c8b400-ca83-11ea-86ce-747a634e1d08.png)

However, I watched the movie over a week ago, and after I watch a movie the media server I use deletes the movie file together with the containing folder, so now the folder `/movies.keep` is empty.
```bash
# ls -lar /movies.keep
total 4
drwxr-xr-x 1 root root  137 Jul 13 20:42 ..
drwxrwxr-x 2 abc  abc  4096 Jul 16 09:00 .
```

Also, this is the log when I click on "Refresh & Scan" in the movie page:
```txt
2020-7-20 12:24:11.4|Info|RefreshMovieService|Updating Info for Indiana Jones and the Last Crusade
2020-7-20 12:24:12.9|Warn|DiskScanService|Movie's root folder (/movies.keep/) is empty.
2020-7-20 12:24:13.8|Info|MetadataService|Movie folder does not exist, skipping metadata creation
```

Thanks

**Comment by ta264** [comment] 2020-07-20 11:34
This is by design. Radarr doesn't scan totally empty folder in case it's a drive / network failure
