### ISSUE TITLE
Automatic folder rename creates new folders instead of renaming originals

### ISSUE THREAD

**Issue by blackwhattack** [Radarr/Radarr#1744] opened 2017-06-28 14:24 UTC
It's frustrating, because all my nfos, srts, and jpgs are left in the old folders and my library is now full of duplicates.

**Comment by galli-leo** [comment] 2017-06-28 15:48
Please see the other issues created about this. This will be fixed when we implement moving extra files.

Duplicate of: #121

**Closed by galli-leo** 2017-06-28 15:48 UTC
Labels: duplicate
