### ISSUE TITLE
Rclone Gdrive Mount Showing Local Used Space as Free Space Rather than Free Space as Free Space

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#4989] opened 2020-09-10 20:35 UTC
**Describe the bug**
Title...
![image](https://user-images.githubusercontent.com/55419169/92800561-6a1bfc00-f37a-11ea-833d-bbf81b60af11.png)

MergerFS command
`/home/bakerboy448/bin/mergerfs /home/bakerboy448/local:/home/bakerboy448/cloud=NC /home/bakerboy448/merge -o rw,async_read=false,statfs_ignore=nc,use_ino,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true,nonempty`

Logs: N/A

XHR from Chrome Dev  Free Space is being showed as used.
Can we check based on lack of label or a UUID in path? and re calculate actual free space?
```
37: {path: "/mnt/mpatht/bakerboy448/merge", label: "", freeSpace: 7758986383360,…}
freeSpace: 7758986383360
label: ""
path: "/mnt/mpatht/bakerboy448/merge"
totalSpace: 1137897908469760
```

**Comment by bakerboy448** [comment] 2020-09-10 20:54
![image](https://user-images.githubusercontent.com/55419169/92804416-efed7680-f37d-11ea-833c-321a75d0dd30.png)

**Comment by bakerboy448** [comment] 2020-09-10 21:00
per discussions with Rg on discord; if rclone mount is not used, it works as expected

appears isolated to rclone... that command is 
`rclone mount --daemon --daemon-timeout=5m --allow-non-empty --buffer-size=128M --use-mmap --dir-cache-time=48h --cache-info-age=48h --vfs-cache-mode=writes --vfs-read-chunk-size-limit off --vfs-cache-max-age=6h --vfs-read-chunk-size=128M --log-file=drivemount.log --log-level INFO crypt: /home/bakerboy448/cloud`

**Comment by Qstick** [comment] 2020-09-11 02:39
Also dupe of #4899

**Closed** 2020-09-11 02:39 UTC
Labels: bug
