### ISSUE TITLE
Not deleting diskstation file (Not needed, since it keeps an internal copy for seeding)

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#2000] opened 2017-08-25 13:39 UTC
hello

i have hardlinks enabled, but every torrent i download gets copied instead and i end up with two copies, one that seeds, and one that goes to the destination path

i am on synology, latest develop update

**Comment by JrCs** [comment] 2017-08-25 18:16
Is the download and destination are on the same volume on your synology ?
Also if you use docker to run Radarr you must declare only ONE volume that contain download and destination directories.

**Comment by king8084** [comment] 2017-08-25 18:24
Yes both on same volume and i am running radarr from syno community

It works as it should on sonarr and it gets hardlinked. But its not working for radarr tho im running exact same setup on both sonarr and radarr

**Comment by JrCs** [comment] 2017-08-25 18:32
I'm using Radarr and Sonarr on my Synology in docker and hardlinks work well on the 2 versions.
Double checks the paths of download and destination directories and if you can try to made a hard link between the two from terminal

**Comment by king8084** [comment] 2017-08-25 18:41
they are both in the same volume

**Comment by king8084** [comment] 2017-08-27 09:08
it is not working, i have tried every thing i do not understand why it is not working !!

here are some screenshots someone help me out here

![image](https://user-images.githubusercontent.com/9740702/29748445-c8044672-8b1f-11e7-9b27-e4b5c62487eb.png)

![image](https://user-images.githubusercontent.com/9740702/29748454-0206ce9e-8b20-11e7-832a-7987ea432921.png)
![image](https://user-images.githubusercontent.com/9740702/29748460-158df762-8b20-11e7-9f53-6e91226c95a5.png)
![image](https://user-images.githubusercontent.com/9740702/29748466-30eafc4e-8b20-11e7-9b37-3c965aa79c7b.png)
![image](https://user-images.githubusercontent.com/9740702/29748473-4bef2326-8b20-11e7-985d-d3d745596096.png)
![image](https://user-images.githubusercontent.com/9740702/29748478-596e5ec2-8b20-11e7-930b-bb8d8c12a25d.png)

someone pls help.....i need hardlinking to work i dont have much space to spare

**Comment by king8084** [comment] 2017-08-27 09:13
oddly enough, if i deleted the original file at "anime" temp download folder, the seeding does not stop, which means the hardlinking part is working but radarr will not delete the "anime" copy !

**Comment by hotio** [comment] 2017-08-27 18:48
Show inode number with ls -i for both files...You seem confused about what hardlinking actually is.

**Comment by king8084** [comment] 2017-08-28 14:02
well, the way it works on Sonarr is once the torrent is downloaded, it moves it to the destination folder and removes it from the downloaded folder and it keeps seeding, so in total i have one file in my drive

with Radarr i have 2 files

**Comment by hotio** [comment] 2017-08-28 16:59
Show inode number with ls -i for both files

**Comment by king8084** [comment] 2017-08-29 14:07
i would if i understand what that means lol

**Comment by king8084** [comment] 2017-08-29 18:43
this is so annoying, some movies do get moved and the torrent continue seeding tho only one file is in the correct destination folder, but most are getting copied and i have two files

it works all the time correctly with Sonarr, i am not sure why its not working with Radarr, i am running exact same setup

**Comment by Dnkhatri** [comment] 2017-09-01 00:48
Hardlink means you get 2 files but they use the same data on the disk. So files should show up in your torrents folder as well as radarr. Your torrent client wont be able to find the files it is seeding that sonarr removed when you reboot your nas

**Comment by king8084** [comment] 2017-09-01 14:41
hmmm interesting, so radarr changed the code of that part and is doing it differently than sonarr? i just assume something is wrong because radarr was behaving differently than sonarr

**Comment by Dnkhatri** [comment] 2017-09-05 04:13
I am using hard linking with both  sonarr and radarr and it works the same as far as I can tell. I think the difference probably is in your sonarr and radarr settings

**Comment by king8084** [comment] 2017-09-05 12:46
settings on both are identical

**Comment by JohanSF** [comment] 2017-10-08 12:15
Could this be a permissions problem?

**Comment by demonbane** [comment] 2017-10-13 05:43
I think the title of this is a bit misleading, but I'm having the same issue.

Hard links are working correctly, however the download handling for DownloadStation does seem to be different than it is in Sonarr. In Sonarr, once the movie is linked from the import folder into the destination the folder, the **import** copy will be deleted. This is because DownloadStation keeps an "internal" copy for seeding, so leaving the copy in the import folder is unnecessary.

It appears that in Radarr, the importer is keeping the import copy around since it, presumably, mistakenly thinks that the files need to be kept around for seeding.

This same issue was discussed in https://github.com/Sonarr/Sonarr/issues/1764 a few months ago and fixed in https://github.com/Sonarr/Sonarr/pull/1803.

**Comment by demonbane** [comment] 2017-10-13 05:45
Oh, and I just saw that this was also submitted to Radarr by the author in #1469 but then closed. @margaale, were there some problems with getting this included in Radarr?

**Comment by margaale** [comment] 2017-10-13 13:39
No issue, lack of time mostly.... Sorry

**Comment by king8084** [comment] 2017-10-22 18:27
even when people called me crazy, i kept pushing cuz i knew i wasnt

i told yall radarr is behaving differently than sonarr but you guys laughed at me :(

hopefully this get sorted soon, also god damn i just learned even if i delete something off synology it does not actually delete it until i stop seeding, that kinda explains why i could never free space

**Comment by Prime-Omega** [comment] 2017-12-17 03:40
Not sure what the status on this is but could we please get the option to choose? Something like this:

![hard](https://user-images.githubusercontent.com/1196516/34076355-3fd189b4-e2e4-11e7-88be-4589d9c4d5f8.png)

It kinda irks me that Sonarr/Radarr are both behaving differently in this regard. In my opinion Sonarr is behaving incorrectly and Radarr is working as intended. The default behaviour for a seeding torrent is to copy it instead of moving it.  

I get the reasoning that it isn't necessary to leave the original file as download station automatically makes an internal hardlink. However I run several scripts on my download folder so it is useful for me that the files remain there until I stop seeding or delete them.

**Comment by galli-leo** [comment] 2017-12-17 12:07
@Prime-Omega I don't think we will pull in the changes from Sonarr any time soon, so no need for that switch.

**Comment by Prime-Omega** [comment] 2017-12-17 12:16
@galli-leo I actually want such a switch in Sonarr as it is not adhering to the default documented behaviour for Download Station torrents. 

Would it make sense to launch a feature request for this on the Sonarr github or would it just be ignored due to too low priority? Or is there perhaps some toggle or config file that I can change myself to force copy?

**Comment by demonbane** [comment] 2017-12-21 06:44
@Prime-Omega It sounds like what you want is a switch to have the default import action be copy instead of rename/move? That's something you should definitely consider suggesting to the Sonarr/Radarr teams.

For the purposes of this issue, however, I'd say this is still definitely a bug. DownloadStation is having a **workaround** applied that it doesn't need, which leads to inconsistent behavior. (all non-torrent download handlers default to rename/move, so DownloadStation should as well since it doesn't require the seeding workaround)

**Comment by alexanderberman** [comment] 2018-03-30 02:08
@margaale Thank you for fixing the issue. I use Radarr and Sonarr with download station and can confirm that the Sonarr behavior is much better. Do you know why your fix was not implemented?

**Comment by margaale** [comment] 2018-03-31 00:33
Nope, I have had no feedback at all. It seems they are not interested in
fixing this issue.

**Comment by galli-leo** [comment] 2018-03-31 15:07
We are interested in fixing this issue, but you never seemed to fix the merge issues with your pr.

**Closed** 2018-04-05 19:24 UTC
Labels: enhancement, priority:low
