### ISSUE TITLE
Bulk import of movies is not detecting all the movies in folder, only the first.

### ISSUE THREAD

**Issue by cybersteel8** [Radarr/Radarr#2697] opened 2018-04-03 11:21 UTC
So I have just installed Radarr for the first time (Fedora 27 Server) and I currently have a library of over 500 movies. I have them categorised into alphabetical folders, "0-B" is the first one, for example. I would like to add all of these movies to Radarr so it can track them (and do all the other fancy updating and stuff I've been reading about).
However, when I add each folder individually, only one movie in the folder is added. I had to match it to the correct TMBD ID and that one movie was added. I have a few dozen more movies in that folder that Radarr apparently has no idea exists.

How would I go about troubleshooting this issue? Is it a bug or have I done something wrong? I am brand new to Radarr, so I would appreciate all the help I can get (and give!).

**Radarr Version:**
Pre-Release v0.2.0.995
**Mono Version:**
4.7.0

**Comment by galli-leo** [comment] 2018-04-03 17:57
Duplicate of #153

**Closed by galli-leo** 2018-04-03 17:57 UTC

**Comment by galli-leo** [comment] 2018-04-03 18:00
Basically, working as intended. For now, Radarr expects the following folder structure:

ROOT FOLDER (e.g. /media/movies)
--Movie Folder (e.g. /media/movies/Prometheus 2017)
----Movie File (e.g. /media/movies/Prometheus 2017/prometheus.2017.mkv)

If you wanna keep using your existing structure, you basically need to add each main folder (0-B) as a root folder and import that. You can also wait for #153 to be fixed, but that's probably gonna take at least another month or two, since we need to rewrite a lot of Radarr code.

**Comment by cybersteel8** [comment] 2018-04-03 21:18
That is what I attempted to do - I added the directory "0-B" directly, which contains each movie file inside it (mp4, mkv etc). However, only one movie was added.
