### ISSUE TITLE
MoveMovieService fails with IOException: Cross-device link

### ISSUE THREAD

**Issue by madhackbt** [Radarr/Radarr#7126] opened 2022-03-10 18:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Edit of Movie Path OR Movie Editor Change Root Path fails with:

Unable to move movie from '/mnt/share/media/Videos/movies/Knives Out (2019)' to '/mnt/datashare/media/Videos/movies/Knives Out (2019)'. Try moving files manually: Cross-device link

System.IO.IOException: Cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262
   at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 88
   at NzbDrone.Core.Movies.MoveMovieService.MoveSingleMovie(Movie movie, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in D:\a\1\s\src\NzbDrone.Core\Movies\MoveMovieService.cs:line 57

NOTE: This was working with Mono-based v3 of Radarr.

### Expected Behavior

Movie and all files in the folder are moved to new location.

### Steps To Reproduce

1. Edit a Movie
2. Change the "root" part of path to new location
3. Click Save
4. Click "Yes, Move the Files" button
5. Response comes back immediately with "Completed", but it should take some time to actually move the file to new location.
6. The log shows the Exception noted above.

1. Use Movie Editor
2. Select Change Root Path
3. Choose new Root Path
4. Click "Yes, Move the Files" button
5. Same response as noted above, with same type of Exception in Events

### Environment

```markdown
- OS: TrueNAS-12.0-U8
- Radarr: 4.0.4.5922
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 98.0
```

### What branch are you running?

Master

### Trace Logs?

2022-03-10 07:54:15.0|Info|MoveMovieService|Moving 1 movies to '/mnt/datashare/media/Videos/movies'
2022-03-10 07:54:15.0|Info|MoveMovieService|Moving Knives Out from '/mnt/share/media/Videos/movies/Knives Out (2019)' to '/mnt/datashare/media/Videos/movies/Knives Out (2019)' (1/1)
2022-03-10 07:54:15.0|Error|MoveMovieService|Unable to move movie from '/mnt/share/media/Videos/movies/Knives Out (2019)' to '/mnt/datashare/media/Videos/movies/Knives Out (2019)'. Try moving files manually

[v4.0.4.5922] System.IO.IOException: Cross-device link
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 262
   at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 88
   at NzbDrone.Core.Movies.MoveMovieService.MoveSingleMovie(Movie movie, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in D:\a\1\s\src\NzbDrone.Core\Movies\MoveMovieService.cs:line 57

2022-03-10 07:54:15.0|Info|MoveMovieService|Finished moving 1 movies to '/mnt/datashare/media/Videos/movies'

[AB#2785](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2785)

**Comment by bakerboy448** [comment] 2022-03-10 18:57
Duplicate of https://github.com/Radarr/Radarr/issues/5558

Updated 5558 Title to be more generic.

**Closed by bakerboy448** 2022-03-10 18:57 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by RobinDadswell** [comment] 2022-03-10 19:53
@madhackbt What is the filesystem mounted as within the Jail? Is it setup as nullfs? Hop by the discord and we can maybe work this out for you as it's not a mergefs type scenario https://radarr.video/discord

**Comment by madhackbt** [comment] 2022-03-10 21:34
For posterity's sake: @RobinDadswell and et. al. gave a work around to fix the issue:

In the base OS Shell:

iocage set enforce_statfs=1 <jailname>
for example:
iocage set enforce_statfs=1 radarr

Then, restart the jail
