### ISSUE TITLE
Multiple Language for Releases in Quality Porfile

### ISSUE THREAD

**Issue by Lonewolf982** [Radarr/Radarr#5242] opened 2020-10-19 23:47 UTC
Some movies that I manually search satisfy all my custom formats and quality profile with the sole exception of the language for release. For example, my quality profile has the language English for Releases. Consequently, some movies are rejected by radarr because of the following reason "English is wanted, but found XXXXXXXX language". 

Would it be possible to allow for multiple language for releases in the same quality profile. So in my case, allow English, French and Italian releases?

Thank you

**Comment by Qstick** [comment] 2020-10-19 23:48
You can do this with custom formats, also dupe of #5074

**Closed by Qstick** 2020-10-19 23:48 UTC
Labels: feature request
