### ISSUE TITLE
Can't access Settings after update

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#2039] opened 2017-09-05 16:50 UTC
**Description:**

Can't go to Settings any more. Just constantly has the moving blobs. Get this error every time I try:

 | NzbDroneErrorPipeline | Request Failed: Sequence contains more than one element

**Radarr Version:**
Just updated to Ver. 0.2.0.846

**Logs:**
  | NzbDroneErrorPipeline | Request Failed: Sequence contains more than one element

`System.InvalidOperationException: Sequence contains more than one element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x000a3] in <198d428ffe33413aa3c4cb6d388f57b3>:0 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].SingleOrDefault () [0x00006] in <79ef4b111ab349828cc9175dd534046a>:0 
  at NzbDrone.Core.Authentication.UserService.FindUser () [0x00000] in <79ef4b111ab349828cc9175dd534046a>:0 
  at NzbDrone.Api.Config.HostConfigModule.GetHostConfig () [0x00019] in <a2c7aea68437403cb2fd6a0f5008f534>:0 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceSingle>b__38_0 (System.Object options) [0x00006] in <a2c7aea68437403cb2fd6a0f5008f534>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 `

**Comment by thefoxman88** [comment] 2017-09-06 04:30
I have the same above issue on Ver. 0.2.0.846

Brand new install on unRAID docker, pulled from "linuxserver/radarr:latest"
Everything else works but unable to use anything under settings.


[v0.2.0.846] System.InvalidOperationException: Sequence contains more than one element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0007b] in <e3fb361e66bb4797b6f56fd88e04971e>:0 
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].SingleOrDefault () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:99 
  at NzbDrone.Core.Organizer.NamingConfigService.GetConfig () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Organizer\NamingConfigService.cs:20 
  at NzbDrone.Api.Config.NamingConfigModule.GetNamingConfig () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Config\NamingConfigModule.cs:56 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceSingle>b__38_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:147 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

**Comment by hotio** [comment] 2017-09-06 13:24
no problems here, ver 0.2.0.847 on hotio/suitarr (not that it should matter) docker

**Comment by thefoxman88** [comment] 2017-09-06 14:24
> no problems here, ver 0.2.0.847 on hotio/suitarr (not that it should matter) docker

It might have been fixed on 0.2.0.847 as turkeyphant and I are on .846 guess I will have to wait for the new version to flow down to "linuxserver/radarr:latest"

**Comment by turkeyphant** [comment] 2017-09-06 14:51
Actually just tried again and seems magically fixed? I'd tried multiple times from different connections over the last few hours...

**Comment by galli-leo** [comment] 2017-09-06 15:16
Can you guys try an incognito window?

**Comment by turkeyphant** [comment] 2017-09-06 15:31
Completely fixed for me now regardless.

**Comment by thefoxman88** [comment] 2017-09-07 04:15
wow... legit nothing changed with the docker, or my setup and is magically
working today.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by hotio** [comment] 2017-09-10 08:06
I can confirm this issue now, a restart of radarr fixed it.

```
System.InvalidCastException: Specified cast is not valid.
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Threading.Tasks.TaskCompletionSource`1<object>,object)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1) [0x00083] in <e3fb361e66bb4797b6f56fd88e04971e>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Threading.Tasks.TaskCompletionSource`1<object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x000b0] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 
```

**Comment by galli-leo** [comment] 2017-09-10 09:36
@hotio Yours seems to be a different one altogether.

**Comment by arette** [comment] 2017-11-20 02:09
bizarre, I'm getting same error with Lidarr:
[https://github.com/VoliKoN/lidarr-docker/issues/3](url)

**Comment by galli-leo** [comment] 2018-01-30 12:02
Well issue seems to be gone now. With no way of reproducing, gonna close this. Feel free to reopen when it happens again.

**Closed by galli-leo** 2018-01-30 12:02 UTC
Labels: bug, cannot reproduce
