### ISSUE TITLE
Feature Request: add nfo file with imdb id

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#256] opened 2017-01-14 17:25 UTC
I'm using Plex and it would be great if Radarr adds a .nfo file with the imdb id in it (like CP does) so plex has the exact match for the movie.

https://forums.plex.tv/discussion/232808/wrong-movie-metadata-showing-up

And the original nfo file of the release could be moved too as "moviefilename.orig.nfo".

**Comment by ShanDestromp** [comment] 2017-01-15 02:22
As of now metadata isn't being generated at all; probably safe to consider this a dupe of #167

**Comment by onedr0p** [comment] 2017-01-15 02:26
Yes it is thanks!

**Closed by onedr0p** 2017-01-15 02:26 UTC
Labels: feature request, priority:low
