### ISSUE TITLE
V3 deleting existing artwork from movie folder

### ISSUE THREAD

**Issue by lexguy2007** [Radarr/Radarr#5545] opened 2020-12-12 22:17 UTC
Describe the bug
When Refresh & Scan of a movie is performed, Radarr is deleting existing artwork and replacing some existing artwork for that movie. This is happening when a new file is downloaded that is of higher quality and when the file gets renamed (using another program). Each instance when the movie is rescanned, Radarr is deleting the artwork. Also, it does not matter if, in the settings under Metadata, Movie Images is checked or not.

Expected behavior
I would expect if there is existing artwork, that it be left alone and only the updated file information within Radarr be updated to reflect the changes. I spend a lot of time downloading specific artwork for my movies and do not want Radarr deleting them or changing them just because a movie is upgraded or renamed.

Screenshots
This screenshot is showing the artwork present in the movie folder before rescanning the renamed movie:
![](https://user-images.githubusercontent.com/13860924/101527604-d4314680-3953-11eb-8566-b8c6df7894bf.png)

This is what the folder looked like after rescanning in Radarr. Files missing:
![](https://user-images.githubusercontent.com/13860924/101527854-270afe00-3954-11eb-90a4-403ac44ecdb3.png)

Screenshot of the even log showing the rescanning in Radarr:

![](https://user-images.githubusercontent.com/13860924/101528143-8406b400-3954-11eb-9515-a5482f6a28e4.png)
Platform Information (please complete the following information):

    OS: Windows 10
    Docker: No
    Radarr Version [3.0.0.4204
    Radarr Branch develop

**Comment by bakerboy448** [comment] 2020-12-12 22:19
Closing; Dupe of numerous others. Please use the search function

Also your radarr version is out of date

**Closed by bakerboy448** 2020-12-12 22:19 UTC
Labels: bug

**Comment by lexguy2007** [comment] 2020-12-12 22:20
I did search dude! I have not found open tickets where artwork is being deleted. Also I just updated my radarr version on the ticket. This is still an issue.

**Comment by lexguy2007** [comment] 2020-12-12 22:21
Why are you not linking the tickets anyway? You're closing my issue and I have no idea what the status is.  If you are not going to link tickets that does not help AT ALL.

**Comment by lexguy2007** [comment] 2020-12-12 22:22
About

Version
    3.0.1.4259
.NET Core
    Yes (3.1.10)
DB Migration
    188
AppData directory
    C:\ProgramData\Radarr
Startup directory
    C:\ProgramData\Radarr\bin
Mode
    Service
Uptime

**Comment by lexguy2007** [comment] 2020-12-12 22:28
![Screenshot 2020-12-12 162535](https://user-images.githubusercontent.com/13860924/101996316-fcdc7780-3c96-11eb-9e5c-2aa2819e1857.png)

@bakerboy448 No search results....

**Comment by bakerboy448** [comment] 2020-12-12 22:29
was on mobile, so don't have the links handy..

https://github.com/Radarr/Radarr/issues/5378
https://github.com/Radarr/Radarr/issues/5210


https://github.com/Radarr/Radarr/issues/5519
^Literally the same issue....oh so you literally opened a new duplicate issue... that is poor GH etiquette 
If you would have re-pinged me on that issue rather than creating a duplicate, more details can be provided there and people's inbox's would be spammed less

As Q said on one of the links.
>Yea I think the solution here is improving our sub handling and parsing, we have similar issues with video file extras... Extras in general need some tlc.

**Comment by austinwbest** [comment] 2020-12-12 22:42
It is on my short term to-do list to work on how meta is handled & accept other types of meta, etc.

**Comment by lexguy2007** [comment] 2020-12-12 22:46
@bakerboy448 
#5378 is about subtitles....how is that related to artwork? 
#5210 is also about subtitles....
#3209 is about version 2 and I never had this problem on V2. Not until updating to V3 did this start for me.

#5519 yes this is my ticket. And don't tell me about GH etiquette when you close tickets immediately as so called "duplicates" without providing links to those said duplicates (Which do not appear to me to be duplicate issues). If behind the scenes they are issues programmatically similar, then again, linking the tickets would let me know that. Also, I DID reply to the first ticket but you never replied to it.

**Comment by lexguy2007** [comment] 2020-12-12 22:47
@austinwbest thank you!

**Comment by austinwbest** [comment] 2020-12-13 00:45
> @austinwbest thank you!

He linked the issues as they are all related to extras

**Comment by lexguy2007** [comment] 2021-03-03 14:22
@austinwbest 
Any update on this? Or is there something I can turn off to prevent my artwork from being deleted? I am starting to get aggravated about having to download and set my custom artwork every time a movie is upgraded.

**Comment by tamburra** [comment] 2021-03-11 17:45
Is there any updates on this.  This is affecting me as well and really is a pain as I also change my poster artwork and it is constantly getting deleted by radarr.

**Comment by bakerboy448** [comment] 2021-03-11 18:16
This thread is closed as other issues cover it.

Please do not bump closed threads.

Additionally:
The main development team is split across 3 apps: Radarr, Readarr, and Lidarr.
There are only 3 or 4 active developers who work on this, and of those 3 or 4 exactly zero work on this fulltime. Exactly zero of any members involved (developers / support) get paid to do this. Everyone of us has fulltime real jobs. Everyone of us has kids and family. Everyone of us works on more than just this project.

**Comment by lexguy2007** [comment] 2021-03-12 21:23
There is no need to be an A-hole about it. I’ve had several run ins with you on different things and you’re always a snarky a$$. That’s fine. I just will stop supporting Radarr and Lidarr. Have a nice day and thanks for your “help”.---- On Thu, 11 Mar 2021 12:16:18 -0600  ***@***.***> wrote ---- 
This thread is closed as other issues cover it. 
Please do not bump closed threads. 
Additionally: 
The main development team is split across 3 apps: Radarr, Readarr, and Lidarr. 
There are only 3 or 4 active developers who work on this, and of those 3 or 4 exactly zero work on this fulltime. Exactly zero of any members involved (developers / support) get paid to do this. Everyone of us has fulltime real jobs. Everyone of us has kids and family. Everyone of us works on more than just this project.

**Comment by austinwbest** [comment] 2021-03-12 21:37
> @austinwbest
> Any update on this? Or is there something I can turn off to prevent my artwork from being deleted? I am starting to get aggravated about having to download and set my custom artwork every time a movie is upgraded.

Talked with robin this morning but didn't get a chance to respond yet, when he finishes some tweaks to lists he is going to look into this so it stops removing movie based items and only items related to the actual release. 

Just to give you an update.

**Comment by lexguy2007** [comment] 2021-03-12 21:56
Thank you very much! ---- On Fri, 12 Mar 2021 15:37:34 -0600  ***@***.***> wrote ---- 
 
@austinwbest 
Any update on this? Or is there something I can turn off to prevent my artwork from being deleted? I am starting to get aggravated about having to download and set my custom artwork every time a movie is upgraded. 
 
Talked with robin this morning but didn't get a chance to respond yet, when he finishes some tweaks to lists he is going to look into this so it stops removing movie based items and only items related to the actual release. 
Just to give you an update.
