### ISSUE TITLE
Manual import not working at all

### ISSUE THREAD

**Issue by GenericPolarBear** [Radarr/Radarr#1611] opened 2017-06-02 12:02 UTC
**Description:**

When trying to manually import a movie file, it will not let me select which movie I am importing, and it won't even show the one wanted in the list of possible movies.

I have tested this both on Firefox and Chrome, both have the same issue.
The search feature for the manual imports doesn't seem to work either.

Torrent hash for the movie used: 91161af133ec994562d6f6f5a52e0a8d89a3e1c5
(Just google it to find the exact one I used in the video, I understand if I can't post the hash here or something.)

Video: https://www.youtube.com/watch?v=Yg-nvjhcrO0&feature=youtu.be

**Radarr Version:** 0.2.0.724

**Logs:** n/a

**Comment by MSe-5-14** [comment] 2017-11-16 07:53
I can confirm this bug. The list seems to be showing all movies that have already been downloaded. The wanted movies are not in the list. The search bar on the top of the popup list isn't working either on Chrome and Firefox

**Comment by galli-leo** [comment] 2017-11-16 19:19
This is fixed on the latest nightly.

**Closed by galli-leo** 2017-11-16 19:19 UTC
Labels: bug
