### ISSUE TITLE
DTS-HD, TrueHD as final download

### ISSUE THREAD

**Issue by gamesbe** [Radarr/Radarr#1552] opened 2017-05-20 06:14 UTC
Hey everyone, hoping someone can help me out here (Or if it doesn't exist, a feature request)

Basically I have it set on two qualitys, web-dl and 1080p bluray as the cutoff. It works great other than I love having my movies with DTS-HD, TrueHD codecs.

I have tried using preferred tags but if the standard 1080p version with just DTS is available, it will get snatched and it ignores the future DTS-HD, TrueHD releases.

So, the only thing I can think of is adding a quality selection with forced DTS-HD, TrueHD as it's main search. I did do some searching on preferred tags, but it didn't seem to help.

Thanks.

**Comment by galli-leo** [comment] 2017-05-20 10:18
Currently the only way to do this is with preferred tags and a delay profile. (See https://github.com/Sonarr/Sonarr/wiki/Delay-Profiles for more details). With delay profiles, Radarr will keep waiting x amount of minutes for a release with your preferred tags to appear. So you could wait say another 4-5 hours for them to appear. However, a feature to require preferred tags for the cutoff to be met, is in the works. (Don't expect it anytime soon though)

**Comment by galli-leo** [comment] 2018-02-06 23:16
Duplicate of #2433

**Closed by galli-leo** 2018-02-06 23:16 UTC
