### ISSUE TITLE
Feature Request: Movie added from list support in Connect

### ISSUE THREAD

**Issue by DjRicko** [Radarr/Radarr#5957] opened 2021-02-22 15:46 UTC
So some of us use various push services under the Connect tab to notify of different events.
Would be lovely to have support for also notifying when a movie has been automatically added from a list.
Like i add tmdb list for Star wars collection, and whenever a new star wars movie is added to that list,
it'll automatically be added as monitored movie, this works perfectly. However would be nice to have the Connect
function be able to notify of this aswell. :)

**Comment by bakerboy448** [comment] 2021-02-22 15:47
Duplicate of #https://github.com/Radarr/Radarr/issues/4038

**Closed by bakerboy448** 2021-02-22 15:47 UTC
Labels: feature request
