### ISSUE TITLE
OMG 404 Not Found

### ISSUE THREAD

**Issue by antigravity83** [Radarr/Radarr#2104] opened 2017-09-21 00:44 UTC
Continually receiving this error when attempting to view individual movie pages. 

Sometimes the front page for a movie will load, but then when "Searching" for available downloads, it'll then give the OMG 404 Not Found error.

Restart doesn't fix the issue - I have approx 2800 movies in my library.

Radarr Ver. 0.2.0.793

![image](https://user-images.githubusercontent.com/27241813/30673922-db7250f2-9eb9-11e7-8d3d-4807e770c7b4.png)

**Comment by hotio** [comment] 2017-09-21 17:02
You should be counting yourself lucky, being able to see that adorable face so much. I never get to see him.

**Comment by galli-leo** [comment] 2017-09-21 20:36
Duplicate of #1196 
Try fixes listed there (clearing caches & cookies)

**Closed by galli-leo** 2017-09-21 20:36 UTC
