### ISSUE TITLE
filename case gets changed on import

### ISSUE THREAD

**Issue by bobbintb** [Radarr/Radarr#2803] opened 2018-05-24 05:15 UTC
**Describe the bug**
I have renaming turned off but it seems to sometimes rename files on import. Specifically, a file that is all lower case will be renamed to have the first letter upper case. This messes with my whole process and the file ends up getting downloaded again by my torrent client. I looked at the debug log and this seems to happen with the hard linking process. The time in the log when this happens is 21:32 and the movie is Forever My Girl.

**To Reproduce**
It seems to happen when the file is lowercase. I can't be certain though.

**Expected behavior**
The file should be hard linked and the case and name stay the same.

**Screenshots**

**Desktop (please complete the following information):**
Version 0.2.0.1067
Mono Version5.12.0.226
Docker

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
[radarr.debug.0.txt](https://github.com/Radarr/Radarr/files/2033904/radarr.debug.0.txt)

**Comment by bobbintb** [comment] 2018-05-24 14:54
I think I've traced the problem back to the BuildFileName method. Most people likely haven't noticed the issue but I have a custom post processing script that has made me very aware of this. Since Radarr will only hard link or copy once a download is done, I've devised a work around that essentially moves the files and continues seeding. Once Radarr imports the files, my script will have the torrent client change download location to where Radarr hard linked them to on imported them to and continue seeding. The problem is, when Radarr hard links the files it changes the case to a title case. This is not an issue most of the time since they are typically already in title case but occasionally I get a file that is all lower case. So when Radarr hardlinks it it changes it to title case and when my torrent client tries to verify the download integrity and continue seeding, it cannot find the files because the case of the filename is different and it downloads the whole thing all over again.

```
        public string BuildFileName(Movie movie, MovieFile movieFile, NamingConfig namingConfig = null)
        {
            if (namingConfig == null)
            {
                namingConfig = _namingConfigService.GetConfig();
            }

            if (!namingConfig.RenameEpisodes)
            {
                return GetOriginalTitle(movieFile);
            }

            var pattern = namingConfig.StandardMovieFormat;
            var tokenHandlers = new Dictionary<string, Func<TokenMatch, string>>(FileNameBuilderTokenEqualityComparer.Instance);

            AddMovieTokens(tokenHandlers, movie);
            AddReleaseDateTokens(tokenHandlers, movie.Year);
            AddImdbIdTokens(tokenHandlers, movie.ImdbId);
            AddQualityTokens(tokenHandlers, movie, movieFile);
            AddMediaInfoTokens(tokenHandlers, movieFile);
            AddMovieFileTokens(tokenHandlers, movieFile);
            AddTagsTokens(tokenHandlers, movieFile);

            var fileName = ReplaceTokens(pattern, tokenHandlers, namingConfig).Trim();
            fileName = FileNameCleanupRegex.Replace(fileName, match => match.Captures[0].Value[0].ToString());
            fileName = TrimSeparatorsRegex.Replace(fileName, string.Empty);

            return fileName;
        }
```

That's as far as I've gotten in tracing the issue, just by looking at the code. I haven't had a chance to do an actual debug.

**Comment by fryfrog** [comment] 2018-05-24 16:40
What are your movie renaming settings? If they're off, but you're not using one of the original release or original file names, maybe try putting that in and see if it changes anything. It'd still be a bug obviously, but worth trying.

![screen shot 2018-05-24 at 9 39 57 am](https://user-images.githubusercontent.com/87748/40499327-78952d72-5f36-11e8-985a-012d720ab081.png)

**Comment by fryfrog** [comment] 2018-05-24 18:07
I just wonder if the setting is having an impact even though renaming is turned off. Should be easy to test, just change it and see. But it seems very very unlikely to have any impact.

**Comment by bobbintb** [comment] 2018-05-24 18:28
It's probably also worth noting that the srt and idx files also had the case changed.

**Comment by bobbintb** [comment] 2018-05-25 16:47
> I just wonder if the setting is having an impact even though renaming is turned off. Should be easy to test, just change it and see. But it seems very very unlikely to have any impact.

Oh, I see what you're saying. As if turning off the setting doesn't actually work? I suppose it could but I don't see anything in the logs  and I'm sure it would have been noticed by now. I might run some tests this weekend but it seems to happen in the hard linking. Thinking about the process, it must happen when the torrent is completes and imported. That is the point where it scans the files that were downloaded and decides what to copy and move over. For whatever reason, when it gets a lost of the files it changes case because the extra files (srt and idx) are also in a different case. If it were a problem with the renaming I'm not sure if it would rename the extra files as well. I don't know if the renaming process renames those extra files specified or just copies them as well.

Does anyone have a better idea of where to look at the problem? Right now I'm looking at the methods in DownloadedMovieImport.cs. I'm a little new to OOP but I think I'm getting close. I think I'll be able to trace it in a dev environment this weekend though.

**Comment by fryfrog** [comment] 2018-05-25 16:49
You're doing better than I am.

Not renaming files is *very* niche, you're probably one of like 3 people that do it that way. ;)

**Comment by fryfrog** [comment] 2018-05-25 16:50
Have you tested w/ hard links on and off?

**Comment by bobbintb** [comment] 2018-05-25 19:39
I've heard that on the help forums from devs and such but I've always wondered how accurate that is and how much of it is just their perception based on how much they help people with renaming issues. You wouldn't hear from those not using it because they wouldn't have any issue. I would think that most people don't do renaming. I started to rename my video files at one point years ago but it was just an unnecessary complication with no real benefit. It complicates seeding torrents. Naming is already standardized among Plex, Kodi, the scene and everything else. All the information I really need about the file in already in the file name. If I wanted to cross-seed it would create more issues and work. I'd download something from some obscure place because I couldn't find it on a torrent site, rename the files, and later try to find a better copy with subtitles or whatever only to realize after I download and ran a checksum comparison that it's the same files. I just could never find a valid reason to rename files beyond a minor aesthetic improvement. All it really did was introduce potential or sometimes real problems. I image it would be the same for most people but maybe I'm wrong. It doesn't really matter, I've just always been curious.

**Comment by fryfrog** [comment] 2018-05-25 19:53
I honestly think most people rename. In Movies, at least there simply can't be a whole lot of variety in naming. You have the name and the year, hard to really fuck that up. Throw in some edition.

But I do agree w/ you, the loss of the original release name and group is a tough one. Radarr and Sonarr *can* help w/ that, but it is easy to screw up (like if the group has a `-` in the name). And it looks ugly if you use it in the file name.

For your torrent seeding issue, that is the whole point of hard links. But they can be problematic to use depending on your setup.

If most people *don't* rename, they would be hitting this same issue you are. And you're the first report of it I've seen. Do you see the same behavior in Sonarr, out of curiosity?

**Comment by bobbintb** [comment] 2018-05-25 21:19
Well, not necessarily. The reason I'm having the issue is a combination of a number of factors. I download to /downloads and Radarr imports files to /movies. I think most people just let the torrent client keep seeding the files from /downloads for a while and then remove them after a set time. My post processing script tells the torrent client to change the download location from /downloads to /movies, continue seeding, and remove the files from /downloads. It is a sort of simulated move. The problem is when Radarr hard links, it hard links /downloads/my.movie.mkv to /movies/My Movie/My.Movie.mkv. I don't know for certain but I think most people would just continue to seed from /downloads and would not encounter this issue. Additionally, even if they did, the vast majority of files I download already come in title case and this only affects the rare instance of a file in all lowercase. If this is the same for other users it just might be rare enough that it hasn't been reported since it's easy to miss and just fix it manually the handful of times it happens. I've had it happen less than 5 times and I download quite about. Additionally, it would also depends on whether or not their client and/or OS is case sensitive. If neither the torrent client nor the OS cares about case then it would not be in issue.

As far as seeing the issue in Sonarr, I don't know. It's something that took me a while to notice in Radarr and then then I started making a few connections to past instances. I really only noticed it because I happened to check on my torrent client at the right time. It automatically downloaded a movie and I happened to catch it when it was almost done downloading. I checked a few minutes later and the download was about 5%. I have notice one or two times before when the imported files where a different case but it was just a "that's weird" moment and moved on. I thought it was just me loosing track of something some other process I had set up not working as expected. But it all clicked when it happened this last time. I haven't noticed it happen it Sonarr but like I said, it might just be that I haven't noticed. Actually, I don't have the same post process for Sonarr as I do for Radarr so I wouldn't even notice it unless I was looking for it. I might be able to look back at some logs and see if I can find and instance of it happening though.

**Comment by Qstick** [comment] 2018-05-25 23:28
@bobbintb I’ll see if I can’t look at this tonight, what torrent client are you using? Is it possible client is doing it or have you seen for sure it’s still lower case in your client download complete folder?

**Comment by bobbintb** [comment] 2018-05-26 02:54
I am using rutorrent. I don't think it could be the client, or at least I can't think of a way how it could be. The files in the download complete folder are still lowercase but are in title case in the movie directory where Radarr hard links them to. In the provided logs, you can see the debug statement for when Radarr hard links them to the movie folder. The source is in lowercase and the destination is in title case.

Although thinking about it a little more, I suppose it would depend on how Radarr gets the names of the files in the torrent. If it asks the torrent client, the client could be reporting it wrong but I'm 99% sure it scans the destination directory. At least that's what I recall when browsing through the code. Also, from a programming perspective, writing a method to query every supported client for a file list would require a lot more work and I doubt the author would have chosen that over a simple disk scan that would work for any client.

**Comment by fryfrog** [comment] 2018-05-26 03:17
Did you Sonarr it yet? They have more developers and a deep knowledge of things. They may quickly know what is wrong. :)

**Comment by bobbintb** [comment] 2018-05-26 03:31
Yeah, I posted on their forum right after I realized it is in Sonarr as well. I haven't gotten a response yet but in my experience markus101 responds pretty quickly and typically fixes it shortly after. I've been having a good time trying to figure it out myself though

**Comment by galli-leo** [comment] 2018-05-26 09:34
@bobbintb Thank you very much for the informative bug report! I will see, if I have time to take a look today.

**Comment by galli-leo** [comment] 2018-05-26 16:01
Hmm I think I know what the issue is, Radarr (and Sonarr) both use the SceneName of a file when not renaming files. The scene name, is usually the name of the item as it appears in your dl client, if that matches scene standards.

@markus101 What's the exact reason we are prefering the scenename when we shouldn't rename anything?

**Comment by markus101** [comment] 2018-05-26 16:06
Poorly named files inside of releases, such as `abc.303-lol` where abc`` is an acronym for the title and `303` is season 3 episode 3. In addition anything that is hashed/encrypted.

I believe you can use `Original Filename` to force Sonarr to use the filename instead of the download client name or folder name.

**Comment by galli-leo** [comment] 2018-05-26 17:54
@markus101 That's what I thought, didn't think of Original Filename though.

@bobbintb Can you try enabling renaming and setting the template to Original Filename?

**Comment by bobbintb** [comment] 2018-05-26 18:37
> Poorly named files inside of releases, such as abc.303-lol where abc`` is an acronym for the title and 303 is season 3 episode 3. In addition anything that is hashed/encrypted.

Ugh, I HATE it when that happens.

Ok, so maybe not so much of a bug. I'll try the Original Filename setting and report back. I don't ever use renaming so I wasn't even aware of that option.

**Comment by bobbintb** [comment] 2018-05-26 22:52
I'm not quite sure if I set it right but the file name is still in title case. Here is my rename config:
![image](https://user-images.githubusercontent.com/2601376/40580841-2c1f2aee-6105-11e8-9cd1-3e4a6f9e7aab.png)

**Comment by bobbintb** [comment] 2018-05-26 23:02
Nevermind. I used {Original Filename} and it works as expected now. It just wasn't is the pull down menu so I used the wrong one until I found the right one in the wiki. Thanks for the help all. A little bit of a counter-intuitive solution but it works.

**Comment by bakerboy448** [comment] 2020-11-14 06:37
closing...OP said it works as expected

**Closed by bakerboy448** 2020-11-14 06:37 UTC
Labels: bug, confirmed, sonarr upstream
