### ISSUE TITLE
IMDB List not importing imdb codes longer than tt+ 7 numbers

### ISSUE THREAD

**Issue by GingerNutzGit** [Radarr/Radarr#4032] opened 2020-01-05 07:51 UTC
Having added my IMDB Watchlist I discovered a few items not importing.

Checked by fetching list manually in AddMovies | Add Movies From Lists | All | Fetch List (I only have the 1 list) - missing items not listed

Downloaded the watch list from imdb to csv file to see what might stand out as a commonality between the missing items:

All items with longer tt IDs were not being detected/selected/found.  eg tt10223546 = bad, tt6358260 = good. Full list of items that are not detected:

Position | Const | Created | Modified | Description | Title | URL | Title Type | IMDb Rating | Runtime (mins) | Year | Genres | Num Votes | Release Date | Directors | Your Rating | Date Rated
48 | tt10223546 | 03/06/2019 | 03/06/2019 |   | Tu mérites un amour | https://www.imdb.com/title/tt10223546/ | movie | 6.4 | 102 | 2019 | Comedy, Drama, Romance | 145 | 19/05/2019 | Hafsia Herzi |  
63 | tt10366206 | 15/08/2019 | 15/08/2019 |   | John Wick: Chapter 4 | https://www.imdb.com/title/tt10366206/ | movie |   |   | 2021 | Action, Crime, Thriller | 21/05/2021 |   |   |  
99 | tt10039344 | 15/10/2019 | 15/10/2019 |   | Countdown | https://www.imdb.com/title/tt10039344/ | movie | 5.3 | 90 | 2019 | Horror, Thriller | 4346 | 24/10/2019 | Justin Dec |   |  
106 | tt10228168 | 15/10/2019 | 15/10/2019 |   | Hatsukoi | https://www.imdb.com/title/tt10228168/ | movie | 7.1 | 108 | 2019 | Comedy, Crime, Romance | 1088 | 17/05/2019 | Takashi Miike |  
107 | tt10838180 | 15/10/2019 | 15/10/2019 |   | The Matrix 4 | https://www.imdb.com/title/tt10838180/ | movie |   |   | 2021 | Action, Sci-Fi | 21/05/2021 | Lana Wachowski |  
114 | tt10844816 | 24/10/2019 | 24/10/2019 |   | Scandalous: The Untold Story of the National Enquirer | https://www.imdb.com/title/tt10844816/ | movie | 5.7 | 97 | 2019 | Documentary | 49 | 11/10/2019 | Mark Landsman |  
158 | tt10065694 | 17/12/2019 | 17/12/2019 |   | Antebellum | https://www.imdb.com/title/tt10065694/ | movie |   |   | 2020 | Horror, Thriller | 23/04/2020 | Gerard Bush, Christopher Renz
204 | tt10648342 | 05/01/2020 | 05/01/2020 |   | Thor: Love and Thunder | https://www.imdb.com/title/tt10648342/ | movie |   |   | 2021 | Action, Adventure, Fantasy | 03/11/2021 | Taika Waititi |  
261 | tt10582690 | 05/01/2020 | 05/01/2020 |   | Untitled Alien Prequel | https://www.imdb.com/title/tt10582690/ | movie |   |   | 2021 | Horror, Mystery, Sci-Fi, Thriller | 15/04/2021 | Ridley Scott |  
403 | tt10199586 | 05/01/2020 | 05/01/2020 |   | Atlantique | https://www.imdb.com/title/tt10199586/ | movie | 6.8 | 106 | 2019 | Drama | 3036 | 16/05/2019 | Mati Diop |   |  
441 | tt10443252 | 05/01/2020 | 05/01/2020 |   | ECCO | https://www.imdb.com/title/tt10443252/ | movie | 5 | 123 | 2019 | Crime, Drama, Thriller | 140 | 09/08/2019 | Ben Medina |  
442 | tt10182822 | 05/01/2020 | 05/01/2020 |   | Loro | https://www.imdb.com/title/tt10182822/ | movie | 6.7 | 151 | 2018 | Biography, Drama | 2088 | 13/09/2018 | Paolo Sorrentino |  

No Problem with TV Movies/Videos/Shorts etc - as I've seen mentioned on REddit as a possible problem.  Only category ignored is TV Shows as expected.

Because I have Clean Library Level = Remove & Delete Files, I can't add these items (looking into TMDB lists to get these added in the short term)

**Radarr Version:**
0.2.0.1450

**Mono Version:**
n/a

**Debug Logs:**
There are no exceptions raised/logged.

**Comment by Qstick** [comment] 2020-01-05 16:49
Dupe of #3637

**Closed by Qstick** 2020-01-05 16:49 UTC
Labels: bug
