### ISSUE TITLE
Problem on search with apostrophe

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#2143] opened 2017-10-06 11:33 UTC
Hi I've a little problem with title that contains apostrophe
I thought was a Jackett problem but I think is not.

I'm on Radarr 0.2.0.852 on a Qnap system with mono V4.6.2.7

Just to have track of all the original issue that I opened on Jackett is here
https://github.com/Jackett/Jackett/issues/1926

So the problem is

For example the movie:
Ace Ventura: Pet Detective

In my country the tile is:
Ace Ventura - L'acchiappanimali

So, correct me if I wrong, Radarr search the original title and my local title but search
ace ventura lacchiappanimali
without the apostrophe

So the ' is missing and don't find any
If I try for example to search on ilcorsaronero you can see the difference
https://ilcorsaronero.info/argh.php?search=ace+ventura+l+acchiappanimali -> 1 results
https://ilcorsaronero.info/argh.php?search=ace+ventura+l%27acchiappanimali -> 1 results
https://ilcorsaronero.info/argh.php?search=ace+ventura+lacchiappanimali -> 0 results

Any idea or any solution to prevent this?

Tnx, Jo

**Comment by Jorman** [comment] 2017-12-15 21:51
Hi, I just see that in past I already opened an issue for the "same" question
https://github.com/Radarr/Radarr/issues/1505

I know that is labeled with low priority, but, do you have any eta about it?

Tnx, Jo

**Comment by galli-leo** [comment] 2017-12-17 12:10
Duplicate of #1505

**Closed by galli-leo** 2017-12-17 12:10 UTC
Labels: enhancement, indexer, priority:low

**Comment by galli-leo** [comment] 2017-12-17 14:02
And I don't currently have any eta :(
