### ISSUE TITLE
Make movie Path clickable with a configurable relative path

### ISSUE THREAD

**Issue by vidarak** [Radarr/Radarr#7229] opened 2022-04-17 18:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When Radarr is running on a server (together with the download client), I would like to be able to click the path of a movie to be taken to the folder in Windows Explorer.

### Describe the solution you'd like

I would like the Path on the movie-view to be clickable with a file:// URL. The URL should be re-mapped to the local path I have in my Windows client via a configuration option that replaces the specific first part of the server path with a specific path used on the client.
Example: 
On the server I may have /zfs/data/movies/1080p/moviename
The folder "/zfs/data" is shared from the server, mapped to Z: drive letter on my Windows workstation.
I would configure Radarr to replace "/zfs/data" with "/Z:" resulting in a clickable path link of "file:///Z:/movies/1080p/moviename" that would open up Windows Explorer.

### Describe alternatives you've considered

I'm just manually locating the folder in Windows Explorer now.

### Anything else?

![image](https://user-images.githubusercontent.com/4713602/163727760-535a6941-bd5b-4183-b336-49608f6e7d25.png)

[AB#3002](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3002)

**Comment by bakerboy448** [comment] 2022-04-17 19:32
Duplicate of https://github.com/Radarr/Radarr/issues/5757

**Closed by bakerboy448** 2022-04-17 19:32 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by vidarak** [comment] 2022-04-17 20:12
Sorry for posting duplicate. I actually only searched for similar topic in open requests.
Also sorry you reject the request. I don't agree with you on the reason for rejection though.
I am fully aware that I COULD access Radarr from many devices, but I would only bother using the link from a device which I know have the folder/drive mapped. I usually have one primary workstation so that would be it.

Please reconsider. It could easily be an optional feature and from a coding logic point of view shouldn't be very hard to implement I think (being a very novice developer/scripter myself).

**Comment by bakerboy448** [comment] 2022-04-17 20:20
Again, no plans to add said functionality.

**Comment by Krandor1** [comment] 2022-04-17 20:32
Not a dev here but I think the big issue is that if support. People have enough issues with remote drive mapping between download client and radar. Now adding in a mapping that can change from machine to machine is little good way to do it. You may access it from only one other machine but what about the person who accessed from multiple?  Link works on some but not others?  Or multiple mappings for every potential client?  

I myself access radar from 2-3 different devices.

**Comment by vidarak** [comment] 2022-04-18 23:08
I'd still want this feature working on 1 client and failing on 5 other less frequently used clients because they don't have the drive mapped the same way as my primary client compared to current situation of not having the feature.
As mentioned, it should be an optional feature that might have a big fat warning sign on it to explain that it would only work on clients that have the same drive mapping as specified in the client-side path parameter. I'm not going to push for it. I get you're against it. Just trying to explain my view. Thanks to all the DEVs for some awesome software!

**Comment by austinwbest** [comment] 2022-04-18 23:26
It would be a neat thing, I've wanted it myself a time or two but it isn't worth the support headache tradeoff nor the configuration to try and reduce the support headaches from it.

Sorry bud.
