### ISSUE TITLE
Auto Sort Advancement(s) - kinda similar to SONARR

### ISSUE THREAD

**Issue by MattGeale** [Radarr/Radarr#6529] opened 2021-08-04 07:42 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem in the slightest, but more of a suggestion for future Radarr deployments. I have a tendancy to micromanage my library so this could perfectly well be a solution that only I would find beneficial but, I'm guessing I'm not the only one who micromanages their media. Another solution that my idea could rectify is removing the need for having multiple Radarr instances for different media types (eg DoVi, HDR, 1080p, ExtendedEdt etc)

**Describe the solution you'd like**
With more and more dual layer DoVi media (disk rips etc) coming out, especially with the dynamic meta intact/a part of the rip, I think there should be a way to have in Radarr detect when there is more than two video tracks in a rip; the HDR core stream as well as the second HEVC dynamic stream. By having this functionality in Radarr, the option to sort media automatically based on this could be implemented too --> pardon the rough explanation but "If(videotrack=2, move (location), elif move (location2)". 

**Describe alternatives you've considered**
Theres nothing really that achieves this unfortunately, but the easiest alternative is to just not micromanage your library. But for people like me who use a mixture of data in their library (disk rips, downloads etc), it'd be a nifty feature to not have to drag and drop files based on how our system is already setup. 

**Additional context**
*The following would run after the movie has been downloaded.* If the tag was implemented, the way I kind of visualised how this would work, in a perfect world, would be the following:
1) Media downloaded to something of an "ingest" folder of user choosing.
2) Radarr, using the already existing standard movie format renaming (with MediaInfo tag) reads through the renamed file name (not folder name)
3) If Radarr detects that in the file name that there is a number "2" or "1", it then moves it to a folder of the end users choosing.

The above is very broad strokes for how it'd work and I'm sure this would be an absolute pain to code, but this type of stuff will probably be beneficial in the future when the .mkv container updates to support proper dual layer media despite (no compromises). I visualise it being implemented in a similar way to a filter - "If(VideoStream=2, move (DoVi Location), elif, move (HDR)". This could also be combined with the already exisiting and implemented datatag, MediaInfo VideoDynamicRange and work in conjunction with something like a mediainfo resolution tag that detects the width/height of the default/first videostream is (3840x2160 vs 1920x1080 etc). 

Following images taken from a recent Radarr DL I did.
![2021-08-04_10-54-30](https://user-images.githubusercontent.com/88370061/128105271-1174799c-675e-4e4f-8aac-ed5402de64d0.png)
![2021-08-04_10-59-58](https://user-images.githubusercontent.com/88370061/128105277-306cc8cf-e49a-4f8d-8e1e-7d5d003aa4a2.png)
![2021-08-04_11-00-37](https://user-images.githubusercontent.com/88370061/128105281-0c07e3b8-24e9-4fc9-8157-4cd6661487f1.png)

[AB#1382](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1382)

**Comment by bakerboy448** [comment] 2021-08-04 12:10
> Similar to Sonarr

Sonarr has nothing like this at all?

Duplicate of #1246

closing in lieu of #153 and #1910

**Closed by bakerboy448** 2021-08-04 12:10 UTC

**Comment by MattGeale** [comment] 2021-08-04 13:09
@bakerboy448 Thanks for pointing me to #1246, I'll try and make something similar to what Bobbintb did in 2018...is it possible to keep this open so that the MediaInfo tags can be implemented in future deployements? What Bobb did is exactly what I want, would just need a little bit of tweaking.
