### ISSUE TITLE
Radarr Tags not added on Trakt list when films are already available in Radarr

### ISSUE THREAD

**Issue by Mrpink200** [Radarr/Radarr#6464] opened 2021-07-11 17:15 UTC
Hi. I ve built trakt custom list based on cannes movies i was thinking that radarr would add all the movies in th list with the tag (what it does) and woul apply the tag if the movies were already found in radarr what it does not.
it s a bit annoying trying to match radarr list with radarr list
Could it be possible to add an option in Trakt list to apply the radarr tags for all the movies, even if the film is already in radarr

Many thanks

[AB#1252](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1252)

**Comment by bakerboy448** [comment] 2021-07-11 18:32
Duplicate of https://github.com/Radarr/Radarr/issues/2529

**Closed by bakerboy448** 2021-07-11 18:32 UTC
