### ISSUE TITLE
Add Monitor Toggle button in home view

### ISSUE THREAD

**Issue by Rathna-K** [Radarr/Radarr#4116] opened 2020-01-31 21:14 UTC
Can we please add a monitor toggle button in the home view so we dont have to the detail page to monitor a movie? if it already exists let me know how to use it. if no plans to do it then can you provide some guidance on how to achieve this manually in compiled UI pages?  

like this 
![image](https://user-images.githubusercontent.com/3465346/73574753-7c2cd800-4444-11ea-929c-dde6f164e12b.png)
in 

![image](https://user-images.githubusercontent.com/3465346/73574780-8ea71180-4444-11ea-9528-615157267e09.png)

**Comment by Rathna-K** [comment] 2020-02-03 20:36
anyway to get this looked at ? is this not of interest to anyone? would be nice to monitor a movie from the home itself instead of going to detail view for each movie right?

**Comment by ta264** [comment] 2020-02-03 20:50
If you find yourself regularly changing monitored options your doing something wrong. For batch jobs you can use movie editor. Jump on the discord if you need help setting it up as intended

**Comment by Rathna-K** [comment] 2020-02-03 21:42
Not regularly. New to Radar. so starting add movies using the TMDB upcoming API. I have about 300 movies that I am yet to go through and mark as Monitor for the ones that are interesting. Is there a link to Radarr for discord ? Haven’t used discord before so pardon my ignorance.

**Comment by Qstick** [comment] 2020-02-04 01:54
@ta264 may not hurt to allow click on monitor icon to toggle when in Movie Editor mode in Aphrodite, if you are not opposed to that? Not really needed, but may save some clicks for some

**Comment by Rathna-K** [comment] 2020-02-04 16:55
if there is no plans to add can you at least give me some idea on how to make it locally? i looked at front end folder and i am guessing i can probably add the control in one of the js? but in compiled install I only see UI folder. so do I need to package it? thanks in advance for any help @ta264

**Comment by Qstick** [comment] 2020-07-09 18:16
Closing this, editor is easy enough already without adding the extra control

**Closed by Qstick** 2020-07-09 18:16 UTC
Labels: aphrodite, feature request, ui
