### ISSUE TITLE
Two file sizes per quality definition.

### ISSUE THREAD

**Issue by jhfry** [Radarr/Radarr#1687] opened 2017-06-15 16:55 UTC
**Problem:**
I have found that my sweet spot for acceptable quality for every day viewing is around 5GB for a 720P or 1080P H264 with 6 channel audio (DTS or AAC)... usually comes in about Netflix quality, sometimes even better, which is more than enough to enjoy the movie and not be distracted by artifacts.

Of course there are some films that I dim the lights and pop some popcorn to watch... these I want to download at higher bitrates since I fully intend to immerse myself and don't want any distracting compression artifacts.

Unfortunately, I don't see any way to create a profiles with different file size maximums for the same "class" of file.  So I either waste space with large downloads for everything, or have to manually re download something I wanted in a higher quality.

**Possible solution**
Add an additional slider on each quality definition "size limit" bar between the max and the min size. Anything above this value is "high bitrate" below is "standard bitrate".  Then, when we add a movie, we select our profile and next to that we select a radio button for high, standard, or any bitrate.

So if my profile is the stock "HD - 720p/1080p", and I set my "Blueray-1080p" sliders to 0, 8GB, and 16GB.  Anything between 0 and 8GB is considered standard bitrate... anything between 8GB and 16GB is high bitrate.  I just tick the high box when add a movie if I want a high bitrate copy, or set it to standard if I want to save space, or put it to any if I dont care.

Anyone who doesn't want this granularity can set the threshold slider equal to the max file size, then all "standard" movies would cover the entire size range.

**Comment by galli-leo** [comment] 2018-02-06 23:49
Duplicate of #1510

**Closed by galli-leo** 2018-02-06 23:49 UTC
