### ISSUE TITLE
Add existing movies like Sickbeard adds tv-series

### ISSUE THREAD

**Issue by deathbybandaid** [Radarr/Radarr#152] opened 2017-01-11 14:23 UTC
I abandoned Sickbeard for Sonarr  seemingly forever ago, and the one feature Sonarr always lacked, in my opinion, was the way Sickbeard added shows.

I, and many others likely have large movie libraries, and it would be a great deal nicer to add them to the program in bulk, and be asked about ones that the program was unsure about. (Instead of adding them all one at a time)

**Comment by fedoranimus** [comment] 2017-01-11 14:25
Related to #150

**Comment by onedr0p** [comment] 2017-01-11 14:30
Closing because it is a duplicate of #150

**Closed by onedr0p** 2017-01-11 14:30 UTC
