### ISSUE TITLE
Add ability to filter by language of file on disk

### ISSUE THREAD

**Issue by Masamune3210** [Radarr/Radarr#10086] opened 2024-06-14 22:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes, radarr manages to fetch languages which I do not want. I am ok with this, but I would like the ability to filter by language so that I can sort them into their own category just like original language or other metadata

### Describe the solution you'd like

![image](https://github.com/Radarr/Radarr/assets/1053504/0ab5fd09-1c7b-4d51-9245-25425dc00608)
To have Language as an option to filter by just like Original Language

### Describe alternatives you've considered

I routinely go through and try to look at latest fetches to check, but sometimes I forget and its tedious as I have to go into each movie manually to look

### Anything else?

First request, I apologize if I missed anything or if I am unaware of some way of doing this that already exists. Thanks for the tool

**Comment by bakerboy448** [comment] 2024-06-14 22:27
Duplicate of https://github.com/Radarr/Radarr/issues/9398

**Closed by bakerboy448** 2024-06-14 22:27 UTC
Labels: Type: Feature Request, Status: Won't Fix

**Comment by Masamune3210** [comment] 2024-06-15 01:07
Believe it or not, I did search, just apparently not thoroughly enough.

As for the argument that the filters are for filtering by movie properties and not movie file properties, there are already filters for a lot of things that have no basis on the movie itself, like Size on disk, Release Group, Path, and so on.

**Comment by bakerboy448** [comment] 2024-06-15 01:32
It's not an argument it's a statement. No plans to change that.

Please use [Discord](http://lidarr.audio/discord) for questions.
