### ISSUE TITLE
Import Exclusions are ignored

### ISSUE THREAD

**Issue by IvanJosipovic** [Radarr/Radarr#995] opened 2017-03-03 16:57 UTC
**Description:**
Movies that have been previously added to the Import Exclusions have been re-added to the Movies List.
I checked a number of movies and the imdb ids are in the Import Exclusions list.

**Radarr Version:** 0.2.0.432

**Logs:**
Logs show that movies have been added the list.
Additionally this entry is logged a number of times,
17-3-2 20:36:17.0|Info|NetImportSearchService|Movie: {0} was found but will not be added because it {exclusion} was found on your exclusion list

**Comment by geogolem** [comment] 2017-03-03 17:14
Can you please look at the discussion in this issue: https://github.com/Radarr/Radarr/issues/981

Is your situation the same?

**Comment by geogolem** [comment] 2017-03-03 17:14
oh interesting, it is logging that it wont be added, but is added anyway?

**Comment by geogolem** [comment] 2017-03-03 17:17
hmm, ok. wait. i am seeing something happening with this feature now.. investigating..

**Comment by geogolem** [comment] 2017-03-03 17:28
Just pasting this here for reference: https://github.com/Radarr/Radarr/issues/961

**Comment by geogolem** [comment] 2017-03-03 17:28
there is definitely something going on with the latest driver and this feature --> not sure what happened.. but I am investigating..

**Comment by IvanJosipovic** [comment] 2017-03-03 17:29
In my case the movie was auto imported.
Additionally, the log entry String.Format has a bug where it doesn't show the actual movie that was excluded.
Thanks!

**Comment by geogolem** [comment] 2017-03-03 17:31
ya i think the reason its not printing them ovie, is the same reason its not being excluded.. I am debugging now. and for some reason we check all the movies but dont act on what we find..

then later, print out the message when we arent even handling a movie anymore --> so there is no title to print.. Anyway, im not sure how this bug got introduced because it was working before.. I am investigating. .will report back here .. thanks for your issue report!! :)

**Comment by geogolem** [comment] 2017-03-03 17:46
no you are right.. i think the whole thing is just caused by the print statement not being right.. im just teting now..

**Comment by geogolem** [comment] 2017-03-03 18:01
so the movie was definietly not printing right in that case.... im not sure how/why but i believe that was causing the move to be added anyway ...  I put a fix in via: https://github.com/Radarr/Radarr/pull/996

I changed the code to print the movie out properly... (not sure how it was wrong before without noticing sorry.. my bad)...

Im not 100% sure why, but i think that fixes the behavior problem... It seems to be working fine for me now.. Could you please give it a try and let me know if your issue is resolved, otherwise I will have to investigate further.

Thanks!

**Comment by geogolem** [comment] 2017-03-03 18:05
I have fifty shades on my exclusions list (and not in my radarr library but is on my trakt watchlist), and i dont have logan on my trakt watchlist but it is in my library.. and i am getting this result: 

![image](https://cloud.githubusercontent.com/assets/23205277/23562780/f2e27c22-0011-11e7-85d2-12fb08df9061.png)


this is what i expect --> i just did this as a testcase... 

Look forward to hearing back on whether or not this resolved your issue.

**Comment by IvanJosipovic** [comment] 2017-03-03 18:28
I'm on build 0.2.0.433 and can confirm the issues is not fixed.
Result is the same, some movies are ignored and some are not.

In the log below tt0369610 was added even though its in the exclusion list.

`17-3-3 10:23:39.7|Info|NetImportSearchService|Found 70 movies on your auto enabled lists not in your library
17-3-3 10:23:39.7|Info|NetImportSearchService|Movie: [tt2126235][Collide] was found but will not be added because tt2126235 was found on your exclusion list
17-3-3 10:23:40.3|Info|NetImportSearchService|Movie: [tt4116284][The Lego Batman Movie] was found but will not be added because tt4116284 was found on your exclusion list
17-3-3 10:23:40.6|Info|NetImportSearchService|Movie: [tt3922818][The Space Between Us] was found but will not be added because tt3922818 was found on your exclusion list
17-3-3 10:23:40.9|Info|NetImportSearchService|Movie: [tt4972582][Split] was found but will not be added because tt4972582 was found on your exclusion list
17-3-3 10:23:41.2|Info|NetImportSearchService|Movie: [tt4846340][Hidden Figures] was found but will not be added because tt4846340 was found on your exclusion list
17-3-3 10:23:41.7|Info|NetImportSearchService|Movie: [tt3416532][A Monster Calls] was found but will not be added because tt3416532 was found on your exclusion list
17-3-3 10:23:42.1|Info|NetImportSearchService|Movie: [tt3470600][Sing] was found but will not be added because tt3470600 was found on your exclusion list
17-3-3 10:23:42.4|Info|NetImportSearchService|Movie: [tt2671706][Fences] was found but will not be added because tt2671706 was found on your exclusion list
17-3-3 10:23:42.7|Info|NetImportSearchService|Movie: [tt3748528][Rogue One: A Star Wars Story] was found but will not be added because tt3748528 was found on your exclusion list
17-3-3 10:23:43.0|Info|NetImportSearchService|Movie: [tt3783958][La La Land] was found but will not be added because tt3783958 was found on your exclusion list
17-3-3 10:23:43.3|Info|NetImportSearchService|Movie: [tt4624424][Storks] was found but will not be added because tt4624424 was found on your exclusion list
17-3-3 10:23:44.0|Info|MovieService|Adding Movie [tt0369610][Jurassic World] Path: [D:\{removed dir}\Jurassic World (2015)]`

**Comment by geogolem** [comment] 2017-03-03 18:29
i have a feeling there must be some bug somewhere in the code.. because i just cant believe that, that fixed it..

**Comment by IvanJosipovic** [comment] 2017-03-03 18:49
I was able to step through the code. The issue is that when the movie is imported the movie.ImdbId is null. This is why it is re-added to the movies list every time.

**Comment by geogolem** [comment] 2017-03-03 18:50
ya i was just thinking that.. (i also was going to prepare a driver with _logger.Debug... so i could trace.. your situation.. i tried with jurassic world and i dont have that probelm.. so i need to figure out why in your case it is null.

**Comment by geogolem** [comment] 2017-03-03 18:53
i think maybe i need to move the check lower
after the mapping....

**Comment by geogolem** [comment] 2017-03-03 18:55
i wonder, if all the exclusions are tmdbid only.. if that will solve the problem.. I know that radarr uses tmdb over imdb..

**Comment by geogolem** [comment] 2017-03-03 19:11
give me a few more minutes. i am just building and testing a fix..

**Comment by geogolem** [comment] 2017-03-03 19:19
If I give you an updated NetImportSearchService.cs, would you be able to build and test?

**Comment by IvanJosipovic** [comment] 2017-03-03 19:22
Yep, shoot it my way.

**Comment by geogolem** [comment] 2017-03-03 19:27
Here is the commit: https://github.com/geogolem/Radarr/commit/4d6ce7e791682dd11d8f7b779596fc58833d6fdf

Here is the branch it was committed to:
https://github.com/geogolem/Radarr/tree/exclusionsFix

**Comment by geogolem** [comment] 2017-03-04 00:32
Please let me know if this resolved your issue ----> or if you are unable to test it .. :)

**Comment by IvanJosipovic** [comment] 2017-03-04 04:15
I was able to test the updated Class, apart from one bug fix it appears to work great. Only downside is that this slowed down the process significantly. I guess switching to primary using TmdbId would be the best solution.

I added a null check for the result, a TV series id (tt3920596) made it into my exclusion list which would return null, probably originated from Couch Potato.

`var result = _movieInfo.GetMovieInfo(exclusion);

if (result == null)
{
	_logger.Info("Cant get movie info for {0}", exclusion);
	continue;
}`

**Comment by geogolem** [comment] 2017-03-04 04:20
ok.. cool... regarding performance.. i might be able to improve that.. ill look into that tomoorow...  at least we know why the feature was failing.

**Comment by geogolem** [comment] 2017-03-04 08:03
So this is what I actually want to do... 

When you add a tag via the Settings--> List area, there is a quick API check to the backend which returns the movieInfo to the Frontend. This is happening anyway - to validate the imdbId or tmdbId.. It uses the same method as our fix when we had to lookup the tmdbId for an imdbID.. 

My plan was to massage the tag the user typed in to something more descriptive since we have all this information..

When you type in an imdb ID, the FE could literally add a tag [imdbId][TITLE (YEAR)][tmdbId]

so even though the user only typed the tmdbId from that point forward it would be as though they typed all that info.. 

then in the BE we wouldalready have the TMDBId for use...

so there would be no performance cost.. since we are already looking up the movieInfo when you manually add an exclusion anyway, we are just keeping more of the info...

Also when deleting movies we already have this info and so when radarr adds the tag it can construct it properly..

Here is the problem - I couldnt figure out how to cleanly and easily manipulate the tags as the user types them in.. Some googling around found this: 
https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/432

so it looks like I should be able to do what I want --> when bootstrap tags is updated... Imnot sure about trying to get his "unstable" version.. but I might look into it..

**Comment by geogolem** [comment] 2017-03-04 08:12
@onedr0p : Please read the comment and reference to bootstrap tags directly above this --> with that new feature in the tags - i will be able to accomplish what I originally wanted with the exclusions...

**Comment by geogolem** [comment] 2017-03-05 06:48
@IvanJosipovic : Hang tight I have a much better solution coming for this soon. I think I have finished implementing it - but i just need to test and verify before merging... Will keep you posted.

**Comment by geogolem** [comment] 2017-03-05 07:09
Please try with the latest driver and let me know how it goes --> incompatibel exclusions from before this change will simpyl be ignored (shouldnt cause a crash - i dont think)

**Comment by geogolem** [comment] 2017-03-06 00:43
I am going to close this issue off since it should be a non-issue in the latest release. If you still have problems or suggestions Please let me know.

**Closed by geogolem** 2017-03-06 00:43 UTC
Labels: bug, enhancement, priority:medium, under investigation

**Comment by IvanJosipovic** [comment] 2017-03-06 16:50
I noticed another issues with the latest build (0.2.0.459)

If I use the StevenLu List, all movies are imported regardless if they are in the Exclusion List.
I have't looked through the code yet, I assume its because this list only returns IMDB ids and we rely on TMDb.

**Comment by geogolem** [comment] 2017-03-06 18:24
i have no experience with the StevenLu lists -- but i will look into this soon.
Your suggestion may be the case, but internally radarr maps everything to a tmdb movie... which is why tmdbId is more reliable internally - so I wouldnt think this would be aproblem; however, i really dont know but I will look into this soon.

**Comment by geogolem** [comment] 2017-03-08 19:51
Can you let me know if the StevenLu Lists issue is resolved in the current build?

**Comment by dhaos21** [comment] 2017-03-09 10:44
i just updated to the latest nightly as the exclusions was not working for me and now i am getting these errors. (i also use stevenlu's list)

http://pastebin.com/XvPzK7Qg

**Comment by geogolem** [comment] 2017-03-09 11:58
@dhaos21 : I think the exclusions are working properly.. according to your log... I think at least. 

17-3-9 10:41:20.0|Info|NetImportSearchService|Collide (collide-195590) will not be added since it was found on the exclusions list

it then looks like it didnt add Collide. The errors are from something else, other than the import exclusions.. and I dont think have anything to do with import exclusions. Could you please perhaps see if you can get those errors without exclusions at all and then open a new issue.

**Comment by dhaos21** [comment] 2017-03-09 12:09
well when i first tried it logan was in my wanted list and it was erroring on Logan, i removed logan from my list and then let the automated list re-add it, it seems to be tripping up when it tried to add a movie already in my wanted list.
