### ISSUE TITLE
Sending PTP torrent to deluge gets error (Possibly related to #761?)

### ISSUE THREAD

**Issue by tymanthius** [Radarr/Radarr#1109] opened 2017-03-10 16:28 UTC
**Description:**

ANY torrent I've tested from search from PTP times out.  But can grab a torrent from other providers just fine.  Sometimes the same torrent.

I've tried from remote browser using a proxy, from remote browser w/o a proxy, and from inside my local network.  Can't really do via local host as this is running on a headless server in an LXC container.

**Radarr Version:**

0.2.0.453 - but has been an issue for a couple of weeks

**Logs:**

```

NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:61 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult] (NzbDrone.Common.Http.JsonRpcRequestBuilder requestBuilder, System.String method, System.Object[] arguments) [0x0006f] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:234 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult] (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings, System.String method, System.Object[] arguments) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:180 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.SetLabel (System.String hash, System.String label, NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:158 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.AddFromTorrentFile (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String hash, System.String filename, System.Byte[] fileContent) [0x00027] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:54 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteEpisode, System.String torrentUrl) [0x001aa] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:269 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x00148] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:125 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x000a3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:119 
  at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease (NzbDrone.Api.Indexers.ReleaseResource release) [0x00041] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:73 
  at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:47 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 
```

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by tymanthius** [comment] 2017-03-10 16:32
Forgot to mention: Testing PTP from settings works.

**Comment by onedr0p** [comment] 2017-03-10 16:38
This is fixed in the latest nightly.

**Comment by onedr0p** [comment] 2017-03-10 16:39
Please confirm.

**Comment by tymanthius** [comment] 2017-03-10 16:40
Awesome. I'll go grab it and see.  :)

**Comment by tymanthius** [comment] 2017-03-10 16:41
Apparently I'm stupid today - where can I grab the nightly?

**Comment by tymanthius** [comment] 2017-03-10 16:49
Update:  Does not appear to be working.  Failed, and here's the log info:

'''
NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:61 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult] (NzbDrone.Common.Http.JsonRpcRequestBuilder requestBuilder, System.String method, System.Object[] arguments) [0x0006f] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:234 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult] (NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings, System.String method, System.Object[] arguments) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:180 
  at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.SetLabel (System.String hash, System.String label, NzbDrone.Core.Download.Clients.Deluge.DelugeSettings settings) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:158 
  at NzbDrone.Core.Download.Clients.Deluge.Deluge.AddFromTorrentFile (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String hash, System.String filename, System.Byte[] fileContent) [0x00027] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:54 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteEpisode, System.String torrentUrl) [0x001aa] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:269 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x00148] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:125 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie) [0x000a3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:119 
  at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease (NzbDrone.Api.Indexers.ReleaseResource release) [0x00041] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:73 
  at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:47 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

'''

**Comment by onedr0p** [comment] 2017-03-10 17:04
Does deluge connect in sonarr? Are you using the same settings there?

**Comment by tymanthius** [comment] 2017-03-10 17:06
Yes, works in sonarr, works in radarr with other torrent providers, and the settings are the same from sonarr to radarr (copy paste is a wonderful thing).

I could test by setting up PTP in Jackett and see what happens. Would that be informative?

**Comment by onedr0p** [comment] 2017-03-10 17:11
Interesting... So both, PTP and deluge successfully test. But you cannot download the torrent. That's a new one.

**Comment by tymanthius** [comment] 2017-03-10 17:15
That is correct.  The only thing I haven't tried is deleteing PTP then re-adding it.  So I did that, and no change.

**Comment by onedr0p** [comment] 2017-03-10 17:22
You have the latest version of deluge?  

Is your deluge accessable to the outside world? If so I can run tests from my end. Please get a hold of me on discord and we can find sometime to debug this. I cannot reproduce this on my end using ptp and deluge.

**Comment by tymanthius** [comment] 2017-03-10 17:26
Just to post here:  I ran apt-get update && apt-get dist-upgrade just now and no updates for deluge.  

Package deluged & deluge-common is Version: 1.3.10-3

I'll log into discord.

**Comment by onedr0p** [comment] 2017-03-10 21:22
You never gave the username / password to deluge on discord :/

**Comment by onedr0p** [comment] 2017-03-11 03:30
One thing to try is another download client to make sure it's not deluge, if you can spin up a vm with transmission or rtorrent and give it a shot I'm curious what will happen.

**Comment by onedr0p** [comment] 2017-03-11 16:15
Closing, because it is a duplicate of #761

I wonder if you and @AdamPan can post your set up and see if you guys are using the same things maybe?

**Closed by onedr0p** 2017-03-11 16:15 UTC
Labels: bug, cannot reproduce, indexer
