### ISSUE TITLE
radarr goes unresponsive during movie import with kodi connection set to update with trace logging

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#7578] opened 2022-09-03 05:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

added two movies to radarr, manually grabbed and saw radarr crash after importing the first movie, puked after doing the nfo. left sfv in the folder. ui no longer responds, process just hung. start new radarr session it pukes due to previous radarr running.

killed process and started new radarr instance, it finished up the previous import then proceeded to crash on the next import in the same fashion. puked after generating nfo.

now it shows both movies stuck in activity with "No files found are eligible for import" for each.

### Expected Behavior

not crash on importing and generating metadata

### Steps To Reproduce

enable kodi metadata with all options checked. add movie, and wait after importing...

### Environment

```markdown
- OS: Win 10
- Radarr: 4.2.3.6555
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

https://pastebin.com/raw/T44YkMbi

[AB#3695](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3695)

**Comment by thezoggy** [comment] 2022-09-03 05:10
tried toggling off the recent kodi metadata collections option, tried another download.. writes nfo then hangs on next part. so still crashing :/

```
2022-09-03 00:06:01.5|Debug|MetadataService|Writing Movie File Metadata to: M:\Movies-HD\Big.Fat.Liar.(2002)\movie.nfo
2022-09-03 00:06:01.5|Trace|EventAggregator|Publishing MovieFileImportedEvent
2022-09-03 00:06:01.5|Trace|EventAggregator|MovieFileImportedEvent -> NotificationService
2022-09-03 00:06:01.5|Debug|NotificationService|No tags set for this notification.
2022-09-03 00:06:01.5|Trace|HttpClient|Req: [POST] http://192.168.0.11:8089/jsonrpc: VideoLibrary.GetMovies(["file","imdbnumber"])
2022-09-03 00:06:01.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-03 00:06:01.7|Trace|HttpClient|Res: [POST] http://192.168.0.11:8089/jsonrpc: 200.OK (493600 bytes) (151 ms)
```

**Comment by Qstick** [comment] 2022-09-03 14:52
What version of Kodi?

**Comment by thezoggy** [comment] 2022-09-03 15:32
19.4 which ive been running for awhile now. i will say i do run kodi headless in docker, and last time radarr imported a movie and didnt crash was on aug 27th.

**Comment by Qstick** [comment] 2022-09-03 18:53
Can't reproduce this with Kodi 19.4 and Radarr Nightly on Windows. Works as intended. 

```
2022-09-03 13:32:08.3|Trace|HttpClient|Req: [POST] http://localhost:8080/jsonrpc: GUI.ShowNotification("Radarr - Deleted", "Dracula III: Legacy (2005) [Bluray-1080p] https://www.imdb.com/title/tt0303929/", "https://raw.github.com/Radarr/Radarr/develop/Logo/64.png", 5000)
2022-09-03 13:32:08.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-03 13:32:08.3|Trace|HttpClient|Res: [POST] http://localhost:8080/jsonrpc: 200.OK (47 bytes) (8 ms)
2022-09-03 13:32:08.3|Trace|HttpClient|Response content (47 bytes): {"id":"38353df5","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:08.3|Trace|XbmcJsonApiProxy|Response: {"id":"38353df5","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:08.3|Trace|XbmcJsonApiProxy|Looking for error in response, {"id":"38353df5","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:10.7|Trace|HttpClient|Req: [POST] http://localhost:8080/jsonrpc: VideoLibrary.GetMovies(["file","imdbnumber"])
2022-09-03 13:32:10.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-03 13:32:10.8|Trace|HttpClient|Res: [POST] http://localhost:8080/jsonrpc: 200.OK (925 bytes) (12 ms)
2022-09-03 13:32:10.8|Trace|HttpClient|Response content (925 bytes): {"id":"1121ca70","jsonrpc":"2.0","result":{"limits":{"end":5,"start":0,"total":5},"movies":[{"file":"D:\\Data\\Dracula III Legacy (2005)\\Dracula.III.Legacy.2005.1080p.Bluray.X264-BARC0DE.mkv","imdbnumber":"10579","label":"Dracula III: Legacy","movieid":1},{"file":"D:\\Data\\Dracula III Legacy (2005)\\Dracula.III.Legacy.2005.REPACK.720p.BluRay.x264-HALCYON-Obfuscated.mkv","imdbnumber":"10579","label":"Dracula III: Legacy","movieid":2},{"file":"D:\\Data\\James Bond 007 - GoldenEye (1995)\\GoldenEye.1995.720p.BluRay.x264AAC-Ozlem.mp4","imdbnumber":"710","label":"GoldenEye","movieid":3},{"file":"D:\\Data\\The Dark Knight (2008)\\The Dark Knight (2008) Bluray-720p - The Dark Knight Collection - tt0468569.mp4","imdbnumber":"155","label":"The Dark Knight","movieid":4},{"file":"D:\\Data\\The Wannabes (2022)\\Les.Vedettes.2022.FRENCH.1080p.WEB.H264-SEiGHT.mkv","imdbnumber":"740460","label":"The Wannabes","movieid":5}]}}
2022-09-03 13:32:10.8|Trace|XbmcJsonApiProxy|Response: {"id":"1121ca70","jsonrpc":"2.0","result":{"limits":{"end":5,"start":0,"total":5},"movies":[{"file":"D:\\Data\\Dracula III Legacy (2005)\\Dracula.III.Legacy.2005.1080p.Bluray.X264-BARC0DE.mkv","imdbnumber":"10579","label":"Dracula III: Legacy","movieid":1},{"file":"D:\\Data\\Dracula III Legacy (2005)\\Dracula.III.Legacy.2005.REPACK.720p.BluRay.x264-HALCYON-Obfuscated.mkv","imdbnumber":"10579","label":"Dracula III: Legacy","movieid":2},{"file":"D:\\Data\\James Bond 007 - GoldenEye (1995)\\GoldenEye.1995.720p.BluRay.x264AAC-Ozlem.mp4","imdbnumber":"710","label":"GoldenEye","movieid":3},{"file":"D:\\Data\\The Dark Knight (2008)\\The Dark Knight (2008) Bluray-720p - The Dark Knight Collection - tt0468569.mp4","imdbnumber":"155","label":"The Dark Knight","movieid":4},{"file":"D:\\Data\\The Wannabes (2022)\\Les.Vedettes.2022.FRENCH.1080p.WEB.H264-SEiGHT.mkv","imdbnumber":"740460","label":"The Wannabes","movieid":5}]}}
2022-09-03 13:32:10.8|Trace|XbmcJsonApiProxy|Looking for error in response, {"id":"1121ca70","jsonrpc":"2.0","result":{"limits":{"end":5,"start":0,"total":5},"movies":[{"file":"D:\\Data\\Dracula III Legacy (2005)\\Dracula.III.Legacy.2005.1080p.Bluray.X264-BARC0DE.mkv","imdbnumber":"10579","label":"Dracula III: Legacy","movieid":1},{"file":"D:\\Data\\Dracula III Legacy (2005)\\Dracula.III.Legacy.2005.REPACK.720p.BluRay.x264-HALCYON-Obfuscated.mkv","imdbnumber":"10579","label":"Dracula III: Legacy","movieid":2},{"file":"D:\\Data\\James Bond 007 - GoldenEye (1995)\\GoldenEye.1995.720p.BluRay.x264AAC-Ozlem.mp4","imdbnumber":"710","label":"GoldenEye","movieid":3},{"file":"D:\\Data\\The Dark Knight (2008)\\The Dark Knight (2008) Bluray-720p - The Dark Knight Collection - tt0468569.mp4","imdbnumber":"155","label":"The Dark Knight","movieid":4},{"file":"D:\\Data\\The Wannabes (2022)\\Les.Vedettes.2022.FRENCH.1080p.WEB.H264-SEiGHT.mkv","imdbnumber":"740460","label":"The Wannabes","movieid":5}]}}
2022-09-03 13:32:10.8|Debug|XbmcService|Updating movie [Dracula III: Legacy (2005)][tt0303929, 10579] (Path: D:\Data\Dracula III Legacy (2005)) on XBMC host: localhost:8080
2022-09-03 13:32:13.8|Trace|HttpClient|Req: [POST] http://localhost:8080/jsonrpc: VideoLibrary.Scan("D:\\Data\\Dracula III Legacy (2005)")
2022-09-03 13:32:13.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-03 13:32:13.8|Trace|HttpClient|Res: [POST] http://localhost:8080/jsonrpc: 200.OK (47 bytes) (13 ms)
2022-09-03 13:32:13.8|Trace|HttpClient|Response content (47 bytes): {"id":"094e219e","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:13.8|Trace|XbmcJsonApiProxy|Response: {"id":"094e219e","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:13.8|Trace|XbmcJsonApiProxy|Looking for error in response, {"id":"094e219e","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:16.3|Trace|HttpClient|Req: [POST] http://localhost:8080/jsonrpc: VideoLibrary.Clean()
2022-09-03 13:32:16.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-03 13:32:16.9|Trace|HttpClient|Res: [POST] http://localhost:8080/jsonrpc: 200.OK (47 bytes) (568 ms)
2022-09-03 13:32:16.9|Trace|HttpClient|Response content (47 bytes): {"id":"c7efb550","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:16.9|Trace|XbmcJsonApiProxy|Response: {"id":"c7efb550","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:16.9|Trace|XbmcJsonApiProxy|Looking for error in response, {"id":"c7efb550","jsonrpc":"2.0","result":"OK"}
2022-09-03 13:32:16.9|Trace|EventAggregator|MovieFileDeletedEvent <- NotificationService
```

**Comment by thezoggy** [comment] 2022-09-03 19:49
as noted on discord, test works fine:
```
2022-09-03 11:28:49.0|Trace|HttpClient|Req: [POST] http://192.168.0.11:8089/jsonrpc: GUI.ShowNotification("Test Notification", "Success! Kodi has been successfully configured!", "https://raw.github.com/Radarr/Radarr/develop/Logo/64.png", 2000)
2022-09-03 11:28:49.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-03 11:28:49.0|Trace|HttpClient|Res: [POST] http://192.168.0.11:8089/jsonrpc: 200.OK (47 bytes) (4 ms)
2022-09-03 11:28:49.0|Trace|HttpClient|Response content (47 bytes): {"id":"5d6888c3","jsonrpc":"2.0","result":"OK"}
2022-09-03 11:28:49.0|Trace|XbmcJsonApiProxy|Response: {"id":"5d6888c3","jsonrpc":"2.0","result":"OK"}
2022-09-03 11:28:49.0|Trace|XbmcJsonApiProxy|Looking for error in response, {"id":"5d6888c3","jsonrpc":"2.0","result":"OK"}
```

if i turned off update library then it works fine (just doesnt do CDH and remove release from sab).


trying the command manually,

getting movies:
`/jsonrpc?request={"jsonrpc": "2.0", "id": 1, "method": "VideoLibrary.GetMovies", "params": {"properties": ["file","imdbnumber"]} }`

that works fine.. but i found something i think might be the culprit.. testing

**Comment by thezoggy** [comment] 2022-09-05 01:41
was on: 4.2.3.6559
downgraded to: 4.2.2.6503

same issue 

radarr movies movie+writes nfo and goes unresponsive after VideoLibrary.GetMovies, then ~25 mins until it shows XbmcJsonApiProxy response. then 15 mins to process it, then another 25 mins to update movie to denote its imported. and then does scan for wrong movie.

tried 4.2.1.6478 also same issue. if i change logging from trace to info or debug, then the whole thing takes ~2 seconds instead of 1+ hour.!

**Comment by Qstick** [comment] 2022-09-05 15:13
@psylenced after some digging on discord, this seems to be similar issue with log cleansing that you fixed on the postgres regex. It's hanging for 10+ minutes in log cleanse. Any other opportunities for improvement there?

@thezoggy do you have a full response from Kodi that you are willing to share.

**Comment by thezoggy** [comment] 2022-09-05 15:14
Sure thing, I'll msg ya on discord

**Comment by psylenced** [comment] 2022-09-06 03:32
@Qstick I didn't really do much optimisation.

Just ran the regex in isolation timing each individual variation. Then fixed the broken one as minimally as possible.

Can have a look at this one too.

**Closed** 2022-09-07 03:34 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by thezoggy** [comment] 2022-09-07 05:24
can confirm that 4.2.3.6566 resolved the issue, with trace logging it imported the movie within ~2 seconds.
