### ISSUE TITLE
Brazilian Portuguese for metadata, radarr displays only Portuguese from Portugal

### ISSUE THREAD

**Issue by Havokdan** [Radarr/Radarr#4815] opened 2020-08-03 23:45 UTC
Brazilian Portuguese for metadata? Radarr displays only Portuguese from Portugal. Example:

https://www.imdb.com/title/tt0399146/?ref_=fn_al_tt_1

Original name: A History of Violence
Portugal name:  Uma História de Violência
Brazilian name: Marcas da Violência

Not to mention that all other content comes from the wrong language.

**Comment by Qstick** [comment] 2020-08-04 11:47
Dupe of #1626

**Closed by Qstick** 2020-08-04 11:47 UTC
Labels: feature request
