### ISSUE TITLE
Filter by files in relative path

### ISSUE THREAD

**Issue by zazabozaza** [Radarr/Radarr#10481] opened 2024-09-25 12:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi, 

I apologise if this exists already I promise i did look up all the titles that could be similar to this. I like to have spanish and english subtitles for each movie. Sometimes movies come missing one of the languages and I wish there was a way for me to see that from radarr

### Describe the solution you'd like

I would love to able to filter based on files within the relative path for example filtering movie files that have .srt files within them

### Describe alternatives you've considered

The only alternative I can think of is to manually divide them up but with a large library that takes a lot of time

### Anything else?

No

**Comment by bakerboy448** [comment] 2024-09-25 13:37
Duplicate of multiple issues.
No plans for File filtering / non-movie attribute properties filtering from the movie index

use bazarr to manage subtitles

**Closed by bakerboy448** 2024-09-25 13:37 UTC
Labels: Type: Feature Request, Status: Needs Triage
