### ISSUE TITLE
Permit Custom Format Score based on tracker.

### ISSUE THREAD

**Issue by Zauxst** [Radarr/Radarr#9091] opened 2023-08-27 19:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The custom format score does not allow to score trackers.

### Describe the solution you'd like

The capability to add score to trackers and to be able to upgrade until the perfect score is met or to upgrade until the prefer tracker is met.

### Describe alternatives you've considered

n/a

### Anything else?

No

**Comment by bakerboy448** [comment] 2023-08-27 19:11
Duplicate of https://github.com/Radarr/Radarr/issues/6697

**Closed by bakerboy448** 2023-08-27 19:11 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by Zauxst** [comment] 2023-08-27 20:05
Hey thanks. I actually searched for the issue and didn't find anything. I'll follow that instead. 

Thanks again for your support!!!
