### ISSUE TITLE
Block Release From Interactive Search Without Grabbing

### ISSUE THREAD

**Issue by owine** [Radarr/Radarr#9565] opened 2024-01-08 17:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If you have multiple indexers, a bad release that you do not want may be added to multiple indexers. Currently, the only way to blocklist a release is to grab the release and blocklist it from the queue. This means you have to spend API grabs (and potentially dip into traffic buckets/ratio) for those grabs (even if partial) just to load into the queue to simply remove and block.

### Describe the solution you'd like

Add a button to each release on interactive search to add that release to the blocklist. You may do an interactive search and see a number that you know you do not want want want to block and ensure they are not grabbed and being able to premptively block them from the search screen would be a good feature. This would be similar to the `x` on a movie History to mark a grab as `Failed` which also adds to the blocklist.

### Describe alternatives you've considered

Not aware of other ways to add to the blocklist.

### Anything else?

baker was framed

**Comment by bakerboy448** [comment] 2024-01-08 17:44
Duplicate of https://github.com/Radarr/Radarr/issues/5911

**Closed by bakerboy448** 2024-01-08 17:44 UTC
Labels: Type: Feature Request, Status: Needs Triage
