### ISSUE TITLE
Update Movie Folder Release Year 

### ISSUE THREAD

**Issue by NjayNL** [Radarr/Radarr#6163] opened 2021-04-08 10:55 UTC
**Is your feature request related to a problem? Please describe.**

At the moment when you add a movie it picks the date that is listed on TMDB on the moment of adding to radarr let's say 2020 as example. 
as time progresses the release date jumps to 2021 radarr will grab it but the folder created on import is still on date 2020 which gives issues with KODI or other scrapers.

this is solved by manually changing the root folder of your movies to the same under movie editor and clicking OK this will change the dates in the path to the current date listed for a movie.  (good example was jurassic world dominion)

**Describe the solution you'd like**

A process that will update the movie folder release date to the current time on TMDB let's say once per week this solves all issues with old dates and scrapers.

**Comment by bakerboy448** [comment] 2021-04-08 11:33
Dupe of #5853

**Closed by bakerboy448** 2021-04-08 11:33 UTC
Labels: feature request
