### ISSUE TITLE
.srt file(s) in subfolders are not being imported.

### ISSUE THREAD

**Issue by douglas24** [Radarr/Radarr#1958] opened 2017-08-18 05:02 UTC
RARBG movie convention puts subtitle files in a folder called 'Subs' within the movie folder. Radarr only seems to see subtitle files for import in the main movie folder, not subfolders, so the RARBG subtitle files are ignored and not imported.

**Comment by hotio** [comment] 2017-08-18 15:12
You certain radarr copies them over at all? IIRC radarr does nothing to subtitles.

**Comment by galli-leo** [comment] 2017-08-18 18:25
Duplicate of #121

**Comment by danielbibit** [comment] 2018-05-17 19:41
Please, re-open this issue as it's NOT a duplicate of #121. I'm using version 0.2.0.1067, and #2506 don't resolve this issue. Subtitles on /downloads/movieTitle/Subs aren't being properly imported.

**Comment by mstrdraco** [comment] 2018-10-30 14:20
I've noticed this same issues, IE Equalizer 2 just downloaded today and it has a folder called "Subtitles" where the .srt files reside, when Radarr imported the movie it downloaded the main movie but ignored the Subtitles folder and therefore didn't import the .srt files.

**Comment by Qstick** [comment] 2019-02-24 06:15
Looks like this is due to the ExtraService only scanning the top level when importing files for new downloads.

https://github.com/Radarr/Radarr/blob/bd969e0bc351a267694d532930b14ef3dc13264a/src/NzbDrone.Core/Extras/ExtraService.cs#L69

This behavior was brought over from Sonarr, since we are only downloading a single movie at a time and there is no risk of confusing which extra files go with what movie, I don't see the harm in changing this. @galli-leo ?

**Comment by galli-leo** [comment] 2019-02-24 09:35
@Qstick Sounds good to me

**Comment by Qstick** [comment] 2019-02-24 20:10
How are subs typically named when they are in sub directories? currently we only import if name matches movie name, so we will have to add some logic to parse other sub names. 

Are they just language codes like `en.srt` or are they named different?

**Comment by MikeLund** [comment] 2019-02-24 21:04
@Qstick They can be named quite differently, and then you have some other fun stuff if you're considering HI/non-HI subs.

So instead, I'd suggest just taking all files with subtitle extension, and importing them with their original names. Then you leave the rest of the heavy-lifting to the media player instead of building some AI; more subtitle options for the media player is less harmful than losing files because they weren't named properly :)

**Comment by douglas24** [comment] 2019-02-25 03:24
@Qstick original file names makes the most sense because there couldn't have been name conflicts with them in the same upload directory, and there are usually at least two types of English subtitles (one for only when the characters don't speak English, and a second for the entire dialogue).

**Comment by thevik** [comment] 2019-05-26 23:34
this is still an issue for me, is there any updated news on this?

**Comment by n1nj4888** [comment] 2019-07-11 09:16
This seems to still be an issue - Any updates on when / if this is planned to be fixed?

**Comment by jpogs** [comment] 2019-07-28 10:14
Fixed this for my personal use but also submitted a pull request to share to the community

#3647

**Comment by n1nj4888** [comment] 2019-07-29 01:25
Thanks for looking into this @jpogs ! It would be great if this could get fixed!

@Qstick - What needs to happen to get this merged into the develop / stable branch?

Thanks!

**Comment by jpogs** [comment] 2019-07-29 09:51
Happy to help @n1nj4888 ! I know how tedious having to import subs for every movie so I hope this helps!

**Comment by douglas24** [comment] 2019-08-07 07:44
Super glad to see this is finally coming!

**Comment by douglas24** [comment] 2019-08-16 23:36
@jpogs is there a way I can include this in my radarr install or do I need to wait for the next release for the developer channel that I'm on?

**Comment by jpogs** [comment] 2019-08-20 10:14
@douglas24 I recommend waiting for the next developer release when this I think will get integrated. If you are interested to test this build I created a release under my fork.

https://github.com/jpogs/Radarr/releases/tag/pre-release

**Comment by douglas24** [comment] 2019-08-29 01:05
> @douglas24 I recommend waiting for the next developer release when this I think will get integrated. If you are interested to test this build I created a release under my fork.
> 
> https://github.com/jpogs/Radarr/releases/tag/pre-release

Thanks I will check it out since the new develop release for June didn't include the subtitle fix.

**Closed** 2019-09-01 15:53 UTC
Labels: confirmed, enhancement

**Comment by Xebozone** [comment] 2020-04-17 15:09
Can we re-open this one? Apparently the change that fixes it was reverted in Dec? ( #4207 )

**Comment by Xebozone** [comment] 2020-04-21 10:51
@Qstick @jordi-j ?

**Comment by bpersino** [comment] 2020-04-26 18:09
I just tested this out and I can confirm that when downloading a RARBG movie, the subtitle file in  folder called 'Subs', subtitle files are ignored and are not imported/copied/moved.
Package Version = 3.0.0.2871-ls5 by linuxserver.io

**Comment by jpogs** [comment] 2020-04-28 06:44
@Xebozone, @bpersino, this fix was reverted as the update only worked exclusively for RARBG subs. The corrected fix is now pending for review, please be patient while @Qstick reviews #4340

**Comment by Xebozone** [comment] 2020-04-28 06:52
> 
> 
> @Xebozone, @bpersino, this fix was reverted as the update only worked exclusively for RARBG subs. The corrected fix is now pending for review, please be patient while @Qstick reviews #4340

Hey @jpogs ,
Thanks for the update! I appreciate all the hard work you guys do.
Looking forwards to the update!

**Comment by douglas24** [comment] 2020-07-29 17:16
Was this change reverted again? I just noticed the current radarr version (0.2.0.1504 on Windows) is ignoring subtitle files (srt) in subfolders again.

**Comment by ta264** [comment] 2020-07-29 17:58
Yes, the fix caused more problems than it solved

**Comment by douglas24** [comment] 2020-07-29 20:27
> Yes, the fix caused more problems than it solved

Is there a way to include 'folder' in the extensions of files to import so radarr can just import subfolders as is with whatever is in them?

**Comment by nebuchar** [comment] 2020-08-25 08:57
Please, reopen the issue, as the problem is still happening

**Comment by austinwbest** [comment] 2020-08-25 15:15
If it was causing problems, it is unlikely to be added back anytime soon since there are other pressing things.

Work around: use a custom script for import trigger to grab contents of subfolders and copy it over + name or accordingly.

**Comment by nebuchar** [comment] 2020-09-01 20:53
Does custom scripts run after the movie has been imported/renamed, and before cleaning the leftovers?

**Comment by douglas24** [comment] 2020-11-10 18:25
Can you please re-open this?

I upgraded to v3 and this functionality seems to be missing. It needs the ability to check all subfolders for files that match extensions defined by user in the 'Import Extra Files' section.

**Comment by douglas24** [comment] 2020-11-10 18:26
> If it was causing problems, it is unlikely to be added back anytime soon since there are other pressing things.
> 
> Work around: use a custom script for import trigger to grab contents of subfolders and copy it over + name it accordingly.

Any chance you could share an example script?

**Comment by Ianik** [comment] 2021-01-19 13:48
This seem to work for .srt, .sub and .idx files if the name of the file is the same as the video file.
But if the subtitle is 2_English.srt or similar it doesn't work.
Can we have an option that will work for this configuration as well? 
Can we have a switch on or off for this behavior in the settings (name doesn't match) so we can choose to use it or not?

**Comment by bakerboy448** [comment] 2021-01-19 14:08
@Ianik please don’t necro closed threads
There are already existing threads for what you described and we’re well aware extras handling needs some work

work around has been provided for this original issue: use custom scripts

thread locked in light of the unproductive, necro’d comments after closing

various related GHI:
https://github.com/Radarr/Radarr/issues/5378
https://github.com/Radarr/Radarr/issues/5210
https://github.com/Radarr/Radarr/issues/4267
https://github.com/Radarr/Radarr/issues/4637
