### ISSUE TITLE
video and audio codec filter

### ISSUE THREAD

**Issue by byakuya322** [Radarr/Radarr#9543] opened 2024-01-03 18:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

you should add the ability to filter movies based on video or audio codec's so that you can see what has been converted to your desired codec without clicking into every movie

### Describe the solution you'd like

you should add the ability to filter movies based on video or audio codec's so that you can see what has been converted to your desired codec without clicking into every movie

### Describe alternatives you've considered

you should add the ability to filter movies based on video or audio codec's so that you can see what has been converted to your desired codec without clicking into every movie

### Anything else?

you should add the ability to filter movies based on video or audio codec's so that you can see what has been converted to your desired codec without clicking into every movie

**Comment by bakerboy448** [comment] 2024-01-03 18:30
- Duplicate of https://github.com/Radarr/Radarr/issues/5703
- duplicate of https://github.com/Radarr/Radarr/issues/5517
- duplicate of https://github.com/Radarr/Radarr/issues/5015
- duplicate of https://github.com/Radarr/Radarr/issues/5304
- Duplicate of https://github.com/Radarr/Radarr/issues/6602

> I have searched the existing open and closed issues

Please do not blindly check the box when it's clear this was not done https://github.com/Radarr/Radarr/issues?q=is%3Aissue+codec

**Closed by bakerboy448** 2024-01-03 18:30 UTC
Labels: Type: Feature Request, Status: Needs Triage
