### ISSUE TITLE
New Feature: Folder name option "Movie CollectionThe"

### ISSUE THREAD

**Issue by FDMatthias** [Radarr/Radarr#5418] opened 2020-11-28 18:28 UTC
**Is your feature request related to a problem? Please describe.**
Hi, I just started using Radarr and I am planning to rename my folders and file names in a consistent and easily accessible way. I have the following Movie Folder Format lined up:
`{Movie Collection}/{Movie TitleThe} ({Release Year}){ Edition Tags}`
Resulting in "The Movie Collection/Movie Title, The (2010) Ultimate Extended Edition" and "Movie Title, The (2010) Ultimate Extended Edition" if there is no collection available. 

In short, I would like to be able to use "Movie Collection, The/..." as a format. This would mean that all non-collection folders (falling back to the `{Movie TitleThe}` option) and collections (maybe using something like an `(Movie CollectionThe}` option) can be sorted consistently in alphabetical order, i.e. without any leading "The".

**Describe the solution you'd like**
I would like to be able to use `{Movie CollectionThe}` as an option in the Movie Folder Format input field, and have it output "Movie Collection, The". This would help me to keep folder names consistent and would allow me to follow the same logic when searching for/scrolling through movie folders.

**Describe alternatives you've considered**
Alternatives: 
1. Using `.../{Movie Title} ...` as a format (instead of `{Movie TitleThe}`) so that it outputs the same leading "The", e.g. _The Wolverine Collection/The Wolverine (2013) ..._: This would keep things consistent but it would also mean that other (non-collection) movies fallback to "The Movie Title (year)/...", which results in the problem of not being able to search alphabetically in folders (because of the leading "The").
2. Using `{Movie Collection}/{Movie TitleThe} ...` as a format would imply that other non-collection movies fall back to "Movie Title, The (year)/...", while collections would output "The Movie Collection/Movie Title, The (year)/..." In my opinion, this makes things inconsistent.
3. Remove the `{Movie Collection}` option from the format, resulting in no reference to a collection at all... which is undesired as movie folders of collections sometimes differ in their starting letter, meaning they are not grouped at all, e.g. _Wolverine, The_, _X-Men Origins: Wolverine_ and _Logan_. With, for example, Star Wars movies _Empire Strikes Back, The_ and _Return of the Jedi_, or with the _Batman Collection_ it would result in _Batman_ and _Dark Knight Rises, The_.

**Additional context**
Collections to test with:
* _The Wolverine Collection_
* _The Huntsman Collection_
* _Star Wars Collection_
* _Batman Collection_
* _Mechanic Collection_

Thanks in advance, and also for the otherwise already awesome piece of software!

**Comment by fryfrog** [comment] 2020-12-05 00:50
This is effectively a duplicate of the long standing https://github.com/Radarr/Radarr/issues/153 feature request. I would add your `{Token}` idea there.

**Closed by fryfrog** 2020-12-05 00:50 UTC
Labels: feature request

**Comment by FDMatthias** [comment] 2020-12-06 10:30
I can see how this feature request's functionality overlaps in #153: the subject "support custom folders" is quite extensive and probably quite a lot of feature requests can be referenced to it! 

However, if I understand that issue correctly I believe it is mainly about _supporting_ custom folders, but that is not something I would like to achieve with this feature request :-)

This feature request is not about being able to scan said "Movie Collection, The" folder name. For that, users can use custom root folders under the Root Folders section in the Media Management page of the Settings view.

With this feature request I would like to provide one specific piece of functionality to users: 
> the ability to select a use `{Movie CollectionThe}` as an option in the Movie Folder Format input field, and have it output "Movie Collection, The". 

Nothing more, nothing less ;-)

Is this something you can agree to, @fryfrog ?

**Comment by fryfrog** [comment] 2020-12-06 17:06
It doesn't really matter that you think what you want is smaller, it is all tied up part and parcel w/ that long standing feature request.

**Comment by FDMatthias** [comment] 2020-12-07 18:10
Okay, thanks for your time and answers.
