### ISSUE TITLE
After renaming folders, allow "import" to map the (re) discovered movies to the "existing" radarr records for them

### ISSUE THREAD

**Issue by randallspicher** [Radarr/Radarr#9564] opened 2024-01-08 05:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I used tinymediamanager to clean up the naming in my movie library.  After which, a lot of the move folders were renamed (year had been incorrect, some differences in handling special characters etc).

As a result of this, radarr no longer sees many of the files.  When I go to "import", it identifies the files, and then does not allow me to import them because the records for those movies already exist in radarr, despite them being listed as missing.  The only solution would be to either delete my radarr database and start over (very undesirable, as I'd loose all my quality preferences), or to edit each movie one-by-one in radarr and pick the new directory.

### Describe the solution you'd like

When radarr finds a movie on the import that already "exists" in radarr, it should give the option to map the discovered files to the existing radarr records.  Preferably by updating the path of the existing records in radarr to point at the directory it just discovered the actual files in.  (note there is the possibiltiy that another copy of the movie exists at the path radarr already has, in which case the user would need to be warned it's a dupe)

### Describe alternatives you've considered

deleting the radarr database and starting over from scratch, or editing every [now missing] movie one-by-one to search for the new directory that movie is now in

### Anything else?

would like to see a checkbox for existing records to "add to existing record" (only needing to update the path), instead of creating a new radarr record (the "monitor", "min availabilty" and "quality profile" dropdowns for such records would either need to be disabled in that case, or updated to reflect the current values of existing record), as it would be editing that record, rather then creating a new one.

**Comment by bakerboy448** [comment] 2024-01-08 08:35
- Library Import should never be used on disorganized hot mess libraries. The wiki and UI state this.
- Radarr owns its root folder, dont use third party tools to mess with Radarr's root folder
- Radarr can rename folders and files and thus the premise of this is invalid
- Duplicate of https://github.com/Radarr/Radarr/issues/6414

**Closed by bakerboy448** 2024-01-08 08:35 UTC
Labels: Type: Feature Request, Status: Needs Triage
