### ISSUE TITLE
Old subtitle gets deleted when upgrading to better quality

### ISSUE THREAD

**Issue by Buster14** [Radarr/Radarr#2770] opened 2018-05-10 01:54 UTC
**Mono Version:** 0.2.0.1076 

As the title says,
When a movie gets upgraded to better quality, the sub also deleted.
e.g 

Avengers (2012) 1080p Web-dl.mkv
Avengers (2012) 1080p Web-dl.srt

A month later, upgraded to 
Avengers (2012) 720p Bluray.mkv

And the sub is gone..
I'd rather keep it because 
1. Finding a sub that matches a particular quality is not always easy
2. Resyncing does not always work, i've resync hundreds of subs, some of them requires manually timing each line
3. Sometimes different quality subs also works with better ones,
e.g web-dl subs sometimes work with bluray

**Comment by Qstick** [comment] 2018-05-20 06:42
Subs are tied to individual movie files, thus we purge if the movie file is purged. If not you will have subs that are not synced correctly with your new file in many cases. I don't think we want to keep old subs in any situation. @galli-leo ?

**Comment by Buster14** [comment] 2018-05-20 08:31
I'd suggest just purge the movie and leave the subs, if not user have to look again for the subs should the movie changes quality

**Comment by galli-leo** [comment] 2018-05-20 10:26
I have marked this as a feature request, but I don’t think we will implement this any time soon

**Comment by Buster14** [comment] 2018-06-06 23:13
Would renaming the subs to moviename.srt.lang prevent the purging? Guess i could use it for temporary fix, dont wanna lose hundreds of subs...

**Comment by Buster14** [comment] 2018-06-08 02:22
Well, just tried it, it doesn't seem to help... still gets deleted

**Comment by Buster14** [comment] 2018-07-15 06:43
So any chance to fix this?

**Comment by Qstick** [comment] 2020-07-13 04:05
Don’t think this is going to happen, subs should be tied to movie files... also dupe of #3209. Bazaar is nice 😁 in v3 you can also solve this by not allowing upgrades

**Closed by Qstick** 2020-07-13 04:05 UTC
Labels: feature request
