### ISSUE TITLE
Download progress in wanted-page

### ISSUE THREAD

**Issue by releases42** [Radarr/Radarr#3408] opened 2019-03-06 06:56 UTC
It would be nice to have the download-progress reported in the "Wanted"-page, for the movies that are missing, but currently downloaded.

I recently added multiple movies, and not all of them found a matching release, so now I have to swap between the "Activity"-tab and the "Wanted"-tab to see which of the movies were unable to find a release, and do a manual search for them. 

I would prefer the "Progress"-column from the "Activity"-tab to be visible in the "Wanted"-tab (Both for Missing and "Cutoff Unmet"). If not, then another column with some other kind of status like "Snatched" or simply "Downloading" would suffice.

**Comment by galli-leo** [comment] 2019-03-19 12:18
Duplicate of #252

**Closed by galli-leo** 2019-03-19 12:18 UTC
