### ISSUE TITLE
Add option to not replace or remove "illegal" characters in filenames when running on Linux

### ISSUE THREAD

**Issue by wheelerlaw** [Radarr/Radarr#5905] opened 2021-02-08 21:36 UTC
**Is your feature request related to a problem? Please describe.**

Most Linux hosts are using a filesystem that was created in the current century (ext3, ext4, btrfs) and don't really have any restrictions on permitted characters in file and folder names. (except for `NUL` and `/`). So on these hosts there is no need to remove perfectly valid characters from the filenames, such as colons and ampersands. 

**Describe the solution you'd like**

It would be nice if instead of a boolean option to replace "illegal" characters or simply just drop them, there were another option that would leave them in there. 

**Describe alternatives you've considered**

**Additional context**

**Comment by wheelerlaw** [comment] 2021-02-08 21:47
I've been looking at the FileNameBuilder.cs and NamingConfigResource.cs files, and this seems like it could be a pretty straightforward addition. It would be very helpful though if it were host-aware, i.e. the option would only be available on systems that support it. Like I wouldn't want to add this option on a Windows host because obviously there are more characters that aren't allowed.

**Comment by bakerboy448** [comment] 2021-02-08 23:25
Duplicate of #https://github.com/Radarr/Radarr/issues/4792#issuecomment-699681153

**Closed by bakerboy448** 2021-02-08 23:25 UTC
Labels: feature request
