### ISSUE TITLE
"Prefer special indexer flags" overrides "Prefer Usenet" in auto-search priority

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1983] opened 2017-08-22 22:39 UTC
If I have the setting "Prefer special indexer flags" ON, this will ignore "Prefer Usenet" under Delay Profiles and will result in torrents being listed at the top of auto-search priority. 

![image](https://user-images.githubusercontent.com/5501908/29590716-c2d71cb4-8760-11e7-85e5-2d1f203ddf6f.png)

Radarr version: 0.2.0.840
nightly

**Comment by hotio** [comment] 2017-08-23 05:29
Is already a known issue...

**Comment by hotio** [comment] 2017-08-23 05:30
https://github.com/Radarr/Radarr/issues/1814

**Comment by desimaniac** [comment] 2017-08-23 07:28
Yup your right, I missed that.

**Comment by galli-leo** [comment] 2017-08-24 20:57
Duplicate of #1814

**Closed by galli-leo** 2017-08-24 20:57 UTC
