### ISSUE TITLE
Running Organize on individual movie never finishes

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#173] opened 2017-01-11 22:45 UTC
From the mass editor, an organize works fine. When run individually, it just spins forever.

![screen shot 2017-01-11 at 2 44 36 pm](https://cloud.githubusercontent.com/assets/87748/21869456/92f4752c-d80c-11e6-83b5-4d688f7b7f02.png)

Logs (maybe?):
```
17-1-11 14:48:55.3|Trace|Http|Req: 1739 [GET] /api/rename??movieId=229
17-1-11 14:48:55.4|Trace|NzbDroneErrorPipeline|Handling Exception
17-1-11 14:48:55.4|Warn|NzbDroneErrorPipeline|API Error

[v0.2.0.61] NzbDrone.Api.REST.BadRequestException: BadRequest :seriesId is missing
  at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes () [0x00139] in <3728f4e99a5d43e4bdb2821f0a019b84>:0
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00006] in <3728f4e99a5d43e4bdb2821f0a019b84>:0
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

17-1-11 14:48:55.4|Trace|Http|Res: 1739 [GET] /api/rename??movieId=229: 400.BadRequest (2 ms)
17-1-11 14:48:55.4|Debug|Api|[GET] /api/rename??movieId=229: 400.BadRequest (2 ms)
17-1-11 14:48:55.4|Trace|Http|Req: 1740 [GET] /api/config/naming
17-1-11 14:48:55.4|Trace|Http|Res: 1740 [GET] /api/config/naming: 200.OK (2 ms)
17-1-11 14:48:55.4|Debug|Api|[GET] /api/config/naming: 200.OK (2 ms)
```

**Comment by fedoranimus** [comment] 2017-01-11 22:51
Closing; duplicate of #84

**Closed by fedoranimus** 2017-01-11 22:51 UTC
