### ISSUE TITLE
Collections - Management made easy

### ISSUE THREAD

**Issue by jacosmitza** [Radarr/Radarr#9279] opened 2023-10-12 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

NA

### Describe the solution you'd like

When editing the Collection properties.

1. Ability to delete an entire collection at once with the usual prompts to delete files and exclude.
2. When changing root folder for a collection, prompted to and abilty to move all movies in the collection to the new root folder.
3. Ability to create a collection root folder from the Collections View.
4. Prompted to move already downloaded movies in a collection from other root folders to proper collection root folder.

### Describe alternatives you've considered

Doing it manually.

### Anything else?

NA

**Comment by bakerboy448** [comment] 2023-10-12 13:13
1) Duplicate of https://github.com/Radarr/Radarr/issues/7663
2) likely no plans at this time, this is similar to how lists work
3) this already exists when a collection is selected or edited and one goes to change the root folder
4) likely no plans at this time, this is similar to how lists work

**Comment by Qstick** [comment] 2023-12-31 17:45
Closing this in favor of #7663, the other items are a bit out for now

**Closed by Qstick** 2023-12-31 17:45 UTC
Labels: Type: Feature Request, Status: Unlikely, Status: Needs Triage
