### ISSUE TITLE
Error when automated list tries to add a already existing movie.

### ISSUE THREAD

**Issue by dhaos21** [Radarr/Radarr#1092] opened 2017-03-09 12:11 UTC
I am getting this error when the automated lists tries to add a movie that is already on my wanted list.

http://pastebin.com/XvPzK7Qg

**Comment by geogolem** [comment] 2017-03-09 12:24
Can you please verify that this is happening when you already have Logan in your Radarr Library? 

or is it just happening if Logan is not already in your Radarr library and is being imported via List Sync.

The reason I ask is because the list Sync only imports movies not already in your library. Nothing changed with respect to this. Before the exclusions are handled - the list of movies elligible to be added should already be filtered of movies which already exist  in the library - and nothing changed with respect to this... 

In any case please get back to us regarding this fact... 

referring to your log: 17-3-9 10:41:19.3|Info|NetImportSearchService|Found 68 movies on your auto enabled lists not in your library

If Logan is not one of those 68 movies, nothing will happen with it.. so if my undersanding is correct, the only way those errors came out for Logan is if it was one of those 68 movies. and the only way it would be one of those 68 movies would be if it was not already in your radarr library.

Based on my current knowledge/understanding, it would make most sense if you are getting these errors when doing a list sync without Logan in your library (and without Logan on your exclusions).. 

Can you please verify this.

**Comment by dhaos21** [comment] 2017-03-09 12:28
At the time of that pastebin i linked Logan was not in my library. after the import Logan was added. the crash seems to be with the movie Get Out which netimport is trying to add, which is already in my library.

**Comment by geogolem** [comment] 2017-03-09 13:33
ok -- regarding the Logan error -- lets not worry about that one right now... Are you able to repeatably get the "Get Out" error.. or if no error --> is "Get Out" repeatably trying to be added during ListSync despite it already being in your library?

**Comment by dhaos21** [comment] 2017-03-09 13:35
Yes, it tries to add it every time and I get the same error.

**Comment by geogolem** [comment] 2017-03-09 13:36
ok, thanks.. I'm trying to reproduce the problem with "Get Out"

**Comment by dhaos21** [comment] 2017-03-09 13:37
I'm guessing it will work with any movie, as it happened with logan before I deleted it from my library.

**Comment by geogolem** [comment] 2017-03-09 13:38
right -- yes it is very strange, since these movies shouldnt even get to that point.. so I need to first reproduce it and then see why those movies are even making it this far along.. as they should be removed from the list of elligble movies to add before we even get to that point... --> Thanks for all the info you provided - it helps me to know whats going on.

**Comment by geogolem** [comment] 2017-03-09 14:12
I am not able to reproduce this. i have a trakt list with 543 movies on it.

I have a radarr library with 542 of those same movies.

when i run list sync.  only the movie missing from my library is added..

this is with the latest driver - i just built it now.

**Comment by dhaos21** [comment] 2017-03-09 15:41
Well both those movies (Logan and get out) are on the stevenlu list. Not sure if that makes a difference

**Comment by IvanJosipovic** [comment] 2017-03-09 16:56
I'm also seeing the same issue on build 0.2.0.510

`
17-3-9 08:54:56.6|Info|NetImportSearchService|Found 88 movies on your auto enabled lists not in your library
17-3-9 08:54:57.2|Info|MovieService|Adding Movie [][Logan] Path: [D:\Downloads\Movies\Logan (2017)]
17-3-9 08:54:57.3|Error|CommandExecutor|Error occurred while executing task NetImportSync

[v0.2.0.510] System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.TitleSlug
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar()
   at Marr.Data.QGen.InsertQueryBuilder`1.Execute() in C:\projects\radarr-usby1\src\Marr.Data\QGen\InsertQueryBuilder.cs:line 138
   at Marr.Data.DataMapper.Insert[T](T entity) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 728
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 106
   at NzbDrone.Core.Tv.MovieService.AddMovie(Movie newMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 164
   at NzbDrone.Core.NetImport.NetImportSearchService.Execute(NetImportSyncCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\NetImportSearchService.cs:line 125
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
`

**Comment by geogolem** [comment] 2017-03-09 17:48
so basically it is trying to add Logan when it is already in your library?

**Comment by geogolem** [comment] 2017-03-09 18:28
this should not have an impact - but i just want to be sure --> you are running with Clean Library disabled, right?

**Comment by geogolem** [comment] 2017-03-09 18:31
Could you also provide me with the setup details for the stephenLu list so that I can try to reproduce with exactly the same list you are using.

**Comment by IvanJosipovic** [comment] 2017-03-09 18:37
Clean Library is disabled for me.

**Comment by geogolem** [comment] 2017-03-09 18:51
i think i found the bug.. give me another 15 minutes! :)

**Comment by geogolem** [comment] 2017-03-09 19:00
ok i checked in the fix. It really was quite stupid.. lol.. Please try with the latest and let me know how it goes. I already tested and it seemed to resolve the issue.

**Comment by PeteOdeath** [comment] 2017-03-09 19:43
I'm getting this error too with 0.2.0.510 
http://pastebin.com/u7C4N1HQ

**Comment by geogolem** [comment] 2017-03-09 19:44
@PeteOdeath : can you please try with the latest code. I just checked in a fix for this a few minutes ago.

**Comment by dhaos21** [comment] 2017-03-09 20:46
Didnt work for me with the latest nightly.

17-3-9 20:46:01.4|Info|NetImportSearchService|Found 34 movies on your auto enabled lists not in your library
17-3-9 20:46:02.2|Info|MovieService|Adding Movie [][Logan] Path: [D:\Downloads\Emma\Movies\Logan]
17-3-9 20:46:02.3|Error|CommandExecutor|Error occurred while executing task NetImportSync

[v0.2.0.510] System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: Movies.TitleSlug
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar()
   at Marr.Data.QGen.InsertQueryBuilder`1.Execute() in C:\projects\radarr-usby1\src\Marr.Data\QGen\InsertQueryBuilder.cs:line 138
   at Marr.Data.DataMapper.Insert[T](T entity) in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:line 728
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 106
   at NzbDrone.Core.Tv.MovieService.AddMovie(Movie newMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:line 164
   at NzbDrone.Core.NetImport.NetImportSearchService.Execute(NetImportSyncCommand message) in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\NetImportSearchService.cs:line 125
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by geogolem** [comment] 2017-03-09 21:02
@dhaos21 : i think the latest nightly is the same driver you were using when you initially reported the issue. I dont think my fix will be in the "nightly" until tonight.. but im not really sure how the relases work. My fix is in the latest develop driver though...

**Comment by geogolem** [comment] 2017-03-10 06:26
Please let us know if this problem has been resolved so I can close off the issue - thanks! :)

**Comment by IvanJosipovic** [comment] 2017-03-10 06:34
Issue is resolved for me.


_____________________________

**Closed** 2017-03-10 06:36 UTC
Labels: bug
