### ISSUE TITLE
Radarr should remove a pending download from download client, if movie gets deleted.

### ISSUE THREAD

**Issue by gbougiakas** [Radarr/Radarr#5462] opened 2020-12-02 12:45 UTC
As the title says, radarr has sent a movie to be downloaded to the client and in the meantime the user decided that he/she doesn't care about the movie and deletes it (within radarr). The download remains (to be downloaded) in the client.

**Comment by bakerboy448** [comment] 2020-12-02 13:15
Duplicate of #3918 

Please use the search function next time

**Closed by bakerboy448** 2020-12-02 13:15 UTC
Labels: feature request
