### ISSUE TITLE
Please allow to import 4K and 1080p versions of the same film

### ISSUE THREAD

**Issue by Gartonious** [Radarr/Radarr#7181] opened 2022-04-03 17:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It would be nice to be able to import multiple versions of the same film - for example, to be able to import a 4K and an 1080p version of a film 

### Describe the solution you'd like

It would be nice to be able to have a 4k version and 1080p version of a film in the library rather than one or the other. At the moment I do not have plex setup to share 4K content with users, only 1080p but I personally have a few 4k films but they are not managed by Radarr as I have got the content manually and added them to a separate folder on my media shares

What I am trying to achieve is to have Overseerr setup to I can download 4K content as well as having a same copy for my shared users in 1080p

### Describe alternatives you've considered

Currently I have to have two instances setup of Radarr in order to achieve having a separate 4K content and a separate 1080p content then to have both the servers connect to overseerr to be able to request them. Radarr is already able to request 4K content but it would overwrite the 1080p content but I want to be able to have both which is stored in two separate folders on my hard drive

### Anything else?

n/a

[AB#2904](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2904)

**Comment by bakerboy448** [comment] 2022-04-03 17:45
Duplicate of #1910

Please search next time.

**Closed by bakerboy448** 2022-04-03 17:45 UTC
Labels: Type: Feature Request, Status: Needs Triage
