### ISSUE TITLE
Deleting a movie that's being downloaded doesn't get removed in the download client

### ISSUE THREAD

**Issue by goestav** [Radarr/Radarr#6432] opened 2021-06-28 23:29 UTC
**Describe the bug**

The download client doesn't remove a movie when it gets deleted in the import list.

**To Reproduce**

1. Add a movie
2. Wait for it to start downloading
3. Delete the movie via the import list (Movies page)
4. Movie still downloading in download client

**Expected behavior**

The movie gets deleted from the download client too after deleting it in the UI.

**Screenshots**

(1 & 2)
<img width="895" alt="image" src="https://user-images.githubusercontent.com/27970303/123713111-3f485900-d863-11eb-90a7-caab2c01c4a2.png">
(3)
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/27970303/123713195-643ccc00-d863-11eb-9ffc-d2fd40add678.png">
(4)
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/27970303/123713310-a36b1d00-d863-11eb-92a9-4d6ed5de1d3c.png">

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET 5.0.5
 - Browser and Version (Only needed for UI issues): /
 - Radarr Version: 3.2.2.5080 (3.2.2.5080-ls105 by linuxserver.io)
 - Radarr Branch: master

**Trace Logs**
<details>
<summary>Click to show log</summary>

```
2021-06-29 00:57:57.2|Debug|Api|[GET] /api/v3/importlist/schema: 200.OK (5 ms)
2021-06-29 00:58:00.8|Trace|Http|Req: 1979 [DELETE] /api/v3/movie/30?deleteFiles=true&addImportExclusion=false&queryParams=%5Bobject%20Object%5D (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Req: 1980 [GET] /api/v3/movieFile?movieId=13 (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Req: 1981 [GET] /api/v3/blacklist/movie?movieId=13 (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Req: 1982 [GET] /api/v3/history/movie?movieId=13 (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Req: 1983 [GET] /api/v3/extraFile?movieId=13 (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Req: 1984 [GET] /api/v3/queue/details?movieId=13 (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Req: 1985 [GET] /api/v3/credit?movieId=13 (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Res: 1981 [GET] /api/v3/blacklist/movie?movieId=13: 200.OK (1 ms)
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/blacklist/movie?movieId=13: 200.OK (1 ms)
2021-06-29 00:58:00.8|Trace|Http|Res: 1984 [GET] /api/v3/queue/details?movieId=13: 200.OK (1 ms)
2021-06-29 00:58:00.8|Trace|Http|Req: 1986 [GET] /api/v3/importlist/schema (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/queue/details?movieId=13: 200.OK (1 ms)
2021-06-29 00:58:00.8|Trace|Http|Res: 1983 [GET] /api/v3/extraFile?movieId=13: 200.OK (3 ms)
2021-06-29 00:58:00.8|Trace|Http|Res: 1980 [GET] /api/v3/movieFile?movieId=13: 200.OK (3 ms)
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/extraFile?movieId=13: 200.OK (3 ms)
2021-06-29 00:58:00.8|Trace|Http|Res: 1985 [GET] /api/v3/credit?movieId=13: 200.OK (2 ms)
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/movieFile?movieId=13: 200.OK (3 ms)
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/credit?movieId=13: 200.OK (2 ms)
2021-06-29 00:58:00.8|Trace|Http|Res: 1986 [GET] /api/v3/importlist/schema: 200.OK (3 ms)
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/importlist/schema: 200.OK (3 ms)
2021-06-29 00:58:00.8|Trace|EventAggregator|Publishing MoviesDeletedEvent
2021-06-29 00:58:00.8|Trace|Http|Res: 1982 [GET] /api/v3/history/movie?movieId=13: 200.OK (11 ms)
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent -> NotificationService
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/history/movie?movieId=13: 200.OK (11 ms)
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <- NotificationService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent -> HistoryService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <- HistoryService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent -> TrackedDownloadService
2021-06-29 00:58:00.8|Debug|Parser|Parsing string 'The.Godfather.1972.1080p.BRRip-YTS'
2021-06-29 00:58:00.8|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2021-06-29 00:58:00.8|Debug|Parser|Movie Parsed. The Godfather - 1972 
2021-06-29 00:58:00.8|Debug|Parser|Release Group parsed: YTS
2021-06-29 00:58:00.8|Debug|Parser|Languages parsed: Unknown
2021-06-29 00:58:00.8|Debug|QualityParser|Trying to parse quality for The.Godfather.1972.1080p.BRRip-YTS
2021-06-29 00:58:00.8|Debug|Parser|Quality parsed: Bluray-1080p v1
2021-06-29 00:58:00.8|Debug|Parser|Edition parsed: 
2021-06-29 00:58:00.8|Debug|ParsingService|No matching movie The Godfather
2021-06-29 00:58:00.8|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
2021-06-29 00:58:00.8|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
2021-06-29 00:58:00.8|Trace|EventAggregator|Publishing QueueUpdatedEvent
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsModule
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsModule
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusModule
2021-06-29 00:58:00.8|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusModule
2021-06-29 00:58:00.8|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <- TrackedDownloadService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent -> PendingReleaseService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <- PendingReleaseService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent -> DownloadHistoryService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <- DownloadHistoryService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent -> MovieModule
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <- MovieModule
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent -> MovieModule
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <- MovieModule
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> CreditService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> MovieTranslationService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> AlternativeTitleService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> MediaCoverService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> MediaFileService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> MediaFileDeletionService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> ImportExclusionsService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> SubtitleFileService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> OtherExtraFileService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> MetadataFileService
2021-06-29 00:58:00.8|Info|MovieService|Deleted movie [The Godfather (1972)][tt0068646, 238]
2021-06-29 00:58:00.8|Trace|Http|Res: 1979 [DELETE] /api/v3/movie/30?deleteFiles=true&addImportExclusion=false&queryParams=%5Bobject%20Object%5D: 200.OK (29 ms)
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <~ ImportExclusionsService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <~ MediaCoverService
2021-06-29 00:58:00.8|Debug|Api|[DELETE] /api/v3/movie/30?deleteFiles=true&addImportExclusion=false&queryParams=%5Bobject%20Object%5D: 200.OK (29 ms)
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent ~> BlacklistService
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <~ CreditService
2021-06-29 00:58:00.8|Trace|EventAggregator|Publishing DeleteCompletedEvent
2021-06-29 00:58:00.8|Trace|EventAggregator|MoviesDeletedEvent <~ MediaFileDeletionService
2021-06-29 00:58:00.8|Trace|EventAggregator|DeleteCompletedEvent ~> NotificationService
2021-06-29 00:58:00.8|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2021-06-29 00:58:00.8|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthModule
2021-06-29 00:58:00.8|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthModule
2021-06-29 00:58:00.8|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthModule
2021-06-29 00:58:00.8|Trace|EventAggregator|DeleteCompletedEvent <~ NotificationService
2021-06-29 00:58:00.8|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthModule
2021-06-29 00:58:00.8|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-06-29 00:58:00.8|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-06-29 00:58:00.8|Trace|Http|Req: 1987 [GET] /api/v3/queue/details?movieId=13 (from ::ffff:172.31.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0)
2021-06-29 00:58:00.8|Trace|Http|Res: 1987 [GET] /api/v3/queue/details?movieId=13: 200.OK (0 ms)
2021-06-29 00:58:00.8|Debug|Api|[GET] /api/v3/queue/details?movieId=13: 200.OK (0 ms)
2021-06-29 00:58:00.9|Trace|EventAggregator|MoviesDelete
```
</summary>

[AB#902](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/902)

**Comment by bakerboy448** [comment] 2021-06-28 23:31
I'm not sure if this is something that should be added due to Hit and Run risk for private torrents.

@Qstick thoughts?

**Comment by austinwbest** [comment] 2021-06-29 02:08
Pretty sure there is a toggle option for delete from client, on my phone so can't look atm

**Comment by bakerboy448** [comment] 2021-06-29 02:09
> Pretty sure there is a toggle option for delete from client, on my phone so can't look atm

From the activity queue yes

from deleting a movie, no

**Comment by bakerboy448** [comment] 2021-07-09 17:38
Duplicate of #3918

**Closed by bakerboy448** 2021-07-09 17:38 UTC
Labels: Type: Feature Request
