### ISSUE TITLE
Custom Formats Tags

### ISSUE THREAD

**Issue by sofasogud** [Radarr/Radarr#5663] opened 2021-01-01 12:37 UTC
**Is your feature request related to a problem? Please describe.**
As I've been upgrading my library to 265 and HDR the majority of my library has upgraded within the quality profiles I've set. Not all have been upgraded because that format is either not available or the format available falls outside of my quality profile. 

If I click on a movie I can see 'custom formats' under history, files, and of course search and this is the only way I can see this information which makes it a time consuming task to search for items in my library that have not yet been updated for 265 and/or HDR.

<img width="1449" alt="Screenshot 2021-01-01 at 12 34 15" src="https://user-images.githubusercontent.com/40215388/103438704-b8a51d00-4c2d-11eb-9f8f-d4c48c08bff8.png">

**Describe the solution you'd like**
In the movies list, it would be great it we could add the 'custom formats' to the table view so we easily have an overview or what items fit in with the custom formats or not. 

<img width="1466" alt="Screenshot 2021-01-01 at 12 33 58" src="https://user-images.githubusercontent.com/40215388/103438703-b642c300-4c2d-11eb-9d2d-43ecb4666b3c.png">

**Describe alternatives you've considered**
I thought about maybe tagging the movies if they're downloaded with custom formats but I'm not sure what we be easier on the development side of things. 

I also just want to take this opportunity to give a big thanks to the work you guys do! You've saved me so much time and I obsoultely love this app!!

**Additional context**

**Comment by bakerboy448** [comment] 2021-01-01 12:43
Duplicate of #5243

Duplicate of #5517

Please search prior to making a GHI in the future.

**Closed by bakerboy448** 2021-01-01 12:43 UTC
Labels: feature request
