### ISSUE TITLE
Better handling of bonus content in STREAM folder (m2ts)

### ISSUE THREAD

**Issue by TheRedSpy15** [Radarr/Radarr#9291] opened 2023-10-16 19:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a folder for a blu ray movie. Inside its STREAM folder it has the m2ts files for the movie itself, and the trailers (and bonus content)

Radarr seems to have just picked 1 out of 17 m2ts files to import. That being a trailer. Of which is nowhere near the size of the 85 gb movie m2ts file.

This has happened to me twice in the past week

### Describe the solution you'd like

I don't have the greatest understanding of how m2ts works. But I feel the massive difference in size of the m2ts files are indicators of which file is the movie. However I do notice the largest m2ts file only has a couple hours of video and no audio. So I'm not sure how to go about finding the file with the correct audio

### Describe alternatives you've considered

Deleting everything in the STREAM folder except for the movie m2ts manually, and re importing in Radarr

### Anything else?

![image](https://github.com/Radarr/Radarr/assets/32081703/f384ed19-9450-4bc9-a53b-48e32c22bbed)

**Comment by bakerboy448** [comment] 2023-10-16 21:02
Duplicate of https://github.com/Radarr/Radarr/issues/8286

**Closed by bakerboy448** 2023-10-16 21:02 UTC
Labels: Type: Feature Request, Status: Needs Triage
