### ISSUE TITLE
Feature Request:  Show multiple type of "Available" dates (digital and disc)

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#3353] opened 2019-02-05 22:35 UTC
**Is your feature request related to a problem? Please describe.**
I do often look at the Available date for a movie, and it's not correct (so much so that I don't tend to look at it anymore, I check elsewhere).  I'm not sure where the dates are pulled from, and if they're ever refreshed periodically like the poster or title would be? 

**Describe the solution you'd like**
I think part of the issue is that sometimes the date displayed can be the digital release, but there's not really an indication of that.   I'd like to know both digital and disc release, as the former indicates when a decent copy will appear, but the latter indicates when the better qualities will start to appear.   I'd like the Available tag to perhaps be clickable, with a popup then opening showing both release dates (digital and disc)?

**Describe alternatives you've considered**
Perhaps just append the Available tag with the type if the above isn't possible.  Eg  Available (Digital): 28 February or Available (Disc): 12 March

**Comment by fryfrog** [comment] 2019-02-18 01:48
Do you know of a good place to get physical and digital release dates? I'm not sure what it uses currently, but w/o a source... there isn't a whole lot to do.

**Comment by simonk83** [comment] 2019-02-18 01:55
Well the dates at the moment seem to be digital generally, so I'm assuming that part is covered (I had a poke through the code but couldn't really find a source).  For physical I always check blu-ray.com however I'm not sure if they have an API or anything like that, I'll have a look.

**Comment by simonk83** [comment] 2019-02-19 05:01
Ok, bluray.com don't offer an API, however I just noticed that this info is available on TMDB:

Eg, Aquaman:
![image](https://user-images.githubusercontent.com/518440/52991171-a7026400-345f-11e9-8406-db18de31fab1.png)

**Comment by geogolem** [comment] 2019-03-01 22:37
It would be nice if we had accurate release date info, and we could display it all in radarr.. This is definitely something I would love. 

I actually use/maintain a fork/branch of radarr that augments release date info from omdbapi (which I believe is IMDB).

Unfortunately even augmenting radarrs current release date info with the info from OMDBAPI is still insufficient and not that accurate.

Please check out my fork/branch here: https://github.com/geogolem/Radarr/tree/augmentMovieInfo

If anybody has any suggestions on how to further or better augment radarr's release date info with a more complete and accurate data source, please let me know. If we had more accurate and complete release date info I might be more motivated to look into adding more stuff to the UI concerning release dates. 

Right now, there is alot of massaging of data to get what Radarr currently has as themoviedb is largely incomplete and not always accurate.

**Comment by geogolem** [comment] 2019-03-01 22:40
> Ok, bluray.com don't offer an API, however I just noticed that this info is available on TMDB:
> 
> Eg, Aquaman:
> ![image](https://user-images.githubusercontent.com/518440/52991171-a7026400-345f-11e9-8406-db18de31fab1.png)
> 
> And here's the call: https://developers.themoviedb.org/3/movies/get-movie-release-dates
> 
> eg: https://api.themoviedb.org/3/movie/297802/release_dates?api_key=<<api_key>>
> 
> Looks like Type 4 = Digital and Type 5 = Physical

Themoviedb does have info like that accessible via the API; however, alot of info is missing or inaccurate. 

anyway, its been a while since I looked into this, so I don't want to say more  -- ill refresh my memory and maybe write back later. but if someone has a better release date info source it would be greatly appreciated.. OR --> maybe the radarr community could somehow work towards, making themoviedb more complete and accurate? or something like that.

**Comment by geogolem** [comment] 2019-03-01 22:55
this mioght be a duplicate of: https://github.com/Radarr/Radarr/issues/3151 (just putting here for reference) in case anybody wanted to merge these 2 issues.

**Comment by fryfrog** [comment] 2019-03-01 22:57
Can't really merge, just mention and close one or the other. :(

**Comment by MagiX13** [comment] 2019-04-01 22:22
> Themoviedb does have info like that accessible via the API; however, alot of info is missing or inaccurate.
Regarding the inaccuracies: Themoviedb API provides several different flags regarding the release date. Some releases might premier (type 1) at special events, such as film festivals, or be available to a limited audience (type 2) before the regular release before being released to the general public (type 3).
Currently, the first (?) available date is used which makes the calendar feature a bit unreliable if you want to watch it in cinema. 
Optionally, one could use the iso_3166_1 country code to make it more precise depending on the region.

**Comment by galli-leo** [comment] 2019-04-03 08:24
What I have planned is using our upcoming API v3, which will hopefully include all release dates and use return release dates from TMDB and IMDB, as well as allow the ability for adding custom ones (some time in the future).

**Comment by henryschade** [comment] 2019-06-02 14:35
I too would like to see a "Digital" and "Physical" release date added to Radarr (mostly for the calendar, but in the movie listing would be handy too).

**Comment by Qstick** [comment] 2020-07-13 03:48
Done, v3

**Closed by Qstick** 2020-07-13 03:48 UTC
Labels: feature request
