### ISSUE TITLE
The string can't be left empty

### ISSUE THREAD

**Issue by OFark** [Radarr/Radarr#3282] opened 2019-01-01 15:54 UTC
**Describe the bug**
Trying to change the folder name of a movie.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a movie
2. Click on edit
3. change the path
4. nothing happens.
5. inspect the response (in Chrome for example)
6. get JSON:
"message": "The string can't be left empty, null or consist of only whitespaces.\nParameter name: path",
  "description": "System.ArgumentException: The string can't be left empty, null or consist of only whitespaces.\nParameter name: path\n  at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsNotNullOrWhiteSpace (NzbDrone.Common.EnsureThat.Param`1[T] param) [0x0001e] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Common\\EnsureThat\\EnsureStringExtensions.cs:18 \n  at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath (System.String path) [0x0000d] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Common\\Extensions\\PathExtensions.cs:28 \n  at NzbDrone.Common.Extensions.PathExtensions.PathEquals (System.String firstPath, System.String secondPath, System.Nullable`1[T] comparison) [0x00027] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Common\\Extensions\\PathExtensions.cs:54 \n  at NzbDrone.Core.Validation.Paths.RootFolderValidator+<>c__DisplayClass2_0.<IsValid>b__0 (NzbDrone.Core.RootFolders.RootFolder r) [0x00000] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Core\\Validation\\Paths\\RootFolderValidator.cs:21 \n  at System.Collections.Generic.List`1[T].FindIndex (System.Int32 startIndex, System.Int32 count, System.Predicate`1[T] match) [0x00033] in <7b0d87324cab49bf96eac679025e77d1>:0 \n  at System.Collections.Generic.List`1[T].FindIndex (System.Predicate`1[T] match) [0x00000] in <7b0d87324cab49bf96eac679025e77d1>:0 \n  at System.Collections.Generic.List`1[T].Exists (System.Predicate`1[T] match) [0x00000] in <7b0d87324cab49bf96eac679025e77d1>:0 \n  at NzbDrone.Core.Validation.Paths.RootFolderValidator.IsValid (FluentValidation.Validators.PropertyValidatorContext context) [0x0001c] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Core\\Validation\\Paths\\RootFolderValidator.cs:21 \n  at FluentValidation.Validators.PropertyValidator.Validate (FluentValidation.Validators.PropertyValidatorContext context) [0x00029] in C:\\projects\\FluentValidation\\src\\FluentValidation\\Validators\\PropertyValidator.cs:79 \n  at FluentValidation.Validators.DelegatingValidator.Validate (FluentValidation.Validators.PropertyValidatorContext context) [0x00013] in C:\\projects\\FluentValidation\\src\\FluentValidation\\Validators\\DelegatingValidator.cs:62 \n  at FluentValidation.Internal.PropertyRule.InvokePropertyValidator (FluentValidation.ValidationContext context, FluentValidation.Validators.IPropertyValidator validator, System.String propertyName) [0x00009] in C:\\projects\\FluentValidation\\src\\FluentValidation\\Internal\\PropertyRule.cs:368 \n  at FluentValidation.Internal.PropertyRule+<Validate>d__60.MoveNext () [0x000e6] in C:\\projects\\FluentValidation\\src\\FluentValidation\\Internal\\PropertyRule.cs:242 \n  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in <7b0d87324cab49bf96eac679025e77d1>:0 \n  at System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) [0x000f4] in <7b0d87324cab49bf96eac679025e77d1>:0 \n  at System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) [0x00000] in <7b0d87324cab49bf96eac679025e77d1>:0 \n  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].ToList () [0x00028] in <079d1695f1b940b981a821e75d331759>:0 \n  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <079d1695f1b940b981a821e75d331759>:0 \n  at FluentValidation.AbstractValidator`1[T].Validate (FluentValidation.ValidationContext`1[T] context) [0x0001d] in C:\\projects\\FluentValidation\\src\\FluentValidation\\AbstractValidator.cs:114 \n  at FluentValidation.AbstractValidator`1[T].Validate (T instance) [0x00000] in C:\\projects\\FluentValidation\\src\\FluentValidation\\AbstractValidator.cs:95 \n  at NzbDrone.Api.REST.RestModule`1[TResource].ReadResourceFromRequest (System.Boolean skipValidate) [0x00024] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\REST\\RestModule.cs:201 \n  at NzbDrone.Api.REST.RestModule`1[TResource].<set_UpdateResource>b__44_1 (System.Object options) [0x00000] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\REST\\RestModule.cs:183 \n  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "

**Expected behavior**
I expect it to save the path to the movie

**Desktop (please complete the following information):**
 - OS: unRAID 6.6.6
 - Browser and Version Chrome 71.0.3578.98

**Debug Logs**
[https://pastebin.com/4F2LtWFp](https://pastebin.com/4F2LtWFp)

**Comment by OFark** [comment] 2019-01-01 23:56
No, it's a bug, I'm getting a 500 error in my browser on the ajax call. I don't need support, this needs to be fixed. By the looks of it, the ajax request is sending an empty path when the path input box isn't empty. My guess is it's a bad ID, but whatever the reason, it's a bug.

**Comment by OFark** [comment] 2019-01-05 17:14
Thank you. :)
[https://imgur.com/a/BPLJmND](https://imgur.com/a/BPLJmND)

So steps to get here:
Edit movie, click Save. It tells me the path that it has is invalid, (it isn't). So I click the browse button, select the same path again, this time it puts a / at the end of the path, and now Save does nothing, or at least it appears to do nothing. There is an XHR request, but it's throwing a 500. I pulled up the Chrome Console so you could see the error. Anything else you need, let me know, I'm a seasoned C# Web Developer.

**Comment by galli-leo** [comment] 2019-01-05 19:54
Can you post the actual content of both puts as reported by chrome? I still cannot reproduce this :/ Can you also try without organizr? I.e. connecting to Radarr directly via the ip? I would also try clearing the cache just to rule that out.

**Comment by OFark** [comment] 2019-01-10 09:21
That last test was direct to IP, no Organizer, no reverse proxy. I'm wondering if Grammarly is interfering, I'm at work at the moment I'll test vanilla Chrome tonight.

**Comment by OFark** [comment] 2019-01-10 18:22
It's doing it in Incognito mode as well

**Comment by OFark** [comment] 2019-01-12 14:13
Same problem in Firefox and IE11

**Comment by OFark** [comment] 2019-01-12 15:32
Fixed it.
The problem wasn't with the request being sent. I downloaded the code and looked over it, it was failing to get a path for a root folder entry from the DB.

I deleted the Root folder entry from the DB that had a blank path field. and all is well.

My opinion; there should either be some code to ignore broken Root Path's, or a way to edit them and a message to tell the user that's what the problem is.

**Comment by galli-leo** [comment] 2019-01-29 10:05
Agreed. Feel free to submit a PR for this. I am currently limited on time.

**Comment by hakong** [comment] 2019-02-19 13:06
Having the same issue trying to import movies. Activity -> Queue -> Manual Import -> nothing happens.
Developer tools says the request to /api/manualimport?downloadId=xxxx responds with a 500 Internal Server Error.
`  "message": "The string can't be left empty, null or consist of only whitespaces.\nParameter name: path",
`

**Comment by OFark** [comment] 2019-02-20 08:08
You need to edit the DB file in the config. Search for an SQLite editor, there are free ones available. Frind the RootPath table and remove any entries that are null or empty.

**Comment by bakerboy448** [comment] 2020-11-14 08:18
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

**Closed by bakerboy448** 2020-11-14 08:18 UTC
Labels: bug, confirmed
