### ISSUE TITLE
[BUG]: Renaming and moves files from subdir (Plex extra material into movie folders) 

### ISSUE THREAD

**Issue by casperse** [Radarr/Radarr#6714] opened 2021-11-09 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Renaming files will also rename subdir with extra material like:
https://support.plex.tv/articles/local-files-for-trailers-and-extras/

Radarr will move the files and rename the video to the same name as the extrnal files
If any subs then they will also be moved and renamed .1.srt , .2.srt , 3.srt 

This was tested with the folder named "other" since this folder is supported by Plex, Emby and more

### Expected Behavior

Only rename files in directory - not subdirs

### Steps To Reproduce

Just rename any movie with a extra suddir for extra material like
https://support.plex.tv/articles/local-files-for-trailers-and-extras/

### Environment

```markdown
Version 4.0.0.5450
Package Version 4.0.0.5450-ls149 by linuxserver.io 
.NET Yes (5.0.10)
Docker Yes
```

### What branch are you running?

Nightly

### Anything else?

No logs needed its a "feature" :-) but for people with allot of extra material in subfolders its a pain

[AB#1889](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1889)

**Comment by casperse** [comment] 2021-11-09 10:26
Example of extra material subfolders:
![billede](https://user-images.githubusercontent.com/2026859/140907446-e4413ba1-dc18-4dd9-80cf-238d8c0030d6.png)

**Comment by ta264** [comment] 2021-11-09 10:29
Sorry I don't follow.

Please can you give a concrete example of what is currently happening and what you think should happen instead.

**Comment by casperse** [comment] 2021-11-09 12:44
Above extra material folders inside Plex gets moved to the root folder of the Movie folder when pressing rename

Please seee the picture in above post:
/Other
Behind the scene.mkv
behind the scene.uk.srt

--> Moved to root of the folder
/Movie Title (YEAR)
Renamed.mkv
Renamed.srt1.srt

**Comment by bakerboy448** [comment] 2021-11-09 13:24
Duplicate of numerous issues.

> /Other
> Behind the scene.mkv

- support for multiple video files in radarr does not exist at this time, including behind the scenes

> behind the scene.uk.srt

- importing subtitles from a sub folder is a duplicate of about a half dozen issues

various related GHI:
https://github.com/Radarr/Radarr/issues/5378
https://github.com/Radarr/Radarr/issues/5210
https://github.com/Radarr/Radarr/issues/4267
https://github.com/Radarr/Radarr/issues/4637

**Closed by bakerboy448** 2021-11-09 13:24 UTC
Labels: Type: Bug, Status: Needs Triage
