### ISSUE TITLE
Library import not parsing nfo files?

### ISSUE THREAD

**Issue by DrTron** [Radarr/Radarr#9599] opened 2024-01-14 00:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Yes, I admit that I have an unusual folder structure, but the classic {Movie Title} ({Release Year}) isn't working for me as it generates too many folders in the directory.
So my structure is different, but consistent: 
`{Movie Title First Letter}/{Movie Title}.{year}/{Movie Title}.{year}.{videoFormat}.{videoCodec}.{audioCodec}.ext`
So I get that Radarr is having a hard time diving into that folder structure.

But every folder containing a movie has a nfo file named the same, and that includes everything Radarr would need to identify that movie, including a TMDB id.

Isn't such info parsed? Currently, no movie is being identified, no matter where I point the library import. Not even when pointed down to the folder containing the files.

### Describe the solution you'd like

Parse existing nfo files to identify movie

### Describe alternatives you've considered

tinyMediaManager parses the folder structure correctly.

### Anything else?

n/a

**Comment by bakerboy448** [comment] 2024-01-14 19:46
> consistent:
{Movie Title First Letter}/{Movie Title}.{year}/{Movie Title}.{year}.{videoFormat}.{videoCodec}.{audioCodec}.ext

you assign each letter as the root folder / import from there  and there should be no issues

**Comment by bakerboy448** [comment] 2024-01-14 19:47
- duplicate of https://github.com/Radarr/Radarr/issues/4200
- Related to https://github.com/Radarr/Radarr/issues/1170

**Closed** 2024-01-14 19:46 UTC
Labels: Type: Support

**Comment by DrTron** [comment] 2024-01-14 21:19
> you assign each letter as the root folder / library import from there and there should be no issues

Sadly, that isn't working, either. Not even when I try to import the folder that holds a single movie.
Thanks for linking the previous issues dating back a few years, seems that this has come up previously but was never implemented?
