### ISSUE TITLE
Option to only remove the video file and not flush the whole folder when a movie is upgraded

### ISSUE THREAD

**Issue by Piddox** [Radarr/Radarr#10094] opened 2024-06-18 09:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Whenever a movie is upgraded and imported, the whole movie folder is flushed and then the upgraded movie file is imported.
This causes a potential loss of other files in that folder such as subtitles. These files may still be useful for the upgraded movie. Or if you decide to revert back to the old movie (because the upgrade actually did not turn out to be not the desired upgrade), you want those old files back as well.

### Describe the solution you'd like

I would like an optional field in the settings where you can choose whether to flush the whole folder or only delete the video file in case of an upgrade. The default value should probably be to flush the folder.

### Describe alternatives you've considered

The alternative is the current situation: I have to try to remember whether I had extra subs in that folder or not, and then check if I can find subs again which fit the new or old video file, and then decide whether to keep or toss the upgraded video file. Time consuming and not ideal.

### Anything else?

The first thing that usually comes as a response to such issues is: "But then you should fix your media profiles/custom formats." Unfortunately, radarr does not do profile scoring based on subtitles available in the releases, so this is not a solution for this particular problem.

**Comment by bakerboy448** [comment] 2024-06-18 10:19
Duplicate of https://github.com/Radarr/Radarr/issues/5210

**Closed by bakerboy448** 2024-06-18 10:19 UTC
Labels: Type: Feature Request, Status: Needs Triage
