### ISSUE TITLE
Radarr shows English release for a multi-language release

### ISSUE THREAD

**Issue by m3mphis9** [Radarr/Radarr#8382] opened 2023-04-23 21:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When searching for releases, Radarr shows English for releases that have more than 1 language. MULTI languages parameter has been set on the indexer for English and French.
See screenshot for current behaviour.
![v4 4 4](https://user-images.githubusercontent.com/131619525/233865234-a2d80433-69cd-4832-bce8-50ef8ccfec66.png)

### Expected Behavior

Radarr should show Multi-Language under Language instead of English. It used to be working fine in version 4.3.2, but somewhere in between 4.3.2 and 4.4.4 it broke.
Got confirmation from Qstick that it is broken, see link https://github.com/Radarr/Radarr/commit/cbcf3d1058f47a87c43658084eafac13e7e0889f

See screenshot for behaviour in version 4.3.2.
![v4 3 2](https://user-images.githubusercontent.com/131619525/233865985-5408a3a0-4eba-4100-9100-49afaca54712.png)

### Environment

```markdown
- OS: Debian 11
- Radarr: 4.4.4.7068
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Google Chrome 112.0.5615.121
- Database:
```

### What branch are you running?

Master

### Trace Logs?

![v4 4 4](https://user-images.githubusercontent.com/131619525/233866010-d2cb05e4-d215-4824-92c6-01f3b51dae81.png)
![v4 3 2](https://user-images.githubusercontent.com/131619525/233866011-7a94c5be-cb4d-4967-8232-8295b55402c0.png)

**Comment by bakerboy448** [comment] 2023-04-30 04:28
Duplicate of #8328

**Closed by bakerboy448** 2023-04-30 04:28 UTC
Labels: Type: Bug, Status: Confirmed, Type: Regression, Type: Duplicate
