### ISSUE TITLE
[Feature Request] One Movie Multiple Profiles

### ISSUE THREAD

**Issue by joshuader6** [Radarr/Radarr#1595] opened 2017-05-29 17:49 UTC
I like watching Movies in English. But most of my Family wants to watch movies in German. 
So how about assigning a movie two Profiles and append the Profile name to the movie naming?

**Comment by galli-leo** [comment] 2017-05-29 18:19
Duplicate of #1352 :)

**Closed by galli-leo** 2017-05-29 18:19 UTC
