### ISSUE TITLE
Filter Option on Movie Page for "Status" shows incorrect options

### ISSUE THREAD

**Issue by Sytanek** [Radarr/Radarr#4593] opened 2020-07-15 13:20 UTC
**Describe the bug**
When trying to filter the movie page, creating a filter based on Status give pre-populated values from Minimum Availability instead of Status. 

**To Reproduce**
1. Go to Movies Page, have both "Minimum Availability" and "Status" showing as visible columns. 
2. Click on Filters, and crate a new custom filter.
3. Select Status as one of the filters. 
4. The only possible values are actually for Minimum Availability not Status. 

**Expected behavior**
The possible values should match the values possible under "Status".

**Screenshots**
I can provide via email if needed. 

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser and Version Chrome
 - Radarr Version Building from Source - aphrodite branch, commit d7e0625be74863a59bdb595227a5efb214ab628f

The easiest fix would to relabel the status filter option to "Minimum Availability", but I'm really hoping for the actual ability to filter based on status.

**Comment by austinwbest** [comment] 2020-07-16 17:44
Simple version:
Status is mis-labeled and should be Minimum Availability
Minimum Availability is missing

That sums it up right? I had to read yours about 17 times before it finally clicked (prolly just me being dumb)

**Comment by Sytanek** [comment] 2020-07-16 18:21
Bug - The current filter option "Status" is mis-labeled and should actually be "Minimum Availability". 

Feature Request - Add "Status" as a filter option. (I can move this to a new report if it helps)

**Comment by ta264** [comment] 2020-07-16 18:27
I guess we could always fire off a tmdb / IMDb lookup if the query matches that format and prepend it to the result list.

Might be a bit wonky if you're searching for 500 and get back reservoir dogs. I'm inclined to say its better left as is

**Comment by Sytanek** [comment] 2020-07-16 18:33
@ta264 i'm confused what your comment has to do with my bug report tbh.

**Comment by austinwbest** [comment] 2020-07-16 18:58
You could have simply said yes :) I think 1 bug report is enough since they are directly related (personally).

**Comment by ta264** [comment] 2020-07-16 19:15
My comment was on the wrong bug :(

**Comment by austinwbest** [comment] 2020-07-16 19:18
> My comment was on the wrong bug :(

I saw the reply in my email and was about to come mention that

**Comment by geogolem** [comment] 2020-08-27 17:46
I think I have some insight into what is happening here...

I think the Status choices are those of MinimumAvailabity.. there is no PreDB there..

Rather the Status in the filtering is referring to "Release Status" (i think)...

like the column in the options "release Status"

I think this should be renamed to "Release Status"

I also think the custom filters should be able to filter based on Status which would be "Downloaded", "Missing" "Not Available" etc.

I'm then also thinking about making a new status called "Soon Available" which would cover some aspects of a feature requested in: https://github.com/Radarr/Radarr/issues/2074

**Comment by geogolem** [comment] 2020-08-27 22:39
So I am working on 1) and 2) . The issue is, The column named Release Status in the table options is referred to in the code as MOVIE_STATUS or movieStatus., and this is what the existing custom filter is referring to. The column in the table lablled Status is referred to in the code as MovieFileStatus...  It should be consistent.. Status in the custom filters should be renamed to "Release Status" to correspond with the table options column, and a new filter for Status should be implemented that corresponds to the Column in the table called Status (MovieFileStatus - in the code).. I'm working on this now.

**Comment by austinwbest** [comment] 2020-08-27 22:51
Wonder if this will create some confusion too, as they are grouped.. Or maybe i am not understanding what you're wanting to change

The status covers all of them visually.

I cant get the stupid code block to work so you'll have to work with it..

----------------------------
const queueStatusText = getQueueStatusText(queueStatus, queueState);
  let movieStatus = (status === 'released' && hasFile) ? 'downloaded' : status;

  if (movieStatus === 'deleted') {
    movieStatus = 'announced';

    if (hasFile) {
      movieStatus = 'downloaded';
    } else {
      movieStatus = 'released';
    }
  }
-----------------------------

This groups all downloading options + downloaded/announced/released/etc into the same label in the UI (on posters for example, the calendar, movie details, etc)

**Comment by geogolem** [comment] 2020-08-27 23:20
it is very confusing, because, status on its own can mean different things in different places in the code.. this is why it got sort of screwed up.

In general it is correct that, 

Release Status corresponds to Announced, Released, InCinemas etc.

and MovieStatus corresponds to Downloaded, Missing etc.

but im looking through now trying to figure out what is going on. its ust a matter of cleaning it up andm aking it consistent.

**Comment by geogolem** [comment] 2020-08-28 00:06
i need to go do something else now, but i did make some progress. Im still in the middle of it, but you can take a look there.

**Comment by geogolem** [comment] 2020-08-28 03:37
so with the code Commited at this point and referring to the previous discussion in this issue the following is a status update for the work items to be addressed by this issue:

(1) Implemented and functional
(2) Partially implemented but not functional
(3) Not implemented at all
(4) Implemented and functional
(5) Not Implemented at all

**Comment by geogolem** [comment] 2020-08-28 04:11
I think this issue is resolved: and the Soon Available feature can be handled by this issue: https://github.com/Radarr/Radarr/issues/2074

In summary this issue:
(1) Renames existing 'Status' filter to 'Release Status'
(2) Added MinmumAvailablity and IsAvailable to the Custom filters.

**Comment by Sytanek** [comment] 2020-08-28 10:07
@geogolem Earlier when you mentioned MovieFileStatus is what is being shown, this is exactly what I was hoping for a filter on. I see you've been doing some serious work to fix this stuff up, and hope this field can be included as a custom filter. Thanks!

**Comment by geogolem** [comment] 2020-08-28 15:28
> @geogolem Earlier when you mentioned MovieFileStatus is what is being shown under the "Status" Column in the GUI, this is exactly what I was hoping for a filter on. I see you've been doing some serious work to fix this stuff up, and hope this field can be included as a custom filter. Thanks! (I like to move files that have hit a certain quality on disk to cold storage, so this filter would make finding those simpler).

I actually abandoned it, since many of those types can be filtered with the other options. the only one that is not totally apparent is downloaded Quality --> though perhaps cutoff Unmet could be used to handle some of those cases, and/or if you leave the quality in the filenames, you could filter based on the quality in the filename.. However, it would be nice to have an easier more direct way to filter that column - it is slightly more complicated than the others - so leave this issue open and I will see what I can do.

**Comment by geogolem** [comment] 2020-09-11 22:12
The PR associated with this issue fixes the filters so that they are more accurately labelled:

"MinimumAvailability" and "Release Status" --> and the filters now work appropriately for those. 

A new feature request has been opened here: https://github.com/Radarr/Radarr/issues/5004 to address the fact that the Status column does not currently have any filtering options.

**Closed** 2020-11-13 04:13 UTC
Labels: bug
