### ISSUE TITLE
Rating percentage rounding error on "Discover" page

### ISSUE THREAD

**Issue by jrucker2004** [Radarr/Radarr#7466] opened 2022-08-09 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the Discover page, I ran into an instance of the rating percentage not rounding correctly.  I don't know if this is doing some math within Radarr, or if it's just displaying the percentage it gets from an external API, but either way, rounding or truncating this value might be a good idea.  See screenshot for example.  This is the only example I've seen so far.

![Screenshot_20220809_073441](https://user-images.githubusercontent.com/19860871/183677445-93acee73-2eda-4bed-9c1d-2aa9e7a4a700.png)
.

### Expected Behavior

Rating percentages should be rounded or truncated to a reasonable length.

### Steps To Reproduce

I don't know how to reliably reproduce this error without stubbing the API Radarr uses to grab ratings.

1. Navigate to the Discover page.
2. Scroll down until a large percentage displays.

### Environment

```markdown
- OS: Truenas jail
- Radarr: 4.1.0.6175
- Docker Install:No
- Using Reverse Proxy:No
- Browser:Firefox
```

### What branch are you running?

Master

### Trace Logs?

![Screenshot_20220809_073441](https://user-images.githubusercontent.com/19860871/183677965-84ea62bf-6949-415f-8975-04b73baddf7d.png)

[AB#3447](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3447)

**Comment by bakerboy448** [comment] 2022-08-09 14:43
Duplicate of #7404

**Closed by bakerboy448** 2022-08-09 14:43 UTC
Labels: Type: Bug, Area: UI, Type: Duplicate
