### ISSUE TITLE
home page - table view - sort by downloaded broken

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2548] opened 2018-02-19 19:49 UTC
on home page with table view, can see there is data for *downloaded*
![radarr](http://zoggy.net/firefox_2018-02-19_13-47-34.png)

sort by downloaded, data goes missing until you sort by another column
![radarr2](http://zoggy.net/firefox_2018-02-19_13-49-01.png)

**Comment by thezoggy** [comment] 2018-02-19 19:55
sorting by downloaded does work in movie editor.. which is using code from
`var DownloadedQualityCell = require('../../Cells/DownloadedQualityCell');`

**Comment by galli-leo** [comment] 2018-02-19 21:09
Duplicate of #2195

**Closed by galli-leo** 2018-02-19 21:09 UTC
