### ISSUE TITLE
Downloads added via radarr whose names don't match the movie name aren't tracked

### ISSUE THREAD

**Issue by kaysond** [Radarr/Radarr#2444] opened 2018-01-23 06:35 UTC
Manually searched a movie that is indexed properly, but whose nzb name is the Japanese version of the name. The download was successfully sent to nzbget, but it wasn't tracked at all. Once it finished, radarr didn't recognize the completion. When I changed the name in nzbget, though, it found it.

It would be nice if the download monitor kept track of the download by id/hash/whatever, so this isn't an issue.

**Comment by galli-leo** [comment] 2018-01-30 14:41
We do keep track of the download id, the problem is if the title doesn't match when we want to import we fail the download. For example, a download could have the wrong file (thus a wrong name) and we don't want to import that. I have an idea how we can fix that (see 7. on https://github.com/Radarr/Radarr/issues/1407#issuecomment-309006654), so closing this issue as a duplicate of #1407)

**Closed by galli-leo** 2018-01-30 14:41 UTC

**Comment by kaysond** [comment] 2018-01-30 17:35
Unfortunately there's no alternative title for this case, so that wouldn't work. But manually downloading it would be fine, plus your plan for a mapping database. Plus your #1 suggestion. It looks like that hasn't made it into a release though? Is there an easy way to get the nightly on linux? Or do I have to build it on a windows machine first?

**Comment by galli-leo** [comment] 2018-01-30 18:07
@kaysond All the things in that comment that are checked are implemented on the latest develop (Mappings database is available under https://mappings.radarr.video). I know that no alt title is available. 7. would automagically add one when imdbid matches, but title doesn't when downloading a release.

**Comment by kaysond** [comment] 2018-01-30 18:15
Got it, thanks.

**Comment by gacpac** [comment] 2019-05-13 15:45
I'm having the same problem. All I want is to manually change the name, because the movie originally has accents in the letters.
