### ISSUE TITLE
Bulk add movies from disk?

### ISSUE THREAD

**Issue by JohnnyT009** [Radarr/Radarr#423] opened 2017-01-24 16:00 UTC
Is there a better way to add existing movies. I have over 1600 movies and would not like to add them one at a time. Am I totally missing something? Sonarr makes me do the same thing but I only have 60 some tv shows so although that is arduous it is doable. If this is not a feature could you please add it? My movies are sorted quite well but I would like it to know what I have and do not have.

**Comment by fedoranimus** [comment] 2017-01-24 16:02
Duplicate of #150

**Closed by fedoranimus** 2017-01-24 16:02 UTC
