### ISSUE TITLE
better handeling of Activity > Queue > Movies with issues

### ISSUE THREAD

**Issue by bob454522** [Radarr/Radarr#4651] opened 2020-07-26 21:26 UTC
Hi,  
running: Radarr Ver. 0.2.0.1504

we very much need improvements to the  Activity > Queue sections.
In terms of handling files with
+Unable to parse file
+ File quality does not match quality of the grabbed release

This is an issue on all radar installs , but especially on a radarr setup with 38k + Movies and ~1245+ movies/entries in the  Activity > Queue  section.

Possible solutions:
Multi Select (so you can quickly multi black list entries)
Multi Select (so you can quickly/easily force accept entries with "File quality does not match quality of the grabbed release"  ->  this should be up to the user if they want to allow poor file naming practices into their system.)

or even just:   Enter to accept modal (Esc key to press cancel / exit on modal) - like sonarr has

or even just pre populate the check boxes, dropdown  when you click the "manual import" icon
 (ie remember "Copy Files" if it were used last time,
or if you click on the row, then check off that row's checkbox (as opposed to currently you must click the actual checkbox of a row/ "relative path")

anything to cut down on the number of clicks / key strokes to manually address import issues in this section)

thanks

**Comment by bakerboy448** [comment] 2020-11-13 04:21
root cause likely addressed in v3; if it is still an issue in v3 (and is not related to the Qbt issue) then open a new GHI with trace logs.

hotkeys exist in v3, see the dialogue in top right

**Closed by bakerboy448** 2020-11-13 04:21 UTC
Labels: feature request
