### ISSUE TITLE
Custom categories, ability to add an indexer without a test connection

### ISSUE THREAD

**Issue by awhileback** [Radarr/Radarr#6887] opened 2022-01-01 04:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Yes, there are existing issues for this. #6256 

CouchPotato is dead, yet even with python 2.7 it works with the indexers I have api keys for. Sonarr also allows me to use the indexers I have api keys for by manually entering categories.

### Describe the solution you'd like

Add the ability to save an indexer with default settings that doesn't respond to test queries. Add the ability to input custom categories, as sonarr can.

### Describe alternatives you've considered

Reinstall python 2.7 and go back to Couchpotato, patch it myself to know what WEBDL is, apparently the last version does not.

### Anything else?

Considering there are posts on this issue forum, pages worth of similar posts on reddit, and multiple google search results on how to add custom categories, I don't think you're accomplishing anything by ignoring these other than putting one more nail in the coffin of newsgroup binaries.

Dashboard looks nice, I guess, too bad I can't actually do anything because it won't let me save indexers.

[AB#2294](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2294)

**Comment by bakerboy448** [comment] 2022-01-01 04:19
Duplicate of #6256

**Comment by bakerboy448** [comment] 2022-01-01 04:20
Sonarr does not support custom categories.  You're likely on Sonarr v2 which is end of life and  having support phased out.

**Closed by bakerboy448** 2022-01-01 04:19 UTC
Labels: Type: Feature Request, Status: Needs Triage
