### ISSUE TITLE
ability to import/ handling ability to import from torrent client the Featurettes folder subfolder that comes on some release groups[FEAT]: 

### ISSUE THREAD

**Issue by aniel300** [Radarr/Radarr#6645] opened 2021-10-06 01:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

ability to import/ handling ability to import from torrent client the Featurettes folder subfolder that comes on some release groups

### Describe alternatives you've considered

filebot since i would like to use the rename option of radarr, but i dont see an option teel radarr to import renamed files by filebot

### Anything else?

n/a

[AB#1737](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1737)

**Comment by bakerboy448** [comment] 2021-10-06 01:11
Please actually search next time 

simply searching `featurette` returns results.

duplicate of https://github.com/Radarr/Radarr/issues/5771

duplicate of https://github.com/Radarr/Radarr/issues/1742

**Closed by bakerboy448** 2021-10-06 01:11 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by aniel300** [comment] 2021-10-06 06:33
do u have any plan on adding this ?

**Comment by bakerboy448** [comment] 2021-10-06 15:46
> do u have any plan on adding this ?

Refer to the duplicate issue comment
https://github.com/Radarr/Radarr/issues/5771#issuecomment-761832305

In other words - maybe once that collective can of worms is opened, but not anytime soon nor the near future.
