### ISSUE TITLE
Pagination needed on Movies page for large collections

### ISSUE THREAD

**Issue by drafie** [Radarr/Radarr#777] opened 2017-02-17 00:38 UTC
We need pagination on the homepage / movies page to limit the amount of movies loaded at one time. 

I have managed to import about 6,000 movies so far - unfortunately not with Bulk Import (different problem) - but I find that opening Radarr now causes the browser to frequently hang or crash in Chrome.

**Comment by fedoranimus** [comment] 2017-02-17 00:39
Duplicate of #762

**Closed by fedoranimus** 2017-02-17 00:39 UTC
