### ISSUE TITLE
V3 deleting existing artwork upon Refresh & Scan

### ISSUE THREAD

**Issue by lexguy2007** [Radarr/Radarr#5519] opened 2020-12-08 18:57 UTC
**Describe the bug**
When Refresh & Scan of a movie is performed, Radarr is deleting existing artwork and replacing some existing artwork for that movie. This is happening when a new file is downloaded that is of higher quality and when the file gets renamed (using another program). Each instance when the movie is rescanned, Radarr is deleting the artwork. Also, it does not matter if, in the settings under Metadata, Movie Images is checked or not.

**Expected behavior**
I would expect if there is existing artwork, that it be left alone and only the updated file information within Radarr be updated to reflect the changes. I spend a lot of time downloading specific artwork for my movies and do not want Radarr deleting them or changing them just because a movie is upgraded or renamed.

**Screenshots**
This screenshot is showing the artwork present in the movie folder before rescanning the renamed movie:
![1 Screenshot Before 2020-12-08 121040](https://user-images.githubusercontent.com/13860924/101527604-d4314680-3953-11eb-8566-b8c6df7894bf.png)

This is what the folder looked like after rescanning in Radarr. Files missing:
![2 Screenshot After 2020-12-08 121040](https://user-images.githubusercontent.com/13860924/101527854-270afe00-3954-11eb-90a4-403ac44ecdb3.png)

Screenshot of the even log showing the rescanning in Radarr:
![1 Screenshot event log 2020-12-08 125403](https://user-images.githubusercontent.com/13860924/101528143-8406b400-3954-11eb-9515-a5482f6a28e4.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Docker: No
 - Radarr Version [3.0.0.4204
 - Radarr Branch develop

**Comment by bakerboy448** [comment] 2020-12-08 19:33
Dupe of the various existing other issues

On mobile else I would link

**Closed by bakerboy448** 2020-12-08 19:33 UTC
Labels: bug

**Comment by lexguy2007** [comment] 2020-12-11 17:24
Is there something that can be done to stop Radarr from deleting my artwork? This is killing me.

**Comment by bakerboy448** [comment] 2020-12-12 22:31
> Is there something that can be done to stop Radarr from deleting my artwork? This is killing me.

some folks use a custom script to temp move the stuff out of the folder.  check on the GHI i linked on your duplicate of this GHI.

but we're well aware Extras need TLC...no need to spam about it
