### ISSUE TITLE
Bulk import can't find movies when this movie is included

### ISSUE THREAD

**Issue by zapras** [Radarr/Radarr#2415] opened 2018-01-12 23:45 UTC
I had problems adding my 2000+ collection with bulk import. It said:

> No movies found in folder /movies/. Have you already added all of them?

I looked through the debug log and found the last movie it was processing before it stopped was "Best Worst Movie (2009) HDTV-1080p.mkv". I then removed that movie and the bulk import was working fine.  I'm not sure how I got the movie. But Radarr probably downloaded from PB before I shifted my movie collection from Windows to Linux. The format of the movie is a bit strange.

The container of the movie is mkv.
Codec: MPEG-1/2 Video (mpgv)
Resolution: 1920x1088
Display resolution: 1920x1080
Frame rate: 29.970029

Radarr Version: 0.2.0.910

[Debug log](https://pastebin.com/DZG0mSx9)
[Trace log](https://pastebin.com/TNtsApLZ)

**Comment by galli-leo** [comment] 2018-01-13 07:40
Interesting almost seems like Radarr crashes on that file. Did you have to restart Radarr after that file? Because the only thing after that in the log is Radarr starting up again.

**Comment by zapras** [comment] 2018-01-13 21:40
Nope, just carried on. If Radarr did restart, I didn't notice it.

**Comment by galli-leo** [comment] 2018-02-07 15:44
Well I cannot reproduce this without the file, so closing this for now.

**Closed by galli-leo** 2018-02-07 15:44 UTC
Labels: bug, cannot reproduce, information needed
