### ISSUE TITLE
Setting URL Base breaks Logo

### ISSUE THREAD

**Issue by MeltedLux** [Radarr/Radarr#235] opened 2017-01-13 18:38 UTC
When setting a URL base to anything other than blank Radarr's 128, 64 & 32 logos break as the paths are not adjusted to match correctly:

128.png Failed to load resource: the server responded with a status of 404 (Not Found)
64.png Failed to load resource: the server responded with a status of 404 (Not Found)
32.png Failed to load resource: the server responded with a status of 404 (Not Found)

With a URL base of /radarr set:

http://127.0.0.1:7878/radarr/Content/Images/logos/128.png - dead
http://127.0.0.1:7878/Content/Images/logos/128.png - working

**Comment by fryfrog** [comment] 2017-01-13 18:53
Works for me through my reverse proxy with url-base set.

https://example.com/radarr/Content/Images/logos/128.png

**Comment by onedr0p** [comment] 2017-01-13 18:54
Same here, working thru my reverse proxy

**Comment by wcomartin** [comment] 2017-01-13 21:53
Works for me too with http://localhost:7878/radarr/Content/Images/logos/128.png

**Comment by fryfrog** [comment] 2017-01-13 22:23
I'd check that you actually fully stopped your original instance. If you're making the change to your config manually, make sure it is stopped when you do that.

**Comment by ShanDestromp** [comment] 2017-01-15 02:28
@MeltedLux can you attempt to recreate this with any recent version; making sure that Radarr is fully shutdown when upgrading (verify with `ps aux | grep [r]adarr` if running some form of *nix); and also clearing your browsers cache.

Like the others, I cannot reproduce this either directly or via my reverse proxy.

**Comment by onedr0p** [comment] 2017-01-15 02:31
Closing this issue it appears to be on his end only.

**Closed by onedr0p** 2017-01-15 02:31 UTC
Labels: cannot reproduce
