### ISSUE TITLE
Synology Docker DSM: Radarr not updateable

### ISSUE THREAD

**Issue by YcKe** [Radarr/Radarr#5633] opened 2020-12-26 19:35 UTC
**Describe the bug**
Currently it is not possible to update Radarr on a Docker DSM. A docker DSM is a virtualized Synology Operation system.

The check located in OsInfo currently avoids this:

`           
if (IsLinux && File.Exists("/proc/1/cgroup") && File.ReadAllText("/proc/1/cgroup").Contains("/docker/"))
{
      IsDocker = true;
} 
`

**To Reproduce**
1. Have Radarr V3 installed on a Docker DSM
2. Go to Update section
3. It is stated that you cannot update

**Expected behavior**
I have 2 suggestions:

1. Have the ability to overrule the ability to 'Not Update' Radarr within docker containers
2. Extend the check to verify that it is a Docker DSM image (In case IsDocker == true, check the file etc/synoinfo.conf exists and check if the file contains 'unique="synology_dockerx64_dockerdsm"') 

**Platform Information (please complete the following information):**
 - OS: Synology 6.2.3
 - Docker: YES (Docker DSM)
 - Mono or.NET Core Version: Mono 5.20.1.34
 - Radarr Version: 3.0.0.4204
 - Radarr Branch: develop

Note: I can code it myself and can create a PR but please suggest me a feasible solution for this issue.

**Comment by RobinDadswell** [comment] 2020-12-27 23:28
You should never update an application within a docker container, you should always recreate the container using the latest version

**Comment by bakerboy448** [comment] 2020-12-28 00:05
Sounds like DSM 6 (+?) Synology package created but the SynoCommunity and not maintained by Team Radarr is running as docker on the backend since Syno went that route.

shouldn’t those , similar to docker, be handled via package (~image) updates by the SynoCommunity who create and maintain the package ?

@Qstick , @austinwbest thoughts?

**Comment by YcKe** [comment] 2020-12-28 08:56
@bakerboy448 : Thanks for the feedback. You are correct, the package is created and maintained by the SynoCommunity. 

Initially (before version 3) it was possible to update Radarr to a newer version with the BuiltIn updater. (This is how I got on version 3 initially) Other packages such as CouchPotato and NZBGet have the ability to use the BuiltIn updater and is working flawlessly, so it it's not an uncommon practice. (On DSM and Docker DSM) 

To understand more about Docker DSM, you can see the Docker DSM as a virtual machine with it's own standalone environment and processes just like a Windows Virtual machine, it's not just 1 application which runs in a docker image but a complete operating system. 

F.y.i.: a PR where the version update is being discussed as we speak.: https://github.com/SynoCommunity/spksrc/pull/4309 .

**Comment by bakerboy448** [comment] 2021-01-19 21:25
Closing; Could not Reproduce

 8 year old NAS (DS412+ w/ DSM 6.2.3-25426 Update 3)  with SynoCommunity package

Though mine did install mono 5.2 as a prereq

updated to 3.0.2.4369 no issue; no docker error

**Closed by bakerboy448** 2021-01-19 21:25 UTC
Labels: enhancement
