### ISSUE TITLE
Feature Request: Backlog Search (not RSS)

### ISSUE THREAD

**Issue by drashna** [Radarr/Radarr#548] opened 2017-01-31 20:59 UTC
Add the option to periodically run a search for movies that are in the watched list, but don't meet the existing quality cutoff.

**Comment by Crowley007** [comment] 2017-06-02 21:40
For some reason, automatic upgrade with rss is failing sometimes, manual search always snatched the better version. It would be really useful to have backlog search for these cases, perhaps with limitations like physical release being available etc.

**Comment by euphoria360** [comment] 2018-03-02 08:26
@drashna @galli-leo I found a workaround way to do backlog searches via API and added the info to [API Wiki](https://github.com/Radarr/Radarr/wiki/API) and [API:Command Wiki](https://github.com/Radarr/Radarr/wiki/API:Command).

It uses curl to instruct Radarr to do a backlog search of missing movies based on filters.
we can use cron to automate it.
What do you guys think about it?

**Comment by galli-leo** [comment] 2018-03-04 14:17
I am closing this as it is absolutely unecessary and will only increase pressure on indexers. When you press the correct button, when adding, Radarr will already search for your movies. If no movie is found, it will continue to "search" your indexers for releases. Thus if you manage to press the correct button it will already function like the op suggests it should.

I will probably remove the add (without searching) option to not confuse new users and make it work regardless of what frontend you use. Though again the issue is not with Radarr, but IMO more so with your frontends not implementing the API correctly.

To iterate again, periodic movie searches are completely pointless, if you hit the correct button (or your frontend implements the API correctly) and IMO people are only requesting it, because they are unaware of how the rss sync works.

(Copied from feathub on the same feature request)

**Closed by galli-leo** 2018-03-04 14:17 UTC
Labels: enhancement, priority:medium, under investigation

**Comment by euphoria360** [comment] 2018-03-04 14:46
@galli-leo I think you are theoretically right. When we add a movie it is either released (add and search button) or going to be released in future (RSS functionality).
But at least in my setup (and lots of other users) the rss search (provided by jackett) doesnt work reliably and from time to time I need to login and manually hit the backlog search button.

I understand that sonarr/radarr work in a different way than sickrage/CP. but i guess rss functionality is mainly for usenet users. and the backlog search is definitely not a useless feature!

**Comment by galli-leo** [comment] 2018-03-04 15:15
@euphoria360 Jackett RSS searches work perfectly fine for me in both Radarr and Sonarr. Maybe the issue lies with your indexers? Anyways, you can achieve the same thing - as you pointed out - by a few lines of shell script and the api.

**Comment by euphoria360** [comment] 2018-03-04 15:23
@galli-leo can I ask what are your indexers and what are your settings for them in Jackett.

In the past few days, I was using torrentz2 and TPB as my indexers and i checked/set the movie categories for each indexer. but i got some warnings about missing periods of time in rss search.

Anyway, today I removed torrentz2 and set idope, thekat.nzand TPB.

I also only download yts,psa,mkvcage or etrg releases which offer good quality/size. so each torrent must contain one of these words in its name.

**Comment by galli-leo** [comment] 2018-03-05 21:25
@euphoria360 ATM mostly PrivateHD, used to use TPB, but don't feel the need anymore.

If you get warnings about missing periods of time, lower your RSS Sync time! Would certainly explain, why some releases aren't grabbed.

**Comment by euphoria360** [comment] 2018-03-06 03:28
@galli-leo Private tracker, no false releases then.
I'll lower rss sync time. hopefully that would fix it.

**Comment by grooves12** [comment] 2018-07-25 05:01
I prefer to not search for movies until physically released (this avoids garbage cam releases that are often mislabeled) 

This results in multiple missed movies without a backlog option.
