### ISSUE TITLE
Clickable paths and files

### ISSUE THREAD

**Issue by Milincho** [Radarr/Radarr#8705] opened 2023-06-16 15:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Can't open files or folders directly.

### Describe the solution you'd like

Clicking on the path label opens the file explorer in that path.

![image](https://github.com/Radarr/Radarr/assets/60118859/1f6d8af7-6958-4d56-818a-65809c619c96)

![image](https://github.com/Radarr/Radarr/assets/60118859/af738a0d-b5ed-422a-9607-caf6638b4610)

### Describe alternatives you've considered

.

### Anything else?

No.

**Comment by bakerboy448** [comment] 2023-06-16 16:40
Duplicate of https://github.com/Radarr/Radarr/issues/5757

**Closed by bakerboy448** 2023-06-16 16:40 UTC
Labels: Type: Feature Request, Status: Needs Triage
