### ISSUE TITLE
Request "Formats" column on main screen/movie listing

### ISSUE THREAD

**Issue by kingfenix** [Radarr/Radarr#6150] opened 2021-04-06 15:08 UTC
**Is your feature request related to a problem? Please describe.**
I have no way to easily find all the x265 movies in my collection.

**Describe the solution you'd like**
It would be great if there were a column for "formats" on the main screen/movie listing

**Describe alternatives you've considered**
Currently the only way I know to review this info is one at a time by clicking on the movie and reviewing in the file info.

**Additional context**
None

**Comment by bakerboy448** [comment] 2021-04-06 15:10
Duplicate of #5703 and numerous others 

Please use the search functionality before opening requests.

**Comment by kingfenix** [comment] 2021-04-06 15:10
I did search by the word formats, didnt find it, sorry

**Closed by bakerboy448** 2021-04-06 15:10 UTC
Labels: feature request
