### ISSUE TITLE
Search button should not be clickable if Monitoring is disabled

### ISSUE THREAD

**Issue by manad777** [Radarr/Radarr#3235] opened 2018-12-06 05:04 UTC
**Describe the bug**
From what I can see, the Search button has no effect unless the movie is also monitored. Therefore, why is it clickable at all? It's just confusing UI. Especially since the app also shows a popup saying it completed a search. 

**To Reproduce**
1. Add a movie, profile Any, Monitored set to No
2a. In the Add dialog, click Add And Search
2b. Alternatively, click just Add, then open the movie and click on Search
3. A popup saying "[moviessearch] completed" will appear. Logs will say "MovieSearchService | Movie search completed. 0 reports downloaded."

**Expected behavior**
The Search button should not be clickable. It should be visible, but disabled. Hovering on it should say why.

In the meantime (whether you disable it or not), in the absence of a manual for Radarr, the tooltip of each button should act as in-UI documentation. "Search Movie" is not a useful tooltip, since evidently it's not clear what it does. A better tooltip would be: "Searches indexers for a movie matching the given profile, and downloads if it finds a match. Does nothing unless the movie's monitoring is set to Yes".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Mono Version: 5.16.0.179
 - Firefox 63.0.3
 - Version 0.2.0.1217

**Debug Logs**
18-12-6 00:05:58.7|Debug|MovieSearchService|Movie The Big *****ski is not monitored, skipping search
18-12-6 00:05:58.7|Info|MovieSearchService|Movie search completed. 0 reports downloaded.

**Comment by Qstick** [comment] 2018-12-07 04:12
Question comes to mind here: Even if the movie is not monitored, should a manual user invoked search actually perform a search? If the user is clicking search doesn't that mean the user wants to search? (monitored or not). I would think instead of disabling search for monitored we should add some logic that if a user invoked search is performed we run the search. Thoughts?

**Comment by austinwbest** [comment] 2020-08-02 23:06
Old one here.. Monitored doesn't have a single meaning that the user doesn't want it. Maybe they are happy with the version they have already, etc

Monitored simply means it will be searched for automatically (be it missing or cut off, etc)

A user should not be blocked in the UI from a manual search, then you will have "why cant i search for things" because they as a new user do not understand fully how monitored works or when to use it. It seems much wiser to leave searching manually alone.

The search in v3 does exactly what is described so that is sorted.

I would recommend closing this @Qstick but i'm not sure if you would want to change the manual search logic (hopefully not!).

**Comment by harrv** [comment] 2021-02-03 23:09
I don't think this is a valid bug. Let me explain.

Radarr uses indexers in two ways:

1. It can send an immediate search request for a specific movie, and get the results back within a few seconds. The results contain only items that match the specific movie searched for. This is the type of search that a Radarr user triggers in real-time in the Radarr UI.

2. It can monitor the indexer for newly indexed items. The details of how it does this can vary (it can be an RSS feed published by the indexer, or a broad search request that Radarr sends to the indexer periodically) but the important thing to know is that when Radarr is configured to use this method, it gets a listing of all newly indexed items (potentially limited by category), not just those for one specific movie.

Method-1 is used when the user initiates a search in the Radarr UI, and is also an option when you initially add a movie to Radarr.

Method-2 is the unattended, automated, ongoing way Radarr finds releases you want.

For purposes of automation (using method-2) Radarr needs a way when it is going through those newly indexed releases to determine whether it is something you want or not. That's what the "monitored" flag is primarily for. For each of the newly indexed items, Radarr checks whether you have that movie in Radarr, and whether it is "monitored". If it is, then it checks the downloaded, minimum quality, cutoff status, etc. for that movie to determine whether or not you'd want it, and sends it to your downloader if you do.

So the reason the "monitored" flag is necessary and the way it is used for ongoing, automated, method-2 monitoring should now be clear. I suppose the issue we're discussing here then is how the "monitored" flag should affect method-1, user-initiated, real-time searching, if at all.

A user-initiated search in Radarr can be triggered in quite a few different ways and quite a few different places in the UI, but they all boil down to either searching for one specific movie (like when you are looking at a movie entry and you click either "Search Movie" or the Search tab), or searching for a specific list of movies (like when you are looking at a filtered list and click "Search Filtered" or in the Movie Editor when you click "Search All" or "Search Selected").

In my mind, in the context of user-initiated searching, "monitored" or "unmonitored" is just one more property that a user can filter on when selecting movies to search for. Other than that, it should not have any bearing on whether the movie is searched for or not. If the movie is selected for the search, then it should be searched for. I don't think anything else should be read into the intent of a movie's "Monitored" flag for real-time searching. It has much less relevance in this context than, say, minimum quality and cutoff do.

**Comment by bakerboy448** [comment] 2021-02-03 23:17
@harrv  Right, so there is a bug.

Option A: If not monitored the button should not be clickable as it does not search.  This is the OP and what you say is not a bug.

Option B: If not monitored the button should be clickable and the functionality corrected so it actually searches.  This is where I would foresee this heading, but that's Q's call

**Comment by harrv** [comment] 2021-02-03 23:22
@bakerboy448 Yes, if the issue reported is accurate, there is a bug (I fixed the first line of my post to say so) and I also think that Option B would be the correct fix.

**Comment by harrv** [comment] 2021-02-03 23:27
@bakerboy448 Regarding your edit, I agree but I do see one potential argument for the monitored flag affecting user-initiated searches, and that is in the context of error handing. Quite a few times I've wondered if the monitored flag should be consulted after a user-initiated download fails. If they clicked on the magnifying glass, maybe not, but if they selected a specific release in the "Search" tab, and then it fails?

**Closed** 2021-02-05 02:20 UTC
Labels: Area: UI, Status: Confirmed, enhancement

**Comment by bakerboy448** [comment] 2022-07-30 02:19
[New: Allow Manual Search when Movie not monitor](https://github.com/Radarr/Radarr/commit/9b85f328a6c5b5ca8a17b41bab1e68f7a0e8043b)
[https://github.com/Radarr/Radarr/commit/4d70798f2ff070df04b2a29886325cf8aaf58d6d](https://github.com/Radarr/Radarr/commit/4d70798f2ff070df04b2a29886325cf8aaf58d6d)
