### ISSUE TITLE
Request: Ability to define "preferred" words

### ISSUE THREAD

**Issue by vertigo235** [Radarr/Radarr#303] opened 2017-01-17 13:56 UTC
This is a long requested sonarr feature that I feel is more important for movies than it is for TV shows.  This is because there can usually be many many releases for movies, and the ability to prefer certain releases over others is very important. 

Sonarr (and Radarr currently of course) has required words only. 

CP and Watcher support the preferred words.

**Comment by Peap0d** [comment] 2017-01-17 14:22
Duplicate of #227

**Closed** 2017-01-17 14:32 UTC
Labels: enhancement, priority:medium

**Comment by vertigo235** [comment] 2017-01-17 15:37
true, but that one only has a low priority, you triaged mine as medium!  :)
