### ISSUE TITLE
Special characters not properly escaped/removed in `CleanTitle` mode

### ISSUE THREAD

**Issue by ColinHebert** [Radarr/Radarr#7945] opened 2022-12-31 05:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Some characters in movie names are not properly handled/converted when working on file names, when the file/folder uses `CleanTitle`.

```
2022-12-30 10:24:20.5|Info|MoveMovieService|Once Upon a Timeâ€¦ in Hollywood moved successfully to /movies/Once Upon a Timeâ€¦ in Hollywood (2019)
```

The [movie title](https://www.themoviedb.org/movie/466272-once-upon-a-time-in-hollywood) contains an ellipsis (UTF-8 encoded); the logs are not in UTF-8 (for whatever reason), but more importantly, the non ASCII characters were not stripped from the file name wile using a `CleanTitle`

### Expected Behavior

The ellipsis (or special character) needs to either be transformed into an ASCII equivalent (`…` should become `...`) or be stripped entirely.

### Environment

```markdown
- OS: Not relevant
- Radarr: 4.2.4.6635
- Docker Install: Yes
- Using Reverse Proxy: Not relevant
- Browser: Not relevant
- Database: Not relevant
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#4590](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4590)

**Comment by bakerboy448** [comment] 2022-12-31 05:41
- logs are not optional
- You've provided no information on the file name

- The issue seems to be with what you're using to view the logs.  There's no issue with this movie at all.

`Once Upon a Time… in Hollywood (2019) {imdb-tt7131622} [Bluray-1080p Proper][EAC3 7.1][x264]-PTer.mkv`

`/data/media/media/movies/Once Upon a Time… in Hollywood (2019) {imdb-tt7131622}`

> Report a new bug, **if you are not 100% certain this is a bug please go to our Reddit or Discord first**

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.


Also duplicate of / related to https://github.com/Radarr/Radarr/issues/6417

**Closed by bakerboy448** 2022-12-31 05:41 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by ColinHebert** [comment] 2022-12-31 06:02
To clarify, you are saying that the ellipsis (that you also have in your file name), is desirable in the CleanTitle?
