### ISSUE TITLE
Movie titles that contain leading periods/ellipsis do not get renamed properly

### ISSUE THREAD

**Issue by codeclem** [Radarr/Radarr#5526] opened 2020-12-09 22:14 UTC
For example, the movie `...And Justice For All` gets renamed to `.And Justice For All` with a single leading period, which causes it to be a hidden file in Linux.

**Comment by austinwbest** [comment] 2020-12-09 22:20
There is already an open issue & PR for this.

**Comment by codeclem** [comment] 2020-12-09 22:29
Thanks. Do you have a link so I can follow it?

**Comment by bakerboy448** [comment] 2020-12-09 22:42
PR
https://github.com/Radarr/Radarr/pull/4509

Duplicate of #4350

**Closed by bakerboy448** 2020-12-09 22:42 UTC
Labels: bug
