### ISSUE TITLE
RAM Usage

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#2083] opened 2017-09-15 14:00 UTC
I am using the newest version of Radarr on the newest mono on Ubuntu.

Radarr is using around 500 MB of RAM although, it fluctuates sometimes but it is generally at around 500, is there anything that can be done to lower this.

Also, is it possible there’s a memory leak because, this amount of RAM usage, at a constant rate seems very high to me.
Thanks

**Comment by hotio** [comment] 2017-09-15 15:24
Don't worry, it's 700MB on my system with 16GB total memory, on my previous system with only 4GB it was using only around 300MB. It will be free'ed up when the system needs it. You've got ram, to use it, not to let it sit there unused.

**Comment by hotio** [comment] 2017-09-16 06:41
It usually shoots straight up when doing a refresh of movies

**Comment by zero77** [comment] 2017-09-16 14:12
@hotio 
That would be ok but it seems high all the time, not just when its carrying out more resource hungry tasks.

**Comment by hotio** [comment] 2017-09-16 15:21
Yeah it doesn't release it straight away, but I've seen it come down...
![mem](https://user-images.githubusercontent.com/26902309/30513441-6f313a84-9b03-11e7-9d4a-05d961bde660.png)

**Comment by bassebaba** [comment] 2017-09-17 11:01
Duplicate of #1580

**Comment by Panderine** [comment] 2017-11-18 00:16
@hotio, sorry for the off-topic, what do you use to get that kind of monitoring graphs?

**Closed** 2017-11-18 09:45 UTC

**Comment by hotio** [comment] 2017-11-18 14:43
@Panderine https://github.com/firehol/netdata
