### ISSUE TITLE
REQ: "Change File Date", add option for first import date

### ISSUE THREAD

**Issue by dRuEFFECT** [Radarr/Radarr#8118] opened 2023-02-13 08:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It's a workaround solution to an Emby-specific problem. Emby sees upgraded files with a different filename as "new" and sorts upgraded files along with new releases in the Latest Movies sections.

### Describe the solution you'd like

Add another option here for overriding with the date/timestamp of the first ever import or grab according to Radarr.
![image](https://user-images.githubusercontent.com/7904175/218408521-570381d2-e3ba-49a6-839d-0a9e04377148.png)

### Describe alternatives you've considered

 I can override the file date with release/premiere date as you have it and let emby use the file date as date added, but then when older movies are added for the first time, they'd be sorted all the way back to when they were first released and those do not appear in their Latest Movies section.
Emby devs give quite a bit of pushback when they dont personally agree with the need and they just recommend having Radarr output a standard filename, which would be the same "file" on a rescan after an upgrade is imported, however I like to retain the quality and release group info on my media files so I know where they came from.

### Anything else?

you can see the discussion here:
https://emby.media/community/index.php?/topic/94661-is-there-a-way-to-make-recently-added-functionally-accurate/page/2/

**Comment by bakerboy448** [comment] 2023-02-13 12:45
Duplicate of https://github.com/Radarr/Radarr/issues/4913

**Closed by bakerboy448** 2023-02-13 12:45 UTC
Labels: Type: Feature Request, Status: Needs Triage
