### ISSUE TITLE
Add filter options on collection page

### ISSUE THREAD

**Issue by sarakha63** [Radarr/Radarr#7888] opened 2022-12-14 13:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In fact on the collections page we can create custom filters. 

i created an unmonitored filter  to easily spot  unmonitored collections

i would like to create (and i think it will be usefull) a custom filter to show collections which have  unmonitored movies in it. or show collections which have a missing movie

No options on the custom filter can permit this

### Describe the solution you'd like

The solution i'd like would be to have in the custom filter droplist

Containing Missing Movies

Containing Unmonitored Movies

### Describe alternatives you've considered

I didnt really find any alternative

### Anything else?

Nothing else to add

[AB#4453](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4453)

**Comment by bakerboy448** [comment] 2022-12-14 13:57
Duplicate of #7338

**Closed by bakerboy448** 2022-12-14 13:57 UTC
Labels: Type: Feature Request, Status: Needs Triage
