### ISSUE TITLE
Value cannot be null, parameter: source

### ISSUE THREAD

**Issue by dolohow** [Radarr/Radarr#6392] opened 2021-06-13 11:44 UTC
Happens almost every time, when radarr is doing some work.

I noticed this errors occurs frequently in logs

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.904
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET 5.05
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: master

```
2021-06-12 23:39:08.5|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue/details

[v3.2.2.5080] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.ToResource(IEnumerable`1 models) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 34
   at Radarr.Api.V3.Queue.QueueResourceMapper.ToResource(Queue model, Boolean includeMovie) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueResource.cs:line 48
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


2021-06-12 23:39:10.1|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue/details
```

[AB#103](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/103)

**Comment by bakerboy448** [comment] 2021-06-13 13:17
Need more than just the error line... and more context

**Comment by dolohow** [comment] 2021-06-13 13:24
Should I enable some settings to log more?

**Comment by protogen** [comment] 2021-06-22 08:39
**Describe the bug**
I am seeing the same error.
It only started occurring once I updated to v3.2.2.5080 (which I did on Jun 13th).
For me, the error only occurs when I delete a movie (it does not occur at any other time).

**To Reproduce**
1. Go to 'Movies'
2. Click on 'Edit Movie' (spanner)
3. Click on 'Delete'
4. The value of 'Delete Movie Folder' does not matter (error occurs with both checked and unchecked)
5. Click on 'Delete'

**Platform Information (please complete the following information):**
 - OS: Oracle Linux 8.3
 - Docker: No
 - Mono or .NET Version (System -> Status): .NET 5.0.5
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: master

**Trace Logs**

Occurrence 1
```
2021-06-17 22:48:55.1|Info|MovieService|Deleted movie [Dream Horse (2021)][tt9883996, 603206]
2021-06-17 22:48:55.1|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue/details

[v3.2.2.5080] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.ToResource(IEnumerable`1 models) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 34
   at Radarr.Api.V3.Queue.QueueResourceMapper.ToResource(Queue model, Boolean includeMovie) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueResource.cs:line 48
   at Radarr.Api.V3.Queue.QueueResourceMapper.<>c__DisplayClass1_0.<ToResource>b__0(Queue m) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueResource.cs:line 76
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Radarr.Api.V3.Queue.QueueResourceMapper.ToResource(IEnumerable`1 models, Boolean includeMovie) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueResource.cs:line 76
   at Radarr.Api.V3.Queue.QueueDetailsModule.GetQueue() in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueDetailsModule.cs:line 41
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```
Occurrence 2
```
2021-06-22 17:39:50.5|Info|MovieService|Deleted movie [Cosmic Sin (2021)][tt11762434, 681887]
2021-06-22 17:39:50.5|Info|RecycleBinProvider|Attempting to send '/path/to/my/movies/Cosmic Sin (2021)' to recycling bin
2021-06-22 17:39:50.5|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /path/to/my/movies/Cosmic Sin (2021)
2021-06-22 17:39:50.5|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue/details

[v3.2.2.5080] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.ToResource(IEnumerable`1 models) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 34
   at Radarr.Api.V3.Queue.QueueResourceMapper.ToResource(Queue model, Boolean includeMovie) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueResource.cs:line 48
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```
Occurrence 3
```
2021-06-22 17:48:19.2|Info|MovieService|Deleted movie [Chaos Walking (2021)][tt2076822, 412656]
2021-06-22 17:48:19.2|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue/details

[v3.2.2.5080] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.ToResource(IEnumerable`1 models) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 34
   at Radarr.Api.V3.Queue.QueueResourceMapper.ToResource(Queue model, Boolean includeMovie) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueResource.cs:line 48
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

**Comment by protogen** [comment] 2021-06-23 08:47
**Further Info**
I've noticed another strange thing that occurs at the same time as this error.

About 2 or 3 seconds after deleting a movie (and seeing this error appear in the logs) my Activity Queue (which was empty) suddenly contains a number of phantom jobs.  The total number of jobs is equal to the number of movies that currently exist in my Root Folder (i.e. movies that have already been downloaded) and the details of each job matches the details of the already downloaded movies.

The phantom jobs remain in the Activity Queue for about 2 minutes, until the RSS Sync task runs and completes, and then all the phantom jobs immediately disappear.

I noticed this happening yesterday when I deleted 2 movies (see Occurrence 2 + 3 above) however I didn't connect it with this error until I saw it happen again today when I deleted another movie.  This time I took screenshots.

**Trace Logs**
```
2021-06-23 17:47:19.6|Info|MovieService|Deleted movie [Raya and the Last Dragon (2021)][tt5109280, 527774]
2021-06-23 17:47:19.6|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/queue/details

[v3.2.2.5080] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Radarr.Api.V3.CustomFormats.CustomFormatResourceMapper.ToResource(IEnumerable`1 models) in D:\a\1\s\src\Radarr.Api.V3\CustomFormats\CustomFormatResource.cs:line 34
   at Radarr.Api.V3.Queue.QueueResourceMapper.ToResource(Queue model, Boolean includeMovie) in D:\a\1\s\src\Radarr.Api.V3\Queue\QueueResource.cs:line 48
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 153
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


2021-06-23 17:48:46.5|Info|RssSyncService|Starting RSS Sync
2021-06-23 17:48:49.7|Info|DownloadDecisionMaker|Processing 260 releases
2021-06-23 17:48:51.7|Info|RssSyncService|RSS Sync Completed. Reports found: 260, Reports grabbed: 0
```

**Screenshot taken at 2021-06-23 17:47:27 (after error, before RSS Sync)**
![001](https://user-images.githubusercontent.com/3028907/123065480-87760e80-d452-11eb-8994-c205c8b95544.png)

**Screenshot taken at 2021-06-23 17:49:12 (after RSS Sync)**
![002](https://user-images.githubusercontent.com/3028907/123065513-8f35b300-d452-11eb-8dc4-cca37105ab9d.png)

PS - I customise the colours of my Radarr install, that's why it looks different.

**Comment by bakerboy448** [comment] 2021-06-23 12:38
trace logs have still not been provided....

https://wiki.servarr.com/radarr/troubleshooting#logging-and-log-files

**Comment by protogen** [comment] 2021-06-24 18:44
Sorry.  I had thought since I'd shown this issue was reproducible that that would be enough.  Are you saying the error is not occurring when _you_ delete a movie?

Either way, I'll collect trace logs the next time I delete a movie.

**Comment by bakerboy448** [comment] 2021-06-24 18:46
correct; deleting a movie works fine... based on the error it's likely related to something in queue....but since you didn;t properly fill out the template, cant' say

**Comment by protogen** [comment] 2021-06-27 01:56
Trace logs link below.  FYI - I have de-identified some info in the trace logs (hostnames, domain, IPs, paths).

1. I deleted the movie "Six Minutes To Midnight (2020)" at exactly 10:37:00.
2. The delete was successful (movie deleted from Radarr and from file system).
3. As expected, the delete produced the error "Value cannot be null. (Parameter 'source')" at 10:37:00.7.
4. At approx 10:37:02 seven (7) phantom jobs appeared in my Activity Queue (see my post above).
5. At approx 10:37:38 the 7 phantom jobs disappeared.

https://hastebin.com/ziquyebemo.rb

**Comment by protogen** [comment] 2021-06-27 21:11
Further update.  The error is no longer occurring for me.  I deleted 3 movies this morning.  All 3 deleted perfectly without an error.

If the error returns I will report it again here.

**Comment by protogen** [comment] 2021-06-27 23:54
This issue should not be closed.  It is not resolved.  The problem still exists in the code and will resurface at some point.

**Comment by protogen** [comment] 2021-07-01 18:05
The error has returned.  I just deleted "A Quiet Place (2018)" and saw the error in my logs.

I will enable trace logs before I perform the next movie delete.  Hopefully I'll capture it again.

**Comment by protogen** [comment] 2021-07-01 18:29
Just deleted another 3 movies.  The error occurred on 1 and did not occur for the other 2.

I managed to capture trace logs for these 3 deletes.  I'll post it as soon as I've de-identified the data.

**Comment by protogen** [comment] 2021-07-01 18:54
Trace logs link below. I have de-identified some info in the trace logs (hostnames, domain, IPs, paths).

1. I deleted "A Quiet Place (2018)" at 04:00:00 (the error occurred but trace logs were disabled - see above)
2. I enabled trace logs at 04:02:56
3. I deleted "Wise Blood (1979)" at 04:06:03 (the error did not occur)
4. I deleted "A Quiet Place Part II (2021)" at 04:09:03 (the error occurred)
5. I deleted "The World to Come (2020)" at 04:24:29 (the error did not occur)

Looking at the trace logs there is a definite difference between how 4 was handled compared to 3 and 5.

https://hastebin.com/fusobopaca.rb

**Comment by protogen** [comment] 2021-07-12 23:33
This issue is still occurring for me when I delete movies.  The trace logs are identical (apart from the movie name) to those I've already posted above.

**Comment by midN** [comment] 2021-11-10 11:02
Same issue, but on import.
Fails on importing movies after they've been download by qbittorrent or manually trying to import afterwards
```radarr-55f856bbf-ls6jv radarr [v3.2.2.5080] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
radarr-55f856bbf-ls6jv radarr    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
radarr-55f856bbf-ls6jv radarr    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
radarr-55f856bbf-ls6jv radarr    at Radarr.Api.V3.ManualImport.ManualImportModule.ReprocessItems() in D:\a\1\s\src\Radarr.Api.V3\ManualImport\ManualImportModule.cs:line 41
radarr-55f856bbf-ls6jv radarr    at Radarr.Api.V3.ManualImport.ManualImportModule.<.ctor>b__1_0(Object x) in D:\a\1\s\src\Radarr.Api.V3\ManualImport\ManualImportModule.cs:line 22
radarr-55f856bbf-ls6jv radarr    at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
radarr-55f856bbf-ls6jv radarr    at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
radarr-55f856bbf-ls6jv radarr    at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
radarr-55f856bbf-ls6jv radarr    at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
radarr-55f856bbf-ls6jv radarr    at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
radarr-55f856bbf-ls6jv radarr    at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

**Comment by protogen** [comment] 2021-11-11 00:00
Just confirming this issue is also still occurring for me when I delete movies.  The trace logs are identical (apart from the movie name) to those I've already posted above.

**Comment by aaitken1111** [comment] 2021-11-25 18:48
This is happening for me too.  It's seems like the queue thinks that there's still something there when there isn't.  could it be database corruption of some kind when deleting a movie?

**Comment by dawnerd** [comment] 2022-01-27 22:18
I'm getting this when trying to manually import a UHD I ripped.

Version: 3.2.2.5080-ls129 by linuxserver.io

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Radarr.Api.V3.ManualImport.ManualImportModule.ReprocessItems() in D:\a\1\s\src\Radarr.Api.V3\ManualImport\ManualImportModule.cs:line 41
   at Radarr.Api.V3.ManualImport.ManualImportModule.<.ctor>b__1_0(Object x) in D:\a\1\s\src\Radarr.Api.V3\ManualImport\ManualImportModule.cs:line 22
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

**Comment by bakerboy448** [comment] 2022-01-27 23:03
As previously stated - not a single user with this issue has ever provided trace logs for it. 
Info logs are not valid for bug reports
Just the error spew that has been posted by several users is not valid for bug reports either nor any debugging / support FYI

https://wiki.servarr.com/radarr/troubleshooting

-----

Also since v3.2.2 is no longer getting any updates;  has anyone reproduced this on v4 (develop or nightly)?

**Comment by protogen** [comment] 2022-01-28 03:40
I have previously provided trace logs twice showing the error occurring multiple times.  Strangely, this error doesn't seem to show much more than the error spew even in trace logs.  Honestly, I don't know what more we can provide.

**Comment by bakerboy448** [comment] 2022-01-28 03:42
> I have previously provided trace logs twice showing the error occurring multiple times.  Strangely, this error doesn't seem to show much more than the error spew even in trace logs.  Honestly, I don't know what more we can provide.

Looks like they all expired 


Also not sure if you caught the edit, but would be nice to know if this is still seen on v4

**Comment by protogen** [comment] 2022-01-28 03:56
> Also not sure if you caught the edit, but would be nice to know if this is still seen on v4

I'm using the latest release (v3.2.2.5080).  I'm not comfortable switching to a pre-release version.

**Comment by protogen** [comment] 2022-02-08 17:39
Today I updated Radarr to the latest release (v4.0.4.5922).  Over the coming weeks I will monitor to see if the error occurs and report back.

**Comment by protogen** [comment] 2022-02-23 00:09
I have been using the latest release (v4.0.4.5922) for 2 weeks now.  During that time the error has not occurred.  Previously, deleting a movie was the trigger for the error.  In the past 2 weeks I have deleted 11 movies.

I am satisfied that the error is gone/resolved for me.  However, before this issue is marked as closed/resolved, I would like at least one other person who has experienced this error (or perhaps the OP?) to also confirm that it is gone.

**Comment by protogen** [comment] 2022-03-05 21:17
It doesn't look like anyone else is going to provide additional confirmation.  I'm comfortable for this issue to be closed.

The error has still not occurred for me.  I have deleted a further 3 movies. 🙂

**Closed** 2022-03-06 08:01 UTC
Labels: Type: Bug, Status: Info Needed
