### ISSUE TITLE
Error 404 when opening movie

### ISSUE THREAD

**Issue by welle** [Radarr/Radarr#1196] opened 2017-03-16 14:42 UTC
Hi,

I am currently importing all my movies from trakt.tv.
I have few movies I can't manage: when I want to open the details of some movie, the page load, then a few secondes later an 404 error appear.

the movie "38 témoins" lead to a page url  `http://localhost:7878/movies/38-tmoins-95191` 
the movie "Akira" lead to a page url `http://localhost:7878/movies/akira-149`

both give me 
![image](https://cloud.githubusercontent.com/assets/642016/24001665/09ea3d0e-0a5f-11e7-9f8d-3bed58cf056a.png)

In the beginning I tought that it was related  with "special" characters (éèàù, etc) but even if "Akira" is related to `アキラ (1988)` subfolder I get `http://localhost:7878/movies/akira-149` for the url.

Radarr Ver. 0.2.0.535
no related logs founds

**Comment by galli-leo** [comment] 2017-03-16 15:32
Both work fine for me. Can you try restarting radarr and clearing the cache of your browser?

**Comment by SJ50** [comment] 2017-03-18 05:53
I have seen this error many times, I think this happens when movie in question is refreshing. 
This goes away when I wait sometime and refresh the page.
I have never tried to reproduce this bug.

**Comment by welle** [comment] 2017-03-18 08:29
Done cleaning the cache but error still appear

I manage to reproduce this bug:
Go to "Movies", then "Movies editor"
Click on the link "38 témoins" (for instance).
Then on the details page of this movie, click on the little wrench to edit it.
Trying to change the directory folder where the movie is.
The page still to refresh in the background and the error 404 appear while I'm walking trough directories to find the correct directory.

Anyway I can edit the movie directory from the page "Movies".

**Comment by calebpaine** [comment] 2017-03-18 19:30
I'm having similar issues as well. I can't find any kind of pattern for it, but I *think* it's only happening on movies added by a Trakt list, not ones I added manually or imported, if it makes any difference. Additionally, sometimes I can see the page, with background image and text for a fraction of a second before the 404 image replaces it.

Shift-Refreshing the page in chrome almost always resolves it for a while. Something with the AJAX maybe?

**Comment by klusion** [comment] 2017-03-19 16:54
I can confirm this as well. If I select any movie in my wanted list to review the details, I receive a 404 error. Sometimes the movie detail page loads for a second followed by the 404 error. It does not matter whether the movie was added from a list or manually added.

**Comment by weirdcrap** [comment] 2017-03-20 13:25
@klusion I had this issue and did what galli-leo said and all my movies that were 404'd are now working again.

**Comment by wolffstarr** [comment] 2017-03-25 00:21
Also confirming this; far too intermittent for me to have been able to track down yet.

I can confirm that it is NOT only happening with trakt lists, since I'm not using any lists and don't have a trakt account.

**Comment by leeramsay** [comment] 2017-04-16 03:04
I can confirm I've seen this with movies where minimum availability is set to PreDB. I think there's another bug/issue open for that. #1322

**Comment by galli-leo** [comment] 2017-04-16 07:35
@leeramsay That seems very strange. Can you change it back to PreDB and see if the 404s pop up again?

**Comment by calebpaine** [comment] 2017-04-29 17:13
Setting a movie that is doing this to Physical/Web stops the behavior. Returning the movie to PreDB does not cause the 404 behavior to return.

**Comment by raspdealer** [comment] 2017-04-29 17:26
Same here

**Comment by Baldrdk** [comment] 2017-04-30 16:42
I have the same problem. All links in the wanted section jumps directly to the 404 page.
The strange thing is, when i refresh the movie page showing the 404, it will show the correct movie page for about 3 seconds before jumping back to the 404 page?

**Comment by Webreaper** [comment] 2017-05-04 13:44
I had this too - I was doing a mass-import of 300+ movies after first installing Radarr, and (probably stupidly ;)) went into the profiles screen and deleted 'Any' from the list. I think what happened was that all of the movies were imported with 'Any' as the profile, but because that'd been deleted, it failed. 
I did a mass-update and set the profile correctly for all movies, and they all started working again - no 404s. So I suspect what's happening is that some internal DB join is failing, causing the 404, when it should just default to 'unknown'.

**Comment by galli-leo** [comment] 2017-05-04 17:27
@Webreaper That could be it, though I suspect it's more because the full collection of movies is failing to load
@Baldrdk @raspdealer @leeramsay The next time this happens can you open the dev console in your browser and see if there are any errors?

**Comment by GenericPolarBear** [comment] 2017-05-09 08:22
I am also having this issue and have recorded me trying to look at the movie page for Logan.
A weird part is that I'm unable to search for the movie within my library in Radarr, but when I try to add it manually, it says it's already added.

I am pretty sure this movie was added through Ombi, otherwise it would have been added automatically using the StevenLu list. This does happen with other movies added through the StevenLu list.

Here's the video: [https://www.youtube.com/watch?v=fHyWU4NjSwU&feature=youtu.be](url)

**Comment by galli-leo** [comment] 2017-05-09 18:55
@GenericPolarBear Are you on the latest nightly? If not, can you please go ahead and update?

**Comment by GenericPolarBear** [comment] 2017-05-09 23:55
@galli-leo I am on the latest nightly. And it is still an issue. (v 0.2.0.691)

It actually seems to be with most requested movies, if needed I can do more tests.

**Comment by galli-leo** [comment] 2017-05-10 08:37
@GenericPolarBear Can you also open the dev console of your browser and see if any errors appear there?

**Comment by GenericPolarBear** [comment] 2017-05-12 13:51
@galli-leo I have figured out how to reproduce the issue. Request a movie through Ombi, then it won't show up at all in Radarr unless the URL is manually typed, which is pretty easy to figure out because they all follow the same pattern.

New Video: https://www.youtube.com/watch?v=G1AZOc57qI0
After a few seconds it will show 404, no errors in the console as shown in the video.
As you can see in the video as well, the version number is 0.2.0.694

It also seems that any newly added movie that isn't added through the inbuild add function, automatically has no minimum availability, which means it downloads a lot of fakes.

**Comment by galli-leo** [comment] 2017-05-12 14:56
@GenericPolarBear Oh wow. That is really strange.
Regarding the second point. It's the responsibility of the program you use to add movies to send us the correct Minimum Availability settings.

**Comment by GenericPolarBear** [comment] 2017-05-13 03:19
@galli-leo Wouldn't it be possible to set a default minimum if those programs don't specify a minimum themselves? I think this also happens with the StevenLu list, although I'm not entirely sure on that one.

**Comment by galli-leo** [comment] 2017-05-13 11:06
@GenericPolarBear For the list you can set it yourself when you edit the list. We could make an option for the default, but IIRC ombi should be patched pretty soon.

**Comment by nibble4bits** [comment] 2017-05-15 21:31
I get this 404 Error only in Chrome. When I view the same movies using Opera, I am experiencing a page reload a few seconds after the initial page appears to load.  I'll go to the movie, start looking at the results of a search, and Radarr flashes like a page reload and goes back to the History tab. But only once. If I do a 2nd search, I don't experience this page reload.

**Comment by MikeBlom** [comment] 2017-05-19 17:35
I had this issue in Chrome. Resetting the cookies fixed this.

**Comment by GenericPolarBear** [comment] 2017-05-20 03:06
What @MikeBlom did also worked for me.

**Comment by lankanmon** [comment] 2017-05-26 15:12
Can confirm that clearing all cache and history does fix the issue... Any idea of the cause?

**Comment by leepa** [comment] 2017-06-11 10:17
Also confirm - in incognito mode everything works.

**Comment by elamperti** [comment] 2017-06-11 21:03
Same problem here, fixed it by browsing to `127.0.0.1` instead of my custom hostname. Strange bug.

**Comment by galli-leo** [comment] 2017-06-12 11:18
@elamperti Probably also cache, because to your browser 127.0.0.1 is a different website, so no cache is used.

**Comment by rcmpayne** [comment] 2017-07-07 20:35
same issue here, Radarr Ver. 0.2.0.778 on develop. Go to Wanted Tab and select Missing, now select any movie and you get a OMG 404 error. i reproduced the issue with trace logging but dont see anything for the below examples

Example:
`http://192.168.0.100:8084/movies/kingdom-of-heaven-1495`

Logs:
[radarr.trace (1).txt](https://github.com/Radarr/Radarr/files/1132240/radarr.trace.1.txt)
[radarr.debug (1).txt](https://github.com/Radarr/Radarr/files/1132241/radarr.debug.1.txt)

**Comment by lzinga** [comment] 2017-07-08 22:43
Chiming in that im getting this issue too. Though on the 404 page if I do a refresh it properly loads the movie.

**Comment by dweidenfeld** [comment] 2017-08-05 19:05
Same issue here. Check the cache invalidation date.

**Comment by GavinHellyer** [comment] 2017-08-21 15:28
This is happening on the latest nightly build.

I've cleared cache, opened incognito on Chrome and opened Radarr, once the list of movies loads I can click on one and it opens fine, then when I press back (on the browser) OR click on the Movies icon to get back to the list, any movie there after shows a 404. As @lzinga said, refreshing the browser will load the movie.

**Comment by rocqua** [comment] 2017-09-09 21:37
I have had this issue after a while, it persists after a reboot. Diving into chrome's developer mode and setting some breakpoints leads me to line 933 of templates.js. This seems to be the response to a helper function that is missing.

This issue did not occur in incognito mode. It was cleared uppon clearing all browser data in chrome.

**Comment by galli-leo** [comment] 2017-09-10 10:35
@rocqua I am thinking chrome is not respecting our caching headers and is still caching stuff.

**Comment by rocqua** [comment] 2017-09-10 10:50
@galli-leo I was surprised clearing cache worked, because the issue persisted even when loading the page with "disable caching" turned on in the developer tools. I cleared my cookies at the same time, maybe that is what helped.

**Comment by galli-leo** [comment] 2017-10-15 11:28
This is fixed on the latest develop release.

**Closed by galli-leo** 2017-10-15 11:28 UTC
Labels: bug, priority:medium
