### ISSUE TITLE
Movie deleted before successful import confirmed

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#4209] opened 2020-03-03 01:14 UTC
**Describe the bug**
I was tired of waiting for an update in Activity view to appear, so I began watching the movie, thinking I could import it manually.
However, I went out for a smoke and when I got back I was curious about its status, so I noticed Windows delete function had a file lock issue, so I closed down my video player, and when I looked at Radarr, or rather the page for the movie it said "Downloaded", you know, green label, like when movies exists.

I then started Kodi (Used MPC earlier) I noticed it hadn't been listed as recently added, so I went to the media-thing to import it manually.
It said the directory was not containing anything.

A quick look in the actual directory showed no files.
I did a check in my download directories, and nada, Zip, Zilch!
It was gone.

So, it seem that something was lost during the import in the communication between µTorrent and Radarr.

This is not the first time that Radarr have removed files for me.
Mostly it has, don't know if that was fixed since it hasn't happened in a while now, imported sample files instead of the actual movies and that seem like a weird thing to do. It should at least check the file sizes and alarm the user if the files are too small.

Anyways, it's annoying having to re-download a movie just because Radarr can't confirm imports as completed before deleting something.

I'd consider this a bug.

**Comment by ta264** [comment] 2020-03-03 06:15
Closing until the details in the issue template are provided

**Closed by ta264** 2020-03-03 06:15 UTC
Labels: bug

**Comment by fryfrog** [comment] 2020-03-04 17:04
This is not a bug, you've got something setup wrong. But you included literally no useful information, so anything will just be a guess. If you're using torrents, you've probably got your torrent client setup to *remove* torrents when they're finished seeding. Otherwise, it is something else. Either way, hop on Discord and work w/ someone to figure out what you've borked in your setup.

**Comment by 4C3T** [comment] 2020-03-04 17:39
How is that not a bug if it's processing the downloaded data, initiates a file import, which got cast into oblivion, thus not successfully copied, then listed as downloaded?

First when I clicked on the update movie info and scan disk, it discovered that it was in fact missing!
A few minutes later it listed it as deleted in the history tab, but it wasn't in the directory that I'm using in case something like this would happen, apart from the actual ghosting of files that is.

I love the fact that Radarr does stuff automagically, like upgrading movies, auto-import it, but the lag between a finished download and the realization that it's in fact finished drives me nuts, and most of the time the System/Tasks->Check For Finished Download mostly does nothing, except animating that recycle-icon.
Something that would be nice to see in Radarr would be a log-type function, like a little text field which showed what's being done, in real time, not heavy logs with hundreds of lines of text or so, but just info like what it's currently doing. Brief info. I think many would really like this.

Ok, that turned into a feature request, sorry for that. But, it'd be nice to see what it's doing.
Heck, even a CLI-addon of sorts would be nice just to see what it's currently doing

Anyway, I still feel it's weird that it didn't copy the file since it requested a file deletion due to the opened file-lock.

As for Discord - I don't use it.

And as for µTorrent that I use, only downloads to a specific directory, and upon completion it moves the downloads to another on the same drive.

**Comment by fryfrog** [comment] 2020-03-04 17:47
It isn't a bug because you haven't shown it is a bug. Issues like this are *almost always* user error. You haven't shown us logs, you haven't even told us what version you're using. How would anyone even find or fix the bug if it was?

Pretend this is all about Radarr and not Sonarr, but start w/ the asking for help wiki. Then move on to the downloads troubleshooting wiki.

https://github.com/Sonarr/Sonarr/wiki/Asking-for-Help

https://github.com/Sonarr/Sonarr/wiki/Downloads-and-Importing

If you can't find and fix the issue yourself, you'll end up w/ useful logs. Then either start using Discord or make a support post on reddit w/ useful details.

Good luck.
