### ISSUE TITLE
Folder Structure support

### ISSUE THREAD

**Issue by Grimshad** [Radarr/Radarr#2260] opened 2017-11-10 16:10 UTC
**Description:**
Support for different folder structures.

My current structure is Movies\year\Movie Name (year)\Movie Name (year).ext

My movies are sorted by year, I need a way to add a single folder. instead of each year individually.

**Comment by galli-leo** [comment] 2017-11-10 16:22
Duplicate of #153

**Closed by galli-leo** 2017-11-10 16:22 UTC
