### ISSUE TITLE
Adding an rtsp link to the movies in order to be able to read it with vlc straight from radarr

### ISSUE THREAD

**Issue by sched75** [Radarr/Radarr#7942] opened 2022-12-30 12:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

this not a bug just a feature request

### Describe the solution you'd like

Could be nice to have an icon near the path that will link to the file via rtsp uri.

### Describe alternatives you've considered

for the moment I use kodi but it would be much lighter to use a simple uri on rtsp protocol.

### Anything else?

this feature would be a quick and easy enhancement

[AB#4582](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4582)

**Comment by bakerboy448** [comment] 2022-12-30 15:40
Duplicate of https://github.com/Radarr/Radarr/issues/5757

**Closed by bakerboy448** 2022-12-30 15:40 UTC
Labels: Type: Feature Request, Status: Won't Fix
