### ISSUE TITLE
Import subfolders along with movie

### ISSUE THREAD

**Issue by akavi1** [Radarr/Radarr#8934] opened 2023-08-04 01:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It is not possible to import subfolders along with the movie file. You can import specific file extensions that are in the same folder as the movie, but you cannot import the subfolders even if they are in the same folder as the movie file

### Describe the solution you'd like

Rename the movie file, then move both the movie file and any other subfolders (Featurettes, Subs, Extra, etc) that came with the movie.

### Describe alternatives you've considered

I have been manually checking if there are subfolders before importing. Unfortunately, this defeats the purpose of automation

### Anything else?

There was a similar post #7092 but even then, it does not discuss moving the whole folder

**Comment by bakerboy448** [comment] 2023-08-04 01:32
- featurettes and multiple video files are not supported
- Duplicate of https://github.com/Radarr/Radarr/issues/6714
- related to  https://github.com/Radarr/Radarr/issues/4637


- What specific items are in subfolders that should be imported, subs are already handled?
- no plans to support importing featurettes or any other video files besides the movie itself
- How are these releases structured?
- What extras - besides subs which is covered by existing issues - are wanted to be imported and are frequently and often in subfolders?

**Comment by akavi1** [comment] 2023-08-04 02:31
> What specific items are in subfolders that should be imported, subs are already handled?

.mkv files aren't importing. I have .mkv listed in the "Import Extra Files" section

> How are these releases structured?

Main folder
--> movie file .mkv
--> --> Featureettes folder
--> -->- -> various .mkv fiiles
--> -->- -> Deleted Scenes folder
--> -->- -> --> more .mkv files

>featurettes and multiple video files are not supported

Is there a way to prevent Radarr from deleting these files? Right now, Radarr will move the main movie (plus subtitles) and delete any leftover folders and extra video files. If it just left the other .mkv files alone, I could move them manually

>no plans to support importing featurettes or any other video files besides the movie itself

A lot of people use Radarr with Plex. There's a section in Plex for extras, if downloaded. I think it would be nice if Radarr could keep those files. It doesn't have to rename them, just move them to wherever the movie is going so everything is in one folder

**Comment by bakerboy448** [comment] 2023-08-04 02:32
Radarr does not delete any files left behind for the import. It tells your download client to remove the download and then your download client handles clean up.

disable remove completed downloads or use a custom script for import, but again multiple video files in a radarr movie folder are not supported and will cause weird unexpected behavior

no plans for non-movie multiple video file support

**Closed by bakerboy448** 2023-08-04 02:32 UTC
Labels: Status: Info Needed, Type: Feature Request, Status: Waiting for OP, Status: Needs Triage
