### ISSUE TITLE
Custom default sort order in search tab

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#7736] opened 2022-11-07 14:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/8129583/200330446-9d2d85c9-736a-4b13-b34e-47ec455ea9eb.png)

When you start a search for a movie, the results are displayed in some arbitrary order. I'd like be able to choose a default sort column (e.g. peers or age would be very useful)

### Describe alternatives you've considered

I have to click the sort column manually literally EVERY TIME I do a search.

### Anything else?

Not really

[AB#4039](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4039)

**Comment by austinwbest** [comment] 2022-11-07 16:40
Duplicate of #4935 with a PR already in progress

**Closed** 2022-11-23 00:33 UTC
Labels: Type: Feature Request, Status: Needs Triage
