### ISSUE TITLE
Not picking up second cd file

### ISSUE THREAD

**Issue by Digitalcheffe** [Radarr/Radarr#1180] opened 2017-03-15 03:51 UTC
**Description:**
When acquiring movies that contain multiple files Resulting in cd1 / cd2. Only 1 file get's picked up,  Does not appear to be a rhyme or reason on which one gets picked up. I can only assume its based on file name sorted descending.  Can provide more details if needed. Did not see any previous posts on issue. Listed anywhere. 

File name: Sleepy.Hollow.1999.iNTERNAL.AC3.DVDRiP.XViD-aGGr0

**Radarr Version:**
Windows Server 2012 R2 , Running as Service , Modified folder permissions / service to run special account. Storage is Synology NAS with Share permissions for account.
Branch Develop
Version0.2.0.535
AppData directoryC:\ProgramData\Radarr 
Startup directoryD:\Radarr 

**Logs:**
17-3-14 14:46:48.0|Info|MovieService|Adding Movie [][Sleepy Hollow] Path: [\\iteganas01\ITegasusData\MOVIES\Sleepy Hollow (1999)]
17-3-14 14:46:48.0|Info|MediaCoverService|Downloading Poster for [][Sleepy Hollow] http://image.tmdb.org/t/p/original/yaX0WQstEi2akQXffoJUxyOsZkj.jpg
17-3-14 14:46:48.0|Info|RefreshMovieService|Updating Info for Sleepy Hollow
17-3-14 14:46:48.9|Info|DiskScanService|Scanning disk for Sleepy Hollow
17-3-14 14:46:48.9|Info|MovieScannedHandler|[Sleepy Hollow] was recently added, performing post-add actions
17-3-14 14:46:48.9|Info|NzbSearchService|Searching 0 indexers for [Sleepy Hollow]
17-3-14 14:46:48.9|Info|DownloadDecisionMaker|No results found
17-3-14 14:46:48.9|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-3-14 14:46:49.1|Info|MediaCoverService|Downloading Banner for [tt0162661][Sleepy Hollow] http://image.tmdb.org/t/p/original/d7yZz1SmFNLSbZGilW2wAd9gcBd.jpg
17-3-14 21:54:08.7|Info|NzbSearchService|Searching 1 indexers for [Sleepy Hollow]
17-3-14 21:54:19.5|Info|Nzbget|Adding report [Sleepy.Hollow.1999.iNTERNAL.AC3.DVDRiP.XViD-aGGr0] to the queue.
17-3-14 21:54:19.9|Info|DownloadService|Report sent to NZBGET. Sleepy.Hollow.1999.iNTERNAL.AC3.DVDRiP.XViD-aGGr0
17-3-14 22:06:54.3|Info|MovieService|Linking [Sleepy Hollow (1999).avi] > [[tt0162661][Sleepy Hollow]]
17-3-14 22:06:54.3|Info|MovieService|Linking [Sleepy Hollow (1999).avi] > [[tt0162661][Sleepy Hollow]]
17-3-14 22:06:55.1|Warn|DownloadedMovieImportService|Unable to parse file on import: [D:\Temp\Completed\Radarr\Sleepy.Hollow.1999.iNTERNAL.AC3.DVDRiP.XViD-aGGr0\aggro-sleepy-cd1.avi]

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by Fredrik81** [comment] 2017-04-21 19:27
I had same issue with "Silent.Hill.2006.iNTERNAL.DVDRip.XviD-iGNiTiON" i manually copied the file in.
Hope radarr will support this in the future as older movies/releases have this.

**Comment by galli-leo** [comment] 2017-06-14 10:05
Duplicate of #145

**Closed by galli-leo** 2017-06-14 10:05 UTC
