### ISSUE TITLE
Movie Library without folders

### ISSUE THREAD

**Issue by MaDTaZ** [Radarr/Radarr#2080] opened 2017-09-14 21:48 UTC
Would like the option to not have folders in my library.  I have my library all in one folder and dont like to have folders at all..

Thanks

**Comment by whatigot1985** [comment] 2017-09-14 22:58
Please. I second this.  All the folder.... my god it looks soooo bad.........

**Comment by hotio** [comment] 2017-09-15 05:41
Please carry on and keep using something else. This question has been asked to death, every time the question is asked, the feature gets delayed by two weeks...

Current ETA: 2030

**Comment by hotio** [comment] 2017-09-15 05:42
PS: most people find folders sexy and organized.

**Comment by whatigot1985** [comment] 2017-09-15 05:55
you really didn't have to be such an ass about it. fyi.

**Comment by hotio** [comment] 2017-09-15 06:18
Ass? Lol. You living in a porcelain castle?

Act serious, I'm telling it like it is. No need to sugar coat it.

Better search before asking the same over and over, saves me from being an ass. Fyi

**Comment by galli-leo** [comment] 2017-09-15 10:14
Duplicate of #153

**Closed by galli-leo** 2017-09-15 10:14 UTC
