### ISSUE TITLE
Automatically cancel downloads when download speed too low or ETA

### ISSUE THREAD

**Issue by Gby56** [Radarr/Radarr#7666] opened 2022-10-09 11:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have checked the issues and there didn't seem to be a request for that, I tried configured a minimum seeders on my indexer, but in most cases it will be hit and miss. What I usually try to do is get a download time under 12hours, and while some downloads work, they all indicate 1d+, even with my strong fiber connection.

### Describe the solution you'd like

A way to configure, in the download client section, an automatic removal of downloads if they go under a threshold of ETA, for X amount of time (because sometimes the ETA might drop/increase suddenly too).
I think this would be a nice addition to ensure the automated downloads are "robust" and never fail.
A simple way would be to automatically trigger a removal and search again whenever `Download warning: The download is stalled with no connections` is shown.

### Describe alternatives you've considered

Manual oversight and constantly checking that chosen downloads are healthy enough. Would require a lot of fiddling to get a good candidate selection.

### Anything else?

Nothing else !

[AB#3886](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3886)

**Comment by bakerboy448** [comment] 2022-10-09 12:55
Duplicate of #5407

**Closed by bakerboy448** 2022-10-09 12:55 UTC
Labels: Type: Feature Request, Status: Needs Triage
