### ISSUE TITLE
Wrong original language detected

### ISSUE THREAD

**Issue by AndreAfonso87** [Radarr/Radarr#9947] opened 2024-04-22 20:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Shaolin Soccer movie on Tmdb as Cantonese original language, but radarr seems trying to get english Dubbed version. For example it says: "Original Language (English) is wanted, but found Chinese, Russian"
https://www.themoviedb.org/movie/11770

### Expected Behavior

Respecting Original Langage as shown on Tmdb, it should prefer to download Cantonese version of Shaolin Soccer movie.

### Steps To Reproduce

Running Docker version 5.3.6.8612-ls208 by [linuxserver.io](https://linuxserver.io/)
Shaolin Soccer & Kung Fu Hustle movies
Profile with Original Language releases preferred

### Environment

```markdown
- OS: N/A
- Radarr: 5.3.6.8612
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

[radarr.txt](https://github.com/Radarr/Radarr/files/15068531/radarr.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2024-04-22 21:05
Closing, dupe

**Closed by bakerboy448** 2024-04-22 21:05 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by bakerboy448** [comment] 2024-04-22 21:09
Duplicate of https://github.com/Radarr/Radarr/issues/5970
Duplicate of https://github.com/Radarr/Radarr/issues/8002
related to  https://github.com/Radarr/Radarr/issues/7788

- please search issues next time and not just check the box "Cantonese" found the related issues
- for future bug reports info logs are not trace logs 
- Please do not check the box saying the wiki was followed and trace logs provided if one actually did not complete the task.

**Comment by bakerboy448** [comment] 2024-04-22 21:13
`  "OriginalLanguage": "cn",`

https://github.com/Radarr/Radarr/issues/5970#issuecomment-915756908

don't believe this was ever fixed hence still open
