### ISSUE TITLE
Option to disable daily Refresh Movie task

### ISSUE THREAD

**Issue by matijaerceg** [Radarr/Radarr#5544] opened 2020-12-12 20:16 UTC
I understand this has been requested before, but I'm making an appeal.

My daily Refresh Movie scan takes about an hour to complete, depending on how much other activity there is on my server. This is on a dedicated box with gdrive+rclone storage. This is frustrating for a few reasons:

1. During the scan, Radarr runs noticeably less responsive. 
2. I don't change files manually; only Radarr handles my files. So when it scans, it never finds any changes anyway.
3. It's sending thousands of hits to my cloud storage (which has API request limits) every day, only to find no changes.

**My request: An option to disable the daily Refresh Movie task.**

Right now, I'm using [this method](https://www.reddit.com/r/radarr/comments/gywsld/disable_auto_refresh_movie_task/) to disable the task myself.

**Comment by bakerboy448** [comment] 2020-12-12 20:18
Duplicate of #5543

**Comment by matijaerceg** [comment] 2020-12-12 20:19
This is not a duplicate. One is a request to disable the task. The other is a request to exclude Unmonitored movies. 

Please reconsider.

**Comment by bakerboy448** [comment] 2020-12-12 20:19
For the record, I (and many others) have 0 issues with radarr and a gdrive rclone mount

Ensure you’re not using reclines default api

**Closed by bakerboy448** 2020-12-12 20:18 UTC
Labels: feature request

**Comment by bakerboy448** [comment] 2020-12-12 20:20
> This is not a duplicate. One is a request to disable the task. The other is a request to exclude Unmonitored movies.
> 
> Please reconsider.

your end goal is the same and either feature will accomplish that end goal...scan your rclone mounted movies less?

Again, as I just commented I’d check your own setup first.

**Comment by matijaerceg** [comment] 2020-12-12 20:21
I am using my own API key.

You and others not having had issues does not mean that others don't.

The end goal is the same, but the feature requests are explicitly different. 

How many movies are you scanning? How long is each scan taking you?

**Comment by Qstick** [comment] 2020-12-12 20:40
This is the entire reason for the "rescan folders after refresh" setting.... turn it off or set it to after manually triggered only if you really don't change your files outside of Radarr

![image](https://user-images.githubusercontent.com/376117/101994410-38277800-3c90-11eb-8a9f-a731795d8873.png)

**Comment by matijaerceg** [comment] 2020-12-12 20:48
Thank you @Qstick, this setting was not clear to me.

To be clear, if set to off or 'after manual', the daily Refresh Movie task will update metadata without scanning files?

**Comment by Qstick** [comment] 2020-12-12 20:51
Correct... we have users with 150k+ movies on cloud setups. With this setting the daily refresh usually finishes in less than 15 minutes.
