### ISSUE TITLE
Backup never completes

### ISSUE THREAD

**Issue by ipkpjersi** [Radarr/Radarr#7272] opened 2022-05-07 05:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The backup never completes via Backup Now. The "Backup Now" icon spins forever. I have tried setting 777 recursive permissions for `/var/lib/radarr`, I have tried multiple different browsers, nothing I can think of works.

### Expected Behavior

I expect the Backup Now button to complete a backup like it does for me just fine on Sonarr.

### Steps To Reproduce

1. With this environment, go to System > Backup 
2. Click Backup Now
3. The backup never completes, Backup Now stays spinning forever.

### Environment

```markdown
- OS: Ubuntu 20.04 LTS with systemd service: 
- Radarr: Radarr 4.1.0.6175
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Not Applicable
```

### What branch are you running?

Master

### Trace Logs?

```
2022-05-07 00:50:57.0|Info|Microsoft.Hosting.Lifetime|Application is shutting down...
2022-05-07 00:50:57.1|Info|ConsoleApp|Exiting main.
2022-05-07 00:50:57.5|Info|Bootstrap|Starting Radarr - /opt/Radarr/Radarr - Version 4.1.0.6175
2022-05-07 00:50:57.6|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
2022-05-07 00:50:57.9|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
2022-05-07 00:50:58.1|Info|MigrationController|*** Migrating data source=/var/lib/radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-05-07 00:50:58.3|Info|MigrationController|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2022-05-07 00:50:58.5|Info|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:7878
2022-05-07 00:50:59.2|Info|CommandExecutor|Starting 2 threads for tasks.
2022-05-07 00:50:59.4|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2022-05-07 00:50:59.4|Info|Microsoft.Hosting.Lifetime|Hosting environment: Production
2022-05-07 00:50:59.4|Info|Microsoft.Hosting.Lifetime|Content root path: /
2022-05-07 00:52:17.6|Info|BackupService|Starting Backup
```

I set radarr to 777 recursive permissions thinking it would help, maybe it's a permissions issue, but nope it didn't help even after restarting radarr service and confirming radarr restarted:
![](https://i.imgur.com/9IfV2bk.png)

So I restored radarr permissions to what they used to be, it matches sonarr permissions and it's worth noting again that sonarr works perfectly with backing up but radarr does not.

Here is some more screenshots:
The API clearly recieves the command since there aren't any errors: ![](https://i.imgur.com/tqzNj1S.png)
The response seems fine, but the backup never completes no matter how long I wait: ![](https://i.imgur.com/oDgihPG.png)
In the API responses, it looks like it should be done backing up but again it still doesn't complete: ![](https://i.imgur.com/I5atTeN.png)

I noticed that in the radarr changelogs for the latest version, it sounds like backup code has been changed - perhaps that has introduced a regression?

[AB#3117](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3117)

**Comment by bakerboy448** [comment] 2022-05-07 05:18
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

- not convinced this is a bug and no other users have reported it; can reopen if needed
- InfoLogs are not valid for bug reports
- Most UI issues are resolved with a page refresh
- Tasks are where to check if the backup task completed or not

Cannot reproduce on 4.2.0.6245. Backup now triggers and completes a backup as expected

**Closed by bakerboy448** 2022-05-07 05:18 UTC
Labels: Type: Bug, Status: Needs Triage
