### ISSUE TITLE
Manual import from queue fails with System.ArgumentNullException: Value cannot be null. (Parameter 'path2')

### ISSUE THREAD

**Issue by ezrealmaster** [Radarr/Radarr#10062] opened 2024-06-04 20:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After adding a manually downloaded movie to qBittorrent's radarr category, and adding the movie unmonitored to my library, I cannot manually import the movie. A pop-up appears saying "Manually imported 1 file", but the hardlink is not in my root folder, nor the movie folder is created (I manually created it and still fails). Looking at the logs, there was an error during the import.

Might be related to trying to use nzb360 manual import first, which failed in the same way for 2 movies I was trying to import, however I was able to import one of them from the WebUI.

### Expected Behavior

Movie is hardlinked and removed from queue.

### Environment

```markdown
- OS: Windows 10 home 10.0.19045
- Radarr: 5.6.0.8846
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/user-attachments/files/15570359/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2024-06-04 21:03
Duplicate of https://github.com/Radarr/Radarr/issues/7828

**Closed by bakerboy448** 2024-06-04 21:03 UTC
Labels: Type: Bug, Type: Duplicate
