### ISSUE TITLE
Feature Request: Import Movie list from Trakt custom list "Radarr"

### ISSUE THREAD

**Issue by blackley** [Radarr/Radarr#188] opened 2017-01-12 09:03 UTC
User sets up a specific list called "Radarr" - if found Radarr imports the list to internal wanted list and removes the listed movies from the "Radarr" trakt list.

**Comment by galli-leo** [comment] 2017-01-12 09:37
Duplicate of #139

**Closed by galli-leo** 2017-01-12 09:37 UTC
