### ISSUE TITLE
[FEAT]: Add Video Codec As Sorting/Filter Option

### ISSUE THREAD

**Issue by jhuebel** [Radarr/Radarr#6602] opened 2021-09-26 21:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Please add the ability to sort and/or filter on video codec. As newer codecs (such as x265) become more prominent, it would be helpful to be able to filter large movie collections by video codec so that we can find movies that are in older codecs and update them.

### Describe the solution you'd like

Provide the ability to filter and/or sort by video codec so that you can identify movies encoded with older video codecs.

### Describe alternatives you've considered

That I'm aware of, there is no other feature in Radarr that would act as a workaround for this.

### Anything else?

![image](https://user-images.githubusercontent.com/116198/134824391-a2a1e85b-5ffc-45f9-9923-60aac3fea890.png)

Add "Video Codec" as a filter to the "Filters" dropdown.

[AB#1608](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1608)

**Comment by bakerboy448** [comment] 2021-09-26 21:19
Duplicate of https://github.com/Radarr/Radarr/issues/5703

duplicate of https://github.com/Radarr/Radarr/issues/5517

duplicate of https://github.com/Radarr/Radarr/issues/5015

please search better next time

no plans

**Closed by bakerboy448** 2021-09-26 21:19 UTC
Labels: Type: Feature Request, Type: Duplicate
