### ISSUE TITLE
Remove files after seeding for Flood/rTorrent

### ISSUE THREAD

**Issue by adyanth** [Radarr/Radarr#6817] opened 2021-12-15 05:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The files do not get automatically removed from flood once the seeding criteria is met and radarr has ingested it.

### Describe the solution you'd like

Similar to how Sonarr does it automatically.

### Describe alternatives you've considered

Deleting the files manually

### Anything else?

https://github.com/Sonarr/Sonarr/commit/411be4d0116f0739bb9c71235312d0c5a26dd3a2

[AB#2152](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2152)

**Comment by bakerboy448** [comment] 2021-12-15 12:43
This was already done and is already indicated on the wiki as supported

https://github.com/Radarr/Radarr/commit/9a395b52acfb17aec983279b50bfc92c1fa49bae

Duplicate of https://github.com/Radarr/Radarr/issues/6328

please search next time

**Closed by bakerboy448** 2021-12-15 12:43 UTC
Labels: Type: Feature Request, Type: Duplicate

**Comment by adyanth** [comment] 2021-12-15 19:20
Sorry, somehow missed this. When is the next release scheduled to be @bakerboy448 ?
I ask because I rely on `ghcr.io/linuxserver/radarr:latest` which pulls latest releases only.

**Comment by ta264** [comment] 2021-12-15 19:29
There is no schedule, it'll be released when we think it's ready.

**Comment by adyanth** [comment] 2021-12-15 19:30
Okay, thanks for the info! Switching to `nightly` for now.

**Comment by bakerboy448** [comment] 2021-12-15 19:32
[wiki](https://wiki.servarr.com/radarr/faq#how-do-i-update-radarr)

Nightly Disclaimer

> nightly - Current Nightly/Unstable - (Alpha/Unstable) : The bleeding edge. Released as soon as code is committed and passed all automated tests. Use this branch only if you know what you are doing and are willing to get your hands dirty to recover a failed update. This is currently v4. This version is updated immediately.

> Warning: You may not be able to go back to master after switching to this branch. On GitHub, this is the develop branch.

(You cannot go back currently)

**Comment by adyanth** [comment] 2021-12-15 19:33
Ooooh, that is a good catch! Thanks for pointing that out @bakerboy448 !
