### ISSUE TITLE
Title mapping fails when 'imax' is in the title (i.e., "Climax")

### ISSUE THREAD

**Issue by lzep1968** [Radarr/Radarr#4003] opened 2019-12-24 14:50 UTC
**Description:**
When attempting to map a title that contains the text 'imax', title mapping fails.  This can be seen by example using the movie Climax (2018) 

![image](https://user-images.githubusercontent.com/10130228/71417278-7d433c00-2632-11ea-97fb-acb766789b85.png)

Additionally, using the "Force Download" button after forcing a donwload does not seem to work. It produces a brief spinny wheel but the movie never gets downloaded.

**Radarr Version:**
0.2.0.1067
**Mono Version:**
5.14.0.177
**Debug Logs:**
[radarr.txt.zip](https://github.com/Radarr/Radarr/files/3998576/radarr.txt.zip)

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by ta264** [comment] 2019-12-24 14:56
Upgrade any try again,you're on a super old build. Should be at least 0.2.0.1450

**Comment by Qstick** [comment] 2019-12-24 16:11
Dupe of #3355, and fixed in a newer build

**Closed by Qstick** 2019-12-24 16:11 UTC
Labels: bug
