### ISSUE TITLE
[FEAT]: Bulk import movies from existing NFO files or from Plex DB?

### ISSUE THREAD

**Issue by casperse** [Radarr/Radarr#6688] opened 2021-10-29 20:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr can create these NFO files with all the data , I wish it would import them when doing the bulk import

But after a crash and when you need to import it again you have to go through them all
(Problems are with different languages translated into english and you have the same title and for some reason Radarr picks the English one even if the year is wrong) 

The time you safe, bulk importing thousand of titles, and even with only my browser running it gets very slow
Scanning NFO files like KOdi can would make import a dream it could load over night and not have one title wrong!

### Describe the solution you'd like

I think using the Kodi approach and just reading the nfo file with the MovieDB ID would make sense
The look-up by the directory name is very slow (Even on a fast machine it slows down after +200)

### Describe alternatives you've considered

Reading the Plex database (Many people like my self spend allot of time making it "perfect"

### Anything else?

https://forum.kodi.tv/showthread.php?tid=215798

Just imports movies by NFO the first time you add a libarary

[AB#1835](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1835)

**Comment by bakerboy448** [comment] 2021-10-29 21:11
Duplicate of https://github.com/Radarr/Radarr/issues/4200

**Closed by bakerboy448** 2021-10-29 21:11 UTC
Labels: Type: Feature Request, Status: Needs Triage
