### ISSUE TITLE
Not moving and renaming

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#672] opened 2017-02-09 11:46 UTC
Radarr is not not moving and renaming the movie that sabnzbd download.
I have the exact same settings in Sonarr and it is working perfect, why it's not working in Radarr.

**Comment by fedoranimus** [comment] 2017-02-09 13:58
Do you see anything in the SAB or Radarr logs referring to this?

**Comment by crockadile35** [comment] 2017-02-09 22:56
I have the same problem, but do I need to setup drone in order for radarr to rename the files?
in sonarr I have drone setup but not in radarr

**Comment by crockadile35** [comment] 2017-02-09 23:38
an update, I did setup the drone folder, exact same way as sonarr but not in the same place. the settings are identical now. it can rename but I have to do it manually by selecting organize. it can't do it yet automatically

**Comment by onedr0p** [comment] 2017-02-09 23:40
how long did you wait? it doesn't rename when you think it does. Prolly takes 5-10 minutes to organize.

**Comment by crockadile35** [comment] 2017-02-10 00:16
ah, ok I'm doing 1 download for testing purpose and will update my response after

**Comment by crockadile35** [comment] 2017-02-10 00:53
update: the file downloaded at 7:21 and it's 7:54 and it's still in the drone folder

**Comment by rickytin** [comment] 2017-02-10 11:22
I have 2 movies downloaded, Radarr is not moving and renaming and I try to do a manual import and the only thin that happen is the moving ball from left to right.

**Comment by rickytin** [comment] 2017-02-11 02:14
Dose anybody else have this problem.

**Comment by steffenhk** [comment] 2017-02-11 15:50
I have the same problem.
When I try manual import I get this in the logs:
System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.ProcessFolder (System.String folder, System.String downloadId) [0x00049] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:111 
  at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.GetMediaFiles (System.String path, System.String downloadId) [0x0006a] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:101 
  at NzbDrone.Api.ManualImport.ManualImportModule.GetMediaFiles () [0x001c4] in C:\projects\radarr-usby1\src\NzbDrone.Api\ManualImport\ManualImportModule.cs:28 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x42280fb0 + 0x0013b> in <filename unknown>:0 
Close

**Comment by galli-leo** [comment] 2017-02-11 17:34
@steffenhk Fixed on the latest nightly

**Comment by crockadile35** [comment] 2017-02-11 18:04
how do I get the nightly?

**Comment by crockadile35** [comment] 2017-02-11 18:06
never mind on that last comment

**Comment by crockadile35** [comment] 2017-02-11 18:34
The renaming configuration doesn't work and i'm in my last build using the nightly version. is there a guide of how to configure radarr properly

**Comment by crockadile35** [comment] 2017-02-12 13:23
it's still won't rename them. here's the error. Import failed, path does not exist or is not accessible by Radarr:

**Comment by onedr0p** [comment] 2017-02-12 13:25
That usually means Radarr doesn't have access to the folder, are you permissions set correctly?

**Comment by crockadile35** [comment] 2017-02-12 13:30
the permissions are set by default when I created the folder

**Comment by crockadile35** [comment] 2017-02-12 13:31
I'm downloading a file I will test it one more time.

**Comment by onedr0p** [comment] 2017-02-12 13:49
Right, but does the Radarr User/Group have access to read/write that folder?

**Comment by crockadile35** [comment] 2017-02-12 13:50
yes

**Comment by crockadile35** [comment] 2017-02-12 13:51
wait, I didn't create a user group for radarr didn't know I had to create one.

**Comment by crockadile35** [comment] 2017-02-12 13:54
i just saw something that shouldn't happened to me. the read only configuration was checked in the properties of the folder. LOL

**Comment by fedoranimus** [comment] 2017-02-12 15:15
Does Radarr move and rename as you expect now, then?

**Comment by crockadile35** [comment] 2017-02-12 17:01
It's not actually, the files are stuck in the drone folder

**Comment by crockadile35** [comment] 2017-02-12 17:08
It's not actually, the files are stuck in the drone folder

**Comment by crockadile35** [comment] 2017-02-13 15:50
This is an update:
I remove completely radarr from the computer. I installed it in the same computer as sonarr and made the same installation configuration. I even change the service of radarr to load with the username of the computer, so that it can see the network storage same as sonarr but different folder.
![radarr](https://cloud.githubusercontent.com/assets/25674133/22890352/1700dd6a-f1da-11e6-92b4-73d808b61bfd.JPG)
![radarr 2](https://cloud.githubusercontent.com/assets/25674133/22890416/480af562-f1da-11e6-8f96-f522ed2437c7.JPG)

**Comment by crockadile35** [comment] 2017-02-13 21:15
if i move manually the folder to the root of where the files should be, then i press on (update movie info and scan disk), it finds the file and then i press on (preview rename for movie) and it renames to what the movie title plus the year plus the quality. but it cannot grab automatically from the drone folder to put it in the root folder. all my setting are correct even the read and write access. i'm using windows 10 pro 64bit.

**Comment by rickytin** [comment] 2017-02-14 12:36
Why I have to do always the manual move of the movie.
I have the exact same settings in Sonarr and it's working perfect.

**Comment by crockadile35** [comment] 2017-02-14 14:26
the developers are working hard to make this the ultimate movie app. i know they will found a way to make it work like sonarr. i'm patiently waiting. keep it up guys. i'm using the renaming folder of couchpotato for now until there's a fix.

**Comment by fedoranimus** [comment] 2017-02-14 15:20
Just to be clear, this issue is being seen _only_ when using the Drone Factory Folder, correct?

**Comment by crockadile35** [comment] 2017-02-14 15:24
i could say so, i haven't tried not using drone

**Comment by rickytin** [comment] 2017-02-14 16:07
First thanks to the developer I know you are working hard to make a great app.
I have try both way, with and without Drone Factory Folder.

**Comment by fedoranimus** [comment] 2017-02-14 19:43
I maybe have seen this in my own install when _not_ using the Drone Factory.

I'll try and reproduce this using the Drone Factory as well.

**Comment by crockadile35** [comment] 2017-02-16 04:38
Any update on that?

**Comment by fedoranimus** [comment] 2017-02-16 12:44
No updates yet, Drone Factory is not the primary way to handle completed downloads, so priority is on getting Bulk Import out the door.

**Comment by crockadile35** [comment] 2017-02-16 14:12
ok i'm trying without the drone folder. i'm trying with the default location of the completed downloads of sabnzb

**Comment by crockadile35** [comment] 2017-02-16 14:30
WOW, so the drone folder is the problem. OMG I can use the default location. it works and it renamed the file easily right away once it was done downloading it. the reason why I don't want to use the default location is because I have other files that goes there too. so I wanted to separate radarr from other apps.

**Comment by fedoranimus** [comment] 2017-02-16 16:57
@crockadile35 Glad to hear that it works for you without the drone factory. I don't know what download client you're using, but normally they can be added with a tag/label/category such as "Movies" or "Series" which will direct the client on a specific place to put the files.

For instance, with NzbGet, Radarr adds movies to it using the "Movies" label. NzbGet will then create a /downloads/Movies folder (customizable in NzbGet) and put all completed downloads in this folder specifically. NzbGet then tells Radarr where to look for these items and handles it from there.

Perhaps this functionality in your download client may help you separating Radarr from other apps?

**Comment by crockadile35** [comment] 2017-02-16 17:48
I've been using sabnzbd for a very long time, and I've been reading about nzbget and I will try it out. they haven't updated sabnzbd in a while too.

**Comment by crockadile35** [comment] 2017-02-16 20:02
sorry, i won't use nzbget, that thing is so complicated to configure. i haven't had any problem with sabnzbd yet, so i'll stick with that. and i won't use the drone folder for now until they fix it.

**Comment by fedoranimus** [comment] 2017-02-16 20:58
Okay, I have never used sabnzbd, so I am not sure what they offer.

**Comment by crockadile35** [comment] 2017-02-17 00:20
you should check it out, very user friendly and stable. sabnzbd.org

**Comment by crockadile35** [comment] 2017-02-17 00:23
I was looking around to see if someone posted this. is there a way to rename about 500 movies at once instead of doing one by one. like a bulk rename? when adding like 500 movies to the library of radarr

**Comment by fedoranimus** [comment] 2017-02-17 12:21
@crockadile35 I used this [post](https://www.reddit.com/r/usenet/comments/4vezuf/sabnzbd_vs_nzbget_for_those_on_the_fence/) to make my decision, I don't know if it's accurate anymore.

**Comment by crockadile35** [comment] 2017-02-19 20:06
ok I found the way to do it. since radarr doesn't rename folders yet, it can't find the path which would be the movie plus year. so when sab is downloading a movie like passengers it has a bunch of words after the quality. so I activated the rule in the sorting of sab and I ask sab to rename the folder to "movie name year" now radarr moved the file. so it looks like it works like that. I will do some more test but if it works, then we should tell people to activate the sorting on the sab configuration.

**Comment by onedr0p** [comment] 2017-03-02 03:56
Please let me know if you're still having issues on the latest nightly. Thanks.

**Comment by crockadile35** [comment] 2017-03-02 15:13
My nightly version is working fine, I have no issues. it's downloading the movies, and renaming them with the settings of radarr version 0.2.0.426

**Closed** 2017-03-02 15:23 UTC

**Comment by hscanlan** [comment] 2018-03-02 23:54
I have this problem exactly, i have over 60 activities that haven't moved.

**Comment by cscetbon** [comment] 2019-11-08 12:27
The same issue happens to me. The path is correctly configured on the item but it doesn't get moved anymore. Any tips ?

**Comment by onedr0p** [comment] 2019-11-08 13:33
Any logs?
