### ISSUE TITLE
translate film collection name 

### ISSUE THREAD

**Issue by jrbongers** [Radarr/Radarr#9003] opened 2023-08-14 05:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

It would be nice if the film collection is also shown in the language set in the film language settings.
Example:  Mission: Impossible Collectie (dutch) instead of Mission: Impossible Collection.

### Describe alternatives you've considered

not using filmsets in radarr

### Anything else?

nope

**Comment by bakerboy448** [comment] 2023-08-14 09:05
Duplicate of https://github.com/Radarr/Radarr/issues/6911

**Closed by bakerboy448** 2023-08-14 09:05 UTC
Labels: Type: Feature Request, Status: Needs Triage
