### ISSUE TITLE
Radarr doesn't delete movies removed from watchlist, no error

### ISSUE THREAD

**Issue by j2ghz** [Radarr/Radarr#1695] opened 2017-06-18 08:44 UTC
**Description:**
When I set a movie as watched on Trakt, Radarr correctly detects, that it was removed from my lists. In log it says that it's removing the file. There is no other message about non-success after it, but the file is not removed. If I do `rm -r "Split (2016)"` from the same user as Radarr it works.

**Radarr Version:** 0.2.0.696

**Logs:**
```
Split (2016)/:
total 5.5G
drwxrwxrwx 1 nobody nogroup 4.0K Jun 13 19:39 .
drwxrwxrwx 1 nobody nogroup  28K Jun 11 09:42 ..
-rwxrwxrwx 1 nobody nogroup 5.5G Nov 15  2016 Split (2016).mkv
```
```
17-6-18 09:27:26.5|Info|NetImportSearchService|[tt4972582][Split (2016)] was in your library, but not found in your lists --> Removing from library and deleting files
17-6-18 09:27:26.5|Trace|EventAggregator|Publishing MovieDeletedEvent
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent -> PendingReleaseService
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent <- PendingReleaseService
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent -> MovieModule
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent <- MovieModule
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent -> CalendarModule
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent <- CalendarModule
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent ~> BlacklistService
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent ~> MediaFileService
17-6-18 09:27:26.5|Trace|EventAggregator|MovieDeletedEvent <~ BlacklistService
17-6-18 09:27:26.6|Trace|EventAggregator|MovieDeletedEvent <~ MediaFileService
17-6-18 09:27:26.7|Trace|CommandQueueManager|Updating command status
17-6-18 09:27:26.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-6-18 09:27:26.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-6-18 09:27:26.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-6-18 09:27:26.8|Trace|EventAggregator|Publishing CommandExecutedEvent
17-6-18 09:27:26.8|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-6-18 09:27:26.8|Trace|TaskManager|Updating last run time for: NzbDrone.Core.NetImport.NetImportSyncCommand
17-6-18 09:27:26.8|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-6-18 09:27:26.8|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-6-18 09:27:26.8|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-6-18 09:27:26.8|Trace|CommandExecutor|NetImportSyncCommand <- NetImportSearchService [00:00:00.8982680]
17-6-18 09:27:26.9|Trace|Http|Req: 768 [GET] /api/system/task?sort_by=name&order=asc
17-6-18 09:27:26.9|Trace|Http|Res: 768 [GET] /api/system/task?sort_by=name&order=asc: 200.OK (7 ms)
17-6-18 09:27:26.9|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (7 ms)
```

**Comment by galli-leo** [comment] 2017-06-18 09:01
Yeah, currently deleting files is not implemented. Sorry, never really came around to it, and do not wanna implement something that deletes files, without rigorous testing. Anyways, issue is a duplicate of #694.

**Closed by galli-leo** 2017-06-18 09:01 UTC
Labels: duplicate
