### ISSUE TITLE
Special char ":" wrong replaced

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#2776] opened 2018-05-14 16:55 UTC
Hi, I just saw that the char : was replaced in a wrong way, is just deleted, so a film like

2:22 became 222 and is difficult to find, only few resulst (that is only one example)

a correct one is 2.22 that find more results

Thank you

Jorman

**Comment by weirdcrap** [comment] 2018-05-15 21:44
How radarr handles this is defined in your media management settings

![image](https://user-images.githubusercontent.com/22824785/40085193-4b1a3a0a-585f-11e8-813a-aab16419fdb1.png)

**Comment by Jorman** [comment] 2018-05-16 05:55
Sorry maybe I miss that, but is about searching phase :D

I tried changing the option you told me, but is only for importing phase, like you said.

But yes definitely for searching phase

I don't know if can be a good idea a kind of table where a user can specify the replacement for each special char in their proper language. But : is deleted and is not good, during a search, maybe a . can be better

**Comment by weirdcrap** [comment] 2018-05-16 12:11
so I added the movie you gave in your example and I had no issues with finding results. I didn't count them all but over 25+ between my usenet indexers and trackers the majority of them being the proper film in question:

![screen shot 2018-05-16 at 7 06 46 am](https://user-images.githubusercontent.com/22824785/40116054-16ceab68-58d8-11e8-82f3-8ae24dbea2e4.png)

Can you post information about your specific configuration?

**Comment by Jorman** [comment] 2018-05-18 11:38
Hi, sorry for the late reply

See here
https://pastebin.com/8Qh7EtTn

Is the search log, if you notice, Radarr search for "222 2017" or "222 il destino è già scritto" (that is the italian name)

Yes I search the foreign language but is the same with English one, because 2:22 became 222 instead 2.22

For example in this traker if you search:
https://ilcorsaronero.info/argh.php?search=222+Il+destino+%C3%A8+gi%C3%A0+scritto+2017

you can't fine nothing but if you search:
https://ilcorsaronero.info/argh.php?search=2.22+Il+destino+%C3%A8+gi%C3%A0+scritto+2017

you can find one result

what do you think?

**Comment by galli-leo** [comment] 2018-05-19 12:06
Duplicate of #2565

**Closed by galli-leo** 2018-05-19 12:06 UTC
