### ISSUE TITLE
Some much needed QOL features

### ISSUE THREAD

**Issue by markdeejay** [Radarr/Radarr#8732] opened 2023-06-23 21:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Whenever I update a movie manually, without interference of Radarr (as to why this is I refer to the next section(s), whenever Radarr rescans the library (daily I think?) everything gets removed (images) and replaced (.nfo files removed by Radarr, then recreated by Emby) anyway, which - with a large library - is quite the undertaking to restore and just an extreme hassle.

### Describe the solution you'd like

Radarr currently has little use for me except for to search movies. Everything that it does afterwards - REMOVE ALL the files in the directories when importing - is a pain in the bum. I want a(n optional) feature that lets me choose to remove existing files or not. This applies to the library scan as well. It shouldn't do anything except add the available information to Radarr and NOT replace or delete anything.

### Describe alternatives you've considered

No alternatives, but Sonarr does this (importing and/or replacing) perfectly. It doesn't mess with any files except for the video files. Why can't Radarr do this? It should be a basic, or at least an optional, feature.

### Anything else?

I'm sure you're familiar with Sonarr since this is based on that (I think?) so look to that for how it does this correctly.

**Comment by bakerboy448** [comment] 2023-06-23 21:04
Duplicate of numerous existing issues.

**Closed by bakerboy448** 2023-06-23 21:04 UTC
Labels: Type: Feature Request, Status: Needs Triage
