### ISSUE TITLE
Language profiles

### ISSUE THREAD

**Issue by AlexR00T** [Radarr/Radarr#6377] opened 2021-06-06 22:30 UTC
**Describe the solution you'd like**
I want a port of Sonarr's feature called Language profiles for adding multiple language processing. Sonarr did add it a couple of moons ago. It's a feature quite requested. PLEASE ADD IT. Thank you a lot. 🙏 

**Describe alternatives you've considered**
Theres been many ideas and alternatives discussed previously but I think this works great for Sonarr and would fit well Radarr too.

**Comment by bakerboy448** [comment] 2021-06-06 22:31
Please search prior to opening issues

duplicate of https://github.com/Radarr/Radarr/issues/5074

**Closed by bakerboy448** 2021-06-06 22:31 UTC
