### ISSUE TITLE
[FEAT]: Universally Exclude/Blacklist Grab

### ISSUE THREAD

**Issue by neo-neo1** [Radarr/Radarr#6718] opened 2021-11-10 05:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

**Example use of case of problem:**
When Radarr grabs a particular undesirable release _(e.g. corrupt video, fake video, wrong movie, packaging issue, watermarked, etc..)_. Currently there's no way to blacklist or exclude this specific release from Radarr grabbing again. 

You can press the X under `History` which `Marks it as failed`. However, this only blacklists the release from that specific indexer. And upon clicking the X to `Mark it as failed` it will instantly initiate a search and auto grabs the same release from another indexer (refer to below photo) when the need in this case is to universally block it across all indexers.

![thorp](https://user-images.githubusercontent.com/6996362/141054978-f53abdf6-ff1e-454b-93a1-0e4cbd29269d.png)

### Describe the solution you'd like

Next to `X` which `Marks it as failed` add a small `Exclude` or `Blacklist` button. This button will exclude this specific `filename` from being grabbed in other indexers.

### Anything else?

Other people have had this identical issue, see post belowi

[AB#1892](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1892)

**Comment by neo-neo1** [comment] 2021-11-10 07:42
Seems like I wasn't the first to request this.

https://github.com/Radarr/Radarr/issues/3863

https://github.com/Radarr/Radarr/issues/6390

https://github.com/Radarr/Radarr/issues/5911

**Comment by LoganSchmalz** [comment] 2023-01-18 05:55
I am having this problem and Radarr is even grabbing torrents from the same indexer. #6390 was closed without any response from the users experiencing the issue, so either they resolved it themselves or it seems to be forgotten.

**Comment by charlesabell5** [comment] 2023-03-09 19:45
I continue to have this same issue as well, can be reproduced on demand. Can provide logs or info if additional info on this issue is still needed.

**Comment by GregoryGHarding** [comment] 2023-10-17 03:28
also still having this issue, let me know what you need.

**Comment by bakerboy448** [comment] 2023-10-18 17:55
Duplicate of https://github.com/Sonarr/Sonarr/issues/6108

no new feature is required.

**Closed by bakerboy448** 2023-10-18 17:55 UTC
Labels: Type: Feature Request, Area: UI, Area: API, Status: Needs Triage
