### ISSUE TITLE
IMDB Movie List Import Support

### ISSUE THREAD

**Issue by markhaines** [Radarr/Radarr#187] opened 2017-01-12 08:57 UTC
Would be great if Radarr could replicate the Couch feature to regularly poll a user's public IMDB movie watchlist and automatically add these movies to the 'wanted' list.

As well as being an easy way to add new movies it also acts as a sort of backup.  If I were to lose all my movies due to disk failure I can just reinstall Radarr, point it at IMDB and it can go and hunt them down again.

**Comment by Mirabis** [comment] 2017-01-12 09:18
When considering this request,would it be possible to add a few extra otions?

- Only download current (or X configurable) years movies. This helps when you use a watchlist to automate downloading but don't want it to backfill movies from 2014 still on your list.

**Comment by galli-leo** [comment] 2017-01-12 09:36
Duplicate of #139. Please move your discussion to there.

**Closed by galli-leo** 2017-01-12 09:36 UTC
