### ISSUE TITLE
Customs Format Size does not allow sizes under 1GB

### ISSUE THREAD

**Issue by darkzabat** [Radarr/Radarr#7476] opened 2022-08-14 17:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a Custom Format using the condition Size with a Minimum Size of 0 and a Maximum Size greater than 0, you get the error “'Min' must be greater than '0'.” when attempting to save the Custom Format.

### Expected Behavior

A Custom Format with a Size condition of Minimum 0 and Maximum greater than zero should be allowed and was allowed in previous versions.

### Steps To Reproduce

1. Create new Custom Format
2. Add Condition - Size
3. Put 0 for Minimum Size
4. Put any number greater than 0 for Maximum Size
5. Save Condition - Size
6. Save Custom Format
7. Get error “'Min' must be greater than '0'.”

### Environment

```markdown
- OS: Fedora
- Radarr: 4.2.2.6482
- Docker Install: No
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

2022-08-14 10:40:37.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Min: 'Min' must be greater than '0'.

[AB#3458](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3458)

**Comment by bakerboy448** [comment] 2022-08-14 17:57
A min size of 0 doesn't make any sense..?

what release would have no size?

**Comment by bakerboy448** [comment] 2022-08-14 18:02
Closing
Not a bug, this is intentional.

previous versions did not have any validation

https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/CustomFormats/Specifications/SizeSpecification.cs
https://github.com/Radarr/Radarr/commit/16ed68d5de5add1ee017bc3181f08e7c835d4b9f

**Comment by darkzabat** [comment] 2022-08-14 18:05
This isn’t for a release of size 0. This is so a release can be greater than 0 but less than 1GB. With the current conditions there is no way to have a minimum size smaller than 1GB which there are definitely releases smaller than 1GB. Why is a minimum size even required if a maximum size is entered?

**Comment by darkzabat** [comment] 2022-08-14 18:29
I created bug [#7477](https://github.com/Radarr/Radarr/issues/7477)  for the other issue mentioned in my comment about both min and max should not be required in the condition size.

**Closed** 2022-08-14 21:19 UTC
Labels: Type: Bug, Type: Regression

**Comment by ItsME6969** [comment] 2022-08-16 00:13
Commented a while back on a similar issue https://github.com/Radarr/Radarr/issues/6147#issuecomment-971782982 and I'd just like to reitterate that there are alot of WEB-DLs and other releases (Including Shorts) that are under a GB and limiting the Size to GB puts a really big limitation in the use of this feature @Qstick. Please allow for at the very least 100MB ranges.
