### ISSUE TITLE
Download button not appearing next to manual searches that do not quite match.

### ISSUE THREAD

**Issue by shadow7412** [Radarr/Radarr#1892] opened 2017-08-10 00:26 UTC
In Sonarr, you could force the download of a file even if it didn't register as a hit with the matcher.

Radarr however seems to hide that button. In the example I've shown for example, the matcher doesn't like the found file because it "Failed to find movie title in release name". That's fine, they are a little different, but as a user I've made a decision that the file shown is probably good enough, and would like it to be downloaded anyway. I've circled the region where I would expect to see this download button.

**Radarr Version:** 0.2.0.778 - 20 Jun 2017

![image](https://user-images.githubusercontent.com/286341/29148859-6df661e8-7db3-11e7-8300-753fabb88399.png)

**Comment by hotio** [comment] 2017-08-10 05:19
Works as intended.

**Comment by shadow7412** [comment] 2017-08-10 05:35
@hotio this behavior differs from sonarr and means I can use radarr to download that movie.

How is this intended? Or, more importantly, how do I use radarr to download that movie in this scenario?

**Comment by hotio** [comment] 2017-08-10 07:01
There are always going to be files that are gonna cause trouble and we humans can immediately see that this is a file we would want, but for radarr with al the info it has, it's a file we definately don't want.

I'll bet you that if radarr would allow that file to show a download button, just as many people would complain "Why does radarr allow me to download this junk, can't this be filtered out?"

Luckily we humans are problem solvers and it would be fairly easy to manually download this particular file if the need to have it grows bigger than the laziness.

**Comment by galli-leo** [comment] 2018-02-06 18:39
This is fixed with force download.

**Closed by galli-leo** 2018-02-06 18:39 UTC

**Comment by alvarooooo** [comment] 2020-03-17 08:10
Hola, yo tengo el mismo problema, pero sin embargo en este caso no lo he podido solucionar con una descarga forzosa, al darle al botón de descarga forzosa no hace nada, carga por un segundo y después no cierra ni siquiera la ventana.
Si descargo el archivo torrent manualmente desde Jackett y lo abro con un cliente torrent no descarga ningún archivo malicioso y dentro contiene la película que quiero descargar.
A continuación dejo la configuración del indexador y el archivo con el que tengo el problema:
Configuración de indexador en Jackett:

![image](https://user-images.githubusercontent.com/35309709/76835182-d2a47900-682e-11ea-87e3-fd3bd1b53bab.png)

Conexión del indexador entre Radarr y Jackett:

![image](https://user-images.githubusercontent.com/35309709/76835207-e3ed8580-682e-11ea-907a-48831d9d80e4.png)

Ejemplo de archivo torrent con ese problema:

![image](https://user-images.githubusercontent.com/35309709/76835243-ef40b100-682e-11ea-9c40-fd30ae1ee417.png)

Información del rechazo:
