### ISSUE TITLE
Filter for current quality

### ISSUE THREAD

**Issue by quadcom** [Radarr/Radarr#9472] opened 2023-12-09 18:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This is related to https://github.com/Radarr/Radarr/issues/5304

While we can filter against a QProfile, there's no way to find older files, prior to using Radarr, and replace versions.

### Describe the solution you'd like

Based on the other closed issue, it was determined that filters against file properties would not be implemented. But there is a need to filter based on that kind of criteria.

### Describe alternatives you've considered

There is another option, and that is filtering by path. Currently, it only searches the direct path to the file but not the filename itself. Most people have file management set to include the resolution of the file in the file name.

Using that filter on path and including the file names, possibly as an option, would allow for finding DB entries that match. 

### Anything else?

Currently, there is no other workaround to find this content in the library. This would allow us to manage that content or tag these entries appropriately.

**Comment by bakerboy448** [comment] 2023-12-09 18:43
Duplicate of #5304

**Closed by bakerboy448** 2023-12-09 18:43 UTC
Labels: Type: Feature Request, Status: Needs Triage
