### ISSUE TITLE
Import subs file or Import all extra files

### ISSUE THREAD

**Issue by nzarbayezid** [Radarr/Radarr#7375] opened 2022-06-21 05:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

the problem is that there is no way that you can import an Srt file from a subfolder

### Describe the solution you'd like

there should be a way to import Srt files from the inside sub-folders, for example, most of the torrents came with Srt files inside a sub-folder called Subs, [like this](https://imgur.com/a/h2RQTeE).

### Describe alternatives you've considered

I'm saying maybe there should be a future below Import Extra Files to let the user import all the Sub-folder now matter what's inside them, sometimes there are extra moves or videos related to the movie inside the Sub-folders and sometimes there is Srt, or mabye there is a way to tell the Radarr to scan all the subfolders for Srt files and import them, this is also can be below the Import Extra Files future

### Anything else?

this is an important future for Radarr because it maintains the automation of Radarr that we love about it

[AB#3303](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3303)

**Comment by bakerboy448** [comment] 2022-06-21 10:16
Duplicate of #7092

**Closed by bakerboy448** 2022-06-21 10:16 UTC
Labels: Type: Feature Request, Type: Duplicate
