### ISSUE TITLE
Add ability to filter by quality

### ISSUE THREAD

**Issue by RickoT** [Radarr/Radarr#9708] opened 2024-01-29 01:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I would like to see an additional filter option on the movies page to filter by quality (not quality profile).  In my case, i imported a lot of movies that show as unknown instead of their actual quality (720p) and since there's no way (that I could find) to filter by quality, i have to manually go to each movie to see what quality it is so I can update it

### Describe alternatives you've considered

Adding additional info to the view on the movies tab and scrolling to find movies that don't meet the quality I want them in

### Anything else?

No, i think this should be pretty easy to implement

**Comment by bakerboy448** [comment] 2024-01-29 01:02
Duplicate of https://github.com/Radarr/Radarr/issues/5304

**Closed** 2024-01-29 01:03 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by RickoT** [comment] 2024-01-29 02:21
I did, I used this filter when searching : is:issue is:open quality
Neither of the id's you listed above came up in my results, sorry for the duplicate

**Comment by RickoT** [comment] 2024-01-29 02:24
Never mind, I see the error in my ways, I didn't realize they were not considered "issues" -- again sorry about that
