### ISSUE TITLE
Upgrading movie loses Plex sharing labels

### ISSUE THREAD

**Issue by tribeforward** [Radarr/Radarr#1829] opened 2017-07-23 16:09 UTC
**Description:**
If a movie that has a label for sharing in Plex is upgraded by Radarr, the upgraded version no longer has the label.

I suspect that Radarr is deleting the original movie file before copying in the new file. When I have manually upgraded a movie by moving the upgraded file in and then deleting the old file, the label stays. This may only happen when Plex is set to update the library automatically on changes.

**Radarr Version:**
0.2.0.778

**Steps to Reproduce:**
1. Add DVD version of a movie to Plex
2. In Plex, edit the movie details
3. Switch to the sharing section
4. Add a label to the movie
5. In Radarr, upgrade to an HD version of the movie

After import, the movie no longer has the sharing label in Plex.

**Comment by galli-leo** [comment] 2017-07-23 16:52
Yeah we first delete the existing file, before copying the other one over. I don't think there is a way around that.

**Comment by ChadScott** [comment] 2017-07-24 21:22
I think what would fix this is to notify Plex _after_ the delete and replacement happens and not after the delete itself. I guess this gets hairy if there is more than one thread going on, though.

**Comment by galli-leo** [comment] 2017-07-25 11:17
@ChadScott We are doing that, the problem is plex scanning before the replacement happens.

**Comment by ChadScott** [comment] 2017-07-25 16:28
Interesting. That line of thought then gives me another way to possibly make this less painful: turn off all automatic updates. I just disabled my periodic and automatic scans in Plex... I'll see if that helps with this.

Seems obvious but it had never occurred to me before. Thanks!

**Comment by bbaldino** [comment] 2017-08-18 05:57
@galli-leo is there a reason why the removal of the old file can't be done after the upgraded one is moved/copied into place?  i've been running into this because plex shows upgraded movies under 'recently added' because the old file is deleted first.  i took a shot at the change in a branch here: https://github.com/bbaldino/Radarr/tree/delete_after_upgrade but i'll admit i've not tried to build it and run it yet; i saw this and wondered if there was a specific reason why things were done in this order.

**Comment by galli-leo** [comment] 2017-08-19 16:33
@bbaldino Because they might be named the same?

**Comment by bbaldino** [comment] 2017-08-19 19:43
@galli-leo is that the only reason?  if so that seems like a case that could be detected and handled by just overwriting the old file and then not removing the new one.  i can take a shot at updating my pr.  what do you think?

**Comment by galli-leo** [comment] 2018-02-06 19:03
@bbaldino Sorry for not coming back to you sooner, but sure if you are still willing to, you can throw up a pr and I will take a look at it.
Closing the issue as wontfix though.

**Closed by galli-leo** 2018-02-06 19:03 UTC
Labels: wontfix
