### ISSUE TITLE
RSS list, only 273 loaded.

### ISSUE THREAD

**Issue by garyleecn** [Radarr/Radarr#1261] opened 2017-03-24 18:37 UTC
trying to switch from couch potato to radarr, using the march.12, 2017 version.

I added couple RSS lists, including 2 IMDB list (including ~2000 titles), a Bluray.com list, and StevenLu list. all lists are set to "Enable Auto sync: on", and "Add movies monitored: on", minimum availability: Physical.
however, radarr stops adding new titles when there are exactly 273 records in the list. I did a fresh install of radarr, still stops at exact 273 movies. 

any idea what's wrong? thanks

**Comment by garyleecn** [comment] 2017-03-24 18:47
<img width="1032" alt="screen shot 2017-03-24 at 11 45 10 am" src="https://cloud.githubusercontent.com/assets/26658796/24309051/8e461c34-1087-11e7-83de-9f6b18fc2705.png">
also I notice that it's only loading 200 entries from RSS, and it somehow stops at <La La Land>.

**Comment by 4getit** [comment] 2017-04-01 17:31
IMDb rss feeds only contain 250 entries. Try to load them manually so you can see what the issue is.
CP parses the IMDb webpages. Radarr doesn't.

**Comment by galli-leo** [comment] 2017-06-15 09:12
Fixed on latest nightly.

**Closed by galli-leo** 2017-06-15 09:12 UTC
