### ISSUE TITLE
Feature request: more prominent parser error reporting?

### ISSUE THREAD

**Issue by matthewaaronthacker** [Radarr/Radarr#4820] opened 2020-08-04 15:42 UTC
I've run into this issue a couple of times where Radarr doesn't like something about the format or filename of a download so the DownloadedMovieImportService fails. That leaves it in this weird state where the movie doesn't exist in Plex, but it has the little black download cloud in Radarr and I'm trying to figure out where the hell the movie is! :) 

Would it be possible to add a feature that floats this type of error up to the gui somehow so we don't have to go digging through log files to figure out what went wrong?

Example:
2020-8-4 10:41:46.0|Debug|QualityParser|Trying to parse quality for Cornetto.2.Hot.Fuzz.2007.1080p.BluRay.DTS.x264-CyTSuNee
2020-8-4 10:41:46.0|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-8-4 10:41:46.0|Debug|Parser|Parsing string 'Cornetto.2.Hot.Fuzz.2007.1080p.BluRay.DTS.x264-CyTSuNee'
2020-8-4 10:41:46.0|Debug|Parser|Movie Parsed. Cornetto 2 Hot Fuzz - 2007 
2020-8-4 10:41:46.1|Debug|Parser|Parsing string 'Cornetto.2.Hot.Fuzz.2007.1080p.BluRay.DTS.x264-CyTSuNee'
2020-8-4 10:41:46.1|Debug|Parser|Movie Parsed. Cornetto 2 Hot Fuzz - 2007 
2020-8-4 10:41:46.1|Debug|DownloadedMovieImportService|Unknown Movie Cornetto.2.Hot.Fuzz.2007.1080p.BluRay.DTS.x264-CyTSuNee

**Comment by austinwbest** [comment] 2020-08-04 16:48
The parser worked fine bud.

`2020-8-4 10:41:46.1|Debug|Parser|Movie Parsed. Cornetto 2 Hot Fuzz - 2007`

The problem is it cant match to something you have added (for good reason)

`2020-8-4 10:41:46.1|Debug|DownloadedMovieImportService|Unknown Movie Cornetto.2.Hot.Fuzz.2007.1080p.BluRay.DTS.x264-CyTSuNee`

And this is pretty easy, the movie is called "Hot Fuzz" not "Cornetto 2 Hot Fuzz"
https://www.themoviedb.org/movie/4638-hot-fuzz

**Comment by matthewaaronthacker** [comment] 2020-08-04 16:54
I’m not an idiot. I probably could have worded the ticket better, but the spirit of the request is the same. The parser didn’t “fail” in the sense of there being a bug in the parser, but it did “fail” to match the movie name to the requested download, and there’s no indication in the radarr gui that “hey, I asked the download client to download this movie, and what the download client gave me doesn’t match”.
That’s what I’m asking for. Something that makes that kind of error more obvious without having to dig through the log files.

**Comment by austinwbest** [comment] 2020-08-04 17:00
Didn't say anything about you being an idiot, was just addressing the log results.

You're saying that Radarr grabbed this movie on its own even though it doesn't exist? You didn't manually add it?

**Comment by matthewaaronthacker** [comment] 2020-08-04 17:05
Yup. It’s happened a few times now and seems specific to searching/downloading with newsgroups rather than torrents. Radarr searches NZBGeek, gets back a hit, feeds it over to SABnzbd, and when the file gets downloaded and put back together by SAB it has some weird naming scheme that Radarr doesn’t like (understandably).

**Comment by austinwbest** [comment] 2020-08-04 17:35
@Qstick may be able to shine some light on that

**Comment by Qstick** [comment] 2020-08-04 18:16
What version are you on? Seems you just decided to blitz out the issue template

**Comment by Qstick** [comment] 2020-09-06 05:02
Closing until we get template info

**Closed by Qstick** 2020-09-06 05:02 UTC
Labels: information needed
