### ISSUE TITLE
Search by Cast (Actor, Director etc) 

### ISSUE THREAD

**Issue by StephenFierce** [Radarr/Radarr#6341] opened 2021-05-22 08:44 UTC
When I find an actor or director that I wanna watch more of I need to make a list or manually Google them to find their movies. 
Wouldn't it be wonderful to search them inside of radarr? 

The solution could either be a filter or search query like "actor: Tom Hanks" or "c: Steven Spielberg" (c for cast). OR it could just be searching the name just like you search for movies. 

Alternatives are googling and lists which are slow and seem unnecessarily arbitrary. 

You're a bunch of MVPs :)

**Comment by bakerboy448** [comment] 2021-05-22 11:31
Duplicate of #1685

**Closed by bakerboy448** 2021-05-22 11:31 UTC
