### ISSUE TITLE
metadata - poster.jpg/fanart.jpg is empty - 0kb

### ISSUE THREAD

**Issue by SugarDroid** [Radarr/Radarr#5419] opened 2020-11-28 18:43 UTC
**Describe the bug**
I'm using Kodi/Emby Metadata service to get these files, but sometimes one of them is empty. If i manually delete it from the file system, using the "Refresh & Scan" function fix it, 

**To Reproduce**
Since it's totally random -mostly works as expected- other than waiting until it happens, there's no way to intentionally reproduce it.

**Expected behavior**
Radarr check them and auto delete, re-import if file size is zero, thus they get stored properly.
![image](https://user-images.githubusercontent.com/56313144/100523169-a2c7b680-31ae-11eb-848f-27d6e3c64f06.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/56313144/100520989-2e3a4b00-31a1-11eb-806a-61e6e057c188.png)

Different movie, no log.
![image](https://user-images.githubusercontent.com/56313144/100521143-24fdae00-31a2-11eb-9f26-31ae9f256530.png)

**Platform Information (please complete the following information):**
- Version 3.0.0.4194
- Package Version 3.0.0.4194-ls2 by linuxserver.io
- .NET Core Yes (3.1.10)
- Docker Yes

**Trace Logs**
https://pastebin.com/gPQTs3dN

[AB#754](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/754)

**Comment by xen0m0rph2020** [comment] 2020-12-04 21:45
having same issue posted on reddit and on discord and no one had any idea what was wrong.
only fix is to delete the 0 byte poster and refresh the movie.
very annoying as it happens on every movie I add
no issues on older version of radarr and im also running it on docker

**Comment by bakerboy448** [comment] 2020-12-04 22:35
Trace logs will have the link to the posters being pulled.

Can you guys check within about the same time the posters are grabbed  by radarr and see if the file being pulled is in fact 0 bytes or some reason or has issues being saved to the disk outside of radarr at the time?

Otherwise, seems like a check to add that would be logical

**Comment by SugarDroid** [comment] 2020-12-05 00:45
All files exist with proper size within Radarr's config directory.
![image](https://user-images.githubusercontent.com/56313144/101226003-52ab9100-3693-11eb-8f1b-14d4884a2a0b.png)
The same files within movie's directory.
![image](https://user-images.githubusercontent.com/56313144/101226232-1fb5cd00-3694-11eb-881b-d2f1c192ef6f.png)

Clearly looks that Radarr pulled the files just fine, but something happens during copy to movie's directory.

**Comment by xen0m0rph2020** [comment] 2020-12-05 18:13
yes same it downloads in app folder fine but moving to Media it goes 0 bytes

**Comment by hart8100** [comment] 2020-12-06 23:22
I'm having the same issue, this is not a fix, but at least it makes deleting the files quicker. Type this into the folder search box to find all of the 0KB jpg files "size:empty AND ext:jpg", then you can select all and delete, and cross fingers and refresh.

The search is recursive so doing this in the main folder should find all of the files.

**Comment by xen0m0rph2020** [comment] 2020-12-13 17:10
@bakerboy448 any updates on this?

**Comment by xen0m0rph2020** [comment] 2021-02-24 19:51
guess this not getting fixed

**Comment by bakerboy448** [comment] 2021-02-24 19:54
It will be fixed when it is fixed. If you would like it fixed sooner, feel free to submit a PR.  There’s limited development resources and this is all volunteer work.


Comments that are not productive to the issue at hand such as +1, me too, i want this too, when will this be in, any updates, etc. are poor etitique and do not result in issues being worked on any faster. Repeated comments of this nature will result in the thread being locked.

**Comment by xen0m0rph2020** [comment] 2021-02-24 21:45
> It will be fixed when it is fixed. If you would like it fixed sooner, feel free to submit a PR. There’s limited development resources and this is all volunteer work.
> 
> Comments that are not productive to the issue at hand such as +1, me too, i want this too, when will this be in, any updates, etc. are poor etitique and do not result in issues being worked on any faster. Repeated comments of this nature will result in the thread being locked.

ok sorry

**Comment by Buster14** [comment] 2021-05-09 00:06
Hi, today i noticed something regarding this issue :
1. Add movie
2. Delete the 0kb poster immediately
3. Radarr would then write proper poster and fanart jpg onto that movie folder automatically.

So i'm just guessing, but probably there's a duplicated poster.jpg copying process somewhere that needs to be removed?

**Comment by Buster14** [comment] 2021-05-09 00:06
Hi, today i noticed something regarding this issue :
1. Add movie
2. Delete the 0kb poster immediately
3. Radarr would then write proper poster and fanart jpg onto that movie folder automatically.

So i'm just guessing, but probably there's a duplicated poster.jpg copying process somewhere that needs to be removed?

**Comment by inspector71** [comment] 2021-06-20 12:41
In case this helps, for me, at present, this is only happening with `poster.jpg` files. 

`fanart.jpg` and `movie.nfo` files are copied (?) to the movie folder, no worries. 

My install:

```
Version
    3.2.2.5080
.NET
    Yes (5.0.5)
DB Migration
    195
AppData directory
    C:\ProgramData\Radarr
Startup directory
    C:\ProgramData\Radarr\bin
Mode
    Tray
```

In my case, movie files are located on a NAS unit separate to the laptop running Radarr. Added folders in the following syntax:

```
\\192.168.1.1\Publc\movies\[A-Z]\[movie folder]\[movie files]

(where [ ] characters represent changable variables)
```

Mention this in case this issue may have anything to do with file systems. Perhaps a Samba or Windows Networking bug, something like that.

Also, my Settings > Media Management:

https://i.imgur.com/GkNSfd5.png

Being 100% new to coding *arr apps, but wanting to help, are there any tips or guides around? Or would it be a matter of scuba diving in and looking around? Thing is, I have zero .Net experience. So any leg-up would be highly appreciated, but of course I am not wanting to be a burden either.

P.S. My intention here is not to aggravate the volunteer devs. Like many, experiencing a bug has annoyed me often in this digital age. However, I have learned (the very painful way) to not so much be patient but try (not always successful) and see the topic from a broad perspective as objectively as I can. If this specific issue could be considered a regression bug (if), there are perhaps few bug categories more aggravating for developers. You work hard staring at pixels, punching keys to build, refine and deliver a quality end result you personally can be proud of, only to find out months after release a regression slip has broken hitherto working code. Frustrating it may be for end users, but arguably regressions can perhaps be a problem when refactoring code. Why refactor? Arguably, it is a necessary evil> To move forward many steps, first need to 'take the hit' of going sideways or backwards a step or few. Otherwise, the medium-long term patchwork quilt a developer suspects will hang over their future efforts likely will not go away by itself. If ... _**if**_ that has possible been the case here, or actually even if not, I empathise. For non-developers, think of regression bugs as redrafting entire chapters of a book. Restarting a car respray job because all those hours of filling and sanding have been for nowt because you spray it and suddenly see a huge flaw only after the paint dries. Etc

**Comment by inspector71** [comment] 2021-06-21 02:05
Just added a new movie. The zero-byte `poster.jpg` files are created when adding a new folder for a new movie. Hope this helps.

**Comment by Buster14** [comment] 2021-06-27 23:45
https://youtu.be/vUpK_qlWSu8

Here's what i meant on my earlier post

1. Add movie
2. Delete the 0kb poster immediately
3. Radarr would then write proper poster and fanart jpg onto that movie folder automatically.

I forgot to show the size because i had to do it quickly, but hopefully you get the idea, the first poster.jpg that i delete is the 0kb poster and then radarr would populate the folder with proper fanart and poster image.
So perhaps there's a duplicated poster copying process somewhere in the code that prevents radarr from generating proper poster size?

**Comment by FrankEBailey** [comment] 2021-07-04 11:25
Just to add another voice to the chorus, I'm experiencing the same issue on Windows 10 running Sonarr 3.2.2.5080 (latest current version AFAIK)

**Comment by bakerboy448** [comment] 2021-07-04 11:53
Unless asked... I don't believe we need to know that this is still occurring nor additional information at this time.

**Comment by Buster14** [comment] 2022-01-08 23:33
Hi, since its marked as stale, and the latest update is jjne 3 2021. Just want to report that its still happening on the latest version. Perhaps a bounty could be made for this issue?

**Comment by fangzhen2005** [comment] 2022-01-11 03:11
This problem still exists.

Version:3.2.2.5080
Package Version:3.2.2.5080-ls124 by linuxserver.io
.NET:Yes (5.0.5)
Docker:Yes
Database migration version:195

**Comment by fangzhen2005** [comment] 2022-01-11 03:17
> This problem still exists.
> 
> Version:3.2.2.5080 Package Version:3.2.2.5080-ls124 by linuxserver.io .NET:Yes (5.0.5) Docker:Yes Database migration version:195

2022-01-06 20:42:33.0|Info|AddMovieService|Adding Movie [Doctor Strange in the Multiverse of Madness (2022)][tt9419884, 453395] Path: [/movies/Doctor Strange in the Multiverse of Madness (2022)]
2022-01-06 20:42:33.1|Info|RefreshMovieService|Updating info for Doctor Strange in the Multiverse of Madness
2022-01-06 20:42:35.1|Info|MediaCoverService|Downloading Poster for [Doctor Strange in the Multiverse of Madness (2022)][tt9419884, 453395] https://image.tmdb.org/t/p/original/BAuj5e4pqMbLGVOci7B9abEto5.jpg
2022-01-06 20:42:35.1|Info|DiskScanService|Scanning disk for Doctor Strange in the Multiverse of Madness
2022-01-06 20:42:35.2|Info|DiskScanService|Completed scanning disk for Doctor Strange in the Multiverse of Madness
2022-01-06 20:42:35.2|Info|MovieScannedHandler|[Doctor Strange in the Multiverse of Madness] was recently added, performing post-add actions
2022-01-06 20:42:35.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
2022-01-06 20:42:35.2|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2022-01-06 20:42:35.2|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2022-01-06 20:42:35.2|Info|ExistingExtraFileService|Found 0 extra files
2022-01-06 20:42:35.3|Error|MetadataService|Couldn't download image /config/MediaCover/298/fanart.jpg for [Doctor Strange in the Multiverse of Madness (2022)][tt9419884, 453395]. Path doesn't exist!

[v3.2.2.5080] System.InvalidOperationException: Path doesn't exist!
   at Mono.Unix.UnixFileSystemInfo.AssertValid()
   at Mono.Unix.UnixFileSystemInfo.get_IsSymbolicLink()
   at NzbDrone.Mono.Disk.DiskProvider.CopyFileInternal(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 226
   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 230
   at NzbDrone.Core.Extras.Metadata.MetadataService.DownloadImage(Movie movie, ImageFileResult image) in D:\a\1\s\src\NzbDrone.Core\Extras\Metadata\MetadataService.cs:line 303


2022-01-06 20:42:35.5|Info|NzbSearchService|Searching 3 indexers for [Doctor Strange in the Multiverse of Madness]
2022-01-06 20:42:36.5|Info|MediaCoverService|Downloading Fanart for [Doctor Strange in the Multiverse of Madness (2022)][tt9419884, 453395] https://image.tmdb.org/t/p/original/zzFQk6KDMCIhXlUwrhbYTtx8tvA.jpg
2022-01-06 20:42:44.9|Info|DownloadDecisionMaker|No results found
2022-01-06 20:42:44.9|Info|MovieSearchService|Movie search completed. 0 reports downloaded.


three picture files are empty:
folder.jpg 0kb
poster.jpg 0kb
Doctor Strange in the Multiverse of Madness (2022) 0kb

**Comment by Buster14** [comment] 2022-01-31 08:23
Looks like it's fixed in 4.0, Just tested adding 3 new movies and all downloaded poster.jpg correctly. Kudos to the radarr team to solve this bug!

**Comment by bakerboy448** [comment] 2022-01-31 13:57
@SugarDroid can you confirm as well v4 fixed it?

**Comment by Qstick** [comment] 2022-01-31 15:59
Likely a result of the new http stack

**Closed** 2022-01-31 15:59 UTC
Labels: Type: Bug, Status: Cannot Reproduce, Status: Confirmed, Area: Extras

**Comment by Buster14** [comment] 2022-02-02 03:24
Sorry guys i'm not sure why,  but today i added House of Gucci and strangely on radarr it shows poster.jpg and fanart.jpg listed on the movie folder, 
and yet there's no file at all on that folder (besides the pending movie download of course).
And another thing i tried pressing refresh and scan several times but it wont download poster and fanart at all.. 
so in v4 now it's getting harder to generate poster in case it's missing.
I did no changes to the settings except i put "nonexistant" on the update choice cause i'd rather not update it thinking it was stable already

**Comment by bakerboy448** [comment] 2022-02-02 03:29
@Buster14 
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

The files listed by Radarr come directly from Radarr looking at the file system.

**Comment by Buster14** [comment] 2022-02-02 03:31
@bakerboy448  I found the source of the problem. updating to V4 reverts the database folder back to C, whereas in setup i set the database to other drive. Restarting the radarr service fixes this.

**Comment by bakerboy448** [comment] 2022-02-02 03:33
So you're saying when v3 updated itself to v4 it overwrote the service back to the defaults?

**Comment by Buster14** [comment] 2022-02-02 03:40
That's the strange part, i checked the radarr service and it's still pointing to Z:\Programs\Radarr\Radarr.Console.exe.
I came into the conclusion cause looking at the log radarr still points at C:\ProgramData\
But after looking at that folder i just remembered that i symlink'ed the C:\ProgramData\radarr  to Z folder as well (IIRC it was the only way to avoid radarr bloating the C folder), does it have anything to do with the old 0kb poster error?

**Comment by SugarDroid** [comment] 2022-03-06 22:15
> @SugarDroid can you confirm as well v4 fixed it?

Sorry for the late reply. I hope, but since it is not reproducible, I can only say that it has indeed not occurred recently.
