### ISSUE TITLE
Torrent Blackhole download client not working

### ISSUE THREAD

**Issue by iLc0** [Radarr/Radarr#310] opened 2017-01-17 20:05 UTC
Hello,

I cannot make "Torrent Blackhole" work. It says it's not configured for movies.

![image](https://cloud.githubusercontent.com/assets/15958336/22037682/7ad7b760-dcf8-11e6-88c9-473e75adbfe3.png)

What I'm trying to do is simply to have radarr download the torrent or magnet file to a specific folder. 

Here's the torrent blackhole config :

![image](https://cloud.githubusercontent.com/assets/15958336/22037747/b7ed4804-dcf8-11e6-9861-929ec9c04aba.png)

Thank you

**Comment by galli-leo** [comment] 2017-01-17 20:10
Duplicate of a very early issue. Blackhole is currently not supported.

**Closed by galli-leo** 2017-01-17 20:10 UTC
