### ISSUE TITLE
"Bulk Import Movies" option doesn't parse movies on the root selected directory

### ISSUE THREAD

**Issue by slavikme** [Radarr/Radarr#2673] opened 2018-03-25 17:35 UTC
**Description:**
I have recently discovered this amazing service, after using CouchPotato for years.
I have over 500 movies on my disk, when most of them are `mkv` and some `avi` and `mp4`.
I wanted to import all of my movies library to Radarr, in order to better manage them. So what I did was using the feature "Bulk Import Movies", but it seems like it is partially working.
My movie library is actually a directory with all of my movies, some of the movies are located directly in the root movies directory (e.g. `/Movies/Some.Movie.2017.BluRay.1080p.mkv`) and some movies are located in sub-directories (e.g. `/Movies/Another.Movie/Another.Movie.2018.BluRay.720p.mkv`).
It looks like the "Bulk Import Movies" feature only "sees" the movies located in the sub-directories (`/Movies/Another.Movie/`), but not directly in the root movies directory (`/Movies/`), so I was only been able to import some of the movies.
I tried to test this assumption by moving one movie into a sub-directory and I was right, I was eventually able to import the movie this way.

To me, it seems like a bug.

If you need any additional information, let me know.

**Radarr Version:**
0.2.0.995

**Note:**
I am using a Docker image [linuxserver/radarr](https://store.docker.com/community/images/linuxserver/radarr):latest from [Docker Hub](https://hub.docker.com/) / [Docker Store](https://store.docker.com/).

**Comment by galli-leo** [comment] 2018-03-26 12:44
Duplicate of #153

**Comment by galli-leo** [comment] 2018-03-26 12:44
Yeah bulk import only supports files in folders for now. When we rework radarr to allow files without folders, bulk import will get fixed as well.

**Closed by galli-leo** 2018-03-26 12:44 UTC

**Comment by jackyaz** [comment] 2018-12-22 11:38
@galli-leo Has any progress been made with this? 817 movies in the root folder, not found by bulk import :(

**Comment by galli-leo** [comment] 2018-12-24 13:58
@jackyaz https://blog.radarr.video/development/update/2018/11/11/roadmap-update.html
