### ISSUE TITLE
Pull watch providers from TMDb to get streaming sources

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#7931] opened 2022-12-27 01:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Its not that much data but I think it would be cool if Radarr could display this info just as a **list** right next to the cast and crew **tab**.  Thanks

### Describe the solution you'd like

https://developers.themoviedb.org/3/movies/get-movie-watch-providers

### Describe alternatives you've considered

https://developers.themoviedb.org/3/movies/get-movie-watch-providers

### Anything else?

.

[AB#4557](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4557)

**Comment by bakerboy448** [comment] 2022-12-27 01:27
Duplicate of several existing issues

**Closed by bakerboy448** 2022-12-27 01:27 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by ItsME6969** [comment] 2022-12-27 06:26
@bakerboy448 care to link one of them I maybe i'm searching wrong but I cant find any existing open or closed ones.
