### ISSUE TITLE
Norwegian is not truncated using {MediaInfo AudioLanguagesAll}

### ISSUE THREAD

**Issue by Jerrk** [Radarr/Radarr#4213] opened 2020-03-08 09:38 UTC
**Describe the bug**
On several items in radarr with Norwegian is not being truncated to NO and norwegian bokmål is not being truncated to NB (if we want to make the latter distinction).

**To Reproduce**
1. Go to settings -> media management -> standard movie format -> add {MediaInfo AudioLanguagesAll} to the field.
2. Import a movie with Norwegian(NOR) or Norwegian bokmal(NOB) among its audio languages
3. Go to the movie name and see error

**Expected behavior**
Norwegian should be truncated like all other languages

**Screenshots**
![](https://i.imgur.com/9eEp4iZ.png)
![](https://i.imgur.com/vC8ToSp.png)

**Desktop (please complete the following information):**
 - OS: Unraid 6.8.3
 - Version 3.0.0.2712

**Debug Logs**
debug log attached
[radarr log.txt](https://github.com/Radarr/Radarr/files/4303045/radarr.log.txt)

[AB#833](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/833)

**Comment by Qstick** [comment] 2020-03-11 04:16
This seems to be dependent on platform, we pull all cultures from System.Globalization.CultureInfo and do a lookup by EnglishName from mediainfo to get two digit iso code in fileNameBuilder.... on unraid I can reproduce this behavior for Norwegian meaning it’s not in the culture list, however on windows this works fine for me. So I think it’s a result of different cultures or some differences in culture naming on different platforms or .net versions. I think we should avoid the culture lookup (inherit from Sonarr) and just use two digit iso from mediainfo (part of mediainfo PR).

**Comment by Jerrk** [comment] 2022-03-06 17:29
Appears to have been fixed for me back in oct-nov 2021.
![](https://i.imgur.com/CwB1Hym.png)

currently on
unraid: 6.9.2
radarr: 4.1.0.5996-ls253 by [linuxserver.io](https://www.linuxserver.io/)

**Comment by bakerboy448** [comment] 2023-01-11 00:38
closing based on Jerrk's comment

**Closed by bakerboy448** 2023-01-11 00:38 UTC
Labels: Type: Bug, Area: Scanning
