### ISSUE TITLE
Radarr detect REMUX-1080p instead of REMUX-2160p

### ISSUE THREAD

**Issue by navycrow** [Radarr/Radarr#5598] opened 2020-12-22 07:04 UTC
**Describe the bug**
Radarr detect REMUX-1080p instead of REMUX-2160p

**Screenshots**
[https://ibb.co/hZRFDvM](https://ibb.co/hZRFDvM)

**Platform Information (please complete the following information):**
 - OS: QNAP
 - Docker: No
 - Mono or.NET Core Version: NET Yes (3.1.10)
 - Radarr Version 3.0.1.4260
 - Radarr Branch develop

**Comment by bakerboy448** [comment] 2020-12-22 12:05
@navycrow 

1) we don’t need the entire log file
2) don’t put the log in the GitHub body
3) that’s not a trace log
4) pretty sure that’s not a bug, but a trace log will help

please edit your post and get a proper trace log
https://wiki.servarr.com/Radarr_Troubleshooting#Logging_and_Log_Files

**Comment by Qstick** [comment] 2020-12-22 12:22
Logs cleaned out, based on the screenshot it’s parsed incorrectly.

**Comment by bakerboy448** [comment] 2020-12-22 15:10
Not sure this is a bug exactly...more of a poorly named release

https://github.com/Radarr/Radarr/blob/eb5add11988671b29ce6faf3011b44522fd82ca6/src/NzbDrone.Core/Parser/QualityParser.cs#L59

`[Dolby Vision A.Star.Is.Born.MULTi.TRUEFRENCH.UHD.4K.BLURAY.REMUX.DoVi-KLP33` would work as "4K" is Required
`[Dolby Vision A.Star.Is.Born.MULTi.TRUEFRENCH.UHD.BLURAY.REMUX.DoVi-KLP33` does not.

I'm not sure if that this poorly named release name can properly be accounted for.

Do you have mediainfo to confirm it is actually 2160p?

**Comment by bakerboy448** [comment] 2020-12-22 15:20
Closing;

Working as expected; the parser is operating in a conservative manner.

the parse does assume worst possible resolution for a group of it's not specific.

I don't see an easy way to handle a poorly named release without causing other issues.
Theoretical fix:
`\b(?:(?<R360p>360p)|(?<R480p>480p|640x480|848x480)|(?<R576p>576p)|(?<R720p>720p|1280x720)|(?<R1080p>1080p|1920x1080|1440p|FHD|1080i)|(?<R2160p>2160p|4k[-_. ](?:UHD|HEVC|BD)|(?:UHD|HEVC|BD)([-_. ]4k|[-_. ]BluRay)))\b`
![image](https://user-images.githubusercontent.com/55419169/102904145-ea9ccf00-4436-11eb-966c-069abf80e53a.png)

**Closed by bakerboy448** 2020-12-22 15:20 UTC
Labels: bug, information needed

**Comment by navycrow** [comment] 2020-12-22 18:12
Here is the media info :
Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 15 min
Bit rate                                 : 45.6 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.229
Stream size                              : 43.2 GiB (79%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 671 cd/m2
Maximum Frame-Average Light Level        : 310 cd/m2
Original source medium                   : Blu-ray

**Comment by bakerboy448** [comment] 2020-12-22 20:06
group needs to name their releases according to standards then.  If it's 4k it needs to be indicated as such.

UHD by itself is not enough to assume 4k all the time.

**Comment by navycrow** [comment] 2020-12-22 21:00
`UHD by itself is not enough to assume 4k all the time.` 
??? What is UHD then ?? For me UHD, 4k and 2160p are the same. What's the difference ?

**Comment by bakerboy448** [comment] 2020-12-22 21:01
see my other comment with the screenshots/examples
it could be a 1080 release sourced from a UHD release

**Comment by navycrow** [comment] 2020-12-23 06:34
i agree. It can be a 1080 release sourced from a UHD release...
but in my case it's a UHD BLURAY REMUX, it can't be 1080p because it's a REMUX (so without modifications)
