### ISSUE TITLE
Selectable import lists to mass change information (mostly root paths)

### ISSUE THREAD

**Issue by Glynax** [Radarr/Radarr#8008] opened 2023-01-17 21:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've just updated my root paths which was simple enough to update collections and the movies themselves, but there is no way to multi select or select all import lists (I have many dozens) and update the now broken root paths.

### Describe the solution you'd like

Ideally it would work exactly like updating collections and movies, just being able to tick each box or select boxes to mass update certain fields for the import lists.

### Describe alternatives you've considered

I considered using the API for this but really how often am I going to have to do this.

### Anything else?

Nope

[AB#4755](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4755)

**Comment by bakerboy448** [comment] 2023-01-17 22:13
Duplicate of #7397

**Closed by bakerboy448** 2023-01-17 22:13 UTC
Labels: Type: Feature Request, Status: Needs Triage
