### ISSUE TITLE
Folder with Movie Title not having the same Movie Title Language

### ISSUE THREAD

**Issue by Aurel004** [Radarr/Radarr#4345] opened 2020-04-23 23:16 UTC
**Describe the bug**
My movies are in french and the folder that contains the movie is in English whereas the title of the file is in French.

Might seem a little bug but it's very boring with plex as it uses the folder title, so all my movies are with an english title.

**To Reproduce**
1. Download a movie not in English (having french title for example)
2. watch folder name and .mkv file name

**Expected behavior**
Having the french title on bot folder and file.

**Desktop (please complete the following information):**
 - OS: Synology
 - Mono Version: 5.20.1.34
 - Version 0.2.0.1480

**Debug Logs**
[radarr.debug.0.log](https://github.com/Radarr/Radarr/files/4525761/radarr.debug.0.log)

**Comment by Qstick** [comment] 2020-04-25 14:40
Duplicate of about three other issues, working on fixing in v3

**Closed by Qstick** 2020-04-25 14:40 UTC
Labels: bug
