### ISSUE TITLE
Download trailer for each movie.

### ISSUE THREAD

**Issue by super94i** [Radarr/Radarr#1835] opened 2017-07-26 04:38 UTC
I really want this feature to be implemented. I tried the "tinyMediaManager" but the "download trailers" is a donators feature and it's not free. https://www.tinymediamanager.org/blog/trailer-download-donator-feature/

I'm sure that so many people want this feature to be implemented. At least if we can have a script that lets me download trailers for all the movies in my library, that would be so helpful.

Thanks.

**Comment by hotio** [comment] 2017-07-26 10:22
http://radarr.video/donate.html

You can be helpful too if you want...

**Comment by galli-leo** [comment] 2017-07-26 21:46
Duplicate of #494. There surely are scripts already out there for this :) Try connecting them via connections.

**Closed by galli-leo** 2017-07-26 21:46 UTC

**Comment by myron0815** [comment] 2017-07-27 15:22
Blog post is 3 years old - didn't you try it with a recent version?!
;)

**Comment by super94i** [comment] 2019-06-30 09:46
Hey, Could you please delete this issue? I would really appreciate it!
