### ISSUE TITLE
Show missing Collection Items

### ISSUE THREAD

**Issue by YouveGotMeowxy** [Radarr/Radarr#7129] opened 2022-03-11 21:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not a "problem", per se.

### Describe the solution you'd like

It would be most delicious ;) if Radarr would do what the "[GAPS](https://github.com/JasonHHouse/gaps)" app is supposed to do; which is to search your library and if any of the movies are part of a collection/series it'll show you which ones are missing and suggest/make it easy to download them so the collection is complete.

It seems like a very natural fit for Radarr, as it already catalogs your movies, has the ability to search and send to the downloaders, and Sonarr already does this for tv shows that are missing. It would also be great to not have to run yet another container (and its resources) just for a single feature.

Also, the Gaps dev is super slow, and it cant even connect using SSL, even though the dev has said it's been at the top of his todo list for at least 2 years now. Radarr can already connect using SSL.

It would also be much nicer on the eyes looking at it in the pretty Radarr app compared to the relatively bare and basic Gaps app.

### Describe alternatives you've considered

 I've searched and asked around but there's apparently no alternatives to Gaps.

### Anything else?

Pretty please with sugar on top??? lol

[AB#2787](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2787)

**Comment by bakerboy448** [comment] 2022-03-11 22:48
Duplicate of https://github.com/Radarr/Radarr/issues/6861

**Closed by bakerboy448** 2022-03-11 22:48 UTC
Labels: Type: Feature Request, Status: Needs Triage
