### ISSUE TITLE
Download 2 files

### ISSUE THREAD

**Issue by lanarchy** [Radarr/Radarr#2882] opened 2018-07-12 02:17 UTC
I would like an option to download 2 quality profiles for the same movie. Or perhaps an option inside the profile itself, I'm not sure which is easier to implement. Such as if I download 4k, I want to also download bluray-720 and store it in the same folder along side the 4k one, since it is faster and higher quality than waiting for Handbrake to re-encode it for crappy upload bandwidth sharing.

**Comment by Qstick** [comment] 2018-07-13 23:38
Dupe of #1910 and #2203

**Closed by Qstick** 2018-07-13 23:38 UTC
