### ISSUE TITLE
Ability to edit "Also known as" list

### ISSUE THREAD

**Issue by seannymurrs** [Radarr/Radarr#3361] opened 2019-02-10 20:40 UTC
**Is your feature request related to a problem? Please describe.**
For many movies in my wanted list, there are incorrect and sometimes seemingly random things listed under the "Also known as" list. I've checked on TMDB, and these names are not listed. It seems like Radarr is using a cached version of the list that is outdated, and there is no way to remove these false entries.

**Describe the solution you'd like**
I'd like to be able to manually go in and remove some of these entries, or somehow trigger a forced refresh of the list.

**Describe alternatives you've considered**
See the alternative mentioned above.

**Additional context**
N/A

**Comment by fryfrog** [comment] 2019-02-18 01:45
@galli-leo, maybe the cache isn't updating properly? Can you give some examples so we can look and verify?

**Comment by galli-leo** [comment] 2019-02-18 10:28
Duplicate of #2866

The AKA list should have a field that says the source. Maybe it's from our mappings server? Also yeah TMDB caches them and Radarr as well.

**Closed by galli-leo** 2019-02-18 10:28 UTC
