### ISSUE TITLE
Some movies after adding to raddar are shown as added but gives 404 error

### ISSUE THREAD

**Issue by dm3ch** [Radarr/Radarr#4078] opened 2020-01-17 21:38 UTC
**Describe the bug**
For some movies I have a problem that movie is marked as added in search but when I'm trying to open it - i'm getting 404 error.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://paste.pics/027adeffdba2fcdeda2af7b5dbdaae1e
https://paste.pics/a9dea4dacb0720f51ad7f809fb6d7911

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Linux
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status) 
 .NET Cire 3.0.0.2532
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues) Chrome

Version: 0.2.0.1450
Image: linuxserver/radarr:preview

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

Here's a debug logs that are generated during attempt to open movie page:
```
2020-1-17 21:36:14.7|Debug|Api|[GET] /api/v3/exclusions: 200.OK (1 ms)
2020-1-17 21:36:14.7|Debug|RootFolderService|Generating list of unmapped folders
2020-1-17 21:36:14.7|Debug|RootFolderService|0 unmapped folders detected.
2020-1-17 21:36:14.7|Debug|RootFolderService|Generating list of unmapped folders
2020-1-17 21:36:14.7|Debug|RootFolderService|0 unmapped folders detected.
2020-1-17 21:36:14.7|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (25 ms)
2020-1-17 21:36:15.0|Debug|Parser|Parsing string 'konosuba'
2020-1-17 21:36:15.0|Debug|Parser|Unable to parse konosuba
2020-1-17 21:36:15.2|Debug|Api|[GET] /api/v3/movie/lookup?term=konosuba: 200.OK (215 ms)
```

And here's an URL that Radarr tries to open (browser redirected to this URL when I'm trying to open movie form search) https://some.host/radarr/movie/konosuba-gods-blessing-on-this-wonderful-world-legend-of-crimson-532067

**Comment by Qstick** [comment] 2020-01-17 23:03
Dupe of #3796 or #2275

**Closed** 2020-01-17 23:04 UTC
Labels: bug
