### ISSUE TITLE
Wrong Original Movie Language

### ISSUE THREAD

**Issue by kindofausername** [Radarr/Radarr#8002] opened 2023-01-15 11:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

As I read radarr gets the original movie language from themoviedb. But for some movies the original movie language is wrong in radarr except the original movie language is correct on tmdb and imdb.

E.g. Hong Kong Family
https://www.themoviedb.org/movie/1021734-hong-kong-family
shows the movies Original Language as Cantonese (same on https://www.imdb.com/title/tt22398080/).

But radarr adds the movie with english as original language.

### Expected Behavior

Add the movie with the correct original language into radarr using the information from themoviedb.

### Steps To Reproduce

1. Import Hong Kong Family to radarr.
https://www.themoviedb.org/movie/1021734-hong-kong-family
https://www.imdb.com/title/tt22398080

2. Check language of movie in radarr. Should be Cantonese. But English will be shown.

### Environment

```markdown
- OS: Linux
- Radarr: 4.3.2.6857 / 4.3.2.6857-ls159 by linuxserver.io
- Docker Install: linuxserver.io
- Using Reverse Proxy: no
- Browser: any
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

![Untitled 2](https://user-images.githubusercontent.com/22766495/212538201-9f690e74-57ea-4ff6-9949-5bacd7ae8bd1.jpg)

[AB#4739](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4739)

**Comment by bakerboy448** [comment] 2023-01-15 15:17
Duplicate of #5970

**Closed by bakerboy448** 2023-01-15 15:17 UTC
Labels: Type: Bug, Status: Needs Triage
