### ISSUE TITLE
Request body too large

### ISSUE THREAD

**Issue by ryguy781** [Radarr/Radarr#5778] opened 2021-01-18 16:04 UTC
**Describe the bug**
Restoration of database fails.  Results in "Request body too large" error

**To Reproduce**
Moving Radarr installation from Synology Docker to MacMini
Backed up docker database (v3.0.1.4259) via GUI interface 
Downloaded .zip file
attempted to restore database on new installation via GUI on MacMini (v3.0.1.4259)
Interface does not appear to respond, other than placing a X by the "Restore" in the dialog box
Log file indicates:
2021-1-18 09:17:30.6|Error|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HM5ROEN8FQJ2", Request id "0HM5ROEN8FQJ2:00000008": An unhandled exception was thrown by the application.
[v3.0.1.4259] Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large.

**Expected behavior**
The restoration process will completed, the GUI will restart and the database information will display on the new installation just as it is on the old installation.

**Screenshots**

**Platform Information (please complete the following information):**
Source
 - OS: Synology Docker
 - Docker: Yes
 - Mono or.NET Core Version: .Net Core (3.1.10)
 - Browser and Version Chrome V87.0.4280.141
 - Radarr Version 3.0.1.4259 (3.0.1.4259-ls89 by linuxserver.io)
 - Radarr Branch latest

Destination
 - OS: MacOS 10.15.7
 - Docker: No
 - Mono or.NET Core Version: .Net Core (3.1.10)
 - Browser and Version Chrome V87.0.4280.141
 - Radarr Version 3.0.1.4259 
 - Radarr Branch NA

[radarr.txt](https://github.com/Radarr/Radarr/files/5831259/radarr.txt)

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment] 2021-01-18 16:19
Duplicate of #5593

Fix is in Develop

**Closed by bakerboy448** 2021-01-18 16:19 UTC
