### ISSUE TITLE
Filenames are wrong movie

### ISSUE THREAD

**Issue by reloxx13** [Radarr/Radarr#7243] opened 2022-04-24 08:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Movies get matches correctly, but the movie title in the file name is a wrong movie which has nothing to do with the imported movie. 

rename doesnt change anything.

happened since yesterdays nightly update to many movies.   
this worked for many months before and stopped working over night.    

Filename pattern: `{Movie CleanTitle:DE} ({Release Year}) - {[EDITION TAGS]}{[Custom Formats]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{MediaInfo AudioLanguages}{[MediaInfo VideoDynamicRange]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}`

![grafik](https://user-images.githubusercontent.com/14855001/164967164-26ae71ad-dbd9-41a1-8e33-0426e84ba2f5.png)

### Expected Behavior

movie title in file name is same as matched movie.

### Steps To Reproduce

import movie
check filename

### Environment

```markdown
- OS: win10x64
- Radarr: 4.2.0.6229
```

### What branch are you running?

Nightly

### Trace Logs?

if u want logs, add optional anonymize them without full paths, usernames, ips, network device names, movie names/release details.

this is all i could find in logs to the movie in this example.

`2022-04-24 09:41:00.0|Info|MovieService|Assigning file [Countdown (2018) - [:::::::::].mkv] to movie [[Ready Player One (2018)][tt1677720, 333339]]`

[AB#3035](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3035)

**Comment by ta264** [comment] 2022-04-24 08:27
Without trace logs this is not going to get any attention, no other reports of these issues makes me think it's an issue with your setup

**Comment by reloxx13** [comment] 2022-04-24 08:27
this is a bug not support

could be related to 6a03eddda96f17cb46867da8147d6ab271906fac

**Comment by RobinDadswell** [comment] 2022-04-24 08:34
> Without anomized logs, u r not going to get logs.

The logs are already cleansed for private information

**Comment by reloxx13** [comment] 2022-04-24 09:29
Renaming older correct movies will also result in the orginal english title as filename and is ignoring country title `Movie CleanTitle:DE`.

**Comment by bakerboy448** [comment] 2022-04-24 13:07
Again, no logs = invalid bug report that will not be investigated.

**Comment by sarakha63** [comment] 2022-04-25 18:53
I can confirm the issue since Yesterday.

1) Search with french language (on my side) gives Always a dumb result as a first result which is totally another movie

2) rename ignores the clean title fr and renames with the english title now

3) all release are ignores with the log "not matching titles" as the french title seems ignored


This was working perfectly until Yesterday's update.

**Comment by bakerboy448** [comment] 2022-04-25 18:56
@sarakha63 without the appropriate trace logs and a valid bug report nothing will be looked into.

"Yesterday" is meaningless

Your issues are also not what OP reported.

**Comment by sarakha63** [comment] 2022-04-25 18:58
I will dig into the logs once im in front of the computer

I think that this is related to the recent metadata rework.

**Comment by bakerboy448** [comment] 2022-04-25 19:00
> I think that this is related to the recent metadata rework.

Agreed. Probably some search logic was missed in the conversion or something;  also best to swing by discord to work on pinning it down.

**Comment by sarakha63** [comment] 2022-04-25 19:02
Im actually driving. I will try to help the best i Can tomorrow (french Time) and why not post on the discord

**Comment by reloxx13** [comment] 2022-04-26 19:21
Moving a movie with the mass movie editor will also result in wrong movie (titlename) folders but the file name stays correct.
    
    
> Your issues are also not what OP reported.   
    
https://github.com/Radarr/Radarr/issues/7243#issuecomment-1107801785

**Comment by Qstick** [comment] 2022-04-27 00:27
@reloxx13 thanks for reporting, should be fixed in next build

**Closed** 2022-04-27 00:27 UTC
Labels: Status: Info Needed, Type: Support.
