### ISSUE TITLE
Possibility of automatic download of trailers using the Youtube data?

### ISSUE THREAD

**Issue by minakitty** [Radarr/Radarr#3984] opened 2019-12-21 07:10 UTC
**Is your feature request related to a problem? Please describe.**
Not that I know of

**Describe the solution you'd like**
After transferring a movie from the download client to the storage location, use the Trailer data (presumably accessed by TMDB?) to optionally also download the trailer (using youtube-dl) and add it to the directory structure

**Describe alternatives you've considered**
Only other option I know is manually getting trailers for every movie

**Additional context**
Suggesting in context with Emby, which has the ability to read trailers from the movie directory, i.e.

- Movie/It's a Wonderful Life (1946)/It's a Wonderful Life (1946).mp4
- Movie/It's a Wonderful Life (1946)/It's a Wonderful Life (1946)-trailer.webm

This feature not only shows the trailer as a viewing option in Emby, but certain plugins can play random trailers as previews as though in a movie theater before the main attraction

**Comment by Qstick** [comment] 2019-12-21 12:27
Dupe of #494

**Closed by Qstick** 2019-12-21 12:27 UTC
Labels: feature_request
