### ISSUE TITLE
Minor change to import screen - make it easier to import

### ISSUE THREAD

**Issue by PeterKse** [Radarr/Radarr#5431] opened 2020-11-29 23:14 UTC
**Is your feature request related to a problem? Please describe.**

When importing movies, and especially when there are large (+10) quantities in a folder you end up having to ping-pong the eyes from left most column (FOLDER) and the right most column (MOVIE). 

It's not very 'ergonomic', to go through this check just to see if the parser have identified the movies correctly so i can press import. Actual physical pain in the eyes after you've gone through a few rows.

****Describe the solution you'd like****

Put FOLDER and MOVIE column neext to each other. I believe most people import with the quality/avail/monitor columns unchanged. And if they do change, well then they are still unaffected since at that speed you slowly go row by row, and not ping-pong your eyes back and forth until your brain hurts 👍

**Comment by bakerboy448** [comment] 2020-11-29 23:16
Duplicate of #5075

**Closed by bakerboy448** 2020-11-29 23:16 UTC
Labels: feature request
