### ISSUE TITLE
Error parsing column 45 (Language=31 - Int64) on roll back to latest

### ISSUE THREAD

**Issue by Turnipisum** [Radarr/Radarr#6065] opened 2021-03-18 00:43 UTC
**Describe the bug**
Error parsing column 45 (Language=31 - Int64) on roll back to latest

**To Reproduce**
1. Radarr on setup latest
2. Radarr setup from :nightly tag
2. roll back to latest
3.  then get the "error Error parsing column 45 (Language=31 - Int64)" when web ui is open

![image](https://user-images.githubusercontent.com/23130067/111556443-88780f80-8782-11eb-9593-fc6a02653f8c.png)

**Platform Information (please complete the following information):**
Version 3.0.2.4552
Package Version 3.0.2.4552-ls97 by linuxserver.io
.NET Core Yes (3.1.10)
Docker Yes
Mode Console

**Trace Logs**
[v3.0.2.4552] System.Data.DataException: Error parsing column 45 (Language=31 - Int64)

**Comment by bakerboy448** [comment] 2021-03-18 00:44
Closing.

not a bug. Expected behavior

you cannot go back to develop or master at this time 

https://wiki.servarr.com/Radarr_FAQ#can_i_switch_between_branches

**Closed by bakerboy448** 2021-03-18 00:44 UTC
Labels: Type: Bug
