### ISSUE TITLE
Radarr gets confused with sequels

### ISSUE THREAD

**Issue by Crowley007** [Radarr/Radarr#8130] opened 2023-02-17 07:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I tried to Download every "Friday the 13th" Movie. Radarr tried to match most of the sequels with the First one, and part 8 got imported to the first's directory. Many Sequels did not get imported at all, had to do it manually. 

### Expected Behavior

Every sequel imported, in the proper diriectory. All releases do have subtitles, years and roman numbers so not sure why radarr gets confused.

### Steps To Reproduce

Add every Friday the 13th Movie and search for them.

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Radarr: 4.4.2.6956
```

### What branch are you running?

Develop

### Trace Logs?

Easy to reproduce

**Comment by Crowley007** [comment] 2023-02-17 08:01
Ok, search fail, sorry. This seems to be already reported years ago: https://github.com/Radarr/Radarr/issues/6088

**Comment by bakerboy448** [comment] 2023-02-17 09:30
Duplicate of #6088

**Closed by bakerboy448** 2023-02-17 09:30 UTC
Labels: Type: Bug, Status: Needs Triage
