### ISSUE TITLE
issue with renaming, incorrect codec and channels applied

### ISSUE THREAD

**Issue by RobinMM** [Radarr/Radarr#6383] opened 2021-06-09 11:40 UTC
Hi there,

When using media rename functionality, E-AC3 DD+7.1 audio tracks get renamed to AC3 5.1 instead of E-AC3 7.1

**To Reproduce**
Rename a MKV file with Radarr that has an E-AC3 DD+7.1 audiotrack

**Expected behavior**
I expect the filename after renaming to contain E-AC3 7.1

**Pastebin**
For complete audio track media info visit: https://pastebin.com/PuGrJQJs

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Radarr Version: 3.2.2.5080

**Comment by RobinDadswell** [comment] 2021-06-09 11:41
Please search Github issues before opening an issue 

Duplicate of #6057

**Closed by RobinDadswell** 2021-06-09 11:41 UTC
Labels: Type: Bug

**Comment by RobinMM** [comment] 2021-06-09 11:51
@RobinDadswell Thank you for your response. I have searched for similar, but apparently not good enough, sorry for that!
