### ISSUE TITLE
Calendar Should only show certain types releases (I.E. cinema, physical, digital)

### ISSUE THREAD

**Issue by Tyrant-24** [Radarr/Radarr#8023] opened 2023-01-23 12:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I rarely go to the cinema, so seeing cinema release dates don't really do anything for me. I export my calendar to my email and when I see it on my phone they is no way of differentiating them.

### Describe the solution you'd like

It would help me if the calendar only showed certain types releases. I would like to leave out cinema release dates. 

### Describe alternatives you've considered

I could try practicing selective vision, but the above seems easier.

### Anything else?

Just kidding about alternatives I've considered. They (the git hub ) forced me to do it by not allowing me to leave it blank

[AB#4792](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4792)

**Comment by RobinDadswell** [comment] 2023-01-23 12:38
Duplicate of #7327

**Closed** 2023-01-23 12:39 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by Tyrant-24** [comment] 2023-01-23 16:34
Sorry for the duplication. I Searched with calendar and nothing came up.
