### ISSUE TITLE
404 favicon not found when using UrlBase

### ISSUE THREAD

**Issue by apwelsh** [Radarr/Radarr#5806] opened 2021-01-24 01:44 UTC
**Describe the bug**
When using a reverse proxy, the UrlBase is required to map different site to a single host/url as is normal.  the favicon reference should be redirected to the UrlBase root instead of the host root is UrlBase is defined.

**To Reproduce**
Open application, and begin a web inspector.  Start network monitoring and view console, or network log of the browser.  The error is reported on every attempt to launch the application when accessed through the reverse proxy.

**Expected behavior**
No 404 errors should be returned for normal operations.

**Screenshots**
Not applicable

**Platform Information (please complete the following information):**
 - OS: NA
 - Docker: NA
 - Mono or .NET Version (System -> Status): NA
 - Browser and Version (Only needed for UI issues): NA
 - Radarr Version: latest (as published via linux server.io docker image)
 - Radarr Branch: master

**Trace Logs**
Not applicable

**Comment by bakerboy448** [comment] 2021-01-30 21:44
"latest" is not a version; it is a branch

Latest, assuming you are current, is 3.0.1.4259

Could not reproduce on nightly

@Qstick I'm thinking 140547e42a32cbaf80e7a794c5be9bfb574e97a2 fixed it?

**Comment by Qstick** [comment] 2021-01-31 07:18
Closing lack of template info

**Closed by Qstick** 2021-01-31 07:18 UTC
Labels: Status: Info Needed, Type: Bug
