### ISSUE TITLE
Dark Theme: File Name Token modal naming options not darkening.

### ISSUE THREAD

**Issue by iarp** [Radarr/Radarr#8170] opened 2023-03-02 01:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Change to Dark theme or have it auto set to dark via browser settings, go to Settings -> Media Management -> Standard Movie Format as well as Movie Folder Format -> Click on the blue ?. 

The File Name Tokens modal appears. NamingOption-token and NamingOption-example are set to `background: #eee` and `#ddd` within the NamingOption.css file. This clashes with the dark theme and its impossible to read without switching to light theme.

### Expected Behavior

Background colours should not be light.

### Steps To Reproduce

Settings
UI
Style -> Theme -> Dark
Settings
Media Management
Standard Movie Format -> Blue ? at end of text box
NamingOption boxes are all currently set to background eee and ddd.

### Environment

```markdown
- OS: unraid
- Radarr: 4.3.2.6857
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 110.0 (64-bit)
- Database: sqlite
```

### What branch are you running?

Master

### Trace Logs?

![tokens](https://user-images.githubusercontent.com/2169438/222307309-5adc57fc-83be-40a5-aa0a-2f22f75ff3d0.png)

**Comment by bakerboy448** [comment] 2023-03-02 01:32
Duplicate of https://github.com/Radarr/Radarr/issues/8001

**Closed by bakerboy448** 2023-03-02 01:32 UTC
Labels: Type: Bug, Area: UI, Type: Duplicate
