### ISSUE TITLE
adding rotten tomatoes link to movies

### ISSUE THREAD

**Issue by shoegazer47** [Radarr/Radarr#10188] opened 2024-07-19 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

![Screenshot 2024-07-19 105157](https://github.com/user-attachments/assets/bb3b5746-c412-4cd2-9226-7b0ae3ba2f21)

not a problem, just a feature request

### Describe the solution you'd like

adding a link to a movie rotten tomatoes page and the audience score in the movie page in radarr alongside the critics score

### Describe alternatives you've considered

i search the name of the movie on google and find the rotten tomatoes page

### Anything else?

not at all, keep up the good work!

**Comment by bakerboy448** [comment] 2024-07-19 11:08
Duplicate of https://github.com/Radarr/Radarr/issues/6764

**Comment by bakerboy448** [comment] 2024-07-19 11:09
> I have searched the existing open and closed issues

Please don't check the box when it's appear any you likely didn't actually search...

**Closed by bakerboy448** 2024-07-19 11:08 UTC
Labels: Type: Feature Request, Status: Needs Triage
