### ISSUE TITLE
Force download fails to do anything

### ISSUE THREAD

**Issue by BaneOfSerenity** [Radarr/Radarr#2478] opened 2018-02-04 14:56 UTC
Similar to issue #2173
Running Radarr Version: 0.2.0.910
I'm trying to download Mad Max 2: The Road Warrior
When trying to download i get http://prntscr.com/i9yvhy
So i figured lets just tell it to force download as the movie.
I click on the icon, select Force Download, spins a little bit and i get nothing. Log entry that gets created is below.
Log output: https://gist.github.com/BaneOfSerenity/16ea6286d2d33255cf77af7e3ee4cdd2

**Comment by galli-leo** [comment] 2018-02-04 15:35
Duplicate of #2477

**Closed by galli-leo** 2018-02-04 15:35 UTC

**Comment by WoLpH** [comment] 2018-03-06 11:41
Even though the related (#2477) error has been fixed, this issue still seems to exist @galli-leo 
After a very long time the `alttitle` API call responds with a 500 response:
```
{
  "message": "Error while calling api: Internal Server Error\nFull error(s): Internal Server Error (500, RayId: e933634f-505f-427f-85fe-ce37493788ae), Details: An error has occurred and this resource cannot be displayed.",
  "description": "NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Internal Server Error\nFull error(s): Internal Server Error (500, RayId: e933634f-505f-427f-85fe-ce37493788ae), Details: An error has occurred and this resource cannot be displayed.\r\n   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.Execute[T](HttpRequest request) in C:\\projects\\radarr-usby1\\src\\NzbDrone.Core\\MetadataSource\\RadarrAPI\\RadarrAPIClient.cs:line 77\r\n   at NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIClient.AddNewAlternativeTitle(AlternativeTitle title, Int32 TmdbId) in C:\\projects\\radarr-usby1\\src\\NzbDrone.Core\\MetadataSource\\RadarrAPI\\RadarrAPIClient.cs:line 159\r\n   at NzbDrone.Api.Movies.AlternativeTitleModule.AddTitle(AlternativeTitleResource altTitle) in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\Movies\\AlternativeTitleModule.cs:line 44\r\n   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\REST\\RestModule.cs:line 161\r\n   at CallSite.Target(Closure , CallSite , Func`2 , Object )\r\n   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)"
}
```

**Comment by galli-leo** [comment] 2018-03-06 12:28
Webhost making problems again

**Comment by WoLpH** [comment] 2018-03-06 12:32
Ah, I see. With the amount of calls... not surprising I suppose.

Perhaps a nice workaround for all of the load issues would be to (ab)use github for the actual reading/searching (i.e. on update push a file to a github repo). That's what many other projects do these days, seems to work just fine :)

**Comment by galli-leo** [comment] 2018-03-06 12:37
Well, the api is needed for other stuff as well, so not really a solution
