### ISSUE TITLE
Start search for missing movie doesn't grab a release when "Monitor" is set to "None" in the Add New Movie window.

### ISSUE THREAD

**Issue by jvgoch** [Radarr/Radarr#7794] opened 2022-11-27 04:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I add a movie without monitoring (because I don't want upgrades for this specific movie) and check the "Start search for missing movie" box, it does a search for the movie but it doesn't actually grab a release.

### Expected Behavior

When I check the "Start search for missing movie" checkbox I'd expect it to grab a release whether it is monitored or not.

### Steps To Reproduce

1. Add new movie
2. In the Add New Movie window set Monitoring to None and check the Start search for missing movie option
3. Radarr doesn't grab a release even though I asked nicely :(

### Environment

```markdown
- OS: Unraid OS 6.11.1
- Radarr: 4.2.4.6635-ls157 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No 
- Browser: Firefox 107.0 (64-bit) | Chrome 107.0.5304.122 (64-bit) | nzb360 v15.8.3 (app)
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/10097497/radarr.trace.txt)

[AB#4198](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4198)

**Comment by bakerboy448** [comment] 2022-11-27 04:06
- manually triggered searches ignoring monitored status was added with https://github.com/Radarr/Radarr/commit/4d70798f2ff070df04b2a29886325cf8aaf58d6d
- but based on this GHI it'd appear the search on add movie logic doesn't treat the command as manual

**Comment by bakerboy448** [comment] 2023-04-06 13:31
Duplicate of #1651

**Closed by bakerboy448** 2023-04-06 13:31 UTC
Labels: Type: Bug, Status: Confirmed
