### ISSUE TITLE
Movie profile not getting updated 

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#657] opened 2017-02-08 08:57 UTC
So I have noticed that when a movie gets downloaded and gets moved to its folder, the profile itself does not get updated. 

Here is an example.

Manchester By the Sea was grabbed, as you can see in the screenshot

![image](https://cloud.githubusercontent.com/assets/18261123/22729466/b5721910-ed97-11e6-9afc-3243378d1ea5.png)

Here is the folder, as you can see its not missing.

![image](https://cloud.githubusercontent.com/assets/18261123/22729494/d5281e3a-ed97-11e6-8c3a-1d30e7af0e27.png)

So i click on the Update movie info and scan disk

![image](https://cloud.githubusercontent.com/assets/18261123/22729698/b1ebf3b4-ed98-11e6-8fd2-6abf63c6fd67.png)

![image](https://cloud.githubusercontent.com/assets/18261123/22729741/e8a6adb8-ed98-11e6-8c14-c2f93d770b13.png)

and now its fixed!!

![image](https://cloud.githubusercontent.com/assets/18261123/22729814/32be72dc-ed99-11e6-9418-8893a4670035.png)

I'm guessing this is what this task is suppose to do right, maybe this is a known issue? (Sorry if it is) 

![image](https://cloud.githubusercontent.com/assets/18261123/22729853/5b3cadaa-ed99-11e6-9f63-c222d116ff1c.png)

**Comment by galli-leo** [comment] 2017-02-08 09:28
Have you tried reloading the page? I think it's an error where a downloaded movie does not correctly tell the web UI it finished.

**Comment by madvtak** [comment] 2017-02-08 09:30
This has been sitting here for maybe half the day, i noticed it in my Plex as a new movie. But i went to check Radarr it was still showing that it was missing. Before i posted this, ran the update for the latest build. No change.

**Comment by drafie** [comment] 2017-02-16 20:23
I confirm the same issue - movies imported from disk sometimes show up as MISSING, despite the fact that they are present on the disk and were imported from the disk.  I've verified that Radarr has access to the movie's directory.

Clicking the refresh button doesn't find the missing movie.

**Comment by diedrichg** [comment] 2017-02-27 19:36
Same issue. File shows as downloaded but the Missing tag is still present.

![2017-02-27 14_35_21-miss peregrine s home for peculiar children - radarr](https://cloud.githubusercontent.com/assets/9559987/23376420/0214c620-fcfa-11e6-8e1b-624f34fe6e24.png)

**Comment by onedr0p** [comment] 2017-03-08 05:23
That movie doesn't show as downloaded..?

**Comment by drafie** [comment] 2017-03-08 05:32
Here is the interesting thing about this  - this particular movie has been downloaded multiple times by Radarr, renamed properly, moved into the directory and the old movie deleted. 

Yet, it still shows 0B and Missing.

![image](https://cloud.githubusercontent.com/assets/808640/23691481/4a4c4888-038e-11e7-9c8a-0c9210b1d4fb.png)

**Comment by onedr0p** [comment] 2017-03-08 05:47
I think that is because of the bug with proper/repacks being downloaded when found. Does it happen with other releases?

**Comment by drafie** [comment] 2017-03-08 07:31
@onedr0p Yes, same thing here.   Again, it has download a few different copies.  It has renamed them.  Deleted the old one.  I can confirm the file is within the directory.

![image](https://cloud.githubusercontent.com/assets/808640/23694342/fec44a8a-039e-11e7-88a2-127b554a15e1.png)

**Comment by onedr0p** [comment] 2017-03-08 13:36
What is the cutoff, can you attach a screenshot of your 'any' profile?

**Comment by drafie** [comment] 2017-03-08 18:30
@onedr0p Sure, here you go.  

![image](https://cloud.githubusercontent.com/assets/808640/23717845/0af14b8a-03fb-11e7-86bc-bfdf779811fa.png)

**Comment by drafie** [comment] 2017-03-08 18:51
Here is another example, this one I found some log lines for after the move was downloaded by Radarr.  

17-3-8 12:21:01.7|Info|RefreshMovieService|Updating Info for A Monster Calls
17-3-8 12:21:02.2|Info|DiskScanService|Scanning disk for A Monster Calls
17-3-8 12:21:02.3|Info|DiskScanService|Completed scanning disk for A Monster Calls

![image](https://cloud.githubusercontent.com/assets/808640/23718466/2afa3fc0-03fd-11e7-8f07-15ae589acdb9.png)

**Comment by onedr0p** [comment] 2017-03-08 21:09
A monster call looks good since you have your cutoff set to 1080p.

**Comment by onedr0p** [comment] 2017-03-08 21:12
For arrival, maybe your profile perferred tags are grabbing releases for you if the tag is set there?

**Comment by galli-leo** [comment] 2017-03-08 21:17
@drafie Can you open your nzbdrone database and tell me what the movie A Monster Calls has for MovieFileId? And if you can find A Monster Calls 2016 Bluray file in the MovieFiles table?

**Comment by galli-leo** [comment] 2017-03-08 21:18
@drafie Also can you tell me what radarr version you are on?

**Comment by drafie** [comment] 2017-03-08 22:31
@onedr0p I agree, but the problem is that it says it says its "Missing" and "0b" still.

@galli-leo Radarr Ver. 0.2.0.497 nightly


Database - I found A Monster Calls in the nzbdrone.db

**Movies**
ID: 5965
ImdbId: tt3416532
Title: A Monster Calls
MovieFileID: 6701
...
Status: 2
Monitored: 1
ProfileID: 1
LastInfoSync: 2017-03-08 18:21:02.0247752Z
Added: 2017-02-17 13:24:31.7472815Z


**MovieFiles**
ID: 164
MovieID: 5965
Quality: {
  "quality": 7,
  "revision": {
    "version": 1,
    "real": 0
  }
}
Size: 3815150724
Date Added: 2017-03-08 18:05:29.451435Z
SceneName: A Monster Calls 2016 BRRip x264 1080p-NPW
MediaInfo: {
  "videoCodec": "AVC",
  "videoBitrate": 4050000,
  "videoBitDepth": 8,
  "width": 1920,
  "height": 804,
  "audioFormat": "AAC",
  "audioBitrate": 635538,
  "runTime": "01:48:25.5830000",
  "audioStreamCount": 1,
  "audioChannels": 2,
  "audioChannelPositions": "3/2/0.1",
  "audioChannelPositionsText": "Front: L C R, Side: L R, LFE",
  "audioProfile": "LC",
  "videoFps": 23.976,
  "audioLanguages": "English",
  "subtitles": "",
  "scanType": "Progressive",
  "schemaRevision": 3
}
ReleaseGroup: NPW
RelativePath: A Monster Calls (2016) Bluray-1080p.mp4
Edition: Null
Path: Null



Finally, I went and checked MovieFiles for ID 6701.  It does not exist.  There is a 6700 and 6702, but no 6701.

**Comment by drafie** [comment] 2017-03-10 06:28
@galli-leo 

So, I checked Arrival.  Movies.MovieFileID = 0. 
Looking in MovieFiles, I found Arrival at MovieFiles.ID=6497
So, I manually edited Arrival so that Movies.MovieFileID = 6497.

Bingo.  Now it shows as downloaded!

![image](https://cloud.githubusercontent.com/assets/808640/23784541/4a7c038e-0528-11e7-9140-7aad733f7220.png)

So I guess the bug here  is causes the Movies to reference the wrong or non-existent MovieFile.IDs.

**Comment by drafie** [comment] 2017-03-11 17:56
@galli-leo on further investigation - I am finding different reasons that are causing movies to remain listed as Missing.

(1) MediaInfo fails to return a run-time length - .wmv and .mp4 files in particular. 
(2) The folder name parsing by Radarr was incorrect in some case - resulting in only the last word being used, for instance using "Name (year)" instead of "The Movie Name (year)"
(3) Unable to parse movie info errors
(4) Incorrect IDs referenced in the Movies.MovieFileID 

I have find quite a few that simply required a manual refresh of the disk and it locates the movies and marks them as downloaded and assigns a run-time.  Shouldn't Radarr does this on its own when it runs the Updating Movies task?   Is it skipping missing movies?

**Comment by galli-leo** [comment] 2017-03-11 18:24
It should. Not sure why it wouldn't. Regarding the 2. one, could you post the folder names causing the issues. Regarding 4., I pushed a commit that should auto fix those and hopefully detect them before they happen. Also interested in folder names causing 3. Regarding 1., it should ignore that and simply skip the sample check, not sure what's happening there.

**Comment by galli-leo** [comment] 2017-03-11 18:27
Also re 4., I have the exact same Code as sonarr, so I do not currently understand how it's happening. Watch out for "Movie is null for the file" error. If you see it and the movie does not correctly show downloaded, please tell me.

**Comment by drafie** [comment] 2017-03-11 19:27
@galli-leo I will watch for "Move is null for the file" error.  

RE: #2 - here are two of them, I will try and locate others.  

\Toy Story 3 (2010) ...... \story
\Paper Covers Rock (2008)  ..... \covers

RE# 1 - is there a way for me to call media info from command line?  I am on windows.  I could run it on some of these files and see exactly what it is returning.

**Comment by drafie** [comment] 2017-03-11 19:53
@galli-leo I found it.  mediainfo cli for windows.   Also figure out why some other movies are marked missing. 

#6 Runtimes do not match

RE #1 - I ran mediainfo locally and indeed some of these movies don't return a run-time so the problem is not with Radarr for some of them.   .wmv and .mp4 in particular.    These could just be bad files to begin with.

RE #6 - I turned on Debug information and scanned one of the problematic files - Africa (2013).   Everything checked out with this movie and I could not figure out why Radarr would not pick it up.   It looks like Radarr said, hey the file on disk is 58 minutes but its supposed to be 60 minutes - so I'm going to mark it as missing.  

This could explain the problem - maybe we need something a little more verbose than "Missing" on the movie page or additional output in the standard logfile (not trace/debug) that indicates why it skiped a file on disk (runtime does not match, etc). 

17-3-11 13:38:36.2|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
17-3-11 13:38:36.2|Debug|ImportDecisionMaker|Quality (HDTV-1080p v1) of the file is different than the one we have (HDTV-720p v1)
17-3-11 13:38:36.2|Debug|FreeSpaceSpecification|Skipping free space check for existing episode
17-3-11 13:38:36.2|Debug|VideoFileInfoReader|Getting media info from \\persipolis\movies\Africa (2013)\Africa.mkv
**17-3-11 13:38:36.2|Debug|DetectSample|[\\persipolis\movies\Africa (2013)\Africa.mkv] appears to be a sample. Runtime: 00:58:25.5890000 seconds. Expected at least: 4140 seconds**
17-3-11 13:38:36.2|Debug|NotUnpackingSpecification|\\persipolis\movies\Africa (2013)\Africa.mkv is in series folder, skipping unpacking check
17-3-11 13:38:36.2|Debug|ImportApprovedMovie|Decisions: 1

So it seems like Radarr said, hey this video file is 58 minutes but IMBDB says it should be 69 minutes.

**Comment by galli-leo** [comment] 2017-03-13 17:03
@drafie Regarding the Africa one, can you give me the TMDBId of that movie? For the sample runtime check I take the Runtime given on TMDB and divide it by five. Maybe the runtime on TMDB is just borked?

**Comment by galli-leo** [comment] 2017-03-13 17:11
Yeah I found it. TMDB gives us 348 minutes as runtime.

**Comment by drafie** [comment] 2017-03-13 20:32
Looking at the file I have, it looks like 58-60min is the legitimate runtime,.

**Comment by galli-leo** [comment] 2017-03-14 14:23
In that case you should probably update the runtime on TMDB. Not much we can do if they have a five times longer runtime :/

**Comment by drafie** [comment] 2017-03-14 17:25
@galli-leo If you go to the website it shows a 60 minute runtime, but the API is returning 348.  Perhaps because its part of a mini-series and adding up all the run times to arrive at 348.   Either way, this particular movie appears to be an edge case.

**Comment by galli-leo** [comment] 2017-03-14 18:09
If you actually edit the movie it shows 348. interesting.

**Comment by TTLucian** [comment] 2018-02-19 19:11
`System.IO.IOException: Destination already exists [C:\Media\1 Movies\Movies - L\REC.4.Apocalipsis.2014.1080p.BluRay.x264-JODER\REC.4.Apocalipsis.2014.1080p.BluRay.x264-JODER.mkv]
   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath(String targetPath, Boolean overwrite) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 331
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 244
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 183
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 120
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.CopyMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 94
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 69
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 106

`

**Comment by galli-leo** [comment] 2018-03-04 14:35
@TTLucian That's fixed in the latest update, though you probably need to do a disk refresh.

**Closed** 2018-03-04 14:35 UTC
Labels: bug, priority:high

**Comment by TTLucian** [comment] 2018-03-05 20:24
@galli-leo Thanks. Seems to be working now!
