### ISSUE TITLE
Movie Index Columns - Video Codec, Audio Info, Language & Quality

### ISSUE THREAD

**Issue by PeterDBNL** [Radarr/Radarr#5703] opened 2021-01-07 13:53 UTC
Radarr is both meant as a tool to watch for future releases. However, it is also meant for media management. Unfortunately, it is not possible from the Movie Index page to select columns for the existing file video and audio information.

It would be beneficial to have Video Code, Audio Info, Languages and Quality as columns and the ability to filter by them.

Use Cases:
A. Existing movie is 720p, but you would like 1080p.
> Right now you would have to use the Status column to sort on and then access the Media Editor to select and search.

B. Existing movie is in less attractive audio or video codec, say VC1 vs anything else, or h264 vs h265, or h265 vs h264, and you would like a different release.
> With new columns you would be able to filter and find these movies faster.

![Radarr](https://user-images.githubusercontent.com/77109155/103900445-189d3700-50f8-11eb-9893-647ece363eab.png)

[AB#1764](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1764)

**Comment by ta264** [comment] 2021-01-07 13:56
Duplicate of #5517 and various others

**Closed by ta264** 2021-01-07 13:56 UTC
Labels: Type: Feature Request, Type: Duplicate
