### ISSUE TITLE
Follow up on IMDB scores request

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#1942] opened 2017-08-15 17:16 UTC
I am not sure if you guys can view closed threads so i made this in case you cant, sorry if you can and this is dupe

but i wanted to respond to 
https://github.com/Radarr/Radarr/issues/1940

on IMDB API....

there are sites that offer APIs to provide IMDB information though, which is utilized by sites like passthepopcorn for example where you can see all IMDB scores as well as rotten tomato scores directly on PTP, you can even search PTP based on IMDB scores criteria so it is possible

**Comment by galli-leo** [comment] 2017-08-15 18:14
Yeah closed threads are still open for view and discussion to everybody. So going to discuss this over there. (Duplicate of #1940 )

**Closed by galli-leo** 2017-08-15 18:14 UTC
