### ISSUE TITLE
Perform Radarr searches based on actor/actress name

### ISSUE THREAD

**Issue by Mughal1** [Radarr/Radarr#6919] opened 2022-01-09 04:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

This isn't a "problem" per se, more so an enhancement request for better efficiency.  Right now, if I'm in the mood to see films based on a particular actor/actress, I have to perform a search using an external database, such as IMDB, for that actor/actress.  I then pull up a list of works that the actor/actress has been in and then manually perform searches for each individual movie name for which that actor/actress has been in.  That process usually takes quite a bit of time.

### Describe the solution you'd like

The solution I would request for is for the ability to perform a named actor/actress search in Radarr and then have the results listed back of all the works that the actor/actress has been in.  Even better would be a feature to add a selection of those movies from the searched list to my Radarr library

### Describe alternatives you've considered

I can't think of an alternative at this time

### Anything else?

None, sorry

[AB#2333](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2333)

**Comment by bakerboy448** [comment] 2022-01-09 04:46
Duplicate of https://github.com/Radarr/Radarr/issues/1685

**Closed by bakerboy448** 2022-01-09 04:46 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by bakerboy448** [comment] 2022-01-09 04:48
Accomplished by just adding by the actor's list - with a tag - thus making the movies easily identifiable if needed
