### ISSUE TITLE
Defaults for manual search results

### ISSUE THREAD

**Issue by Davst** [Radarr/Radarr#7775] opened 2022-11-24 10:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When working with manual searches, each time you search you have to set up all the options you wish for again.

If you want to sort by custom format score, you have to click twice, to sort first by the lowest score, then by the highest (this should also be the other way around as people use scores to download the ones with the highest score, not the lowest.

You also have to re-select any custom filters that you have defined for the results.

### Describe the solution you'd like

I'd love one of two things.. or both

1. Be able to pick the default sorting and filtering options for your manual searches
2. Radarr should remember selections of sorting order and filters chosen if you switch between movies with the arrow buttons

### Describe alternatives you've considered

Alternatives would be keybinds for different sets of filters and such but that seems overly complicated.

To by default change the standard sorting order to Custom score, then release quality or such.. but flexibility is better.

To change the results to put results that don't match the criteria for downloading below the ones that do? still seems like the main solution is preferable.

### Anything else?

Sort orders on click should represent how interactions with the column are intended.. this mainly applies to custom score where the first click should be high to low instead of low to high as it currently is.

[AB#4152](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4152)

**Comment by bakerboy448** [comment] 2022-11-24 12:57
Duplicate of #4935
Duplicate of #7736

> I have searched the existing open and closed issues

please search and don't simply check the box

**Closed by bakerboy448** 2022-11-24 12:57 UTC
Labels: Type: Feature Request, Type: Duplicate
