### ISSUE TITLE
Quality Definitions not Saving

### ISSUE THREAD

**Issue by robinkooli** [Radarr/Radarr#1131] opened 2017-03-11 21:51 UTC
**Description:**

Quality Definitions are not saving, I tried multiple times.

When I press the Submit button it outputs following error on Google Chrome browser:

`vendor.js:24910 Uncaught TypeError: Cannot read property "toString" of undefined`

`at Object.setValue (vendor.js:24910)`
`at child.saveSettings (main.js:14100)`
`at triggerEvents (vendor.js:10851)`
`at EA.trigger (vendor.js:10794)`
`at child._save (main.js:8723)`
`at HTMLButtonElement.bound (vendor.js:12901)`
`at HTMLDivElement.dispatch (vendor.js:4830)`
` at HTMLDivElement.elemData.handle (vendor.js:4498)`

**Radarr Version:** 0.2.0.453 - Mar 6 2017

**Google Chrome Version:** 57.0.2987.98 (64-bit)

**Comment by galli-leo** [comment] 2017-03-11 22:01
Please try setting a page size.

**Comment by galli-leo** [comment] 2017-03-11 22:01
Also duplicate of another issue on here.

**Closed by galli-leo** 2017-03-11 22:01 UTC
