### ISSUE TITLE
More extra files should be matched for importing.

### ISSUE THREAD

**Issue by samtomcom** [Radarr/Radarr#6447] opened 2021-07-05 17:36 UTC
**Is your feature request related to a problem? Please describe.**

Extra files (Settings > Media Management (Advanced) > Importing > Import Extra Files) are only imported when they start with the same string as the movie file. e.g., with the extra files being "idx,sub,srt":

    zardoz.1974.1080p.bluray.x264-veto.mkv    _the movie_
    zardoz.1974.1080p.bluray.x264-veto.idx    imported 👍
    zardoz.1974.1080p.bluray.x264-veto.sub    imported 👍
    2_Eng.srt                                 **not imported 😢**
    3_Eng.srt                                 **also not imported 😢**

This is understandable for Sonarr, with most files linked to each episode being named as the idx and sub files above are, but for movie downloads often there is only a single .srt file named `Eng.srt`, `2_Eng.srt`, etc.

**Describe the solution you'd like**

Files with the matching extension should be imported regardless of if they begin with the same string as the movie title.
Multiple matching files obviously complicate this, but if there is a single matching file it should be imported.

**Describe alternatives you've considered**

Using a custom script to add this behaviour.

**Comment by bakerboy448** [comment] 2021-07-05 20:20
~ duplicate of https://github.com/Radarr/Radarr/issues/5472

**Closed by bakerboy448** 2021-07-05 20:20 UTC
Labels: Type: Feature Request
