### ISSUE TITLE
Download Station DSM7, API Changes

### ISSUE THREAD

**Issue by ddmunhoz** [Radarr/Radarr#6440] opened 2021-07-04 01:24 UTC
**Describe the bug**
Synology changed the methods and API response on DSM 7. That causes Download Station download client to fail with Radarr. The problem does not exist on Sonarr.

**To Reproduce**
1 - Configure Download Station on Synology DSM7 as a download Client
2 - Test connection on Radarr

**Expected behavior**
Connet successfully

This [merge](https://github.com/Sonarr/Sonarr/pull/4485/commits/ceb6f06d2f63da4e70a1c3250cd1cb7f2a856e5c) fixed it for Sonarr. 

[AB#1181](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1181)

**Comment by bakerboy448** [comment] 2021-07-04 01:29
Please search prior to opening issues

Duplicate of #6062

Fixed in https://github.com/Radarr/Radarr/commit/143067621c4a0065365c2446a1cdda19dcd1a378

**Closed by bakerboy448** 2021-07-04 01:29 UTC
Labels: Type: Bug

**Comment by ddmunhoz** [comment] 2021-07-04 02:15
Issue is definitely not fixed on nightly. But anyway. I'll fix it on my side.

**Comment by bakerboy448** [comment] 2021-07-04 07:06
> Issue is definitely not fixed on nightly. But anyway. I'll fix it on my side.

The same pull that is in Sonarr is in nightly, so yes it is fixed.
Radarr - https://github.com/Radarr/Radarr/commit/143067621c4a0065365c2446a1cdda19dcd1a378
Sonarr - https://github.com/Sonarr/Sonarr/commit/49e90463e57929e7b9885f1b7b0eb05bd7cc3ebe

There is an issue where if you fail to set a download path in *arr for DS then it errors out.  Twenty is aware of the issue and is testing a fix
https://github.com/Sonarr/Sonarr/issues/4562

**Comment by bakerboy448** [comment] 2021-07-17 00:11
second piece https://github.com/Radarr/Radarr/commit/94c685a5caf30dbef5708dca0018ba8df436b6d2
