### ISSUE TITLE
"Search selected" does not perform any search for movies that are not "monitored"

### ISSUE THREAD

**Issue by ameel** [Radarr/Radarr#4853] opened 2020-08-12 13:08 UTC
**Description:**
Per title, "Search selected" from "Wanted" and "Search for Movie" when selecting a movie do not undertake search if a movie is not "monitored"

**Actions taken:**
Go to "Wanted"
Select some items
Click "Search Selected"
Search completes immediately and does not actually perform search
Log reports "Movie search completed. 0 reports downloaded."

This issue also happens when I go into an item and click "Search for Movie" button for automatic search.

I use nzb and torrent downloaders, and nzb and torrent indexers. All work.
When I click "Search All" or go into an individual item and click the "Manual Search" button, this performs the search as expected.

**Radarr Version:**
0.2.0.1504

**Mono Version:**
6.8.0.105

**Debug Logs:**
2020-8-12 23:04:51.9|Debug|MovieSearchService|Movie XXXXXXXXXXXXXXX is not monitored, skipping search

**Comment by austinwbest** [comment] 2020-08-12 14:16
There is ongoing discussion about searching for unmonitored but whatever decision is made, it won't be changed in v0.2 so you know. It would be in v3.

**Comment by Qstick** [comment] 2020-08-13 01:51
Closing the issue is covered by #1651 and #3235...

**Closed by Qstick** 2020-08-13 01:51 UTC
