### ISSUE TITLE
Choose library details languages

### ISSUE THREAD

**Issue by alxlaxv** [Radarr/Radarr#3406] opened 2019-03-05 18:28 UTC
Hi,

I'm contacting you to talk about a feature request related to a recent change in the application which makes me unhappy...

My usecase is the following:
- I'm watching my movies in VO (English most of the time) with French subtitles. Releases are called VOSTFR
- But having English titles and descriptions is very important to me
- Currently I have to set my downloading profile for those movies to language = French otherwise it will not match (VOSTFR detected as French)

Since a recent update (I'm using night builds for years), the language of my library changed to be the language of the profile of each movie... so French instead of English.

Could you please have an option to choose the language to use for the library (title, description, ...)  ?

Thanks a lot

A very regular user for a long time feeling disappointed.

**Comment by ToXinE** [comment] 2019-03-27 08:17
Are you talking about movie summary? I'm french and since several months, movies summary disapearing when added to my library. 
![summary_disapearing](https://user-images.githubusercontent.com/6205053/55060148-1841c200-5071-11e9-9cfc-1a5a303818c9.gif)

**Comment by alxlaxv** [comment] 2019-04-11 17:43
Yes for me they switched back to French because the profile language is French but I had to as explained above.

**Comment by galli-leo** [comment] 2019-05-30 18:58
Duplicate of #3497

**Closed by galli-leo** 2019-05-30 18:58 UTC
