### ISSUE TITLE
Add MPAA rating in the Metadata NFO for Kodi

### ISSUE THREAD

**Issue by alxlaxv** [Radarr/Radarr#2734] opened 2018-04-23 20:05 UTC
**Description:**

I wondering if you can add the mpaa in the metadata (nfo file) used by Kodi which is created by Radarr.
https://kodi.wiki/view/NFO_files/Movies
<mpaa></mpaa>

Thanks in advance,

Great soft !

**Comment by galli-leo** [comment] 2018-04-24 06:37
Duplicate of #1561

**Closed by galli-leo** 2018-04-24 06:37 UTC
