### ISSUE TITLE
Year 0 for newly added movies

### ISSUE THREAD

**Issue by 4getit** [Radarr/Radarr#2613] opened 2018-03-06 22:03 UTC
Currently, the release years are set to (0) for newly added movies.

When trying to start the download manually, the Force Download modal pops up but nothing happens.

Not sure if related but there seems to be a 500 error when reaching out to somewhere:

Request Failed: Error while calling api: Internal Server Error
Full error(s): Internal Server Error (500, RayId: ccfb251a-0c89-4f5d-af72-302a1e2f1031), Details: An error has occurred and this resource cannot be displayed.

**Comment by galli-leo** [comment] 2018-03-06 22:23
Duplicate of #2611 

Year 0 is due to whatever app you are using not correctly sending the year when adding a movie.

**Closed by galli-leo** 2018-03-06 22:23 UTC
