### ISSUE TITLE
404 when clicking on wanted movie

### ISSUE THREAD

**Issue by wifiuk** [Radarr/Radarr#1791] opened 2017-07-12 20:09 UTC
go to the wanted menu. see list of wanted movies there
Click on one of the movies get a 404 page with a demented angry bird pig.

Right click on the movie in the list and open in new window, loads up the movie page as expected.

**Comment by hotio** [comment] 2017-07-12 21:39
Try clearing all of your browser cache

**Comment by wifiuk** [comment] 2017-07-13 11:28
same issue

**Comment by hotio** [comment] 2017-07-13 16:47
Which version are you running?
Does it happen in an Incognito window too?

**Comment by wifiuk** [comment] 2017-07-13 16:49
Version
0.2.0.778

same issue in incognito window

**Comment by galli-leo** [comment] 2017-07-16 15:32
duplicate of #1196

**Closed by galli-leo** 2017-07-16 15:32 UTC

**Comment by highwaycat** [comment] 2017-11-13 14:07
In my case the 404 happened because I added the movie on another language before. If you do this you have to search for it by it's original title.
