### ISSUE TITLE
Feature Request:  Temporarily Download higher profile(s), and auto remove after set time frame to save on storage space.

### ISSUE THREAD

**Issue by requiem240sx** [Radarr/Radarr#2423] opened 2018-01-16 10:54 UTC
With 4K content being very large  file sizes, this would offer users 4K video without sacrificing all of their storage. I would really like to be able to watch and enjoy 4K content with Dolby Atmos/DTS: X for the first time I watch the video.  Having a feature to temporarily download a higher profile (like 4K or uncompressed versions etc..) for a set amount of time would allow users to be able to watch the latest movies in a higher profile for the first time, then after a set amount of days or months etc, Radarr would automatically remove that larger file or "downgrade" the profile to something that will save more space. (say 1080P Blue-ray or 720p Blue-ray) etc... 

This could be handled a few ways that I see

- Download 2 separate files, and later remove the higher one. 
- Download the larger one, then after x amount of days after it will change the profile of the movie.  Using a "temporary" profile. 
- Download 1 larger file, then have a different program convert it to a compressed/smaller size and remove the original later. 

**Disclaimer, I'm new to posting here and tried searching for this.  I have not found anything that matched, but might have missed something. I did find a different feature request that is slightly similar to this.  Issue #2203 . If this feature gets implemented, I'm sure it wouldn't be too hard to write a script on the server to check files over "x" in size and remove them after "x" amount of time if multiple files exist in the directory etc...   Until then I will continue to manually manage 4K content temporarily for users etc.

Would love to hear others feedback.  If anyone already has a solution to this, I would be very interested in a workaround in case the feature can't be added for a while.

**Comment by galli-leo** [comment] 2018-02-07 14:08
Duplicate of #1526

**Closed by galli-leo** 2018-02-07 14:08 UTC
