### ISSUE TITLE
Increase upload file size in ASP.Net Core

### ISSUE THREAD

**Issue by fhedstrom** [Radarr/Radarr#5593] opened 2020-12-21 07:48 UTC
**Is your feature request related to a problem? Please describe.**
The problem is when I try to use one of my database backups it states "Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large". 
This is probably because my database is 57.4 MB and it seems like there is a limit to Kestrel in AspNetCore to 28,6 MB.
Here is the log: https://pastebin.com/Jq8j1u96

**Describe the solution you'd like**
To raise the size of allowed files to be used as a backup in Radarr in Asp.Net Core, if that is actually the problem which it seems to be as stated here:
https://github.com/dotnet/aspnetcore/issues/20369

**Describe alternatives you've considered**
To start over with a new database.

**Comment by bakerboy448** [comment] 2020-12-21 10:16
Those are not trace logs

Also does not appear to be a radarr bug
It appears the issue is you need to configure your IIS server

the issue you linked has a fix, https://github.com/dotnet/aspnetcore/issues/20369#issuecomment-607057822

Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by ta264** [comment] 2020-12-21 10:20
This is a legitimate issue we should fix

**Comment by ta264** [comment] 2020-12-21 10:21
(Radarr runs in kestrel, not with IIS)

**Comment by bakerboy448** [comment] 2020-12-21 15:23
fixed in https://github.com/Radarr/Radarr/commit/9e3c290ad1d392162d218fd3b67ddd583a775835

**Closed** 2020-12-21 17:39 UTC
Labels: bug
