### ISSUE TITLE
Manual Import - Select Movie: Filter not working

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#962] opened 2017-03-01 14:41 UTC
**Description:**

When doing a manual import, radarr finds a movie file, when manually matching the file to a movie in the movie collection, a long list of movies is shown. Trying to filter this list does not work.

![filter](https://cloud.githubusercontent.com/assets/25102010/23464457/58089196-fe95-11e6-8352-7af54c7e80d3.png)

**Radarr Version:**
0.2.0.418

**Comment by drashna** [comment] 2017-03-02 16:47
Can confirm on two different systems.

Not only does it not show the *full* list of items, it doesn't filter when you type in, either.

**Comment by geogolem** [comment] 2017-03-02 17:42
I am looking into this issue.... it is likely very similar to the recent fixes I put in for the MovieEditor... Have you guys tried the MovieEditor in the most recent build? I'll report back here when I fix the issue.

**Comment by drashna** [comment] 2017-03-02 17:51
Well, started happening on the pagination build (breaking the main page up), specifically. 

As for the movie editor, I'm not entirely sure what you mean here. But the "select folder" window does appear to be the same.  But I'm guessing that the issue is with the enumeration code for the added movies.

**Comment by geogolem** [comment] 2017-03-02 17:53
the movieEditor was not working, i.e. filtering was not working, and saving would not work if you selected items across pages, or across filters... The MovieEditor should work since late last night as I merged a fix for it then... Please let me know if you have any issues with the MovieEditor.. btw. I know the "Done Saving" message, and the state one is left in after saving (all items still selected) are not the best, but its functional.. Eventually the Done Message should be  conveyed similar to other messages and perhaps it would be better to clear all selections after a save... or maybe have a clear all button.. 

I also realize a delete for batch deleting button is ideal in the movieEditor - i plan to look into that eventually...

**Comment by geogolem** [comment] 2017-03-02 20:06
I am quite sure I have a fix for this now.. both issues (not all movuies showing up, filtering not working)..

I just need to triple check that it doesnt break anything else..

**Comment by drashna** [comment] 2017-03-02 23:18
Can confirm that this issue is fixed. 

Thanks!!

**Comment by geogolem** [comment] 2017-03-02 23:20
Happy Filtering during Manual Import!!!!

**Closed** 2017-03-02 23:19 UTC
Labels: fixed in next release

**Comment by geogolem** [comment] 2017-03-03 08:11
after this change, you might have noticed that the filters were broken on the main index page.. (well the released, announced and incinemas)...   this has been fixed.. so if you notice this, just make sure you are up to date.

**Comment by adamtheturtle** [comment] 2017-08-23 22:50
This issue is present for me.

I'm up to date on Safari, Chrome, Firefox and macOS.

Radarr version 0.2.0.778.

**Comment by qweasdzxc787** [comment] 2017-10-12 02:11
Still an issue: running version 0.2.0.870

**Comment by Benni-chan** [comment] 2017-10-19 19:38
can confirm. can't filter and can't sort. newly added movies are at the bottom of the list and not alphabetically sorted

**Comment by jrozelle** [comment] 2017-11-15 12:52
Same issue here.
Radarr Ver. 0.2.0.870

**Comment by scottwallacesh** [comment] 2017-11-26 13:05
Confirmed.  This seems to have regressed.

```Radarr Ver. 0.2.0.870```

**Comment by galli-leo** [comment] 2017-11-26 13:52
.870 does not have the fix, since its not the nightly release

**Comment by PnoT** [comment] 2017-12-08 19:52
Eagerly waiting on this one to get fixed.
