### ISSUE TITLE
Matching TV category as movie, and regexp washing of title? (MMA Events)

### ISSUE THREAD

**Issue by sliddjur** [Radarr/Radarr#2181] opened 2017-10-15 11:54 UTC
**Description:**
I am using Radarr with Jackett. I want to search for MMA events, such as UFC 216: Ferguson vs. Lee (2017), or Bellator 175: Rampage vs. King Mo 2 (2017).
From earlier discussions these events are not in thetvdb. They are considered as movies, and metadata is therefor found in themoviedb.
So I successfully added my indexer, connected to Jackett, and added category 5000. Now I successfully can search and find torrents with my title. Great, but I am not getting any matches to the title. My error is "Failed to find movie title in release name ...". I have set Parser Leniency to Lenient Mapping without success. I suspect the problem is that most of these MMA events have "PPV" inserted in the title? See screenshot here: https://paste.debian.net/990853/
When I press the hidden button (for example on the 720p release), the force download popup appears, but nothing happens when I press the force download button. Is that a language issue? I have set language to english, and themoviedb has set originial language as english.

Is it a title match problem?
Or is it an issue that these are from a TV category?
Is it possible to make exceptions to matches, such as the PPV string?

**Radarr Version:**

```
Radarr Version: 0.2.0.870
Mono Version: 5.2.0.224 (tarball Tue Oct 3 19:51:58 UTC 2017)
AppData directory: /home/media/.config/Radarr
Startup directory: /opt/Radarr
OS: OpenMediaVault based on Debian 8 (jessie) 
```
**Logs:**

```
17-10-15 12:36:27.5|Info|RssSyncService|Starting RSS Sync
17-10-15 12:36:29.9|Info|DownloadDecisionMaker|Processing 150 releases
17-10-15 12:36:34.8|Info|RssSyncService|RSS Sync Completed. Reports found: 150, Reports grabbed: 0
17-10-15 12:47:27.7|Info|PreDBService|Starting PreDB Sync
17-10-15 12:47:27.7|Info|NetImportSearchService|No lists are enabled for auto-import.
17-10-15 12:49:31.0|Info|NzbSearchService|Searching 2 indexers for [UFC 216: Ferguson vs. Lee]
17-10-15 12:49:33.1|Info|DownloadDecisionMaker|Processing 7 releases
17-10-15 12:49:33.1|Info|AcceptableSizeSpecification|[tt7467368][UFC 216: Ferguson vs. Lee (2017)] has no runtime information using median movie runtime of 110 minutes.
17-10-15 12:50:06.3|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.870] NzbDrone.Core.Datastore.ModelNotFoundException: Movie with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x0009d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:79 
  at NzbDrone.Core.Tv.MovieService.GetMovie (System.Int32 movieId) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:142 
  at NzbDrone.Api.Movie.AlternativeTitleModule.AddTitle (NzbDrone.Api.Movie.AlternativeTitleResource altTitle) [0x00007] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\AlternativeTitleModule.cs:44 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_CreateResource>b__41_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:161 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 

17-10-15 13:02:56.5|Info|NzbSearchService|Searching 2 indexers for [UFC 216: Ferguson vs. Lee]
17-10-15 13:02:58.6|Info|DownloadDecisionMaker|Processing 7 releases
17-10-15 13:02:58.6|Info|AcceptableSizeSpecification|[tt7467368][UFC 216: Ferguson vs. Lee (2017)] has no runtime information using median movie runtime of 110 minutes.
17-10-15 13:07:44.8|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.870] NzbDrone.Core.Datastore.ModelNotFoundException: Movie with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x0009d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:79 
  at NzbDrone.Core.Tv.MovieService.GetMovie (System.Int32 movieId) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:142 
  at NzbDrone.Api.Movie.AlternativeTitleModule.AddTitle (NzbDrone.Api.Movie.AlternativeTitleResource altTitle) [0x00007] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\AlternativeTitleModule.cs:44 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_CreateResource>b__41_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:161 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 

17-10-15 13:08:29.4|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.870] NzbDrone.Core.Datastore.ModelNotFoundException: Movie with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x0009d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:79 
  at NzbDrone.Core.Tv.MovieService.GetMovie (System.Int32 movieId) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\MovieService.cs:142 
  at NzbDrone.Api.Movie.AlternativeTitleModule.AddTitle (NzbDrone.Api.Movie.AlternativeTitleResource altTitle) [0x00007] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\AlternativeTitleModule.cs:44 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_CreateResource>b__41_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:161 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 

```

**Comment by weirdcrap** [comment] 2017-10-20 16:35
this is a dupe of https://github.com/Radarr/Radarr/issues/2179

**Comment by galli-leo** [comment] 2018-02-07 13:39
Duplicate of #2179

**Closed by galli-leo** 2018-02-07 13:39 UTC
