### ISSUE TITLE
qbittorrent not getting category - only sometimes

### ISSUE THREAD

**Issue by nicopolous** [Radarr/Radarr#1937] opened 2017-08-14 12:02 UTC
Firstly, love this software!

I use qbittorrent to download torrents.  Sometimes (not always) a category is not added to the torrent, so it's not picked up by Radarr when it's finished and just sits in the downloads folder.  Log attached - I tried once and the download didn't get a category.  I then cancelled it (in qbittorrent) and re-downloaded through Radarr, and the category was added correctly.

I have a separate directory for finished downloads in qbittorrent, not sure if that makes a difference, but I could try and have the same directory.

**Radarr Version:  0.2.0.827**
Qbittorrent version 3.3.15

**Logs:  attached - interesting bit below:**
17-8-14 12:53:49.9|Info|MovieService|Adding Movie [][Kidnap (2017)] Path: [\\data\media\1 - Films\Kidnap (2017)]
17-8-14 12:53:50.0|Info|MediaCoverService|Downloading Poster for [][Kidnap (2017)] http://image.tmdb.org/t/p/original/9CabD3j9PrjRY054fL0WJuEcXHZ.jpg
17-8-14 12:53:50.0|Info|RefreshMovieService|Updating Info for Kidnap
17-8-14 12:53:51.2|Info|DiskScanService|Scanning disk for Kidnap
17-8-14 12:53:51.2|Info|MovieScannedHandler|[Kidnap] was recently added, performing post-add actions
17-8-14 12:53:51.3|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\154\banner.jpg not found
17-8-14 12:53:51.6|Info|MediaCoverService|Downloading Banner for [tt1458169][Kidnap (2017)] http://image.tmdb.org/t/p/original/8hRN2YGnjzFZAVseunzDZjLoXh7.jpg
17-8-14 12:53:53.9|Info|NzbSearchService|Searching 3 indexers for [Kidnap]
17-8-14 12:53:56.0|Info|DownloadDecisionMaker|Processing 31 releases
17-8-14 12:54:02.4|Info|DownloadService|Report sent to qbittorrent. Kidnap.2017.1080p.WEB-DL.DD5.1.H264-FGT
17-8-14 12:54:32.9|Info|NzbSearchService|Searching 3 indexers for [Kidnap]
17-8-14 12:54:35.0|Info|DownloadDecisionMaker|Processing 31 releases
17-8-14 12:54:40.1|Info|DownloadService|Report sent to qbittorrent. Kidnap.2017.1080p.WEB-DL.DD5.1.H264-FGT

[radarr.txt](https://github.com/Radarr/Radarr/files/1222121/radarr.txt)

**Comment by jamesmacwhite** [comment] 2017-08-15 05:37
qBittorrent did recent change their API in 3.3.14 which broke label assignment, in theory this commit should of fixed it (taken from Sonarr upstream):

https://github.com/Radarr/Radarr/commit/17feedaf53e2d302dd4e4f5bb0f7a9211ca1c2cf

However, based on your report are you saying you still have the problem on the latest nightly?

**Comment by nicopolous** [comment] 2017-08-15 09:31
I had the issue previously, but didn't report as it was already logged as a bug. I also thought the latest nightly (0.2.0.827) would have fixed it, but unfortunately it hasn't.

I turned on debug log and attached.

I selected a random movie (already in my collection), did a search and selected a bunch of torrents to download (6 in total).  Only 5 of them had the correct "radarr" category in qbitorrent and appeared in the Radarr queue.  One of them didn't have a category attached and didn't appear in the Radarr queue.  It does appear in the Radarr history however.

I've attached screenshots to show what I mean.

Hope this helps!

[radarr.debug.0.txt](https://github.com/Radarr/Radarr/files/1224640/radarr.debug.0.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1224644/radarr.debug.txt)

![radarr history](https://user-images.githubusercontent.com/30494497/29310241-e17a2dee-81a4-11e7-9502-0f244e856a9f.PNG)

![radarr queue](https://user-images.githubusercontent.com/30494497/29310256-ead821fc-81a4-11e7-88cc-2049f9aef3c2.PNG)

![qbittorrent](https://user-images.githubusercontent.com/30494497/29310258-edc3ddf2-81a4-11e7-870f-86d56264a9ac.PNG)

**Comment by jamesmacwhite** [comment] 2017-08-15 10:22
Thanks for the detailed explanation. Fully understood. It would suggest there is still potentially an API issue to investigate then or something else.

We'll have to check if anything in qBittorrent 3.3.15 has also been modified API wise.

**Comment by nicopolous** [comment] 2017-08-15 10:29
Superb, thanks.  

Again want to say great work on Radarr and Sonarr - they're both excellent.

**Comment by nicopolous** [comment] 2017-08-18 06:53
I had the exact same issue happen in Sonarr yesterday, which points to it being a qbittorrent issue.

**Comment by jamesmacwhite** [comment] 2017-08-18 07:01
@nicopolous Thanks for the update, will try and look at further API changes since the 3.3.14 fix went in and see what can be done/where the problem is.

**Comment by sayem314** [comment] 2017-11-02 09:40
I'm using Qbittorrent 3.3.7 ( Radrr Ver. 0.2.0.870, Mono Ver. 5.4.0.201 ). Still same problem.

**Comment by jamesmacwhite** [comment] 2017-11-04 07:43
Tracking thus issue under this issue number:

https://github.com/Radarr/Radarr/issues/2200

It would appear that both Sonarr and Radarr have the same issue. Possibly an upstream qBittorrent thing, or the way the API is used in this case and might need to be changed.

**Comment by galli-leo** [comment] 2018-02-07 10:28
This is fixed in the latest release.

**Closed by galli-leo** 2018-02-07 10:28 UTC
