### ISSUE TITLE
Download standard releases in same quality after HC release has been downloaded

### ISSUE THREAD

**Issue by r1nzl3r9991** [Radarr/Radarr#1600] opened 2017-05-31 17:06 UTC
Download standard releases in same quality after HC release has been downloaded

Now that we have the ability to download Hardcoded releases (thank you dev team) I wanted to know how I can make Radarr download the real release after the Hardcoded release has been downloaded.

Example

**Life (2017) 720p HC** release is downloaded automatically by Radarr

_*2 weeks later*_

**Life (2017) 720p WEB-DL** is released, but Radarr will not automatically download it because Radarr thinks I have already downloaded a 720p WEB-DL release (when it is really the HC version). Is there a way to automatically make Radarr detect the HC release, remove it, and replace with the real 720p WEB-DL release? I know it sounds a bit complicated, but I am not sure how to make this happen. 

Radarr 0.2.0.696

**Comment by galli-leo** [comment] 2018-02-06 23:20
Duplicate of #2433

**Closed by galli-leo** 2018-02-06 23:20 UTC
