### ISSUE TITLE
View movies by list

### ISSUE THREAD

**Issue by davidchalifoux** [Radarr/Radarr#6766] opened 2021-11-26 19:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

NA

### Describe the solution you'd like

I'd like to be able to view individual lists that are added on Radarr and view a list of the movies related to it. Navigation example: Movies -> Lists -> Star Wars Collection -> list of Star Wars movies. This way, it would be easier to view and manage the movies within a given collection.

### Describe alternatives you've considered

I've found that you can create a custom filter to search by collection, but this is a very tedious process and you need to know the name of the collection you are looking for, instead of being able to see a list.

### Anything else?

Nav example, sorry I didn't take the time to mock-up the full page.
<img width="228" alt="Screen Shot 2021-11-26 at 1 10 55 PM" src="https://user-images.githubusercontent.com/3289533/143622523-963410a4-9556-4d28-83d2-eeb4f5562f59.png">

[AB#1987](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1987)

**Comment by bakerboy448** [comment] 2021-11-26 19:17
Duplicate of https://github.com/Radarr/Radarr/issues/6734 and various others

Assign a tag to the list, then the movie will get that tag. no additional plans on this

Movies on Lists are viewable in Discover

**Closed by bakerboy448** 2021-11-26 19:17 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by davidchalifoux** [comment] 2021-11-26 21:58
> Duplicate of #6734 and various others
> 
> Assign a tag to the list, then the movie will get that tag. no additional plans on this
> 
> Movies on Lists are viewable in Discover

Thanks for the recommendations and sorry I didn't find the duplicate. Unfortunately none of those things really fit what I'm looking for.

Would a PR be considered for this?
