### ISSUE TITLE
Updater causing full tmpfs /tmp/  (QNAP)

### ISSUE THREAD

**Issue by macvirii** [Radarr/Radarr#2520] opened 2018-02-14 08:56 UTC
After some tinkering (problems on SABNzb because of the full /tmp) I saw that both directories used in the updater where still there.

Radarr now downloads the new version package, extracts , create the backup folder, copy the current version folder to the update folder, updates, and keeps the folder on /tmp.

Considering the /tmp is only 64 MB (it's a ramdisk, it needs to be mounted before the file system is online) , it's troublesome using the directory.

On Sonarr they use other symlinks/dirs
Example from my previous Sonarr Update

```
18-1-22 00:17:19.3|Info|AppFolderInfo|Data directory is being overridden to [/share/CACHEDEV1_DATA/SONARR_CONFIG]
18-1-22 00:17:19.3|Debug|UpdateApp|NzbDrone process ID: 1102
18-1-22 00:17:19.3|Debug|UpdateApp|Arguments:
18-1-22 00:17:19.3|Debug|UpdateApp|  1102
18-1-22 00:17:19.3|Debug|UpdateApp|  /share/CACHEDEV1_DATA/SONARR_CONFIG/nzbdrone_update
18-1-22 00:17:19.3|Debug|UpdateApp|  /share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone/NzbDrone.exe
18-1-22 00:17:19.3|Debug|UpdateApp|  /data=/share/CACHEDEV1_DATA/SONARR_CONFIG
18-1-22 00:17:19.3|Debug|UpdateApp|Using executing application: /share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone/NzbDrone.exe
18-1-22 00:17:19.3|Debug|UpdateApp|Executable location: /share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone/NzbDrone.exe
18-1-22 00:17:19.3|Info|InstallUpdateService|Installation Folder: /share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone
18-1-22 00:17:19.3|Info|InstallUpdateService|Updating Sonarr from version 2.0.0.5054 to version 2.0.0.5085
18-1-22 00:17:23.7|Info|BackupAndRestore|Creating backup of existing installation
18-1-22 00:17:23.7|Debug|DiskTransferService|Mirror [/share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone] > [/share/CACHEDEV1_DATA/SONARR_CONFIG/nzbdrone_update/nzbdrone_backup/]
18-1-22 00:17:23.7|Debug|DiskTransferService|Mirror [/share/CACHEDEV1_DATA/.qpkg/QSonarr/NzbDrone/NzbDrone.Update] > [/share/CACHEDEV1_DATA/SONARR_CONFIG/nzbdrone_update/nzbdrone_backup/NzbDrone.Update]
```

Also, I think this is a problem that issue #2424 raised, the disk full that was reported probably was the /tmp full.

**Comment by galli-leo** [comment] 2018-02-14 22:36
So apparently Sonarr doesn't do anything special on Qnap. The update to the other dir, is probably caused by QSonarr. Maybe you can ask them a) what they did and b) if they can make a Radarr version. /tmp being only 64mb is stupid. No idea why anyone would do that, so gonna close this issue as wontfix.

**Closed by galli-leo** 2018-02-14 22:36 UTC
Labels: wontfix
