### ISSUE TITLE
Add Release Group to Movies Table view available Columns

### ISSUE THREAD

**Issue by owine** [Radarr/Radarr#7919] opened 2022-12-22 16:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

Add Release Group as an available column on the Movies Table view

### Describe alternatives you've considered

N/A

### Anything else?

Sonarr includes this functionality (example below)

![CleanShot 2022-12-22 at 10 04 42](https://user-images.githubusercontent.com/4283702/209174507-c32fbafe-26b4-4524-809a-ee667e664b47.png)

[AB#4525](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4525)

**Comment by bakerboy448** [comment] 2022-12-22 16:06
Duplicate of https://github.com/Radarr/Radarr/issues/7377

**Closed by bakerboy448** 2022-12-22 16:06 UTC
Labels: Type: Feature Request, Status: Needs Triage
