### ISSUE TITLE
Ability to import movies and delete watched movies

### ISSUE THREAD

**Issue by silv3r23** [Radarr/Radarr#3435] opened 2019-03-20 12:14 UTC
Hi, I am using SteveLu List for automated importing wanted movies to be monitored. When a movie has watched he will be added to my Trakt UserWatchedList by my media server. 
I want to delete watched movie files and avoid to be redownloaded.
My try was second list (Trakt UserWatchedList) and enabled Library Cleanup but this is unfortunately a global setting, not just for one list.
In my test environment I figured out that:
a) all lists will be processed as one task, it would be easy when there could be implemented an information what type of list is being processed while this task is running.
b) it seems that there is a bug in /src/NzbDrone.Core/NetImport/NetImportSearchService.cs line 187 - TmdbId is empty while using StevenLu, switch to ImdbId works.
`if (movie.TmdbId == listedMovie.TmdbId)
                        {
                            foundMatch = true;
                            break;
                        }`

I hope we could find a way to improve a) so I could do further testings and commit my almost finished code.
(just a tiny hint: I want to import wanted movies as monitored and cleanup watched movies by putting them to import blacklist and delete the folder depending on user settings)

Version 0.2.0.1293

**Comment by geogolem** [comment] 2019-03-21 01:02
I am just tagging this for future reference:

Potentially related to: https://github.com/Radarr/Radarr/issues/3014

**Comment by geogolem** [comment] 2019-03-21 01:06
My workflow accomplishes the task you are requesting; however, it works because I use a trakt watch list and a trakt watched list.

and those are the only lists I use. When a movie is marked as watched in Trakt (added to watched list), it is automatically removed from the watch list and the library cleanup thing then works by printing out a message in the log indicating that a movie is no longer in my watch list and that I might want to remove it.

The reason I tagged the other issue, is because if/how your request is implemented will likely be dependent on better multiple list support as outlined in that issue.

**Comment by geogolem** [comment] 2019-03-21 01:08
perhaps also related to: https://github.com/Radarr/Radarr/issues/2469

**Comment by silv3r23** [comment] 2019-03-25 18:23
@geogolem thanks for your quick response! I checked all related feature request, they are exactly what I need!
In the next weeks I will doublecheck where the difference between trakt watch list and stevenLu watch list exactly is and will leave an update here

**Comment by fryfrog** [comment] 2019-04-23 03:44
Closing since this is a duplicate of existing feature requests.

**Closed by fryfrog** 2019-04-23 03:44 UTC
