### ISSUE TITLE
Updated new folders as new info is available

### ISSUE THREAD

**Issue by herkalurk** [Radarr/Radarr#7322] opened 2022-05-31 16:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not really...?

I'm finding that some movies that were added to radarr very early before their release date are now having weird folder names.

### Describe the solution you'd like

**IF** the folder doesn't exist then these are simply database entries at this point.  So why not update the folder name so that when we actually get the movie the folder name matches the movie appropriately.  It should be a simple check to see if a directory exists and if not then change what's listed at the directory name.

### Describe alternatives you've considered

I manually rename them.

### Anything else?

Example where data is updated but folder is still named weirdly

![Capture](https://user-images.githubusercontent.com/2532699/171224918-27abfeda-ac2d-4e8f-89d1-14137dfa51d1.PNG)

[AB#3213](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3213)

**Comment by bakerboy448** [comment] 2022-05-31 16:28
Duplicate of #6374

**Closed by bakerboy448** 2022-05-31 16:28 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by herkalurk** [comment] 2022-05-31 16:34
Radarr requires folders, so I'm trying to understand why we wouldn't want the folders to be appropriately named for sorting purposes.  Also don't understand why simply changing a database entry on a not yet created folder is a problem.

**Comment by bakerboy448** [comment] 2022-05-31 16:48
> Radarr requires folders

Radarr does not require a movie folder for movies that are only in database and do not have a file.  Users can enable Radarr to create empty folders, but that's typically not advised due to these types of issues with future movies (i.e. names changing; years changing, etc.).

Assuming create empty folders is disabled, the folder should get renamed properly upon import and thus there's no issue.  If it's not, then that'd be a bug.

**Comment by herkalurk** [comment] 2022-05-31 16:55
And the weirdly named folder has happened, the movie metadata had the updated name at the time of download yet the folder still contained 'untitled'

![image](https://user-images.githubusercontent.com/2532699/171230598-2470cca3-671f-49ed-b3ad-68f9915cf798.png)

**Comment by bakerboy448** [comment] 2022-05-31 18:09
No near term plans to change that I guess; the movie folder naming uses the metadata from the time of movie adding to radarr.

So for any movies added prior to its name and year being solidified, once they're downloaded they'll need to have their folders manually renamed

1. Movies
1. Movie Editor
1. Select what movies need their folder renamed
1. Change Root Folder to the same Root Folder that the movies currently exist in
1. Select "Yes move files"

https://wiki.servarr.com/radarr/faq#how-can-i-rename-my-movie-folders

**Comment by herkalurk** [comment] 2022-05-31 18:55
> No near term plans to change that I guess; the movie folder naming uses the metadata from the time of movie adding to radarr.
> 
> So for any movies added prior to its name and year being solidified, once they're downloaded they'll need to have their folders manually renamed
> 
> 1. Movies
> 2. Movie Editor
> 3. Select what movies need their folder renamed
> 4. Change Root Folder to the same Root Folder that the movies currently exist in
> 5. Select "Yes move files"
> 
> https://wiki.servarr.com/radarr/faq#how-can-i-rename-my-movie-folders

I've done that in the past.  I feel that radarr shouldn't be automatically changing folders AFTER import, but I want radarr to update what the folder WOULD BE when import occurs in the event the current folder doesn't exist.

**Comment by austinwbest** [comment] 2022-05-31 19:45
> I've done that in the past. I feel that radarr shouldn't be automatically changing folders AFTER import, but I want radarr to update what the folder WOULD BE when import occurs in the event the current folder doesn't exist.

Seems fair and am inclined to agree, right a long the lines of what i mentioned earlier in another conversation.

**Comment by herkalurk** [comment] 2022-06-02 18:51
Should I report a bug about the Home Alone import then?  Unfortunately that import occurred months ago, so I don't have logs and I'm unsure the next time this would occur.  Or could you re-open this so that it's actually considered in your long term plans for development.

**Comment by austinwbest** [comment] 2022-06-02 22:06
> Should I report a bug about the Home Alone import then?  Unfortunately that import occurred months ago, so I don't have logs and I'm unsure the next time this would occur.  Or could you re-open this so that it's actually considered in your long term plans for development.

Well Q said it isn't a planned change as of now so it can be reopened if he changes his mind bud.
