### ISSUE TITLE
"Downloaded" information disappears when sorting by it in table view

### ISSUE THREAD

**Issue by hanzoh** [Radarr/Radarr#2507] opened 2018-02-11 12:42 UTC
**Description:**
When sorting by "Downloaded" column in table view, the information disappears.
Sorting by any other column shows the values in the "Downloaded" column correctly.

Also, when sorting by any column other than "Downloaded", it shows I have 568 movies in the library.
When I sort by "Downloaded", this values changes to 554.

**Radarr Version:** 0.2.0.935
**Mono Version:** 5.8.0.108

**Comment by gregcbrown** [comment] 2018-02-11 13:04
Ditto here, I go from 252 to 211 when sorted by download, and the downloaded column is blank.

**Comment by gregcbrown** [comment] 2018-02-11 13:07
update... If I switch to a different tab, like system, and switch back, the downloaded info reappears even though it is still sorted by downloaded...

**Comment by galli-leo** [comment] 2018-02-11 16:08
Duplicate of #2195

**Closed by galli-leo** 2018-02-11 16:08 UTC
